module

/-
CubicRing19.lean — own work for the Fermat project.

# `ℤ[θ] = ℤ[X]/(X³ + 2X² + 4X + 2)`, its ring of integers, and its units mod squares

This module is the level-`19` twin of the `Cubic.ZS` development inside
`Fermat/FLT/EllipticCurve/MordellWeil.lean` (lines `659`–`1852` there, the
`MazurLevel11` section).  It exists to close the single remaining leaf of level
`19`, `MazurX0Nineteen.descent_unit_square` in
`Fermat/FLT/EllipticCurve/MordellWeil19.lean`: the `2`-descent on

    19a3 :  W² = U³ + 4U² + 16U + 16        (monic model of `y² + y = x³ + x² + x`)

runs in the cubic ring `ℤ[θ]`, `θ³ + 2θ² + 4θ + 2 = 0`, because `U = 2θ` is a root
of the right-hand side and the descent image of the coprime integral point
`U = p/e²` is `β = p − 2θe²`.

It is a SEPARATE module rather than more of `MordellWeil19.lean` because that
file already carries a `decide +kernel` quadratic-residue sieve over `26427`
cells and costs `135 s` to elaborate; nothing here depends on anything there, so
the two elaborate independently.

## WHAT IS PROVEN HERE, AND WHERE IT DIFFERS FROM LEVEL `11`

Everything, with no `sorry`.  The architecture is the level-`11` one, transcribed
with different constants:

* `ZS` is a `structure` on three integer coordinates whose multiplication is
  `MazurX0Nineteen.zsMul` **definitionally**, so the bridge back to the
  coordinate statements is `rfl`;
* `IsDomain ZS` by an infinite `2`-adic descent on the norm form
  (`norm_eq_zero_aux`), the elementary substitute for irreducibility of the
  cubic;
* `K = ℚ(θ)` is realised as `FractionRing ZS`, which makes `ℤ[θ] ⊆ K` free by
  construction; `Basis.localizationLocalization` and
  `Algebra.discr_localizationLocalization` transport the `ℤ`-basis `1, θ, θ²` and
  its discriminant `−76`, computed from `Tr(a + bθ + cθ²) = 3a − 2b − 4c`;
* `𝓞_K = ℤ[θ]` (`isIntegralClosure_ZS`), by the discriminant multiplier `−76`,
  the Eisenstein-at-`2` descent stripping `2²`, and a hand argument at `19`;
* `h(K) = 1` (`isPrincipalIdealRing_zs`);
* the units modulo squares are `{±1, ±ε}`, `ε = θ + 1` (`unit_sq_class`);
* the valuation bookkeeping `descent_zs`, which is what
  `descent_unit_square` is assembled from.

**THE ONE PLACE THE LEVEL-`11` PROOF DOES NOT TRANSCRIBE, and it is the thing to
know before touching this file.**  Level `11` gets `h(K) = 1` from
`RingOfIntegers.isPrincipalIdealRing_of_abs_discr_lt`, i.e. from "the Minkowski
bound is `< 2`, so every class contains an ideal of norm `1`".  That is
`|disc| = 44` against `(2·(π/4)·27/6)² ≈ 49.96`, and it is comfortable.  **It is
FALSE here**: `|disc| = 76 > 49.96`.  The Minkowski bound of `K` is

    (4/π) · (3!/3³) · √76 = 8√76 / (9π) ≈ 2.4666,

so a class may contain an ideal of norm `2`, and the class group is generated by
the primes above `2`.  What saves it is that `2` is TOTALLY RAMIFIED with a
principal prime above it: `θ³ = −2θ² − 4θ − 2 = −2(θ + 1)² = −2ε²` with `ε` a
unit, so `(2) = (θ)³` and the unique prime above `2` is `(θ)`, of norm `2`.

So the route here is the general one,
`RingOfIntegers.isPrincipalIdealRing_of_isPrincipal_of_pow_le_of_mem_primesOver_of_mem_Icc`:
compute `⌊M K⌋₊ = 2`, so the only prime to consider is `p = 2`; any `P` above `2`
contains `θ³`, hence `θ`, hence the maximal ideal `(θ)` (maximal because its
absolute norm `|N(θ)| = 2` is prime); and a prime ideal containing a maximal
ideal equals it.  That is `isPrincipalIdealRing_OKK` below, and it is the only
declaration in this file with no counterpart at level `11`.

## FIELD DATA (PARI/GP as an untrusted searcher; every number is re-derived in Lean)

`poldisc(X³ + 2X² + 4X + 2) = −76 = disc(K)` and `nfbasis` is `[1, θ, θ²]`, so the
index is `1` — but `−76 = −2²·19` is NOT squarefree, so "the discriminants agree,
hence index `1`" is a CONCLUSION and not an input: the polynomial IS Eisenstein at
`2`, which kills the `2`-part, and `19` is killed separately, by the trace form
together with `N(7 − θ + θ²) = 361 = 19²`.

`h(K) = 1`; signature `(1, 1)`; unit rank `1`, torsion `{±1}`, fundamental unit
`ε = θ + 1` of norm `+1` (the Lean-side witness that it is a unit is
`ε·(θ² + θ + 3) = 1`).

**THE UNIT OBSTRUCTION.**  `N(ε) = +1` here, where level `11` has `N(ε) = −1`,
and in NEITHER case does the norm force the exponent parity — that inference is
recorded as invalid in `MordellWeil.lean`'s own section docstring.  What is
needed is a quadratic-residue obstruction at a degree-one prime, and level `19`
has one at `q = 29`: `X³ + 2X² + 4X + 2 ≡ 0 (mod 29)` at `θ ↦ 18` (and `18² ≡ 5`),
so `φ(a + bθ + cθ²) = a + 18b + 5c` is a ring map to `𝔽₂₉`, `φ(ε) = 19`, and
neither `19` nor `−19 = 10` is a square mod `29`.  Because `N(ε) = +1` the norm
excludes NEITHER sign here, so — unlike level `11`, where only the `−` case needed
it — `φ` does both cases.  (`q ≡ 1 mod 4` is what makes `−1` a square, so one
non-residue check settles both; `29, 37, 41, 53, 89` all work.)
-/

public import Fermat.FLT.EllipticCurve.MordellWeil

@[expose] public section

namespace MazurX0Nineteen

namespace Cubic19

/-- `ℤ[θ] = ℤ[X]/(X³ + 2X² + 4X + 2)`, as a structure on its coordinates in the
`ℤ`-basis `1, θ, θ²`: `⟨a, b, c⟩` denotes `a + bθ + cθ²`.

The multiplication defined below is `MazurX0Nineteen.zsMul` **definitionally**, so
the bridge to the coordinate statements of `MordellWeil19.lean` (`ofZS_mul`,
`ofZS_beta` there) is `rfl` and nothing is lost in translation.  Working with a
bespoke structure rather than `AdjoinRoot` buys exactly that: `decide` and `ring`
see the coordinates. -/
structure ZS where
  /-- The coefficient of `1`. -/
  a : ℤ
  /-- The coefficient of `θ`. -/
  b : ℤ
  /-- The coefficient of `θ²`. -/
  c : ℤ
deriving DecidableEq

namespace ZS

@[ext] theorem ext {x y : ZS} (ha : x.a = y.a) (hb : x.b = y.b) (hc : x.c = y.c) : x = y := by
  cases x; cases y; simp_all

instance : Zero ZS := ⟨⟨0, 0, 0⟩⟩
instance : One ZS := ⟨⟨1, 0, 0⟩⟩
instance : Add ZS := ⟨fun x y => ⟨x.a + y.a, x.b + y.b, x.c + y.c⟩⟩
instance : Neg ZS := ⟨fun x => ⟨-x.a, -x.b, -x.c⟩⟩
instance : Sub ZS := ⟨fun x y => ⟨x.a - y.a, x.b - y.b, x.c - y.c⟩⟩
instance : Mul ZS := ⟨fun x y =>
  ⟨x.a * y.a - 2 * (x.b * y.c + x.c * y.b) + 4 * (x.c * y.c),
   x.a * y.b + x.b * y.a - 4 * (x.b * y.c + x.c * y.b) + 6 * (x.c * y.c),
   x.a * y.c + x.b * y.b + x.c * y.a - 2 * (x.b * y.c + x.c * y.b)⟩⟩
instance : NatCast ZS := ⟨fun n => ⟨(n : ℤ), 0, 0⟩⟩
instance : IntCast ZS := ⟨fun k => ⟨k, 0, 0⟩⟩

@[simp] theorem zero_a : (0 : ZS).a = 0 := rfl
@[simp] theorem zero_b : (0 : ZS).b = 0 := rfl
@[simp] theorem zero_c : (0 : ZS).c = 0 := rfl
@[simp] theorem one_a : (1 : ZS).a = 1 := rfl
@[simp] theorem one_b : (1 : ZS).b = 0 := rfl
@[simp] theorem one_c : (1 : ZS).c = 0 := rfl
@[simp] theorem add_a (x y : ZS) : (x + y).a = x.a + y.a := rfl
@[simp] theorem add_b (x y : ZS) : (x + y).b = x.b + y.b := rfl
@[simp] theorem add_c (x y : ZS) : (x + y).c = x.c + y.c := rfl
@[simp] theorem neg_a (x : ZS) : (-x).a = -x.a := rfl
@[simp] theorem neg_b (x : ZS) : (-x).b = -x.b := rfl
@[simp] theorem neg_c (x : ZS) : (-x).c = -x.c := rfl
@[simp] theorem sub_a (x y : ZS) : (x - y).a = x.a - y.a := rfl
@[simp] theorem sub_b (x y : ZS) : (x - y).b = x.b - y.b := rfl
@[simp] theorem sub_c (x y : ZS) : (x - y).c = x.c - y.c := rfl
@[simp] theorem mul_a (x y : ZS) :
    (x * y).a = x.a * y.a - 2 * (x.b * y.c + x.c * y.b) + 4 * (x.c * y.c) := rfl
@[simp] theorem mul_b (x y : ZS) :
    (x * y).b = x.a * y.b + x.b * y.a - 4 * (x.b * y.c + x.c * y.b) + 6 * (x.c * y.c) := rfl
@[simp] theorem mul_c (x y : ZS) :
    (x * y).c = x.a * y.c + x.b * y.b + x.c * y.a - 2 * (x.b * y.c + x.c * y.b) := rfl
@[simp] theorem natCast_a (n : ℕ) : ((n : ZS)).a = (n : ℤ) := rfl
@[simp] theorem natCast_b (n : ℕ) : ((n : ZS)).b = 0 := rfl
@[simp] theorem natCast_c (n : ℕ) : ((n : ZS)).c = 0 := rfl
@[simp] theorem intCast_a (k : ℤ) : ((k : ZS)).a = k := rfl
@[simp] theorem intCast_b (k : ℤ) : ((k : ZS)).b = 0 := rfl
@[simp] theorem intCast_c (k : ℤ) : ((k : ZS)).c = 0 := rfl

instance instCommRing : CommRing ZS where
  nsmul := nsmulRec
  zsmul := zsmulRec
  add_assoc := by intros; ext <;> simp <;> ring
  zero_add := by intros; ext <;> simp
  add_zero := by intros; ext <;> simp
  add_comm := by intros; ext <;> simp <;> ring
  left_distrib := by intros; ext <;> simp <;> ring
  right_distrib := by intros; ext <;> simp <;> ring
  zero_mul := by intros; ext <;> simp
  mul_zero := by intros; ext <;> simp
  mul_assoc := by intros; ext <;> simp <;> ring
  one_mul := by intros; ext <;> simp
  mul_one := by intros; ext <;> simp
  neg_add_cancel := by intros; ext <;> simp
  mul_comm := by intros; ext <;> simp <;> ring
  sub_eq_add_neg := by intros; ext <;> simp <;> ring
  natCast_zero := by ext <;> simp
  natCast_succ := by intros; ext <;> simp
  intCast_ofNat := by intros; ext <;> simp
  intCast_negSucc := by intros; ext <;> simp [Int.negSucc_eq]

/-- The field norm `N : ℤ[θ] → ℤ`, the determinant of multiplication-by-`x` in the
basis `1, θ, θ²`.  Agrees with `MazurX0Nineteen.zsNorm` on coordinates by
construction. -/
def N (x : ZS) : ℤ :=
  x.a ^ 3 - 2 * x.a ^ 2 * x.b - 4 * x.a ^ 2 * x.c + 4 * x.a * x.b ^ 2
    - 2 * x.a * x.b * x.c + 8 * x.a * x.c ^ 2 - 2 * x.b ^ 3
    + 4 * x.b ^ 2 * x.c - 8 * x.b * x.c ^ 2 + 4 * x.c ^ 3

@[simp] theorem N_one : N 1 = 1 := by simp [N]

/-- `N` is multiplicative (PROVEN): the same `ring` check as `zsNorm_zsMul`. -/
theorem N_mul (x y : ZS) : N (x * y) = N x * N y := by simp only [N, mul_a, mul_b, mul_c]; ring

/-- The adjugate `x'·x''` (the product of the two conjugates), in coordinates:
the first column of the adjugate of the multiplication matrix. -/
def adj (x : ZS) : ZS :=
  ⟨x.a ^ 2 - 2 * x.a * x.b - 4 * x.a * x.c + 4 * x.b ^ 2 - 6 * x.b * x.c + 12 * x.c ^ 2,
   -(x.a * x.b) + 2 * x.b ^ 2 - 4 * x.b * x.c + 6 * x.c ^ 2,
   -(x.a * x.c) + x.b ^ 2 - 2 * x.b * x.c + 4 * x.c ^ 2⟩

/-- **`x` divides its own norm** (PROVEN), with the explicit cofactor.  This is
what makes `N x = ±1 → IsUnit x` elementary. -/
theorem mul_adj (x : ZS) : x * adj x = ((N x : ℤ) : ZS) := by
  ext <;> simp only [mul_a, mul_b, mul_c, intCast_a, intCast_b, intCast_c, adj, N] <;> ring

/-- **The norm form has no nontrivial integral zero** (PROVEN), by infinite descent
at `2`.  If `N(a, b, c) = 0` then `a` is even (every other term of `N` is);
substituting, `b` is even; substituting again, `c` is even; and `N` is homogeneous
of degree `3`, so `(a/2, b/2, c/2)` is a strictly smaller zero.

This is the elementary stand-in for "`X³ + 2X² + 4X + 2` is irreducible over `ℚ`",
and it is what makes `ℤ[θ]` an integral domain. -/
theorem norm_eq_zero_aux : ∀ n : ℕ, ∀ a b c : ℤ, a.natAbs + b.natAbs + c.natAbs ≤ n →
    a ^ 3 - 2 * a ^ 2 * b - 4 * a ^ 2 * c + 4 * a * b ^ 2 - 2 * a * b * c + 8 * a * c ^ 2
      - 2 * b ^ 3 + 4 * b ^ 2 * c - 8 * b * c ^ 2 + 4 * c ^ 3 = 0 → a = 0 ∧ b = 0 ∧ c = 0 := by
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro a b c hn hN
    by_cases hz : a = 0 ∧ b = 0 ∧ c = 0
    · exact hz
    exfalso
    obtain ⟨a1, rfl⟩ : (2 : ℤ) ∣ a := by
      refine Int.prime_two.dvd_of_dvd_pow (n := 3) ⟨a ^ 2 * b + 2 * a ^ 2 * c - 2 * a * b ^ 2
        + a * b * c - 4 * a * c ^ 2 + b ^ 3 - 2 * b ^ 2 * c + 4 * b * c ^ 2 - 2 * c ^ 3,
        by linear_combination hN⟩
    obtain ⟨b1, rfl⟩ : (2 : ℤ) ∣ b := by
      have h2 : 2 * (b ^ 3 - 2 * (2 * a1 ^ 3 - 2 * a1 ^ 2 * b - 4 * a1 ^ 2 * c + 2 * a1 * b ^ 2
          - a1 * b * c + 4 * a1 * c ^ 2 + b ^ 2 * c - 2 * b * c ^ 2 + c ^ 3)) = 0 := by
        linear_combination -hN
      have h3 : b ^ 3 = 2 * (2 * a1 ^ 3 - 2 * a1 ^ 2 * b - 4 * a1 ^ 2 * c + 2 * a1 * b ^ 2
          - a1 * b * c + 4 * a1 * c ^ 2 + b ^ 2 * c - 2 * b * c ^ 2 + c ^ 3) := by linarith
      exact Int.prime_two.dvd_of_dvd_pow (n := 3) ⟨_, h3⟩
    obtain ⟨c1, rfl⟩ : (2 : ℤ) ∣ c := by
      have h2 : 4 * (c ^ 3 - 2 * (-(a1 ^ 3) + 2 * a1 ^ 2 * b1 + 2 * a1 ^ 2 * c
          - 4 * a1 * b1 ^ 2 + a1 * b1 * c - 2 * a1 * c ^ 2 + 2 * b1 ^ 3 - 2 * b1 ^ 2 * c
          + 2 * b1 * c ^ 2)) = 0 := by
        linear_combination hN
      have h3 : c ^ 3 = 2 * (-(a1 ^ 3) + 2 * a1 ^ 2 * b1 + 2 * a1 ^ 2 * c
          - 4 * a1 * b1 ^ 2 + a1 * b1 * c - 2 * a1 * c ^ 2 + 2 * b1 ^ 3 - 2 * b1 ^ 2 * c
          + 2 * b1 * c ^ 2) := by linarith
      exact Int.prime_two.dvd_of_dvd_pow (n := 3) ⟨_, h3⟩
    have hN1 : a1 ^ 3 - 2 * a1 ^ 2 * b1 - 4 * a1 ^ 2 * c1 + 4 * a1 * b1 ^ 2 - 2 * a1 * b1 * c1
        + 8 * a1 * c1 ^ 2 - 2 * b1 ^ 3 + 4 * b1 ^ 2 * c1 - 8 * b1 * c1 ^ 2 + 4 * c1 ^ 3 = 0 := by
      have h8 : (8 : ℤ) * (a1 ^ 3 - 2 * a1 ^ 2 * b1 - 4 * a1 ^ 2 * c1 + 4 * a1 * b1 ^ 2
          - 2 * a1 * b1 * c1 + 8 * a1 * c1 ^ 2 - 2 * b1 ^ 3 + 4 * b1 ^ 2 * c1 - 8 * b1 * c1 ^ 2
          + 4 * c1 ^ 3) = 8 * 0 := by
        linear_combination hN
      linarith
    have habs : (2 * a1).natAbs + (2 * b1).natAbs + (2 * c1).natAbs
        = 2 * (a1.natAbs + b1.natAbs + c1.natAbs) := by
      simp [Int.natAbs_mul]; ring
    have hpos : 0 < a1.natAbs + b1.natAbs + c1.natAbs := by
      rcases Nat.eq_zero_or_pos (a1.natAbs + b1.natAbs + c1.natAbs) with h | h
      · exact absurd ⟨by omega, by omega, by omega⟩ hz
      · exact h
    exact hz (by
      have := ih (a1.natAbs + b1.natAbs + c1.natAbs) (by omega) a1 b1 c1 le_rfl hN1
      exact ⟨by omega, by omega, by omega⟩)

/-- `N x = 0 → x = 0` (PROVEN), the element-level form of `norm_eq_zero_aux`. -/
theorem norm_eq_zero {x : ZS} (h : N x = 0) : x = 0 := by
  obtain ⟨a, b, c⟩ := x
  obtain ⟨h1, h2, h3⟩ := norm_eq_zero_aux (a.natAbs + b.natAbs + c.natAbs) a b c le_rfl
    (by simpa [N] using h)
  subst h1; subst h2; subst h3; rfl

instance : Nontrivial ZS := ⟨⟨0, 1, by intro h; simpa using congrArg ZS.a h⟩⟩

instance : NoZeroDivisors ZS :=
  ⟨fun {x y} h => by
    have hz : N x * N y = 0 := by rw [← N_mul, h]; simp [N]
    rcases mul_eq_zero.mp hz with h1 | h1
    · exact Or.inl (norm_eq_zero h1)
    · exact Or.inr (norm_eq_zero h1)⟩

instance : IsDomain ZS := NoZeroDivisors.to_isDomain ZS

theorem unit_of_mul_eq_one {x y : ZS} (h : x * y = 1) : IsUnit x :=
  isUnit_iff_exists.mpr ⟨y, h, by rw [mul_comm]; exact h⟩

/-- **`N x = ±1 → IsUnit x`** (PROVEN), via `mul_adj`. -/
theorem isUnit_of_norm_isUnit {x : ZS} (h : IsUnit (N x)) : IsUnit x := by
  rcases Int.isUnit_iff.mp h with h1 | h1
  · exact unit_of_mul_eq_one (y := adj x) (by rw [mul_adj, h1]; rfl)
  · exact unit_of_mul_eq_one (y := -adj x) (by rw [mul_neg, mul_adj, h1]; ext <;> simp)

/-- **`IsUnit x → N x = ±1`** (PROVEN), by multiplicativity. -/
theorem norm_isUnit_of_isUnit {x : ZS} (h : IsUnit x) : IsUnit (N x) := by
  obtain ⟨y, hy⟩ := h.exists_right_inv
  exact isUnit_iff_exists.mpr
    ⟨N y, by rw [← N_mul, hy, N_one], by rw [← N_mul, mul_comm, hy, N_one]⟩

/-- `θ`, of norm `−2`; `(2) = (θ)³` is totally ramified. -/
def sEl : ZS := ⟨0, 1, 0⟩
/-- `g = θ + 3`, of norm `19`: a generator of the prime over `19` that meets `D`. -/
def gEl : ZS := ⟨3, 1, 0⟩
/-- `ε = θ + 1`, the fundamental unit, of norm `+1`. -/
def epsEl : ZS := ⟨1, 1, 0⟩
/-- The unit `D/(θ⁸·g) = 191 + 83θ + 61θ²`, of norm `1`. -/
def uD : ZS := ⟨191, 83, 61⟩
/-- `D = 16 + 16θ + 12θ²`, of norm `4864 = 2⁸·19`. -/
def DEl : ZS := ⟨16, 16, 12⟩
/-- `β = p − 2θ·e²`, the descent image. -/
def beta (p e : ℤ) : ZS := ⟨p, -2 * e ^ 2, 0⟩
/-- `γ = adj β = p² + 4pe² + 16e⁴ + (2pe² + 8e⁴)θ + 4e⁴θ²`: `β·γ = n²`. -/
def gammaEl (p e : ℤ) : ZS :=
  ⟨p ^ 2 + 4 * p * e ^ 2 + 16 * e ^ 4, 2 * p * e ^ 2 + 8 * e ^ 4, 4 * e ^ 4⟩
/-- `Q = p + 4e² + 4e²θ`, the quotient in the exact division `γ = Q·β + D·e⁴`. -/
def QEl (p e : ℤ) : ZS := ⟨p + 4 * e ^ 2, 4 * e ^ 2, 0⟩

theorem beta_eq (p e : ℤ) : beta p e = ((p : ℤ) : ZS) - ((2 * e ^ 2 : ℤ) : ZS) * sEl := by
  ext <;> simp only [beta, sEl, sub_a, sub_b, sub_c, mul_a, mul_b, mul_c,
    intCast_a, intCast_b, intCast_c] <;> ring

/-- **`β·γ = n²` on the curve** (PROVEN): the ring-level form of the factorisation
`U³ + 4U² + 16U + 16 = (U − 2θ)(U² + (2θ + 4)U + 4θ² + 8θ + 16)`. -/
theorem beta_mul_gamma (p e n : ℤ)
    (hn : p ^ 3 + 4 * p ^ 2 * e ^ 2 + 16 * p * e ^ 4 + 16 * e ^ 6 = n ^ 2) :
    beta p e * gammaEl p e = ((n ^ 2 : ℤ) : ZS) := by
  ext
  · simp only [mul_a, beta, gammaEl, intCast_a]; linear_combination hn
  · simp only [mul_b, beta, gammaEl, intCast_b]; ring
  · simp only [mul_c, beta, gammaEl, intCast_c]; ring

/-- **The exact division of `γ` by `β`** (PROVEN, a pure `ring` identity): this is
what bounds `gcd(β, γ)` by `D·e⁴`. -/
theorem gamma_eq (p e : ℤ) :
    gammaEl p e = QEl p e * beta p e + DEl * ((e ^ 4 : ℤ) : ZS) := by
  ext <;> simp only [gammaEl, QEl, beta, DEl, add_a, add_b, add_c, mul_a, mul_b, mul_c,
    intCast_a, intCast_b, intCast_c] <;> ring

/-- **`D = uD·θ⁸·g`** (PROVEN by `decide`): the point of the norm `4864 = 2⁸·19` is
that the only primes involved are `θ` and `g`. -/
theorem D_eq : DEl = uD * sEl ^ 8 * gEl := by decide

/-- An element of prime norm is irreducible (PROVEN). -/
theorem irreducible_of_prime_norm {x : ZS} (h : Prime (N x)) : Irreducible x := by
  refine ⟨fun hu => h.not_unit (norm_isUnit_of_isUnit hu), fun {y z} hyz => ?_⟩
  have hN : N x = N y * N z := by rw [hyz, N_mul]
  rcases h.irreducible.isUnit_or_isUnit hN with h1 | h1
  · exact Or.inl (isUnit_of_norm_isUnit h1)
  · exact Or.inr (isUnit_of_norm_isUnit h1)

/-- `θ` is irreducible (PROVEN): `N(θ) = −2`. -/
theorem irreducible_sEl : Irreducible sEl :=
  irreducible_of_prime_norm
    (by show Prime (-2 : ℤ); exact Int.prime_iff_natAbs_prime.mpr (by decide))

/-- `g = θ + 3` is irreducible (PROVEN): `N(g) = 19`. -/
theorem irreducible_gEl : Irreducible gEl :=
  irreducible_of_prime_norm
    (by show Prime (19 : ℤ); exact Int.prime_iff_natAbs_prime.mpr (by decide))

/-- `uD` is a unit (PROVEN): `N(uD) = 1`. -/
theorem isUnit_uD : IsUnit uD := isUnit_of_norm_isUnit (by decide)

section RingOfIntegers

open scoped NumberField
open _root_.Module

/-! ## Coordinate scaffolding -/

@[simp] theorem zsmul_a (m : ℤ) (x : ZS) : (m • x).a = m * x.a := by
  rw [zsmul_eq_mul]; simp
@[simp] theorem zsmul_b (m : ℤ) (x : ZS) : (m • x).b = m * x.b := by
  rw [zsmul_eq_mul]; simp
@[simp] theorem zsmul_c (m : ℤ) (x : ZS) : (m • x).c = m * x.c := by
  rw [zsmul_eq_mul]; simp

theorem sEl_pow_two : sEl ^ 2 = ⟨0, 0, 1⟩ := by decide
theorem sEl_pow_three : sEl ^ 3 = ⟨-2, -4, -2⟩ := by decide
theorem sEl_pow_four : sEl ^ 4 = ⟨4, 6, 0⟩ := by decide

instance : CharZero ZS := ⟨fun m n h => by
  have := congrArg ZS.a h
  simpa using this⟩

/-- The `ℤ`-linear coordinate isomorphism `ℤ[θ] ≃ ℤ³`. -/
def coordEquiv : ZS ≃ₗ[ℤ] (Fin 3 → ℤ) where
  toFun x := ![x.a, x.b, x.c]
  invFun v := ⟨v 0, v 1, v 2⟩
  map_add' x y := by ext i; fin_cases i <;> simp
  map_smul' m x := by ext i; fin_cases i <;> simp
  left_inv x := by cases x; rfl
  right_inv v := by ext i; fin_cases i <;> simp

/-- The `ℤ`-basis `1, θ, θ²` of `ℤ[θ]`. -/
noncomputable def basisZS : Basis (Fin 3) ℤ ZS := Basis.ofEquivFun coordEquiv

@[simp] theorem basisZS_repr (x : ZS) (i : Fin 3) :
    basisZS.repr x i = ![x.a, x.b, x.c] i :=
  Basis.ofEquivFun_repr_apply coordEquiv x i

theorem basisZS_apply (i : Fin 3) : basisZS i = sEl ^ (i : ℕ) := by
  refine (Basis.apply_eq_iff (b := basisZS)).mpr ?_
  ext j
  fin_cases i <;> fin_cases j <;>
    simp <;> decide

theorem basisZS_zero : basisZS 0 = ⟨1, 0, 0⟩ := by rw [basisZS_apply]; decide
theorem basisZS_one : basisZS 1 = ⟨0, 1, 0⟩ := by rw [basisZS_apply]; decide
theorem basisZS_two : basisZS 2 = ⟨0, 0, 1⟩ := by rw [basisZS_apply]; decide

/-! ## The trace and discriminant of `ℤ[θ]` over `ℤ` -/

instance : Module.Finite ℤ ZS := Module.Finite.of_basis basisZS
instance : Module.Free ℤ ZS := Module.Free.of_basis basisZS

theorem trace_eq (x : ZS) : Algebra.trace ℤ ZS x = 3 * x.a - 2 * x.b - 4 * x.c := by
  classical
  rw [Algebra.trace_eq_matrix_trace basisZS]
  simp only [Matrix.trace, Matrix.diag_apply, Fin.sum_univ_three,
    Algebra.leftMulMatrix_eq_repr_mul, basisZS_repr, basisZS_zero, basisZS_one, basisZS_two,
    Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
    Matrix.cons_val_two, Matrix.tail_cons, mul_a, mul_b, mul_c]
  ring

theorem discr_basisZS : Algebra.discr ℤ basisZS = -76 := by
  classical
  rw [Algebra.discr_def, Matrix.det_fin_three]
  simp only [Algebra.traceMatrix_apply, Algebra.traceForm_apply, trace_eq,
    basisZS_zero, basisZS_one, basisZS_two, mul_a, mul_b, mul_c]
  norm_num

/-! ## The cubic field `K = ℚ(θ)` -/

/-- The cubic field `K = ℚ(θ)`, realised as the fraction field of `ℤ[θ]`.

This is a `def`, not an `abbrev`, on purpose, for the reason recorded at the
level-`11` twin: `FractionRing` carries both an `OreLocalization`-flavoured
`CommRing`/`Algebra ℤ` structure and the one coming from its `Field` instance,
and although the two are definitionally equal they are never syntactically equal,
so mathlib's `𝓞 K` API does not match a goal elaborated through the
`OreLocalization` path. -/
def KK : Type := FractionRing ZS

noncomputable instance instFieldKK : Field KK := inferInstanceAs (Field (FractionRing ZS))
noncomputable instance instAlgZSKK : Algebra ZS KK := inferInstanceAs (Algebra ZS (FractionRing ZS))
instance instIFRKK : IsFractionRing ZS KK := inferInstanceAs (IsFractionRing ZS (FractionRing ZS))

instance instSTZSKK : IsScalarTower ℤ ZS KK :=
  IsScalarTower.of_algebraMap_eq fun n => by simp [eq_intCast]

instance instCZKK : CharZero KK :=
  charZero_of_injective_algebraMap (IsFractionRing.injective ZS KK)

theorem algebraMap_ne_zero {x : ZS} (hx : x ≠ 0) : algebraMap ZS KK x ≠ 0 :=
  fun h => hx (IsFractionRing.injective ZS KK (by rw [map_zero]; exact h))

instance isLocalization_KK :
    IsLocalization (Algebra.algebraMapSubmonoid ZS (nonZeroDivisors ℤ)) KK := by
  rw [isLocalization_iff]
  refine ⟨?_, ?_, ?_⟩
  · rintro ⟨y, m, hm, rfl⟩
    have hm0 : m ≠ 0 := nonZeroDivisors.coe_ne_zero ⟨m, hm⟩
    refine isUnit_iff_ne_zero.mpr (algebraMap_ne_zero fun h => hm0 ?_)
    have h2 := congrArg ZS.a h
    simpa [eq_intCast] using h2
  · intro z
    obtain ⟨⟨x, s, hs⟩, hxs⟩ := IsLocalization.surj (nonZeroDivisors ZS) z
    have hs0 : s ≠ 0 := nonZeroDivisors.coe_ne_zero ⟨s, hs⟩
    have hN : N s ≠ 0 := fun h => hs0 (norm_eq_zero h)
    refine ⟨⟨x * adj s, ⟨algebraMap ℤ ZS (N s), ⟨N s, ?_, rfl⟩⟩⟩, ?_⟩
    · simpa using hN
    · have hms : (algebraMap ℤ ZS (N s)) = s * adj s := (mul_adj s).symm
      simp only [hms, map_mul, ← mul_assoc]
      rw [hxs]
  · intro x y h
    exact ⟨1, by rw [IsFractionRing.injective ZS KK h]⟩

instance instSTQ : @IsScalarTower ℤ ℚ KK Algebra.toSMul Algebra.toSMul Algebra.toSMul :=
  IsScalarTower.of_algebraMap_eq fun n => by
    simp [eq_intCast, map_intCast]

/-- The `ℚ`-basis `1, θ, θ²` of `K`. -/
noncomputable def basisKK : Basis (Fin 3) ℚ KK :=
  basisZS.localizationLocalization ℚ (nonZeroDivisors ℤ) KK

theorem discr_basisKK : Algebra.discr ℚ basisKK = -76 := by
  rw [basisKK, Algebra.discr_localizationLocalization ℤ (nonZeroDivisors ℤ) KK basisZS,
    discr_basisZS]
  norm_num

/-- The generator `θ ∈ K`. -/
noncomputable def thetaK : KK := algebraMap ZS KK sEl

theorem basisKK_apply (i : Fin 3) : basisKK i = thetaK ^ (i : ℕ) := by
  rw [basisKK, Basis.localizationLocalization_apply, basisZS_apply, thetaK, map_pow]

/-- The power basis `1, θ, θ²` of `K` over `ℚ`. -/
noncomputable def pbKK : PowerBasis ℚ KK where
  gen := thetaK
  dim := 3
  basis := basisKK
  basis_eq_pow := basisKK_apply

instance : FiniteDimensional ℚ KK := Module.Finite.of_basis basisKK

instance : NumberField KK where
  to_charZero := inferInstance
  to_finiteDimensional := inferInstance

theorem finrank_KK : Module.finrank ℚ KK = 3 := by
  rw [Module.finrank_eq_card_basis basisKK]; simp

/-! ## The minimal polynomial `X³ + 2X² + 4X + 2`, Eisenstein at `2` -/

/-- `X³ + 2X² + 4X + 2 ∈ ℤ[X]`. -/
noncomputable def minPolyZ : Polynomial ℤ :=
  Polynomial.X ^ 3 + Polynomial.C 2 * Polynomial.X ^ 2 + Polynomial.C 4 * Polynomial.X
    + Polynomial.C 2

theorem minPolyZ_monic : minPolyZ.Monic := by
  unfold minPolyZ; monicity!

theorem minPolyZ_natDegree : minPolyZ.natDegree = 3 := by
  unfold minPolyZ; compute_degree!

@[simp] theorem minPolyZ_coeff_zero : minPolyZ.coeff 0 = 2 := by simp [minPolyZ]
@[simp] theorem minPolyZ_coeff_one : minPolyZ.coeff 1 = 4 := by simp [minPolyZ]
@[simp] theorem minPolyZ_coeff_two : minPolyZ.coeff 2 = 2 := by
  simp [minPolyZ, Polynomial.coeff_X]

theorem minPolyZ_eisenstein :
    minPolyZ.IsEisensteinAt (Submodule.span ℤ {(2 : ℤ)}) where
  leading := by
    rw [minPolyZ_monic.leadingCoeff, ← Ideal.span, Ideal.mem_span_singleton]
    decide
  mem := by
    intro n hn
    rw [minPolyZ_natDegree] at hn
    rw [← Ideal.span, Ideal.mem_span_singleton]
    interval_cases n <;> simp
  notMem := by
    rw [minPolyZ_coeff_zero, ← Ideal.span, Ideal.span_singleton_pow,
      Ideal.mem_span_singleton]
    decide

theorem sEl_relation : sEl ^ 3 + 2 * sEl ^ 2 + 4 * sEl + 2 = 0 := by decide

theorem aeval_thetaK : Polynomial.aeval thetaK minPolyZ = 0 := by
  have h : (Polynomial.aeval sEl) minPolyZ = 0 := by
    simp only [minPolyZ, map_add, map_mul, map_pow, Polynomial.aeval_X,
      Polynomial.aeval_C]
    simpa using sEl_relation
  have hth : thetaK = algebraMap ZS KK sEl := rfl
  rw [hth, Polynomial.aeval_algebraMap_apply, h, map_zero]

theorem isIntegral_thetaK : IsIntegral ℤ thetaK := ⟨minPolyZ, minPolyZ_monic, by
  simpa [Polynomial.aeval_def] using aeval_thetaK⟩

theorem minPolyZ_irreducible : Irreducible minPolyZ :=
  minPolyZ_eisenstein.irreducible
    (Ideal.span_singleton_prime (by decide) |>.mpr Int.prime_two)
    minPolyZ_monic.isPrimitive (by rw [minPolyZ_natDegree]; decide)

theorem minpoly_rat_thetaK : minpoly ℚ thetaK = minPolyZ.map (algebraMap ℤ ℚ) := by
  refine (minpoly.eq_of_irreducible_of_monic ?_ ?_ (minPolyZ_monic.map _)).symm
  · exact (Polynomial.IsPrimitive.Int.irreducible_iff_irreducible_map_cast
      minPolyZ_monic.isPrimitive).mp minPolyZ_irreducible
  · rw [Polynomial.aeval_map_algebraMap]
    exact aeval_thetaK

theorem minpoly_int_thetaK : minpoly ℤ thetaK = minPolyZ := by
  have h := minpoly.isIntegrallyClosed_eq_field_fractions' (K := ℚ) (S := KK)
    isIntegral_thetaK
  rw [minpoly_rat_thetaK] at h
  exact (Polynomial.map_injective (algebraMap ℤ ℚ) (algebraMap ℤ ℚ).injective_int h.symm)

theorem minpoly_eisenstein :
    (minpoly ℤ thetaK).IsEisensteinAt (Submodule.span ℤ {(2 : ℤ)}) := by
  rw [minpoly_int_thetaK]; exact minPolyZ_eisenstein

/-! ## `ℤ[θ]` as a subring of `K` -/

instance : Algebra.IsIntegral ℤ ZS := Algebra.IsIntegral.of_finite ℤ ZS

theorem isIntegral_algebraMap_ZS (u : ZS) : IsIntegral ℤ (algebraMap ZS KK u) :=
  (Algebra.IsIntegral.isIntegral (R := ℤ) u).map (IsScalarTower.toAlgHom ℤ ZS KK)

theorem eq_intCast_add (x : ZS) :
    x = (x.a : ZS) + (x.b : ZS) * sEl + (x.c : ZS) * sEl ^ 2 := by
  rw [sEl_pow_two]; ext <;> simp [sEl]

theorem algebraMap_eq (x : ZS) :
    algebraMap ZS KK x = (x.a : KK) + (x.b : KK) * thetaK + (x.c : KK) * thetaK ^ 2 := by
  conv_lhs => rw [eq_intCast_add x]
  simp only [map_add, map_mul, map_pow, map_intCast, thetaK]

theorem mem_adjoin_thetaK_iff {z : KK} :
    z ∈ Algebra.adjoin ℤ ({thetaK} : Set KK) ↔ ∃ y : ZS, algebraMap ZS KK y = z := by
  constructor
  · intro hz
    have hle : Algebra.adjoin ℤ ({thetaK} : Set KK) ≤
        (IsScalarTower.toAlgHom ℤ ZS KK).range := by
      refine Algebra.adjoin_le ?_
      rintro _ rfl
      exact ⟨sEl, rfl⟩
    exact hle hz
  · rintro ⟨y, rfl⟩
    have hθ : thetaK ∈ Algebra.adjoin ℤ ({thetaK} : Set KK) :=
      Algebra.subset_adjoin rfl
    rw [algebraMap_eq]
    exact Subalgebra.add_mem _
      (Subalgebra.add_mem _ (Subalgebra.intCast_mem _ _)
        (Subalgebra.mul_mem _ (Subalgebra.intCast_mem _ _) hθ))
      (Subalgebra.mul_mem _ (Subalgebra.intCast_mem _ _) (Subalgebra.pow_mem _ hθ _))

/-! ## The discriminant multiplier and the Eisenstein descent at `2` -/

set_option backward.isDefEq.respectTransparency false in
theorem mul76_mem {z : KK} (hz : IsIntegral ℤ z) :
    (-76 : KK) * z ∈ Algebra.adjoin ℤ ({thetaK} : Set KK) := by
  have H := Algebra.discr_mul_isIntegral_mem_adjoin (R := ℤ) ℚ
    (B := pbKK) isIntegral_thetaK hz
  rw [Algebra.smul_def, show Algebra.discr ℚ pbKK.basis = -76 from discr_basisKK,
    show pbKK.gen = thetaK from rfl,
    show (algebraMap ℚ KK) (-76 : ℚ) = (-76 : KK) by simp] at H
  exact H

theorem isIntegral_intCast (m : ℤ) : IsIntegral ℤ ((m : ℤ) : KK) := by
  rw [show ((m : ℤ) : KK) = algebraMap ℤ KK m by simp]
  exact isIntegral_algebraMap

set_option backward.isDefEq.respectTransparency false in
theorem mul19_mem {z : KK} (hz : IsIntegral ℤ z) :
    (19 : KK) * z ∈ Algebra.adjoin ℤ ({thetaK} : Set KK) := by
  have h19 : IsIntegral ℤ ((-19 : KK) * z) := by
    have h1 : (-19 : KK) = ((-19 : ℤ) : KK) := by push_cast; ring
    rw [h1]
    exact (isIntegral_intCast (-19)).mul hz
  have hm : (-19 : KK) * z ∈ Algebra.adjoin ℤ ({pbKK.gen} : Set KK) := by
    refine mem_adjoin_of_smul_prime_pow_smul_of_minpoly_isEisensteinAt
      (B := pbKK) (n := 2) (p := (2 : ℤ)) Int.prime_two isIntegral_thetaK h19 ?_
      minpoly_eisenstein
    rw [Algebra.smul_def, show pbKK.gen = thetaK from rfl,
      show (algebraMap ℤ KK ((2 : ℤ) ^ 2)) * ((-19 : KK) * z) = (-76 : KK) * z by
        simp only [map_pow, map_ofNat]; ring]
    exact mul76_mem hz
  rw [show pbKK.gen = thetaK from rfl] at hm
  have hneg := Subalgebra.neg_mem _ hm
  rw [show -((-19 : KK) * z) = (19 : KK) * z by ring] at hneg
  exact hneg

/-! ## Trace and norm through the localization -/

theorem trace_algebraMap (w : ZS) :
    Algebra.trace ℚ KK (algebraMap ZS KK w) = ((Algebra.trace ℤ ZS w : ℤ) : ℚ) := by
  rw [Algebra.trace_localization ℤ (nonZeroDivisors ℤ)]; simp

theorem norm_algebraMap_ZS (w : ZS) :
    Algebra.norm ℚ (algebraMap ZS KK w) = ((Algebra.norm ℤ w : ℤ) : ℚ) := by
  rw [Algebra.norm_localization ℤ (nonZeroDivisors ℤ)]; simp

theorem norm_eq (x : ZS) : Algebra.norm ℤ x = N x := by
  classical
  rw [Algebra.norm_eq_matrix_det basisZS, Matrix.det_fin_three]
  simp only [Algebra.leftMulMatrix_eq_repr_mul, basisZS_repr, basisZS_zero, basisZS_one,
    basisZS_two, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
    Matrix.cons_val_two, Matrix.tail_cons, mul_a, mul_b, mul_c, N]
  ring

theorem nineteen_dvd_trace {z : KK} (hz : IsIntegral ℤ z) {x : ZS}
    (hx : algebraMap ZS KK x = (19 : KK) * z) (u : ZS) :
    (19 : ℤ) ∣ Algebra.trace ℤ ZS (x * u) := by
  have hint : IsIntegral ℤ (z * algebraMap ZS KK u) := hz.mul (isIntegral_algebraMap_ZS u)
  obtain ⟨m, hm⟩ := IsIntegrallyClosed.isIntegral_iff.mp (Algebra.isIntegral_trace
    (R := ℤ) (L := ℚ) (F := KK) hint)
  refine ⟨m, ?_⟩
  have key : ((Algebra.trace ℤ ZS (x * u) : ℤ) : ℚ) = 19 * ((m : ℤ) : ℚ) := by
    rw [← trace_algebraMap, map_mul, hx, mul_assoc,
      show ((19 : KK) * (z * algebraMap ZS KK u))
          = ((19 : ℚ) • (z * algebraMap ZS KK u)) by rw [Algebra.smul_def]; norm_num,
      map_smul, ← hm]
    simp
  exact_mod_cast key

/-! ## Killing the prime `19`: `𝓞_K = ℤ[θ]`

The trace conditions `19 ∣ Tr(x·θ^j)` for `j = 0, 1, 2` read

    3a − 2b − 4c ≡ 0,   −2a − 4b + 10c ≡ 0,   −4a + 10b ≡ 0   (mod 19),

whose solution space is the single `𝔽₁₉`-line `(a, b, c) ≡ c·(7, −1, 1)`.  So if
`𝓞_K ≠ ℤ[θ]` then `x₀/19 ∈ 𝓞_K` for `x₀ = 7 − θ + θ²`; but `N(x₀) = 361 = 19²`,
so `N(x₀/19) = 361/6859 ∉ ℤ`. -/

/-- `x₀ = 7 − θ + θ²`, of norm `361 = 19²`. -/
def x0El : ZS := ⟨7, -1, 1⟩

theorem N_x0El : N x0El = 361 := by decide

theorem exists_mem_ZS {z : KK} (hz : IsIntegral ℤ z) : ∃ y : ZS, algebraMap ZS KK y = z := by
  obtain ⟨x, hx⟩ := mem_adjoin_thetaK_iff.mp (mul19_mem hz)
  have h1 : (19 : ℤ) ∣ 3 * x.a - 2 * x.b - 4 * x.c := by
    have h := nineteen_dvd_trace hz hx 1
    rwa [mul_one, trace_eq] at h
  have h3 : (19 : ℤ) ∣ -4 * x.a + 10 * x.b := by
    have h := nineteen_dvd_trace hz hx ⟨0, 0, 1⟩
    rw [trace_eq] at h
    obtain ⟨k, hk⟩ := h
    simp only [mul_a, mul_b, mul_c] at hk
    exact ⟨k, by linarith⟩
  obtain ⟨p, hp⟩ : (19 : ℤ) ∣ x.a - 7 * x.c := by omega
  obtain ⟨q, hq⟩ : (19 : ℤ) ∣ x.b + x.c := by omega
  by_cases hc : (19 : ℤ) ∣ x.c
  · obtain ⟨r, hr⟩ := hc
    refine ⟨⟨7 * r + p, -r + q, r⟩, ?_⟩
    have hxeq : x = ((19 : ℤ) : ZS) * (⟨7 * r + p, -r + q, r⟩ : ZS) := by
      ext <;>
        simp only [mul_a, mul_b, mul_c, intCast_a, intCast_b, intCast_c] <;>
        ring_nf <;> omega
    have h19 : (19 : KK) * algebraMap ZS KK (⟨7 * r + p, -r + q, r⟩ : ZS) = 19 * z := by
      rw [← hx, hxeq, map_mul, map_intCast]
      norm_num
    exact mul_left_cancel₀ (by norm_num : (19 : KK) ≠ 0) h19
  · exfalso
    obtain ⟨t, k, ht⟩ : ∃ t k : ℤ, x.c * t = 1 + 19 * k := by
      have hgcd : Int.gcd 19 x.c = 1 := by
        have hg19 : Int.gcd 19 x.c ∣ 19 := Nat.gcd_dvd_left _ _
        rcases (by decide : Nat.Prime 19).eq_one_or_self_of_dvd _ hg19 with h | h
        · exact h
        · exact absurd (by
            have hd := Int.gcd_dvd_right (a := (19 : ℤ)) (b := x.c)
            rw [h] at hd; exact_mod_cast hd) hc
      obtain ⟨u, v, huv⟩ := Int.isCoprime_iff_gcd_eq_one.mpr hgcd
      exact ⟨v, -u, by linarith⟩
    have hxd : x = (x.c : ZS) * x0El + ((19 : ℤ) : ZS) * (⟨p, q, 0⟩ : ZS) := by
      ext <;>
        simp only [x0El, mul_a, mul_b, mul_c, add_a, add_b, add_c,
          intCast_a, intCast_b, intCast_c] <;>
        ring_nf <;> omega
    have hw : (19 : KK) * (z - algebraMap ZS KK (⟨p, q, 0⟩ : ZS))
        = (x.c : KK) * algebraMap ZS KK x0El := by
      have hxx := hx
      rw [hxd, map_add, map_mul, map_mul, map_intCast, map_intCast] at hxx
      push_cast at hxx ⊢
      linear_combination -hxx
    have hvint : IsIntegral ℤ ((t : KK) * (z - algebraMap ZS KK (⟨p, q, 0⟩ : ZS))
        - (k : KK) * algebraMap ZS KK x0El) :=
      ((isIntegral_intCast t).mul (hz.sub (isIntegral_algebraMap_ZS _))).sub
        ((isIntegral_intCast k).mul (isIntegral_algebraMap_ZS _))
    have hv : (19 : KK) * ((t : KK) * (z - algebraMap ZS KK (⟨p, q, 0⟩ : ZS))
        - (k : KK) * algebraMap ZS KK x0El) = algebraMap ZS KK x0El := by
      have hct : (x.c : KK) * (t : KK) = 1 + 19 * (k : KK) := by
        have : ((x.c * t : ℤ) : KK) = ((1 + 19 * k : ℤ) : KK) := by rw [ht]
        push_cast at this
        linear_combination this
      have h2 : (19 : KK) * ((t : KK) * (z - algebraMap ZS KK (⟨p, q, 0⟩ : ZS)))
          = ((x.c : KK) * (t : KK)) * algebraMap ZS KK x0El := by
        rw [show (19 : KK) * ((t : KK) * (z - algebraMap ZS KK (⟨p, q, 0⟩ : ZS)))
            = (t : KK) * ((19 : KK) * (z - algebraMap ZS KK (⟨p, q, 0⟩ : ZS))) by ring, hw]
        ring
      rw [hct] at h2
      linear_combination h2
    obtain ⟨n, hn⟩ := IsIntegrallyClosed.isIntegral_iff.mp
      (Algebra.isIntegral_norm (K := ℚ) hvint)
    have hnorm := congrArg (Algebra.norm ℚ) hv
    rw [map_mul, norm_algebraMap_ZS, norm_eq, N_x0El,
      show (19 : KK) = algebraMap ℚ KK 19 by simp, Algebra.norm_algebraMap,
      finrank_KK, ← hn] at hnorm
    rw [eq_intCast] at hnorm
    have hcast : ((6859 * n : ℤ) : ℚ) = ((361 : ℤ) : ℚ) := by
      push_cast; linear_combination hnorm
    have h6859 : (6859 : ℤ) * n = 361 := by exact_mod_cast hcast
    omega

/-! ## `ℤ[θ] = 𝓞_K`, the discriminant of `K`, and Minkowski -/

instance isIntegralClosure_ZS : IsIntegralClosure ZS ℤ KK where
  algebraMap_injective := IsFractionRing.injective ZS KK
  isIntegral_iff := fun {_} =>
    ⟨fun h => exists_mem_ZS h, fun ⟨y, hy⟩ => hy ▸ isIntegral_algebraMap_ZS y⟩

/-- **`𝓞_K = ℤ[θ]`**. -/
noncomputable def ringOfIntegersEquivZS : ZS ≃ₐ[ℤ] 𝓞 KK :=
  IsIntegralClosure.equiv ℤ ZS KK (𝓞 KK)

theorem discr_KK : NumberField.discr KK = -76 := by
  have hb : (⇑(basisZS.map ringOfIntegersEquivZS.toLinearEquiv))
      = ⇑ringOfIntegersEquivZS ∘ ⇑basisZS := by
    funext i; simp
  rw [← NumberField.discr_eq_discr KK (basisZS.map ringOfIntegersEquivZS.toLinearEquiv), hb,
    ← Algebra.discr_eq_discr_of_algEquiv basisZS ringOfIntegersEquivZS, discr_basisZS]

theorem nrComplexPlaces_le : NumberField.InfinitePlace.nrComplexPlaces KK ≤ 1 := by
  have h := NumberField.InfinitePlace.card_add_two_mul_card_eq_rank KK
  rw [finrank_KK] at h
  omega

/-- The signature of `K` is `(1, 1)`, from `sign (disc K) = (−1)^{r₂}` with
`disc K = −76 < 0` (so `r₂` is odd) together with `r₁ + 2r₂ = 3`. -/
theorem nrComplexPlaces_KK : NumberField.InfinitePlace.nrComplexPlaces KK = 1 := by
  have hsign := NumberField.sign_discr (K := KK)
  rw [discr_KK] at hsign
  rcases Nat.le_one_iff_eq_zero_or_eq_one.mp nrComplexPlaces_le with h | h
  · rw [h] at hsign; exact absurd hsign (by decide)
  · exact h

theorem nrRealPlaces_KK : NumberField.InfinitePlace.nrRealPlaces KK = 1 := by
  have h := NumberField.InfinitePlace.card_add_two_mul_card_eq_rank KK
  rw [finrank_KK, nrComplexPlaces_KK] at h
  omega

/-- `θ³ = −2ε²` with `ε = θ + 1` a unit, so `(2) = (θ)³`: this is the reason the
unique prime above `2` is principal, and hence the reason `h(K) = 1` survives a
Minkowski bound bigger than `2`. -/
theorem sEl_cube_eq : sEl ^ 3 = -(2 * epsEl ^ 2) := by decide

theorem isUnit_epsEl : IsUnit epsEl := isUnit_of_norm_isUnit (by decide)

/-- `√76 ≤ 9`, the only analytic input to the Minkowski bound besides `π > 3`. -/
theorem sqrt_abs_neg76_le_nine : Real.sqrt |((-76 : ℤ) : ℝ)| ≤ 9 := by
  have h76 : |((-76 : ℤ) : ℝ)| = 76 := by norm_num
  rw [h76]
  nlinarith [Real.sq_sqrt (show (0 : ℝ) ≤ 76 by norm_num), Real.sqrt_nonneg (76 : ℝ)]

/-- The Minkowski bound of `K`, `(4/π)·(3!/3³)·√76 = 8√76/(9π)`, is `< 3` — so
`⌊M K⌋₊ ≤ 2` and only the primes above `2` have to be inspected.  It is NOT `< 2`:
`8·√76/(9·3.1416) ≈ 2.4666`, which is exactly why level `11`'s
`isPrincipalIdealRing_of_abs_discr_lt` route is unavailable here. -/
theorem minkowski_aux (S : ℝ) (_hS : 0 ≤ S) (hS9 : S ≤ 9) :
    (4 / Real.pi) ^ 1 * ((Nat.factorial 3 : ℝ) / ((3 : ℕ) : ℝ) ^ (3 : ℕ) * S) < 3 := by
  have hpi : (3 : ℝ) < Real.pi := Real.pi_gt_three
  have hpi0 : (0 : ℝ) < Real.pi := by linarith
  have hf : ((Nat.factorial 3 : ℕ) : ℝ) / ((3 : ℕ) : ℝ) ^ (3 : ℕ) = 2 / 9 := by
    norm_num [Nat.factorial]
  rw [hf, pow_one, div_mul_eq_mul_div, div_lt_iff₀ hpi0]
  linarith

/-- **`h(K) = 1`, i.e. `𝓞_K` is a PID** (PROVEN).

**This is the one step that does NOT transcribe from level `11`.**  There
`|disc| = 44` is below `(2·(π/4)·3³/3!)² ≈ 49.96`, so
`isPrincipalIdealRing_of_abs_discr_lt` applies and every class contains an ideal
of norm `1`.  Here `|disc| = 76` is ABOVE it: the Minkowski bound is
`8√76/(9π) ≈ 2.4666`, so classes may contain an ideal of norm `2` and the general
criterion is needed.

`⌊M K⌋₊ = 2`, so the only prime to consider is `p = 2`.  A prime `P` above `2`
contains `2`, hence `θ³ = −2ε²`, hence `θ`; and `span {θ}` is MAXIMAL because its
absolute norm `|N(θ)| = 2` is prime.  A prime ideal containing a maximal ideal
equals it, so `P = span {θ}` is principal. -/
theorem isPrincipalIdealRing_OKK : IsPrincipalIdealRing (𝓞 KK) := by
  refine _root_.RingOfIntegers.isPrincipalIdealRing_of_isPrincipal_of_pow_le_of_mem_primesOver_of_mem_Icc
    (fun p hp hpp P hP hple => ?_)
  -- `p = 2` is the only prime in `Finset.Icc 1 ⌊M K⌋₊ = Finset.Icc 1 2`.
  have hp2 : p = 2 := by
    have hple2 : p ≤ 2 := by
      refine le_trans (Finset.mem_Icc.mp hp).2
        (Nat.lt_succ_iff.mp ((Nat.floor_lt ?_).mpr ?_))
      · have hpi0 : (0 : ℝ) < Real.pi := Real.pi_pos
        positivity
      · rw [nrComplexPlaces_KK, finrank_KK, discr_KK]
        refine lt_of_lt_of_le (minkowski_aux _ (Real.sqrt_nonneg _) sqrt_abs_neg76_le_nine) ?_
        norm_num
    interval_cases p
    · exact absurd hpp (by decide)
    · exact absurd hpp (by decide)
    · rfl
  subst hp2
  -- `θ`, as an element of `𝓞 K`.
  set tO : 𝓞 KK := ringOfIntegersEquivZS sEl with htO
  have hPprime : P.IsPrime := hP.1
  -- `2 ∈ P`, from `P` lying over `span {2}`.
  have h2P : (2 : 𝓞 KK) ∈ P := by
    have hov : Ideal.span {((2 : ℕ) : ℤ)} = Ideal.under ℤ P := hP.2.over
    have h2 : ((2 : ℕ) : ℤ) ∈ Ideal.under ℤ P := hov ▸ Ideal.mem_span_singleton_self _
    rw [Ideal.mem_under] at h2
    simpa using h2
  -- `θ³ = −2ε² ∈ P`, so `θ ∈ P`.
  have htP : tO ∈ P := by
    have hcube : tO ^ 3 = -(2 * (ringOfIntegersEquivZS epsEl) ^ 2) := by
      rw [htO, ← map_pow, sEl_cube_eq, map_neg, map_mul, map_pow, map_ofNat]
    have hmem : tO ^ 3 ∈ P := by
      rw [hcube]
      exact neg_mem (Ideal.mul_mem_right _ _ h2P)
    exact hPprime.mem_of_pow_mem 3 hmem
  -- `span {θ}` is maximal because `|N θ| = 2` is prime.
  have hnorm2 : Ideal.absNorm (Ideal.span {tO}) = 2 := by
    have hn : Algebra.norm ℤ tO = -2 := by
      rw [htO, Algebra.norm_eq_of_algEquiv ringOfIntegersEquivZS, norm_eq]
      decide
    rw [Ideal.absNorm_span_singleton, hn]
    decide
  have hspanPrime : (Ideal.span {tO}).IsPrime :=
    Ideal.isPrime_of_irreducible_absNorm (by rw [hnorm2]; exact Nat.prime_two)
  have hspanNe : Ideal.span {tO} ≠ ⊥ := by
    intro h
    rw [← Ideal.absNorm_eq_zero_iff, hnorm2] at h
    exact absurd h (by omega)
  have hspanMax : (Ideal.span {tO}).IsMaximal := hspanPrime.isMaximal hspanNe
  have hle : Ideal.span {tO} ≤ P := (Ideal.span_singleton_le_iff_mem _).mpr htP
  have hPtop : P ≠ ⊤ := hPprime.ne_top
  have heq : Ideal.span {tO} = P := hspanMax.eq_of_le hPtop hle
  rw [← heq]
  exact ⟨⟨tO, rfl⟩⟩

theorem isPrincipalIdealRing_of_ringEquiv {A B : Type*} [CommRing A] [CommRing B]
    (e : A ≃+* B) [IsPrincipalIdealRing B] : IsPrincipalIdealRing A := by
  refine ⟨fun I => ?_⟩
  obtain ⟨b, hb⟩ := (IsPrincipalIdealRing.principal (I.map (e : A →+* B))).principal
  refine ⟨e.symm b, ?_⟩
  have h1 : (I.map (e : A →+* B)).map (e.symm : B →+* A) = I := by
    rw [Ideal.map_map]
    convert Ideal.map_id I
    ext x; simp
  rw [← h1, hb, Ideal.map_span]
  simp

end RingOfIntegers

/-- **`ℤ[θ]` is a principal ideal ring** (PROVEN), i.e. `𝓞_K = ℤ[θ]` together with
`h(K) = 1`.

Consumed below only through `WfDvdMonoid`, `UniqueFactorizationMonoid` and
Bézout. -/
theorem isPrincipalIdealRing_zs : IsPrincipalIdealRing ZS :=
  haveI := isPrincipalIdealRing_OKK
  isPrincipalIdealRing_of_ringEquiv ringOfIntegersEquivZS.toRingEquiv

instance : IsPrincipalIdealRing ZS := isPrincipalIdealRing_zs

section UnitGroup

open scoped NumberField
open _root_.Module

/-! ## Transporting Dirichlet's unit theorem to `ℤ[θ]` -/

theorem rank_KK : NumberField.Units.rank KK = 1 := by
  rw [NumberField.Units.rank, NumberField.InfinitePlace.card_eq_nrRealPlaces_add_nrComplexPlaces,
    nrRealPlaces_KK, nrComplexPlaces_KK]

noncomputable def unitsEquivZS : (ZS)ˣ ≃* (𝓞 KK)ˣ :=
  Units.mapEquiv ringOfIntegersEquivZS.toRingEquiv.toMulEquiv

theorem unitsEquivZS_neg (X : (ZS)ˣ) : unitsEquivZS (-X) = -unitsEquivZS X := by
  ext
  simp [unitsEquivZS]

/-- **Dirichlet for `ℤ[θ]`**: `ℤ[θ]ˣ = {±1} × ⟨E⟩` for a fundamental unit `E`. -/
theorem exists_fundamental_unit :
    ∃ E : (ZS)ˣ, ∀ U : (ZS)ˣ, ∃ (σ : (ZS)ˣ) (n : ℤ), (σ = 1 ∨ σ = -1) ∧ U = σ * E ^ n := by
  have hsub : Subsingleton (Fin (NumberField.Units.rank KK)) :=
    Fin.subsingleton_iff_le_one.mpr (le_of_eq rank_KK)
  have hidx : (0 : ℕ) < NumberField.Units.rank KK := by rw [rank_KK]; norm_num
  refine ⟨unitsEquivZS.symm (NumberField.Units.fundSystem KK ⟨0, hidx⟩), fun U => ?_⟩
  obtain ⟨⟨ζ, e⟩, hV, -⟩ := NumberField.Units.exist_unique_eq_mul_prod KK (unitsEquivZS U)
  have hprod : (∏ i, (NumberField.Units.fundSystem KK i) ^ (e i))
      = (NumberField.Units.fundSystem KK ⟨0, hidx⟩) ^ (e ⟨0, hidx⟩) :=
    Finset.prod_eq_single_of_mem _ (Finset.mem_univ _)
      fun b _ hb => absurd (Subsingleton.elim b ⟨0, hidx⟩) hb
  rw [hprod] at hV
  refine ⟨unitsEquivZS.symm (ζ : (𝓞 KK)ˣ), e ⟨0, hidx⟩, ?_, ?_⟩
  · rcases NumberField.Units.torsion_eq_one_or_neg_one_of_odd_finrank (K := KK)
      (by rw [finrank_KK]; decide) ζ with hz | hz
    · left; rw [hz, map_one]
    · right
      apply unitsEquivZS.injective
      rw [MulEquiv.apply_symm_apply, hz, show (-1 : (ZS)ˣ) = -(1 : (ZS)ˣ) from rfl,
        unitsEquivZS_neg, map_one]
  · apply unitsEquivZS.injective
    rw [map_mul, map_zpow, MulEquiv.apply_symm_apply, MulEquiv.apply_symm_apply, hV]

/-! ## `ε` is not `±` a square: reduction mod the prime `θ ↦ 18` of `𝔽₂₉`

`18³ + 2·18² + 4·18 + 2 = 5832 + 648 + 72 + 2 = 6554 = 29·226`, and `18² ≡ 5`, so
`φ(a + bθ + cθ²) = a + 18b + 5c` is a ring map `ℤ[θ] → 𝔽₂₉`.

Unlike level `11`, where `N(ε) = −1` disposes of the `+` case for free, here
`N(ε) = +1` and BOTH cases need the character: `φ(ε) = 19`, and neither `19` nor
`−19 = 10` is a square mod `29`. -/

/-- The ring reduction `ℤ[θ] → 𝔽₂₉`, `θ ↦ 18`. -/
def phi29 (x : ZS) : ZMod 29 := (x.a : ZMod 29) + 18 * (x.b : ZMod 29) + 5 * (x.c : ZMod 29)

theorem phi29_mul (x y : ZS) : phi29 (x * y) = phi29 x * phi29 y := by
  have h : ((x * y).a + 18 * (x * y).b + 5 * (x * y).c : ℤ)
      = (x.a + 18 * x.b + 5 * x.c) * (y.a + 18 * y.b + 5 * y.c)
        - 29 * (11 * x.b * y.b + 6 * x.b * y.c + 6 * x.c * y.b - 3 * x.c * y.c) := by
    simp only [mul_a, mul_b, mul_c]; ring
  have hc := congrArg (fun z : ℤ => (z : ZMod 29)) h
  push_cast at hc
  rw [show (29 : ZMod 29) = 0 from by decide, zero_mul, sub_zero] at hc
  simp only [phi29]
  linear_combination hc

theorem phi29_neg (x : ZS) : phi29 (-x) = -phi29 x := by
  simp only [phi29, neg_a, neg_b, neg_c, Int.cast_neg]; ring

theorem phi29_epsEl : phi29 epsEl = 19 := by decide

theorem sq_ne_nineteen : ∀ y : ZMod 29, (19 : ZMod 29) ≠ y ^ 2 ∧ (19 : ZMod 29) ≠ -y ^ 2 := by
  decide

/-- **`ε` is neither a square nor minus a square in `ℤ[θ]`.**  Here `N(ε) = +1`, so
— unlike at level `11` — the norm excludes NEITHER case and the mod-`29`
quadratic-residue obstruction does both. -/
theorem epsEl_ne_sq (w : ZS) : epsEl ≠ w ^ 2 ∧ epsEl ≠ -(w ^ 2) := by
  constructor
  · intro h
    have hp := congrArg phi29 h
    rw [phi29_epsEl, pow_two, phi29_mul] at hp
    exact (sq_ne_nineteen (phi29 w)).1 (by rw [hp]; ring)
  · intro h
    have hp := congrArg phi29 h
    rw [phi29_epsEl, phi29_neg, pow_two, phi29_mul] at hp
    exact (sq_ne_nineteen (phi29 w)).2 (by rw [hp]; ring)

theorem zpow_two_mul (F : (ZS)ˣ) (k : ℤ) : F ^ (2 * k) = (F ^ k) ^ 2 := by
  rw [← zpow_natCast (F ^ k) 2, ← zpow_mul]
  congr 1
  push_cast
  ring

end UnitGroup

/-- **The units of `ℤ[θ]` modulo squares are `{±1, ±ε}`** (PROVEN), `ε = θ + 1`. -/
theorem unit_sq_class {u : ZS} (hu : IsUnit u) :
    ∃ v w : ZS, (v = 1 ∨ v = -1 ∨ v = epsEl ∨ v = -epsEl) ∧ u = v * w ^ 2 := by
  obtain ⟨E, hE⟩ := exists_fundamental_unit
  obtain ⟨U, rfl⟩ := hu
  obtain ⟨P, hP⟩ := isUnit_epsEl
  obtain ⟨σ₀, j, hσ₀, hj⟩ := hE P
  -- `j` is odd: otherwise `ε = ±(square)`.
  have hjodd : ¬ (2 ∣ j) := by
    rintro ⟨t, rfl⟩
    rw [zpow_two_mul] at hj
    rcases hσ₀ with rfl | rfl
    · exact (epsEl_ne_sq ((E ^ t : (ZS)ˣ) : ZS)).1 (by
        rw [← hP, hj, one_mul]; push_cast; ring_nf)
    · exact (epsEl_ne_sq ((E ^ t : (ZS)ˣ) : ZS)).2 (by
        rw [← hP, hj]; push_cast; ring_nf)
  obtain ⟨σ, n, hσ, hU⟩ := hE U
  rcases Int.even_or_odd n with ⟨m, hm⟩ | ⟨m, hm⟩
  · -- `n` even
    refine ⟨(σ : ZS), ((E ^ m : (ZS)ˣ) : ZS), ?_, ?_⟩
    · rcases hσ with rfl | rfl
      · exact Or.inl rfl
      · exact Or.inr (Or.inl rfl)
    · have : U = σ * (E ^ m) ^ 2 := by
        rw [hU, hm, show (m + m : ℤ) = 2 * m by ring, ← zpow_natCast (E ^ m) 2, ← zpow_mul]
        ring_nf
      rw [this]; push_cast; ring
  · -- `n` odd; use `j` odd to replace `E` by `ε`
    obtain ⟨t, ht⟩ : ∃ t : ℤ, j = 2 * t + 1 := by
      rcases Int.even_or_odd j with ⟨r, hr⟩ | ⟨r, hr⟩
      · exact absurd ⟨r, by omega⟩ hjodd
      · exact ⟨r, hr⟩
    have hσ₀sq : σ₀ * σ₀ = 1 := by rcases hσ₀ with rfl | rfl <;> simp
    have hcalc : (σ * σ₀) * (σ₀ * E ^ j) * (E ^ (m - t)) ^ 2 = σ * E ^ n := by
      have h1 : (σ * σ₀) * (σ₀ * E ^ j) = σ * E ^ j := by
        rw [mul_assoc, ← mul_assoc σ₀ σ₀, hσ₀sq, one_mul]
      rw [h1, mul_assoc, ← zpow_natCast (E ^ (m - t)) 2, ← zpow_mul, ← zpow_add, ht, hm]
      congr 1
      push_cast
      ring_nf
    refine ⟨((σ * σ₀ : (ZS)ˣ) : ZS) * epsEl, ((E ^ (m - t) : (ZS)ˣ) : ZS), ?_, ?_⟩
    · rcases hσ with rfl | rfl <;> rcases hσ₀ with rfl | rfl
      · exact Or.inr (Or.inr (Or.inl (by norm_num)))
      · exact Or.inr (Or.inr (Or.inr (by norm_num)))
      · exact Or.inr (Or.inr (Or.inr (by norm_num)))
      · exact Or.inr (Or.inr (Or.inl (by norm_num)))
    · have hUU : U = (σ * σ₀) * P * (E ^ (m - t)) ^ 2 := by
        rw [hj, hcalc, hU]
      rw [hUU, ← hP]
      push_cast
      ring_nf

/-- **THE VALUATION BOOKKEEPING** (PROVEN): `β = p − 2θ·e²` is a unit from
`{±1, ±ε}` times `θ^r g^t` (`r, t ∈ {0, 1}`) times a square.

The argument, in the order it is written below:

* `β ≠ 0` because its `θ`-coordinate is `−2e² ≠ 0`.
* Split off the two bad primes: `β = θ^a·β₁` with `θ ∤ β₁`, then `β₁ = g^b·β₂`
  with `g ∤ β₂` (`WfDvdMonoid.max_power_factor`, available since `ℤ[θ]` is a PID
  hence a `WfDvdMonoid`).
* `β₂` is coprime to `θ^a·g^b·γ`.  This is the only place the arithmetic of the
  point enters.  A prime `z` dividing both divides neither `θ` nor `g`, so it
  divides `γ`; it divides `β` as well, so by `gamma_eq` it divides
  `D·e⁴ = uD·θ⁸·g·e⁴`; `uD` is a unit and `θ, g` are excluded, so `z ∣ e`; and
  then `z ∣ p` by `beta_eq`, contradicting `IsCoprime p e` through Bézout.
* `β₂ · (θ^a g^b γ) = n²` with the two factors coprime, so `β₂` is a square up to
  a unit (`exists_associated_pow_of_mul_eq_pow'`, the Bézout form).
* Finally `θ^a = (θ^{a/2})²·θ^{a%2}` and likewise for `g`, and the leftover unit
  is `{±1, ±ε}` times a square by `unit_sq_class`. -/
theorem descent_zs {p e n : ℤ} (he : 0 < e) (hcop : IsCoprime p e)
    (hn : p ^ 3 + 4 * p ^ 2 * e ^ 2 + 16 * p * e ^ 4 + 16 * e ^ 6 = n ^ 2) :
    ∃ (v δ : ZS) (r t : ℕ), (v = 1 ∨ v = -1 ∨ v = epsEl ∨ v = -epsEl) ∧
      r < 2 ∧ t < 2 ∧ beta p e = v * sEl ^ r * gEl ^ t * δ ^ 2 := by
  have hbne : beta p e ≠ 0 := by
    intro h
    have hb : (-2 * e ^ 2 : ℤ) = 0 := congrArg ZS.b h
    nlinarith
  obtain ⟨a, β₁, hsβ₁, hβ₁⟩ := WfDvdMonoid.max_power_factor hbne irreducible_sEl
  have hβ₁ne : β₁ ≠ 0 := by rintro rfl; rw [mul_zero] at hβ₁; exact hbne hβ₁
  obtain ⟨b, β₂, hgβ₂, hβ₂⟩ := WfDvdMonoid.max_power_factor hβ₁ne irreducible_gEl
  have hβ₂ne : β₂ ≠ 0 := by rintro rfl; rw [mul_zero] at hβ₂; exact hβ₁ne hβ₂
  have hsβ₂ : ¬ sEl ∣ β₂ := fun h => hsβ₁ (hβ₂ ▸ h.mul_left _)
  have hβ : beta p e = sEl ^ a * gEl ^ b * β₂ := by rw [hβ₁, hβ₂]; ring
  have hnn : ((n ^ 2 : ℤ) : ZS) = ((n : ℤ) : ZS) ^ 2 := by push_cast; ring
  have hprod : β₂ * (sEl ^ a * gEl ^ b * gammaEl p e) = ((n : ℤ) : ZS) ^ 2 := by
    have h1 := beta_mul_gamma p e n hn
    rw [hβ, hnn] at h1; linear_combination h1
  have hcop2 : IsCoprime β₂ (sEl ^ a * gEl ^ b * gammaEl p e) := by
    refine isCoprime_of_irreducible_dvd (fun h => hβ₂ne h.1) ?_
    intro z hz hzβ₂ hzB
    have hzp : Prime z := UniqueFactorizationMonoid.irreducible_iff_prime.mp hz
    have hzs : ¬ z ∣ sEl := fun h =>
      hsβ₂ ((hz.associated_of_dvd irreducible_sEl h).symm.dvd.trans hzβ₂)
    have hzg : ¬ z ∣ gEl := fun h =>
      hgβ₂ ((hz.associated_of_dvd irreducible_gEl h).symm.dvd.trans hzβ₂)
    have hzγ : z ∣ gammaEl p e := by
      rcases hzp.dvd_mul.mp hzB with h | h
      · rcases hzp.dvd_mul.mp h with h1 | h1
        · exact absurd (hzp.dvd_of_dvd_pow h1) hzs
        · exact absurd (hzp.dvd_of_dvd_pow h1) hzg
      · exact h
    have hzβ : z ∣ beta p e := by rw [hβ]; exact hzβ₂.mul_left _
    have hzD : z ∣ uD * sEl ^ 8 * gEl * ((e ^ 4 : ℤ) : ZS) := by
      have hid : DEl * ((e ^ 4 : ℤ) : ZS) = gammaEl p e - QEl p e * beta p e := by
        rw [gamma_eq]; ring
      have h2 := dvd_sub hzγ (hzβ.mul_left (QEl p e))
      rw [← hid, D_eq] at h2
      exact h2
    have hze : z ∣ ((e : ℤ) : ZS) := by
      rcases hzp.dvd_mul.mp hzD with h | h
      · rcases hzp.dvd_mul.mp h with h1 | h1
        · rcases hzp.dvd_mul.mp h1 with h2 | h2
          · exact absurd (isUnit_of_dvd_unit h2 isUnit_uD) hzp.not_unit
          · exact absurd (hzp.dvd_of_dvd_pow h2) hzs
        · exact absurd h1 hzg
      · refine hzp.dvd_of_dvd_pow (n := 4) ?_
        rwa [show (((e ^ 4 : ℤ)) : ZS) = ((e : ℤ) : ZS) ^ 4 by push_cast; ring] at h
    have hzpp : z ∣ ((p : ℤ) : ZS) := by
      have hp : ((p : ℤ) : ZS) = beta p e + ((2 * e : ℤ) : ZS) * ((e : ℤ) : ZS) * sEl := by
        rw [beta_eq]; push_cast; ring
      rw [hp]
      exact dvd_add hzβ ((hze.mul_left _).mul_right sEl)
    obtain ⟨x, y, hxy⟩ := hcop
    refine absurd (isUnit_of_dvd_one (a := z) ?_) hzp.not_unit
    have h1 : ((1 : ℤ) : ZS)
        = ((x : ℤ) : ZS) * ((p : ℤ) : ZS) + ((y : ℤ) : ZS) * ((e : ℤ) : ZS) := by
      rw [← Int.cast_mul, ← Int.cast_mul, ← Int.cast_add, hxy]
    rw [show (1 : ZS) = ((1 : ℤ) : ZS) by push_cast; ring, h1]
    exact dvd_add (hzpp.mul_left _) (hze.mul_left _)
  obtain ⟨d, u, hu⟩ := exists_associated_pow_of_mul_eq_pow' hcop2 (k := 2) hprod
  obtain ⟨v, w, hv, hvw⟩ := unit_sq_class (u := (u : ZS)) u.isUnit
  refine ⟨v, sEl ^ (a / 2) * gEl ^ (b / 2) * d * w, a % 2, b % 2, hv, by omega, by omega, ?_⟩
  have hsa : sEl ^ a = (sEl ^ (a / 2)) ^ 2 * sEl ^ (a % 2) := by
    rw [← pow_mul, ← pow_add]; congr 1; omega
  have hgb : gEl ^ b = (gEl ^ (b / 2)) ^ 2 * gEl ^ (b % 2) := by
    rw [← pow_mul, ← pow_add]; congr 1; omega
  rw [hβ, hsa, hgb, ← hu, hvw]
  ring

end ZS

end Cubic19

end MazurX0Nineteen
