/-
DifferentialCharacter.lean — own work for the Fermat project (not vendored).

**The action of an isogeny on the invariant differential**, cut 2026-07-28 out
of the single sorry leaf `MazurLevelFortyNine.exists_sqrtNegOne_galSign` in
`Fermat/FLT/FreyCurve/MazurTorsion.lean`, which is *ATAEC* II.2.2 — "the CM
field is the field of definition of the endomorphisms" — in the exact form the
level-`49` argument consumes.

## What this file builds

For a Weierstrass curve `W` the **invariant differential** is
`ω = dx / (2y + a₁x + a₃)`, and a rational map `φ : W → W'` pulls `ω'` back to a
scalar multiple of `ω`:

  `φ*ω' = λ(φ) · ω`,   `λ(φ) ∈ F`.

`λ` is additive, multiplicative on composites, restricts to the identity on `ℤ`,
is INJECTIVE in characteristic zero, and is Galois-equivariant. Those five facts
are what make `End(E_ℚ̄)` a commutative ring embedded in `ℚ̄` and pin the field
of definition of an endomorphism to the field generated by its `λ`-value — which
is the whole content of *ATAEC* II.2.2 for the case at hand.

## How `λ` is written here: a RELATION, not a function

`λ` is not introduced as a function. Its defining equation is a polynomial
identity in the rational-map witnesses of `φ`, and it is stated as the relation
`IsDiffChar φ c` ("`φ` acts on the invariant differential by `c`"). Every fact
about `λ` is then a statement about that relation, and the choice-free
formulation costs nothing: `isDiffChar_unique` says the scalar is unique, which
is all a function would have bought.

Concretely, if `IsRationalMap φ` is witnessed by `A, B, C, D, E` with

  `x ∘ φ = A/B`,  `y ∘ φ = (C·y + D)/E`

then, writing `f = A/B` and `g = (C·y + D)/E`,

  `φ*ω' = d f / (2g + a₁'f + a₃')
        = f' · (2y + a₁x + a₃) / (2g + a₁'f + a₃') · ω`

so `λ(φ) = f'·(2y + a₁x + a₃)/(2g + a₁'f + a₃')`. Clearing denominators
(`f' = (A'B − AB')/B²`) gives the identity in `isDiffChar_certificate` below,
which is what `IsDiffChar` asserts, at every affine point.

Two sanity checks are PROVEN here rather than asserted, and they are what pins
the normalisation: `isDiffChar_id` (`λ(1) = 1`) and `isDiffChar_neg_id`
(`λ(−1) = −1`).

## The degenerate-witness trap, and the `φ = 0 → c = 0` clause

`IsRationalMap`'s certificate is quantified over the points where `φ P ≠ 0`, so
for `φ = 0` it is VACUOUS and *any* tuple `A, …, E` is a legal witness. Without a
guard, `IsDiffChar 0 c` would therefore hold for every `c` that occurs at all
(take the witnesses of the identity map and get `IsDiffChar 0 1`), and both
`isDiffChar_unique` and `isDiffChar_add` would be FALSE. The definition carries
the explicit clause `φ = 0 → c = 0` for exactly this reason; it is the only
place where the zero map needs separate handling, and with it in place
uniqueness needs no `φ ≠ 0` hypothesis.

## The leaves

`isDiffChar_id`, `isDiffChar_zero`, `isDiffChar_neg_id`, `isDiffChar_neg`,
`isDiffChar_mulByHom`, `psi_ne_zero_of_two_nsmul_ne_zero`, `exists_isDiffChar`
and `isDiffChar_unique` are PROVEN (the last two on 2026-07-28).

`isDiffChar_unique` needs no geometry at all — the two witness tuples define the
same rational function `A/B`, and its derivative is what the certificate
measures. `exists_isDiffChar` is an assembly over ONE geometric leaf,
`exists_diffCharScalar` (translation-invariance of `ω`, in the form "the pullback
ratio is constant"); the `y`-witnesses, the zero map, and the crossing of the
finite kernel by Zariski density are all discharged there.

Still open, each stated in full:

* `exists_diffCharScalar` — the pullback ratio `φ*ω'/ω` is CONSTANT;
* `isDiffChar_add` — `λ` is additive;
* `isDiffChar_comp` — `λ` is multiplicative on composites;
* `eq_of_isDiffChar` — `λ` is injective (characteristic zero);
* `isDiffChar_galConj` — `λ(φ^σ) = σ(λ φ)` for `σ ∈ Gal(ℚ̄/ℚ)`.

Reference: Silverman, *AEC* III.5 (the invariant differential and its
functoriality), *ATAEC* II.2.
-/
module

public import Fermat.FLT.EllipticCurve.Isogeny

@[expose] public section

open WeierstrassCurve WeierstrassCurve.Affine

namespace WeierstrassCurve

open _root_.Polynomial

section General

variable {F : Type*} [Field F] [DecidableEq F] {W W' W'' : Affine F}

/-- **The polynomial certificate for `φ*ω' = c·ω`.**

With `x = x(P)`, `y = y(P)`, `f = A/B = x ∘ φ` and `g = (C·y + D)/E = y ∘ φ`, the
equation `λ(φ)·(2g + a₁'·f + a₃') = f'·(2y + a₁x + a₃)` becomes, after clearing
`B²` and `E`,

  `c · B · (2·B·(C·y + D) + a₁'·A·E + a₃'·B·E)
     = (A'·B − A·B')·E·(2y + a₁x + a₃)`.

The primed coefficients are those of the TARGET curve `W'` (they come from
`y(φP)`), the unprimed ones from the SOURCE curve `W` (they come from `ω`). -/
def IsDiffCharCert (W : Affine F) (W' : Affine F) (A B C D E : F[X]) (c : F)
    (P : W.Point) : Prop :=
  c * (B.eval (veluPointX P) *
        (2 * B.eval (veluPointX P)
              * (C.eval (veluPointX P) * veluPointY P + D.eval (veluPointX P))
          + W'.a₁ * A.eval (veluPointX P) * E.eval (veluPointX P)
          + W'.a₃ * B.eval (veluPointX P) * E.eval (veluPointX P)))
    = ((derivative A).eval (veluPointX P) * B.eval (veluPointX P)
          - A.eval (veluPointX P) * (derivative B).eval (veluPointX P))
        * E.eval (veluPointX P)
        * (2 * veluPointY P + W.a₁ * veluPointX P + W.a₃)

/-- **`φ` acts on the invariant differential by the scalar `c`**, i.e.
`φ*ω' = c·ω` where `ω = dx/(2y + a₁x + a₃)`.

The witnesses `A, B, C, D, E` are the rational-map witnesses of `φ` (so
`IsDiffChar φ c → IsRationalMap φ`), and the extra requirement is the
differential certificate at every affine point.

The clause `φ = 0 → c = 0` is NOT redundant: `IsRationalMap`'s certificate is
vacuous for `φ = 0`, so without it every scalar would be a legal
differential character of the zero map. See the module docstring. -/
def IsDiffChar (φ : W.Point →+ W'.Point) (c : F) : Prop :=
  (φ = 0 → c = 0) ∧
  ∃ A B C D E : F[X], B ≠ 0 ∧ E ≠ 0 ∧
    (∀ P : W.Point, φ P ≠ 0 →
      veluPointX (φ P) * B.eval (veluPointX P) = A.eval (veluPointX P) ∧
      veluPointY (φ P) * E.eval (veluPointX P)
        = C.eval (veluPointX P) * veluPointY P + D.eval (veluPointX P)) ∧
    (∀ P : W.Point, P ≠ 0 → IsDiffCharCert W W' A B C D E c P)

/-! ### The three normalisations, PROVEN

These are the non-vacuity witnesses for `IsDiffChar`: they exhibit the relation
holding at the three values that pin its normalisation, `λ(0) = 0`, `λ(1) = 1`
and `λ(−1) = −1`. Each is a direct computation with explicit witnesses. -/

/-- `λ(0) = 0`, with the witnesses `A = 0`, `B = 1`, `C = D = 0`, `E = 1`: both
sides of the certificate vanish. -/
theorem isDiffChar_zero : IsDiffChar (0 : W.Point →+ W'.Point) 0 := by
  refine ⟨fun _ => rfl, 0, 1, 0, 0, 1, one_ne_zero, one_ne_zero,
    fun P hP => absurd (AddMonoidHom.zero_apply P) hP, fun P _ => ?_⟩
  simp [IsDiffCharCert]

omit [DecidableEq F] in
/-- An elliptic curve over an algebraically closed field has a nonzero point;
this is what makes `AddMonoidHom.id W.Point` nonzero, hence lets
`isDiffChar_id` and `isDiffChar_neg_id` discharge the guard clause of
`IsDiffChar`. -/
theorem exists_point_ne_zero [IsAlgClosed F] [W.IsElliptic] :
    ∃ P : W.Point, P ≠ 0 := by
  obtain ⟨P, hP, -⟩ := exists_point_veluPointX_eq (W := W) 0
  exact ⟨P, hP⟩

/-- **`ω` has no zero at a non-`2`-torsion point**: `2y + a₁x + a₃ = 0` at a
nonzero `P` says exactly that `−P` has the same two coordinates as `P`, i.e. that
`P` is its own negative. Contrapositive form, which is how both
`exists_isDiffChar` and `isDiffChar_unique` use it: away from the (finite)
`2`-torsion the denominator of `ω` is invertible. -/
theorem psi_ne_zero_of_two_nsmul_ne_zero {P : W.Point} (h2 : (2 : ℕ) • P ≠ 0) :
    2 * veluPointY P + W.a₁ * veluPointX P + W.a₃ ≠ 0 := by
  intro hc
  have hP : P ≠ 0 := fun hz => h2 (by rw [hz, smul_zero])
  refine h2 ?_
  have hneg : -P = P := by
    refine eq_of_veluPoint_eq (neg_ne_zero.2 hP) hP (velu_pointX_neg _) ?_
    rw [velu_pointY_neg _ hP]
    linear_combination -hc
  calc (2 : ℕ) • P = P + P := two_nsmul _
    _ = P + -P := by rw [hneg]
    _ = 0 := add_neg_cancel _

/-- `λ(1) = 1`, with the witnesses `A = X`, `B = 1`, `C = 1`, `D = 0`, `E = 1`:
the certificate reads `2y + a₁x + a₃ = 2y + a₁x + a₃`. -/
theorem isDiffChar_id [IsAlgClosed F] [W.IsElliptic] :
    IsDiffChar (AddMonoidHom.id W.Point) 1 := by
  refine ⟨fun hc => ?_, X, 1, 1, 0, 1, one_ne_zero, one_ne_zero,
    fun P _ => by simp, fun P _ => ?_⟩
  · obtain ⟨Q, hQ⟩ := exists_point_ne_zero (W := W)
    exact absurd (DFunLike.congr_fun hc Q) hQ
  · simp only [IsDiffCharCert, eval_X, eval_one, eval_zero, derivative_X,
      derivative_one]
    ring

/-- `λ(−1) = −1`, with the witnesses `A = X`, `B = 1`, `C = −1`,
`D = −(a₁X + a₃)`, `E = 1`: the `y`-witness is `negY`, and the certificate reads
`(−1)·(−(2y + a₁x + a₃)) = 2y + a₁x + a₃`. -/
theorem isDiffChar_neg_id [IsAlgClosed F] [W.IsElliptic] :
    IsDiffChar (-(AddMonoidHom.id W.Point)) (-1) := by
  refine ⟨fun hc => ?_, X, 1, -1, -(C W.a₁ * X + C W.a₃), 1,
    one_ne_zero, one_ne_zero, fun P hP => ?_, fun P _ => ?_⟩
  · obtain ⟨Q, hQ⟩ := exists_point_ne_zero (W := W)
    have : -Q = 0 := DFunLike.congr_fun hc Q
    exact absurd (by simpa using congrArg (fun R : W.Point => -R) this) hQ
  · have hP0 : P ≠ 0 := fun hc => hP (by rw [hc]; simp)
    have happ : (-(AddMonoidHom.id W.Point)) P = -P := rfl
    rw [happ]
    refine ⟨by simpa using velu_pointX_neg (W := W) P, ?_⟩
    rw [velu_pointY_neg P hP0]
    simp only [eval_one, eval_neg, eval_add, eval_mul, eval_C, eval_X, mul_one]
    ring
  · simp only [IsDiffCharCert, eval_X, eval_one, eval_zero, eval_neg, eval_add,
      eval_mul, eval_C, derivative_X, derivative_one]
    ring

/-! ### The open geometry

The six statements below are the leaves of this cut. Each is a standard fact
about the invariant differential (Silverman, *AEC* III.5); none of them is in
the mathlib pin, in `~/cs/FLT`, or elsewhere in `Fermat/` — the pin has the
invariant differential nowhere, and this project has only the universal
Hamiltonian derivation `PsiSumCompanion.DK` of
`Fermat/FLT/EllipticCurve/InvariantDerivation.lean`, which is the derivation
`ψ₂ · d/dx` on the function field of the UNIVERSAL curve and carries no
statement about isogenies. -/

/-- **LEAF: the pullback ratio `φ*ω'/ω` is a CONSTANT.**

This is the ONE geometric input of `exists_isDiffChar`, isolated from all of its
bookkeeping: the `φ = 0` branch, the restoration of the `y`-witnesses `Cx, D, E`
that the identity below has cancelled, and the extension of the certificate from
the good locus across the (finite) kernel by Zariski density are all PROVEN there
from this statement.

**What it says.** At a point `P` off the kernel the two rational-map certificates
`x(φP)·B = A` and `y(φP)·E = Cx·y + D` collapse `IsDiffCharCert` to

  `c · B(x)² · (2y(φP) + a₁'x(φP) + a₃')  =  (A'B − AB')(x) · (2y + a₁x + a₃)`,

i.e. `c = u'(x)·ψ(P)/ψ'(φP)` with `u = A/B = x∘φ`, which is exactly
`φ*ω' = c·ω` for `ω = dx/(2y + a₁x + a₃)`. The content is that this quotient does
not depend on `P`. Note the `y`-witnesses have dropped out entirely: the scalar is
a function of the `x`-map alone. No `φ ≠ 0` hypothesis is needed — for `φ = 0` the
conclusion is vacuous.

**THE ARGUMENT.** `ω` is translation-invariant (*AEC* III.5.1: `div ω = 0`, so
`τ_Q^*ω/ω` is a function with neither zeros nor poles, hence a constant, and
`Q ↦ that constant` is a morphism from a complete connected curve to `𝔾_m`, hence
constant `= 1`). Because `φ` is a HOMOMORPHISM, `φ ∘ τ_Q = τ_{φQ} ∘ φ`, so
`φ*ω'` is translation-invariant as well, and therefore so is `h := φ*ω'/ω`. The
step from there is free and needs no completeness: a translation-invariant
FUNCTION is constant, since `h(P₁) = h(P₁ + (P₂ − P₁)) = h(P₂)`. So the whole
burden is the invariance of `ω` and `ω'`, not the constancy of `h`.

**A REDUCTION WORTH KNOWING: `y` can be eliminated.** Squaring and using
`(2y + a₁x + a₃)² = 4x³ + b₂x² + 2b₄x + b₆` on each curve turns the statement into
a purely ONE-VARIABLE polynomial identity in `F[X]`,

  `(A'B − AB')² · (4X³ + b₂X² + 2b₄X + b₆)
     = C (c²) · B · (4A³ + b₂'A²B + 2b₄'AB² + b₆'B³)`,

which pins `c` up to sign. The `[n]` case of exactly this identity is already in
the tree: it is the Wronskian `Φₙ′·ΨSqₙ − Φₙ·ΨSqₙ′ = n·preΨ₂ₙ` behind
`separable_preΨ'`, proven through the Hamiltonian derivation
`PsiSumCompanion.DK` of `InvariantDerivation.lean` (`D = ψ₂·d/dx`, which kills the
curve polynomial and so acts on the coordinate ring). That derivation is the
natural route to the general case.

**THE CHECK THAT WOULD REFUTE THIS LEAF**: a rational map of Weierstrass curves
over an algebraically closed field, with witnesses `A, …, E`, and two points off
its kernel at which the displayed quotient takes different values. -/
theorem exists_diffCharScalar [IsAlgClosed F] [W.IsElliptic] [W'.IsElliptic]
    {φ : W.Point →+ W'.Point} {A B Cx D E : F[X]} (hB : B ≠ 0) (hE : E ≠ 0)
    (hrat : ∀ P : W.Point, φ P ≠ 0 →
      veluPointX (φ P) * B.eval (veluPointX P) = A.eval (veluPointX P) ∧
      veluPointY (φ P) * E.eval (veluPointX P)
        = Cx.eval (veluPointX P) * veluPointY P + D.eval (veluPointX P)) :
    ∃ c : F, ∀ P : W.Point, P ≠ 0 → φ P ≠ 0 →
      c * B.eval (veluPointX P) ^ 2
          * (2 * veluPointY (φ P) + W'.a₁ * veluPointX (φ P) + W'.a₃)
        = ((derivative A).eval (veluPointX P) * B.eval (veluPointX P)
            - A.eval (veluPointX P) * (derivative B).eval (veluPointX P))
          * (2 * veluPointY P + W.a₁ * veluPointX P + W.a₃) :=
  sorry

/-- **PROVEN** (2026-07-28): every rational map acts on the invariant differential
by some scalar.

`φ*ω'` is an invariant (translation-invariant) differential on `W`, and the space
of invariant differentials is one-dimensional, spanned by `ω`; so `φ*ω' = c·ω`.
That one-dimensionality is `exists_diffCharScalar` above and is the ONLY thing
this proof takes on trust. Everything else is discharged here:

* **`φ = 0`** is `isDiffChar_zero`; the guard clause `φ = 0 → c = 0` is then
  vacuous for `φ ≠ 0`.
* **Restoring the `y`-witnesses.** `exists_diffCharScalar` returns the collapsed
  identity, with `Cx, D, E` cancelled. Multiplying it by `E(x)` and feeding back
  the two rational-map certificates recovers `IsDiffCharCert` verbatim at every
  `P ∉ ker φ` — with no side condition on `E(x)`, because the certificates hold
  wherever `φ P ≠ 0`.
* **Crossing the kernel.** `IsDiffCharCert` is required at EVERY affine `P`,
  including the finitely many with `φ P = 0`, where nothing can be rewritten. But
  the certificate is affine-linear in `y`: its difference is `y·p(x) + q(x)` for
  two explicit polynomials `p, q` built from `A, B, Cx, D, E` and `c`. At an `x`
  outside the (finite) image of `ker φ ∪ W[2]`, BOTH points `P` and `−P` over it
  are good, and subtracting their two instances leaves
  `(2y + a₁x + a₃)·p(x) = 0` with the first factor nonzero
  (`psi_ne_zero_of_two_nsmul_ne_zero`); so `p` and then `q` have cofinitely many
  roots, hence vanish identically, hence the certificate holds everywhere.

**THE CHECK THAT WOULD REFUTE THE REMAINING LEAF**: a rational map of Weierstrass
curves over a field, in any characteristic, whose pullback of `ω'` is not a
constant multiple of `ω`. (In characteristic `p` the constant may be `0` — the
Frobenius — which is why only `eq_of_isDiffChar` below carries `CharZero`.) -/
theorem exists_isDiffChar [IsAlgClosed F] [W.IsElliptic] [W'.IsElliptic]
    {φ : W.Point →+ W'.Point} (hφ : IsRationalMap φ) :
    ∃ c : F, IsDiffChar φ c := by
  classical
  by_cases hφ0 : φ = 0
  · subst hφ0
    exact ⟨0, isDiffChar_zero⟩
  obtain ⟨A, B, Cx, D, E, hB, hE, hrat⟩ := id hφ
  obtain ⟨c, hc⟩ := exists_diffCharScalar hB hE hrat
  -- The certificate off the kernel, with the `y`-witnesses restored.
  have hcertGood : ∀ P : W.Point, P ≠ 0 → φ P ≠ 0 →
      IsDiffCharCert W W' A B Cx D E c P := by
    intro P hP0 hφP
    have hcol := hc P hP0 hφP
    have hr := hrat P hφP
    unfold IsDiffCharCert
    linear_combination E.eval (veluPointX P) * hcol
      - (2 * c * B.eval (veluPointX P) ^ 2) * hr.2
      - (c * B.eval (veluPointX P) * W'.a₁ * E.eval (veluPointX P)) * hr.1
  -- The certificate is affine-linear in `y`, with polynomial coefficients `p, q`.
  obtain ⟨p, q, hΔ⟩ : ∃ p q : F[X], ∀ P : W.Point,
      IsDiffCharCert W W' A B Cx D E c P ↔
        veluPointY P * p.eval (veluPointX P) + q.eval (veluPointX P) = 0 := by
    refine ⟨C (2 * c) * B ^ 2 * Cx
        - C (2 : F) * (derivative A * B - A * derivative B) * E,
      C c * B * (C (2 : F) * B * D + C W'.a₁ * A * E + C W'.a₃ * B * E)
        - (derivative A * B - A * derivative B) * E * (C W.a₁ * X + C W.a₃),
      fun P => ?_⟩
    unfold IsDiffCharCert
    simp only [eval_sub, eval_add, eval_mul, eval_pow, eval_C, eval_X]
    constructor
    · intro hh; linear_combination hh
    · intro hh; linear_combination hh
  -- Both coefficients vanish at every `x` off a finite set, hence identically.
  have hker : (AddMonoidHom.ker φ : Set W.Point).Finite := hφ.finite_ker hφ0
  have htor : {P : W.Point | (2 : ℕ) • P = 0}.Finite := finite_nsmulKer (by norm_num)
  have hTfin : (veluPointX '' ((AddMonoidHom.ker φ : Set W.Point)
      ∪ {P : W.Point | (2 : ℕ) • P = 0})).Finite := (hker.union htor).image _
  have hpq : ∀ t : F, t ∉ veluPointX '' ((AddMonoidHom.ker φ : Set W.Point)
      ∪ {P : W.Point | (2 : ℕ) • P = 0}) → p.eval t = 0 ∧ q.eval t = 0 := by
    intro t ht
    obtain ⟨P, hP0, hPx⟩ := exists_point_veluPointX_eq (W := W) t
    have hφP : φ P ≠ 0 := fun hcc =>
      ht ⟨P, Or.inl (by simpa [AddMonoidHom.mem_ker] using hcc), hPx⟩
    have hP2 : (2 : ℕ) • P ≠ 0 := fun hcc => ht ⟨P, Or.inr hcc, hPx⟩
    have hψ : 2 * veluPointY P + W.a₁ * veluPointX P + W.a₃ ≠ 0 :=
      psi_ne_zero_of_two_nsmul_ne_zero hP2
    have hnP0 : -P ≠ 0 := neg_ne_zero.2 hP0
    have hφnP : φ (-P) ≠ 0 := by rw [map_neg]; exact neg_ne_zero.2 hφP
    have e1 := (hΔ P).mp (hcertGood P hP0 hφP)
    have e2 := (hΔ (-P)).mp (hcertGood (-P) hnP0 hφnP)
    rw [velu_pointX_neg, velu_pointY_neg P hP0] at e2
    rw [hPx] at e1 e2 hψ
    have hp0 : p.eval t = 0 := by
      have hsub : (2 * veluPointY P + W.a₁ * t + W.a₃) * p.eval t = 0 := by
        linear_combination e1 - e2
      rcases mul_eq_zero.mp hsub with hh | hh
      · exact absurd hh hψ
      · exact hh
    exact ⟨hp0, by linear_combination e1 - veluPointY P * hp0⟩
  have hp0 : p = 0 := Polynomial.eq_zero_of_infinite_isRoot _
    (Set.Infinite.mono (fun t ht => (hpq t ht).1) hTfin.infinite_compl)
  have hq0 : q = 0 := Polynomial.eq_zero_of_infinite_isRoot _
    (Set.Infinite.mono (fun t ht => (hpq t ht).2) hTfin.infinite_compl)
  exact ⟨c, fun hz => absurd hz hφ0, A, B, Cx, D, E, hB, hE, hrat, fun P _ =>
    (hΔ P).mpr (by rw [hp0, hq0]; simp)⟩

/-- **PROVEN** (2026-07-28): the scalar is unique.

If `φ*ω' = c·ω = c'·ω` then `(c − c')·ω = 0`, and `ω ≠ 0`.

**THE PROOF**, which needs *nothing* from the geometry — no invariant-differential
theory, only the two certificates and the finiteness facts of `Isogeny.lean`.

For `φ = 0` both scalars are `0` by the guard clause of `IsDiffChar`; this is the
one place that clause is load-bearing, and without it the statement is FALSE (see
the module docstring). For `φ ≠ 0`:

1. **The `x`-witnesses agree as rational functions.** `x(φP)·B₁ = A₁` and
   `x(φP)·B₂ = A₂` give `A₁B₂ = A₂B₁` at every `x` off the (finite) image of
   `ker φ`, hence — the base field being infinite — as POLYNOMIALS.
2. **Hence so do their derivatives.** Differentiating `A₁B₂ = A₂B₁` and taking a
   two-term `linear_combination` yields
   `(A₁′B₁ − A₁B₁′)·B₂² = (A₂′B₂ − A₂B₂′)·B₁²`, the cleared-denominator form of
   `(A₁/B₁)′ = (A₂/B₂)′`.
3. **The `y`-witnesses are irrelevant.** Feeding both rational-map certificates
   into `IsDiffCharCert` turns it into `c·B²·E·ψ'(φP) = (A′B − AB′)·E·ψ(P)`, and
   `E(x) ≠ 0` cancels: `Cx, D, E` disappear from the identity entirely.
4. **One good point finishes it.** Cross-multiplying the two collapsed identities
   with step 2 gives `(c − c')·B₁²B₂²·ψ'(φP) = 0`. Choose `P` with `B₁, B₂, E₁, E₂`
   nonvanishing at `x P` and `2•(φ P) ≠ 0` — possible because
   `ker(φ ∘ [2])` is finite (`[2]` is surjective, so `φ ∘ [2] ≠ 0`) and each
   polynomial has finitely many roots — and `ψ'(φP) ≠ 0` by
   `psi_ne_zero_of_two_nsmul_ne_zero`.

**THE CHECK THAT WOULD REFUTE THIS**: a nonzero rational map with two witness
tuples giving different scalars. -/
theorem isDiffChar_unique [IsAlgClosed F] [W.IsElliptic] [W'.IsElliptic]
    {φ : W.Point →+ W'.Point} {c c' : F}
    (h : IsDiffChar φ c) (h' : IsDiffChar φ c') : c = c' := by
  classical
  by_cases hφ0 : φ = 0
  · rw [h.1 hφ0, h'.1 hφ0]
  obtain ⟨-, A₁, B₁, C₁, D₁, E₁, hB₁, hE₁, hrat₁, hcert₁⟩ := h
  obtain ⟨-, A₂, B₂, C₂, D₂, E₂, hB₂, hE₂, hrat₂, hcert₂⟩ := h'
  have hrm : IsRationalMap φ := ⟨A₁, B₁, C₁, D₁, E₁, hB₁, hE₁, hrat₁⟩
  -- **Step 1.** `A₁/B₁` and `A₂/B₂` are the same rational function.
  have hXker : (veluPointX '' (AddMonoidHom.ker φ : Set W.Point)).Finite :=
    (hrm.finite_ker hφ0).image _
  have hsub : (veluPointX '' (AddMonoidHom.ker φ : Set W.Point))ᶜ
      ⊆ {t : F | IsRoot (A₁ * B₂ - A₂ * B₁) t} := by
    intro t ht
    obtain ⟨P, hP0, hPx⟩ := exists_point_veluPointX_eq (W := W) t
    have hφP : φ P ≠ 0 := fun hc =>
      ht ⟨P, by simpa [AddMonoidHom.mem_ker] using hc, hPx⟩
    have h1 := (hrat₁ P hφP).1
    have h2 := (hrat₂ P hφP).1
    rw [hPx] at h1 h2
    show (A₁ * B₂ - A₂ * B₁).eval t = 0
    simp only [eval_sub, eval_mul]
    linear_combination B₁.eval t * h2 - B₂.eval t * h1
  have hkey : A₁ * B₂ = A₂ * B₁ := by
    have := Polynomial.eq_zero_of_infinite_isRoot (A₁ * B₂ - A₂ * B₁)
      (Set.Infinite.mono hsub hXker.infinite_compl)
    linear_combination this
  -- **Step 2.** So do their derivatives, in cleared-denominator form.
  have hpolyD : (derivative A₁ * B₁ - A₁ * derivative B₁) * B₂ ^ 2
      = (derivative A₂ * B₂ - A₂ * derivative B₂) * B₁ ^ 2 := by
    have hd := congrArg derivative hkey
    simp only [derivative_mul] at hd
    linear_combination (B₁ * B₂) * hd
      - (derivative B₁ * B₂ + B₁ * derivative B₂) * hkey
  -- **Step 3.** A point where nothing degenerates.
  have hrm2 : IsRationalMap (φ.comp (mulByHom W 2)) :=
    IsRationalMap.comp (isRationalMap_mulByHom_two (W := W)) hrm
  have hne2 : φ.comp (mulByHom W 2) ≠ 0 := by
    intro hcc
    refine hφ0 (AddMonoidHom.ext fun Q => ?_)
    obtain ⟨P, hP⟩ := nsmul_surjective (W := W) (n := 2) two_ne_zero Q
    have hz := DFunLike.congr_fun hcc P
    simp only [AddMonoidHom.comp_apply, mulByHom_apply, AddMonoidHom.zero_apply] at hz
    have hP' : (2 : ℕ) • P = Q := hP
    rw [← hP']
    simpa using hz
  have hker2 : (AddMonoidHom.ker (φ.comp (mulByHom W 2)) : Set W.Point).Finite :=
    hrm2.finite_ker hne2
  have hfin : (veluPointX '' (AddMonoidHom.ker (φ.comp (mulByHom W 2)) : Set W.Point)
      ∪ ({t : F | IsRoot B₁ t} ∪ {t : F | IsRoot B₂ t}
        ∪ ({t : F | IsRoot E₁ t} ∪ {t : F | IsRoot E₂ t}))).Finite :=
    (hker2.image _).union
      (((Polynomial.finite_setOf_isRoot hB₁).union
          (Polynomial.finite_setOf_isRoot hB₂)).union
        ((Polynomial.finite_setOf_isRoot hE₁).union
          (Polynomial.finite_setOf_isRoot hE₂)))
  obtain ⟨t, ht⟩ := hfin.infinite_compl.nonempty
  simp only [Set.mem_compl_iff, Set.mem_union, Set.mem_setOf_eq, IsRoot.def,
    not_or] at ht
  obtain ⟨htk, ⟨htB₁, htB₂⟩, htE₁, htE₂⟩ := ht
  obtain ⟨P, hP0, hPx⟩ := exists_point_veluPointX_eq (W := W) t
  have hmemk : ∀ (_ : φ (2 • P) = 0), False := fun hc =>
    htk ⟨P, by simpa [AddMonoidHom.mem_ker] using hc, hPx⟩
  have hφP : φ P ≠ 0 := fun hc => hmemk (by rw [map_nsmul, hc, smul_zero])
  have hP2 : (2 : ℕ) • φ P ≠ 0 := fun hc => hmemk (by rw [map_nsmul]; exact hc)
  have hpsi' : 2 * veluPointY (φ P) + W'.a₁ * veluPointX (φ P) + W'.a₃ ≠ 0 :=
    psi_ne_zero_of_two_nsmul_ne_zero hP2
  -- **Step 4.** Both certificates collapse to `c·B²·ψ'(φP) = (A′B − AB′)·ψ(P)`.
  have hcollapse : ∀ (A B Cw Dw Ew : F[X]) (d : F),
      (∀ Q : W.Point, φ Q ≠ 0 →
        veluPointX (φ Q) * B.eval (veluPointX Q) = A.eval (veluPointX Q) ∧
        veluPointY (φ Q) * Ew.eval (veluPointX Q)
          = Cw.eval (veluPointX Q) * veluPointY Q + Dw.eval (veluPointX Q)) →
      (∀ Q : W.Point, Q ≠ 0 → IsDiffCharCert W W' A B Cw Dw Ew d Q) →
      Ew.eval t ≠ 0 →
      d * B.eval t ^ 2
          * (2 * veluPointY (φ P) + W'.a₁ * veluPointX (φ P) + W'.a₃)
        = ((derivative A).eval t * B.eval t - A.eval t * (derivative B).eval t)
            * (2 * veluPointY P + W.a₁ * t + W.a₃) := by
    intro A B Cw Dw Ew d hrat hcert hEt
    have hc1 := hcert P hP0
    have hr1 := hrat P hφP
    unfold IsDiffCharCert at hc1
    rw [hPx] at hc1 hr1
    refine mul_right_cancel₀ hEt ?_
    linear_combination hc1 + (2 * d * B.eval t ^ 2) * hr1.2
      + (d * B.eval t * W'.a₁ * Ew.eval t) * hr1.1
  have hd₁ := hcollapse A₁ B₁ C₁ D₁ E₁ c hrat₁ hcert₁ htE₁
  have hd₂ := hcollapse A₂ B₂ C₂ D₂ E₂ c' hrat₂ hcert₂ htE₂
  -- **Step 5.** Cross-multiply and cancel.
  have hpolyD' : ((derivative A₁).eval t * B₁.eval t - A₁.eval t * (derivative B₁).eval t)
        * B₂.eval t ^ 2
      = ((derivative A₂).eval t * B₂.eval t - A₂.eval t * (derivative B₂).eval t)
        * B₁.eval t ^ 2 := by
    have hev := congrArg (Polynomial.eval t) hpolyD
    simpa only [eval_mul, eval_sub, eval_pow] using hev
  have hfinal : (c - c') * (B₁.eval t ^ 2 * B₂.eval t ^ 2
      * (2 * veluPointY (φ P) + W'.a₁ * veluPointX (φ P) + W'.a₃)) = 0 := by
    linear_combination B₂.eval t ^ 2 * hd₁ - B₁.eval t ^ 2 * hd₂
      + (2 * veluPointY P + W.a₁ * t + W.a₃) * hpolyD'
  rcases mul_eq_zero.mp hfinal with hcc | hcc
  · exact sub_eq_zero.mp hcc
  · exact absurd hcc (mul_ne_zero
      (mul_ne_zero (pow_ne_zero 2 htB₁) (pow_ne_zero 2 htB₂)) hpsi')

/-- **LEAF: `λ` is additive.**

`(φ + ψ)*ω' = φ*ω' + ψ*ω'`, because pullback of differentials along the addition
map `W × W → W` is additive on invariant differentials (Silverman *AEC* III.5.2:
`ω` is invariant, so `μ*ω = pr₁*ω + pr₂*ω` on `W' × W'`, and composing with
`(φ, ψ)` gives the claim).

The sum of two rational maps is rational (`IsRationalMap.add`, PROVEN in
`Isogeny.lean`), so the statement is not vacuous; note that `IsIsogeny.add` is
FALSE (see the falsity audit there) — which is exactly why `IsDiffChar` is built
over `IsRationalMap` rather than over `IsIsogeny`.

**THE CHECK THAT WOULD REFUTE THIS LEAF**: two rational maps whose sum acts on
`ω` by something other than the sum of their scalars. -/
theorem isDiffChar_add [IsAlgClosed F] [W.IsElliptic] [W'.IsElliptic]
    {φ ψ : W.Point →+ W'.Point} {c d : F}
    (hφ : IsDiffChar φ c) (hψ : IsDiffChar ψ d) :
    IsDiffChar (φ + ψ) (c + d) :=
  sorry

/-- **LEAF: `λ` is multiplicative on composites.**

`(ψ ∘ φ)*ω'' = φ*(ψ*ω'') = φ*(d·ω') = d·(φ*ω') = (d·c)·ω`. Purely formal from
functoriality of pullback; the content is that the certificate of the composite
is obtained by substituting the witnesses of `φ` into those of `ψ`, which is the
same substitution `IsRationalMap.comp` performs.

**THE CHECK THAT WOULD REFUTE THIS LEAF**: two composable rational maps whose
composite acts on `ω` by something other than the product of their scalars. -/
theorem isDiffChar_comp [IsAlgClosed F] [W.IsElliptic] [W'.IsElliptic]
    [W''.IsElliptic] {φ : W.Point →+ W'.Point} {ψ : W'.Point →+ W''.Point}
    {c d : F} (hφ : IsDiffChar φ c) (hψ : IsDiffChar ψ d) :
    IsDiffChar (ψ.comp φ) (d * c) :=
  sorry

/-- **LEAF: `λ` is injective, in characteristic zero.**

If `φ*ω' = ψ*ω'` then `(φ − ψ)*ω' = 0`, and a rational map killing the invariant
differential is INSEPARABLE, hence constant in characteristic zero, hence `0`
(it is a group homomorphism). Concretely: `f' = 0` forces `f = A/B` constant, and
`eq_zero_of_constX` (PROVEN in `Isogeny.lean`) then gives `φ − ψ = 0`.

`CharZero` is essential and cannot be dropped: in characteristic `p` the
Frobenius is a nonzero isogeny with `λ = 0`.

**THE CHECK THAT WOULD REFUTE THIS LEAF**: two distinct rational maps of
Weierstrass curves over a field of characteristic zero acting by the same scalar
on the invariant differential. -/
theorem eq_of_isDiffChar [IsAlgClosed F] [CharZero F] [W.IsElliptic]
    [W'.IsElliptic] {φ ψ : W.Point →+ W'.Point} {c : F}
    (hφ : IsDiffChar φ c) (hψ : IsDiffChar ψ c) : φ = ψ :=
  sorry

/-! ### Consequences of the leaves, PROVEN -/

/-- `λ(−φ) = −λ(φ)`, from `−φ = (−1) ∘ φ` and `isDiffChar_neg_id`. -/
theorem isDiffChar_neg [IsAlgClosed F] [W.IsElliptic] [W'.IsElliptic]
    {φ : W.Point →+ W'.Point} {c : F} (h : IsDiffChar φ c) :
    IsDiffChar (-φ) (-c) := by
  have hcomp : IsDiffChar ((-(AddMonoidHom.id W'.Point)).comp φ) ((-1) * c) :=
    isDiffChar_comp h isDiffChar_neg_id
  have hEq : (-(AddMonoidHom.id W'.Point)).comp φ = -φ := by
    ext P; rfl
  rw [hEq, neg_one_mul] at hcomp
  exact hcomp

/-- `λ([n]) = n` for a natural number `n`, by induction from `λ(0) = 0`,
`λ(1) = 1` and additivity. -/
theorem isDiffChar_mulByHom [IsAlgClosed F] [W.IsElliptic] (n : ℕ) :
    IsDiffChar (mulByHom W n) (n : F) := by
  induction n with
  | zero =>
      have hEq : mulByHom W 0 = (0 : W.Point →+ W.Point) := by ext P; simp
      rw [hEq]; simpa using (isDiffChar_zero (W := W) (W' := W))
  | succ n ih =>
      have hEq : mulByHom W (n + 1) = mulByHom W n + AddMonoidHom.id W.Point := by
        ext P; simp [succ_nsmul]
      have hsum := isDiffChar_add ih (isDiffChar_id (W := W))
      rw [hEq]
      have hcast : ((n + 1 : ℕ) : F) = (n : F) + 1 := by push_cast; ring
      rw [hcast]
      exact hsum

end General

/-! ### Galois equivariance over `ℚ`

The statement below is the one the level-`49` argument consumes. It is stated in
the concrete setting `E/ℚ` base changed to `ℚ̄`, because that is where the
coefficients `a₁, a₃` of the curve are `σ`-fixed — which is exactly what makes
the equivariance true. -/

section Galois

variable [DecidableEq (AlgebraicClosure ℚ)]

/-- **LEAF: `λ` is Galois-equivariant**, `λ(φ^σ) = σ(λ φ)`.

For `E/ℚ` and `σ ∈ Gal(ℚ̄/ℚ)`, the conjugate `φ^σ = σ ∘ φ ∘ σ⁻¹` of a rational
map of `E_ℚ̄` is rational with the `σ`-conjugated witnesses `A.map σ, …, E.map σ`
(this is the transport proven as `MazurLevelFortyNine.isIsogeny_galConj`, from
`velu_pointX_map`, `velu_pointY_map` and `velu_point_map_symm_map`). Applying `σ`
to the differential certificate of `φ` at `σ⁻¹ P` turns it into the certificate
of `φ^σ` at `P` with scalar `σ c`: `σ` is a ring homomorphism, it commutes with
`eval` (`Polynomial.eval₂_at_apply`) and with `derivative` (`derivative_map`),
and it FIXES `a₁` and `a₃`, which lie in the base field `ℚ`.

Equivalently and more conceptually: `ω` is defined over `ℚ`, so `ω^σ = ω`, and
`(φ^σ)*ω = (φ*ω)^σ = (λ(φ)·ω)^σ = σ(λ(φ))·ω`.

**THE CHECK THAT WOULD REFUTE THIS LEAF**: a curve over `ℚ`, an endomorphism of
`E_ℚ̄` and a `σ` with `λ(φ^σ) ≠ σ(λ φ)`. -/
theorem isDiffChar_galConj (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ)
    (φ : (E⁄(AlgebraicClosure ℚ)).Point →+ (E⁄(AlgebraicClosure ℚ)).Point)
    (c : AlgebraicClosure ℚ) (h : IsDiffChar φ c) :
    IsDiffChar ((Affine.Point.map (W' := E) σ.toAlgHom).comp
      (φ.comp (Affine.Point.map (W' := E) σ.symm.toAlgHom))) (σ c) :=
  sorry

end Galois

end WeierstrassCurve
