/-
DifferentialCharacter.lean — own work for the Fermat project (not vendored).

**The action of an isogeny on the invariant differential**, cut 2026-07-28 out
of the single sorry leaf `MazurLevelFortyNine.exists_sqrtNegOne_galSign` in
`Fermat/FLT/FreyCurve/MazurTorsion.lean`, which is *ATAEC* II.2.2 — "the CM
field is the field of definition of the endomorphisms" — in the exact form the
level-`49` argument consumes.

## What this file builds

For a Weierstrass curve `W` the **invariant differential** is
`ω = dx / (2y + a₁x + a₃)`, and a rational map `φ : W → W'` pulls `ω'` back to a
scalar multiple of `ω`:

  `φ*ω' = λ(φ) · ω`,   `λ(φ) ∈ F`.

`λ` is additive, multiplicative on composites, restricts to the identity on `ℤ`,
is INJECTIVE in characteristic zero, and is Galois-equivariant. Those five facts
are what make `End(E_ℚ̄)` a commutative ring embedded in `ℚ̄` and pin the field
of definition of an endomorphism to the field generated by its `λ`-value — which
is the whole content of *ATAEC* II.2.2 for the case at hand.

## How `λ` is written here: a RELATION, not a function

`λ` is not introduced as a function. Its defining equation is a polynomial
identity in the rational-map witnesses of `φ`, and it is stated as the relation
`IsDiffChar φ c` ("`φ` acts on the invariant differential by `c`"). Every fact
about `λ` is then a statement about that relation, and the choice-free
formulation costs nothing: `isDiffChar_unique` says the scalar is unique, which
is all a function would have bought.

Concretely, if `IsRationalMap φ` is witnessed by `A, B, C, D, E` with

  `x ∘ φ = A/B`,  `y ∘ φ = (C·y + D)/E`

then, writing `f = A/B` and `g = (C·y + D)/E`,

  `φ*ω' = d f / (2g + a₁'f + a₃')
        = f' · (2y + a₁x + a₃) / (2g + a₁'f + a₃') · ω`

so `λ(φ) = f'·(2y + a₁x + a₃)/(2g + a₁'f + a₃')`. Clearing denominators
(`f' = (A'B − AB')/B²`) gives the identity in `isDiffChar_certificate` below,
which is what `IsDiffChar` asserts, at every affine point.

Two sanity checks are PROVEN here rather than asserted, and they are what pins
the normalisation: `isDiffChar_id` (`λ(1) = 1`) and `isDiffChar_neg_id`
(`λ(−1) = −1`).

## The degenerate-witness trap, and the `φ = 0 → c = 0` clause

`IsRationalMap`'s certificate is quantified over the points where `φ P ≠ 0`, so
for `φ = 0` it is VACUOUS and *any* tuple `A, …, E` is a legal witness. Without a
guard, `IsDiffChar 0 c` would therefore hold for every `c` that occurs at all
(take the witnesses of the identity map and get `IsDiffChar 0 1`), and both
`isDiffChar_unique` and `isDiffChar_add` would be FALSE. The definition carries
the explicit clause `φ = 0 → c = 0` for exactly this reason; it is the only
place where the zero map needs separate handling, and with it in place
uniqueness needs no `φ ≠ 0` hypothesis.

## The leaves — STATUS AS OF 2026-07-28

`isDiffChar_id`, `isDiffChar_zero`, `isDiffChar_neg_id`, `isDiffChar_neg` and
`isDiffChar_mulByHom` are PROVEN, and so now are three of the six geometric facts:

* `isDiffChar_unique` — that scalar is unique. **PROVEN.**
* `eq_of_isDiffChar` — `λ` is injective (characteristic zero). **PROVEN**, over
  `eq_zero_of_isDiffChar_zero` (also proven here); it consumes `isDiffChar_add`
  and `isDiffChar_comp`, so it is transitively sorried with nothing left to prove.
* `isDiffChar_galConj` — `λ(φ^σ) = σ(λ φ)` for `σ ∈ Gal(ℚ̄/ℚ)`. **PROVEN.**

**STALE LIST, CORRECTED 2026-07-28.** This paragraph used to say "still open, and
these three are the whole remaining mathematics of the file: `exists_isDiffChar`,
`isDiffChar_add`, `isDiffChar_comp`". Two of those three have since been closed in
this very file — `isDiffChar_comp` outright (via the `homogSubst` chain rule) and
`isDiffChar_add` as an assembly over the five-way branch split. The list as it
stands is:

* `isDiffChar_comp` — `λ` is multiplicative on composites. **PROVEN.**
* `isDiffChar_add` — `λ` is additive. **PROVEN as an assembly**; four of its five
  branches are discharged, the fifth is `isDiffChar_add_of_ne` below.
* `isDiffChar_two` — `[2]*ω = 2ω`, the doubling branch. **PROVEN** (2026-07-28),
  from `PsiSumCompanion.wronskian` at `n = 2` plus `eval_preΨ₄_two`.

Genuinely still open, and these two are the whole remaining mathematics:

* `exists_isDiffChar` — every rational map acts on `ω` by some scalar;
* `isDiffChar_add_of_ne` — the CHORD branch of additivity. Its docstring carries
  the mapped route, including that the differentiated chord addition law is
  already proven (sorry-free) as `PsiSumCompanion.DK_addition_step`.

**Do not attack them from the raw definition.** The section "What the certificate
really says" below is PROVEN infrastructure written for exactly this purpose:
`isDiffCharCert_reduced` / `isDiffCharCert_of_reduced` show that, given the
rational-map relations, the certificate is EQUIVALENT to

  `c · B(x)² · E(x) · ψ₂(φP) = (A'B − AB')(x) · E(x) · ψ₂(P)`,   `ψ₂ = 2y + a₁x + a₃`,

with no nonvanishing hypotheses in either direction; and
`isDiffCharCert_of_cofinite` shows the certificate need only be checked at the
points whose `x`-coordinate avoids ONE finite set of the prover's choosing, so
`φP ≠ 0`, `B(x) ≠ 0`, `E(x) ≠ 0`, `ψ₂(P) ≠ 0` and `ψ₂(φP) ≠ 0` are all free.

With that, `isDiffChar_comp` reduced to the CHAIN RULE for the composite
`x`-witnesses produced by `IsRationalMap.comp` (i.e. to a `homogSubst`
derivative identity) — that is how it was closed — and `isDiffChar_add` to the
corresponding statement for the chord/duplication witnesses of
`IsRationalMap.add`. The duplication half of that is now `isDiffChar_two`,
PROVEN; the chord half is `isDiffChar_add_of_ne`, the last derivative identity in
the file.

Reference: Silverman, *AEC* III.5 (the invariant differential and its
functoriality), *ATAEC* II.2.
-/
module

public import Fermat.FLT.EllipticCurve.Isogeny
-- `PsiSumCompanion.wronskian` (`Φₙ′ΨSqₙ − ΦₙΨSqₙ′ = n·preΨ₂ₙ`, sorry-free, any
-- commutative ring) is the `x`-side of `isDiffChar_two` at `n = 2`.
public import Fermat.FLT.EllipticCurve.WronskianInduction

@[expose] public section

open WeierstrassCurve WeierstrassCurve.Affine

namespace WeierstrassCurve

open _root_.Polynomial

section General

variable {F : Type*} [Field F] [DecidableEq F] {W W' W'' : Affine F}

/-- **The polynomial certificate for `φ*ω' = c·ω`.**

With `x = x(P)`, `y = y(P)`, `f = A/B = x ∘ φ` and `g = (C·y + D)/E = y ∘ φ`, the
equation `λ(φ)·(2g + a₁'·f + a₃') = f'·(2y + a₁x + a₃)` becomes, after clearing
`B²` and `E`,

  `c · B · (2·B·(C·y + D) + a₁'·A·E + a₃'·B·E)
     = (A'·B − A·B')·E·(2y + a₁x + a₃)`.

The primed coefficients are those of the TARGET curve `W'` (they come from
`y(φP)`), the unprimed ones from the SOURCE curve `W` (they come from `ω`). -/
def IsDiffCharCert (W : Affine F) (W' : Affine F) (A B C D E : F[X]) (c : F)
    (P : W.Point) : Prop :=
  c * (B.eval (veluPointX P) *
        (2 * B.eval (veluPointX P)
              * (C.eval (veluPointX P) * veluPointY P + D.eval (veluPointX P))
          + W'.a₁ * A.eval (veluPointX P) * E.eval (veluPointX P)
          + W'.a₃ * B.eval (veluPointX P) * E.eval (veluPointX P)))
    = ((derivative A).eval (veluPointX P) * B.eval (veluPointX P)
          - A.eval (veluPointX P) * (derivative B).eval (veluPointX P))
        * E.eval (veluPointX P)
        * (2 * veluPointY P + W.a₁ * veluPointX P + W.a₃)

/-- **`φ` acts on the invariant differential by the scalar `c`**, i.e.
`φ*ω' = c·ω` where `ω = dx/(2y + a₁x + a₃)`.

The witnesses `A, B, C, D, E` are the rational-map witnesses of `φ` (so
`IsDiffChar φ c → IsRationalMap φ`), and the extra requirement is the
differential certificate at every affine point.

The clause `φ = 0 → c = 0` is NOT redundant: `IsRationalMap`'s certificate is
vacuous for `φ = 0`, so without it every scalar would be a legal
differential character of the zero map. See the module docstring. -/
def IsDiffChar (φ : W.Point →+ W'.Point) (c : F) : Prop :=
  (φ = 0 → c = 0) ∧
  ∃ A B C D E : F[X], B ≠ 0 ∧ E ≠ 0 ∧
    (∀ P : W.Point, φ P ≠ 0 →
      veluPointX (φ P) * B.eval (veluPointX P) = A.eval (veluPointX P) ∧
      veluPointY (φ P) * E.eval (veluPointX P)
        = C.eval (veluPointX P) * veluPointY P + D.eval (veluPointX P)) ∧
    (∀ P : W.Point, P ≠ 0 → IsDiffCharCert W W' A B C D E c P)

/-! ### The three normalisations, PROVEN

These are the non-vacuity witnesses for `IsDiffChar`: they exhibit the relation
holding at the three values that pin its normalisation, `λ(0) = 0`, `λ(1) = 1`
and `λ(−1) = −1`. Each is a direct computation with explicit witnesses. -/

/-- `λ(0) = 0`, with the witnesses `A = 0`, `B = 1`, `C = D = 0`, `E = 1`: both
sides of the certificate vanish. -/
theorem isDiffChar_zero : IsDiffChar (0 : W.Point →+ W'.Point) 0 := by
  refine ⟨fun _ => rfl, 0, 1, 0, 0, 1, one_ne_zero, one_ne_zero,
    fun P hP => absurd (AddMonoidHom.zero_apply P) hP, fun P _ => ?_⟩
  simp [IsDiffCharCert]

omit [DecidableEq F] in
/-- An elliptic curve over an algebraically closed field has a nonzero point;
this is what makes `AddMonoidHom.id W.Point` nonzero, hence lets
`isDiffChar_id` and `isDiffChar_neg_id` discharge the guard clause of
`IsDiffChar`. -/
theorem exists_point_ne_zero [IsAlgClosed F] [W.IsElliptic] :
    ∃ P : W.Point, P ≠ 0 := by
  obtain ⟨P, hP, -⟩ := exists_point_veluPointX_eq (W := W) 0
  exact ⟨P, hP⟩

/-- `λ(1) = 1`, with the witnesses `A = X`, `B = 1`, `C = 1`, `D = 0`, `E = 1`:
the certificate reads `2y + a₁x + a₃ = 2y + a₁x + a₃`. -/
theorem isDiffChar_id [IsAlgClosed F] [W.IsElliptic] :
    IsDiffChar (AddMonoidHom.id W.Point) 1 := by
  refine ⟨fun hc => ?_, X, 1, 1, 0, 1, one_ne_zero, one_ne_zero,
    fun P _ => by simp, fun P _ => ?_⟩
  · obtain ⟨Q, hQ⟩ := exists_point_ne_zero (W := W)
    exact absurd (DFunLike.congr_fun hc Q) hQ
  · simp only [IsDiffCharCert, eval_X, eval_one, eval_zero, derivative_X,
      derivative_one]
    ring

/-- `λ(−1) = −1`, with the witnesses `A = X`, `B = 1`, `C = −1`,
`D = −(a₁X + a₃)`, `E = 1`: the `y`-witness is `negY`, and the certificate reads
`(−1)·(−(2y + a₁x + a₃)) = 2y + a₁x + a₃`. -/
theorem isDiffChar_neg_id [IsAlgClosed F] [W.IsElliptic] :
    IsDiffChar (-(AddMonoidHom.id W.Point)) (-1) := by
  refine ⟨fun hc => ?_, X, 1, -1, -(C W.a₁ * X + C W.a₃), 1,
    one_ne_zero, one_ne_zero, fun P hP => ?_, fun P _ => ?_⟩
  · obtain ⟨Q, hQ⟩ := exists_point_ne_zero (W := W)
    have : -Q = 0 := DFunLike.congr_fun hc Q
    exact absurd (by simpa using congrArg (fun R : W.Point => -R) this) hQ
  · have hP0 : P ≠ 0 := fun hc => hP (by rw [hc]; simp)
    have happ : (-(AddMonoidHom.id W.Point)) P = -P := rfl
    rw [happ]
    refine ⟨by simpa using velu_pointX_neg (W := W) P, ?_⟩
    rw [velu_pointY_neg P hP0]
    simp only [eval_one, eval_neg, eval_add, eval_mul, eval_C, eval_X, mul_one]
    ring
  · simp only [IsDiffCharCert, eval_X, eval_one, eval_zero, eval_neg, eval_add,
      eval_mul, eval_C, derivative_X, derivative_one]
    ring

/-! ### What the certificate really says, PROVEN

Six facts that turn `IsDiffCharCert` from a nine-term polynomial identity into
something one can compute with. They are what the closed leaves below rest on,
and they are the tools the three still-open leaves need — read them before
attacking `exists_isDiffChar`, `isDiffChar_add` or `isDiffChar_comp`.

The first two are the heart: SUBSTITUTING the rational-map relations
`x(φP)·B = A` and `y(φP)·E = C·y + D` into the certificate collapses it to

  `c · B(x)² · E(x) · ψ₂(φP) = (A'B − AB')(x) · E(x) · ψ₂(P)`,

where `ψ₂(Q) = 2y(Q) + a₁x(Q) + a₃` is the denominator of `ω`. Away from the
zeros of `B` and `E` this is literally `c = f'(x)·ψ₂(P)/ψ₂(φP)` with
`f = A/B = x ∘ φ`, i.e. the definition of `λ(φ)` in Silverman *AEC* III.5. The
equivalence needs NO nonvanishing hypothesis — both directions are one
`linear_combination`. -/

/-- **The certificate, reduced through the rational-map relations.** -/
theorem isDiffCharCert_reduced {A B C D G : F[X]} {c : F} {φ : W.Point →+ W'.Point}
    {P : W.Point}
    (hx : veluPointX (φ P) * B.eval (veluPointX P) = A.eval (veluPointX P))
    (hy : veluPointY (φ P) * G.eval (veluPointX P)
        = C.eval (veluPointX P) * veluPointY P + D.eval (veluPointX P))
    (hcert : IsDiffCharCert W W' A B C D G c P) :
    c * B.eval (veluPointX P) ^ 2 * G.eval (veluPointX P)
        * (2 * veluPointY (φ P) + W'.a₁ * veluPointX (φ P) + W'.a₃)
      = ((derivative A).eval (veluPointX P) * B.eval (veluPointX P)
          - A.eval (veluPointX P) * (derivative B).eval (veluPointX P))
        * G.eval (veluPointX P)
        * (2 * veluPointY P + W.a₁ * veluPointX P + W.a₃) := by
  simp only [IsDiffCharCert] at hcert
  linear_combination hcert + (2 * c * B.eval (veluPointX P) ^ 2) * hy
    + (c * W'.a₁ * B.eval (veluPointX P) * G.eval (veluPointX P)) * hx

/-- **The converse of `isDiffCharCert_reduced`**: the reduced identity, together with
the rational-map relations, gives the certificate back. This is the form in which a
certificate should be VERIFIED — the reduced identity has one occurrence of each
witness and no `C·y + D` bookkeeping. -/
theorem isDiffCharCert_of_reduced {A B C D G : F[X]} {c : F} {φ : W.Point →+ W'.Point}
    {P : W.Point}
    (hx : veluPointX (φ P) * B.eval (veluPointX P) = A.eval (veluPointX P))
    (hy : veluPointY (φ P) * G.eval (veluPointX P)
        = C.eval (veluPointX P) * veluPointY P + D.eval (veluPointX P))
    (hred : c * B.eval (veluPointX P) ^ 2 * G.eval (veluPointX P)
        * (2 * veluPointY (φ P) + W'.a₁ * veluPointX (φ P) + W'.a₃)
      = ((derivative A).eval (veluPointX P) * B.eval (veluPointX P)
          - A.eval (veluPointX P) * (derivative B).eval (veluPointX P))
        * G.eval (veluPointX P)
        * (2 * veluPointY P + W.a₁ * veluPointX P + W.a₃)) :
    IsDiffCharCert W W' A B C D G c P := by
  simp only [IsDiffCharCert]
  linear_combination hred - (2 * c * B.eval (veluPointX P) ^ 2) * hy
    - (c * W'.a₁ * B.eval (veluPointX P) * G.eval (veluPointX P)) * hx

/-- A nonzero point at which `ψ₂ = 2y + a₁x + a₃` vanishes is `2`-torsion: `ψ₂(Q) = 0`
says exactly that `y(−Q) = y(Q)`, and `x(−Q) = x(Q)` always. -/
theorem add_self_eq_zero_of_denom_eq_zero {Q : W.Point} (hQ : Q ≠ 0)
    (h : 2 * veluPointY Q + W.a₁ * veluPointX Q + W.a₃ = 0) : Q + Q = 0 := by
  have hneg : -Q = Q := by
    refine eq_of_veluPoint_eq (neg_ne_zero.mpr hQ) hQ (velu_pointX_neg Q) ?_
    rw [velu_pointY_neg Q hQ]
    linear_combination -h
  have := congrArg (fun R : W.Point => Q + R) hneg
  simpa using this.symm

/-- **The certificate is a COFINITE condition**, and this is what makes the remaining
leaves tractable: to prove `IsDiffCharCert` at EVERY point it is enough to prove it at
the points whose `x`-coordinate avoids a finite set `S`. So a construction may freely
assume `φ P ≠ 0`, `B(x P) ≠ 0`, `E(x P) ≠ 0`, `ψ₂(P) ≠ 0` and `ψ₂(φP) ≠ 0`.

The mechanism: `y` occurs LINEARLY in the certificate, so its two sides differ by
`q(x)·y + p(x)` for explicit polynomials `q, p`. Evaluating at `R` and at `−R`
and subtracting kills `p` and leaves `q(x)·ψ₂(R) = 0`; off the (finite)
`2`-torsion that forces `q(x) = 0` at infinitely many `x`, hence `q = 0`, hence
`p = 0`. Note the conclusion holds at `P = 0` as well — no hypothesis on `P`. -/
theorem isDiffCharCert_of_cofinite [IsAlgClosed F] [W.IsElliptic]
    {A B Cp D G : F[X]} {c : F} {S : Set F} (hS : S.Finite)
    (h : ∀ Q : W.Point, Q ≠ 0 → veluPointX Q ∉ S → IsDiffCharCert W W' A B Cp D G c Q)
    (P : W.Point) : IsDiffCharCert W W' A B Cp D G c P := by
  classical
  set q : F[X] := Polynomial.C (2 * c) * B ^ 2 * Cp
      - Polynomial.C 2 * (derivative A * B - A * derivative B) * G with hq
  set p : F[X] := Polynomial.C c * B * (Polynomial.C 2 * B * D
        + Polynomial.C W'.a₁ * A * G + Polynomial.C W'.a₃ * B * G)
      - (derivative A * B - A * derivative B) * G
        * (Polynomial.C W.a₁ * Polynomial.X + Polynomial.C W.a₃) with hp
  have hequiv : ∀ Q : W.Point, IsDiffCharCert W W' A B Cp D G c Q ↔
      q.eval (veluPointX Q) * veluPointY Q + p.eval (veluPointX Q) = 0 := by
    intro Q
    simp only [IsDiffCharCert, hq, hp, Polynomial.eval_add, Polynomial.eval_sub,
      Polynomial.eval_mul, Polynomial.eval_pow, Polynomial.eval_C, Polynomial.eval_X]
    constructor <;> intro hh <;> linear_combination hh
  have hbad : (S ∪ veluPointX '' {R : W.Point | (2 : ℕ) • R = 0}).Finite :=
    hS.union ((finite_nsmulKer (W := W) two_ne_zero).image _)
  have hqzero : q = 0 := by
    refine Polynomial.eq_zero_of_infinite_isRoot _
      (Set.Infinite.mono ?_ hbad.infinite_compl)
    intro t ht
    obtain ⟨R, hR0, hRx⟩ := exists_point_veluPointX_eq (W := W) t
    have hRnot : veluPointX R ∉ S := by rw [hRx]; exact fun hc => ht (Or.inl hc)
    have hnegR : veluPointX (-R) ∉ S := by rw [velu_pointX_neg]; exact hRnot
    have e₁ := (hequiv R).mp (h R hR0 hRnot)
    have e₂ := (hequiv (-R)).mp (h (-R) (neg_ne_zero.mpr hR0) hnegR)
    rw [velu_pointX_neg, velu_pointY_neg R hR0] at e₂
    have hden : 2 * veluPointY R + W.a₁ * veluPointX R + W.a₃ ≠ 0 := by
      intro hc
      refine ht (Or.inr ⟨R, ?_, hRx⟩)
      show (2 : ℕ) • R = 0
      rw [two_nsmul]
      exact add_self_eq_zero_of_denom_eq_zero hR0 hc
    show q.eval t = 0
    rw [← hRx]
    have hprod : q.eval (veluPointX R)
        * (2 * veluPointY R + W.a₁ * veluPointX R + W.a₃) = 0 := by
      linear_combination e₁ - e₂
    rcases mul_eq_zero.mp hprod with hc | hc
    · exact hc
    · exact absurd hc hden
  have hpzero : p = 0 := by
    refine Polynomial.eq_zero_of_infinite_isRoot _
      (Set.Infinite.mono ?_ hbad.infinite_compl)
    intro t ht
    obtain ⟨R, hR0, hRx⟩ := exists_point_veluPointX_eq (W := W) t
    have hRnot : veluPointX R ∉ S := by rw [hRx]; exact fun hc => ht (Or.inl hc)
    have e₁ := (hequiv R).mp (h R hR0 hRnot)
    rw [hqzero] at e₁
    simp only [Polynomial.eval_zero, zero_mul, zero_add] at e₁
    show p.eval t = 0
    rw [← hRx]; exact e₁
  refine (hequiv P).mpr ?_
  rw [hqzero, hpzero]
  simp

/-- Two witness pairs computing the `x`-coordinate of the same map with finite kernel
define the SAME rational function: `A₁/B₁ = A₂/B₂` as an identity of polynomials.

Off the (finite) `x`-image of `ker φ` every `t` is the `x`-coordinate of a point not in
the kernel, where both witnesses compute `x(φP)`; so `A₁B₂ − A₂B₁` has infinitely many
roots. -/
theorem diffChar_xWitness_eq [IsAlgClosed F] [W.IsElliptic] {φ : W.Point →+ W'.Point}
    (hker : (AddMonoidHom.ker φ : Set W.Point).Finite) {A₁ B₁ A₂ B₂ : F[X]}
    (h₁ : ∀ P : W.Point, φ P ≠ 0 →
      veluPointX (φ P) * B₁.eval (veluPointX P) = A₁.eval (veluPointX P))
    (h₂ : ∀ P : W.Point, φ P ≠ 0 →
      veluPointX (φ P) * B₂.eval (veluPointX P) = A₂.eval (veluPointX P)) :
    A₁ * B₂ = A₂ * B₁ := by
  have hbad : (veluPointX '' (AddMonoidHom.ker φ : Set W.Point)).Finite := hker.image _
  have hsub : (veluPointX '' (AddMonoidHom.ker φ : Set W.Point))ᶜ
      ⊆ {t : F | (A₁ * B₂ - A₂ * B₁).IsRoot t} := by
    intro t ht
    obtain ⟨P, hP0, hPx⟩ := exists_point_veluPointX_eq (W := W) t
    have hφP : φ P ≠ 0 := fun hc => ht ⟨P, hc, hPx⟩
    have e₁ := h₁ P hφP
    have e₂ := h₂ P hφP
    rw [hPx] at e₁ e₂
    show (A₁ * B₂ - A₂ * B₁).eval t = 0
    simp only [Polynomial.eval_sub, Polynomial.eval_mul]
    linear_combination (-(B₂.eval t)) * e₁ + B₁.eval t * e₂
  have hzero : A₁ * B₂ - A₂ * B₁ = 0 :=
    Polynomial.eq_zero_of_infinite_isRoot _ (Set.Infinite.mono hsub hbad.infinite_compl)
  linear_combination hzero

omit [DecidableEq F] in
/-- **Equal rational functions have equal derivatives**, with denominators cleared:
`A₁B₂ = A₂B₁` implies `(A₁'B₁ − A₁B₁')·B₂² = (A₂'B₂ − A₂B₂')·B₁²`. Differentiating the
hypothesis and eliminating gives the cofactor `(B₁'B₂ + B₂'B₁)·(A₂B₁ − A₁B₂)`. -/
theorem diffChar_wronskian_transfer {A₁ B₁ A₂ B₂ : F[X]} (h : A₁ * B₂ = A₂ * B₁) :
    (derivative A₁ * B₁ - A₁ * derivative B₁) * B₂ ^ 2
      = (derivative A₂ * B₂ - A₂ * derivative B₂) * B₁ ^ 2 := by
  have h' := congrArg derivative h
  simp only [derivative_mul] at h'
  linear_combination (B₁ * B₂) * h' - (derivative B₁ * B₂ + derivative B₂ * B₁) * h

/-- **In characteristic zero a rational function with vanishing derivative is
constant.** Cancel `g = gcd A B` to a coprime pair: the Wronskian is `g²`-homogeneous,
so `A₀'B₀ = A₀B₀'`, hence `B₀ ∣ B₀'` by coprimality, hence `B₀' = 0` by degree, hence
`A₀' = 0`; and `derivative p = 0` forces `p` constant only in characteristic zero. -/
theorem exists_const_of_wronskian_eq_zero [CharZero F] {A B : F[X]} (hB : B ≠ 0)
    (h : derivative A * B - A * derivative B = 0) :
    ∃ lam : F, A = Polynomial.C lam * B := by
  classical
  letI : GCDMonoid F[X] := EuclideanDomain.gcdMonoid F[X]
  obtain ⟨g, A₀, B₀, hgne, hA, hBeq, hcop⟩ :
      ∃ g A₀ B₀ : F[X], g ≠ 0 ∧ A = g * A₀ ∧ B = g * B₀ ∧ IsCoprime A₀ B₀ :=
    ⟨GCDMonoid.gcd A B, A / GCDMonoid.gcd A B, B / GCDMonoid.gcd A B,
      gcd_ne_zero_of_right hB,
      (EuclideanDomain.mul_div_cancel' (gcd_ne_zero_of_right hB) (gcd_dvd_left A B)).symm,
      (EuclideanDomain.mul_div_cancel' (gcd_ne_zero_of_right hB) (gcd_dvd_right A B)).symm,
      isCoprime_div_gcd_div_gcd hB⟩
  have hB₀ : B₀ ≠ 0 := by rintro rfl; rw [mul_zero] at hBeq; exact hB hBeq
  have hkey : g ^ 2 * (derivative A₀ * B₀ - A₀ * derivative B₀) = 0 := by
    rw [hA, hBeq] at h
    simp only [derivative_mul] at h
    linear_combination h
  have hw₀ : derivative A₀ * B₀ - A₀ * derivative B₀ = 0 := by
    rcases mul_eq_zero.mp hkey with hc | hc
    · exact absurd (pow_eq_zero_iff two_ne_zero |>.mp hc) hgne
    · exact hc
  have hdvd : B₀ ∣ derivative B₀ := by
    refine (hcop.symm).dvd_of_dvd_mul_left ?_
    exact ⟨derivative A₀, by linear_combination -hw₀⟩
  have hB₀' : derivative B₀ = 0 := by
    by_contra hne
    have hdeg : B₀.natDegree ≠ 0 := by
      intro hc
      exact hne (by rw [Polynomial.eq_C_of_natDegree_eq_zero hc, derivative_C])
    exact absurd (Polynomial.natDegree_le_of_dvd hdvd hne)
      (not_le.mpr (Polynomial.natDegree_derivative_lt hdeg))
  have hA₀' : derivative A₀ = 0 := by
    have hz : derivative A₀ * B₀ = 0 := by rw [hB₀'] at hw₀; linear_combination hw₀
    rcases mul_eq_zero.mp hz with hc | hc
    · exact hc
    · exact absurd hc hB₀
  obtain ⟨a, hAC⟩ : ∃ a : F, A₀ = Polynomial.C a :=
    ⟨_, Polynomial.eq_C_of_derivative_eq_zero hA₀'⟩
  obtain ⟨b, hBC⟩ : ∃ b : F, B₀ = Polynomial.C b :=
    ⟨_, Polynomial.eq_C_of_derivative_eq_zero hB₀'⟩
  have hbne : b ≠ 0 := by
    intro hc
    rw [hc, map_zero] at hBC
    exact hB₀ hBC
  refine ⟨a / b, ?_⟩
  rw [hA, hBeq, hAC, hBC, ← mul_assoc, mul_comm (Polynomial.C (a / b)) g, mul_assoc,
    ← Polynomial.C_mul, div_mul_cancel₀ _ hbne]

/-- **`λ(φ) = 0` forces `φ = 0` in characteristic zero** — the concrete content of
"a rational map killing `ω` is inseparable". With `c = 0` the reduced certificate reads
`0 = (A'B − AB')(x)·E(x)·ψ₂(P)`; off the zeros of `E`, the `x`-image of `ker φ` and the
`x`-image of the `2`-torsion, both other factors are nonzero, so the Wronskian
`A'B − AB'` has infinitely many roots and vanishes. Then `A = C λ · B` by
`exists_const_of_wronskian_eq_zero` and `eq_zero_of_constX` finishes.

`CharZero` enters exactly once, in `exists_const_of_wronskian_eq_zero`: in
characteristic `p` the Frobenius has `A = X^p`, `A' = 0`, and is not zero. -/
theorem eq_zero_of_isDiffChar_zero [IsAlgClosed F] [CharZero F] [W.IsElliptic]
    {φ : W.Point →+ W'.Point} (h : IsDiffChar φ 0) : φ = 0 := by
  classical
  by_contra hφ0
  obtain ⟨-, A, B, C, D, G, hB, hG, hcert, hdiff⟩ := h
  have hrat : IsRationalMap φ := ⟨A, B, C, D, G, hB, hG, hcert⟩
  have hker : (AddMonoidHom.ker φ : Set W.Point).Finite := hrat.finite_ker hφ0
  have hwr : derivative A * B - A * derivative B = 0 := by
    have hbad : ((veluPointX '' (AddMonoidHom.ker φ : Set W.Point)
        ∪ veluPointX '' {P : W.Point | (2 : ℕ) • P = 0})
        ∪ {t : F | G.eval t = 0}).Finite :=
      ((hker.image _).union ((finite_nsmulKer (W := W) two_ne_zero).image _)).union
        (Polynomial.finite_setOf_isRoot hG)
    have hsub : ((veluPointX '' (AddMonoidHom.ker φ : Set W.Point)
        ∪ veluPointX '' {P : W.Point | (2 : ℕ) • P = 0})
        ∪ {t : F | G.eval t = 0})ᶜ
        ⊆ {t : F | (derivative A * B - A * derivative B).IsRoot t} := by
      intro t ht
      obtain ⟨P, hP0, hPx⟩ := exists_point_veluPointX_eq (W := W) t
      have hφP : φ P ≠ 0 := fun hc => ht (Or.inl (Or.inl ⟨P, hc, hPx⟩))
      have hGt : G.eval t ≠ 0 := fun hc => ht (Or.inr hc)
      have hden : 2 * veluPointY P + W.a₁ * veluPointX P + W.a₃ ≠ 0 := by
        intro hc
        refine ht (Or.inl (Or.inr ⟨P, ?_, hPx⟩))
        show (2 : ℕ) • P = 0
        rw [two_nsmul]
        exact add_self_eq_zero_of_denom_eq_zero hP0 hc
      obtain ⟨hx, hy⟩ := hcert P hφP
      have hred := isDiffCharCert_reduced hx hy (hdiff P hP0)
      rw [hPx] at hred hden
      show (derivative A * B - A * derivative B).eval t = 0
      simp only [Polynomial.eval_sub, Polynomial.eval_mul]
      have hprod : ((derivative A).eval t * B.eval t - A.eval t * (derivative B).eval t)
          * (G.eval t * (2 * veluPointY P + W.a₁ * t + W.a₃)) = 0 := by
        linear_combination -hred
      rcases mul_eq_zero.mp hprod with hc | hc
      · exact hc
      · exact absurd hc (mul_ne_zero hGt hden)
    exact Polynomial.eq_zero_of_infinite_isRoot _
      (Set.Infinite.mono hsub hbad.infinite_compl)
  obtain ⟨lam, hlam⟩ := exists_const_of_wronskian_eq_zero hB hwr
  exact hφ0 (eq_zero_of_constX hB lam hlam (fun P hP => (hcert P hP).1))

/-! ### The open geometry

The statements still sorried below are the remaining leaves of this cut. Each is a
standard fact about the invariant differential (Silverman, *AEC* III.5), and the pin
does not have the invariant differential.

**STALE ABSENCE CLAIM, CORRECTED 2026-07-28.** This paragraph used to end "none of
them is in the mathlib pin, in `~/cs/FLT`, or elsewhere in `Fermat/` … this project
has only the universal Hamiltonian derivation `PsiSumCompanion.DK` of
`InvariantDerivation.lean` … and carries no statement about isogenies." The last
clause is **FALSE**, and it is the load-bearing one.

`Fermat/FLT/EllipticCurve/WronskianInduction.lean` — built on exactly that `DK`, and
SORRY-FREE — proves `[n]*ω = n·ω` in precisely the Wronskian form this file's reduced
certificate consumes:

  `PsiSumCompanion.wronskian (W : WeierstrassCurve R) (hn : 1 ≤ n) :`
  `  Φₙ′ · ΨSqₙ − Φₙ · ΨSqₙ′ = n · preΨ (2n)`

over an ARBITRARY commutative ring `R`, for every `n ≥ 1`. Its file docstring says so
outright: "the coordinates of `n • (tautX, tautY)` satisfy `DK xₙ = n ⬝ ψ₂(nP)` … i.e.
`[n]*ω = n ⬝ ω` for the invariant differential." So the invariant-differential
induction is not missing from this project — it is *done*, at the universal curve, and
descended to every ring. It is reachable (`TorsionCharP.lean` and `TorsionCardSep.lean`
`public import` it).

The check that refutes the old claim in one command:
`grep -rn "theorem wronskian" Fermat/FLT/EllipticCurve/WronskianInduction.lean`.

What this changes concretely: `isDiffChar_two` below is a Wronskian identity between
division polynomials and `PsiSumCompanion.wronskian` at `n = 2` supplies its
`x`-side outright. See that leaf's docstring for what remains.

**How to attack any of them** (2026-07-28, and this is what the block above exists
for). Build witnesses, then verify the certificate through
`isDiffCharCert_of_cofinite` + `isDiffCharCert_of_reduced`: it then suffices to prove

  `c · B(x)² · E(x) · ψ₂(φP) = (A'B − AB')(x) · E(x) · ψ₂(P)`

at the points `P` whose `x`-coordinate avoids one finite set of your choosing — so
`φ P ≠ 0`, `B(x P) ≠ 0`, `E(x P) ≠ 0`, `ψ₂(P) ≠ 0` and `ψ₂(φP) ≠ 0` are all free
hypotheses. Do NOT try to verify the raw nine-term `IsDiffCharCert` at every point;
that is what made these leaves look atomic. -/

/-- **LEAF: every rational map acts on the invariant differential by some
scalar.**

`φ*ω'` is an invariant (translation-invariant) differential on `W`, and the space
of invariant differentials is one-dimensional, spanned by `ω`; so `φ*ω' = c·ω`
for a unique `c`. Equivalently, in the coordinates: the rational function
`f'·(2y + a₁x + a₃)/(2g + a₁'f + a₃')` on `W` is regular and invariant under
translation by every point, hence constant.

**THE ARGUMENT** in the form the certificate wants. Take any witness tuple
`A, …, E` for `IsRationalMap φ`; for `φ = 0` take `A = 0, B = 1, C = D = 0,
E = 1` and `c = 0`, which is the certificate `0 = 0`. For `φ ≠ 0`, differentiate
the two certificate identities of `IsRationalMap` along the Hamiltonian
derivation `D = ψ₂ · d/dx` of `InvariantDerivation.lean`: `D` kills the curve
polynomial, so it acts on the coordinate ring of `W`, and `Dx = ψ₂`,
`Dy = (3x² + 2a₂x + a₄ − a₁y)`. Applying `D` to `x∘φ = A/B` and using the chain
rule gives `D(x∘φ) = f'(x)·ψ₂(x,y)`, while `x∘φ` is the `x`-coordinate of a point
of `W'` so `D(x∘φ) = c·ψ₂(φP)` for the scalar `c` defined by
`c = D(x∘φ)/ψ₂(φP)`. That this last quotient is a CONSTANT — not merely a
rational function — is the one-dimensionality of the space of invariant
differentials, and is what makes the statement a leaf rather than a computation.

**THE CHECK THAT WOULD REFUTE THIS LEAF**: a rational map of Weierstrass curves
over a field, in any characteristic, whose pullback of `ω'` is not a constant
multiple of `ω`. (In characteristic `p` the constant may be `0` — the Frobenius
— which is why only `eq_of_isDiffChar` below carries `CharZero`.) -/
theorem exists_isDiffChar [IsAlgClosed F] [W.IsElliptic] [W'.IsElliptic]
    {φ : W.Point →+ W'.Point} (hφ : IsRationalMap φ) :
    ∃ c : F, IsDiffChar φ c :=
  sorry

/-- **PROVEN 2026-07-28: the scalar is unique.**

For `φ = 0` both scalars are `0` by the guard clause of `IsDiffChar`.

For `φ ≠ 0` the argument runs through the reduced certificate. With witnesses
`A₁, …, E₁` and `A₂, …, E₂`, `diffChar_xWitness_eq` gives `A₁B₂ = A₂B₁` (the two
`x`-witnesses compute the same function off the finite kernel), and
`diffChar_wronskian_transfer` upgrades that to
`(A₁'B₁ − A₁B₁')B₂² = (A₂'B₂ − A₂B₂')B₁²`. Multiplying the reduced certificate of
the first witness tuple by `B₂²E₂` and the second by `B₁²E₁` and subtracting, the
Wronskians cancel and

  `(c − c')·B₁²B₂²·E₁E₂·ψ₂(φP) = 0`.

So if `c ≠ c'` then `ψ₂(φP) = 0` — i.e. `φP` is `2`-torsion — at every `P` off the
zeros of `B₁B₂E₁E₂`, a finite set of `x`-values. Hence `φ + φ` has finite range,
so `φ + φ = 0` by `eq_zero_of_finite_range`; then `range φ` lies in the (finite)
`2`-torsion of `W'` and the same lemma gives `φ = 0`, a contradiction.

Note the proof needs no hypothesis on the characteristic: it is
`eq_of_isDiffChar`, not this, that fails for the Frobenius. -/
theorem isDiffChar_unique [IsAlgClosed F] [W.IsElliptic] [W'.IsElliptic]
    {φ : W.Point →+ W'.Point} {c c' : F}
    (h : IsDiffChar φ c) (h' : IsDiffChar φ c') : c = c' := by
  classical
  by_cases hφ0 : φ = 0
  · rw [h.1 hφ0, h'.1 hφ0]
  by_contra hne
  obtain ⟨-, A₁, B₁, C₁, D₁, G₁, hB₁, hG₁, hcert₁, hdiff₁⟩ := h
  obtain ⟨-, A₂, B₂, C₂, D₂, G₂, hB₂, hG₂, hcert₂, hdiff₂⟩ := h'
  have hrat : IsRationalMap φ := ⟨A₁, B₁, C₁, D₁, G₁, hB₁, hG₁, hcert₁⟩
  have hker : (AddMonoidHom.ker φ : Set W.Point).Finite := hrat.finite_ker hφ0
  have hAB : A₁ * B₂ = A₂ * B₁ :=
    diffChar_xWitness_eq hker (fun P hP => (hcert₁ P hP).1) (fun P hP => (hcert₂ P hP).1)
  have hW := diffChar_wronskian_transfer hAB
  have hBadne : B₁ * B₂ * G₁ * G₂ ≠ 0 :=
    mul_ne_zero (mul_ne_zero (mul_ne_zero hB₁ hB₂) hG₁) hG₂
  have hkill : ∀ P : W.Point, P ≠ 0 →
      (B₁ * B₂ * G₁ * G₂).eval (veluPointX P) ≠ 0 → (φ + φ) P = 0 := by
    intro P hP0 hBadP
    by_cases hφP : φ P = 0
    · show φ P + φ P = 0
      rw [hφP, add_zero]
    simp only [Polynomial.eval_mul] at hBadP
    have hb₁ : B₁.eval (veluPointX P) ≠ 0 := fun hc => hBadP (by rw [hc]; ring)
    have hb₂ : B₂.eval (veluPointX P) ≠ 0 := fun hc => hBadP (by rw [hc]; ring)
    have hg₁ : G₁.eval (veluPointX P) ≠ 0 := fun hc => hBadP (by rw [hc]; ring)
    have hg₂ : G₂.eval (veluPointX P) ≠ 0 := fun hc => hBadP (by rw [hc]; ring)
    obtain ⟨hx₁, hy₁⟩ := hcert₁ P hφP
    obtain ⟨hx₂, hy₂⟩ := hcert₂ P hφP
    have hred₁ := isDiffCharCert_reduced hx₁ hy₁ (hdiff₁ P hP0)
    have hred₂ := isDiffCharCert_reduced hx₂ hy₂ (hdiff₂ P hP0)
    have hWt := congrArg (Polynomial.eval (veluPointX P)) hW
    simp only [Polynomial.eval_mul, Polynomial.eval_sub, Polynomial.eval_pow] at hWt
    have hkey : (c - c') * B₁.eval (veluPointX P) ^ 2 * B₂.eval (veluPointX P) ^ 2
        * G₁.eval (veluPointX P) * G₂.eval (veluPointX P)
        * (2 * veluPointY (φ P) + W'.a₁ * veluPointX (φ P) + W'.a₃) = 0 := by
      linear_combination B₂.eval (veluPointX P) ^ 2 * G₂.eval (veluPointX P) * hred₁
        - B₁.eval (veluPointX P) ^ 2 * G₁.eval (veluPointX P) * hred₂
        + G₁.eval (veluPointX P) * G₂.eval (veluPointX P)
          * (2 * veluPointY P + W.a₁ * veluPointX P + W.a₃) * hWt
    have hden : 2 * veluPointY (φ P) + W'.a₁ * veluPointX (φ P) + W'.a₃ = 0 := by
      have hc0 : c - c' ≠ 0 := sub_ne_zero.mpr hne
      rcases mul_eq_zero.mp hkey with hc | hc
      · exact absurd hc (mul_ne_zero (mul_ne_zero (mul_ne_zero (mul_ne_zero hc0
          (pow_ne_zero 2 hb₁)) (pow_ne_zero 2 hb₂)) hg₁) hg₂)
      · exact hc
    show φ P + φ P = 0
    exact add_self_eq_zero_of_denom_eq_zero hφP hden
  have hfin : (Set.range (φ + φ)).Finite := by
    have hbadset : {P : W.Point | P ≠ 0 ∧
        veluPointX P ∈ {t : F | (B₁ * B₂ * G₁ * G₂).eval t = 0}}.Finite :=
      finite_veluPointX_preimage (Polynomial.finite_setOf_isRoot hBadne)
    refine Set.Finite.subset ((hbadset.image (φ + φ)).insert 0) ?_
    rintro Q ⟨P, rfl⟩
    by_cases hP0 : P = 0
    · exact Set.mem_insert_iff.2 (Or.inl (by rw [hP0]; simp))
    by_cases hBadP : (B₁ * B₂ * G₁ * G₂).eval (veluPointX P) = 0
    · exact Set.mem_insert_iff.2 (Or.inr ⟨P, ⟨hP0, hBadP⟩, rfl⟩)
    · exact Set.mem_insert_iff.2 (Or.inl (hkill P hP0 hBadP))
  have hdouble : (φ + φ) = 0 := eq_zero_of_finite_range hfin
  have hrange : (Set.range φ).Finite := by
    refine Set.Finite.subset (finite_nsmulKer (W := W') two_ne_zero) ?_
    rintro Q ⟨P, rfl⟩
    show (2 : ℕ) • φ P = 0
    rw [two_nsmul]
    simpa using DFunLike.congr_fun hdouble P
  exact hφ0 (eq_zero_of_finite_range hrange)

/-! ### The chain rule for `homogSubst`, PROVEN 2026-07-28

This block is what closes `isDiffChar_comp`, and it is pure one-variable algebra —
no curve, no points. `IsRationalMap.comp` computes the composite's `x`-witnesses as
`homogSubst A B d A'`, `homogSubst A B d B'`, i.e. `B^d·A'(A/B)` and `B^d·B'(A/B)`
with denominators cleared. To evaluate the differential certificate of the composite
one needs the DERIVATIVE of that substitution, and the identity below is exactly the
chain rule with denominators cleared.

It comes from **Euler's relation**. Writing `H(x,y) = ∑ qᵢ xⁱ y^{d−i}` for the
homogenisation of `Q`, so that `homogSubst A B d Q = H(A,B)`:

* `H_x(A,B) = homogSubst A B (d−1) Q'` (differentiating the coefficients);
* `x·H_x + y·H_y = d·H` is Euler's relation, which eliminates `H_y`;
* `(H(A,B))' = A'·H_x(A,B) + B'·H_y(A,B)`.

Combining the three gives `homogSubst_derivative_euler`, and antisymmetrising it in a
pair `A', B'` gives `homogSubst_wronskian` — the form the certificate consumes, since
`λ` is read off a Wronskian `A'B − AB'`. Note both are stated with `B ·` on the left:
that is what makes them denominator-free, and the `B ≠ 0` needed to divide is a
free hypothesis at certificate-checking time by `isDiffCharCert_of_cofinite`. -/

omit [DecidableEq F] in
/-- `homogSubst A B e (derivative Q)`, reindexed so that its `i`-th term matches the
`i`-th term of `homogSubst A B (e+1) Q`. This is `H_x(A,B) = ∑ i·qᵢ·A^{i−1}·B^{d−i}`;
the `i = 0` term vanishes, which is what `Finset.sum_range_succ'` peels off. -/
theorem homogSubst_derivative_reindex {A B Q : F[X]} {e : ℕ} :
    homogSubst A B e (derivative Q)
      = ∑ i ∈ Finset.range (e + 2),
          Polynomial.C ((i : F) * Q.coeff i) * A ^ (i - 1) * B ^ (e + 1 - i) := by
  rw [Finset.sum_range_succ']
  simp only [Nat.cast_zero, zero_mul, map_zero, add_zero]
  unfold homogSubst
  refine Finset.sum_congr rfl fun i _ => ?_
  simp only [Nat.add_sub_cancel, Nat.add_sub_add_right, Polynomial.coeff_derivative]
  push_cast
  rw [mul_comm (Q.coeff (i + 1))]

omit [DecidableEq F] in
/-- **Euler's relation for `homogSubst`: the chain rule with denominators cleared.**

`B·(B^d·Q(A/B))' = (A'B − AB')·B^{d−1}·Q'(A/B) + d·B'·B^d·Q(A/B)`, which is what
`d/dt [B^d Q(A/B)] = B^{d−1}(A'B − AB')Q'(A/B) + d B^{d−1} B' B Q(A/B)` becomes once
the division is cleared. Proven term by term over `Finset.range (d+1)`; the three
`have`s are the natural-subtraction bookkeeping (`i = 0` and `i = d` are the edge
cases, and in each the offending coefficient `C i` or `C (d−i)` is itself zero). -/
theorem homogSubst_derivative_euler {A B Q : F[X]} {d : ℕ} (hd : Q.natDegree ≤ d) :
    B * derivative (homogSubst A B d Q)
      = (derivative A * B - A * derivative B) * homogSubst A B (d - 1) (derivative Q)
        + Polynomial.C ((d : ℕ) : F) * derivative B * homogSubst A B d Q := by
  rcases d with _ | e
  · rw [Polynomial.eq_C_of_natDegree_le_zero hd]
    simp [homogSubst]
  · rw [show e + 1 - 1 = e from rfl, homogSubst_derivative_reindex (A := A) (B := B)
      (Q := Q) (e := e)]
    unfold homogSubst
    rw [Polynomial.derivative_sum, Finset.mul_sum, Finset.mul_sum, Finset.mul_sum,
      ← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl fun i hi => ?_
    have hile : i ≤ e + 1 := Nat.lt_succ_iff.1 (Finset.mem_range.1 hi)
    have hA : Polynomial.C ((i : ℕ) : F) * (A ^ (i - 1) * A)
        = Polynomial.C ((i : ℕ) : F) * A ^ i := by
      rcases Nat.eq_zero_or_pos i with rfl | hpos
      · simp
      · rw [← pow_succ]
        congr 2
        omega
    have hB : Polynomial.C (((e + 1 - i : ℕ)) : F) * (B ^ (e + 1 - i - 1) * B)
        = Polynomial.C (((e + 1 - i : ℕ)) : F) * B ^ (e + 1 - i) := by
      rcases Nat.eq_zero_or_pos (e + 1 - i) with h0 | hpos
      · rw [h0]; simp
      · rw [← pow_succ]
        congr 2
        omega
    have hcast : Polynomial.C (((e + 1 - i : ℕ)) : F) + Polynomial.C ((i : ℕ) : F)
        = Polynomial.C (((e + 1 : ℕ)) : F) := by
      rw [← map_add, ← Nat.cast_add]
      congr 2
      omega
    simp only [Polynomial.derivative_mul, Polynomial.derivative_C,
      Polynomial.derivative_pow, Polynomial.C_mul, zero_mul, zero_add]
    linear_combination (Polynomial.C (Q.coeff i) * A ^ i * derivative B) * hB
      + (Polynomial.C (Q.coeff i) * derivative B * B ^ (e + 1 - i)) * hA
      + (Polynomial.C (Q.coeff i) * A ^ i * derivative B * B ^ (e + 1 - i)) * hcast

omit [DecidableEq F] in
/-- **The Wronskian of a substituted pair.** Antisymmetrising Euler's relation in
`Ap, Bp` kills the `d·B'` term, leaving the clean chain rule

  `B·W(B^d Ap(A/B), B^d Bp(A/B)) = (A'B − AB')·B^{2d−1}·W(Ap,Bp)(A/B)`

in denominator-free form. This is the identity that turns the composite's certificate
into the product of the two factors' certificates. -/
theorem homogSubst_wronskian {A B Ap Bp : F[X]} {d : ℕ}
    (hAp : Ap.natDegree ≤ d) (hBp : Bp.natDegree ≤ d) :
    B * (derivative (homogSubst A B d Ap) * homogSubst A B d Bp
         - homogSubst A B d Ap * derivative (homogSubst A B d Bp))
      = (derivative A * B - A * derivative B)
        * (homogSubst A B (d - 1) (derivative Ap) * homogSubst A B d Bp
           - homogSubst A B d Ap * homogSubst A B (d - 1) (derivative Bp)) := by
  have h1 := homogSubst_derivative_euler (A := A) (B := B) hAp
  have h2 := homogSubst_derivative_euler (A := A) (B := B) hBp
  linear_combination (homogSubst A B d Bp) * h1 - (homogSubst A B d Ap) * h2

/-- **PROVEN 2026-07-28: `λ` is multiplicative on composites.**

`(ψ ∘ φ)*ω'' = φ*(ψ*ω'') = φ*(d·ω') = d·(φ*ω') = (d·c)·ω`. Conceptually formal from
functoriality of pullback; the content is that the certificate of the composite is
obtained by substituting the witnesses of `φ` into those of `ψ`, which is the same
substitution `IsRationalMap.comp` performs — and then DIFFERENTIATING it, which is
`homogSubst_wronskian` above.

**HOW THE PROOF RUNS.** Write `t = x(P)`, `u = x(φP)`, `β = B(t)`.

* The degenerate case `ψ∘φ = 0` is separated first: either `φ = 0` (so `c = 0` by the
  guard clause) or `φ ≠ 0`, whence `φ` is SURJECTIVE (`IsRationalMap.surjective`) and
  `ψ` vanishes on all of `W'`, so `d = 0`. Either way `d·c = 0` and `isDiffChar_zero`
  applies. This is the only place surjectivity is used, and it is why the guard clause
  of `IsDiffChar` costs nothing here.
* Otherwise `x∘φ` is nonconstant (else `eq_zero_of_constX` would give `φ = 0`), so no
  `homogSubst A B n Q` degenerates (`exists_const_of_homogSubst_eq_zero`), and
  likewise `max A'.natDegree B'.natDegree ≥ 1` because a constant `x∘ψ` would give
  `ψ = 0`. Write that maximum as `m+1`.
* The witnesses actually used are whatever `IsRationalMap.comp` returns, NOT the
  `homogSubst` ones. The two families compute the same rational function, so
  `diffChar_xWitness_eq` gives `a·Bc = Ac·b` and `diffChar_wronskian_transfer`
  transports the Wronskian between them. That is what lets the proof reuse
  `IsRationalMap.comp` wholesale instead of rebuilding its case analysis.
* The certificate is then checked off the finite bad set of `x`-values where `B`, `E`,
  `Bc` or `homogSubst A B E'.natDegree E'` vanishes, or where `ψ∘φ` dies
  (`isDiffCharCert_of_cofinite`). There the two reduced certificates
  `c·β²·ψ₂(φP) = (A'B−AB')(t)·ψ₂(P)` and `d·B'(u)²·ψ₂(ψφP) = (A''B'−A'B'')(u)·ψ₂(φP)`
  multiply, `ψ₂(φP)` cancels between them, and `homogSubst_wronskian` supplies the
  missing factor `(A''B'−A'B'')(u)·β^{2m+1}`. Note `ψ₂(φP) ≠ 0` is NOT needed: it
  cancels algebraically rather than being divided out.

**THE CHECK THAT WOULD REFUTE THIS LEAF**: two composable rational maps whose
composite acts on `ω` by something other than the product of their scalars. -/
theorem isDiffChar_comp [IsAlgClosed F] [W.IsElliptic] [W'.IsElliptic]
    [W''.IsElliptic] {φ : W.Point →+ W'.Point} {ψ : W'.Point →+ W''.Point}
    {c d : F} (hφ : IsDiffChar φ c) (hψ : IsDiffChar ψ d) :
    IsDiffChar (ψ.comp φ) (d * c) := by
  classical
  obtain ⟨hgφ, A, B, Cx, Dx, E, hB, hE, hrel, hcert⟩ := hφ
  obtain ⟨hgψ, A', B', C', D', E', hB', hE', hrel', hcert'⟩ := hψ
  have hratφ : IsRationalMap φ := ⟨A, B, Cx, Dx, E, hB, hE, hrel⟩
  have hratψ : IsRationalMap ψ := ⟨A', B', C', D', E', hB', hE', hrel'⟩
  by_cases hzero : ψ.comp φ = 0
  · have hdc : d * c = 0 := by
      by_cases hφ0 : φ = 0
      · rw [hgφ hφ0, mul_zero]
      · have hψ0 : ψ = 0 := by
          ext R
          obtain ⟨Pt, hPt⟩ := hratφ.surjective hφ0 R
          have : (ψ.comp φ) Pt = 0 := by rw [hzero]; rfl
          rw [← hPt]
          exact this
        rw [hgψ hψ0, zero_mul]
    rw [hzero, hdc]
    exact isDiffChar_zero
  have hφ0 : φ ≠ 0 := by
    rintro rfl
    exact hzero (by ext P; simp)
  have hψ0 : ψ ≠ 0 := by
    rintro rfl
    exact hzero (by ext P; simp)
  -- `x ∘ φ` is nonconstant, so no `homogSubst` in `A, B` degenerates.
  have hnc : ¬ ∃ lam : F, A = Polynomial.C lam * B := by
    rintro ⟨lam, hlam⟩
    exact hφ0 (eq_zero_of_constX hB lam hlam (fun P hP => (hrel P hP).1))
  have hne : ∀ Q : F[X], Q ≠ 0 → ∀ n : ℕ, Q.natDegree ≤ n → homogSubst A B n Q ≠ 0 :=
    fun Q hQ n hn hz => hnc (exists_const_of_homogSubst_eq_zero hB hQ hn hz)
  -- `x ∘ ψ` is nonconstant too, which is what makes the substitution degree positive.
  obtain ⟨m, hm⟩ : ∃ m : ℕ, max A'.natDegree B'.natDegree = m + 1 := by
    rcases Nat.eq_zero_or_pos (max A'.natDegree B'.natDegree) with h0 | hpos
    · exfalso
      have hA'0 : A'.natDegree = 0 := Nat.le_zero.1 (h0 ▸ le_max_left _ _)
      have hB'0 : B'.natDegree = 0 := Nat.le_zero.1 (h0 ▸ le_max_right _ _)
      obtain ⟨p, hp⟩ : ∃ p, A' = Polynomial.C p :=
        ⟨_, Polynomial.eq_C_of_natDegree_le_zero hA'0.le⟩
      obtain ⟨q, hq⟩ : ∃ q, B' = Polynomial.C q :=
        ⟨_, Polynomial.eq_C_of_natDegree_le_zero hB'0.le⟩
      have hqne : q ≠ 0 := by rintro rfl; rw [map_zero] at hq; exact hB' hq
      refine hψ0 (eq_zero_of_constX hB' (p / q) ?_ (fun R hR => (hrel' R hR).1))
      rw [hp, hq, ← Polynomial.C_mul, div_mul_cancel₀ _ hqne]
    · exact ⟨max A'.natDegree B'.natDegree - 1, by omega⟩
  have hdA' : A'.natDegree ≤ m + 1 := hm ▸ le_max_left _ _
  have hdB' : B'.natDegree ≤ m + 1 := hm ▸ le_max_right _ _
  have hdA'' : (derivative A').natDegree ≤ m :=
    le_trans (Polynomial.natDegree_derivative_le A') (by omega)
  have hdB'' : (derivative B').natDegree ≤ m :=
    le_trans (Polynomial.natDegree_derivative_le B') (by omega)
  set Ac := homogSubst A B (m + 1) A' with hAcdef
  set Bc := homogSubst A B (m + 1) B' with hBcdef
  have hBcne : Bc ≠ 0 := hne B' hB' _ hdB'
  set Ecc := homogSubst A B E'.natDegree E' with hEccdef
  have hEccne : Ecc ≠ 0 := hne E' hE' _ le_rfl
  -- the `x`-relation for the substituted witnesses
  have hxAcBc : ∀ P : W.Point, (ψ.comp φ) P ≠ 0 →
      veluPointX ((ψ.comp φ) P) * Bc.eval (veluPointX P) = Ac.eval (veluPointX P) := by
    intro P hP
    have hφP : φ P ≠ 0 := fun hc => hP (by show ψ (φ P) = 0; rw [hc, map_zero])
    have hx := (hrel P hφP).1
    have hx' := (hrel' (φ P) hP).1
    rw [hAcdef, hBcdef, eval_homogSubst hdA' hx, eval_homogSubst hdB' hx]
    show veluPointX (ψ (φ P)) * _ = _
    linear_combination (B.eval (veluPointX P)) ^ (m + 1) * hx'
  obtain ⟨a, b, γ, δ, ε, hb, hε, hrelc⟩ := hratφ.comp hratψ
  have hratc : IsRationalMap (ψ.comp φ) := ⟨a, b, γ, δ, ε, hb, hε, hrelc⟩
  have hkerc : (AddMonoidHom.ker (ψ.comp φ) : Set W.Point).Finite := hratc.finite_ker hzero
  -- the two `x`-witness families agree, hence so do their Wronskians
  have hxeq : a * Bc = Ac * b :=
    diffChar_xWitness_eq hkerc (fun P hP => (hrelc P hP).1) hxAcBc
  have hwtr := diffChar_wronskian_transfer hxeq
  refine ⟨fun hc => absurd hc hzero, a, b, γ, δ, ε, hb, hε, hrelc, fun Pt _ => ?_⟩
  -- the certificate, checked off a finite bad set
  refine isDiffCharCert_of_cofinite
    (S := (({t : F | B.eval t = 0} ∪ {t : F | E.eval t = 0}) ∪
            ({t : F | Bc.eval t = 0} ∪ {t : F | Ecc.eval t = 0})) ∪
          veluPointX '' (AddMonoidHom.ker (ψ.comp φ) : Set W.Point))
    ((((Polynomial.finite_setOf_isRoot hB).union (Polynomial.finite_setOf_isRoot hE)).union
      ((Polynomial.finite_setOf_isRoot hBcne).union
        (Polynomial.finite_setOf_isRoot hEccne))).union (hkerc.image _))
    (fun R hR0 hRS => ?_) Pt
  set t := veluPointX R with htdef
  have hβ : B.eval t ≠ 0 := fun hc => hRS (Or.inl (Or.inl (Or.inl hc)))
  have hEt : E.eval t ≠ 0 := fun hc => hRS (Or.inl (Or.inl (Or.inr hc)))
  have hBct : Bc.eval t ≠ 0 := fun hc => hRS (Or.inl (Or.inr (Or.inl hc)))
  have hEcct : Ecc.eval t ≠ 0 := fun hc => hRS (Or.inl (Or.inr (Or.inr hc)))
  have hψφR : (ψ.comp φ) R ≠ 0 := fun hc => hRS (Or.inr ⟨R, hc, rfl⟩)
  have hφR : φ R ≠ 0 := fun hc => hψφR (by show ψ (φ R) = 0; rw [hc, map_zero])
  set u := veluPointX (φ R) with hudef
  have hx := (hrel R hφR).1
  have hy := (hrel R hφR).2
  have hx' := (hrel' (φ R) hψφR).1
  have hy' := (hrel' (φ R) hψφR).2
  have hE'u : E'.eval u ≠ 0 := by
    intro hc
    exact hEcct (by rw [hEccdef, eval_homogSubst le_rfl hx, hc, mul_zero])
  -- the two reduced certificates, with their `E`-factors divided out
  have red1 := isDiffCharCert_reduced hx hy (hcert R hR0)
  have red2 := isDiffCharCert_reduced hx' hy' (hcert' (φ R) hφR)
  have h1' : c * B.eval t ^ 2 * (2 * veluPointY (φ R) + W'.a₁ * u + W'.a₃)
      = ((derivative A).eval t * B.eval t - A.eval t * (derivative B).eval t)
        * (2 * veluPointY R + W.a₁ * t + W.a₃) := by
    refine mul_right_cancel₀ hEt ?_
    linear_combination red1
  have h2' : d * B'.eval u ^ 2
        * (2 * veluPointY (ψ (φ R)) + W''.a₁ * veluPointX (ψ (φ R)) + W''.a₃)
      = ((derivative A').eval u * B'.eval u - A'.eval u * (derivative B').eval u)
        * (2 * veluPointY (φ R) + W'.a₁ * u + W'.a₃) := by
    refine mul_right_cancel₀ hE'u ?_
    linear_combination red2
  have hevAc : Ac.eval t = B.eval t ^ (m + 1) * A'.eval u := by
    rw [hAcdef]; exact eval_homogSubst hdA' hx
  have hevBc : Bc.eval t = B.eval t ^ (m + 1) * B'.eval u := by
    rw [hBcdef]; exact eval_homogSubst hdB' hx
  -- the chain rule, evaluated
  have hchain := congrArg (Polynomial.eval t)
    (homogSubst_wronskian (A := A) (B := B) hdA' hdB')
  simp only [Polynomial.eval_mul, Polynomial.eval_sub, Nat.add_sub_cancel] at hchain
  rw [← hAcdef, ← hBcdef] at hchain
  rw [eval_homogSubst hdA'' hx, eval_homogSubst hdB'' hx, hevAc, hevBc] at hchain
  -- the composite scalar identity for the SUBSTITUTED witnesses
  have hY : d * c * Bc.eval t ^ 2
        * (2 * veluPointY (ψ (φ R)) + W''.a₁ * veluPointX (ψ (φ R)) + W''.a₃)
      = ((derivative Ac).eval t * Bc.eval t - Ac.eval t * (derivative Bc).eval t)
        * (2 * veluPointY R + W.a₁ * t + W.a₃) := by
    refine mul_left_cancel₀ hβ ?_
    rw [hevAc, hevBc]
    linear_combination (c * B.eval t ^ (m + 1) * B.eval t ^ (m + 1) * B.eval t) * h2'
      + (B.eval t ^ m * B.eval t ^ (m + 1)
          * ((derivative A').eval u * B'.eval u - A'.eval u * (derivative B').eval u)) * h1'
      - (2 * veluPointY R + W.a₁ * t + W.a₃) * hchain
  -- transfer to the witnesses `IsRationalMap.comp` actually produced
  have hXev := congrArg (Polynomial.eval t) hwtr
  simp only [Polynomial.eval_mul, Polynomial.eval_sub, Polynomial.eval_pow] at hXev
  have hT0 : d * c * b.eval t ^ 2
        * (2 * veluPointY (ψ (φ R)) + W''.a₁ * veluPointX (ψ (φ R)) + W''.a₃)
      = ((derivative a).eval t * b.eval t - a.eval t * (derivative b).eval t)
        * (2 * veluPointY R + W.a₁ * t + W.a₃) := by
    refine mul_right_cancel₀ (pow_ne_zero 2 hBct) ?_
    linear_combination (b.eval t ^ 2) * hY
      - (2 * veluPointY R + W.a₁ * t + W.a₃) * hXev
  refine isDiffCharCert_of_reduced (hrelc R hψφR).1 (hrelc R hψφR).2 ?_
  simp only [AddMonoidHom.comp_apply]
  linear_combination (ε.eval t) * hT0

/-! ### Consequences of the leaves, PROVEN -/

/-- `λ(−φ) = −λ(φ)`, from `−φ = (−1) ∘ φ` and `isDiffChar_neg_id`. -/
theorem isDiffChar_neg [IsAlgClosed F] [W.IsElliptic] [W'.IsElliptic]
    {φ : W.Point →+ W'.Point} {c : F} (h : IsDiffChar φ c) :
    IsDiffChar (-φ) (-c) := by
  have hcomp : IsDiffChar ((-(AddMonoidHom.id W'.Point)).comp φ) ((-1) * c) :=
    isDiffChar_comp h isDiffChar_neg_id
  have hEq : (-(AddMonoidHom.id W'.Point)).comp φ = -φ := by
    ext P; rfl
  rw [hEq, neg_one_mul] at hcomp
  exact hcomp

/-! ### Additivity, and the TWO leaves it reduces to

`isDiffChar_add` is now an ASSEMBLY over the same five-way split that
`IsRationalMap.add` uses in `Isogeny.lean`, and for the same reason: the affine
group law on `W'` has two formulas, selected by whether `x(φP) = x(ψP)`, and that
condition holds *identically* exactly when `φ = ψ` or `φ = −ψ`.

**THREE of the five branches are FREE**, and are discharged in `isDiffChar_add`
below:

* `φ = 0` and `ψ = 0` — the guard clause of `IsDiffChar` gives `c = 0` resp.
  `d = 0`, and the sum is the other summand unchanged.
* `φ + ψ = 0` — then `ψ = −φ`, so `isDiffChar_neg` and `isDiffChar_unique` force
  `d = −c`, and the sum is `IsDiffChar 0 0`, which is `isDiffChar_zero`.

What is left is exactly two statements, and they are INDEPENDENT — they can be
owned separately.

**`isDiffChar_two`, the DOUBLING branch, collapsed to ONE curve.** `φ + φ` is
`φ ∘ [2]_W` — the doubling happens on the SOURCE curve — so `isDiffChar_comp`
reduces that whole branch to `IsDiffChar (mulByHom W 2) 2`, a statement in which
`φ`, `ψ`, `W'`, `c` and `d` have all disappeared. That is `[2]*ω = 2ω`.

**It is NOT derivable from additivity elsewhere, and that is worth recording**,
because it looks at first as though it should be. The polarisation
`2φ = (φ + χ) + (φ − χ)` would reduce doubling to the chord branch, but it needs a
`χ` whose scalar is already known and which is neither `0` nor `±φ`; on a bare pair
of curves `(W, W')` no such `χ` is available, and every candidate built from `φ`
itself (`φ ∘ [n]`) has a scalar known only through `isDiffChar_mulByHom`, which is
proven BY additivity. `[2]` is the irreducible core of additivity, not an instance
of it.

**Why it should be tractable, and HALF OF IT IS ALREADY PROVEN.** The witnesses are
in the tree and explicit: `veluPointX_nsmul` gives `x([n]P)·ΨSqₙ(x P) = Φₙ(x P)`, and
the `y`-witness for `n = 2` is `exists_y_witness_two` (both in `Isogeny.lean`, both
PROVEN). Through `isDiffCharCert_of_cofinite` + `isDiffCharCert_of_reduced` the leaf
becomes the Wronskian identity

  `2 · ΨSq₂² · ψ₂([2]P) = (Φ₂′·ΨSq₂ − Φ₂·ΨSq₂′) · ψ₂(P)`

between division polynomials — algebra in one variable, not geometry. And its
right-hand side is ALREADY A THEOREM:

  `PsiSumCompanion.wronskian` (`WronskianInduction.lean`, sorry-free, any
  commutative ring, every `n ≥ 1`): `Φₙ′·ΨSqₙ − Φₙ·ΨSqₙ′ = n · preΨ (2n)`.

At `n = 2` that reads `Φ₂′·ΨSq₂ − Φ₂·ΨSq₂′ = 2 · preΨ 4`, so the target collapses to
the `y`-side statement

  `ΨSq₂² · ψ₂([2]P) = preΨ 4 (x P) · ψ₂(P)`,

i.e. the classical `2y(nP) + a₁x(nP) + a₃ = ψ₂ₙ/ψₙ⁴` at `n = 2`. **THE
NORMALISATION IS NOW CHECKED, AND THE DISPLAY ABOVE IS EXACT** (2026-07-28; this
paragraph used to end "up to `preΨ`'s normalisation … this docstring has not checked
it"). `ψ₄ = preΨ₄·ψ₂`, so `ψ₄/ψ₂⁴ = preΨ₄/ψ₂³`, and since `ΨSq₂ = ψ₂²` the display
is `ψ₂⁴·ψ₂([2]P) = preΨ₄·ψ₂` — no stray `ψ₂` in either direction. `eval_preΨ₄_two`
is that identity in the `veluPoint` spelling, and `preΨ₄_two_core` is the ring
identity `ψ₂³·ψ₂([2]P) = preΨ₄(x)` behind it; the route was indeed the one predicted
here, a `linear_combination` over the curve equation and the tangent-slope relation
rather than a search.

Note the whole statement is true in EVERY characteristic, including `2`, where both
sides vanish because `[2]` is inseparable; so it must not acquire a `CharZero`
hypothesis.

**A tempting shortcut that is CIRCULAR**: `PsiSumCompanion.wronskian` holds for all
`n`, so it looks as though `isDiffChar_mulByHom` could be proven directly from it and
additivity read off afterwards. It cannot — `isDiffChar_mulByHom` is proven BY
`isDiffChar_add`, whose doubling branch is this leaf. Use `wronskian` at `n = 2` only.

**`isDiffChar_add_of_ne`, the CHORD branch**, carries the four degeneracies as
hypotheses, matching `IsRationalMap.add_of_ne` hypothesis for hypothesis. That
match is evidence the cut is the right one rather than a convenient one: the same
four exclusions are what make the chord formula applicable at all. -/

omit [DecidableEq F] in
/-- **The ring identity behind the `y`-side of `isDiffChar_two`**, isolated from the
curve exactly as `addY_two_core` is: `ψ₂³ · ψ₂([2]P) = preΨ₄(x)`.

`L` is the tangent slope, constrained only by `hLd : L·ψ₂ = 3x² + 2a₂x + a₄ − a₁y`;
the left-hand factor after `ψ₂³` is `2·addY + a₁·addX + a₃` written out through
`negY`/`negAddY`/`addX`, and the right-hand side is mathlib's `preΨ₄` with the
`b`-invariants expanded.

Three steps. `hAX` is the `x`-coordinate of the duplication cleared by `ψ₂²` (the
same identity `addY_two_core` opens with, and with the same cofactors); `hQ` is
`ψ₂² = 4x³ + b₂x² + 2b₄x + b₆`, which is `4 ×` the curve equation; and the final
`linear_combination` is the derivation

  `ψ₂³·ψ₂([2]P) = −(𝔸 − x·ψ₂²)·(2ν₀ + a₁(a₁x + a₃)) − ψ₂⁴`,

where `𝔸 = addX·ψ₂²` and `ν₀ = 3x² + 2a₂x + a₄`. The `y` disappears because
`2ν + a₁ψ₂ = 2ν₀ + a₁(a₁x + a₃)` identically, with `ν = ν₀ − a₁y`.

**Note the classical normalisation this settles**, which `isDiffChar_two`'s
docstring flagged as unchecked: `2y(2P) + a₁x(2P) + a₃ = ψ₄/ψ₂⁴ = preΨ₄/ψ₂³`, so
mathlib's `preΨ₄` — not `ψ₄` — is the polynomial that pairs with `ΨSq₂² = ψ₂⁴`. -/
theorem preΨ₄_two_core (a₁ a₂ a₃ a₄ a₆ x y L : F)
    (hEq : y ^ 2 + a₁ * x * y + a₃ * y = x ^ 3 + a₂ * x ^ 2 + a₄ * x + a₆)
    (hLd : L * (2 * y + a₁ * x + a₃) = 3 * x ^ 2 + 2 * a₂ * x + a₄ - a₁ * y) :
    (2 * y + a₁ * x + a₃) ^ 3
        * (2 * (-(L * ((L ^ 2 + a₁ * L - a₂ - x - x) - x) + y)
              - a₁ * (L ^ 2 + a₁ * L - a₂ - x - x) - a₃)
            + a₁ * (L ^ 2 + a₁ * L - a₂ - x - x) + a₃)
      = 2 * x ^ 6 + (a₁ ^ 2 + 4 * a₂) * x ^ 5 + 5 * (2 * a₄ + a₁ * a₃) * x ^ 4
          + 10 * (a₃ ^ 2 + 4 * a₆) * x ^ 3
          + 10 * (a₁ ^ 2 * a₆ + 4 * a₂ * a₆ - a₁ * a₃ * a₄ + a₂ * a₃ ^ 2 - a₄ ^ 2) * x ^ 2
          + ((a₁ ^ 2 + 4 * a₂)
                * (a₁ ^ 2 * a₆ + 4 * a₂ * a₆ - a₁ * a₃ * a₄ + a₂ * a₃ ^ 2 - a₄ ^ 2)
              - (2 * a₄ + a₁ * a₃) * (a₃ ^ 2 + 4 * a₆)) * x
          + ((2 * a₄ + a₁ * a₃)
                * (a₁ ^ 2 * a₆ + 4 * a₂ * a₆ - a₁ * a₃ * a₄ + a₂ * a₃ ^ 2 - a₄ ^ 2)
              - (a₃ ^ 2 + 4 * a₆) ^ 2) := by
  have hAX : (L ^ 2 + a₁ * L - a₂ - x - x) * (2 * y + a₁ * x + a₃) ^ 2
      = (3 * x ^ 2 + 2 * a₂ * x + a₄) ^ 2
        + a₁ * (a₁ * x + a₃) * (3 * x ^ 2 + 2 * a₂ * x + a₄)
        - a₁ ^ 2 * (x ^ 3 + a₂ * x ^ 2 + a₄ * x + a₆)
        - (a₂ + 2 * x) * (2 * y + a₁ * x + a₃) ^ 2 := by
    linear_combination (L * (2 * y + a₁ * x + a₃) + (3 * x ^ 2 + 2 * a₂ * x + a₄ - a₁ * y)
      + a₁ * (2 * y + a₁ * x + a₃)) * hLd + (-a₁ ^ 2) * hEq
  have hQ : (2 * y + a₁ * x + a₃) ^ 2
      = 4 * x ^ 3 + (a₁ ^ 2 + 4 * a₂) * x ^ 2 + 2 * (2 * a₄ + a₁ * a₃) * x
        + (a₃ ^ 2 + 4 * a₆) := by
    linear_combination 4 * hEq
  set S : F := (2 * y + a₁ * x + a₃) ^ 2 with hS
  set Q : F := 4 * x ^ 3 + (a₁ ^ 2 + 4 * a₂) * x ^ 2 + 2 * (2 * a₄ + a₁ * a₃) * x
      + (a₃ ^ 2 + 4 * a₆) with hQd
  set 𝔸 : F := (3 * x ^ 2 + 2 * a₂ * x + a₄) ^ 2
      + a₁ * (a₁ * x + a₃) * (3 * x ^ 2 + 2 * a₂ * x + a₄)
      - a₁ ^ 2 * (x ^ 3 + a₂ * x ^ 2 + a₄ * x + a₆) - (a₂ + 2 * x) * S with h𝔸
  set M : F := 2 * (3 * x ^ 2 + 2 * a₂ * x + a₄) + a₁ * (a₁ * x + a₃) with hM
  linear_combination (-2 * (L * (2 * y + a₁ * x + a₃)) - a₁ * (2 * y + a₁ * x + a₃)) * hAX
    + (-2 * (𝔸 - x * S)) * hLd
    + ((a₂ + 3 * x) * M - (S + Q)) * hQ

omit [DecidableEq F] in
/-- `Ψ₂Sq` evaluates to `ψ₂(P)²` at every nonzero point — the `veluPoint` spelling of
`TorsionCard.eval_Ψ₂Sq_eq_sq`. -/
theorem eval_Ψ₂Sq_veluPointX [W.IsElliptic] {P : W.Point} (hP : P ≠ 0) :
    W.Ψ₂Sq.eval (veluPointX P)
      = (2 * veluPointY P + W.a₁ * veluPointX P + W.a₃) ^ 2 := by
  cases P with
  | zero => exact absurd rfl hP
  | some x y h =>
    haveI : (W⁄F).IsElliptic := inferInstanceAs W.IsElliptic
    have hq := TorsionCard.eval_Ψ₂Sq_eq_sq W h.1
    simp only [veluPointX_some, veluPointY_some]
    rw [show (2 * y + W.a₁ * x + W.a₃) = (2 * y + (W.a₁ * x + W.a₃)) from by ring]
    exact hq

/-- **`preΨ₄(x P) = ψ₂(P)³ · ψ₂([2]P)`**, the `y`-side of `isDiffChar_two`.

This is the classical `2y(nP) + a₁x(nP) + a₃ = ψ₂ₙ/ψₙ⁴` at `n = 2`, in mathlib's
`preΨ` normalisation (`ψ₄ = preΨ₄·ψ₂`, so `ψ₄/ψ₂⁴ = preΨ₄/ψ₂³`). The hypothesis
`(2 : ℕ) • P ≠ 0` is what makes the duplication formula available; where it fails
both sides are unconstrained and the certificate is vacuous, which is exactly the
finite set `isDiffCharCert_of_cofinite` absorbs.

Proof: the duplication point is `Affine.Point.add_self_of_Y_ne`, so its coordinates
are `addX`/`addY` at the tangent slope, and the identity is `preΨ₄_two_core`. Holds
in EVERY characteristic, including `2`. -/
theorem eval_preΨ₄_two [W.IsElliptic] (P : W.Point) (hP : (2 : ℕ) • P ≠ 0) :
    W.preΨ₄.eval (veluPointX P)
      = (2 * veluPointY P + W.a₁ * veluPointX P + W.a₃) ^ 3
        * (2 * veluPointY ((2 : ℕ) • P) + W.a₁ * veluPointX ((2 : ℕ) • P) + W.a₃) := by
  cases P with
  | zero => exact absurd (smul_zero 2) hP
  | some x y h =>
    have hEq : y ^ 2 + W.a₁ * x * y + W.a₃ * y
        = x ^ 3 + W.a₂ * x ^ 2 + W.a₄ * x + W.a₆ := (Affine.equation_iff ..).1 h.1
    by_cases hy2 : y = -y - W.a₁ * x - W.a₃
    · refine absurd ?_ hP
      rw [two_nsmul]
      exact Affine.Point.add_self_of_Y_eq (by simpa [Affine.negY] using hy2)
    have hd : (2 * y + W.a₁ * x + W.a₃) ≠ 0 := fun hc => hy2 (by linear_combination hc)
    have hy2' : y ≠ W.negY x y := by simpa [Affine.negY] using hy2
    have hLd : W.slope x x y y * (2 * y + W.a₁ * x + W.a₃)
        = 3 * x ^ 2 + 2 * W.a₂ * x + W.a₄ - W.a₁ * y := by
      rw [Affine.slope_of_Y_ne' hy2,
        show y - (-y - W.a₁ * x - W.a₃) = 2 * y + W.a₁ * x + W.a₃ from by ring]
      exact div_mul_cancel₀ _ hd
    have hX : veluPointX ((2 : ℕ) • (Affine.Point.some x y h : W.Point))
        = W.addX x x (W.slope x x y y) := by
      rw [two_nsmul, Affine.Point.add_self_of_Y_ne hy2', veluPointX_some]
    have hY : veluPointY ((2 : ℕ) • (Affine.Point.some x y h : W.Point))
        = W.addY x x y (W.slope x x y y) := by
      rw [two_nsmul, Affine.Point.add_self_of_Y_ne hy2', veluPointY_some]
    rw [hX, hY]
    simp only [veluPointX_some, veluPointY_some, Affine.addY, Affine.negAddY, Affine.addX,
      Affine.negY, WeierstrassCurve.preΨ₄, WeierstrassCurve.b₂, WeierstrassCurve.b₄,
      WeierstrassCurve.b₆, WeierstrassCurve.b₈, Polynomial.eval_add,
      Polynomial.eval_mul, Polynomial.eval_pow, Polynomial.eval_C,
      Polynomial.eval_X, Polynomial.eval_ofNat]
    linear_combination
      (-1 : F) * preΨ₄_two_core W.a₁ W.a₂ W.a₃ W.a₄ W.a₆ x y (W.slope x x y y) hEq hLd

/-- **LEAF: `[2]*ω = 2ω`**, the irreducible core of additivity.

`IsDiffChar (mulByHom W 2) 2` — multiplication by `2` on a single curve acts on the
invariant differential by the scalar `2`. See the section docstring above for why
this cannot be obtained from additivity by polarisation, and for the concrete route:
the `x`-witnesses are the division polynomials `(W.Φ 2, W.ΨSq 2)` supplied by
`veluPointX_nsmul`, and the reduced certificate turns the leaf into a Wronskian
identity between them.

**NO `CharZero`.** In characteristic `2` the statement reads `λ([2]) = 0`, which is
correct — `[2]` is inseparable there — so a `CharZero` hypothesis would be both
unnecessary and a silent weakening of every consumer.

**THE CHECK THAT WOULD REFUTE THIS LEAF**: a Weierstrass curve over an
algebraically closed field on which the duplication map pulls `ω` back to `k·ω`
for some `k ≠ 2`.

**PROVEN 2026-07-28**, exactly along the route the section docstring maps out, and
with the normalisation it flagged as unchecked now SETTLED (see `preΨ₄_two_core`):
the classical `ψ₂ₙ/ψₙ⁴` is `preΨ₄/ψ₂³` in mathlib's spelling, not `ψ₄/ψ₂⁴`.

The witnesses are `(Φ 2, ΨSq 2)` for `x` (`veluPointX_nsmul`) and
`exists_y_witness_two` for `y`. Off the finite `2`-torsion the reduced certificate
is, after cancelling `E`,

  `2·ΨSq₂(t)²·ψ₂([2]R) = (Φ₂′ΨSq₂ − Φ₂ΨSq₂′)(t)·ψ₂(R)`,

whose right-hand side is `2·preΨ₄(t)·ψ₂(R)` by `PsiSumCompanion.wronskian` at
`n = 2` and whose left-hand side is `2·ψ₂(R)⁴·ψ₂([2]R)` by
`eval_Ψ₂Sq_veluPointX`; `eval_preΨ₄_two` matches them. Note `ψ₂(R) ≠ 0` is never
needed — nothing is divided out — so characteristic `2` is not a special case.

The guard clause `[2] = 0 → (2 : F) = 0` is discharged by refuting the hypothesis:
if `[2] = 0` then every point is `2`-torsion, `finite_nsmulKer` makes `W.Point`
finite, and `exists_point_veluPointX_eq` then makes `F` finite, contradicting
`Infinite F` for an algebraically closed field. -/
theorem isDiffChar_two [IsAlgClosed F] [W.IsElliptic] :
    IsDiffChar (mulByHom W 2) (2 : F) := by
  classical
  obtain ⟨Cw, Dw, Ew, hEw, hyw⟩ := exists_y_witness_two (W := W)
  have hB : W.ΨSq ((2 : ℕ) : ℤ) ≠ 0 := ΨSq_ne_zero' W (by norm_num)
  refine ⟨fun hc => ?_, W.Φ ((2 : ℕ) : ℤ), W.ΨSq ((2 : ℕ) : ℤ), Cw, Dw, Ew, hB, hEw,
    fun P hP => ⟨veluPointX_nsmul (by norm_num) P hP, hyw P hP⟩, fun P _ => ?_⟩
  · exfalso
    have hall : (Set.univ : Set W.Point).Finite := by
      refine Set.Finite.subset (finite_nsmulKer (W := W) (n := 2) (by norm_num)) ?_
      intro Q _
      show (2 : ℕ) • Q = 0
      simpa using DFunLike.congr_fun hc Q
    have himg : (Set.univ : Set F).Finite := by
      refine Set.Finite.subset (hall.image veluPointX) ?_
      intro t _
      obtain ⟨Q, -, hQx⟩ := exists_point_veluPointX_eq (W := W) t
      exact ⟨Q, Set.mem_univ _, hQx⟩
    exact Set.infinite_univ himg
  · refine isDiffCharCert_of_cofinite
      (S := veluPointX '' {R : W.Point | (2 : ℕ) • R = 0})
      ((finite_nsmulKer (W := W) (n := 2) (by norm_num)).image _) (fun R hR0 hRS => ?_) P
    have h2R : mulByHom W 2 R ≠ 0 := fun hc => hRS ⟨R, hc, rfl⟩
    set t := veluPointX R with htdef
    have hx : veluPointX (mulByHom W 2 R) * (W.ΨSq ((2 : ℕ) : ℤ)).eval t
        = (W.Φ ((2 : ℕ) : ℤ)).eval t := veluPointX_nsmul (by norm_num) R h2R
    have hy := hyw R h2R
    refine isDiffCharCert_of_reduced (φ := mulByHom W 2) hx hy ?_
    have hwr := congrArg (Polynomial.eval t) (PsiSumCompanion.wronskian W (n := 2) (by norm_num))
    simp only [Polynomial.eval_sub, Polynomial.eval_mul, Polynomial.eval_natCast] at hwr
    rw [show (2 * ((2 : ℕ) : ℤ)) = (4 : ℤ) from by norm_num, WeierstrassCurve.preΨ_four] at hwr
    have hΨ : (W.ΨSq ((2 : ℕ) : ℤ)).eval t
        = (2 * veluPointY R + W.a₁ * t + W.a₃) ^ 2 := by
      rw [show ((2 : ℕ) : ℤ) = (2 : ℤ) from by norm_num, WeierstrassCurve.ΨSq_two]
      exact eval_Ψ₂Sq_veluPointX hR0
    have hpre : W.preΨ₄.eval t
        = (2 * veluPointY R + W.a₁ * t + W.a₃) ^ 3
          * (2 * veluPointY (mulByHom W 2 R) + W.a₁ * veluPointX (mulByHom W 2 R) + W.a₃) :=
      eval_preΨ₄_two R h2R
    linear_combination
      (2 * Ew.eval t
          * (2 * veluPointY (mulByHom W 2 R) + W.a₁ * veluPointX (mulByHom W 2 R) + W.a₃)
          * ((W.ΨSq ((2 : ℕ) : ℤ)).eval t + (2 * veluPointY R + W.a₁ * t + W.a₃) ^ 2)) * hΨ
        + (-(Ew.eval t * (2 * veluPointY R + W.a₁ * t + W.a₃))) * hwr
        + (-(2 * Ew.eval t * (2 * veluPointY R + W.a₁ * t + W.a₃))) * hpre

/-- **LEAF: additivity, the CHORD branch.**

`λ(φ + ψ) = λ(φ) + λ(ψ)` when the four degeneracies are excluded: `φ ≠ 0`,
`ψ ≠ 0`, `φ + ψ ≠ 0` and `φ ≠ ψ`. These are exactly the hypotheses of
`IsRationalMap.add_of_ne` in `Isogeny.lean`, which is what makes the chord formula
`x₃ = m² + a₁m − a₂ − x₁ − x₂` applicable: `φ ≠ ψ` and `φ + ψ ≠ 0` together say
that `x∘φ` and `x∘ψ` are DIFFERENT rational functions, so `A₂B₁ − A₁B₂ ≠ 0` and its
vanishing locus is a finite set of `x`-values that
`isDiffCharCert_of_cofinite` absorbs.

**THE ARGUMENT.** Conceptually this is Silverman *AEC* III.5.2: `ω` is
translation-invariant, so the addition map `μ : W' × W' → W'` satisfies
`μ*ω = pr₁*ω + pr₂*ω`, and composing with `(φ, ψ)` gives the claim. In the
coordinates the two halves of that invariance are the identities

  `ψ₂(S)·∂x₃/∂x_S + ν(S)·∂x₃/∂y_S = ψ₂(S+T)`  and the same in `T`,

where `ν(Q) = 3x_Q² + 2a₂x_Q + a₄ − a₁y_Q`, i.e. `D = ψ₂ ∂/∂x + ν ∂/∂y` is the
invariant derivation of `InvariantDerivation.lean` and the identities say `D`
differentiates the chord formula to `ψ₂` on each factor. Given them, the two
reduced certificates supply `D(x∘φ) = c·ψ₂(φP)` and `D(x∘ψ) = d·ψ₂(ψP)`, and the
chain rule through the chord formula gives `D(x∘(φ+ψ)) = (c+d)·ψ₂((φ+ψ)P)`, which
is the reduced certificate for `c + d`.

**THE CHECK THAT WOULD REFUTE THIS LEAF**: two rational maps, neither zero, with
`φ ≠ ψ` and `φ + ψ ≠ 0`, whose sum acts on `ω` by something other than the sum of
their scalars.

## The route, mapped 2026-07-28 — and the invariance identities are ALREADY PROVEN

Two findings, both checked, that the paragraph above did not have.

**(1) `PsiSumCompanion.DK_addition_step` (`WronskianStep.lean`, SORRY-FREE) IS the
differentiated chord addition law.** Its file docstring calls it exactly that: "the
additivity of the invariant differential `ω = dx/ψ₂`, proven as a polynomial
certificate". It takes `DK x₁ = ψ₂(P₁)`, `DK y₁ = −(a₁y₁ − ν₀(x₁))`,
`DK xₙ = m·ψ₂(Pₙ)`, `DK yₙ = −m(a₁yₙ − ν₀(xₙ))` and the chord formulas, and returns
`DK x₃ = (m+1)·ψ₂(P₃)` **and** `DK y₃ = −(m+1)(a₁y₃ − ν₀(x₃))`. Its companion
`DK_doubling_step` is the tangent case. So the "two halves of the invariance" above
are not open mathematics — they are done, with cofactors already extracted.

It is NOT directly reusable here: it is stated for the specific derivation `DK` on
the universal function field `Kuniv`, and `InvariantDerivation.lean` builds `Dham`,
`DB`, `DK` only over `ℤ[A₁,…,A₅]` — there is no base-ring-generic version, and this
file works over an arbitrary algebraically closed `F`. What transfers is the
**certificate**: the same saturation exponents and the same hypothesis list.

**(2) The general-scalar version is TRUE and has the same shape** (verified in
Singular before this note was written; both remainders `0`). With `ψ₂ᵢ = 2yᵢ + a₁xᵢ
+ a₃`, `νᵢ = 3xᵢ² + 2a₂xᵢ + a₄ − a₁yᵢ`, and the DEFINITIONS

  `Dx₁ = c·ψ₂₁`, `Dy₁ = c·ν₁`, `Dx₂ = d·ψ₂₂`, `Dy₂ = d·ν₂`,
  `DL·(x₁ − x₂) = (Dy₁ − Dy₂) − L·(Dx₁ − Dx₂)`   (quotient rule),
  `Dx₃ = (2L + a₁)·DL − Dx₁ − Dx₂`                (chain rule),

the two curve equations and `L(x₁ − x₂) = y₁ − y₂` imply

  `(Dx₃ − (c+d)·ψ₂(P₃))·(x₁ − x₂)⁴ = 0`  and  `(Dy₃ − (c+d)·ν(P₃))·(x₁ − x₂)⁵ = 0`,

i.e. exactly `DK_addition_step` with `(1, m)` replaced by `(c, d)`. Saturation
exponents `4` and `5`, the same as there.

## What is actually left, and the tool for it

Given (2), the leaf reduces to ONE thing: connecting the *defined* `Dx₃` above to
the polynomial Wronskian `A₃′B₃ − A₃B₃′` of a genuine `x`-witness of `φ + ψ`. That
splits again:

* *The `x`-side is free.* `IsRationalMap.add_of_x_ne` already builds the witness
  `(V, Hp²K)` explicitly out of `A₁,…,E₂`, so `derivative V` and `derivative (Hp²K)`
  are the product rule applied to explicit polynomial expressions, and
  `diffChar_xWitness_eq` + `diffChar_wronskian_transfer` move the result onto
  whatever witness `IsRationalMap.add_of_ne` hands back — the pattern
  `isDiffChar_comp` already uses.
* *The `y`-side is the real gap.* The Wronskian of `V` involves `C₁′, D₁′, E₁′`,
  and nothing in `IsDiffChar` constrains them directly. What constrains them is the
  `y`-companion `D(y∘φ) = c·ν(φP)`, in cleared form

    `ψ₂(P)·(C′(t)y + D′(t))·E(t) + C(t)·ν(P)·E(t) − (C(t)y + D(t))·ψ₂(P)·E′(t)`
      `= c·ν(φP)·E(t)²`.

  **This does NOT need a derivation on `F[t,y]/(W)`, contrary to the first
  impression.** The `W'`-equation at `(x∘φ, y∘φ)`, cleared of denominators, is a
  polynomial identity in `F[t][y]` holding at every point of `W`; `y` occurs
  linearly after one reduction, so writing it as `q(t)·y + p(t) = 0` and evaluating
  at `R` and `−R` forces `q = 0` and `p = 0` as POLYNOMIALS — this is precisely the
  mechanism already implemented inside `isDiffCharCert_of_cofinite`, reusable
  verbatim. Differentiating the two polynomial identities `q = 0`, `p = 0` with the
  ordinary `Polynomial.derivative` then gives the `y`-companion.

So the leaf is large but has no missing theory: `isDiffCharCert_of_cofinite`'s
`q`/`p` trick, `DK_addition_step`'s certificate, and `add_of_x_ne`'s `V`/`Hp²K`
are the three pieces, and all three exist.

**Do not attempt the polarisation `2φ = (φ+χ) + (φ−χ)`** to avoid this: see the
section docstring — no `χ` with a known scalar exists on a bare pair `(W, W')`. -/
theorem isDiffChar_add_of_ne [IsAlgClosed F] [W.IsElliptic] [W'.IsElliptic]
    {φ ψ : W.Point →+ W'.Point} {c d : F}
    (hφ : IsDiffChar φ c) (hψ : IsDiffChar ψ d)
    (h0φ : φ ≠ 0) (h0ψ : ψ ≠ 0) (hsum : φ + ψ ≠ 0) (hdiff : φ ≠ ψ) :
    IsDiffChar (φ + ψ) (c + d) :=
  sorry

/-- **PROVEN 2026-07-28 (assembly): `λ` is additive.**

The five-way split of the section docstring above. Three branches are discharged
here outright; the doubling branch is `isDiffChar_comp` applied to
`isDiffChar_two`; the chord branch is `isDiffChar_add_of_ne`.

The sum of two rational maps is rational (`IsRationalMap.add`, PROVEN in
`Isogeny.lean`), so the statement is not vacuous; note that `IsIsogeny.add` is
FALSE (see the falsity audit there) — which is exactly why `IsDiffChar` is built
over `IsRationalMap` rather than over `IsIsogeny`. -/
theorem isDiffChar_add [IsAlgClosed F] [W.IsElliptic] [W'.IsElliptic]
    {φ ψ : W.Point →+ W'.Point} {c d : F}
    (hφ : IsDiffChar φ c) (hψ : IsDiffChar ψ d) :
    IsDiffChar (φ + ψ) (c + d) := by
  by_cases h0φ : φ = 0
  · rw [h0φ, zero_add, hφ.1 h0φ, zero_add]
    exact hψ
  by_cases h0ψ : ψ = 0
  · rw [h0ψ, add_zero, hψ.1 h0ψ, add_zero]
    exact hφ
  by_cases hsum : φ + ψ = 0
  · have hψeq : ψ = -φ := eq_neg_of_add_eq_zero_left (by rw [add_comm]; exact hsum)
    rw [hψeq] at hψ
    have hd : d = -c := isDiffChar_unique hψ (isDiffChar_neg hφ)
    have hcd : c + d = 0 := by rw [hd]; ring
    rw [hsum, hcd]
    exact isDiffChar_zero
  by_cases hdiff : φ = ψ
  · have hcd : c = d := by
      rw [hdiff] at hφ
      exact isDiffChar_unique hφ hψ
    have hEq : φ + ψ = ψ.comp (mulByHom W 2) := by
      ext P
      rw [hdiff]
      simp [two_nsmul]
    have hval : c + d = d * 2 := by rw [hcd]; ring
    rw [hEq, hval]
    exact isDiffChar_comp isDiffChar_two hψ
  exact isDiffChar_add_of_ne hφ hψ h0φ h0ψ hsum hdiff

/-- **PROVEN 2026-07-28: `λ` is injective, in characteristic zero.**

`(φ − ψ)*ω' = 0`, and a rational map killing the invariant differential is
INSEPARABLE, hence constant in characteristic zero, hence `0` (it is a group
homomorphism). In this formalisation that last step is
`eq_zero_of_isDiffChar_zero` above, PROVEN: `f' = 0` forces `f = A/B` constant
(`exists_const_of_wronskian_eq_zero`), and `eq_zero_of_constX` (PROVEN in
`Isogeny.lean`) then gives `φ − ψ = 0`.

The assembly here consumes two of this file's remaining leaves —
`isDiffChar_comp` (to get `λ(−ψ) = −λ(ψ)` from `λ(−1) = −1`) and
`isDiffChar_add` — so this declaration is transitively sorried but has NOTHING
left to prove: do not dispatch a prover at it.

`CharZero` is essential and cannot be dropped, and this is the one place in the
file where it is: in characteristic `p` the Frobenius is a nonzero isogeny with
`λ = 0`, so `Frob` and `0` would be two distinct maps with the same scalar. It
enters through `exists_const_of_wronskian_eq_zero`, where `X^p` has zero
derivative without being constant. -/
theorem eq_of_isDiffChar [IsAlgClosed F] [CharZero F] [W.IsElliptic]
    [W'.IsElliptic] {φ ψ : W.Point →+ W'.Point} {c : F}
    (hφ : IsDiffChar φ c) (hψ : IsDiffChar ψ c) : φ = ψ := by
  have hsum : IsDiffChar (φ + -ψ) (c + -c) := isDiffChar_add hφ (isDiffChar_neg hψ)
  rw [add_neg_cancel, ← sub_eq_add_neg] at hsum
  exact sub_eq_zero.mp (eq_zero_of_isDiffChar_zero hsum)

/-- `λ([n]) = n` for a natural number `n`, by induction from `λ(0) = 0`,
`λ(1) = 1` and additivity. -/
theorem isDiffChar_mulByHom [IsAlgClosed F] [W.IsElliptic] (n : ℕ) :
    IsDiffChar (mulByHom W n) (n : F) := by
  induction n with
  | zero =>
      have hEq : mulByHom W 0 = (0 : W.Point →+ W.Point) := by ext P; simp
      rw [hEq]; simpa using (isDiffChar_zero (W := W) (W' := W))
  | succ n ih =>
      have hEq : mulByHom W (n + 1) = mulByHom W n + AddMonoidHom.id W.Point := by
        ext P; simp [succ_nsmul]
      have hsum := isDiffChar_add ih (isDiffChar_id (W := W))
      rw [hEq]
      have hcast : ((n + 1 : ℕ) : F) = (n : F) + 1 := by push_cast; ring
      rw [hcast]
      exact hsum

end General

/-! ### Galois equivariance over `ℚ`

The statement below is the one the level-`49` argument consumes. It is stated in
the concrete setting `E/ℚ` base changed to `ℚ̄`, because that is where the
coefficients `a₁, a₃` of the curve are `σ`-fixed — which is exactly what makes
the equivariance true. -/

section Galois

variable [DecidableEq (AlgebraicClosure ℚ)]

/-- **PROVEN 2026-07-28: `λ` is Galois-equivariant**, `λ(φ^σ) = σ(λ φ)`.

For `E/ℚ` and `σ ∈ Gal(ℚ̄/ℚ)`, the conjugate `φ^σ = σ ∘ φ ∘ σ⁻¹` of a rational
map of `E_ℚ̄` is rational with the `σ`-conjugated witnesses `A.map σ, …, E.map σ`
(this is the transport proven as `MazurLevelFortyNine.isIsogeny_galConj`, from
`velu_pointX_map`, `velu_pointY_map` and `velu_point_map_symm_map`). Applying `σ`
to the differential certificate of `φ` at `σ⁻¹ P` turns it into the certificate
of `φ^σ` at `P` with scalar `σ c`: `σ` is a ring homomorphism, it commutes with
`eval` (`Polynomial.eval₂_at_apply`) and with `derivative` (`derivative_map`),
and it FIXES `a₁` and `a₃`, which lie in the base field `ℚ`.

Equivalently and more conceptually: `ω` is defined over `ℚ`, so `ω^σ = ω`, and
`(φ^σ)*ω = (φ*ω)^σ = (λ(φ)·ω)^σ = σ(λ(φ))·ω`.

**THE CHECK THAT WOULD REFUTE THIS LEAF**: a curve over `ℚ`, an endomorphism of
`E_ℚ̄` and a `σ` with `λ(φ^σ) ≠ σ(λ φ)`. -/
theorem isDiffChar_galConj (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ)
    (φ : (E⁄(AlgebraicClosure ℚ)).Point →+ (E⁄(AlgebraicClosure ℚ)).Point)
    (c : AlgebraicClosure ℚ) (h : IsDiffChar φ c) :
    IsDiffChar ((Affine.Point.map (W' := E) σ.toAlgHom).comp
      (φ.comp (Affine.Point.map (W' := E) σ.symm.toAlgHom))) (σ c) := by
  obtain ⟨hguard, A, B, C, D, G, hB, hG, hcert, hdiff⟩ := h
  set f : AlgebraicClosure ℚ →+* AlgebraicClosure ℚ := σ.toAlgHom.toRingHom with hf_def
  have hfinj : Function.Injective f := σ.injective
  have hev : ∀ (p : Polynomial (AlgebraicClosure ℚ)) (x : AlgebraicClosure ℚ),
      (p.map f).eval (σ x) = σ (p.eval x) := by
    intro p x
    have hsx : σ x = f x := rfl
    rw [hsx, Polynomial.eval_map, Polynomial.eval₂_at_apply]
    rfl
  have hinv : ∀ P : (E⁄(AlgebraicClosure ℚ)).Point,
      Affine.Point.map (W' := E) σ.toAlgHom
        (Affine.Point.map (W' := E) σ.symm.toAlgHom P) = P :=
    fun P => WeierstrassCurve.velu_point_map_symm_map E σ.symm P
  have hxP : ∀ P : (E⁄(AlgebraicClosure ℚ)).Point, veluPointX P
      = σ (veluPointX (Affine.Point.map (W' := E) σ.symm.toAlgHom P)) := by
    intro P
    conv_lhs => rw [← hinv P]
    exact WeierstrassCurve.velu_pointX_map E σ _
  have hyP : ∀ P : (E⁄(AlgebraicClosure ℚ)).Point, veluPointY P
      = σ (veluPointY (Affine.Point.map (W' := E) σ.symm.toAlgHom P)) := by
    intro P
    conv_lhs => rw [← hinv P]
    exact WeierstrassCurve.velu_pointY_map E σ _
  refine ⟨?_, A.map f, B.map f, C.map f, D.map f, G.map f,
    (Polynomial.map_ne_zero_iff hfinj).mpr hB,
    (Polynomial.map_ne_zero_iff hfinj).mpr hG, ?_, ?_⟩
  · -- the guard clause: conjugation is invertible, so `φ^σ = 0` forces `φ = 0`
    intro hzero
    have hφ0 : φ = 0 := by
      refine AddMonoidHom.ext fun Q => ?_
      have h2 : Affine.Point.map (W' := E) σ.toAlgHom (φ Q) = 0 := by
        have := DFunLike.congr_fun hzero (Affine.Point.map (W' := E) σ.toAlgHom Q)
        simpa [WeierstrassCurve.velu_point_map_symm_map E σ Q] using this
      have h3 : Affine.Point.map (W' := E) σ.toAlgHom (φ Q)
          = Affine.Point.map (W' := E) σ.toAlgHom 0 := by rw [h2, map_zero]
      simpa using Affine.Point.map_injective (W' := E) σ.toAlgHom h3
    rw [hguard hφ0, map_zero]
  · -- the rational-map witnesses, conjugated
    intro P hP
    have hφQ : φ (Affine.Point.map (W' := E) σ.symm.toAlgHom P) ≠ 0 := by
      intro hcc
      exact hP (by
        show Affine.Point.map (W' := E) σ.toAlgHom
          (φ (Affine.Point.map (W' := E) σ.symm.toAlgHom P)) = 0
        rw [hcc, map_zero])
    obtain ⟨hx, hy⟩ := hcert _ hφQ
    constructor
    · show veluPointX (Affine.Point.map (W' := E) σ.toAlgHom
          (φ (Affine.Point.map (W' := E) σ.symm.toAlgHom P)))
            * (B.map f).eval (veluPointX P)
          = (A.map f).eval (veluPointX P)
      rw [WeierstrassCurve.velu_pointX_map E σ _, hxP P, hev, hev, ← map_mul, hx]
    · show veluPointY (Affine.Point.map (W' := E) σ.toAlgHom
          (φ (Affine.Point.map (W' := E) σ.symm.toAlgHom P)))
            * (G.map f).eval (veluPointX P)
          = (C.map f).eval (veluPointX P) * veluPointY P + (D.map f).eval (veluPointX P)
      rw [WeierstrassCurve.velu_pointY_map E σ _, hxP P, hyP P, hev, hev, hev,
        ← map_mul, ← map_mul, ← map_add, hy]
  · -- the differential certificate: `σ` commutes with `eval` and with `derivative`,
    -- and fixes `a₁`, `a₃`, which lie in the base field `ℚ`
    intro P hP
    have hQ : Affine.Point.map (W' := E) σ.symm.toAlgHom P ≠ 0 := by
      intro hcc
      exact hP (by rw [← hinv P, hcc, map_zero])
    have ha₁ : σ (E⁄(AlgebraicClosure ℚ)).a₁ = (E⁄(AlgebraicClosure ℚ)).a₁ := by simp
    have ha₃ : σ (E⁄(AlgebraicClosure ℚ)).a₃ = (E⁄(AlgebraicClosure ℚ)).a₃ := by simp
    have key := congrArg σ (hdiff _ hQ)
    simp only [IsDiffCharCert] at key ⊢
    rw [hxP P, hyP P, Polynomial.derivative_map, Polynomial.derivative_map]
    simp only [hev]
    simp only [map_mul, map_add, map_sub, map_ofNat, ha₁, ha₃] at key
    linear_combination key

end Galois

end WeierstrassCurve
