/-
Copyright (c) 2026 Deyao Chen. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

-- `IsogenyTrace.lean` is the existing home of the `End W` API: it supplies
-- `End.intCast_injective` (`ℤ ↪ End W`), `End.coe_add_apply`, and above all
-- `End.torsionRep`, the ring map `End W →+* Module.End (ZMod n) (W.nTorsion n)`
-- that this file's CM action is composed out of. It `public import`s
-- `EllipticCurve.Isogeny` (for `endSubring`/`End`) and `EllipticCurve.Torsion`
-- (for `nTorsion`), so no further elliptic-curve import is needed here.
public import Fermat.FLT.EllipticCurve.IsogenyTrace
public import Mathlib.RingTheory.AdjoinRoot

/-!
# The CM order inside `End(E)`, and its action on the torsion

## What was already there, and what this file adds

`Fermat/FLT/EllipticCurve/Isogeny.lean` builds the endomorphism RING —
`endSubring W : Subring (AddMonoid.End W.Point)`, `End W := ↥(endSubring W)`, with
`((n : ℤ) : End W)` equal to multiplication by `n` **definitionally**
(`End.intCast_apply`) — and `Fermat/FLT/EllipticCurve/IsogenyTrace.lean` builds the
`ℤ`-embedding `End.intCast_injective` and the torsion representation
`End.torsionRep W n : End W →+* Module.End (ZMod n) (W.nTorsion n)`.

What was missing, and is supplied here, is the **imaginary quadratic order**: the
statement that an endomorphism satisfying `φ² = φ − m` with `1 < 4m` generates a
copy of `ℤ[(1 + √(1−4m))/2]`, and the resulting action of that order on the
torsion.

* `eq_zero_of_cmRelation` — `1` and `φ` are `ℤ`-INDEPENDENT.  Point-level, so a
  consumer holding a bare `AddMonoidHom` can use it directly; `End.cmIndep` is the
  same statement in the ring.
* `cmOrderHom` — the ring map `AdjoinRoot (X² − X + m) →+* End W` sending the root
  to `φ`, and `cmOrderHom_injective`.  Together: **the subring of `End W`
  generated by `φ` is isomorphic to the order `ℤ[(1 + √(1−4m))/2]`**.  At
  `4m = p + 1` that order is `ℤ[(1 + √−p)/2]`, the MAXIMAL order of `ℚ(√−p)` for
  `p ≡ 3 mod 4` — which is the situation of `X0.lean`'s CM leaves at
  `p ∈ {11, 19, 43, 67, 163}`.
* `cmTorsionRep`, `cmTorsionQuotRep`, `cmTorsionModule` — the order acts on
  `W[n]`, and because `n` kills `W[n]` the action factors through `O/nO`.  So
  `W[n]` **is a module over `O_K/n`**, which is the object
  `not_forall_galoisScalar_of_cmEndomorphism` needs to talk about.

## Why `1 < 4m` is exactly the right hypothesis

`1 − 4m` is the discriminant of `X² − X + m`.  `1 < 4m` says it is NEGATIVE, which
is what makes the norm form `N(a + bφ) = a² + ab + b²m` positive definite — and the
proof of independence is precisely that positive definiteness.  The hypothesis
cannot be weakened:

* at `m = 0` the relation `φ² = φ` is satisfied by `φ = 0` and by `φ = 1`, and
  `1 · 1 + (−1) · φ = 0` is a nontrivial relation;
* at `m = −2` the polynomial factors as `(X − 2)(X + 1)` over `ℤ`, so `φ = 2`
  satisfies the relation and `(−2) + 1 · φ = 0`.

Over `ℤ` the condition `1 < 4m` is just `1 ≤ m`.

## What is NOT here, and is the remaining input of the CM leaf

`W[q]` being **free of rank one** over `O_K/q` is not proven here.  That needs the
count `#W[q] = q² = #(O_K/q)` *together with* faithfulness of the action, and it is
the geometric input of `not_forall_galoisScalar_of_cmEndomorphism`.  What is here
is the module structure that freeness would be a statement ABOUT, which did not
previously exist in the tree — so the leaf can now at least be *stated* in its
natural vocabulary rather than through a hand-rolled pair of scalars.

## `[IsAlgClosed F]` and `[W.IsElliptic]` are not decoration

Both are inherited from `Isogeny.lean`, where they carry machine-checked FALSITY
AUDITs: `IsIsogeny.add` — hence `endSubring` itself — is FALSE over a general
field (`[2] = id + id` is not surjective on `W₅(𝔽₅)`), and `Affine F` contains
singular cubics, whose point groups need not be divisible.  Nothing here needs
`[CharZero F]`: the only geometry used is `End.intCast_injective`, which does not.
-/

@[expose] public section

open Polynomial WeierstrassCurve WeierstrassCurve.Affine

namespace WeierstrassCurve

variable {F : Type*} [Field F] [DecidableEq F] {W : Affine F}

section CMOrder

variable [IsAlgClosed F] [W.IsElliptic]

/-! ### `[n] ≠ 0` on points -/

/-- **Multiplication by a nonzero integer is not the zero map**, in point-level
form.

This is `End.intCast_injective` (`IsogenyTrace.lean`) read backwards: `(n : End W)`
IS multiplication by `n` definitionally, so an `n` annihilating every point is an
`n` whose cast agrees with the cast of `0`.  Stated separately because every
independence argument below reaches the geometry through this one step and does so
while holding points, not ring elements. -/
theorem eq_zero_of_forall_zsmul_eq_zero {n : ℤ}
    (h : ∀ P : W.Point, n • P = 0) : n = 0 := by
  refine End.intCast_injective (W := W) (Subtype.ext (AddMonoidHom.ext fun P => ?_))
  show n • P = (0 : ℤ) • P
  rw [h P, zero_zsmul]

/-- `(n : End W) = 0` exactly when `n = 0`. -/
theorem End.intCast_eq_zero_iff (n : ℤ) : (n : End W) = 0 ↔ n = 0 := by
  constructor
  · intro h
    refine End.intCast_injective (W := W) ?_
    rw [h, Int.cast_zero]
  · rintro rfl; exact Int.cast_zero

instance End.instCharZero : CharZero (End W) :=
  ⟨fun a b hab => by
    have h : ((a : ℤ) : End W) = ((b : ℤ) : End W) := by push_cast; exact_mod_cast hab
    exact_mod_cast End.intCast_injective (W := W) h⟩

/-! ### `1` and `φ` are `ℤ`-independent -/

/-- **`1` and `φ` are `ℤ`-independent in the endomorphism ring**, stated on points
so that a consumer holding a bare `AddMonoidHom` can use it without bundling.

The proof is the norm form, obtained without ever mentioning a quadratic field.
Apply `φ` to the relation `a • P + b • φ P = 0` and substitute `φ² = φ − m`:

    (a + b) • φ P = (b·m) • P.

Scale that by `b` and substitute `b • φ P = −(a • P)` from the original relation:

    (a² + a·b + b²·m) • P = 0   for every `P`,

so the integer `a² + ab + b²m` — the norm of `a + bφ` — annihilates `W(F)`, hence
is `0` by `eq_zero_of_forall_zsmul_eq_zero`.  Finally

    4(a² + ab + b²m) = (2a + b)² + b²(4m − 1)

is a sum of two nonnegative terms when `4m > 1`, so both vanish, so `b = 0` and
then `a = 0`.

Note that NO geometry is used about `φ`: it is an arbitrary additive endomorphism
satisfying the relation.  All the geometry sits in
`eq_zero_of_forall_zsmul_eq_zero`, i.e. in `[n] ≠ 0`, which is a fact about the
CURVE.  That is why `IsIsogeny φ` is absent from the hypotheses here and why it is
nevertheless indispensable in `X0.lean`: it is what makes such a `φ` exist at all
(`X² − X + (p+1)/4` has a root in `M₂(Ẑ)`, so every elliptic curve over `ℚ` carries
an ABSTRACT solution of the relation — see the docstring of
`not_forall_galoisScalar_of_cmEndomorphism`). -/
theorem eq_zero_of_cmRelation {m : ℤ} (hm : 1 < 4 * m)
    (φ : W.Point →+ W.Point)
    (hφ : ∀ P : W.Point, φ (φ P) = φ P - m • P)
    {a b : ℤ} (h : ∀ P : W.Point, a • P + b • φ P = 0) : a = 0 ∧ b = 0 := by
  have key : ∀ P : W.Point, (a ^ 2 + a * b + b ^ 2 * m) • P = 0 := by
    intro P
    -- Apply `φ` to `a • P + b • φ P = 0` and substitute `φ² = φ − m`.
    have hc : a • φ P + b • (φ P - m • P) = 0 := by
      have hd := congrArg φ (h P)
      rwa [map_add, map_zsmul, map_zsmul, map_zero, hφ] at hd
    -- Rearrange: `(a + b) • φ P = (b·m) • P`.
    have h2 : (a + b) • φ P = (b * m) • P := by
      have e : a • φ P + b • (φ P - m • P) = (a + b) • φ P - (b * m) • P := by
        rw [add_smul, smul_sub, smul_smul]; abel
      rw [e] at hc
      exact sub_eq_zero.mp hc
    -- `b • φ P = −(a • P)` is the original relation.
    have h3 : b • φ P = -(a • P) := by
      rw [eq_neg_iff_add_eq_zero, add_comm]; exact h P
    -- Scale `h2` by `b` and substitute.
    have h4 : (a + b) • (b • φ P) = (b * (b * m)) • P := by
      rw [smul_smul, mul_comm (a + b) b, ← smul_smul, h2, smul_smul]
    rw [h3, smul_neg, smul_smul] at h4
    have h5 : (b * (b * m)) • P - (-(((a + b) * a) • P)) = 0 := sub_eq_zero.mpr h4.symm
    rw [sub_neg_eq_add, ← add_smul] at h5
    have h6 : a ^ 2 + a * b + b ^ 2 * m = b * (b * m) + (a + b) * a := by ring
    rw [h6]
    exact h5
  have hnorm : a ^ 2 + a * b + b ^ 2 * m = 0 :=
    eq_zero_of_forall_zsmul_eq_zero (W := W) key
  -- `4·norm = (2a + b)² + b²(4m − 1)`, both terms nonnegative.
  have hsum : (2 * a + b) ^ 2 + b ^ 2 * (4 * m - 1) = 0 := by linear_combination 4 * hnorm
  have hb0 : b = 0 := by
    have hnn1 : 0 ≤ (2 * a + b) ^ 2 := sq_nonneg _
    have hnn2 : 0 ≤ b ^ 2 * (4 * m - 1) := mul_nonneg (sq_nonneg b) (by omega)
    have hz : b ^ 2 * (4 * m - 1) = 0 := by omega
    rcases mul_eq_zero.mp hz with hbb | hmm
    · exact sq_eq_zero_iff.mp hbb
    · omega
  subst hb0
  refine ⟨?_, rfl⟩
  have h7 : a ^ 2 = 0 := by linarith [hnorm]
  exact sq_eq_zero_iff.mp h7

/-- The form of `eq_zero_of_cmRelation` matching `X0.lean`'s spelling of the CM
relation, `φ (φ P) + m • P = φ P` with `m : ℕ`. -/
theorem eq_zero_of_cmRelation_nat {m : ℕ} (hm : 1 < 4 * m)
    (φ : W.Point →+ W.Point)
    (hφ : ∀ P : W.Point, φ (φ P) + m • P = φ P)
    {a b : ℤ} (h : ∀ P : W.Point, a • P + b • φ P = 0) : a = 0 ∧ b = 0 := by
  refine eq_zero_of_cmRelation (m := (m : ℤ)) (by exact_mod_cast hm) φ (fun P => ?_) h
  rw [natCast_zsmul]
  exact eq_sub_of_add_eq (hφ P)

/-! ### The order `ℤ[(1 + √(1−4m))/2]` and its embedding -/

/-- **`X² − X + m`**, the minimal polynomial of `(1 + √(1−4m))/2`.  At
`4m = p + 1` it is the minimal polynomial of `(1 + √−p)/2`, so
`AdjoinRoot (cmOrderPoly m)` IS the order `ℤ[(1 + √−p)/2]`. -/
noncomputable def cmOrderPoly (m : ℤ) : ℤ[X] := X ^ 2 - X + C m

theorem cmOrderPoly_monic (m : ℤ) : (cmOrderPoly m).Monic := by
  unfold cmOrderPoly
  monicity!

theorem natDegree_cmOrderPoly (m : ℤ) : (cmOrderPoly m).natDegree = 2 := by
  unfold cmOrderPoly
  compute_degree!

theorem degree_cmOrderPoly (m : ℤ) : (cmOrderPoly m).degree = 2 := by
  rw [Polynomial.degree_eq_natDegree (cmOrderPoly_monic m).ne_zero, natDegree_cmOrderPoly]
  rfl

/-- **Bundling**: an `AddMonoidHom` carrying an `IsIsogeny` witness, as an element
of the endomorphism RING.  This is the one-line bridge `X0.lean` needs, since its
CM endomorphism arrives in exactly that unbundled shape. -/
def End.ofIsogeny {φ : W.Point →+ W.Point} (hφ : IsIsogeny φ) : End W := ⟨φ, hφ⟩

@[simp] theorem End.coe_ofIsogeny {φ : W.Point →+ W.Point} (hφ : IsIsogeny φ) :
    ((End.ofIsogeny hφ : End W) : AddMonoid.End W.Point) = φ := rfl

/-- `φ² + m = φ` in the ring is exactly the pointwise relation, in the `+`
spelling `X0.lean` uses (`φ (φ P) + m • P = φ P`).

Both directions are `rfl` under the hood: `End.coe_add_apply`, `End.mul_apply` and
`End.intCast_apply` are all literal `rfl`, so the two sides of each `show` below
are definitionally equal and the proof only has to name the reduction. -/
theorem End.cmRelation_iff {m : ℤ} (φ : End W) :
    φ * φ + (m : End W) = φ ↔ ∀ P : W.Point,
      (φ : AddMonoid.End W.Point) ((φ : AddMonoid.End W.Point) P) + m • P
        = (φ : AddMonoid.End W.Point) P := by
  constructor
  · intro h P
    exact congrArg (fun f : End W => (f : AddMonoid.End W.Point) P) h
  · intro h
    refine Subtype.ext (AddMonoidHom.ext fun P => ?_)
    exact h P

/-- The subtractive spelling, for consumers that hold `φ (φ P) = φ P - m • P`. -/
theorem End.cmRelation_iff' {m : ℤ} (φ : End W) :
    φ * φ + (m : End W) = φ ↔ ∀ P : W.Point,
      (φ : AddMonoid.End W.Point) ((φ : AddMonoid.End W.Point) P)
        = (φ : AddMonoid.End W.Point) P - m • P := by
  rw [End.cmRelation_iff]
  exact forall_congr' fun P => ⟨fun hP => eq_sub_of_add_eq hP, fun hP => by rw [hP]; abel⟩

/-- **`ℤ`-independence of `1` and `φ` inside the endomorphism ring** — the ring
form of `eq_zero_of_cmRelation`. -/
theorem End.cmIndep {m : ℤ} (hm : 1 < 4 * m) (φ : End W)
    (hφ : φ * φ + (m : End W) = φ) {a b : ℤ}
    (h : (a : End W) + (b : End W) * φ = 0) : a = 0 ∧ b = 0 := by
  refine eq_zero_of_cmRelation (W := W) hm (φ : AddMonoid.End W.Point)
    ((End.cmRelation_iff' φ).mp hφ) (fun P => ?_)
  exact congrArg (fun f : End W => (f : AddMonoid.End W.Point) P) h

/-- Evaluation of integer polynomials at `φ`, as a ring map.

`End W` is NOT commutative, so this cannot be `Polynomial.aeval`; it is
`eval₂RingHom'`, whose commutation hypothesis is discharged by the centrality of
`Int.cast` in any ring. -/
noncomputable def cmEvalHom (φ : End W) : ℤ[X] →+* End W :=
  Polynomial.eval₂RingHom' (Int.castRingHom (End W)) φ (fun a => Int.cast_commute a φ)

@[simp] theorem cmEvalHom_X (φ : End W) : cmEvalHom φ X = φ := by
  simp [cmEvalHom, Polynomial.eval₂RingHom']

@[simp] theorem cmEvalHom_C (φ : End W) (c : ℤ) : cmEvalHom φ (C c) = (c : End W) := by
  simp [cmEvalHom, Polynomial.eval₂RingHom']

theorem cmEvalHom_cmOrderPoly {m : ℤ} (φ : End W)
    (hφ : φ * φ + (m : End W) = φ) : cmEvalHom φ (cmOrderPoly m) = 0 := by
  rw [cmOrderPoly, map_add, map_sub, map_pow, cmEvalHom_X, cmEvalHom_C, sq,
    sub_add_eq_add_sub, hφ, sub_self]

/-- **THE CM ORDER, EMBEDDED.**  `AdjoinRoot (X² − X + m)` — the order
`ℤ[(1 + √(1−4m))/2]` — maps to `End W`, sending the root to `φ`.

At `4m = p + 1` and `p ≡ 3 mod 4` the source is the maximal order `O_K` of
`K = ℚ(√−p)`.  With `cmOrderHom_injective` this says precisely that **the subring
of `End W` generated by `φ` is `O_K`**, which is what "`W` has complex
multiplication by `O_K`" means. -/
noncomputable def cmOrderHom {m : ℤ} (φ : End W)
    (hφ : φ * φ + (m : End W) = φ) : AdjoinRoot (cmOrderPoly m) →+* End W :=
  Ideal.Quotient.lift _ (cmEvalHom φ) (by
    intro g hg
    rcases Ideal.mem_span_singleton.mp hg with ⟨c, rfl⟩
    rw [map_mul, cmEvalHom_cmOrderPoly φ hφ, zero_mul])

@[simp] theorem cmOrderHom_mk {m : ℤ} (φ : End W)
    (hφ : φ * φ + (m : End W) = φ) (g : ℤ[X]) :
    cmOrderHom φ hφ (AdjoinRoot.mk _ g) = cmEvalHom φ g := rfl

@[simp] theorem cmOrderHom_root {m : ℤ} (φ : End W)
    (hφ : φ * φ + (m : End W) = φ) :
    cmOrderHom φ hφ (AdjoinRoot.root (cmOrderPoly m)) = φ := by
  rw [AdjoinRoot.root, cmOrderHom_mk, cmEvalHom_X]

/-- **The embedding is injective**: `φ` really does generate a copy of the order,
not a proper quotient of it.

Every class in `AdjoinRoot (X² − X + m)` is represented by a polynomial of degree
`≤ 1` (reduce modulo the monic `X² − X + m`), i.e. by `bX + a`; it maps to
`a + bφ`, and `eq_zero_of_cmRelation` says that vanishes only for `a = b = 0`. -/
theorem cmOrderHom_injective {m : ℤ} (hm : 1 < 4 * m) (φ : End W)
    (hφ : φ * φ + (m : End W) = φ) :
    Function.Injective (cmOrderHom φ hφ) := by
  rw [injective_iff_map_eq_zero]
  intro x hx
  obtain ⟨g, rfl⟩ := AdjoinRoot.mk_surjective (g := cmOrderPoly m) x
  -- Reduce `g` modulo the monic `cmOrderPoly m`; the class is unchanged.
  set r : ℤ[X] := g %ₘ cmOrderPoly m with hr
  have hmk : AdjoinRoot.mk (cmOrderPoly m) g = AdjoinRoot.mk (cmOrderPoly m) r := by
    refine (AdjoinRoot.mk_eq_mk).mpr ?_
    rw [hr, modByMonic_eq_sub_mul_div g (cmOrderPoly m)]
    exact ⟨g /ₘ cmOrderPoly m, by ring⟩
  -- `deg r ≤ 1`, so `r = C b * X + C a`.
  have hnd : r.natDegree ≤ 1 := by
    by_cases hz : r = 0
    · simp [hz]
    · have hlt : r.degree < (cmOrderPoly m).degree :=
        degree_modByMonic_lt g (cmOrderPoly_monic m)
      have := Polynomial.natDegree_lt_natDegree hz hlt
      rw [natDegree_cmOrderPoly] at this
      omega
  have hform : r = C (r.coeff 1) * X + C (r.coeff 0) :=
    Polynomial.eq_X_add_C_of_natDegree_le_one hnd
  -- The image is `a + bφ`, which vanishes only trivially.
  rw [hmk] at hx ⊢
  rw [cmOrderHom_mk, hform, map_add, map_mul, cmEvalHom_C, cmEvalHom_C, cmEvalHom_X] at hx
  have hab : (((r.coeff 0) : ℤ) : End W) + (((r.coeff 1) : ℤ) : End W) * φ = 0 := by
    rw [← hx]; ring_nf; rw [add_comm]
  obtain ⟨ha, hb⟩ := End.cmIndep (W := W) hm φ hφ hab
  rw [hform, ha, hb]
  simp

/-! ### The order acts on the torsion, through `O/nO` -/

/-- **The CM order acting on `W[n]`.**  Compose the embedding of the order with the
existing torsion representation `End.torsionRep` (`IsogenyTrace.lean`).

The target is `ZMod n`-linear maps, not merely additive ones, because `W[n]` is a
`ZMod n`-module and an additive map between `n`-torsion modules is automatically
`ZMod n`-linear. -/
noncomputable def cmTorsionRep {m : ℤ} (φ : End W)
    (hφ : φ * φ + (m : End W) = φ) (n : ℕ) :
    AdjoinRoot (cmOrderPoly m) →+* Module.End (ZMod n) (W.nTorsion n) :=
  (End.torsionRep W n).comp (cmOrderHom φ hφ)

omit [IsAlgClosed F] [W.IsElliptic] in
/-- **`n` acts as `0` on `W[n]`.**

`Module.End (ZMod n) (W[n])` is a `ZMod n`-algebra, so the natural number `n` in it
is `algebraMap (n : ZMod n)`, and `(n : ZMod n) = 0`.  No torsion computation is
needed: the `ZMod n`-module structure on `W[n]` (supplied by `Torsion.lean`) has
already recorded it. -/
theorem natCast_torsion_eq_zero (n : ℕ) :
    ((n : ℕ) : Module.End (ZMod n) (W.nTorsion n)) = 0 := by
  rw [← map_natCast (algebraMap (ZMod n) (Module.End (ZMod n) (W.nTorsion n))) n,
    ZMod.natCast_self, map_zero]

/-- The CM action on `W[n]` kills `n`. -/
theorem cmTorsionRep_natCast {m : ℤ} (φ : End W)
    (hφ : φ * φ + (m : End W) = φ) (n : ℕ) :
    cmTorsionRep φ hφ n (n : AdjoinRoot (cmOrderPoly m)) = 0 := by
  rw [map_natCast, natCast_torsion_eq_zero]

/-- **`W[n]` IS A MODULE OVER `O/nO`.**  The action of the order on the
`n`-torsion factors through the quotient by `n`, because `n` annihilates `W[n]`.

At `n = q` prime and `4m = p + 1` this is the object
`not_forall_galoisScalar_of_cmEndomorphism` is about: `E[q]` as a module over
`O_K/q`, the ring whose unit group is the Cartan subgroup `C = (O_K/q)ˣ`. -/
noncomputable def cmTorsionQuotRep {m : ℤ} (φ : End W)
    (hφ : φ * φ + (m : End W) = φ) (n : ℕ) :
    (AdjoinRoot (cmOrderPoly m) ⧸
        Ideal.span {(n : AdjoinRoot (cmOrderPoly m))}) →+*
      Module.End (ZMod n) (W.nTorsion n) :=
  Ideal.Quotient.lift _ (cmTorsionRep φ hφ n) (by
    intro g hg
    rcases Ideal.mem_span_singleton.mp hg with ⟨c, rfl⟩
    rw [map_mul, cmTorsionRep_natCast φ hφ n, zero_mul])

/-- The `O/nO`-module structure on `W[n]` carried by `cmTorsionQuotRep`. -/
@[reducible] noncomputable def cmTorsionModule {m : ℤ} (φ : End W)
    (hφ : φ * φ + (m : End W) = φ) (n : ℕ) :
    Module (AdjoinRoot (cmOrderPoly m) ⧸
        Ideal.span {(n : AdjoinRoot (cmOrderPoly m))}) (W.nTorsion n) :=
  Module.compHom _ (cmTorsionQuotRep φ hφ n)

end CMOrder

end WeierstrassCurve
