module

/-
MordellWeil.lean — own work for the Fermat project (not vendored from the
FLT project; mathlib has no Mordell–Weil theorem of any kind).

# Mordell–Weil over `ℚ`, and the modular curve `X_1(11)` as `11a3`

This module builds the load-bearing absence recorded in the
missing-machinery list of `Fermat/FLT/FreyCurve/MazurTorsion.lean`:

  3. **Mordell–Weil over `ℚ`** — mathlib has NONE of it, and it blocks even
     the classically-provable levels `11` and `13` of Mazur's torsion
     theorem.

## Why this is the right next brick

`MazurTorsion.lean` proves `no_prime_torsion_ge_eleven` by reducing to eight
per-level nodes, and then proves each node's general form from a
**Tate-coordinate** node `tateNormalForm_origin_order_ne_ℓ` via the PROVEN
`exists_tateNormalForm`. That reduction already discharges the moduli half
of missing-machinery item 1: the two-parameter family
`tateNormalForm b c : y² + (1 − c)xy − by = x³ − bx²` with the marked point
`(0,0)` is a plane model of `X_1(ℓ)` in the `(b,c)`-coordinates.

What is left at level `11` is exactly the classical Billing–Mahler
argument, and it has two halves:

* the **plane model**: the locus where the origin has order `11` is
  birational to the elliptic curve `v² + v = u³ − u²` — Cremona **11a3**,
  which *is* `X_1(11)`, of genus `1`; and
* the **arithmetic**: `11a3` has Mordell–Weil rank `0` over `ℚ` with
  torsion `ℤ/5`, so `11a3(ℚ)` has exactly five points — and all five are
  cusps, carrying no elliptic curve with a point of order `11`.

The second half is where Mordell–Weil enters, and it is the only reason
level `11` is not already provable here.

## What is PROVEN here and what is left

PROVEN:
* `WeierstrassCurve.curve11a3` and its `IsElliptic` instance — the
  discriminant is `Δ = −11 ≠ 0`, computed rather than asserted.
* `WeierstrassCurve.curve11a3_finite` — `11a3(ℚ)` is FINITE, assembled from
  the two leaves below through `AddCommGroup.finite_of_fg_torsion`. This is
  the descent step "finitely generated + rank `0` ⟹ finite", and it is the
  piece that makes the Mordell–Weil leaf load-bearing rather than
  decorative.

LEAVES, in dependency order:
* `WeierstrassCurve.mordellWeil` — **the Mordell–Weil theorem**: `E(ℚ)` is
  a finitely generated abelian group, for every elliptic curve `E` over
  `ℚ`. Mordell (1922); Weil (1929). Its classical proof is the descent
  `weak Mordell–Weil + theory of heights`: (a) `E(ℚ)/2E(ℚ)` is finite,
  which needs the Kummer sequence, `S`-units and finiteness of the class
  group; (b) the canonical height is a positive-definite quadratic form
  with finitely many points below any bound; (c) infinite descent
  assembles the two. **None of (a), (b), (c) exists in mathlib**, so this
  is stated as a single node rather than decomposed — decomposing it would
  create bricks with no written consumer, which this project forbids. The
  natural next cut is (a) and (b) as separate nodes with (c) as their
  proven assembly.
* `WeierstrassCurve.curve11a3_isTorsion` — **rank `0` for 11a3**, in the
  concrete form "every rational point is torsion". Classically a
  `5`-isogeny descent: `11a3` admits a rational `5`-isogeny, and both
  `5`-Selmer groups are trivial. Billing–Mahler (1940).
* `WeierstrassCurve.curve11a3_points` — the enumeration of the five
  rational points `O, (0,0), (0,−1), (1,0), (1,−1)`, given finiteness. The
  group is `ℤ/5`, generated by `(0,0)`.

The `X_1(11)` plane model itself — the birational passage between
`tateNormalForm b c` with an order-`11` origin and a rational point of
`curve11a3` — lives in `MazurTorsion.lean`, next to its consumer.

UPDATE 2026-07-26. That passage is now `x1Eleven_plane_ne_zero`, and it
takes the PLANE route rather than the original birational one: main's
`MazurX1Plane` section derives the plane quintic `F₁₁(b, c)` inside Lean
from the proven `normEDS`/`preΨ'` recursion, so the modular curve never
has to be transported — one leaf fewer. `x1Eleven_plane_ne_zero` reduces
`F₁₁` to this file's `curve11a3` by an explicit birational map and
consumes `curve11a3_points` through
`WeierstrassCurve.x1Eleven_11a3_x_eq_zero_or_one`. That is what makes
this module reachable from the root theorem.
-/

public import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
public import Mathlib.GroupTheory.FiniteAbelian.Basic

@[expose] public section

namespace WeierstrassCurve

/-! ### The Mordell–Weil theorem -/

/-- **The Mordell–Weil theorem** (sorry leaf — absent from mathlib
entirely, 2026-07-25): the group of rational points of an elliptic curve
over `ℚ` is finitely generated. Mordell, "On the rational solutions of the
indeterminate equations of the third and fourth degrees" (Proc. Camb. Phil.
Soc. 21, 1922); Weil, "L'arithmétique sur les courbes algébriques" (Acta
Math. 52, 1929).

This is missing-machinery item 3 of `MazurTorsion.lean`'s section note, and
it is the load-bearing absence: it blocks the classically-provable torsion
levels `11` and `13` just as much as the deep ones.

THE CLASSICAL PROOF, and why it is not decomposed here. Descent in three
stages: (a) **weak Mordell–Weil**, `E(ℚ)/2E(ℚ)` is finite — via the Kummer
sequence `0 → E(ℚ)/2E(ℚ) → H¹(G_ℚ, E[2]) → …`, bounded by the finiteness of
the `S`-unit group and of the class group; (b) **heights** — the canonical
height `ĥ` is a positive-definite quadratic form on `E(ℚ) ⊗ ℝ`, and
`{P : ĥ(P) ≤ B}` is finite for every `B`; (c) the **descent lemma**
assembling (a) and (b). Mathlib has none of the three, and this development
forbids building bricks in front of an unwritten consumer, so the theorem
is one node here. The natural next cut is (a) and (b) as nodes with (c) as
their PROVEN assembly. Silverman AEC VIII.

Note the hypothesis is `[E.IsElliptic]` and the conclusion is about the
AFFINE point group, which is the one carrying the `AddCommGroup` structure
used throughout `MazurTorsion.lean`. -/
theorem mordellWeil (E : WeierstrassCurve ℚ) [E.IsElliptic] :
    AddGroup.FG E.toAffine.Point :=
  sorry

/-! ### `X_1(11)` as the elliptic curve 11a3 -/

/-- **The modular curve `X_1(11)`**, as the elliptic curve
`y² + y = x³ − x²` — Cremona label **11a3**, the curve of conductor `11`
and discriminant `Δ = −11`.

`X_1(11)` has genus `1` and a rational cusp, so it *is* an elliptic curve
over `ℚ`; this is that curve. Its Mordell–Weil group is `ℤ/5`, and all five
rational points are cusps — which is precisely why no elliptic curve over
`ℚ` has a rational point of order `11`. -/
def curve11a3 : WeierstrassCurve ℚ := ⟨0, -1, 1, 0, 0⟩

/-- `11a3` is an elliptic curve: its discriminant is `Δ = −11 ≠ 0`.

Computed from `b₂ = −4`, `b₄ = 0`, `b₆ = 1`, `b₈ = −1`, giving
`Δ = −b₂²b₈ − 8b₄³ − 27b₆² + 9b₂b₄b₆ = 16 − 27 = −11`. -/
instance instIsEllipticCurve11a3 : curve11a3.IsElliptic := by
  refine ⟨?_⟩
  refine isUnit_iff_ne_zero.mpr ?_
  simp only [curve11a3, WeierstrassCurve.Δ, WeierstrassCurve.b₂, WeierstrassCurve.b₄,
    WeierstrassCurve.b₆, WeierstrassCurve.b₈]
  norm_num

/-- **Rank `0` for `11a3`** (sorry leaf, 2026-07-25), in the concrete form
that carries the content: every rational point of `y² + y = x³ − x²` is a
torsion point.

Classically this is a descent by the rational `5`-isogeny that `11a3`
admits: both `5`-Selmer groups vanish, so the rank is `0`. Billing–Mahler,
"On exceptional points on cubic curves" (J. London Math. Soc. 15, 1940);
subsumed in Mazur 1977, Thm 7.

Stated as `AddMonoid.IsTorsion` rather than as `rank = 0` deliberately:
there is no rank function here to state the latter against, and this form
is exactly what `curve11a3_finite` consumes. Any future `rank` definition
should be proven equivalent to this at `11a3` rather than replacing it. -/
theorem curve11a3_isTorsion : AddMonoid.IsTorsion curve11a3.toAffine.Point :=
  sorry

/-- **`11a3(ℚ)` is finite** (PROVEN 2026-07-25 from the two leaves above).

This is the descent conclusion "finitely generated + rank `0` ⟹ finite",
and it is where the Mordell–Weil leaf does its work: neither leaf gives
finiteness alone. A rank-`0` curve has a finitely generated torsion group,
hence a finite one. -/
theorem curve11a3_finite : Finite curve11a3.toAffine.Point :=
  haveI : AddGroup.FG curve11a3.toAffine.Point := mordellWeil curve11a3
  AddCommGroup.finite_of_fg_torsion _ curve11a3_isTorsion

/-- **The five rational points of `11a3`** (sorry leaf, 2026-07-25): given
that `11a3(ℚ)` is finite, its affine rational points are exactly
`(0,0)`, `(0,−1)`, `(1,0)`, `(1,−1)`. Together with the point at infinity
these are the five elements of `11a3(ℚ) ≅ ℤ/5`, generated by `(0,0)`.

The finiteness hypothesis is what makes this a finite computation rather
than a Diophantine problem, and it is supplied by `curve11a3_finite` — so
the Mordell–Weil leaf is genuinely load-bearing here and not decorative.
With finiteness in hand the group is its own torsion subgroup, which
injects into `11a3(𝔽_p)` for any prime `p ≠ 11` of good reduction;
`#11a3(𝔽_3) = 5` already forces the order to divide `5`, and the four
points listed are visibly on the curve and distinct.

All five points are CUSPS of `X_1(11)`; that is the input to
`WeierstrassCurve.x1Eleven_11a3_x_eq_zero_or_one` in `MazurTorsion.lean`,
whose consumer `x1Eleven_plane_ne_zero` shows the two cusps with a finite
`b`-coordinate, `x = 0` and `x = 1`, to be the loci `b = c² + c` and
`b = c` of the Tate family — neither of which meets the chart `b ≠ 0`. -/
theorem curve11a3_points (_hfin : Finite curve11a3.toAffine.Point) (x y : ℚ)
    (_h : curve11a3.toAffine.Nonsingular x y) :
    (x, y) = ((0 : ℚ), (0 : ℚ)) ∨ (x, y) = ((0 : ℚ), (-1 : ℚ)) ∨
      (x, y) = ((1 : ℚ), (0 : ℚ)) ∨ (x, y) = ((1 : ℚ), (-1 : ℚ)) :=
  sorry

end WeierstrassCurve
