module

/-
MordellWeil.lean — own work for the Fermat project (not vendored from the
FLT project; mathlib has no Mordell–Weil theorem of any kind).

# Mordell–Weil over `ℚ`, and the modular curve `X_1(11)` as `11a3`

This module builds the load-bearing absence recorded in the
missing-machinery list of `Fermat/FLT/FreyCurve/MazurTorsion.lean`:

  3. **Mordell–Weil over `ℚ`** — mathlib has NONE of it, and it blocks even
     the classically-provable levels `11` and `13` of Mazur's torsion
     theorem.

## Why this is the right next brick

`MazurTorsion.lean` proves `no_prime_torsion_ge_eleven` by reducing to eight
per-level nodes, and then proves each node's general form from a
**Tate-coordinate** node `tateNormalForm_origin_order_ne_ℓ` via the PROVEN
`exists_tateNormalForm`. That reduction already discharges the moduli half
of missing-machinery item 1: the two-parameter family
`tateNormalForm b c : y² + (1 − c)xy − by = x³ − bx²` with the marked point
`(0,0)` is a plane model of `X_1(ℓ)` in the `(b,c)`-coordinates.

What is left at level `11` is exactly the classical Billing–Mahler
argument, and it has two halves:

* the **plane model**: the locus where the origin has order `11` is
  birational to the elliptic curve `v² + v = u³ − u²` — Cremona **11a3**,
  which *is* `X_1(11)`, of genus `1`; and
* the **arithmetic**: `11a3` has Mordell–Weil rank `0` over `ℚ` with
  torsion `ℤ/5`, so `11a3(ℚ)` has exactly five points — and all five are
  cusps, carrying no elliptic curve with a point of order `11`.

The second half is where Mordell–Weil enters, and it is the only reason
level `11` is not already provable here.

## What is PROVEN here and what is left

PROVEN:
* `WeierstrassCurve.curve11a3` and its `IsElliptic` instance — the
  discriminant is `Δ = −11 ≠ 0`, computed rather than asserted.
* `WeierstrassCurve.curve11a3_finite` — `11a3(ℚ)` is FINITE, assembled from
  the two leaves below through `AddCommGroup.finite_of_fg_torsion`. This is
  the descent step "finitely generated + rank `0` ⟹ finite", and it is the
  piece that makes the Mordell–Weil leaf load-bearing rather than
  decorative.

* the whole `14a4` block (`curve14a4_affine_points`, `curve14a4_finite`,
  `curve14a4_isTorsion`) — see `curve14a4_rational_T`. UPDATE 2026-07-26: level
  `14` no longer consumes `mordellWeil` at all. Its two leaves
  (`curve14a4_isTorsion`, `curve14a4_points`) were replaced by the single
  plane-Diophantine leaf `curve14a4_rational_T` on the descent model
  `W² = T³ − 11T² + 32T`, from which rank `0`, finiteness AND the point
  enumeration all follow — they are not independent facts, and neither of the
  two former leaves implied the other. The same restructuring is available at
  `11a3` and has NOT been carried out here; that is the obvious next step for
  this file.

LEAVES, in dependency order:
* `WeierstrassCurve.mordellWeil` — **the Mordell–Weil theorem**: `E(ℚ)` is
  a finitely generated abelian group, for every elliptic curve `E` over
  `ℚ`. Mordell (1922); Weil (1929). Its classical proof is the descent
  `weak Mordell–Weil + theory of heights`: (a) `E(ℚ)/2E(ℚ)` is finite,
  which needs the Kummer sequence, `S`-units and finiteness of the class
  group; (b) the canonical height is a positive-definite quadratic form
  with finitely many points below any bound; (c) infinite descent
  assembles the two. **None of (a), (b), (c) exists in mathlib**, so this
  is stated as a single node rather than decomposed — decomposing it would
  create bricks with no written consumer, which this project forbids. The
  natural next cut is (a) and (b) as separate nodes with (c) as their
  proven assembly.
* `WeierstrassCurve.curve11a3_isTorsion` — **rank `0` for 11a3**, in the
  concrete form "every rational point is torsion". Classically a
  `5`-isogeny descent: `11a3` admits a rational `5`-isogeny, and both
  `5`-Selmer groups are trivial. Billing–Mahler (1940).
* `WeierstrassCurve.curve11a3_points` — the enumeration of the five
  rational points `O, (0,0), (0,−1), (1,0), (1,−1)`, given finiteness. The
  group is `ℤ/5`, generated by `(0,0)`.

The `X_1(11)` plane model itself — the birational passage between
`tateNormalForm b c` with an order-`11` origin and a rational point of
`curve11a3` — lives in `MazurTorsion.lean`, next to its consumer.

UPDATE 2026-07-26. That passage is now `x1Eleven_plane_ne_zero`, and it
takes the PLANE route rather than the original birational one: main's
`MazurX1Plane` section derives the plane quintic `F₁₁(b, c)` inside Lean
from the proven `normEDS`/`preΨ'` recursion, so the modular curve never
has to be transported — one leaf fewer. `x1Eleven_plane_ne_zero` reduces
`F₁₁` to this file's `curve11a3` by an explicit birational map and
consumes `curve11a3_points` through
`WeierstrassCurve.x1Eleven_11a3_x_eq_zero_or_one`. That is what makes
this module reachable from the root theorem.
-/

public import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
public import Mathlib.GroupTheory.FiniteAbelian.Basic

@[expose] public section

namespace WeierstrassCurve

/-! ### The Mordell–Weil theorem -/

/-- **The Mordell–Weil theorem** (sorry leaf — absent from mathlib
entirely, 2026-07-25): the group of rational points of an elliptic curve
over `ℚ` is finitely generated. Mordell, "On the rational solutions of the
indeterminate equations of the third and fourth degrees" (Proc. Camb. Phil.
Soc. 21, 1922); Weil, "L'arithmétique sur les courbes algébriques" (Acta
Math. 52, 1929).

This is missing-machinery item 3 of `MazurTorsion.lean`'s section note, and
it is the load-bearing absence: it blocks the classically-provable torsion
levels `11` and `13` just as much as the deep ones.

THE CLASSICAL PROOF, and why it is not decomposed here. Descent in three
stages: (a) **weak Mordell–Weil**, `E(ℚ)/2E(ℚ)` is finite — via the Kummer
sequence `0 → E(ℚ)/2E(ℚ) → H¹(G_ℚ, E[2]) → …`, bounded by the finiteness of
the `S`-unit group and of the class group; (b) **heights** — the canonical
height `ĥ` is a positive-definite quadratic form on `E(ℚ) ⊗ ℝ`, and
`{P : ĥ(P) ≤ B}` is finite for every `B`; (c) the **descent lemma**
assembling (a) and (b). Mathlib has none of the three, and this development
forbids building bricks in front of an unwritten consumer, so the theorem
is one node here. The natural next cut is (a) and (b) as nodes with (c) as
their PROVEN assembly. Silverman AEC VIII.

Note the hypothesis is `[E.IsElliptic]` and the conclusion is about the
AFFINE point group, which is the one carrying the `AddCommGroup` structure
used throughout `MazurTorsion.lean`. -/
theorem mordellWeil (E : WeierstrassCurve ℚ) [E.IsElliptic] :
    AddGroup.FG E.toAffine.Point :=
  sorry

/-! ### `X_1(11)` as the elliptic curve 11a3 -/

/-- **The modular curve `X_1(11)`**, as the elliptic curve
`y² + y = x³ − x²` — Cremona label **11a3**, the curve of conductor `11`
and discriminant `Δ = −11`.

`X_1(11)` has genus `1` and a rational cusp, so it *is* an elliptic curve
over `ℚ`; this is that curve. Its Mordell–Weil group is `ℤ/5`, and all five
rational points are cusps — which is precisely why no elliptic curve over
`ℚ` has a rational point of order `11`. -/
def curve11a3 : WeierstrassCurve ℚ := ⟨0, -1, 1, 0, 0⟩

/-- `11a3` is an elliptic curve: its discriminant is `Δ = −11 ≠ 0`.

Computed from `b₂ = −4`, `b₄ = 0`, `b₆ = 1`, `b₈ = −1`, giving
`Δ = −b₂²b₈ − 8b₄³ − 27b₆² + 9b₂b₄b₆ = 16 − 27 = −11`. -/
instance instIsEllipticCurve11a3 : curve11a3.IsElliptic := by
  refine ⟨?_⟩
  refine isUnit_iff_ne_zero.mpr ?_
  simp only [curve11a3, WeierstrassCurve.Δ, WeierstrassCurve.b₂, WeierstrassCurve.b₄,
    WeierstrassCurve.b₆, WeierstrassCurve.b₈]
  norm_num

/-- **Rank `0` for `11a3`** (sorry leaf, 2026-07-25), in the concrete form
that carries the content: every rational point of `y² + y = x³ − x²` is a
torsion point.

Classically this is a descent by the rational `5`-isogeny that `11a3`
admits: both `5`-Selmer groups vanish, so the rank is `0`. Billing–Mahler,
"On exceptional points on cubic curves" (J. London Math. Soc. 15, 1940);
subsumed in Mazur 1977, Thm 7.

Stated as `AddMonoid.IsTorsion` rather than as `rank = 0` deliberately:
there is no rank function here to state the latter against, and this form
is exactly what `curve11a3_finite` consumes. Any future `rank` definition
should be proven equivalent to this at `11a3` rather than replacing it. -/
theorem curve11a3_isTorsion : AddMonoid.IsTorsion curve11a3.toAffine.Point :=
  sorry

/-- **`11a3(ℚ)` is finite** (PROVEN 2026-07-25 from the two leaves above).

This is the descent conclusion "finitely generated + rank `0` ⟹ finite",
and it is where the Mordell–Weil leaf does its work: neither leaf gives
finiteness alone. A rank-`0` curve has a finitely generated torsion group,
hence a finite one. -/
theorem curve11a3_finite : Finite curve11a3.toAffine.Point :=
  haveI : AddGroup.FG curve11a3.toAffine.Point := mordellWeil curve11a3
  AddCommGroup.finite_of_fg_torsion _ curve11a3_isTorsion

/-- **The five rational points of `11a3`** (sorry leaf, 2026-07-25): given
that `11a3(ℚ)` is finite, its affine rational points are exactly
`(0,0)`, `(0,−1)`, `(1,0)`, `(1,−1)`. Together with the point at infinity
these are the five elements of `11a3(ℚ) ≅ ℤ/5`, generated by `(0,0)`.

The finiteness hypothesis is what makes this a finite computation rather
than a Diophantine problem, and it is supplied by `curve11a3_finite` — so
the Mordell–Weil leaf is genuinely load-bearing here and not decorative.
With finiteness in hand the group is its own torsion subgroup, which
injects into `11a3(𝔽_p)` for any prime `p ≠ 11` of good reduction;
`#11a3(𝔽_3) = 5` already forces the order to divide `5`, and the four
points listed are visibly on the curve and distinct.

All five points are CUSPS of `X_1(11)`; that is the input to
`WeierstrassCurve.x1Eleven_11a3_x_eq_zero_or_one` in `MazurTorsion.lean`,
whose consumer `x1Eleven_plane_ne_zero` shows the two cusps with a finite
`b`-coordinate, `x = 0` and `x = 1`, to be the loci `b = c² + c` and
`b = c` of the Tate family — neither of which meets the chart `b ≠ 0`. -/
theorem curve11a3_points (_hfin : Finite curve11a3.toAffine.Point) (x y : ℚ)
    (_h : curve11a3.toAffine.Nonsingular x y) :
    (x, y) = ((0 : ℚ), (0 : ℚ)) ∨ (x, y) = ((0 : ℚ), (-1 : ℚ)) ∨
      (x, y) = ((1 : ℚ), (0 : ℚ)) ∨ (x, y) = ((1 : ℚ), (-1 : ℚ)) :=
  sorry

/-! ### `X_1(14)` as the elliptic curve 14a4 -/

/-- **The modular curve `X_1(14)`**, as the elliptic curve
`y² + xy + y = x³ − x` — Cremona label **14a4**, the curve of conductor `14`
and discriminant `Δ = −28`.

`X_1(14)` has genus `1` and a rational cusp, so it *is* an elliptic curve over
`ℚ`; this is that curve. Its Mordell–Weil group is `ℤ/6`, and all six rational
points are cusps — which is precisely why no elliptic curve over `ℚ` carries a
rational point of order `2` together with one of order `7`.

IDENTIFICATION (Magma 2026-07-26, untrusted searcher; the classical fact is
Kubert's and Ligozat's). The `2`-division cubic of the Kubert family
`E(d³ − d², d² − d)` of `X_1(7)`, i.e. the plane sextic

    4x³ + ((1 + d − d²)² − 4(d³ − d²))x² − 2(1 + d − d²)(d³ − d²)x + (d³ − d²)²

in the coordinates `(d, x)`, has projective closure of `Genus = 1`, and
`EllipticCurve` + `MinimalModel` return exactly `y² + xy + y = x³ − x`, with
`Conductor = 14` and `CremonaReference = 14a4`. That birational map is written
out and PROVEN in `x1_fourteen_no_rational_point`
(`Fermat/FLT/FreyCurve/TateNormalForm.lean`), so this curve is the whole
arithmetic content of level `14`, exactly as `curve11a3` is of level `11`. -/
def curve14a4 : WeierstrassCurve ℚ := ⟨1, 0, 1, -1, 0⟩

/-- `14a4` is an elliptic curve: its discriminant is `Δ = −28 ≠ 0`.

Computed from `b₂ = 1`, `b₄ = −1`, `b₆ = 1`, `b₈ = 0`, giving
`Δ = −b₂²b₈ − 8b₄³ − 27b₆² + 9b₂b₄b₆ = 0 + 8 − 27 − 9 = −28`. -/
instance instIsEllipticCurve14a4 : curve14a4.IsElliptic := by
  refine ⟨?_⟩
  refine isUnit_iff_ne_zero.mpr ?_
  simp only [curve14a4, WeierstrassCurve.Δ, WeierstrassCurve.b₂, WeierstrassCurve.b₄,
    WeierstrassCurve.b₆, WeierstrassCurve.b₈]
  norm_num

/-- **The rational points of the descent model of `14a4`** (sorry leaf,
2026-07-26 — the SINGLE replacement for what were the two leaves
`curve14a4_isTorsion` and `curve14a4_points`): the only rational points of

    W² = T³ − 11T² + 32T

have `T ∈ {0, 4, 8}`.

THE MODEL. Completing the square in `14a4 : y² + xy + y = x³ − x` gives
`(2y + x + 1)² = 4x³ + x² − 2x + 1`, and scaling by `T = 4(x + 1)`,
`W = 4(2y + x + 1)` clears the leading `4` and moves the rational `2`-torsion
point to the origin:

    T = 4x + 4,   W = 8y + 4x + 4,   W² = T³ − 11T² + 32T,

an isomorphism of `14a4` onto `[0, −11, 0, 32, 0]` (`Δ = −114688`, conductor
`14`, torsion `ℤ/6`, rank `0` — PARI 2026-07-26, untrusted searcher). The six
rational points are `∞` and `T ∈ {0, 4, 8}` with `W ∈ {0}, {±4}, {±8}`; they
pull back to the point at infinity and the five affine points listed in
`curve14a4_points`.

WHY THIS IS THE RIGHT LEAF, AND WHY IT IS ONE RATHER THAN TWO. Rank `0` and
the torsion enumeration are not independent facts about `14a4`: the single
Diophantine statement above yields both, and neither of the two former leaves
yields the other. `curve14a4_points` follows by the birational map plus solving
the quadratic in `y` at each of `x ∈ {−1, 0, 1}`; `curve14a4_finite` follows by
exhibiting the point set as a subset of a five-element set; and
`curve14a4_isTorsion` is then just "a finite group is torsion". All three are
now PROVEN below, and `mordellWeil` is no longer needed at `14a4` at all.

HOW TO ATTACK IT — the shape is exactly `MazurLevel15.rank_zero_x` in
`Fermat/FLT/FreyCurve/MazurTorsion.lean`, whose whole elementary-descent chain
(`sq_or_two_sq`, `quartic_*`, `concordant_*`) is the template. Reconnaissance
carried out 2026-07-26 and recorded here so it need not be redone:

* Write `T = p/q` in lowest terms. `q` is coprime to `p(p² − 11pq + 32q²)`, so
  `q = e²`; then `gcd(p, p² − 11pe² + 32e⁴) = gcd(p, 32e⁴)` divides `32`, so
  `p = dS²` with `d ∈ {1, −1, 2, −2}` squarefree.
* `d < 0` dies by POSITIVITY, with no congruence needed: the quadratic
  `T² − 11T + 32` has discriminant `121 − 128 = −7 < 0`, hence is positive
  everywhere, so `W² = T(T² − 11T + 32) ≥ 0` forces `T ≥ 0`.
* `d = 1` gives the quartic `c² = S⁴ − 11S²e² + 32e⁴` (whose only coprime
  solution up to `300` is `(S, e) = (2, 1)`, i.e. `T = 4`), and `d = 2` gives
  `c² = 2S⁴ − 11S²e² + 16e⁴` (only `(0, 1)` and `(2, 1)`, i.e. `T = 0` and
  `T = 8`) — PARI 2026-07-26, untrusted searcher.
* Neither quartic is congruence-obstructed — each HAS a rational point — so
  they must be SOLVED, not excluded, and a genuine SECOND descent is needed,
  exactly as at level `15`. Completing the square turns them into
  `4c² = N² + 7e⁴` with `N = 2S² − 11e²` and `8c² = M² + 7e⁴` with
  `M = 4S² − 11e²`, i.e. into the `2`-isogenous curve `Y² = X³ + 22X² − 7X`
  (`b′ = a² − 4b = 121 − 128 = −7`).

THE SECOND DESCENT, mapped out 2026-07-26. Factor `A² − N² = 7e⁴` as
`(A − N)(A + N) = 7e⁴` with `A = 2c`. The gcd of the two factors divides `7`,
and `7` itself is impossible (it forces `7 ∣ S` and `7 ∣ e`), so the factors are
coprime; writing `e = mn` the coprime split into fourth powers gives exactly two
branches, and the even-`e` case of quartic A and both cases of quartic B run
into the SAME two branches after dividing out powers of `2`:

* **Branch (i)** yields `X² = −m⁴ + 22m²n² + 7n⁴` — the `d′ = −1` homogeneous
  space of the isogenous curve. **This branch is DEAD by a pure congruence**,
  and it is the one genuinely new ingredient: for coprime `m`, `n`, split on
  parity — `m`, `n` both odd gives `X² ≡ 12 (mod 16)`, impossible; `m` odd,
  `n` even gives `X² ≡ 3 (mod 4)`, impossible; `m` even, `n` odd gives
  `X² ≡ 7 (mod 8)`, impossible. (No coprime solution with `|m|, |n| ≤ 400`,
  PARI 2026-07-26 — consistent, as it must be.)
* **Branch (ii)** yields `X² = n⁴ + 22m²n² − 7m⁴`, whose ONLY coprime solutions
  up to `400` are `(m, n) = (0, 1)` and `(1, 1)` (PARI 2026-07-26) — i.e. it
  must be shown that `m = 0 ∨ m² = n²`. This is the surviving hard branch and it
  is where the infinite descent lives: completing the square gives
  `(n² + 11m²)² − X² = 128m⁴`, and stripping the powers of `2` leads to
  `n² = 8a⁴ − 11a²b² + 4b⁴` with `ab = m`, a strictly smaller instance. That is
  precisely the shape of `MazurLevel15.concordant_aux`, whose well-founded
  recursion on `x² + y²` is the template to copy.

So the remaining work is: the level-`15` integral bookkeeping transported
(`sq_or_two_sq` with `32` in place of `16`, and `split_gcd`), the mod-`16`
congruence above, and ONE well-founded descent on branch (ii). Note those
helpers currently live in `Fermat/FLT/FreyCurve/MazurTorsion.lean`, which is
DOWNSTREAM of this file, so they have to be restated here (or hoisted) rather
than imported. -/
theorem curve14a4_rational_T (T W : ℚ) (h : W ^ 2 = T ^ 3 - 11 * T ^ 2 + 32 * T) :
    T = 0 ∨ T = 4 ∨ T = 8 :=
  sorry

/-- **The five affine rational points of `14a4`, UNCONDITIONALLY** (PROVEN
2026-07-26 over `curve14a4_rational_T`): the affine rational points of
`y² + xy + y = x³ − x` are exactly `(1,−2)`, `(0,−1)`, `(−1,0)`, `(0,0)`,
`(1,0)`. Together with the point at infinity these are the six elements of
`14a4(ℚ) ≅ ℤ/6`.

This is the hypothesis-free form, and it is what `curve14a4_finite` consumes —
`curve14a4_points` below is the same statement with the (now unused) finiteness
hypothesis its consumer supplies positionally. Splitting the two is what breaks
the circle: finiteness is DERIVED from this enumeration rather than assumed for
it.

THE PROOF. `Nonsingular` gives `Equation`, i.e. `y² + xy + y = x³ − x`; the
scaled coordinates `T = 4x + 4`, `W = 8y + 4x + 4` satisfy
`W² = T³ − 11T² + 32T` (the identity is `64 ×` the curve equation), so
`curve14a4_rational_T` pins `x ∈ {−1, 0, 1}`. At each the equation becomes a
quadratic in `y` that factors over `ℚ`: `y² = 0`, `y(y + 1) = 0`,
`y(y + 2) = 0`. Note the `x`-coordinates take only THREE values, and that is
the form in which the consumer uses this lemma.

All six points are CUSPS of `X_1(14)` (`φ(14)/2 = 3` rational cusps, plus the
three conjugate ones that happen to be rational on this model). That is the
input to `x1_fourteen_no_rational_point`, whose proof exhibits the birational
map from the plane sextic and checks that each of the three `x`-values pulls
back to `d ∈ {0, 1}` — the two excluded degenerate loci. -/
theorem curve14a4_affine_points (x y : ℚ)
    (h : curve14a4.toAffine.Nonsingular x y) :
    (x, y) = ((1 : ℚ), (-2 : ℚ)) ∨ (x, y) = ((0 : ℚ), (-1 : ℚ)) ∨
      (x, y) = ((-1 : ℚ), (0 : ℚ)) ∨ (x, y) = ((0 : ℚ), (0 : ℚ)) ∨
      (x, y) = ((1 : ℚ), (0 : ℚ)) := by
  have heq : curve14a4.toAffine.Equation x y := h.1
  rw [WeierstrassCurve.Affine.equation_iff] at heq
  simp only [curve14a4] at heq
  have key : (8 * y + 4 * x + 4) ^ 2
      = (4 * x + 4) ^ 3 - 11 * (4 * x + 4) ^ 2 + 32 * (4 * x + 4) := by
    linear_combination 64 * heq
  rcases curve14a4_rational_T _ _ key with hT | hT | hT
  · have hx : x = -1 := by linarith
    subst hx
    have hy : y ^ 2 = 0 := by linarith [heq]
    have hy0 : y = 0 := pow_eq_zero_iff (n := 2) (a := y) (by norm_num) |>.mp hy
    subst hy0; simp
  · have hx : x = 0 := by linarith
    subst hx
    have hy : y * (y + 1) = 0 := by linarith [heq]
    rcases mul_eq_zero.mp hy with h0 | h0
    · subst h0; simp
    · have hy1 : y = -1 := by linarith
      subst hy1; simp
  · have hx : x = 1 := by linarith
    subst hx
    have hy : y * (y + 2) = 0 := by linarith [heq]
    rcases mul_eq_zero.mp hy with h0 | h0
    · subst h0; simp
    · have hy2 : y = -2 := by linarith
      subst hy2; simp

/-- **The five affine rational points of `14a4`** (PROVEN 2026-07-26 over
`curve14a4_rational_T`; was a sorry leaf) — the form the consumer calls, with
the finiteness hypothesis it supplies.

**The finiteness hypothesis is now UNUSED** (hence `_hfin`), and that is a
strengthening rather than a gap: the enumeration is no longer conditional on a
Mordell–Weil input. It is kept in the signature only because
`x1_fourteen_no_rational_point` in `Fermat/FLT/FreyCurve/TateNormalForm.lean`
passes `curve14a4_finite` positionally. All content is in
`curve14a4_affine_points`. -/
theorem curve14a4_points (_hfin : Finite curve14a4.toAffine.Point) (x y : ℚ)
    (h : curve14a4.toAffine.Nonsingular x y) :
    (x, y) = ((1 : ℚ), (-2 : ℚ)) ∨ (x, y) = ((0 : ℚ), (-1 : ℚ)) ∨
      (x, y) = ((-1 : ℚ), (0 : ℚ)) ∨ (x, y) = ((0 : ℚ), (0 : ℚ)) ∨
      (x, y) = ((1 : ℚ), (0 : ℚ)) :=
  curve14a4_affine_points x y h

/-- **`14a4(ℚ)` is finite** (PROVEN 2026-07-26 over `curve14a4_affine_points`, hence
over `curve14a4_rational_T` alone).

This USED to be the descent conclusion "finitely generated (Mordell–Weil) plus
torsion (rank `0`) gives finite", and it no longer is: with the five affine
points enumerated outright, finiteness is immediate from mathlib's
`nonsingularPointEquiv`, which identifies `E(ℚ)` with `WithZero` of the set of
nonsingular affine pairs. **So `mordellWeil` is NOT consumed at `14a4`** —
contrary to what this file's earlier docstrings claimed, it is not load-bearing
here. It remains load-bearing at `11a3`, where the enumeration is still a leaf.
-/
theorem curve14a4_finite : Finite curve14a4.toAffine.Point := by
  have hsub : {xy : ℚ × ℚ | curve14a4.toAffine.Nonsingular xy.1 xy.2} ⊆
      ({((1 : ℚ), (-2 : ℚ)), (0, -1), (-1, 0), (0, 0), (1, 0)} : Set (ℚ × ℚ)) := by
    rintro ⟨x, y⟩ hxy
    have hx := curve14a4_affine_points x y hxy
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff]
    tauto
  have hfin : {xy : ℚ × ℚ | curve14a4.toAffine.Nonsingular xy.1 xy.2}.Finite :=
    Set.Finite.subset (Set.toFinite _) hsub
  haveI : Finite {xy : ℚ × ℚ // curve14a4.toAffine.Nonsingular xy.1 xy.2} := hfin
  haveI : Finite (WithZero {xy : ℚ × ℚ // curve14a4.toAffine.Nonsingular xy.1 xy.2}) :=
    inferInstanceAs (Finite (Option _))
  exact Finite.of_equiv _ curve14a4.toAffine.nonsingularPointEquiv.symm

/-- **Rank `0` for `14a4`** (PROVEN 2026-07-26 over `curve14a4_finite`; was a
sorry leaf), in the concrete form that carries the content: every rational
point of `y² + xy + y = x³ − x` is a torsion point.

Classically this is a descent by the rational `2`-isogeny that `14a4` admits;
here it is a corollary of the full enumeration instead, since a finite group is
a torsion group. `RankBound(E) = 0` with proof flag `true` (Magma 2026-07-26,
untrusted searcher). Kubert, "Universal bounds on the torsion of elliptic
curves" (Proc. LMS 33, 1976); Ligozat; subsumed in Mazur 1977, Thm 8.

Stated as `AddMonoid.IsTorsion` rather than as `rank = 0` for the same reason
as `curve11a3_isTorsion`: there is no rank function here to state the latter
against. -/
theorem curve14a4_isTorsion : AddMonoid.IsTorsion curve14a4.toAffine.Point :=
  haveI := curve14a4_finite
  fun g => isOfFinAddOrder_of_finite g

end WeierstrassCurve
