/-
TorsionCounting.lean — own work for the Fermat project (not vendored from the
FLT project).

The goal of this file is the pure group-theory counting lemma needed by
`group_theory_lemma` in `Fermat/FLT/EllipticCurve/Torsion.lean`:

  If `A` is an abelian group, `n > 0`, and for every divisor `d` of `n` the
  `d`-torsion of `A` has exactly `d ^ r` elements, then the `n`-torsion of
  `A` is isomorphic to `(ZMod n) ^ r`.

Proof strategy (structure theorem + counting):
1. The `n`-torsion `T` is finite (its cardinality is `n ^ r > 0`).
2. By the structure theorem for finite abelian groups,
   `T ≃+ ⨁ i, ZMod (p i ^ e i)` with `p i` prime.
3. The `d`-torsion of `ZMod m` has exactly `gcd d m` elements, so the
   counting hypothesis pins down the multiset of prime powers: after
   discarding trivial factors, for each prime `q ∣ n` there are exactly `r`
   indices with `p i = q`, and each such exponent is `n.factorization q`.
4. Reassembling with the Chinese remainder theorem (`ZMod.equivPi`) yields
   `T ≃+ (Fin r → ZMod n)`.
-/
module

public import Mathlib.GroupTheory.FiniteAbelian.Basic
public import Mathlib.Data.ZMod.QuotientRing
public import Mathlib.Algebra.Module.Torsion.Basic
public import Mathlib.GroupTheory.Coset.Card
public import Mathlib.GroupTheory.QuotientGroup.Basic
public import Mathlib.LinearAlgebra.Pi
public import Mathlib.SetTheory.Cardinal.Finite
public import Mathlib.Data.Nat.Factorization.Basic

@[expose] public section

namespace TorsionCounting

open Submodule

variable {A : Type*} [AddCommGroup A] {B : Type*} [AddCommGroup B]

/-- Transport `torsionBy` along an additive equivalence. -/
def torsionByCongr (z : ℤ) (e : A ≃+ B) :
    torsionBy ℤ A z ≃+ torsionBy ℤ B z where
  toFun x := ⟨e x.1, show z • (e x.1) = 0 by
    rw [← map_zsmul, show z • (x.1 : A) = 0 from x.2, map_zero]⟩
  invFun y := ⟨e.symm y.1, show z • (e.symm y.1) = 0 by
    rw [← map_zsmul, show z • (y.1 : B) = 0 from y.2, map_zero]⟩
  left_inv x := Subtype.ext (e.symm_apply_apply x.1)
  right_inv y := Subtype.ext (e.apply_symm_apply y.1)
  map_add' x y := Subtype.ext (map_add e x.1 y.1)

/-- For `d ∣ n`, the `d`-torsion of `A` is the `d`-torsion of the
`n`-torsion of `A`. -/
def torsionByDvd {d n : ℤ} (hdn : d ∣ n) :
    torsionBy ℤ A d ≃+ torsionBy ℤ (torsionBy ℤ A n) d where
  toFun x := ⟨⟨x.1, show n • (x.1 : A) = 0 by
      obtain ⟨c, rfl⟩ := hdn
      rw [mul_comm, mul_smul, show d • (x.1 : A) = 0 from x.2, smul_zero]⟩,
    by
      apply Subtype.ext
      exact x.2⟩
  invFun y := ⟨y.1.1, show d • (y.1.1 : A) = 0 from
    congrArg Subtype.val (show d • y.1 = (0 : torsionBy ℤ A n) from y.2)⟩
  left_inv x := Subtype.ext rfl
  right_inv y := Subtype.ext (Subtype.ext rfl)
  map_add' x y := Subtype.ext (Subtype.ext rfl)

/-- The `z`-torsion of a product is the product of the `z`-torsions. -/
def torsionByPi {ι : Type*} (M : ι → Type*) [∀ i, AddCommGroup (M i)] (z : ℤ) :
    torsionBy ℤ (∀ i, M i) z ≃+ ∀ i, torsionBy ℤ (M i) z where
  toFun x i := ⟨x.1 i, show z • (x.1 i) = 0 from
    congrFun (show z • x.1 = 0 from x.2) i⟩
  invFun f := ⟨fun i => (f i).1, show z • (fun i => ((f i).1 : M i)) = 0 by
    exact funext fun i => (f i).2⟩
  left_inv x := Subtype.ext rfl
  right_inv f := funext fun i => Subtype.ext rfl
  map_add' x y := rfl

/-- An additive endomorphism restricts to the `z`-torsion submodule. -/
def endRestrict (f : A →+ A) (z : ℤ) :
    torsionBy ℤ A z →+ torsionBy ℤ A z where
  toFun x := ⟨f x.1, show z • f x.1 = 0 by
    rw [← map_zsmul, show z • (x.1 : A) = 0 from x.2, map_zero]⟩
  map_zero' := Subtype.ext (map_zero f)
  map_add' x y := Subtype.ext (map_add f x.1 y.1)

@[simp] lemma endRestrict_apply (f : A →+ A) (z : ℤ) (x : torsionBy ℤ A z) :
    (endRestrict f z x : A) = f x.1 := rfl

/-- Drop the factors of a product that are trivial: if `M i` is a
subsingleton whenever `¬ P i`, the product over all of `ι` is the product
over the subtype `{j // P j}`. -/
def piSubsingleton {ι : Type*} (M : ι → Type*) [∀ i, AddCommGroup (M i)]
    (P : ι → Prop) [DecidablePred P] (hM : ∀ i, ¬ P i → Subsingleton (M i)) :
    (∀ i, M i) ≃+ ∀ j : { j // P j }, M j.1 where
  toFun f j := f j.1
  invFun f i := if h : P i then f ⟨i, h⟩ else 0
  left_inv f := funext fun i => by
    by_cases h : P i
    · simp [h]
    · haveI := hM i h
      exact Subsingleton.elim _ _
  right_inv f := funext fun j => by simp [j.2]
  map_add' f g := rfl

/-- `Equiv.piComm` as an additive equivalence. -/
def piCommAddEquiv {ι κ : Type*} (M : ι → κ → Type*)
    [∀ i j, AddCommGroup (M i j)] :
    (∀ i j, M i j) ≃+ ∀ j i, M i j :=
  { Equiv.piComm M with map_add' := fun _ _ => rfl }

/-- The `d`-torsion of `ZMod m` (for `m ≠ 0`) has exactly `gcd d m`
elements: it is the kernel of multiplication by `d`, whose image is the
cyclic subgroup generated by `(d : ZMod m)`, of order `m / gcd m d`. -/
theorem card_torsionBy_zmod (d m : ℕ) (hm : m ≠ 0) :
    Nat.card (torsionBy ℤ (ZMod m) (d : ℤ)) = Nat.gcd d m := by
  haveI : NeZero m := ⟨hm⟩
  set f : ZMod m →+ ZMod m := AddMonoidHom.mulLeft (d : ZMod m) with hf
  -- the torsion submodule is the kernel of `f`
  have hmem : ∀ x : ZMod m, (d : ℤ) • x = 0 ↔ f x = 0 := by
    intro x
    rw [natCast_zsmul, nsmul_eq_mul, hf]
    rfl
  have e1 : (torsionBy ℤ (ZMod m) (d : ℤ)) ≃ f.ker :=
    Equiv.subtypeEquivRight fun x => hmem x
  -- the range of `f` is the cyclic subgroup generated by `(d : ZMod m)`
  have hrange : f.range = AddSubgroup.zmultiples ((d : ℕ) : ZMod m) := by
    ext y
    simp only [AddMonoidHom.mem_range, AddSubgroup.mem_zmultiples_iff]
    constructor
    · rintro ⟨x, rfl⟩
      obtain ⟨k, rfl⟩ := ZMod.intCast_surjective (n := m) x
      exact ⟨k, by simp [hf, zsmul_eq_mul, mul_comm]⟩
    · rintro ⟨k, rfl⟩
      exact ⟨(k : ZMod m), by simp [hf, zsmul_eq_mul, mul_comm]⟩
  -- counting
  have hcard : Nat.card (ZMod m) = Nat.card (ZMod m ⧸ f.ker) * Nat.card f.ker :=
    AddSubgroup.card_eq_card_quotient_mul_card_addSubgroup f.ker
  have hquot : Nat.card (ZMod m ⧸ f.ker) = Nat.card f.range :=
    Nat.card_congr (QuotientAddGroup.quotientKerEquivRange f).toEquiv
  have hrangecard : Nat.card f.range = m / Nat.gcd m d := by
    rw [hrange, Nat.card_zmultiples, ZMod.addOrderOf_coe d hm]
  have hzmod : Nat.card (ZMod m) = m := Nat.card_zmod m
  have hg : Nat.gcd m d ∣ m := Nat.gcd_dvd_left m d
  have hgpos : 0 < Nat.gcd m d := Nat.gcd_pos_of_pos_left d (Nat.pos_of_ne_zero hm)
  have hqpos : 0 < m / Nat.gcd m d := Nat.div_pos (Nat.le_of_dvd (Nat.pos_of_ne_zero hm) hg) hgpos
  -- `m = (m / gcd m d) * card(ker)` forces `card(ker) = gcd m d`
  have key : m / Nat.gcd m d * Nat.card f.ker = m := by
    rw [← hrangecard, ← hquot]
    exact (hcard.symm.trans hzmod)
  have : m / Nat.gcd m d * Nat.card f.ker = m / Nat.gcd m d * Nat.gcd m d := by
    rw [Nat.div_mul_cancel hg]
    exact key
  have hker : Nat.card f.ker = Nat.gcd m d := Nat.eq_of_mul_eq_mul_left hqpos this
  rw [Nat.card_congr e1, hker, Nat.gcd_comm]

/-- The `d`-torsion of a finite product of `ZMod (m i)`s (all `m i ≠ 0`)
has `∏ i, gcd d (m i)` elements. -/
theorem card_torsionBy_pi_zmod {ι : Type*} [Fintype ι] (mfam : ι → ℕ)
    (hmfam : ∀ i, mfam i ≠ 0) (d : ℕ) :
    Nat.card (torsionBy ℤ (∀ i, ZMod (mfam i)) (d : ℤ)) = ∏ i, Nat.gcd d (mfam i) := by
  rw [Nat.card_congr (torsionByPi (fun i => ZMod (mfam i)) (d : ℤ)).toEquiv, Nat.card_pi]
  exact Finset.prod_congr rfl fun i _ => card_torsionBy_zmod d (mfam i) (hmfam i)

/-- **The counting lemma.** If `A` is an abelian group, `n > 0`, and for every
divisor `d` of `n` the `d`-torsion of `A` has exactly `d ^ r` elements, then
the `n`-torsion of `A` is isomorphic to `(ZMod n) ^ r`. -/
theorem nonempty_torsionBy_addEquiv_pi_zmod {A : Type*} [AddCommGroup A] {n : ℕ}
    (hn : 0 < n) (r : ℕ)
    (h : ∀ d : ℕ, d ∣ n → Nat.card (torsionBy ℤ A d) = d ^ r) :
    Nonempty (torsionBy ℤ A n ≃+ (Fin r → ZMod n)) := by
  classical
  set T := torsionBy ℤ A (n : ℤ) with hT
  -- Step 1: `T` is finite.
  have hTcard : Nat.card T = n ^ r := h n dvd_rfl
  have hTfin : Finite T := Nat.finite_of_card_ne_zero (by
    rw [hTcard]; exact pow_ne_zero r hn.ne')
  -- Step 2: structure theorem for finite abelian groups.
  obtain ⟨ι, fι, p, hp, e, ⟨σ0⟩⟩ := AddCommGroup.equiv_directSum_zmod_of_finite T
  haveI := fι
  let σ : T ≃+ ∀ i, ZMod (p i ^ e i) :=
    σ0.trans (DirectSum.addEquivProd fun i => ZMod (p i ^ e i))
  -- Step 3: transfer the counting hypothesis through `σ`.
  have hcount : ∀ d : ℕ, d ∣ n → ∏ i, Nat.gcd d (p i ^ e i) = d ^ r := by
    intro d hd
    have hdz : (d : ℤ) ∣ (n : ℤ) := Int.natCast_dvd_natCast.mpr hd
    calc ∏ i, Nat.gcd d (p i ^ e i)
        = Nat.card (torsionBy ℤ (∀ i, ZMod (p i ^ e i)) (d : ℤ)) :=
          (card_torsionBy_pi_zmod _ (fun i => pow_ne_zero _ (hp i).pos.ne') d).symm
      _ = Nat.card (torsionBy ℤ T (d : ℤ)) :=
          (Nat.card_congr (torsionByCongr (d : ℤ) σ).toEquiv).symm
      _ = Nat.card (torsionBy ℤ A (d : ℤ)) :=
          (Nat.card_congr (torsionByDvd hdz).toEquiv).symm
      _ = d ^ r := h d hd
  -- Step 4: every cyclic factor is killed by `n`, i.e. `p i ^ e i ∣ n`.
  have hdvd : ∀ i, p i ^ e i ∣ n := by
    intro i
    have hkill : (n : ℤ) • (fun _ => 1 : ∀ i, ZMod (p i ^ e i)) = 0 := by
      have h0 : (n : ℤ) • (σ.symm (fun _ => 1)) = 0 := by
        apply Subtype.ext
        exact (σ.symm (fun _ => 1)).2
      calc (n : ℤ) • (fun _ => 1 : ∀ i, ZMod (p i ^ e i))
          = (n : ℤ) • (σ (σ.symm (fun _ => 1))) := by rw [σ.apply_symm_apply]
        _ = σ ((n : ℤ) • (σ.symm (fun _ => 1))) := (map_zsmul σ _ _).symm
        _ = σ 0 := by rw [h0]
        _ = 0 := map_zero σ
    have h2 : (n : ℤ) • (1 : ZMod (p i ^ e i)) = 0 := congrFun hkill i
    rw [zsmul_eq_mul, mul_one] at h2
    have h3 : ((n : ℕ) : ZMod (p i ^ e i)) = 0 := by exact_mod_cast h2
    exact (CharP.cast_eq_zero_iff (ZMod (p i ^ e i)) (p i ^ e i) n).mp h3
  -- Step 5: exponent bound from Step 4.
  have hle : ∀ i, e i ≤ n.factorization (p i) := fun i =>
    ((hp i).pow_dvd_iff_le_factorization hn.ne').mp (hdvd i)
  -- Step 6: for each prime `q ∣ n`, exactly `r` nontrivial factors have `p i = q`.
  have hfiber : ∀ q : ℕ, q.Prime → q ∣ n →
      (Finset.univ.filter fun i => p i = q ∧ e i ≠ 0).card = r := by
    intro q hq hqn
    have hcnt := hcount q hqn
    have hfac : ∀ i, Nat.gcd q (p i ^ e i) = if p i = q ∧ e i ≠ 0 then q else 1 := by
      intro i
      by_cases h1 : p i = q ∧ e i ≠ 0
      · obtain ⟨hpq, he⟩ := h1
        rw [if_pos ⟨hpq, he⟩, hpq]
        exact Nat.gcd_eq_left (dvd_pow_self q he)
      · rw [if_neg h1]
        push Not at h1
        by_cases hpq : p i = q
        · rw [h1 hpq, pow_zero, Nat.gcd_one_right]
        · exact Nat.Coprime.pow_right _
            ((Nat.coprime_primes hq (hp i)).mpr fun hh => hpq hh.symm)
    rw [Finset.prod_congr rfl (fun i _ => hfac i), Finset.prod_ite,
      Finset.prod_const, Finset.prod_const_one, mul_one] at hcnt
    exact Nat.pow_right_injective hq.two_le hcnt
  -- Step 7: the total product of the factors is `n ^ r`.
  have htotal : ∏ i, p i ^ e i = n ^ r := by
    have hcnt := hcount n dvd_rfl
    rwa [Finset.prod_congr rfl (fun i _ => Nat.gcd_eq_right (hdvd i))] at hcnt
  -- Step 8: every nontrivial exponent is forced to be `n.factorization (p i)`.
  have hexp : ∀ i, e i ≠ 0 → e i = n.factorization (p i) := by
    intro i0 hei0
    have hqprime : (p i0).Prime := hp i0
    have hqdvd : p i0 ∣ n := dvd_trans (dvd_pow_self _ hei0) (hdvd i0)
    set S := Finset.univ.filter (fun i => p i = p i0 ∧ e i ≠ 0) with hS
    have hScard : S.card = r := hfiber (p i0) hqprime hqdvd
    -- the sum of the exponents over the fiber is `r * v`
    have hsum : ∑ i ∈ S, e i = r * n.factorization (p i0) := by
      have hfact := congrArg (fun m => m.factorization (p i0)) htotal
      rw [Nat.factorization_prod (fun i _ => pow_ne_zero _ (hp i).pos.ne'),
        Finset.sum_apply'] at hfact
      have hterm : ∀ i, ((p i ^ e i).factorization) (p i0) =
          if p i = p i0 then e i else 0 := by
        intro i
        rw [(hp i).factorization_pow]
        exact Finsupp.single_apply
      rw [Finset.sum_congr rfl (fun i _ => hterm i), ← Finset.sum_filter,
        Nat.factorization_pow, Finsupp.smul_apply, smul_eq_mul] at hfact
      have hsub : S ⊆ Finset.univ.filter (fun i => p i = p i0) := by
        intro i hi
        rw [hS, Finset.mem_filter] at hi
        exact Finset.mem_filter.mpr ⟨hi.1, hi.2.1⟩
      have hzero : ∀ i ∈ Finset.univ.filter (fun i => p i = p i0), i ∉ S → e i = 0 := by
        intro i hi hnotin
        by_contra hne
        exact hnotin (Finset.mem_filter.mpr
          ⟨Finset.mem_univ i, (Finset.mem_filter.mp hi).2, hne⟩)
      rw [← Finset.sum_subset hsub hzero] at hfact
      exact hfact
    have hle' : ∀ i ∈ S, e i ≤ n.factorization (p i0) := by
      intro i hi
      have hh := hle i
      rwa [(Finset.mem_filter.mp hi).2.1] at hh
    have hin : i0 ∈ S := Finset.mem_filter.mpr ⟨Finset.mem_univ _, rfl, hei0⟩
    by_contra hne
    have hlt : e i0 < n.factorization (p i0) := lt_of_le_of_ne (hle' i0 hin) hne
    have hcontra : ∑ i ∈ S, e i < ∑ i ∈ S, n.factorization (p i0) :=
      Finset.sum_lt_sum (fun i hi => hle' i hi) ⟨i0, hin, hlt⟩
    rw [hsum, Finset.sum_const, smul_eq_mul, hScard] at hcontra
    exact lt_irrefl _ hcontra
  -- Step 9: assemble the isomorphism.
  -- Discard the trivial factors.
  let ι' := { j : ι // e j ≠ 0 }
  let σ2 : T ≃+ ∀ j : ι', ZMod (p j.1 ^ e j.1) :=
    σ.trans (piSubsingleton (fun i => ZMod (p i ^ e i)) (fun i => e i ≠ 0)
      (fun i hi => by
        rw [not_not] at hi
        rw [hi, pow_zero]
        infer_instance))
  -- The map sending a nontrivial factor to its prime, seen in `n.primeFactors`.
  let Pmap : ι' → n.primeFactors := fun j =>
    ⟨p j.1, Nat.mem_primeFactors.mpr
      ⟨hp j.1, dvd_trans (dvd_pow_self _ j.2) (hdvd j.1), hn.ne'⟩⟩
  -- Each fiber of `Pmap` has exactly `r` elements.
  have hfibercard : ∀ q : n.primeFactors, Fintype.card { j : ι' // Pmap j = q } = r := by
    intro q
    obtain ⟨hqp, hqd, -⟩ := Nat.mem_primeFactors.mp q.2
    have hcongr : ∀ j : ι', (Pmap j = q) = (p j.1 = (q : ℕ)) := by
      intro j
      simp only [Pmap, Subtype.ext_iff]
    calc Fintype.card { j : ι' // Pmap j = q }
        = Fintype.card { j : ι' // p j.1 = (q : ℕ) } := Fintype.card_congr
          (Equiv.subtypeEquivRight fun j => by rw [hcongr j])
      _ = Fintype.card { i : ι // e i ≠ 0 ∧ p i = (q : ℕ) } := Fintype.card_congr
          (Equiv.subtypeSubtypeEquivSubtypeInter
            (fun i : ι => e i ≠ 0) (fun i : ι => p i = (q : ℕ)))
      _ = Fintype.card { i : ι // p i = (q : ℕ) ∧ e i ≠ 0 } := Fintype.card_congr
          (Equiv.subtypeEquivRight fun i => and_comm)
      _ = (Finset.univ.filter fun i => p i = (q : ℕ) ∧ e i ≠ 0).card :=
          Fintype.card_subtype _
      _ = r := hfiber (q : ℕ) hqp hqd
  -- Now chain the equivalences together.
  refine ⟨σ2.trans <| ?_⟩
  -- (a) fix up each factor: `ZMod (p j ^ e j) ≃+ ZMod (q ^ v_q(n))` for `q = Pmap j`
  have step_a : (∀ j : ι', ZMod (p j.1 ^ e j.1)) ≃+
      ∀ j : ι', ZMod ((Pmap j : ℕ) ^ n.factorization (Pmap j : ℕ)) :=
    AddEquiv.piCongrRight fun j =>
      (ZMod.ringEquivCongr (congrArg (p j.1 ^ ·) (hexp j.1 j.2))).toAddEquiv
  -- (b) regroup along the fibers of `Pmap`
  have step_b : (∀ j : ι', ZMod ((Pmap j : ℕ) ^ n.factorization (Pmap j : ℕ))) ≃+
      ∀ x : Σ q : n.primeFactors, { j : ι' // Pmap j = q },
        ZMod ((Pmap ((Equiv.sigmaFiberEquiv Pmap) x) : ℕ)
          ^ n.factorization (Pmap ((Equiv.sigmaFiberEquiv Pmap) x) : ℕ)) :=
    (LinearEquiv.piCongrLeft ℤ
      (fun j : ι' => ZMod ((Pmap j : ℕ) ^ n.factorization (Pmap j : ℕ)))
      (Equiv.sigmaFiberEquiv Pmap)).symm.toAddEquiv
  -- (c) inside each fiber the modulus only depends on the base point
  have step_c : (∀ x : Σ q : n.primeFactors, { j : ι' // Pmap j = q },
        ZMod ((Pmap ((Equiv.sigmaFiberEquiv Pmap) x) : ℕ)
          ^ n.factorization (Pmap ((Equiv.sigmaFiberEquiv Pmap) x) : ℕ))) ≃+
      ∀ x : Σ q : n.primeFactors, { j : ι' // Pmap j = q },
        ZMod ((x.1 : ℕ) ^ n.factorization (x.1 : ℕ)) :=
    AddEquiv.piCongrRight fun x =>
      (ZMod.ringEquivCongr (congrArg
        (fun q : n.primeFactors => (q : ℕ) ^ n.factorization (q : ℕ))
        x.2.2)).toAddEquiv
  -- (d) curry the sigma type
  have step_d : (∀ x : Σ q : n.primeFactors, { j : ι' // Pmap j = q },
        ZMod ((x.1 : ℕ) ^ n.factorization (x.1 : ℕ))) ≃+
      ∀ q : n.primeFactors, ∀ _ : { j : ι' // Pmap j = q },
        ZMod ((q : ℕ) ^ n.factorization (q : ℕ)) :=
    (LinearEquiv.piCurry ℤ
      (fun (q : n.primeFactors) (_ : { j : ι' // Pmap j = q }) =>
        ZMod ((q : ℕ) ^ n.factorization (q : ℕ)))).toAddEquiv
  -- (e) each fiber is a `Fin r`
  have step_e : (∀ q : n.primeFactors, ∀ _ : { j : ι' // Pmap j = q },
        ZMod ((q : ℕ) ^ n.factorization (q : ℕ))) ≃+
      ∀ q : n.primeFactors, ∀ _ : Fin r, ZMod ((q : ℕ) ^ n.factorization (q : ℕ)) :=
    AddEquiv.piCongrRight fun q =>
      (LinearEquiv.funCongrLeft ℤ (ZMod ((q : ℕ) ^ n.factorization (q : ℕ)))
        (Fintype.equivFinOfCardEq (hfibercard q)).symm).toAddEquiv
  -- (f) swap the two indices
  have step_f : (∀ q : n.primeFactors, ∀ _ : Fin r,
        ZMod ((q : ℕ) ^ n.factorization (q : ℕ))) ≃+
      ∀ _ : Fin r, ∀ q : n.primeFactors, ZMod ((q : ℕ) ^ n.factorization (q : ℕ)) :=
    piCommAddEquiv fun (q : n.primeFactors) (_ : Fin r) =>
      ZMod ((q : ℕ) ^ n.factorization (q : ℕ))
  -- (g) reassemble each copy with the Chinese remainder theorem
  have step_g : (∀ _ : Fin r, ∀ q : n.primeFactors,
        ZMod ((q : ℕ) ^ n.factorization (q : ℕ))) ≃+ (Fin r → ZMod n) :=
    AddEquiv.piCongrRight fun _ => (ZMod.equivPi n hn.ne').symm.toAddEquiv
  exact step_a.trans <| step_b.trans <| step_c.trans <| step_d.trans <|
    step_e.trans <| step_f.trans step_g

end TorsionCounting
