/-
WronskianStep.lean — own work for the Fermat project.

The differentiated addition law: if `DK` has the invariant-derivation
values at a base point `(x₁, y₁)` (i.e. `DK x₁ = ψ₂(P₁)`,
`DK y₁ = −F_X(P₁)`) and the `m`-fold values at `(xₙ, yₙ)`, then at the
chord-sum of the two points it has the `(m+1)`-fold values. This is
the additivity of the invariant differential `ω = dx/ψ₂`, proven as a
polynomial certificate: the two goals, saturated by `(xₙ − x₁)⁴` resp.
`(xₙ − x₁)⁵`, lie in the ideal generated by the two curve equations,
the slope relation, and the cleared quotient rule for `DK ℓ` — with
cofactors extracted by explicit linear elimination (sympy,
`scripts/eds/` companion `step_cofactors3.py`).
-/
module

public import Fermat.FLT.EllipticCurve.InvariantDerivation

@[expose] public section

namespace PsiSumCompanion

open Polynomial WeierstrassCurve WeierstrassCurve.Affine

set_option backward.isDefEq.respectTransparency false in
set_option maxHeartbeats 4000000 in
/-- **The differentiated addition law** for the invariant derivation
`DK` on the universal function field. -/
theorem DK_addition_step
    (a1 a2 a3 a4 a6 x1 y1 xn yn m l x3 y3 : Kuniv)
    (hDa1 : DK a1 = 0) (hDa2 : DK a2 = 0) (hDa3 : DK a3 = 0)
    (hE1 : y1 ^ 2 + a1 * x1 * y1 + a3 * y1 =
      x1 ^ 3 + a2 * x1 ^ 2 + a4 * x1 + a6)
    (hEn : yn ^ 2 + a1 * xn * yn + a3 * yn =
      xn ^ 3 + a2 * xn ^ 2 + a4 * xn + a6)
    (hne : xn ≠ x1)
    (hl : l = (yn - y1) / (xn - x1))
    (hDx1 : DK x1 = 2 * y1 + a1 * x1 + a3)
    (hDy1 : DK y1 = -(a1 * y1 - (3 * x1 ^ 2 + 2 * a2 * x1 + a4)))
    (hDxn : DK xn = m * (2 * yn + a1 * xn + a3))
    (hDyn : DK yn = -(m * (a1 * yn - (3 * xn ^ 2 + 2 * a2 * xn + a4))))
    (hx3 : x3 = l ^ 2 + a1 * l - a2 - xn - x1)
    (hy3 : y3 = -(l * (x3 - xn) + yn) - a1 * x3 - a3) :
    DK x3 = (m + 1) * (2 * y3 + a1 * x3 + a3) ∧
    DK y3 = -((m + 1) * (a1 * y3 -
      (3 * x3 ^ 2 + 2 * a2 * x3 + a4))) := by
  have hd : xn - x1 ≠ 0 := sub_ne_zero.mpr hne
  have hneg : ∀ t : Kuniv, DK (-t) = -DK t := fun t => by
    have h := DK_sub 0 t
    rwa [zero_sub, DK_zero, zero_sub] at h
  have hR3 : l * (xn - x1) = yn - y1 := by
    rw [hl]
    exact div_mul_cancel₀ _ hd
  have hR5 : DK l * (xn - x1) =
      (DK yn - DK y1) - l * (DK xn - DK x1) := by
    have h1 := congrArg DK hR3
    have h2 := DK_mul l (xn - x1)
    have h3 := DK_sub yn y1
    have h4 := DK_sub xn x1
    linear_combination h1 - h2 + h3 - l * h4
  rw [hDxn, hDx1, hDyn, hDy1] at hR5
  have hDx3 : DK x3 = 2 * l * DK l + a1 * DK l - DK xn - DK x1 := by
    rw [hx3]
    have e1 := DK_sub (l ^ 2 + a1 * l - a2 - xn) x1
    have e2 := DK_sub (l ^ 2 + a1 * l - a2) xn
    have e3 := DK_sub (l ^ 2 + a1 * l) a2
    have e4 := DK_add (l ^ 2) (a1 * l)
    have e5 := DK_sq l
    have e6 := DK_mul a1 l
    linear_combination e1 + e2 + e3 + e4 + e5 + e6 +
      l * hDa1 - hDa2
  have hDy3 : DK y3 = -(DK l * (x3 - xn) +
      l * (DK x3 - DK xn) + DK yn) - a1 * DK x3 := by
    rw [hy3]
    have e1 := DK_sub (-(l * (x3 - xn) + yn) - a1 * x3) a3
    have e2 := DK_sub (-(l * (x3 - xn) + yn)) (a1 * x3)
    have e3 := hneg (l * (x3 - xn) + yn)
    have e4 := DK_add (l * (x3 - xn)) yn
    have e5 := DK_mul l (x3 - xn)
    have e6 := DK_sub x3 xn
    have e7 := DK_mul a1 x3
    linear_combination e1 + e2 + e3 - e4 - l * e6 - e5 - e7 -
      x3 * hDa1 - hDa3
  rw [hDxn, hDx1] at hDx3
  rw [hDx3, hDxn, hDyn] at hDy3
  constructor
  · have key : (DK x3 - (m + 1) * (2 * y3 + a1 * x3 + a3)) *
        (xn - x1) ^ 4 = 0 := by
      rw [hDx3, hy3, hx3]
      linear_combination
        (-a1*x1^2 - a1*xn^2 - 2*x1*y1 - 2*xn*yn + 2*x1*yn + 2*xn*y1 + a1*m*x1^2 + a1*m*xn^2 - 2*m*x1*yn - 2*m*xn*y1 + 2*a1*x1*xn + 2*m*x1*y1 + 2*m*xn*yn - 2*a1*m*x1*xn) * hE1 +
        (a1*x1^2 + a1*xn^2 - 2*x1*yn - 2*xn*y1 + 2*x1*y1 + 2*xn*yn - a1*m*x1^2 - a1*m*xn^2 - 2*a1*x1*xn - 2*m*x1*y1 - 2*m*xn*yn + 2*m*x1*yn + 2*m*xn*y1 + 2*a1*m*x1*xn) * hEn +
        (-4*x1^4 - 4*xn^4 + a1^2*xn^3 - 12*x1^2*xn^2 - 2*a2*x1^3 - 2*a2*xn^3 - 2*a4*x1^2 - 2*a4*xn^2 - 2*x1*yn^2 - 2*xn*y1^2 - 2*l^2*x1^3 + 2*m*x1^4 + 2*m*xn^4 + 2*x1*y1^2 + 2*xn*yn^2 + 2*l^2*xn^3 + 10*x1*xn^3 + 10*xn*x1^3 + a1*a3*x1^2 + a1*a3*xn^2 + a1*y1*xn^2 + a1*yn*x1^2 + xn*a1^2*x1^2 - a1*l*x1^3 - m*a1^2*x1^3 - 6*x1*l^2*xn^2 - 2*a3*x1*yn - 2*a3*xn*y1 - 2*m*x1*xn^3 - 2*m*x1*y1^2 - 2*m*xn*x1^3 - 2*m*xn*yn^2 - 2*m*l^2*x1^3 - 2*x1*a1^2*xn^2 + 2*a2*m*x1^3 + 2*a2*m*xn^3 + 2*a2*x1*xn^2 + 2*a2*xn*x1^2 + 2*a3*l*x1^2 + 2*a3*l*xn^2 + 2*a3*x1*y1 + 2*a3*xn*yn + 2*a4*m*x1^2 + 2*a4*m*xn^2 + 2*l*y1*x1^2 + 2*l*y1*xn^2 + 2*l*yn*x1^2 + 2*l*yn*xn^2 + 2*m*x1*yn^2 + 2*m*xn*y1^2 + 2*m*l^2*xn^3 + 3*a1*l*xn^3 + 3*a1*y1*x1^2 + 3*a1*yn*xn^2 + 4*a4*x1*xn + 6*xn*l^2*x1^2 + a1*l*m*xn^3 - a1*a3*m*x1^2 - a1*a3*m*xn^2 - a1*m*y1*xn^2 - a1*m*yn*x1^2 - m*x1*a1^2*xn^2 - 7*a1*l*x1*xn^2 - 6*m*x1*l^2*xn^2 - 4*a1*x1*xn*y1 - 4*a1*x1*xn*yn - 4*a3*l*x1*xn - 4*a4*m*x1*xn - 4*l*x1*xn*y1 - 4*l*x1*xn*yn - 3*a1*l*m*x1^3 - 3*a1*m*y1*x1^2 - 3*a1*m*yn*xn^2 - 2*a1*a3*x1*xn - 2*a2*m*x1*xn^2 - 2*a2*m*xn*x1^2 - 2*a3*l*m*x1^2 - 2*a3*l*m*xn^2 - 2*a3*m*x1*y1 - 2*a3*m*xn*yn - 2*l*m*y1*x1^2 - 2*l*m*y1*xn^2 - 2*l*m*yn*x1^2 - 2*l*m*yn*xn^2 + 2*a3*m*x1*yn + 2*a3*m*xn*y1 + 2*m*xn*a1^2*x1^2 + 5*a1*l*xn*x1^2 + 6*m*xn*l^2*x1^2 - 5*a1*l*m*x1*xn^2 + 2*a1*a3*m*x1*xn + 4*a1*m*x1*xn*y1 + 4*a1*m*x1*xn*yn + 4*a3*l*m*x1*xn + 4*l*m*x1*xn*y1 + 4*l*m*x1*xn*yn + 7*a1*l*m*xn*x1^2) * hR3 +
        (a1*xn^3 - a1*x1^3 - 2*l*x1^3 + 2*l*xn^3 - 6*l*x1*xn^2 - 3*a1*x1*xn^2 + 3*a1*xn*x1^2 + 6*l*xn*x1^2) * hR5
    rcases mul_eq_zero.mp key with h0 | h0
    · linear_combination h0
    · exact absurd h0 (pow_ne_zero 4 hd)
  · have key : (DK y3 + (m + 1) * (a1 * y3 -
        (3 * x3 ^ 2 + 2 * a2 * x3 + a4))) * (xn - x1) ^ 5 = 0 := by
      rw [hDy3, hy3, hx3]
      linear_combination
        (-6*xn^4 + a2*x1^3 + a2*yn^2 + a6*a1^2 - a2*a6 - a1^2*x1^3 - a1^2*yn^2 - a2^2*xn^2 - 9*m*xn^4 - 9*x1^2*xn^2 - 5*a2*xn^3 - 3*a4*xn^2 - 3*a6*xn - 3*m*x1^4 - 3*x1*y1^2 - 3*x1*yn^2 + 2*a1^2*xn^3 + 3*xn*x1^3 + 3*xn*y1^2 + 6*xn*yn^2 + 9*x1*xn^3 + a2*a3*yn + a2*a1^2*xn^2 + a4*xn*a1^2 + m*a1^2*x1^3 + m*a1^2*yn^2 - a2*a4*xn - a2*m*x1^3 - a3*yn*a1^2 - a6*m*a1^2 - xn*yn*a1^3 - 10*a2*m*xn^3 - 9*a4*m*xn^2 - 9*a6*m*xn - 9*m*x1^2*xn^2 - 6*xn*y1*yn - 4*a1*y1*x1^2 - 4*a1*y1*xn^2 - 3*a2*xn*x1^2 - 3*m*xn*y1^2 - 3*x1*a1^2*xn^2 - 2*a2*a6*m - 2*m*a1^2*xn^3 - 2*m*a2^2*xn^2 + 2*a2*m*yn^2 + 3*a2*x1*xn^2 + 3*a3*xn*yn + 3*a6*m*x1 + 3*m*x1*y1^2 + 3*xn*a1^2*x1^2 + 4*a1*yn*x1^2 + 6*m*x1*xn^3 + 6*m*xn*yn^2 + 6*x1*y1*yn + 7*a1*yn*xn^2 + 9*m*xn*x1^3 + a1*a2*xn*yn + a3*m*yn*a1^2 + m*xn*yn*a1^3 - a2*m*a1^2*xn^2 - a4*m*xn*a1^2 - 8*a1*x1*xn*yn - 6*m*x1*y1*yn - 4*a1*m*yn*x1^2 - 3*a3*m*x1*yn - 3*m*xn*a1^2*x1^2 - 2*a2*a4*m*xn + 2*a2*a3*m*yn + 3*a2*m*xn*x1^2 + 3*a4*m*x1*xn + 3*m*x1*a1^2*xn^2 + 4*a1*m*y1*x1^2 + 4*a1*m*y1*xn^2 + 5*a1*m*yn*xn^2 + 6*m*xn*y1*yn + 8*a1*x1*xn*y1 + 9*a3*m*xn*yn - 8*a1*m*x1*xn*y1 + 2*a1*a2*m*xn*yn + 5*a1*m*x1*xn*yn) * hE1 +
        (3*xn^4 + a2*a6 + a2*xn^3 + a1^2*y1^2 + a2^2*x1^2 - a2*y1^2 - a6*a1^2 - a1^2*xn^3 - 9*x1*xn^3 - 6*xn*y1^2 - 3*xn*yn^2 + 3*a6*xn + 3*x1*y1^2 + 3*x1*yn^2 + 9*x1^2*xn^2 + a2*a4*x1 + a3*y1*a1^2 + a6*m*a1^2 + m*a1^2*xn^3 + x1*y1*a1^3 - a2*a3*y1 - a2*m*xn^3 - a2*a1^2*x1^2 - a4*x1*a1^2 - m*a1^2*y1^2 - 6*m*xn*y1^2 - 6*x1*y1*yn - 4*a1*yn*x1^2 - 4*a1*yn*xn^2 - 3*a2*x1*xn^2 - 3*a3*xn*y1 - 3*a4*m*x1^2 - 3*a6*m*x1 - 3*m*x1*xn^3 - 3*m*x1*yn^2 - 3*xn*a1^2*x1^2 - 2*a2*m*y1^2 + 2*a2*a6*m + 2*m*a2^2*x1^2 + 3*a4*x1*xn + 3*m*xn*yn^2 + 3*x1*a1^2*xn^2 + 4*a1*y1*x1^2 + 4*a1*y1*xn^2 + 6*a2*xn*x1^2 + 6*xn*y1*yn + 9*a6*m*xn + 9*m*x1^2*xn^2 + a2*m*a1^2*x1^2 + a4*m*x1*a1^2 - a1*a2*x1*y1 - a1*m*y1*x1^2 - a3*m*y1*a1^2 - m*x1*y1*a1^3 - 11*a1*x1*xn*y1 - 9*a3*m*xn*y1 - 6*m*xn*y1*yn - 4*a1*m*y1*xn^2 - 3*m*x1*a1^2*xn^2 - 2*a2*a3*m*y1 + 2*a2*a4*m*x1 + 3*a2*m*x1*xn^2 + 3*a3*m*x1*y1 + 3*m*xn*a1^2*x1^2 + 4*a1*m*yn*x1^2 + 4*a1*m*yn*xn^2 + 6*a2*m*xn*x1^2 + 6*m*x1*y1*yn + 8*a1*x1*xn*yn + 9*a4*m*x1*xn - a1*m*x1*xn*y1 - 8*a1*m*x1*xn*yn - 2*a1*a2*m*x1*y1) * hEn +
        (-a1^3*xn^4 - 5*a1*x1^5 - 3*l*x1^5 - 3*xn*y1^3 - 3*xn*yn^3 - 3*y1*x1^4 - 3*l^3*x1^4 - 3*l^3*xn^4 + 3*a3*xn^4 + 3*x1*y1^3 + 3*x1*yn^3 + 3*yn*x1^4 + 6*l*xn^5 + 6*yn*xn^4 + 8*a1*xn^5 + a2*a3*xn^3 + a3*a1^2*x1^3 + xn*a1^3*x1^3 + yn*a1^2*x1^3 - a2*a3*x1^3 - a3*a1^2*xn^3 - l*a1^2*x1^4 - m*a1^3*x1^4 - y1*a1^2*xn^3 - 22*a1*x1*xn^4 - 18*l*x1*xn^4 - 18*l^3*x1^2*xn^2 - 17*a1*x1^3*xn^2 - 15*l*x1^3*xn^2 - 12*x1*yn*xn^3 - 9*a3*x1*xn^3 - 7*a1*l^2*xn^4 - 7*a1*xn^2*yn^2 - 6*x1*y1*xn^3 - 6*xn*yn*x1^3 - 5*l*a1^2*xn^4 - 5*yn*a1^2*xn^3 - 4*a1*a2*x1^4 - 4*a1*a4*x1^3 - 4*a1*m*xn^5 - 4*a1*l^2*x1^4 - 4*a1*x1^2*yn^2 - 4*a2*y1*x1^3 - 3*a3*xn*x1^3 - 3*a3*xn*y1^2 - 3*a3*xn*yn^2 - 3*a3*l^2*xn^3 - 3*a4*l*x1^3 - 3*a4*y1*x1^2 - 3*a4*y1*xn^2 - 3*l*m*xn^5 - 3*l*x1^2*yn^2 - 3*l*xn^2*yn^2 - 3*m*x1*y1^3 - 3*m*x1*yn^3 - 3*m*yn*xn^4 - 3*m*l^3*x1^4 - 3*m*l^3*xn^4 - 3*x1*y1*yn^2 - 3*x1*yn*y1^2 - 3*y1*l^2*xn^3 - 3*yn*l^2*xn^3 - 3*a1^3*x1^2*xn^2 - 2*a2*l*x1^4 - 2*a2*y1*xn^3 + 2*a2*yn*x1^3 + 3*a3*m*x1^4 + 3*a3*x1*y1^2 + 3*a3*x1*yn^2 + 3*a3*l^2*x1^3 + 3*a4*l*xn^3 + 3*a4*yn*x1^2 + 3*a4*yn*xn^2 + 3*l*x1^2*y1^2 + 3*l*xn^2*y1^2 + 3*m*xn*y1^3 + 3*m*xn*yn^3 + 3*m*y1*xn^4 + 3*x1*a1^3*xn^3 + 3*xn*y1*yn^2 + 3*xn*yn*y1^2 + 3*y1*l^2*x1^3 + 3*yn*l^2*x1^3 + 4*a1*a4*xn^3 + 4*a1*xn^2*y1^2 + 4*a2*l*xn^4 + 4*a2*yn*xn^3 + 5*a1*a2*xn^4 + 5*y1*a1^2*x1^3 + 6*l*m*x1^5 + 6*m*y1*x1^4 + 7*a1*m*x1^5 + 7*a1*x1^2*y1^2 + 9*a3*x1^2*xn^2 + 9*l*xn*x1^4 + 9*y1*x1^2*xn^2 + 9*yn*x1^2*xn^2 + 12*x1*l^3*xn^3 + 12*xn*l^3*x1^3 + 13*a1*xn*x1^4 + 21*l*x1^2*xn^3 + 23*a1*x1^2*xn^3 + a2*a3*m*x1^3 + a3*m*a1^2*xn^3 + m*x1*a1^3*xn^3 + m*y1*a1^2*xn^3 - a2*a3*m*xn^3 - a3*m*a1^2*x1^3 - l*m*a1^2*xn^4 - m*yn*a1^2*x1^3 - 33*a1*l^2*x1^2*xn^2 - 18*l*m*xn*x1^4 - 18*l*a1^2*x1^2*xn^2 - 18*m*l^3*x1^2*xn^2 - 17*a1*m*xn*x1^4 - 15*l*m*x1^2*xn^3 - 12*a1*a4*x1*xn^2 - 12*m*xn*y1*x1^3 - 11*a1*a2*x1*xn^3 - 11*a1*x1*xn*y1^2 - 11*xn*y1*a1^2*x1^2 - 10*a2*l*x1*xn^3 - 9*a3*m*xn*x1^3 - 9*a3*xn*l^2*x1^2 - 9*a4*l*x1*xn^2 - 9*xn*y1*l^2*x1^2 - 9*xn*yn*l^2*x1^2 - 7*a1*l*yn*xn^3 - 7*a1*m*l^2*x1^4 - 7*a1*m*x1^2*xn^3 - 7*a1*m*x1^2*y1^2 - 7*xn*yn*a1^2*x1^2 - 6*a2*x1*yn*xn^2 - 6*a3*x1*y1*yn - 6*a4*x1*xn*yn - 6*l*x1*xn*y1^2 - 6*m*x1*y1*xn^3 - 6*m*xn*yn*x1^3 - 5*l*m*a1^2*x1^4 - 5*m*y1*a1^2*x1^3 - 4*a1*a2*m*xn^4 - 4*a1*a3*l*xn^3 - 4*a1*a3*yn*x1^2 - 4*a1*a3*yn*xn^2 - 4*a1*a4*m*xn^3 - 4*a1*l*y1*xn^3 - 4*a1*m*l^2*xn^4 - 4*a1*m*xn^2*y1^2 - 4*a2*m*yn*xn^3 - 3*a1*y1*yn*x1^2 - 3*a2*a3*x1*xn^2 - 3*a3*l*yn*x1^2 - 3*a3*l*yn*xn^2 - 3*a3*m*x1*xn^3 - 3*a3*m*x1*y1^2 - 3*a3*m*x1*yn^2 - 3*a3*m*l^2*x1^3 - 3*a3*xn*a1^2*x1^2 - 3*a4*l*m*xn^3 - 3*a4*m*yn*x1^2 - 3*a4*m*yn*xn^2 - 3*l*m*x1^2*y1^2 - 3*l*m*xn^2*y1^2 - 3*m*xn*y1*yn^2 - 3*m*xn*yn*y1^2 - 3*m*y1*l^2*x1^3 - 3*m*yn*l^2*x1^3 - 3*m*a1^3*x1^2*xn^2 - 2*a2*l*m*xn^4 - 2*a2*m*yn*x1^3 + 2*a2*l*xn*x1^3 + 2*a2*m*y1*xn^3 + 3*a1*a2*x1^2*xn^2 + 3*a1*y1*yn*xn^2 + 3*a2*a3*xn*x1^2 + 3*a3*l*y1*x1^2 + 3*a3*l*y1*xn^2 + 3*a3*m*xn*y1^2 + 3*a3*m*xn*yn^2 + 3*a3*m*l^2*xn^3 + 3*a3*x1*a1^2*xn^2 + 3*a4*l*m*x1^3 + 3*a4*m*y1*x1^2 + 3*a4*m*y1*xn^2 + 3*l*m*x1^2*yn^2 + 3*l*m*xn^2*yn^2 + 3*m*x1*y1*yn^2 + 3*m*x1*yn*y1^2 + 3*m*xn*a1^3*x1^3 + 3*m*y1*l^2*xn^3 + 3*m*yn*l^2*xn^3 + 4*a1*a3*l*x1^3 + 4*a1*a3*y1*x1^2 + 4*a1*a3*y1*xn^2 + 4*a1*a4*m*x1^3 + 4*a1*l*yn*x1^3 + 4*a1*m*x1^2*yn^2 + 4*a2*l*m*x1^4 + 4*a2*m*y1*x1^3 + 5*a1*a2*m*x1^4 + 5*m*yn*a1^2*xn^3 + 6*a2*l*x1^2*xn^2 + 6*a2*xn*y1*x1^2 + 6*a3*xn*y1*yn + 6*a4*x1*xn*y1 + 6*l*x1*xn*yn^2 + 7*a1*a2*xn*x1^3 + 7*a1*l*y1*x1^3 + 7*a1*m*xn^2*yn^2 + 7*x1*y1*a1^2*xn^2 + 8*a1*m*x1*xn^4 + 8*l*xn*a1^2*x1^3 + 9*a3*m*x1^2*xn^2 + 9*a3*x1*l^2*xn^2 + 9*a4*l*xn*x1^2 + 9*l*m*x1*xn^4 + 9*m*y1*x1^2*xn^2 + 9*m*yn*x1^2*xn^2 + 9*x1*y1*l^2*xn^2 + 9*x1*yn*l^2*xn^2 + 11*a1*x1*xn*yn^2 + 11*x1*yn*a1^2*xn^2 + 12*a1*a4*xn*x1^2 + 12*m*x1*l^3*xn^3 + 12*m*xn*l^3*x1^3 + 13*a1*m*x1^3*xn^2 + 16*l*x1*a1^2*xn^3 + 19*a1*xn*l^2*x1^3 + 21*l*m*x1^3*xn^2 + 25*a1*x1*l^2*xn^3 - 33*a1*m*l^2*x1^2*xn^2 - 18*a1*l*xn*y1*x1^2 - 18*l*m*a1^2*x1^2*xn^2 - 15*a1*l*xn*yn*x1^2 - 12*a1*a3*l*xn*x1^2 - 12*a1*a4*m*xn*x1^2 - 11*a1*a2*m*xn*x1^3 - 11*a1*m*x1*xn*yn^2 - 11*m*x1*yn*a1^2*xn^2 - 10*a2*l*m*xn*x1^3 - 9*a3*m*x1*l^2*xn^2 - 9*a4*l*m*xn*x1^2 - 9*m*x1*y1*l^2*xn^2 - 9*m*x1*yn*l^2*xn^2 - 8*a1*a3*x1*xn*y1 - 7*a1*l*m*y1*x1^3 - 7*m*x1*y1*a1^2*xn^2 - 6*a2*m*xn*y1*x1^2 - 6*a3*l*x1*xn*y1 - 6*a3*m*xn*y1*yn - 6*a4*m*x1*xn*y1 - 6*l*m*x1*xn*yn^2 - 4*a1*a3*l*m*x1^3 - 4*a1*a3*m*y1*x1^2 - 4*a1*a3*m*y1*xn^2 - 4*a1*l*m*yn*x1^3 - 3*a1*m*y1*yn*xn^2 - 3*a2*a3*m*xn*x1^2 - 3*a3*l*m*y1*x1^2 - 3*a3*l*m*y1*xn^2 - 3*a3*m*x1*a1^2*xn^2 + 2*a2*l*m*x1*xn^3 + 3*a1*a2*m*x1^2*xn^2 + 3*a1*m*y1*yn*x1^2 + 3*a2*a3*m*x1*xn^2 + 3*a3*l*m*yn*x1^2 + 3*a3*l*m*yn*xn^2 + 3*a3*m*xn*a1^2*x1^2 + 4*a1*a3*l*m*xn^3 + 4*a1*a3*m*yn*x1^2 + 4*a1*a3*m*yn*xn^2 + 4*a1*l*m*y1*xn^3 + 6*a2*l*m*x1^2*xn^2 + 6*a2*m*x1*yn*xn^2 + 6*a3*l*x1*xn*yn + 6*a3*m*x1*y1*yn + 6*a4*m*x1*xn*yn + 6*l*m*x1*xn*y1^2 + 7*a1*a2*m*x1*xn^3 + 7*a1*l*m*yn*xn^3 + 7*m*xn*yn*a1^2*x1^2 + 8*a1*a3*x1*xn*yn + 8*l*m*x1*a1^2*xn^3 + 9*a3*m*xn*l^2*x1^2 + 9*a4*l*m*x1*xn^2 + 9*m*xn*y1*l^2*x1^2 + 9*m*xn*yn*l^2*x1^2 + 11*a1*m*x1*xn*y1^2 + 11*m*xn*y1*a1^2*x1^2 + 12*a1*a3*l*x1*xn^2 + 12*a1*a4*m*x1*xn^2 + 15*a1*l*x1*y1*xn^2 + 16*l*m*xn*a1^2*x1^3 + 18*a1*l*x1*yn*xn^2 + 19*a1*m*x1*l^2*xn^3 + 25*a1*m*xn*l^2*x1^3 - 18*a1*l*m*x1*yn*xn^2 - 15*a1*l*m*x1*y1*xn^2 - 12*a1*a3*l*m*x1*xn^2 - 8*a1*a3*m*x1*xn*yn - 6*a3*l*m*x1*xn*yn + 6*a3*l*m*x1*xn*y1 + 8*a1*a3*m*x1*xn*y1 + 12*a1*a3*l*m*xn*x1^2 + 15*a1*l*m*xn*yn*x1^2 + 18*a1*l*m*xn*y1*x1^2) * hR3 +
        (x1^5 + 2*xn^5 + a2*x1^4 + a2*xn^4 - a1^2*x1^4 - a1^2*xn^4 - 7*x1*xn^4 - 3*l^2*x1^4 - 3*l^2*xn^4 - 2*xn*x1^4 - 2*x1^3*xn^2 + 8*x1^2*xn^3 - 18*l^2*x1^2*xn^2 - 6*a1^2*x1^2*xn^2 - 4*a1*l*x1^4 - 4*a1*l*xn^4 - 4*a2*x1*xn^3 - 4*a2*xn*x1^3 + 4*x1*a1^2*xn^3 + 4*xn*a1^2*x1^3 + 6*a2*x1^2*xn^2 + 12*x1*l^2*xn^3 + 12*xn*l^2*x1^3 - 24*a1*l*x1^2*xn^2 + 16*a1*l*x1*xn^3 + 16*a1*l*xn*x1^3) * hR5
    rcases mul_eq_zero.mp key with h0 | h0
    · linear_combination h0
    · exact absurd h0 (pow_ne_zero 5 hd)

set_option backward.isDefEq.respectTransparency false in
set_option maxHeartbeats 4000000 in
/-- **The differentiated duplication law**: the tangent case of the
invariant-differential additivity. Certificates saturated by
`ψ₂(P₁)⁴` resp. `ψ₂(P₁)⁵`. -/
theorem DK_doubling_step
    (a1 a2 a3 a4 a6 x1 y1 l x3 y3 : Kuniv)
    (hDa1 : DK a1 = 0) (hDa2 : DK a2 = 0) (hDa3 : DK a3 = 0)
    (hDa4 : DK a4 = 0)
    (hE1 : y1 ^ 2 + a1 * x1 * y1 + a3 * y1 =
      x1 ^ 3 + a2 * x1 ^ 2 + a4 * x1 + a6)
    (hs1 : 2 * y1 + a1 * x1 + a3 ≠ 0)
    (hl : l = (3 * x1 ^ 2 + 2 * a2 * x1 + a4 - a1 * y1) /
      (2 * y1 + a1 * x1 + a3))
    (hDx1 : DK x1 = 2 * y1 + a1 * x1 + a3)
    (hDy1 : DK y1 = -(a1 * y1 - (3 * x1 ^ 2 + 2 * a2 * x1 + a4)))
    (hx3 : x3 = l ^ 2 + a1 * l - a2 - 2 * x1)
    (hy3 : y3 = -(l * (x3 - x1) + y1) - a1 * x3 - a3) :
    DK x3 = 2 * (2 * y3 + a1 * x3 + a3) ∧
    DK y3 = -(2 * (a1 * y3 - (3 * x3 ^ 2 + 2 * a2 * x3 + a4))) := by
  have hD2 : DK (2 : Kuniv) = 0 := by
    rw [show (2 : Kuniv) = 1 + 1 by norm_num, DK_add, DK_one, add_zero]
  have hD3 : DK (3 : Kuniv) = 0 := by
    rw [show (3 : Kuniv) = 1 + 1 + 1 by norm_num, DK_add, DK_add,
      DK_one, add_zero, add_zero]
  have hneg : ∀ t : Kuniv, DK (-t) = -DK t := fun t => by
    have h := DK_sub 0 t
    rwa [zero_sub, DK_zero, zero_sub] at h
  have hR3 : l * (2 * y1 + a1 * x1 + a3) =
      3 * x1 ^ 2 + 2 * a2 * x1 + a4 - a1 * y1 := by
    rw [hl]
    exact div_mul_cancel₀ _ hs1
  have hnum : DK (3 * x1 ^ 2 + 2 * a2 * x1 + a4 - a1 * y1) =
      (6 * x1 + 2 * a2) * DK x1 - a1 * DK y1 := by
    have e1 := DK_sub (3 * x1 ^ 2 + 2 * a2 * x1 + a4) (a1 * y1)
    have e2 := DK_add (3 * x1 ^ 2 + 2 * a2 * x1) a4
    have e3 := DK_add (3 * x1 ^ 2) (2 * a2 * x1)
    have e4 := DK_mul (3 : Kuniv) (x1 ^ 2)
    have e5 := DK_sq x1
    have e6 := DK_mul (2 * a2) x1
    have e7 := DK_mul (2 : Kuniv) a2
    have e8 := DK_mul a1 y1
    linear_combination e1 + e2 + e3 + e4 + 3 * e5 + e6 + x1 * e7 -
      e8 + x1 ^ 2 * hD3 + 2 * x1 * hDa2 + a2 * x1 * hD2 + hDa4 -
      y1 * hDa1
  have hden : DK (2 * y1 + a1 * x1 + a3) =
      2 * DK y1 + a1 * DK x1 := by
    have e1 := DK_add (2 * y1 + a1 * x1) a3
    have e2 := DK_add (2 * y1) (a1 * x1)
    have e3 := DK_mul (2 : Kuniv) y1
    have e4 := DK_mul a1 x1
    linear_combination e1 + e2 + e3 + e4 + y1 * hD2 + x1 * hDa1 + hDa3
  have hR5 : DK l * (2 * y1 + a1 * x1 + a3) =
      ((6 * x1 + 2 * a2) * DK x1 - a1 * DK y1) -
        l * (2 * DK y1 + a1 * DK x1) := by
    have h1 := congrArg DK hR3
    have h2 := DK_mul l (2 * y1 + a1 * x1 + a3)
    linear_combination h1 - h2 + hnum - l * hden
  rw [hDx1, hDy1] at hR5
  have hDx3 : DK x3 = 2 * l * DK l + a1 * DK l - 2 * DK x1 := by
    rw [hx3]
    have e1 := DK_sub (l ^ 2 + a1 * l - a2) (2 * x1)
    have e2 := DK_sub (l ^ 2 + a1 * l) a2
    have e3 := DK_add (l ^ 2) (a1 * l)
    have e4 := DK_sq l
    have e5 := DK_mul a1 l
    have e6 := DK_mul (2 : Kuniv) x1
    linear_combination e1 + e2 + e3 + e4 + e5 + l * hDa1 - hDa2 -
      e6 - x1 * hD2
  have hDy3 : DK y3 = -(DK l * (x3 - x1) +
      l * (DK x3 - DK x1) + DK y1) - a1 * DK x3 := by
    rw [hy3]
    have e1 := DK_sub (-(l * (x3 - x1) + y1) - a1 * x3) a3
    have e2 := DK_sub (-(l * (x3 - x1) + y1)) (a1 * x3)
    have e3 := hneg (l * (x3 - x1) + y1)
    have e4 := DK_add (l * (x3 - x1)) y1
    have e5 := DK_mul l (x3 - x1)
    have e6 := DK_sub x3 x1
    have e7 := DK_mul a1 x3
    linear_combination e1 + e2 + e3 - e4 - l * e6 - e5 - e7 -
      x3 * hDa1 - hDa3
  rw [hDx1] at hDx3
  rw [hDx3, hDx1, hDy1] at hDy3
  constructor
  · have key : (DK x3 - 2 * (2 * y3 + a1 * x3 + a3)) *
        (2 * y1 + a1 * x1 + a3) ^ 4 = 0 := by
      rw [hDx3, hy3, hx3]
      linear_combination
        (0) * hE1 +
        (a1^2*a3^3 + a1^5*x1^3 + 4*a3^3*l^2 + 8*a1^2*y1^3 + 32*l^2*y1^3 + 3*a3*a1^4*x1^2 + 3*x1*a1^3*a3^2 + 4*a1*l*a3^3 + 4*l*a1^4*x1^3 + 4*a1^3*l^2*x1^3 + 6*y1*a1^2*a3^2 + 6*y1*a1^4*x1^2 + 12*a3*a1^2*y1^2 + 12*x1*a1^3*y1^2 + 24*y1*a3^2*l^2 + 32*a1*l*y1^3 + 48*a3*l^2*y1^2 + 12*a1*x1*a3^2*l^2 + 12*a3*l*a1^3*x1^2 + 12*a3*x1*y1*a1^3 + 12*a3*a1^2*l^2*x1^2 + 12*l*x1*a1^2*a3^2 + 24*a1*l*y1*a3^2 + 24*l*y1*a1^3*x1^2 + 24*y1*a1^2*l^2*x1^2 + 48*a1*a3*l*y1^2 + 48*a1*x1*l^2*y1^2 + 48*l*x1*a1^2*y1^2 + 48*a1*a3*x1*y1*l^2 + 48*a3*l*x1*y1*a1^2) * hR3 +
        (a1*a3^3 + a1^4*x1^3 + 2*l*a3^3 + 8*a1*y1^3 + 16*l*y1^3 + 2*l*a1^3*x1^3 + 3*a3*a1^3*x1^2 + 3*x1*a1^2*a3^2 + 6*a1*y1*a3^2 + 6*y1*a1^3*x1^2 + 12*a1*a3*y1^2 + 12*l*y1*a3^2 + 12*x1*a1^2*y1^2 + 24*a3*l*y1^2 + 6*a1*l*x1*a3^2 + 6*a3*l*a1^2*x1^2 + 12*a3*x1*y1*a1^2 + 12*l*y1*a1^2*x1^2 + 24*a1*l*x1*y1^2 + 24*a1*a3*l*x1*y1) * hR5
    rcases mul_eq_zero.mp key with h0 | h0
    · linear_combination h0
    · exact absurd h0 (pow_ne_zero 4 hs1)
  · have key : (DK y3 + 2 * (a1 * y3 -
        (3 * x3 ^ 2 + 2 * a2 * x3 + a4))) *
        (2 * y1 + a1 * x1 + a3) ^ 5 = 0 := by
      rw [hDy3, hy3, hx3]
      linear_combination
        (0) * hE1 +
        (3*a3^5 + 96*y1^5 - a1^3*a3^4 - a1^7*x1^4 - 96*l^3*y1^4 - 16*a1^3*y1^4 - 6*a3^4*l^3 + 6*a1^5*x1^5 + 30*y1*a3^4 + 120*a3^3*y1^2 + 240*a3*y1^4 + 240*a3^2*y1^3 + a1*a2*a3^4 + a2*a1^5*x1^4 - 192*a3*l^3*y1^3 - 176*a1*l^2*y1^4 - 144*a3^2*l^3*y1^2 - 96*l*a1^2*y1^4 - 48*y1*a3^3*l^3 - 32*a3*a1^3*y1^3 - 32*x1*a1^4*y1^3 - 24*a1^3*a3^2*y1^2 - 24*a1^5*x1^2*y1^2 - 11*a1*a3^4*l^2 - 11*a1^5*l^2*x1^4 - 8*y1*a1^3*a3^3 - 8*y1*a1^6*x1^3 - 6*l*a1^2*a3^4 - 6*l*a1^6*x1^4 - 6*a1^4*l^3*x1^4 - 6*a1^5*a3^2*x1^2 - 4*a3*a1^6*x1^3 - 4*x1*a1^4*a3^3 + 2*a2*l*a3^4 + 6*l*x1*a3^4 + 6*l*a1^4*x1^5 + 16*a1*a2*y1^4 + 18*a1*x1*a3^4 + 27*a3*a1^4*x1^4 + 32*a2*l*y1^4 + 42*a1^2*a3^3*x1^2 + 48*a1^3*a3^2*x1^3 + 54*y1*a1^4*x1^4 + 96*l*x1*y1^4 + 192*a1^3*x1^3*y1^2 + 288*a1*x1*y1^4 + 336*a1^2*x1^2*y1^3 - 352*a1*a3*l^2*y1^3 - 352*x1*a1^2*l^2*y1^3 - 264*a1*a3^2*l^2*y1^2 - 264*a1^3*l^2*x1^2*y1^2 - 192*a1*x1*l^3*y1^3 - 192*a3*l*a1^2*y1^3 - 192*l*x1*a1^3*y1^3 - 144*l*a1^2*a3^2*y1^2 - 144*l*a1^4*x1^2*y1^2 - 144*a1^2*l^3*x1^2*y1^2 - 88*a1*y1*a3^3*l^2 - 88*y1*a1^4*l^2*x1^3 - 66*a1^3*a3^2*l^2*x1^2 - 48*a3*x1*a1^4*y1^2 - 48*l*y1*a1^2*a3^3 - 48*l*y1*a1^5*x1^3 - 48*y1*a1^3*l^3*x1^3 - 44*a3*a1^4*l^2*x1^3 - 44*x1*a1^2*a3^3*l^2 - 36*l*a1^4*a3^2*x1^2 - 36*a1^2*a3^2*l^3*x1^2 - 24*a1*x1*a3^3*l^3 - 24*a3*l*a1^5*x1^3 - 24*a3*y1*a1^5*x1^2 - 24*a3*a1^3*l^3*x1^3 - 24*l*x1*a1^3*a3^3 - 24*x1*y1*a1^4*a3^2 + 2*a2*l*a1^4*x1^4 + 4*a2*a3*a1^4*x1^3 + 4*a2*x1*a1^2*a3^3 + 6*a2*a1^3*a3^2*x1^2 + 8*a1*a2*y1*a3^3 + 8*a2*y1*a1^4*x1^3 + 16*a2*l*y1*a3^3 + 24*a1*a2*a3^2*y1^2 + 24*a1*l*a3^3*x1^2 + 24*a2*a1^3*x1^2*y1^2 + 24*a3*l*a1^3*x1^4 + 32*a1*a2*a3*y1^3 + 32*a2*x1*a1^2*y1^3 + 36*l*a1^2*a3^2*x1^3 + 48*a2*l*a3^2*y1^2 + 48*l*x1*y1*a3^3 + 48*l*y1*a1^3*x1^4 + 64*a2*a3*l*y1^3 + 144*a1*x1*y1*a3^3 + 144*l*x1*a3^2*y1^2 + 144*l*a1^2*x1^3*y1^2 + 192*a1*l*x1^2*y1^3 + 192*a3*l*x1*y1^3 + 192*a3*y1*a1^3*x1^3 + 252*y1*a1^2*a3^2*x1^2 + 432*a1*x1*a3^2*y1^2 + 504*a3*a1^2*x1^2*y1^2 + 576*a1*a3*x1*y1^3 - 528*a3*x1*a1^2*l^2*y1^2 - 288*a1*a3*x1*l^3*y1^2 - 288*a3*l*x1*a1^3*y1^2 - 264*a3*y1*a1^3*l^2*x1^2 - 264*x1*y1*a1^2*a3^2*l^2 - 144*a1*x1*y1*a3^2*l^3 - 144*a3*l*y1*a1^4*x1^2 - 144*a3*y1*a1^2*l^3*x1^2 - 144*l*x1*y1*a1^3*a3^2 + 8*a1*a2*l*x1*a3^3 + 8*a2*a3*l*a1^3*x1^3 + 12*a2*l*a1^2*a3^2*x1^2 + 16*a2*l*y1*a1^3*x1^3 + 24*a2*a3*y1*a1^3*x1^2 + 24*a2*x1*y1*a1^2*a3^2 + 48*a2*a3*x1*a1^2*y1^2 + 48*a2*l*a1^2*x1^2*y1^2 + 64*a1*a2*l*x1*y1^3 + 144*a1*l*y1*a3^2*x1^2 + 144*a3*l*y1*a1^2*x1^3 + 288*a1*a3*l*x1^2*y1^2 + 48*a1*a2*l*x1*y1*a3^2 + 48*a2*a3*l*y1*a1^2*x1^2 + 96*a1*a2*a3*l*x1*y1^2) * hR3 +
        (a2*a3^4 - a1^2*a3^4 - a1^6*x1^4 - 48*l^2*y1^4 - 16*a1^2*y1^4 - 3*a3^4*l^2 + 3*x1*a3^4 + 3*a1^4*x1^5 + 16*a2*y1^4 + 48*x1*y1^4 + a2*a1^4*x1^4 - 96*a3*l^2*y1^3 - 72*a3^2*l^2*y1^2 - 64*a1*l*y1^4 - 32*a3*a1^2*y1^3 - 32*x1*a1^3*y1^3 - 24*y1*a3^3*l^2 - 24*a1^2*a3^2*y1^2 - 24*a1^4*x1^2*y1^2 - 8*y1*a1^2*a3^3 - 8*y1*a1^5*x1^3 - 6*a1^4*a3^2*x1^2 - 4*a1*l*a3^4 - 4*a3*a1^5*x1^3 - 4*l*a1^5*x1^4 - 4*x1*a1^3*a3^3 - 3*a1^4*l^2*x1^4 + 8*a2*y1*a3^3 + 12*a1*a3^3*x1^2 + 12*a3*a1^3*x1^4 + 18*a1^2*a3^2*x1^3 + 24*a2*a3^2*y1^2 + 24*x1*y1*a3^3 + 24*y1*a1^3*x1^4 + 32*a2*a3*y1^3 + 72*x1*a3^2*y1^2 + 72*a1^2*x1^3*y1^2 + 96*a1*x1^2*y1^3 + 96*a3*x1*y1^3 - 128*a1*a3*l*y1^3 - 128*l*x1*a1^2*y1^3 - 96*a1*l*a3^2*y1^2 - 96*a1*x1*l^2*y1^3 - 96*l*a1^3*x1^2*y1^2 - 72*a1^2*l^2*x1^2*y1^2 - 48*a3*x1*a1^3*y1^2 - 32*a1*l*y1*a3^3 - 32*l*y1*a1^4*x1^3 - 24*a3*y1*a1^4*x1^2 - 24*l*a1^3*a3^2*x1^2 - 24*x1*y1*a1^3*a3^2 - 24*y1*a1^3*l^2*x1^3 - 18*a1^2*a3^2*l^2*x1^2 - 16*a3*l*a1^4*x1^3 - 16*l*x1*a1^2*a3^3 - 12*a1*x1*a3^3*l^2 - 12*a3*a1^3*l^2*x1^3 + 4*a1*a2*x1*a3^3 + 4*a2*a3*a1^3*x1^3 + 6*a2*a1^2*a3^2*x1^2 + 8*a2*y1*a1^3*x1^3 + 24*a2*a1^2*x1^2*y1^2 + 32*a1*a2*x1*y1^3 + 72*a1*y1*a3^2*x1^2 + 72*a3*y1*a1^2*x1^3 + 144*a1*a3*x1^2*y1^2 - 192*a3*l*x1*a1^2*y1^2 - 144*a1*a3*x1*l^2*y1^2 - 96*a3*l*y1*a1^3*x1^2 - 96*l*x1*y1*a1^2*a3^2 - 72*a1*x1*y1*a3^2*l^2 - 72*a3*y1*a1^2*l^2*x1^2 + 24*a1*a2*x1*y1*a3^2 + 24*a2*a3*y1*a1^2*x1^2 + 48*a1*a2*a3*x1*y1^2) * hR5
    rcases mul_eq_zero.mp key with h0 | h0
    · linear_combination h0
    · exact absurd h0 (pow_ne_zero 5 hs1)

end PsiSumCompanion
