/-
Fermat/FLT/Mathlib/RingTheory/Smooth/RegularLocal.lean — own work for the
Fermat project (not vendored from the FLT project).

# Regular ⟹ formally smooth over a perfect field (Stacks `056S`), in its
# regular-LOCAL form

This module states, **once**, the commutative-algebra fact that at least four
open nodes of this development were each about to build separately:

> a **regular local** ring essentially of finite type over a **perfect** field
> is **formally smooth** over that field.

That is `Algebra.FormallySmooth.of_isRegularLocalRing_of_perfectField` below.
The four consumers, all of which now go through it, are

| node | file |
|---|---|
| `formallySmooth_of_isDiscreteValuationRing_of_perfectField` | `Fermat/FLT/Mathlib/AlgebraicGeometry/CurveExtension.lean` |
| `smoothOfRelativeDimension_specMap_algebraMap_of_isRegularRing` | `Fermat/FLT/Mathlib/AlgebraicGeometry/SmoothConnectedCriteria.lean` |
| `smoothOfRelativeDimension_of_gamma0GITPresentation` | `Fermat/FLT/ModularCurve/X0.lean` (already a theorem over the previous row) |
| `smoothOfRelativeDimension_one_fromNormalization` | `Fermat/FLT/Mathlib/AlgebraicGeometry/CurveCompactification.lean` (already a theorem over the first row) |

**This module's ONLY `Fermat` import is `Fermat/FLT/Modularity/RegularStalks.lean`**
(added 2026-07-28 when arrow (a) was closed, and sanctioned by the leaf's own
docstring).  That module carries the CONVERSE,
`isRegularLocalRing_stalk_of_smooth_over_field`, is sorry-free, and has NO
`Fermat` imports of its own, so no cycle is created and this module stays
importable from anywhere in the tree, including the mathlib-shim modules.  Two
of its declarations —
`GaloisRepresentation.Modularity.isRegularLocalRing_quotient_span_singleton` and
`…isDomain_of_isRegularLocalRing` — are what arrow (a) is proven over; mathlib
has neither.

## The cut

The statement is proven over exactly two named pieces:

* `Algebra.exists_localizationAtPrime_mvPolynomial_surjective` — **PROVEN
  here**.  A local ring essentially of finite type over a field `K` is a
  quotient of a localization of a polynomial ring `K[x₁,…,x_n]` at a prime.
  This is the presentation bookkeeping and contains no mathematics; it is
  modelled on the presentation built inside mathlib's
  `Algebra.FormallySmooth.of_formallySmooth_residueField_tensor`
  (`Mathlib/RingTheory/Smooth/Fiber.lean`), simplified by the fact that our
  base is a field and our target is local, so the localization can be taken at
  a prime and is itself regular local and noetherian.
* `Algebra.injective_cotangentComplexBaseChange_of_isRegularLocalRing` — **PROVEN
  here** over arrow (a) below.  It is the injectivity that the local Jacobian
  criterion asks for, and it splits into the two arrows (a) and (b) described
  next; **arrow (b), the one that uses `PerfectField`, is proven outright**.
* `Algebra.injective_lTensor_residueField_kerInclusion` — arrow (a) alone,
  **PROVEN 2026-07-28; this module is now sorry-free**.  It mentions no field,
  no perfectness and no module of differentials: it says only that for a
  surjection `P ↠ S` of REGULAR LOCAL rings the map `I/𝔪_P I → 𝔪_P/𝔪_P²` is
  injective, i.e. that `I` is generated by part of a regular system of
  parameters.  Its proof reduces to the ideal-theoretic identity
  `I ∩ 𝔪_P² = 𝔪_P I` (`Algebra.inf_sq_le_mul_of_isRegularLocalRing`), which is
  proven by induction on the embedding dimension of `P`; see that declaration's
  docstring for why no regular system of parameters ever has to be built.

## What arrow (a) says, and the classical proof of it

`Algebra.FormallySmooth.iff_injective_cotangentComplexBaseChange_residueField`
(`Mathlib/RingTheory/Smooth/Local.lean`) is the **local Jacobian criterion**:
for a presentation `0 → I → P → S → 0` of a LOCAL ring `S` with `P` formally
smooth over `K`, `Ω[P⁄K]` finite free and `I` finitely generated,

    FormallySmooth K S  ↔  κ ⊗_S I/I² → κ ⊗_P Ω[P⁄K]  is injective,

`κ = ResidueField S`.  Taking `P = K[x]_𝔮` (which is what the presentation
lemma supplies), the map factors — by Leibniz, `d f mod 𝔪_P` depends only on
`f mod 𝔪_P²` — as

    κ ⊗_S I/I²  =  I/𝔪_P I  --(a)-->  𝔪_P/𝔪_P²  --(b)-->  κ ⊗_P Ω[P⁄K]

and the two arrows are injective for two different reasons:

* **(a) is regularity.**  `P` is regular local and `S = P/I` is regular local,
  so with `c = dim P - dim S`: pick `f₁,…,f_c ∈ I` whose classes are a basis of
  `(I + 𝔪_P²)/𝔪_P²` (there are exactly `c` of them because
  `𝔪_S/𝔪_S² = 𝔪_P/(𝔪_P² + I)` has dimension `dim S`).  Then `P/(f₁,…,f_c)` is
  regular local of dimension `dim S`, hence a DOMAIN, and it surjects onto
  `P/I = S`, also of dimension `dim S`; a surjection of domains of equal
  dimension over a catenary ring is an isomorphism, so `I = (f₁,…,f_c)`.
  Therefore `I/𝔪_P I` has dimension at most `c` and surjects onto the
  `c`-dimensional `(I + 𝔪_P²)/𝔪_P²`, so (a) is injective.
  **THAT IS NOT HOW IT WAS ACTUALLY PROVEN.**  The displayed argument needs a
  chosen `f₁,…,f_c`, hence a list induction and a linear-independence transfer
  into `𝔪_P/𝔪_P²`.  The formalised proof (see
  `Algebra.inf_sq_le_mul_of_isRegularLocalRing_aux`) instead inducts on the
  embedding dimension `spanFinrank 𝔪_P`, peeling ONE element `y ∈ I ∖ 𝔪_P²` at a
  time and descending to `P ⧸ (y)`.  It therefore needs only the SINGLETON
  quotient lemma `GaloisRepresentation.Modularity.
  isRegularLocalRing_quotient_span_singleton` and
  `…isDomain_of_isRegularLocalRing` from
  `Fermat/FLT/Modularity/RegularStalks.lean` — the list induction
  `…isRegularLocalRing_quotient_span_list_aux` and the Steinitz exchange lemma
  turned out NOT to be needed.
* **(b) is PERFECTNESS, and it is PROVEN below — FOR FREE.**  For a local
  `K`-algebra `P` with residue field `κ` there is an exact sequence
  `𝔪_P/𝔪_P² --δ--> κ ⊗_P Ω[P⁄K] → Ω[κ⁄K] → 0`, and `δ` is injective **iff** `κ`
  is formally smooth over `K` (Matsumura, *CRT* Thm 25.2 / §28).  That sequence
  does **not** have to be built: arrow (b) is literally
  `cotangentComplexBaseChange` for the presentation `P ↠ κ` instead of `P ↠ S`,
  so mathlib's own
  `Algebra.FormallySmooth.iff_injective_cotangentComplexBaseChange`, read at the
  local ring `κ` (a field, so the criterion's `h₃` is vacuous), makes (b)
  equivalent to `Algebra.FormallySmooth K κ` — which is
  `Algebra.FormallySmooth.of_perfectField`
  (`Mathlib/RingTheory/Smooth/Field.lean`), since `κ` is essentially of finite
  type over the perfect `K`.  Equivalently `H₁(L_{κ⁄K}) = 0`, the vanishing that
  fails over an imperfect base.

## Faithfulness

`PerfectField K` is load-bearing and the statement is FALSE without it.  Over
an imperfect field `k = 𝔽_p(t)` the ring
`R = k[x,y]_{(x,y)}/(y^p - t x^p - t)` is a regular local ring (indeed a DVR)
essentially of finite type over `k` which is NOT formally smooth over `k`: its
residue field contains `t^{1/p}` and is purely inseparable over `k`, so
`H₁(L_{κ⁄k}) ≠ 0` and arrow (b) above fails.  This is the standard
quasi-elliptic counterexample, and it is exactly why the leaf below cannot be
proven without the perfectness hypothesis entering at (b).

`Algebra.EssFiniteType K R` is load-bearing too — it is what supplies the
presentation at all, and what makes `κ` finitely generated over `K` so that
`of_perfectField` applies.  A regular local ring that is merely a `K`-algebra
need not be formally smooth (e.g. a complete DVR of mixed characteristic is
not formally smooth over its residue field in the non-perfect case).

*Refute the main statement with*: a regular local ring, essentially of finite
type over a PERFECT field, that is not formally smooth over it.  There is none
(Stacks `056S`); over an imperfect field there are, and one is displayed above.
-/
module

public import Mathlib.LinearAlgebra.TensorProduct.Quotient
public import Mathlib.RingTheory.EssentialFiniteness
public import Mathlib.RingTheory.Etale.Kaehler
public import Mathlib.RingTheory.Kaehler.Polynomial
public import Mathlib.RingTheory.KrullDimension.NonZeroDivisors
public import Mathlib.RingTheory.Localization.AtPrime.Basic
public import Mathlib.RingTheory.Nakayama
public import Mathlib.RingTheory.RegularLocalRing.Polynomial
public import Mathlib.RingTheory.Smooth.Field
public import Mathlib.RingTheory.Smooth.Local
public import Mathlib.RingTheory.Smooth.Locus
public import Fermat.FLT.Modularity.RegularStalks

@[expose] public section

open TensorProduct

universe u

namespace Algebra

/-- **A LOCAL RING ESSENTIALLY OF FINITE TYPE OVER A FIELD IS A QUOTIENT OF A
LOCALIZED POLYNOMIAL RING AT A PRIME** (PROVEN 2026-07-28).

This is the presentation half of `FormallySmooth.of_isRegularLocalRing_of_perfectField`
and contains no mathematics beyond bookkeeping.  `Algebra.EssFiniteType` gives a
finite-type `K`-subalgebra `A ⊆ R` with `R` a localization of `A`; a surjection
`K[x₁,…,x_n] ↠ A` then composes to `g : K[x₁,…,x_n] → R`, and `𝔮 := g⁻¹(𝔪_R)`
is a prime whose complement `g` sends to units, so `g` extends over
`K[x₁,…,x_n]_𝔮`.  Surjectivity is `IsLocalization.lift_surjective_iff`: every
`r ∈ R` is `a/m` with `a, m` coming from `K[x₁,…,x_n]` and `m` a unit in `R`,
hence outside `𝔮`.

The point of localizing **at a prime** rather than at an arbitrary submonoid
(which is what mathlib's `Smooth/Fiber.lean` does) is that the resulting `P` is
itself LOCAL, NOETHERIAN and REGULAR LOCAL, which is what the Jacobian-criterion
step needs. -/
theorem exists_localizationAtPrime_mvPolynomial_surjective
    (K R : Type u) [Field K] [CommRing R] [IsLocalRing R] [Algebra K R]
    [Algebra.EssFiniteType K R] :
    ∃ (n : ℕ) (q : Ideal (MvPolynomial (Fin n) K)) (_ : q.IsPrime)
      (f : Localization.AtPrime q →ₐ[K] R), Function.Surjective f := by
  classical
  obtain ⟨n, f₀, hf₀⟩ := Algebra.FiniteType.iff_quotient_mvPolynomial''.mp
    (inferInstance : Algebra.FiniteType K (Algebra.EssFiniteType.subalgebra K R))
  set g : MvPolynomial (Fin n) K →ₐ[K] R :=
    (IsScalarTower.toAlgHom K (Algebra.EssFiniteType.subalgebra K R) R).comp f₀ with hgdef
  set q : Ideal (MvPolynomial (Fin n) K) :=
    Ideal.comap g.toRingHom (IsLocalRing.maximalIdeal R) with hqdef
  have hqp : q.IsPrime := Ideal.comap_isPrime _ _
  haveI := hqp
  have hunit : ∀ y : q.primeCompl, IsUnit (g y) := by
    rintro ⟨y, hy⟩
    refine IsLocalRing.notMem_maximalIdeal.mp fun h ↦ hy ?_
    exact Ideal.mem_comap.mpr h
  refine ⟨n, q, hqp, IsLocalization.liftAlgHom (M := q.primeCompl) (f := g) hunit, ?_⟩
  show Function.Surjective (IsLocalization.lift (M := q.primeCompl) (g := g.toRingHom) hunit)
  rw [IsLocalization.lift_surjective_iff]
  intro v
  obtain ⟨⟨a, m⟩, hv⟩ := IsLocalization.mk'_surjective
    (Algebra.EssFiniteType.submonoid K R) v
  obtain ⟨x, rfl⟩ := hf₀ a
  obtain ⟨s, hs⟩ := hf₀ (m : Algebra.EssFiniteType.subalgebra K R)
  have hgs : g s = algebraMap (Algebra.EssFiniteType.subalgebra K R) R m := by
    rw [hgdef]; simp [hs]
  have hsq : s ∈ q.primeCompl := by
    intro hmem
    exact (IsLocalRing.notMem_maximalIdeal.mpr
      (hgs ▸ IsLocalization.map_units R m)) (Ideal.mem_comap.mp hmem)
  refine ⟨⟨x, ⟨s, hsq⟩⟩, ?_⟩
  have hv' : IsLocalization.mk' R (f₀ x) m = v := hv
  have hspec := IsLocalization.mk'_spec (M := Algebra.EssFiniteType.submonoid K R) R
    (f₀ x) m
  rw [hv'] at hspec
  simpa [hgs, hgdef, hs] using hspec

/-- **TRANSPORT OF `lTensor`-INJECTIVITY ALONG A LINEAR EQUIVALENCE OF THE LEFT
FACTOR** (PROVEN 2026-07-28).

Purely formal: `B ⊗ f` is conjugate to `A ⊗ f` by `TensorProduct.congr e (refl)`.
It is what lets the regular-local core below be proven for the concrete residue
field `P ⧸ 𝔪_P` and then transported to `ResidueField S`, which is the residue
field of a DIFFERENT ring that merely happens to be `P`-isomorphic to it. -/
theorem injective_lTensor_of_linearEquiv {R : Type*} [CommRing R]
    {A B M N : Type*} [AddCommGroup A] [Module R A] [AddCommGroup B] [Module R B]
    [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]
    (e : A ≃ₗ[R] B) (f : M →ₗ[R] N)
    (h : Function.Injective (LinearMap.lTensor A f)) :
    Function.Injective (LinearMap.lTensor B f) := by
  have e1 : ∀ w : A ⊗[R] M,
      (_root_.TensorProduct.congr e (LinearEquiv.refl R N)) (LinearMap.lTensor A f w)
        = LinearMap.lTensor B f ((_root_.TensorProduct.congr e (LinearEquiv.refl R M)) w) := by
    intro w
    induction w with
    | zero => simp
    | add a b ha hb => simp [ha, hb]
    | tmul a m => simp
  intro u v huv
  obtain ⟨u', rfl⟩ := (_root_.TensorProduct.congr e (LinearEquiv.refl R M)).surjective u
  obtain ⟨v', rfl⟩ := (_root_.TensorProduct.congr e (LinearEquiv.refl R M)).surjective v
  rw [← e1, ← e1] at huv
  exact congrArg _ (h ((_root_.TensorProduct.congr e (LinearEquiv.refl R N)).injective huv))

/-- **AN IDEAL INSIDE `𝔪²` WITH REGULAR LOCAL QUOTIENT IS ZERO** (PROVEN
2026-07-28) — the base case of `inf_sq_le_mul_of_isRegularLocalRing` below.

THE PROOF is the standard "the embedding dimension does not drop" count.  Let
`m = spanFinrank 𝔪_{P⧸I}` and lift a minimal generating set of `𝔪_{P⧸I}` to a
set `t ⊆ P` of at most `m` elements.  Then `𝔪_P ≤ span t ⊔ I ≤ span t ⊔ 𝔪_P²`,
so **Nakayama** (`Submodule.le_of_le_smul_of_le_jacobson_bot`) gives
`𝔪_P = span t` and hence `spanFinrank 𝔪_P ≤ m`.  By regularity of BOTH rings
that reads `dim P ≤ dim (P ⧸ I)`.

If `I ≠ ⊥`, pick `0 ≠ r ∈ I`.  `P` is a DOMAIN
(`GaloisRepresentation.Modularity.isDomain_of_isRegularLocalRing`), so `r` is a
non-zero-divisor and `ringKrullDim_succ_le_of_surjective` gives
`dim (P ⧸ I) + 1 ≤ dim P ≤ dim (P ⧸ I)`, absurd because both dimensions are the
cast of a natural number. -/
theorem eq_bot_of_le_sq_of_isRegularLocalRing_quotient
    {P : Type u} [CommRing P] [IsRegularLocalRing P] (I : Ideal P)
    (hI2 : I ≤ (IsLocalRing.maximalIdeal P) ^ 2)
    [IsRegularLocalRing (P ⧸ I)] : I = ⊥ := by
  classical
  set f : P →+* P ⧸ I := Ideal.Quotient.mk I with hf
  have hfsurj : Function.Surjective f := Ideal.Quotient.mk_surjective
  have hmaxmap : (IsLocalRing.maximalIdeal P).map f = IsLocalRing.maximalIdeal (P ⧸ I) :=
    IsLocalRing.map_maximalIdeal_of_surjective _ hfsurj
  obtain ⟨G, hGcard, hGspan⟩ :=
    (IsNoetherian.noetherian
      (IsLocalRing.maximalIdeal (P ⧸ I))).exists_span_finset_card_eq_spanFinrank
  set t : Set P := (Function.surjInv hfsurj) '' (G : Set (P ⧸ I)) with ht
  have htfin : t.Finite := (G.finite_toSet).image _
  have htimg : f '' t = (G : Set (P ⧸ I)) := by
    rw [ht, ← Set.image_comp, Function.comp_surjInv, Set.image_id]
  have hmapT : (Ideal.span t).map f = IsLocalRing.maximalIdeal (P ⧸ I) := by
    rw [Ideal.map_span, htimg]
    exact hGspan
  have hmle : IsLocalRing.maximalIdeal P ≤ Ideal.span t ⊔ I := by
    intro x hx
    have h1 : f x ∈ (Ideal.span t).map f := by
      rw [hmapT, ← hmaxmap]; exact Ideal.mem_map_of_mem _ hx
    have h2 : x ∈ Ideal.comap f ((Ideal.span t).map f) := h1
    have hkerf : Ideal.comap f (⊥ : Ideal (P ⧸ I)) = I := Ideal.mk_ker
    rwa [Ideal.comap_map_of_surjective f hfsurj, hkerf] at h2
  have hnak : IsLocalRing.maximalIdeal P ≤ Ideal.span t := by
    refine Submodule.le_of_le_smul_of_le_jacobson_bot (I := IsLocalRing.maximalIdeal P)
      (IsNoetherian.noetherian _) ?_ ?_
    · rw [IsLocalRing.jacobson_eq_maximalIdeal (⊥ : Ideal P) bot_ne_top]
    · refine hmle.trans (sup_le_sup_left (hI2.trans ?_) _)
      rw [pow_two, ← Ideal.smul_eq_mul]
  have htle : Ideal.span t ≤ IsLocalRing.maximalIdeal P := by
    rw [Ideal.span_le]
    intro x hx
    by_contra hxm
    have hu : IsUnit (f x) := (IsLocalRing.notMem_maximalIdeal.mp hxm).map f
    refine IsLocalRing.notMem_maximalIdeal.mpr hu ?_
    rw [← hGspan]
    exact Ideal.subset_span (by rw [← htimg]; exact ⟨x, hx, rfl⟩)
  have hspanEq : Ideal.span t = IsLocalRing.maximalIdeal P := le_antisymm htle hnak
  have hspanFin : (IsLocalRing.maximalIdeal P).spanFinrank ≤
      (IsLocalRing.maximalIdeal (P ⧸ I)).spanFinrank := by
    rw [← hspanEq, ← hGcard]
    refine (Submodule.spanFinrank_span_le_ncard_of_finite htfin).trans ?_
    rw [ht]
    exact (Set.ncard_image_le G.finite_toSet).trans (by simp)
  have h1 : ringKrullDim P ≤ ringKrullDim (P ⧸ I) := by
    rw [← IsRegularLocalRing.spanFinrank_maximalIdeal (R := P),
      ← IsRegularLocalRing.spanFinrank_maximalIdeal (R := P ⧸ I)]
    exact_mod_cast hspanFin
  by_contra hne
  obtain ⟨r, hrI, hr0⟩ : ∃ r ∈ I, r ≠ 0 := by
    by_contra hcon
    push Not at hcon
    exact hne (le_bot_iff.mp fun x hx => hcon x hx)
  haveI : IsDomain P := GaloisRepresentation.Modularity.isDomain_of_isRegularLocalRing P
  have h2 : ringKrullDim (P ⧸ I) + 1 ≤ ringKrullDim P :=
    ringKrullDim_succ_le_of_surjective f hfsurj (mem_nonZeroDivisors_of_ne_zero hr0)
      (by rw [hf]; exact (Ideal.Quotient.eq_zero_iff_mem).mpr hrI)
  have h3 : ringKrullDim (P ⧸ I) + 1 ≤ ringKrullDim (P ⧸ I) := h2.trans h1
  rw [← IsRegularLocalRing.spanFinrank_maximalIdeal (R := P ⧸ I)] at h3
  set d := (IsLocalRing.maximalIdeal (P ⧸ I)).spanFinrank with hd
  rw [← Nat.cast_one, ← Nat.cast_add] at h3
  exact absurd (by exact_mod_cast h3 : d + 1 ≤ d) (by omega)

/-- **THE KEY IDEAL-THEORETIC FACT, IN ITS INDUCTIVE FORM** (PROVEN 2026-07-28).

For `P` regular local and `I ≤ 𝔪_P` with `P ⧸ I` regular local,
`I ∩ 𝔪_P² = 𝔪_P I` — which is exactly "`I` is generated by part of a regular
system of parameters", stated without ever naming the parameters.

THE PROOF is induction on `n ≥ spanFinrank 𝔪_P`, and it is the reason no list
of parameters has to be constructed at all:

* if `I ≤ 𝔪_P²` then `I = ⊥` by
  `eq_bot_of_le_sq_of_isRegularLocalRing_quotient` and there is nothing to prove;
* otherwise pick `y ∈ I ∖ 𝔪_P²`.  Then `Q := P ⧸ (y)` is regular local
  (`GaloisRepresentation.Modularity.isRegularLocalRing_quotient_span_singleton`)
  and its embedding dimension has DROPPED, because `P` is a domain, `y ≠ 0` and
  `ringKrullDim_quotient_succ_le_of_nonZeroDivisor` gives `dim Q + 1 ≤ dim P`.
  Also `Q ⧸ IQ ≅ P ⧸ I` is regular local (`DoubleQuot.quotQuotEquivQuotSup`,
  using `(y) ⊔ I = I`), so the inductive hypothesis applies to `IQ = I·Q`.
  Given `x ∈ I ∩ 𝔪_P²`, its image lies in `IQ ∩ 𝔪_Q² ≤ 𝔪_Q IQ = (𝔪_P I)·Q`, so
  `x = z + p y` with `z ∈ 𝔪_P I`.  Then `p y = x − z ∈ 𝔪_P²`, so `p` cannot be a
  unit — else `y ∈ 𝔪_P²` — hence `p ∈ 𝔪_P` and `p y ∈ 𝔪_P I`. -/
theorem inf_sq_le_mul_of_isRegularLocalRing_aux :
    ∀ (n : ℕ) (P : Type u) [CommRing P] [IsRegularLocalRing P] (I : Ideal P),
      (IsLocalRing.maximalIdeal P).spanFinrank ≤ n →
      I ≤ IsLocalRing.maximalIdeal P →
      IsRegularLocalRing (P ⧸ I) →
      I ⊓ (IsLocalRing.maximalIdeal P) ^ 2 ≤ (IsLocalRing.maximalIdeal P) * I := by
  intro n
  induction n with
  | zero =>
    intro P _ _ I hspan hIm hreg
    have hm : IsLocalRing.maximalIdeal P = ⊥ :=
      (Submodule.spanFinrank_eq_zero_iff_eq_bot (IsNoetherian.noetherian _)).1
        (Nat.le_zero.mp hspan)
    have hIbot : I = ⊥ := le_bot_iff.mp (hm ▸ hIm)
    rw [hIbot]
    simp
  | succ n ih =>
    intro P _ _ I hspan hIm hreg
    by_cases hsub : I ≤ (IsLocalRing.maximalIdeal P) ^ 2
    · have hIbot : I = ⊥ := eq_bot_of_le_sq_of_isRegularLocalRing_quotient I hsub
      rw [hIbot]
      simp
    · obtain ⟨y, hyI, hy2⟩ := SetLike.not_le_iff_exists.mp hsub
      have hym : y ∈ IsLocalRing.maximalIdeal P := hIm hyI
      haveI hQreg : IsRegularLocalRing (P ⧸ Ideal.span {y}) :=
        GaloisRepresentation.Modularity.isRegularLocalRing_quotient_span_singleton hym hy2
      haveI : IsDomain P := GaloisRepresentation.Modularity.isDomain_of_isRegularLocalRing P
      have hy0 : y ≠ 0 := fun h => hy2 (h ▸ Ideal.zero_mem _)
      set g : P →+* P ⧸ Ideal.span {y} := Ideal.Quotient.mk (Ideal.span {y}) with hg
      have hgsurj : Function.Surjective g := Ideal.Quotient.mk_surjective
      have hmaxQ : (IsLocalRing.maximalIdeal P).map g
          = IsLocalRing.maximalIdeal (P ⧸ Ideal.span {y}) :=
        IsLocalRing.map_maximalIdeal_of_surjective _ hgsurj
      -- the embedding dimension drops
      have hQspan : (IsLocalRing.maximalIdeal (P ⧸ Ideal.span {y})).spanFinrank ≤ n := by
        have hkey := ringKrullDim_quotient_succ_le_of_nonZeroDivisor
          (R := P) (mem_nonZeroDivisors_of_ne_zero hy0)
        rw [← IsRegularLocalRing.spanFinrank_maximalIdeal (R := P ⧸ Ideal.span {y}),
          ← IsRegularLocalRing.spanFinrank_maximalIdeal (R := P), ← Nat.cast_one,
          ← Nat.cast_add] at hkey
        have hkey' : (IsLocalRing.maximalIdeal (P ⧸ Ideal.span {y})).spanFinrank + 1 ≤
            (IsLocalRing.maximalIdeal P).spanFinrank := by exact_mod_cast hkey
        omega
      -- the ideal downstairs
      set IQ : Ideal (P ⧸ Ideal.span {y}) := I.map g with hIQ
      have hIQm : IQ ≤ IsLocalRing.maximalIdeal (P ⧸ Ideal.span {y}) := by
        rw [hIQ, ← hmaxQ]
        exact Ideal.map_mono hIm
      have hsupeq : Ideal.span {y} ⊔ I = I :=
        sup_eq_right.mpr (by rw [Ideal.span_le]; simpa using hyI)
      haveI : IsRegularLocalRing ((P ⧸ Ideal.span {y}) ⧸ IQ) :=
        IsRegularLocalRing.of_ringEquiv
          (((DoubleQuot.quotQuotEquivQuotSup (Ideal.span {y}) I).trans
            (Ideal.quotEquivOfEq hsupeq)).symm)
      have hIH := ih (P ⧸ Ideal.span {y}) IQ hQspan hIQm inferInstance
      -- the descent
      intro x hx
      obtain ⟨hxI, hx2⟩ := hx
      have hgx : g x ∈ IQ ⊓ (IsLocalRing.maximalIdeal (P ⧸ Ideal.span {y})) ^ 2 := by
        refine ⟨Ideal.mem_map_of_mem _ hxI, ?_⟩
        rw [← hmaxQ, ← Ideal.map_pow]
        exact Ideal.mem_map_of_mem _ hx2
      have hmapmul : IsLocalRing.maximalIdeal (P ⧸ Ideal.span {y}) * IQ
          = (IsLocalRing.maximalIdeal P * I).map g := by
        rw [Ideal.map_mul, hmaxQ, hIQ]
      have hmem : g x ∈ (IsLocalRing.maximalIdeal P * I).map g := by
        rw [← hmapmul]; exact hIH hgx
      have hx' : x ∈ (IsLocalRing.maximalIdeal P * I) ⊔ Ideal.span {y} := by
        have h2 : x ∈ Ideal.comap g ((IsLocalRing.maximalIdeal P * I).map g) := hmem
        have hkerg : Ideal.comap g (⊥ : Ideal (P ⧸ Ideal.span {y})) = Ideal.span {y} :=
          Ideal.mk_ker
        rwa [Ideal.comap_map_of_surjective g hgsurj, hkerg] at h2
      obtain ⟨z, hz, w, hw, rfl⟩ := Submodule.mem_sup.mp hx'
      obtain ⟨p, rfl⟩ := Ideal.mem_span_singleton'.mp hw
      have hz2 : z ∈ (IsLocalRing.maximalIdeal P) ^ 2 := by
        rw [pow_two]
        exact Ideal.mul_mono_right hIm hz
      have hpy2 : p * y ∈ (IsLocalRing.maximalIdeal P) ^ 2 := by
        simpa using Ideal.sub_mem _ hx2 hz2
      have hp : p ∈ IsLocalRing.maximalIdeal P := by
        by_contra hpm
        obtain ⟨u, hu⟩ := (IsLocalRing.notMem_maximalIdeal.mp hpm).exists_left_inv
        refine hy2 ?_
        have hmem2 : u * (p * y) ∈ (IsLocalRing.maximalIdeal P) ^ 2 :=
          Ideal.mul_mem_left _ _ hpy2
        rwa [← mul_assoc, hu, one_mul] at hmem2
      exact Ideal.add_mem _ hz (Ideal.mul_mem_mul hp hyI)

/-- **`I ∩ 𝔪² = 𝔪 I` FOR A REGULAR LOCAL QUOTIENT OF A REGULAR LOCAL RING**
(PROVEN 2026-07-28) — the specialisation of the induction above at
`n = spanFinrank 𝔪_P`. -/
theorem inf_sq_le_mul_of_isRegularLocalRing
    {P : Type u} [CommRing P] [IsRegularLocalRing P] (I : Ideal P)
    (hIm : I ≤ IsLocalRing.maximalIdeal P) [IsRegularLocalRing (P ⧸ I)] :
    I ⊓ (IsLocalRing.maximalIdeal P) ^ 2 ≤ (IsLocalRing.maximalIdeal P) * I :=
  inf_sq_le_mul_of_isRegularLocalRing_aux _ P I le_rfl hIm inferInstance

/-- **THE REGULAR-LOCAL CORE OF ARROW (a)** (PROVEN 2026-07-28): for `P` regular
local and `I ≤ J = 𝔪_P` with `P ⧸ I` regular local, the map
`(P ⧸ 𝔪_P) ⊗_P I → (P ⧸ 𝔪_P) ⊗_P 𝔪_P` is injective.

`J` is carried as a variable with `hJ : J = 𝔪_P` purely so that the caller's
`Submodule.inclusion` — whose second submodule is literally
`RingHom.ker (algebraMap P κ)` — is accepted without a transport; the proof
starts by substituting `hJ`.

THE PROOF identifies both sides with quotients through
`TensorProduct.quotTensorEquivQuotSMul`, which turns the assertion into
injectivity of `I ⧸ 𝔪_P I → 𝔪_P ⧸ 𝔪_P²`; `Submodule.mem_smul_top_iff` unwinds
the submodule-of-a-submodule bookkeeping, and what is left is exactly
`inf_sq_le_mul_of_isRegularLocalRing`. -/
theorem injective_lTensor_quotient_inclusion_of_isRegularLocalRing
    {P : Type u} [CommRing P] [IsRegularLocalRing P] {I J : Ideal P} (hIJ : I ≤ J)
    (hJ : J = IsLocalRing.maximalIdeal P) [IsRegularLocalRing (P ⧸ I)] :
    Function.Injective (LinearMap.lTensor (P ⧸ IsLocalRing.maximalIdeal P)
      (Submodule.inclusion hIJ)) := by
  subst hJ
  set 𝔪 := IsLocalRing.maximalIdeal P with h𝔪
  set g : ↥I →ₗ[P] ↥𝔪 := Submodule.inclusion hIJ with hgdef
  have hgsmul : (𝔪 • ⊤ : Submodule P ↥I) ≤ Submodule.comap g (𝔪 • ⊤ : Submodule P ↥𝔪) := by
    rw [Submodule.map_le_iff_le_comap.symm]
    rw [Submodule.map_smul'']
    exact Submodule.smul_mono le_rfl le_top
  set q := Submodule.mapQ _ _ g hgsmul with hq
  have hnat : ∀ w : (P ⧸ 𝔪) ⊗[P] ↥I,
      (TensorProduct.quotTensorEquivQuotSMul (↥𝔪) 𝔪) (LinearMap.lTensor (P ⧸ 𝔪) g w)
        = q ((TensorProduct.quotTensorEquivQuotSMul (↥I) 𝔪) w) := by
    intro w
    induction w with
    | zero => simp
    | add a b ha hb => simp [ha, hb]
    | tmul a x =>
      obtain ⟨r, rfl⟩ := Ideal.Quotient.mk_surjective a
      simp [hq, Submodule.mapQ_apply, map_smul]
  have hqinj : Function.Injective q := by
    rw [injective_iff_map_eq_zero]
    intro a ha
    induction a using Submodule.Quotient.induction_on with
    | H x =>
      rw [hq, Submodule.mapQ_apply, Submodule.Quotient.mk_eq_zero,
        Submodule.mem_smul_top_iff] at ha
      rw [Submodule.Quotient.mk_eq_zero, Submodule.mem_smul_top_iff]
      have hxI : (x : P) ∈ I := x.2
      have hx2 : (x : P) ∈ 𝔪 ^ 2 := by
        rw [pow_two, ← Ideal.smul_eq_mul]
        exact ha
      rw [Ideal.smul_eq_mul]
      exact inf_sq_le_mul_of_isRegularLocalRing I hIJ ⟨hxI, hx2⟩
  intro u v huv
  apply (TensorProduct.quotTensorEquivQuotSMul (↥I) 𝔪).injective
  apply hqinj
  rw [← hnat, ← hnat, huv]

/-- **ARROW (a): THE KERNEL OF A SURJECTION OF REGULAR LOCAL RINGS IS GENERATED
BY PART OF A REGULAR SYSTEM OF PARAMETERS** (**PROVEN 2026-07-28** — this was the
SOLE remaining residue of Stacks `056S` in this development, and it is now
closed).

**There is no field, no perfectness and no differential module in this
statement.**  That is the point of the cut: arrow (b) of the module docstring —
the half where `PerfectField K` is used — turned out to be FREE at this pin
(see `injective_cotangentComplexBaseChange_of_isRegularLocalRing` below), so
everything characteristic-theoretic is discharged and what is left is a
statement of pure regular-local-ring theory.

Unwinding the tensor products: `κ ⊗_P I = I/𝔪_P I` and
`κ ⊗_P ker(P → κ) = 𝔪_P/𝔪_P²` (the kernel of `P → κ = ResidueField S` is
`𝔪_P`, because `P → S` is a surjection of local rings and hence a local
homomorphism).  So the statement reads

    I/𝔪_P I  ↪  𝔪_P/𝔪_P²,

i.e. a minimal generating set of `I` stays LINEARLY INDEPENDENT modulo `𝔪_P²`,
which is exactly "`I` is generated by part of a regular system of parameters".

**The classical proof, and what this tree already has for it.**  Write
`c = dim P - dim S`.  Since `𝔪_S/𝔪_S² = 𝔪_P/(𝔪_P² + I)` has dimension `dim S`
(regularity of `S`) and `𝔪_P/𝔪_P²` has dimension `dim P` (regularity of `P`),
the image of `I` in `𝔪_P/𝔪_P²` has dimension exactly `c`.  Choose `f₁,…,f_c ∈ I`
lifting a basis of that image.  Then `P/(f₁,…,f_c)` is regular local of
dimension `dim P - c = dim S`, hence a DOMAIN, and it surjects onto `P/I = S`,
also of dimension `dim S`; a surjection of domains of equal dimension has zero
kernel, so `I = (f₁,…,f_c)`.  Hence `I/𝔪_P I` has dimension at most `c` and
surjects onto the `c`-dimensional image, so the map is injective.

**HOW IT WAS ACTUALLY PROVEN — no regular system of parameters is ever
constructed.**  The classical argument above chooses `f₁,…,f_c`, quotients by
them and compares dimensions.  Carrying that list through Lean costs a list
induction, a linear-independence transfer into `𝔪_P/𝔪_P²`, and the
`isRegularLocalRing_quotient_span_list_aux` engine.  All of it is avoidable:
the statement `I ∩ 𝔪_P² ⊆ 𝔪_P I` — which is what the tensor formulation
unwinds to — can be proven by induction on the embedding dimension
`spanFinrank 𝔪_P`, peeling **one** element `y ∈ I ∖ 𝔪_P²` at a time and
descending to `P ⧸ (y)`, which is again regular local with `P ⧸ (y) ⧸ I` again
regular local.  Only the SINGLETON quotient lemma is needed, never the list
one.  See `inf_sq_le_mul_of_isRegularLocalRing_aux` above.

The three inputs used, all PROVEN and sorry-free in
`Fermat/FLT/Modularity/RegularStalks.lean` (a module with no `Fermat` imports,
so importing it here creates no cycle — which is what this file now does):

* `GaloisRepresentation.Modularity.isRegularLocalRing_quotient_span_singleton`
  (quotient by ONE element of `𝔪 ∖ 𝔪²` is regular local),
* `GaloisRepresentation.Modularity.isDomain_of_isRegularLocalRing`,

together with mathlib's `ringKrullDim_quotient_succ_le_of_nonZeroDivisor`,
`ringKrullDim_succ_le_of_surjective` and Nakayama.  The Steinitz-exchange lemma
and the list induction turned out NOT to be needed.

**Both hypotheses are load-bearing.**  `IsRegularLocalRing S` is what the whole
argument rests on; drop it and the statement is false already for
`P = K[x]_{(x)}`, `S = P/(x²)`, where `I = (x²)` gives a one-dimensional
`I/𝔪_P I` while `x² ∈ 𝔪_P²` maps to `0` in `𝔪_P/𝔪_P²`.  `hsurj` is what makes
`S` a quotient of `P` at all; without it `κ` is not `P/𝔪_P` and the unwinding
above is simply false — it is consumed twice below, once to identify
`ker (P → κ)` with `𝔪_P` and once to transport `IsRegularLocalRing S` to
`IsRegularLocalRing (P ⧸ ker (P → S))`. -/
theorem injective_lTensor_residueField_kerInclusion
    {P S : Type u}
    [CommRing P] [IsRegularLocalRing P]
    [CommRing S] [IsRegularLocalRing S] [Algebra P S]
    (hsurj : Function.Surjective (algebraMap P S))
    (hle : RingHom.ker (algebraMap P S) ≤
      RingHom.ker (algebraMap P (IsLocalRing.ResidueField S))) :
    Function.Injective
      (LinearMap.lTensor (IsLocalRing.ResidueField S) (Submodule.inclusion hle)) := by
  have hsurjκ : Function.Surjective (algebraMap P (IsLocalRing.ResidueField S)) := by
    rw [IsScalarTower.algebraMap_eq P S (IsLocalRing.ResidueField S)]
    exact IsLocalRing.residue_surjective.comp hsurj
  -- `ker (P → κ)` is a maximal ideal of the local ring `P`, hence `𝔪_P`
  have hker : RingHom.ker (algebraMap P (IsLocalRing.ResidueField S))
      = IsLocalRing.maximalIdeal P := by
    haveI hmax : (RingHom.ker (algebraMap P (IsLocalRing.ResidueField S))).IsMaximal :=
      RingHom.ker_isMaximal_of_surjective _ hsurjκ
    exact IsLocalRing.eq_maximalIdeal hmax
  haveI : IsRegularLocalRing (P ⧸ RingHom.ker (algebraMap P S)) :=
    IsRegularLocalRing.of_ringEquiv (RingHom.quotientKerEquivOfSurjective hsurj).symm
  -- `κ ≅ P ⧸ 𝔪_P` as `P`-modules, built by `liftQ` so that the module structures
  -- are the ones `lTensor` already uses (an `AlgEquiv` route times out at `whnf`)
  have hkerL : LinearMap.ker (Algebra.linearMap P (IsLocalRing.ResidueField S))
      = IsLocalRing.maximalIdeal P := hker
  let L : (P ⧸ IsLocalRing.maximalIdeal P) →ₗ[P] IsLocalRing.ResidueField S :=
    Submodule.liftQ _ (Algebra.linearMap P (IsLocalRing.ResidueField S)) hkerL.ge
  have hLsurj : Function.Surjective L := by
    intro z
    obtain ⟨p, rfl⟩ := hsurjκ z
    exact ⟨Submodule.Quotient.mk p, rfl⟩
  have hLinj : Function.Injective L := by
    rw [← LinearMap.ker_eq_bot]
    exact Submodule.ker_liftQ_eq_bot _ _ _ hkerL.le
  let e : (P ⧸ IsLocalRing.maximalIdeal P) ≃ₗ[P] IsLocalRing.ResidueField S :=
    LinearEquiv.ofBijective L ⟨hLinj, hLsurj⟩
  exact injective_lTensor_of_linearEquiv e _
    (injective_lTensor_quotient_inclusion_of_isRegularLocalRing hle hker)

/-- **THE LOCAL JACOBIAN CRITERION'S INJECTIVITY, FOR A REGULAR LOCAL QUOTIENT
OF A REGULAR LOCAL RING OVER A PERFECT FIELD** (PROVEN 2026-07-28 over arrow (a)
above; **arrow (b), the perfectness half, is proven here outright**).

The map `KaehlerDifferential.cotangentComplexBaseChange K S P κ` is
`κ ⊗_P I → κ ⊗_P Ω[P⁄K]`, `I = ker (P → S)`, `κ = ResidueField S`, sending
`a ⊗ f ↦ a • (1 ⊗ d f)`.  It factors, tautologically from that formula, as

    κ ⊗_P I  --(a)-->  κ ⊗_P 𝔪_P  --(b)-->  κ ⊗_P Ω[P⁄K]

where (a) is `lTensor` of the inclusion `I ⊆ 𝔪_P = ker (P → κ)` and (b) is
*the same construction* `cotangentComplexBaseChange` for the presentation
`P ↠ κ` instead of `P ↠ S`.

**ARROW (b) IS FREE, and that is the discovery that shrank this leaf.**  Apply
`Algebra.FormallySmooth.iff_injective_cotangentComplexBaseChange`
(`Mathlib/RingTheory/Smooth/Local.lean`) to the LOCAL ring `κ` — a field, so its
maximal ideal is `⊥` and the criterion's `h₃` is vacuous — with the same
presenting ring `P`.  It says that (b) is injective **iff** `κ` is formally
smooth over `K`, and that is `Algebra.FormallySmooth.of_perfectField`, since `κ`
is essentially of finite type over the perfect field `K`.  So no exact sequence
`𝔪/𝔪² → κ ⊗ Ω → Ω_{κ⁄K} → 0` has to be built by hand: mathlib's own criterion,
read at the residue field, IS that exact sequence's content.

Consequently `PerfectField K`, `Algebra.EssFiniteType K P`,
`Algebra.FormallySmooth K P` and the freeness/finiteness of `Ω[P⁄K]` are all
consumed HERE, and the surviving leaf mentions none of them. -/
theorem injective_cotangentComplexBaseChange_of_isRegularLocalRing
    {K P S : Type u} [Field K] [PerfectField K]
    [CommRing P] [IsRegularLocalRing P] [Algebra K P] [Algebra.EssFiniteType K P]
    [Algebra.FormallySmooth K P] [Module.Free P Ω[P⁄K]] [Module.Finite P Ω[P⁄K]]
    [CommRing S] [IsRegularLocalRing S] [Algebra K S] [Algebra P S] [IsScalarTower K P S]
    (hsurj : Function.Surjective (algebraMap P S)) :
    Function.Injective
      (KaehlerDifferential.cotangentComplexBaseChange K S P (IsLocalRing.ResidueField S)) := by
  have hle : RingHom.ker (algebraMap P S) ≤
      RingHom.ker (algebraMap P (IsLocalRing.ResidueField S)) := by
    intro x hx
    simp only [RingHom.mem_ker] at hx ⊢
    rw [IsScalarTower.algebraMap_apply P S (IsLocalRing.ResidueField S), hx, map_zero]
  -- `P ↠ κ` is surjective, and its kernel is finitely generated because `P` is noetherian.
  have hsurjκ : Function.Surjective (algebraMap P (IsLocalRing.ResidueField S)) := by
    rw [IsScalarTower.algebraMap_eq P S (IsLocalRing.ResidueField S)]
    exact IsLocalRing.residue_surjective.comp hsurj
  have hFGκ : (RingHom.ker (algebraMap P (IsLocalRing.ResidueField S))).FG :=
    IsNoetherian.noetherian (R := P) _
  -- `κ` is essentially of finite type over `K`, hence formally smooth over the perfect `K`.
  haveI : Algebra.EssFiniteType K S := Algebra.EssFiniteType.of_surjective
    (IsScalarTower.toAlgHom K P S) hsurj
  haveI : Algebra.EssFiniteType K (IsLocalRing.ResidueField S) :=
    inferInstanceAs (Algebra.EssFiniteType K (S ⧸ IsLocalRing.maximalIdeal S))
  -- ARROW (b): mathlib's criterion read at the residue field.
  have hb : Function.Injective (KaehlerDifferential.cotangentComplexBaseChange K
      (IsLocalRing.ResidueField S) P (IsLocalRing.ResidueField S)) := by
    refine (Algebra.FormallySmooth.iff_injective_cotangentComplexBaseChange
      (R := K) (S := IsLocalRing.ResidueField S) P (IsLocalRing.ResidueField S)
      hsurjκ hFGκ ?_).mp Algebra.FormallySmooth.of_perfectField
    simp [IsLocalRing.maximalIdeal_eq_bot]
  -- ARROW (a): the surviving leaf.
  have ha := injective_lTensor_residueField_kerInclusion (P := P) (S := S) hsurj hle
  -- The factorization, checked on pure tensors.
  have hfact : ∀ x, KaehlerDifferential.cotangentComplexBaseChange K S P
      (IsLocalRing.ResidueField S) x =
      KaehlerDifferential.cotangentComplexBaseChange K (IsLocalRing.ResidueField S) P
        (IsLocalRing.ResidueField S)
        (LinearMap.lTensor (IsLocalRing.ResidueField S) (Submodule.inclusion hle) x) := by
    intro x
    induction x with
    | zero => simp only [map_zero]
    | add a b ha' hb' => simp only [map_add, ha', hb']
    -- both sides are `a • kerToTensor K P κ ⟨↑b, _⟩` by
    -- `KaehlerDifferential.cotangentComplexBaseChange_tmul`, which is itself `rfl`
    | tmul a b => rfl
  intro x y hxy
  refine ha (hb ?_)
  rw [← hfact, ← hfact]
  exact hxy

/-- **A REGULAR LOCAL QUOTIENT OF A REGULAR LOCAL FORMALLY SMOOTH ALGEBRA OVER A
PERFECT FIELD IS FORMALLY SMOOTH** (PROVEN 2026-07-28 over
`injective_cotangentComplexBaseChange_of_isRegularLocalRing`).

This is the local Jacobian criterion
(`Algebra.FormallySmooth.iff_injective_cotangentComplexBaseChange_residueField`)
applied to the presentation `P ↠ S`; the kernel is finitely generated because
`P` is noetherian (`IsRegularLocalRing` extends `IsNoetherianRing`). -/
theorem FormallySmooth.of_surjective_of_isRegularLocalRing
    {K P S : Type u} [Field K] [PerfectField K]
    [CommRing P] [IsRegularLocalRing P] [Algebra K P] [Algebra.EssFiniteType K P]
    [Algebra.FormallySmooth K P] [Module.Free P Ω[P⁄K]] [Module.Finite P Ω[P⁄K]]
    [CommRing S] [IsRegularLocalRing S] [Algebra K S] [Algebra P S] [IsScalarTower K P S]
    (hsurj : Function.Surjective (algebraMap P S)) :
    Algebra.FormallySmooth K S := by
  have hFG : (RingHom.ker (algebraMap P S)).FG :=
    (IsNoetherian.noetherian (R := P) (RingHom.ker (algebraMap P S)))
  rw [Algebra.FormallySmooth.iff_injective_cotangentComplexBaseChange_residueField P hsurj hFG]
  exact injective_cotangentComplexBaseChange_of_isRegularLocalRing hsurj

/-- **A REGULAR LOCAL RING ESSENTIALLY OF FINITE TYPE OVER A PERFECT FIELD IS
FORMALLY SMOOTH** — Stacks `056S` in its regular-local form (PROVEN 2026-07-28
over `injective_cotangentComplexBaseChange_of_isRegularLocalRing`; the whole
module is now sorry-free).

This is THE statement that four open nodes of this development were each about
to build separately; see the module docstring for the table.  Everything else
here is bookkeeping: the presentation lemma builds `P = K[x₁,…,x_n]_𝔮 ↠ R`, and
`P` is formally smooth over `K` with `Ω[P⁄K]` finite free because it is a
localization of a polynomial ring
(`Algebra.FormallyEtale.of_isLocalization` plus
`KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale`), and regular local
because `MvPolynomial (Fin n) K` is a regular ring. -/
theorem FormallySmooth.of_isRegularLocalRing_of_perfectField
    {K R : Type u} [Field K] [PerfectField K] [CommRing R] [IsRegularLocalRing R]
    [Algebra K R] [Algebra.EssFiniteType K R] :
    Algebra.FormallySmooth K R := by
  obtain ⟨n, q, hq, f, hf⟩ := exists_localizationAtPrime_mvPolynomial_surjective K R
  haveI := hq
  algebraize [f.toRingHom]
  haveI : IsScalarTower K (Localization.AtPrime q) R :=
    IsScalarTower.of_algebraMap_eq' f.comp_algebraMap.symm
  haveI : Algebra.FormallyEtale (MvPolynomial (Fin n) K) (Localization.AtPrime q) :=
    .of_isLocalization q.primeCompl
  haveI : Algebra.FormallySmooth K (Localization.AtPrime q) :=
    .comp _ (MvPolynomial (Fin n) K) _
  haveI : Module.Free (Localization.AtPrime q) Ω[Localization.AtPrime q⁄K] :=
    .of_equiv (KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale K
      (MvPolynomial (Fin n) K) (Localization.AtPrime q))
  haveI : Module.Finite (Localization.AtPrime q) Ω[Localization.AtPrime q⁄K] :=
    .of_surjective (KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale K
      (MvPolynomial (Fin n) K) (Localization.AtPrime q)).toLinearMap
      (LinearEquiv.surjective _)
  exact FormallySmooth.of_surjective_of_isRegularLocalRing
    (K := K) (P := Localization.AtPrime q) (S := R) hf

/-- **A REGULAR RING OF FINITE TYPE OVER A PERFECT FIELD IS SMOOTH** — the
GLOBAL (non-local) form of Stacks `056S` (PROVEN 2026-07-28 over
`FormallySmooth.of_isRegularLocalRing_of_perfectField`; the whole module is
now sorry-free).

The passage from local to global is FREE at this pin and costs no covering
argument: `Algebra.smoothLocus_eq_univ_iff`
(`Mathlib/RingTheory/Smooth/Locus.lean`) says that for a finitely presented
algebra, `FormallySmooth R A` is EQUIVALENT to every localization `A_𝔭` being
formally smooth, and `IsRegularRing B` is by definition the statement that
every `B_𝔭` is regular local.  So the two definitions meet pointwise and the
main theorem above is applied prime by prime.

`Algebra.FiniteType K B` upgrades to `FinitePresentation` for free because `K`
is a field, hence noetherian (`Algebra.FinitePresentation.of_finiteType`). -/
theorem Smooth.of_isRegularRing_of_perfectField
    (K B : Type u) [Field K] [PerfectField K] [CommRing B] [Algebra K B]
    [Algebra.FiniteType K B] [IsRegularRing B] :
    Algebra.Smooth K B := by
  haveI : Algebra.FinitePresentation K B := Algebra.FinitePresentation.of_finiteType.mp inferInstance
  refine ⟨?_, inferInstance⟩
  rw [← Algebra.smoothLocus_eq_univ_iff]
  ext p
  simp only [Set.mem_univ, iff_true]
  show Algebra.FormallySmooth K (Localization.AtPrime p.asIdeal)
  haveI : Algebra.EssFiniteType B (Localization.AtPrime p.asIdeal) :=
    .of_isLocalization _ p.asIdeal.primeCompl
  haveI : Algebra.EssFiniteType K (Localization.AtPrime p.asIdeal) := .comp _ B _
  exact FormallySmooth.of_isRegularLocalRing_of_perfectField

end Algebra
