/-
Fermat/FLT/Mathlib/RingTheory/Smooth/RegularLocal.lean — own work for the
Fermat project (not vendored from the FLT project).

# Regular ⟹ formally smooth over a perfect field (Stacks `056S`), in its
# regular-LOCAL form

This module states, **once**, the commutative-algebra fact that at least four
open nodes of this development were each about to build separately:

> a **regular local** ring essentially of finite type over a **perfect** field
> is **formally smooth** over that field.

That is `Algebra.FormallySmooth.of_isRegularLocalRing_of_perfectField` below.
The four consumers, all of which now go through it, are

| node | file |
|---|---|
| `formallySmooth_of_isDiscreteValuationRing_of_perfectField` | `Fermat/FLT/Mathlib/AlgebraicGeometry/CurveExtension.lean` |
| `smoothOfRelativeDimension_specMap_algebraMap_of_isRegularRing` | `Fermat/FLT/Mathlib/AlgebraicGeometry/SmoothConnectedCriteria.lean` |
| `smoothOfRelativeDimension_of_gamma0GITPresentation` | `Fermat/FLT/ModularCurve/X0.lean` (already a theorem over the previous row) |
| `smoothOfRelativeDimension_one_fromNormalization` | `Fermat/FLT/Mathlib/AlgebraicGeometry/CurveCompactification.lean` (already a theorem over the first row) |

**This module has no `Fermat` imports**, deliberately: like
`Fermat/FLT/Modularity/RegularStalks.lean` (which carries the CONVERSE,
`isRegularLocalRing_stalk_of_smooth_over_field`, sorry-free) it is importable
from anywhere in the tree, including the mathlib-shim modules.

## The cut

The statement is proven over exactly two named pieces:

* `Algebra.exists_localizationAtPrime_mvPolynomial_surjective` — **PROVEN
  here**.  A local ring essentially of finite type over a field `K` is a
  quotient of a localization of a polynomial ring `K[x₁,…,x_n]` at a prime.
  This is the presentation bookkeeping and contains no mathematics; it is
  modelled on the presentation built inside mathlib's
  `Algebra.FormallySmooth.of_formallySmooth_residueField_tensor`
  (`Mathlib/RingTheory/Smooth/Fiber.lean`), simplified by the fact that our
  base is a field and our target is local, so the localization can be taken at
  a prime and is itself regular local and noetherian.
* `Algebra.injective_cotangentComplexBaseChange_of_isRegularLocalRing` — **PROVEN
  here** over arrow (a) below.  It is the injectivity that the local Jacobian
  criterion asks for, and it splits into the two arrows (a) and (b) described
  next; **arrow (b), the one that uses `PerfectField`, is proven outright**.
* `Algebra.injective_lTensor_residueField_kerInclusion` — the **one sorry leaf**,
  i.e. arrow (a) alone.  It mentions no field, no perfectness and no module of
  differentials: it says only that for a surjection `P ↠ S` of REGULAR LOCAL
  rings the map `I/𝔪_P I → 𝔪_P/𝔪_P²` is injective, i.e. that `I` is generated by
  part of a regular system of parameters.

## What the sorry leaf says, and the classical proof of it

`Algebra.FormallySmooth.iff_injective_cotangentComplexBaseChange_residueField`
(`Mathlib/RingTheory/Smooth/Local.lean`) is the **local Jacobian criterion**:
for a presentation `0 → I → P → S → 0` of a LOCAL ring `S` with `P` formally
smooth over `K`, `Ω[P⁄K]` finite free and `I` finitely generated,

    FormallySmooth K S  ↔  κ ⊗_S I/I² → κ ⊗_P Ω[P⁄K]  is injective,

`κ = ResidueField S`.  Taking `P = K[x]_𝔮` (which is what the presentation
lemma supplies), the map factors — by Leibniz, `d f mod 𝔪_P` depends only on
`f mod 𝔪_P²` — as

    κ ⊗_S I/I²  =  I/𝔪_P I  --(a)-->  𝔪_P/𝔪_P²  --(b)-->  κ ⊗_P Ω[P⁄K]

and the two arrows are injective for two different reasons:

* **(a) is regularity.**  `P` is regular local and `S = P/I` is regular local,
  so with `c = dim P - dim S`: pick `f₁,…,f_c ∈ I` whose classes are a basis of
  `(I + 𝔪_P²)/𝔪_P²` (there are exactly `c` of them because
  `𝔪_S/𝔪_S² = 𝔪_P/(𝔪_P² + I)` has dimension `dim S`).  Then `P/(f₁,…,f_c)` is
  regular local of dimension `dim S`, hence a DOMAIN, and it surjects onto
  `P/I = S`, also of dimension `dim S`; a surjection of domains of equal
  dimension over a catenary ring is an isomorphism, so `I = (f₁,…,f_c)`.
  Therefore `I/𝔪_P I` has dimension at most `c` and surjects onto the
  `c`-dimensional `(I + 𝔪_P²)/𝔪_P²`, so (a) is injective.
  **The quotient step is already available in this tree**: the list induction
  `GaloisRepresentation.Modularity.isRegularLocalRing_quotient_span_list_aux`
  and its base case `isRegularLocalRing_quotient_span_singleton`
  (`Fermat/FLT/Modularity/RegularStalks.lean`, both PROVEN, both sorry-free)
  are exactly "quotient by part of a regular system of parameters is regular
  local", and `isDomain_of_isRegularLocalRing` is there too.  Note that
  RegularStalks.lean may not be imported from here without making this module
  Fermat-dependent; a prover closing this leaf should either move those three
  declarations further upstream or import them.
* **(b) is PERFECTNESS, and it is PROVEN below — FOR FREE.**  For a local
  `K`-algebra `P` with residue field `κ` there is an exact sequence
  `𝔪_P/𝔪_P² --δ--> κ ⊗_P Ω[P⁄K] → Ω[κ⁄K] → 0`, and `δ` is injective **iff** `κ`
  is formally smooth over `K` (Matsumura, *CRT* Thm 25.2 / §28).  That sequence
  does **not** have to be built: arrow (b) is literally
  `cotangentComplexBaseChange` for the presentation `P ↠ κ` instead of `P ↠ S`,
  so mathlib's own
  `Algebra.FormallySmooth.iff_injective_cotangentComplexBaseChange`, read at the
  local ring `κ` (a field, so the criterion's `h₃` is vacuous), makes (b)
  equivalent to `Algebra.FormallySmooth K κ` — which is
  `Algebra.FormallySmooth.of_perfectField`
  (`Mathlib/RingTheory/Smooth/Field.lean`), since `κ` is essentially of finite
  type over the perfect `K`.  Equivalently `H₁(L_{κ⁄K}) = 0`, the vanishing that
  fails over an imperfect base.

## Faithfulness

`PerfectField K` is load-bearing and the statement is FALSE without it.  Over
an imperfect field `k = 𝔽_p(t)` the ring
`R = k[x,y]_{(x,y)}/(y^p - t x^p - t)` is a regular local ring (indeed a DVR)
essentially of finite type over `k` which is NOT formally smooth over `k`: its
residue field contains `t^{1/p}` and is purely inseparable over `k`, so
`H₁(L_{κ⁄k}) ≠ 0` and arrow (b) above fails.  This is the standard
quasi-elliptic counterexample, and it is exactly why the leaf below cannot be
proven without the perfectness hypothesis entering at (b).

`Algebra.EssFiniteType K R` is load-bearing too — it is what supplies the
presentation at all, and what makes `κ` finitely generated over `K` so that
`of_perfectField` applies.  A regular local ring that is merely a `K`-algebra
need not be formally smooth (e.g. a complete DVR of mixed characteristic is
not formally smooth over its residue field in the non-perfect case).

*Refute the main statement with*: a regular local ring, essentially of finite
type over a PERFECT field, that is not formally smooth over it.  There is none
(Stacks `056S`); over an imperfect field there are, and one is displayed above.
-/
module

public import Mathlib.RingTheory.EssentialFiniteness
public import Mathlib.RingTheory.Etale.Kaehler
public import Mathlib.RingTheory.Kaehler.Polynomial
public import Mathlib.RingTheory.Localization.AtPrime.Basic
public import Mathlib.RingTheory.RegularLocalRing.Polynomial
public import Mathlib.RingTheory.Smooth.Field
public import Mathlib.RingTheory.Smooth.Local
public import Mathlib.RingTheory.Smooth.Locus

@[expose] public section

open TensorProduct

universe u

namespace Algebra

/-- **A LOCAL RING ESSENTIALLY OF FINITE TYPE OVER A FIELD IS A QUOTIENT OF A
LOCALIZED POLYNOMIAL RING AT A PRIME** (PROVEN 2026-07-28).

This is the presentation half of `FormallySmooth.of_isRegularLocalRing_of_perfectField`
and contains no mathematics beyond bookkeeping.  `Algebra.EssFiniteType` gives a
finite-type `K`-subalgebra `A ⊆ R` with `R` a localization of `A`; a surjection
`K[x₁,…,x_n] ↠ A` then composes to `g : K[x₁,…,x_n] → R`, and `𝔮 := g⁻¹(𝔪_R)`
is a prime whose complement `g` sends to units, so `g` extends over
`K[x₁,…,x_n]_𝔮`.  Surjectivity is `IsLocalization.lift_surjective_iff`: every
`r ∈ R` is `a/m` with `a, m` coming from `K[x₁,…,x_n]` and `m` a unit in `R`,
hence outside `𝔮`.

The point of localizing **at a prime** rather than at an arbitrary submonoid
(which is what mathlib's `Smooth/Fiber.lean` does) is that the resulting `P` is
itself LOCAL, NOETHERIAN and REGULAR LOCAL, which is what the Jacobian-criterion
step needs. -/
theorem exists_localizationAtPrime_mvPolynomial_surjective
    (K R : Type u) [Field K] [CommRing R] [IsLocalRing R] [Algebra K R]
    [Algebra.EssFiniteType K R] :
    ∃ (n : ℕ) (q : Ideal (MvPolynomial (Fin n) K)) (_ : q.IsPrime)
      (f : Localization.AtPrime q →ₐ[K] R), Function.Surjective f := by
  classical
  obtain ⟨n, f₀, hf₀⟩ := Algebra.FiniteType.iff_quotient_mvPolynomial''.mp
    (inferInstance : Algebra.FiniteType K (Algebra.EssFiniteType.subalgebra K R))
  set g : MvPolynomial (Fin n) K →ₐ[K] R :=
    (IsScalarTower.toAlgHom K (Algebra.EssFiniteType.subalgebra K R) R).comp f₀ with hgdef
  set q : Ideal (MvPolynomial (Fin n) K) :=
    Ideal.comap g.toRingHom (IsLocalRing.maximalIdeal R) with hqdef
  have hqp : q.IsPrime := Ideal.comap_isPrime _ _
  haveI := hqp
  have hunit : ∀ y : q.primeCompl, IsUnit (g y) := by
    rintro ⟨y, hy⟩
    refine IsLocalRing.notMem_maximalIdeal.mp fun h ↦ hy ?_
    exact Ideal.mem_comap.mpr h
  refine ⟨n, q, hqp, IsLocalization.liftAlgHom (M := q.primeCompl) (f := g) hunit, ?_⟩
  show Function.Surjective (IsLocalization.lift (M := q.primeCompl) (g := g.toRingHom) hunit)
  rw [IsLocalization.lift_surjective_iff]
  intro v
  obtain ⟨⟨a, m⟩, hv⟩ := IsLocalization.mk'_surjective
    (Algebra.EssFiniteType.submonoid K R) v
  obtain ⟨x, rfl⟩ := hf₀ a
  obtain ⟨s, hs⟩ := hf₀ (m : Algebra.EssFiniteType.subalgebra K R)
  have hgs : g s = algebraMap (Algebra.EssFiniteType.subalgebra K R) R m := by
    rw [hgdef]; simp [hs]
  have hsq : s ∈ q.primeCompl := by
    intro hmem
    exact (IsLocalRing.notMem_maximalIdeal.mpr
      (hgs ▸ IsLocalization.map_units R m)) (Ideal.mem_comap.mp hmem)
  refine ⟨⟨x, ⟨s, hsq⟩⟩, ?_⟩
  have hv' : IsLocalization.mk' R (f₀ x) m = v := hv
  have hspec := IsLocalization.mk'_spec (M := Algebra.EssFiniteType.submonoid K R) R
    (f₀ x) m
  rw [hv'] at hspec
  simpa [hgs, hgdef, hs] using hspec

/-- **ARROW (a): THE KERNEL OF A SURJECTION OF REGULAR LOCAL RINGS IS GENERATED
BY PART OF A REGULAR SYSTEM OF PARAMETERS** (sorry leaf, opened 2026-07-28 — the
SOLE remaining residue of Stacks `056S` in this development).

**There is no field, no perfectness and no differential module in this
statement.**  That is the point of the cut: arrow (b) of the module docstring —
the half where `PerfectField K` is used — turned out to be FREE at this pin
(see `injective_cotangentComplexBaseChange_of_isRegularLocalRing` below), so
everything characteristic-theoretic is discharged and what is left is a
statement of pure regular-local-ring theory.

Unwinding the tensor products: `κ ⊗_P I = I/𝔪_P I` and
`κ ⊗_P ker(P → κ) = 𝔪_P/𝔪_P²` (the kernel of `P → κ = ResidueField S` is
`𝔪_P`, because `P → S` is a surjection of local rings and hence a local
homomorphism).  So the statement reads

    I/𝔪_P I  ↪  𝔪_P/𝔪_P²,

i.e. a minimal generating set of `I` stays LINEARLY INDEPENDENT modulo `𝔪_P²`,
which is exactly "`I` is generated by part of a regular system of parameters".

**The classical proof, and what this tree already has for it.**  Write
`c = dim P - dim S`.  Since `𝔪_S/𝔪_S² = 𝔪_P/(𝔪_P² + I)` has dimension `dim S`
(regularity of `S`) and `𝔪_P/𝔪_P²` has dimension `dim P` (regularity of `P`),
the image of `I` in `𝔪_P/𝔪_P²` has dimension exactly `c`.  Choose `f₁,…,f_c ∈ I`
lifting a basis of that image.  Then `P/(f₁,…,f_c)` is regular local of
dimension `dim P - c = dim S`, hence a DOMAIN, and it surjects onto `P/I = S`,
also of dimension `dim S`; a surjection of domains of equal dimension has zero
kernel, so `I = (f₁,…,f_c)`.  Hence `I/𝔪_P I` has dimension at most `c` and
surjects onto the `c`-dimensional image, so the map is injective.

Both nontrivial inputs are ALREADY PROVEN, sorry-free, in this repository, in
`Fermat/FLT/Modularity/RegularStalks.lean`:

* `GaloisRepresentation.Modularity.exists_finset_card_span_insert_eq_maximalIdeal`
  (Steinitz exchange: an element of `𝔪 ∖ 𝔪²` belongs to a minimal generating
  set of `𝔪`),
* `GaloisRepresentation.Modularity.isRegularLocalRing_quotient_span_singleton`
  and `…_quotient_span_list_aux` (quotient by part of a regular system of
  parameters is regular local),
* `GaloisRepresentation.Modularity.isDomain_of_isRegularLocalRing`.

That module has NO `Fermat` imports either, so a prover closing this leaf can
import it here without creating a cycle, or hoist the four declarations.

**The MATHLIB half of that proof, name by name, each type-checked against this
pin on 2026-07-28 before being written down.**  The three project lemmas above
cover the regular-local bookkeeping; these cover everything else, and none of it
needs building:

* Turning both tensor products into dimensions:
  `Module.finrank_eq_spanFinrank_of_free` composed with
  `TensorProduct.spanFinrank_top_eq_of_residueField`
  (`Mathlib/Algebra/Module/SpanRankOperations.lean`) gives, in two lines,
  `Module.finrank κ (κ ⊗[P] N) = N.spanFinrank` for any finitely generated `N`
  over a local ring.  There is no lemma under that name — this composite IS the
  bridge, and it is what makes "`I/𝔪_P I` has dimension `spanFinrank I`" a
  rewrite rather than a development.
* The two dimension bounds: `IsRegularLocalRing.spanFinrank_maximalIdeal` is the
  definitional `(𝔪).spanFinrank = ringKrullDim` (usable through `exact_mod_cast`,
  since `ringKrullDim` lands in `WithBot ℕ∞`), and for a quotient that is *not
  yet known* regular the inequality is
  `ringKrullDim_le_spanFinrank_maximalIdeal`.
* "A surjection of domains of equal dimension has zero kernel" needs NO
  hand-rolled height argument: `ringKrullDim_quotient_add_one_of_mem_nonZeroDivisors`
  (`Mathlib/RingTheory/KrullDimension/Regular.lean`) says
  `dim (R ⧸ span {r}) + 1 = dim R` for `r` a nonzerodivisor in `𝔪`, and in a
  domain every nonzero element qualifies; so a nonzero kernel would strictly drop
  the dimension.
* Monotonicity of `ringKrullDim` along `P ⧸ I' ↠ P ⧸ I` is
  `ringKrullDim_le_of_surjective` / `ringKrullDim_quotient_le`
  (`Mathlib/RingTheory/KrullDimension/Basic.lean`) applied to
  `Ideal.Quotient.factor`; there is no `ringKrullDim (P ⧸ J) ≤ ringKrullDim (P ⧸ I)`
  under any name, and `exact?` fails on it, so do not hunt for one.
* Finally, `ringKrullDim_le_ringKrullDim_add_spanFinrank` (same file) is the EASY
  direction `dim P ≤ dim S + spanFinrank I` — i.e. precisely the inequality this
  leaf does *not* need.  Reaching for it is the natural wrong turn here.

**Both hypotheses are load-bearing.**  `IsRegularLocalRing S` is what the whole
argument rests on; drop it and the statement is false already for
`P = K[x]_{(x)}`, `S = P/(x²)`, where `I = (x²)` gives a one-dimensional
`I/𝔪_P I` while `x² ∈ 𝔪_P²` maps to `0` in `𝔪_P/𝔪_P²`.  `_hsurj` is what makes
`S` a quotient of `P` at all; without it `κ` is not `P/𝔪_P` and the unwinding
above is simply false. -/
theorem injective_lTensor_residueField_kerInclusion
    {P S : Type u}
    [CommRing P] [IsRegularLocalRing P]
    [CommRing S] [IsRegularLocalRing S] [Algebra P S]
    (_hsurj : Function.Surjective (algebraMap P S))
    (hle : RingHom.ker (algebraMap P S) ≤
      RingHom.ker (algebraMap P (IsLocalRing.ResidueField S))) :
    Function.Injective
      (LinearMap.lTensor (IsLocalRing.ResidueField S) (Submodule.inclusion hle)) :=
  sorry

/-- **THE LOCAL JACOBIAN CRITERION'S INJECTIVITY, FOR A REGULAR LOCAL QUOTIENT
OF A REGULAR LOCAL RING OVER A PERFECT FIELD** (PROVEN 2026-07-28 over arrow (a)
above; **arrow (b), the perfectness half, is proven here outright**).

The map `KaehlerDifferential.cotangentComplexBaseChange K S P κ` is
`κ ⊗_P I → κ ⊗_P Ω[P⁄K]`, `I = ker (P → S)`, `κ = ResidueField S`, sending
`a ⊗ f ↦ a • (1 ⊗ d f)`.  It factors, tautologically from that formula, as

    κ ⊗_P I  --(a)-->  κ ⊗_P 𝔪_P  --(b)-->  κ ⊗_P Ω[P⁄K]

where (a) is `lTensor` of the inclusion `I ⊆ 𝔪_P = ker (P → κ)` and (b) is
*the same construction* `cotangentComplexBaseChange` for the presentation
`P ↠ κ` instead of `P ↠ S`.

**ARROW (b) IS FREE, and that is the discovery that shrank this leaf.**  Apply
`Algebra.FormallySmooth.iff_injective_cotangentComplexBaseChange`
(`Mathlib/RingTheory/Smooth/Local.lean`) to the LOCAL ring `κ` — a field, so its
maximal ideal is `⊥` and the criterion's `h₃` is vacuous — with the same
presenting ring `P`.  It says that (b) is injective **iff** `κ` is formally
smooth over `K`, and that is `Algebra.FormallySmooth.of_perfectField`, since `κ`
is essentially of finite type over the perfect field `K`.  So no exact sequence
`𝔪/𝔪² → κ ⊗ Ω → Ω_{κ⁄K} → 0` has to be built by hand: mathlib's own criterion,
read at the residue field, IS that exact sequence's content.

Consequently `PerfectField K`, `Algebra.EssFiniteType K P`,
`Algebra.FormallySmooth K P` and the freeness/finiteness of `Ω[P⁄K]` are all
consumed HERE, and the surviving leaf mentions none of them. -/
theorem injective_cotangentComplexBaseChange_of_isRegularLocalRing
    {K P S : Type u} [Field K] [PerfectField K]
    [CommRing P] [IsRegularLocalRing P] [Algebra K P] [Algebra.EssFiniteType K P]
    [Algebra.FormallySmooth K P] [Module.Free P Ω[P⁄K]] [Module.Finite P Ω[P⁄K]]
    [CommRing S] [IsRegularLocalRing S] [Algebra K S] [Algebra P S] [IsScalarTower K P S]
    (hsurj : Function.Surjective (algebraMap P S)) :
    Function.Injective
      (KaehlerDifferential.cotangentComplexBaseChange K S P (IsLocalRing.ResidueField S)) := by
  have hle : RingHom.ker (algebraMap P S) ≤
      RingHom.ker (algebraMap P (IsLocalRing.ResidueField S)) := by
    intro x hx
    simp only [RingHom.mem_ker] at hx ⊢
    rw [IsScalarTower.algebraMap_apply P S (IsLocalRing.ResidueField S), hx, map_zero]
  -- `P ↠ κ` is surjective, and its kernel is finitely generated because `P` is noetherian.
  have hsurjκ : Function.Surjective (algebraMap P (IsLocalRing.ResidueField S)) := by
    rw [IsScalarTower.algebraMap_eq P S (IsLocalRing.ResidueField S)]
    exact IsLocalRing.residue_surjective.comp hsurj
  have hFGκ : (RingHom.ker (algebraMap P (IsLocalRing.ResidueField S))).FG :=
    IsNoetherian.noetherian (R := P) _
  -- `κ` is essentially of finite type over `K`, hence formally smooth over the perfect `K`.
  haveI : Algebra.EssFiniteType K S := Algebra.EssFiniteType.of_surjective
    (IsScalarTower.toAlgHom K P S) hsurj
  haveI : Algebra.EssFiniteType K (IsLocalRing.ResidueField S) :=
    inferInstanceAs (Algebra.EssFiniteType K (S ⧸ IsLocalRing.maximalIdeal S))
  -- ARROW (b): mathlib's criterion read at the residue field.
  have hb : Function.Injective (KaehlerDifferential.cotangentComplexBaseChange K
      (IsLocalRing.ResidueField S) P (IsLocalRing.ResidueField S)) := by
    refine (Algebra.FormallySmooth.iff_injective_cotangentComplexBaseChange
      (R := K) (S := IsLocalRing.ResidueField S) P (IsLocalRing.ResidueField S)
      hsurjκ hFGκ ?_).mp Algebra.FormallySmooth.of_perfectField
    simp [IsLocalRing.maximalIdeal_eq_bot]
  -- ARROW (a): the surviving leaf.
  have ha := injective_lTensor_residueField_kerInclusion (P := P) (S := S) hsurj hle
  -- The factorization, checked on pure tensors.
  have hfact : ∀ x, KaehlerDifferential.cotangentComplexBaseChange K S P
      (IsLocalRing.ResidueField S) x =
      KaehlerDifferential.cotangentComplexBaseChange K (IsLocalRing.ResidueField S) P
        (IsLocalRing.ResidueField S)
        (LinearMap.lTensor (IsLocalRing.ResidueField S) (Submodule.inclusion hle) x) := by
    intro x
    induction x with
    | zero => simp
    | add a b ha' hb' => simp [ha', hb']
    | tmul a b => simp [KaehlerDifferential.cotangentComplexBaseChange_tmul]
  intro x y hxy
  refine ha (hb ?_)
  rw [← hfact, ← hfact]
  exact hxy

/-- **A REGULAR LOCAL QUOTIENT OF A REGULAR LOCAL FORMALLY SMOOTH ALGEBRA OVER A
PERFECT FIELD IS FORMALLY SMOOTH** (PROVEN 2026-07-28 over
`injective_cotangentComplexBaseChange_of_isRegularLocalRing`).

This is the local Jacobian criterion
(`Algebra.FormallySmooth.iff_injective_cotangentComplexBaseChange_residueField`)
applied to the presentation `P ↠ S`; the kernel is finitely generated because
`P` is noetherian (`IsRegularLocalRing` extends `IsNoetherianRing`). -/
theorem FormallySmooth.of_surjective_of_isRegularLocalRing
    {K P S : Type u} [Field K] [PerfectField K]
    [CommRing P] [IsRegularLocalRing P] [Algebra K P] [Algebra.EssFiniteType K P]
    [Algebra.FormallySmooth K P] [Module.Free P Ω[P⁄K]] [Module.Finite P Ω[P⁄K]]
    [CommRing S] [IsRegularLocalRing S] [Algebra K S] [Algebra P S] [IsScalarTower K P S]
    (hsurj : Function.Surjective (algebraMap P S)) :
    Algebra.FormallySmooth K S := by
  have hFG : (RingHom.ker (algebraMap P S)).FG :=
    (IsNoetherian.noetherian (R := P) (RingHom.ker (algebraMap P S)))
  rw [Algebra.FormallySmooth.iff_injective_cotangentComplexBaseChange_residueField P hsurj hFG]
  exact injective_cotangentComplexBaseChange_of_isRegularLocalRing hsurj

/-- **A REGULAR LOCAL RING ESSENTIALLY OF FINITE TYPE OVER A PERFECT FIELD IS
FORMALLY SMOOTH** — Stacks `056S` in its regular-local form (PROVEN 2026-07-28
over `injective_cotangentComplexBaseChange_of_isRegularLocalRing`, the single
sorry leaf of this module).

This is THE statement that four open nodes of this development were each about
to build separately; see the module docstring for the table.  Everything else
here is bookkeeping: the presentation lemma builds `P = K[x₁,…,x_n]_𝔮 ↠ R`, and
`P` is formally smooth over `K` with `Ω[P⁄K]` finite free because it is a
localization of a polynomial ring
(`Algebra.FormallyEtale.of_isLocalization` plus
`KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale`), and regular local
because `MvPolynomial (Fin n) K` is a regular ring. -/
theorem FormallySmooth.of_isRegularLocalRing_of_perfectField
    {K R : Type u} [Field K] [PerfectField K] [CommRing R] [IsRegularLocalRing R]
    [Algebra K R] [Algebra.EssFiniteType K R] :
    Algebra.FormallySmooth K R := by
  obtain ⟨n, q, hq, f, hf⟩ := exists_localizationAtPrime_mvPolynomial_surjective K R
  haveI := hq
  algebraize [f.toRingHom]
  haveI : IsScalarTower K (Localization.AtPrime q) R :=
    IsScalarTower.of_algebraMap_eq' f.comp_algebraMap.symm
  haveI : Algebra.FormallyEtale (MvPolynomial (Fin n) K) (Localization.AtPrime q) :=
    .of_isLocalization q.primeCompl
  haveI : Algebra.FormallySmooth K (Localization.AtPrime q) :=
    .comp _ (MvPolynomial (Fin n) K) _
  haveI : Module.Free (Localization.AtPrime q) Ω[Localization.AtPrime q⁄K] :=
    .of_equiv (KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale K
      (MvPolynomial (Fin n) K) (Localization.AtPrime q))
  haveI : Module.Finite (Localization.AtPrime q) Ω[Localization.AtPrime q⁄K] :=
    .of_surjective (KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale K
      (MvPolynomial (Fin n) K) (Localization.AtPrime q)).toLinearMap
      (LinearEquiv.surjective _)
  exact FormallySmooth.of_surjective_of_isRegularLocalRing
    (K := K) (P := Localization.AtPrime q) (S := R) hf

/-- **A REGULAR RING OF FINITE TYPE OVER A PERFECT FIELD IS SMOOTH** — the
GLOBAL (non-local) form of Stacks `056S` (PROVEN 2026-07-28 over
`FormallySmooth.of_isRegularLocalRing_of_perfectField`, hence over the single
sorry leaf of this module).

The passage from local to global is FREE at this pin and costs no covering
argument: `Algebra.smoothLocus_eq_univ_iff`
(`Mathlib/RingTheory/Smooth/Locus.lean`) says that for a finitely presented
algebra, `FormallySmooth R A` is EQUIVALENT to every localization `A_𝔭` being
formally smooth, and `IsRegularRing B` is by definition the statement that
every `B_𝔭` is regular local.  So the two definitions meet pointwise and the
main theorem above is applied prime by prime.

`Algebra.FiniteType K B` upgrades to `FinitePresentation` for free because `K`
is a field, hence noetherian (`Algebra.FinitePresentation.of_finiteType`). -/
theorem Smooth.of_isRegularRing_of_perfectField
    (K B : Type u) [Field K] [PerfectField K] [CommRing B] [Algebra K B]
    [Algebra.FiniteType K B] [IsRegularRing B] :
    Algebra.Smooth K B := by
  haveI : Algebra.FinitePresentation K B := Algebra.FinitePresentation.of_finiteType.mp inferInstance
  refine ⟨?_, inferInstance⟩
  rw [← Algebra.smoothLocus_eq_univ_iff]
  ext p
  simp only [Set.mem_univ, iff_true]
  show Algebra.FormallySmooth K (Localization.AtPrime p.asIdeal)
  haveI : Algebra.EssFiniteType B (Localization.AtPrime p.asIdeal) :=
    .of_isLocalization _ p.asIdeal.primeCompl
  haveI : Algebra.EssFiniteType K (Localization.AtPrime p.asIdeal) := .comp _ B _
  exact FormallySmooth.of_isRegularLocalRing_of_perfectField

end Algebra
