/-
CyclotomicInertiaSurjective.lean — own work for the Fermat project.

**Surjectivity of the mod-`p` cyclotomic character on the inertia at `p`.**

This module carries exactly ONE theorem,
`exists_mem_localInertiaGroup_cyclotomicCharacter_toZModPow_eq`: every unit
of `ℤ/p` is the level-`1` value of the `p`-adic cyclotomic character at some
element of the local inertia group at `p`.  It is the total tame ramification
of `ℚ_p(ζ_p)/ℚ_p`, written in inertia-ELEMENT form.

**Why the module exists — a HOIST, not new mathematics** (2026-07-28).  The
theorem was proven on 2026-07-24 inside `Fermat/FLT/Modularity/Interface.lean`,
which is DOWNSTREAM of `Fermat/FLT/FreyCurve/MazurTorsion.lean`.  Lean has no
forward references, so `MazurTorsion`'s leaf `A₀-1`
(`exists_mem_localInertiaGroup_cyclotomicCharacterModL_eq`, the same statement
in `(ZMod N)ˣ` vocabulary) could not cite it and stood open purely for
DECLARATION-ORDER reasons.  Moving the theorem here — above both files — closes
that leaf with no new argument, exactly as the Minkowski block leaf `C` was
closed by the hoist into `Fermat.FLT.GaloisRepresentation.MinkowskiUnramified`.

The proof is unchanged, VERBATIM, and it stays in namespace
`GaloisRepresentation.Modularity` so that every existing call site in
`Interface.lean` keeps resolving without an edit.

The hoist is clean: the proof's only project-level inputs are
`maximalIdeal_map_eq_of_le_fixedField_localInertiaGroup`
(`Deformations/RepresentationTheory/LocalInertiaFixedField.lean`),
`maximalIdeal_adicCompletionIntegers_eq_span` and
`Nat.Prime.toHeightOneSpectrumRingOfIntegersRat`
(`Mathlib/RingTheory/DedekindDomain/Ideal/Lemmas.lean`), and
`Field.absoluteGaloisGroup.map` / `.lift_map` and `AlgebraicClosure.map`
(`Deformations/RepresentationTheory/AbsoluteGaloisGroup.lean` and
`Deformations/Lemmas.lean`).  It uses NONE of the helper lemmas that sat
beside it in `Interface.lean` (`isIntegral_of_pow_eq_one`,
`pos_of_natCast_notMem_maximalIdeal`, `natCast_pow_notMem_maximalIdeal`,
`eq_of_sub_mem_maximalIdeal_of_pow_eq_one`,
`map_fixes_of_pow_eq_one_of_mem_localInertiaGroup`) — checked by grepping the
proof body, not assumed — so those stay where they are and travel with
nothing.
-/
module

public import Fermat.FLT.Deformations.RepresentationTheory.AbsoluteGaloisGroup
public import Fermat.FLT.Deformations.RepresentationTheory.LocalInertiaFixedField
public import Fermat.FLT.Mathlib.RingTheory.DedekindDomain.Ideal.Lemmas
public import Mathlib.NumberTheory.Cyclotomic.CyclotomicCharacter
public import Mathlib.NumberTheory.Padics.RingHoms
public import Mathlib.RingTheory.Polynomial.Cyclotomic.Eval
public import Mathlib.RingTheory.Polynomial.Cyclotomic.Basic
-- `HasEnoughRootsOfUnity (AlgebraicClosure F) n`, which the Gauss-period
-- argument uses to pick a primitive `p`-th root of unity.  In `Interface.lean`
-- this instance arrived transitively; here it must be named.
public import Mathlib.RingTheory.RootsOfUnity.AlgebraicallyClosed

@[expose] public section

namespace GaloisRepresentation.Modularity

open IsDedekindDomain

variable {p : ℕ} [hp : Fact p.Prime]

set_option maxHeartbeats 2000000 in
/-- **The mod-`p` cyclotomic character maps the inertia at `p` ONTO
`(ℤ/p)^×`** (PROVEN 2026-07-24 — the surjectivity core of the
Serre §1.3 fundamental-character leaf below): every unit `u` of
`ℤ/p^1 = ℤ/p` is the level-`1` reduction of `ω(σ)` for some element
`σ` of the local inertia at `p`. This is the total tame ramification
of `ℚ_p(ζ_p)/ℚ_p` in inertia-element form, proven by a Gauss-period
argument that needs no ramification theory beyond the project's
PROVEN inertia-fixed-field node: let `H ⊆ (ℤ/p)^×` be the image of
the inertia under `ω` and suppose some unit `u₀ ∉ H`. The period
`τ₁ = ∏_{a ∈ H} (1 − ζ^a)` is then fixed by the whole inertia (the
inertia permutes the factors by translation inside `H`), so
`ℚ_pᵥ(τ₁)` lies in the fixed field of `localInertiaGroup v`, whence
`e = 1` there (`maximalIdeal_map_eq_of_le_fixedField_localInertiaGroup`,
Neukirch II.9.11) and the maximal ideal of its integral closure is
generated by `p` (`maximalIdeal_adicCompletionIntegers_eq_span`). At
the finite level `τ₁` is therefore either a unit — and then the
cofactor identity `1 − ζ = (1 − ζ^{u₀})·(integral)` inverts the
MISSING factor `1 − ζ^{u₀}` — or divisible by `p`, and cancelling `p`
from `∏_{all a}(1 − ζ^a) = Φ_p(1) = p`
(`Polynomial.eval_one_cyclotomic_prime`) again inverts every factor
outside `H`, `u₀` among them. Either way all `p − 1` factors become
invertible with integral inverses, so `1/p` is integral over the
DVR `𝒪ᵥ`, hence lies in it (`IsIntegrallyClosed`) — contradicting
`p ∈ 𝔪ᵥ`. Hence `H = (ℤ/p)^×`. (Serre, Duke Math. J. 54 (1987),
§1.3, 1.7; Serre, *Corps Locaux*, IV §4.) -/
theorem exists_mem_localInertiaGroup_cyclotomicCharacter_toZModPow_eq
    (u : (ZMod (p ^ 1))ˣ) :
    ∃ σ ∈ localInertiaGroup
        (Nat.Prime.toHeightOneSpectrumRingOfIntegersRat
          (Fact.out : p.Prime)),
      PadicInt.toZModPow 1
        ((cyclotomicCharacter (AlgebraicClosure ℚ) p
          ((Field.absoluteGaloisGroup.map (algebraMap ℚ
            (HeightOneSpectrum.adicCompletion ℚ
              (Nat.Prime.toHeightOneSpectrumRingOfIntegersRat
                (Fact.out : p.Prime)))) σ).toRingEquiv) : ℤ_[p]ˣ) : ℤ_[p]) =
        (u : ZMod (p ^ 1)) := by
  classical
  haveI : NeZero (p ^ 1) := ⟨pow_ne_zero 1 hp.out.ne_zero⟩
  haveI : NeZero p := ⟨hp.out.ne_zero⟩
  set v := Nat.Prime.toHeightOneSpectrumRingOfIntegersRat
    (Fact.out : p.Prime) with hvdef
  set f : ℚ →+* HeightOneSpectrum.adicCompletion ℚ v :=
    algebraMap ℚ (HeightOneSpectrum.adicCompletion ℚ v) with hfdef
  -- the exponent character on the local Galois group: the level-`1`
  -- reduction of the global cyclotomic character
  set χring : Field.absoluteGaloisGroup ℚ →*
      ((AlgebraicClosure ℚ) ≃+* (AlgebraicClosure ℚ)) :=
    { toFun := fun g => g.toRingEquiv
      map_one' := rfl
      map_mul' := fun _ _ => rfl } with hχringdef
  set χcomp : Field.absoluteGaloisGroup
      (HeightOneSpectrum.adicCompletion ℚ v) →* (ZMod (p ^ 1))ˣ :=
    ((Units.map (PadicInt.toZModPow (p := p) 1).toMonoidHom).comp
      ((cyclotomicCharacter (AlgebraicClosure ℚ) p).comp χring)).comp
      (Field.absoluteGaloisGroup.map f).toMonoidHom with hχcompdef
  have hχval : ∀ σ : Field.absoluteGaloisGroup
      (HeightOneSpectrum.adicCompletion ℚ v),
      ((χcomp σ : (ZMod (p ^ 1))ˣ) : ZMod (p ^ 1)) =
        PadicInt.toZModPow 1
          ((cyclotomicCharacter (AlgebraicClosure ℚ) p
            ((Field.absoluteGaloisGroup.map f σ).toRingEquiv) : ℤ_[p]ˣ) :
            ℤ_[p]) := fun _ => rfl
  -- it suffices that the image subgroup of the local inertia is full
  suffices hHfull : ∀ w : (ZMod (p ^ 1))ˣ,
      w ∈ Subgroup.map χcomp (localInertiaGroup v) by
    obtain ⟨σ, hσ, hσval⟩ := Subgroup.mem_map.mp (hHfull u)
    exact ⟨σ, hσ, by rw [← hχval σ, hσval]⟩
  intro u₀
  by_contra hu₀mem
  -- a primitive `p`-th root of unity over `ℚ` and its local image
  obtain ⟨ζ₀, hζ₀⟩ := HasEnoughRootsOfUnity.exists_primitiveRoot
    (AlgebraicClosure ℚ) p
  set ζ' : AlgebraicClosure (HeightOneSpectrum.adicCompletion ℚ v) :=
    AlgebraicClosure.map f ζ₀ with hζ'def
  have hζ'prim : IsPrimitiveRoot ζ' p :=
    hζ₀.map_of_injective (AlgebraicClosure.map f).injective
  have hζ'p1 : ζ' ^ p ^ 1 = 1 := by rw [pow_one]; exact hζ'prim.pow_eq_one
  have hpow_mod : ∀ m : ℕ, ζ' ^ m = ζ' ^ (m % p ^ 1) := by
    intro m
    conv_lhs => rw [← Nat.div_add_mod m (p ^ 1)]
    rw [pow_add, pow_mul, hζ'p1, one_pow, one_mul]
  -- the Galois action on `ζ'` is by the level-`1` cyclotomic exponent
  have hact : ∀ σ : Field.absoluteGaloisGroup
      (HeightOneSpectrum.adicCompletion ℚ v),
      σ ζ' = ζ' ^ ((χcomp σ : ZMod (p ^ 1))).val := by
    intro σ
    have hζ₀p1 : ζ₀ ^ p ^ 1 = 1 := by rw [pow_one]; exact hζ₀.pow_eq_one
    have hspec := cyclotomicCharacter.spec p
      ((Field.absoluteGaloisGroup.map f σ).toRingEquiv) ζ₀ hζ₀p1
    have hlift := Field.absoluteGaloisGroup.lift_map f σ ζ₀
    rw [hζ'def, ← hlift, show ((Field.absoluteGaloisGroup.map f σ) ζ₀ :
        AlgebraicClosure ℚ) =
      ((Field.absoluteGaloisGroup.map f σ).toRingEquiv) ζ₀ from rfl,
      hspec, map_pow, hχval σ]
  -- the factors of `Φ_p(1) = p`
  set q : (ZMod (p ^ 1))ˣ → AlgebraicClosure
      (HeightOneSpectrum.adicCompletion ℚ v) :=
    fun a => 1 - ζ' ^ ((a : ZMod (p ^ 1))).val with hqdef
  have hζ'int : IsIntegral (HeightOneSpectrum.adicCompletionIntegers ℚ v)
      ζ' := by
    refine ⟨Polynomial.X ^ p - Polynomial.C 1,
      Polynomial.monic_X_pow_sub_C 1 hp.out.ne_zero, ?_⟩
    rw [Polynomial.eval₂_sub, Polynomial.eval₂_pow, Polynomial.eval₂_X,
      Polynomial.eval₂_C, map_one, hζ'prim.pow_eq_one, sub_self]
  have hqint : ∀ a : (ZMod (p ^ 1))ˣ,
      IsIntegral (HeightOneSpectrum.adicCompletionIntegers ℚ v) (q a) := by
    intro a
    simp only [hqdef]
    exact isIntegral_one.sub (hζ'int.pow _)
  -- mutual divisibility of the factors, with integral cofactors
  have hdvd : ∀ a b : (ZMod (p ^ 1))ˣ, ∃ c,
      IsIntegral (HeightOneSpectrum.adicCompletionIntegers ℚ v) c ∧
      q b = q a * c := by
    intro a b
    refine ⟨∑ j ∈ Finset.range (((a⁻¹ * b : (ZMod (p ^ 1))ˣ) :
        ZMod (p ^ 1))).val, (ζ' ^ ((a : ZMod (p ^ 1))).val) ^ j, ?_, ?_⟩
    · exact IsIntegral.sum _ fun j _ => (hζ'int.pow _).pow _
    · simp only [hqdef]
      have hx : (ζ' ^ ((a : ZMod (p ^ 1))).val) ^
          (((a⁻¹ * b : (ZMod (p ^ 1))ˣ) : ZMod (p ^ 1))).val =
          ζ' ^ (((b : ZMod (p ^ 1))).val) := by
        rw [← pow_mul, hpow_mod, ← ZMod.val_mul, ← Units.val_mul,
          mul_inv_cancel_left]
      rw [← hx]
      linear_combination geom_sum_mul (ζ' ^ ((a : ZMod (p ^ 1))).val)
        (((a⁻¹ * b : (ZMod (p ^ 1))ˣ) : ZMod (p ^ 1))).val
  -- the full product over `(ℤ/p)ˣ` is `Φ_p(1) = p`
  have hprodfull : ∏ a : (ZMod (p ^ 1))ˣ, q a =
      ((p : ℕ) : AlgebraicClosure (HeightOneSpectrum.adicCompletion ℚ v)) := by
    have hcyc := Polynomial.eval_one_cyclotomic_prime
      (R := AlgebraicClosure (HeightOneSpectrum.adicCompletion ℚ v)) (p := p)
    rw [Polynomial.cyclotomic_eq_prod_X_sub_primitiveRoots hζ'prim,
      Polynomial.eval_prod] at hcyc
    simp only [Polynomial.eval_sub, Polynomial.eval_X, Polynomial.eval_C]
      at hcyc
    rw [← hcyc]
    refine Finset.prod_bij (fun a _ => ζ' ^ ((a : ZMod (p ^ 1))).val)
      ?_ ?_ ?_ ?_
    · intro a _
      rw [mem_primitiveRoots hp.out.pos]
      refine hζ'prim.pow_of_coprime _ ?_
      exact (ZMod.val_coe_unit_coprime a).coprime_dvd_right
        (dvd_pow_self p one_ne_zero)
    · intro a _ b _ hab
      have ha : ((a : ZMod (p ^ 1))).val < p :=
        calc ((a : ZMod (p ^ 1))).val < p ^ 1 := ZMod.val_lt _
          _ = p := pow_one p
      have hb : ((b : ZMod (p ^ 1))).val < p :=
        calc ((b : ZMod (p ^ 1))).val < p ^ 1 := ZMod.val_lt _
          _ = p := pow_one p
      exact Units.ext (ZMod.val_injective _ (hζ'prim.pow_inj ha hb hab))
    · intro μ hμ
      rw [mem_primitiveRoots hp.out.pos] at hμ
      obtain ⟨j, hjlt, hjcop, hjeq⟩ := (hζ'prim.isPrimitiveRoot_iff).mp hμ
      refine ⟨ZMod.unitOfCoprime j (hjcop.pow_right 1), Finset.mem_univ _, ?_⟩
      rw [ZMod.coe_unitOfCoprime, ZMod.val_natCast,
        Nat.mod_eq_of_lt (by rw [pow_one]; exact hjlt)]
      exact hjeq
    · intro a _
      rfl
  -- the local closure has characteristic zero
  haveI : CharZero (AlgebraicClosure (HeightOneSpectrum.adicCompletion ℚ v)) :=
    charZero_of_injective_algebraMap
      (algebraMap (HeightOneSpectrum.adicCompletion ℚ v) _).injective
  have hp0 : ((p : ℕ) : AlgebraicClosure
      (HeightOneSpectrum.adicCompletion ℚ v)) ≠ 0 :=
    Nat.cast_ne_zero.mpr hp.out.ne_zero
  -- the Gauss period over the (assumed proper) image subgroup
  set Hfin : Finset (ZMod (p ^ 1))ˣ :=
    Finset.univ.filter (· ∈ Subgroup.map χcomp (localInertiaGroup v))
    with hHfindef
  set τ₁ : AlgebraicClosure (HeightOneSpectrum.adicCompletion ℚ v) :=
    ∏ a ∈ Hfin, q a with hτ₁def
  -- every inertia element fixes the period
  have hτ₁fix : ∀ σ ∈ localInertiaGroup v, σ τ₁ = τ₁ := by
    intro σ hσ
    have hcmem : χcomp σ ∈ Subgroup.map χcomp (localInertiaGroup v) :=
      Subgroup.mem_map.mpr ⟨σ, hσ, rfl⟩
    have hqσ : ∀ a : (ZMod (p ^ 1))ˣ, σ (q a) = q (χcomp σ * a) := by
      intro a
      simp only [hqdef]
      rw [map_sub, map_one, map_pow, hact σ, ← pow_mul, hpow_mod,
        ← ZMod.val_mul, ← Units.val_mul]
    rw [hτ₁def, map_prod, Finset.prod_congr rfl fun a _ => hqσ a]
    refine Finset.prod_nbij' (fun a => χcomp σ * a) (fun a => (χcomp σ)⁻¹ * a)
      ?_ ?_ ?_ ?_ ?_
    · intro a ha
      simp only [hHfindef, Finset.mem_filter] at ha ⊢
      exact ⟨Finset.mem_univ _, Subgroup.mul_mem _ hcmem ha.2⟩
    · intro a ha
      simp only [hHfindef, Finset.mem_filter] at ha ⊢
      exact ⟨Finset.mem_univ _,
        Subgroup.mul_mem _ (Subgroup.inv_mem _ hcmem) ha.2⟩
    · intro a _
      rw [inv_mul_cancel_left]
    · intro a _
      rw [mul_inv_cancel_left]
    · intro a _
      rfl
  -- the adjoined field `Kᵥ(τ₁)` is finite and inertia-fixed
  have hτ₁algK : IsIntegral (HeightOneSpectrum.adicCompletion ℚ v) τ₁ :=
    (Algebra.IsAlgebraic.isAlgebraic τ₁).isIntegral
  haveI hfdM : FiniteDimensional (HeightOneSpectrum.adicCompletion ℚ v)
      (IntermediateField.adjoin (HeightOneSpectrum.adicCompletion ℚ v)
        {τ₁}) :=
    IntermediateField.adjoin.finiteDimensional hτ₁algK
  have hMle : IntermediateField.adjoin
      (HeightOneSpectrum.adicCompletion ℚ v) {τ₁} ≤
      IntermediateField.fixedField (localInertiaGroup v) := by
    rw [IntermediateField.adjoin_le_iff]
    intro z hz
    rw [Set.mem_singleton_iff] at hz
    subst hz
    rw [SetLike.mem_coe, IntermediateField.mem_fixedField_iff]
    exact hτ₁fix
  -- `𝔪ᵥ = (p)` generates the maximal ideal of the integral closure
  have hideal := maximalIdeal_map_eq_of_le_fixedField_localInertiaGroup v
    (IntermediateField.adjoin (HeightOneSpectrum.adicCompletion ℚ v) {τ₁})
    hMle
  have hspan : IsLocalRing.maximalIdeal
      (HeightOneSpectrum.adicCompletionIntegers ℚ v) =
      Ideal.span {((p : ℕ) :
        HeightOneSpectrum.adicCompletionIntegers ℚ v)} :=
    maximalIdeal_adicCompletionIntegers_eq_span (Fact.out : p.Prime)
  have hMR : IsLocalRing.maximalIdeal
      (IntegralClosure (HeightOneSpectrum.adicCompletionIntegers ℚ v)
      (IntermediateField.adjoin (HeightOneSpectrum.adicCompletion ℚ v)
        {τ₁})) =
      Ideal.span {((p : ℕ) :
        IntegralClosure (HeightOneSpectrum.adicCompletionIntegers ℚ v)
        (IntermediateField.adjoin (HeightOneSpectrum.adicCompletion ℚ v)
          {τ₁}))} := by
    rw [← hideal, hspan, Ideal.map_span, Set.image_singleton, map_natCast]
  -- `τ₁` as an element of the integral closure at the finite level
  have hτ₁mem : τ₁ ∈ IntermediateField.adjoin
      (HeightOneSpectrum.adicCompletion ℚ v) {τ₁} :=
    IntermediateField.mem_adjoin_simple_self _ τ₁
  have hτ₁int : IsIntegral (HeightOneSpectrum.adicCompletionIntegers ℚ v)
      τ₁ := by
    rw [hτ₁def]
    exact Finset.prod_induction q _ (fun x y hx hy => hx.mul hy)
      isIntegral_one fun a _ => hqint a
  have hτ₁Mint : IsIntegral (HeightOneSpectrum.adicCompletionIntegers ℚ v)
      (⟨τ₁, hτ₁mem⟩ :
      IntermediateField.adjoin (HeightOneSpectrum.adicCompletion ℚ v)
        {τ₁}) := by
    rw [← isIntegral_algebraMap_iff (algebraMap
      (IntermediateField.adjoin (HeightOneSpectrum.adicCompletion ℚ v) {τ₁})
      (AlgebraicClosure (HeightOneSpectrum.adicCompletion ℚ v))).injective]
    exact hτ₁int
  obtain ⟨T, hT⟩ := (IsIntegralClosure.isIntegral_iff
    (A := IntegralClosure (HeightOneSpectrum.adicCompletionIntegers ℚ v)
      (IntermediateField.adjoin (HeightOneSpectrum.adicCompletion ℚ v)
        {τ₁}))).mp hτ₁Mint
  -- pushing integral-closure elements back into the algebraic closure
  set toC : IntegralClosure (HeightOneSpectrum.adicCompletionIntegers ℚ v)
      (IntermediateField.adjoin (HeightOneSpectrum.adicCompletion ℚ v)
        {τ₁}) → AlgebraicClosure (HeightOneSpectrum.adicCompletion ℚ v) :=
    fun Z => algebraMap
      (IntermediateField.adjoin (HeightOneSpectrum.adicCompletion ℚ v) {τ₁})
      (AlgebraicClosure (HeightOneSpectrum.adicCompletion ℚ v))
      (algebraMap (IntegralClosure
        (HeightOneSpectrum.adicCompletionIntegers ℚ v)
        (IntermediateField.adjoin (HeightOneSpectrum.adicCompletion ℚ v)
          {τ₁}))
        (IntermediateField.adjoin (HeightOneSpectrum.adicCompletion ℚ v)
          {τ₁}) Z) with htoCdef
  have hpushint : ∀ Z,
      IsIntegral (HeightOneSpectrum.adicCompletionIntegers ℚ v) (toC Z) := by
    intro Z
    simp only [htoCdef]
    exact ((Algebra.IsIntegral.isIntegral
      (R := HeightOneSpectrum.adicCompletionIntegers ℚ v)
      Z).algebraMap).algebraMap
  have hToCT : toC T = τ₁ := by
    simp only [htoCdef]
    rw [hT]
    rfl
  -- either way, the missing factor `1 − ζ'^{u₀}` acquires an integral
  -- inverse
  have hqu₀inv : ∃ y,
      IsIntegral (HeightOneSpectrum.adicCompletionIntegers ℚ v) y ∧
      q u₀ * y = 1 := by
    by_cases hTu : IsUnit T
    · -- the period is a unit at the finite level
      obtain ⟨Tu, hTueq⟩ := hTu
      have hTmul : T * ((Tu⁻¹ : _ˣ) : IntegralClosure
          (HeightOneSpectrum.adicCompletionIntegers ℚ v)
          (IntermediateField.adjoin (HeightOneSpectrum.adicCompletion ℚ v)
            {τ₁})) = 1 := by
        rw [← hTueq, Units.mul_inv]
      have hTCinv : toC T * toC ((Tu⁻¹ : _ˣ) : IntegralClosure
          (HeightOneSpectrum.adicCompletionIntegers ℚ v)
          (IntermediateField.adjoin (HeightOneSpectrum.adicCompletion ℚ v)
            {τ₁})) = 1 := by
        simp only [htoCdef]
        rw [← map_mul, ← map_mul, hTmul, map_one, map_one]
      have hTinv : τ₁ * toC ((Tu⁻¹ : _ˣ) : IntegralClosure
          (HeightOneSpectrum.adicCompletionIntegers ℚ v)
          (IntermediateField.adjoin (HeightOneSpectrum.adicCompletion ℚ v)
            {τ₁})) = 1 :=
        calc τ₁ * toC ((Tu⁻¹ : _ˣ) : IntegralClosure
              (HeightOneSpectrum.adicCompletionIntegers ℚ v)
              (IntermediateField.adjoin
                (HeightOneSpectrum.adicCompletion ℚ v) {τ₁}))
            = toC T * toC ((Tu⁻¹ : _ˣ) : IntegralClosure
              (HeightOneSpectrum.adicCompletionIntegers ℚ v)
              (IntermediateField.adjoin
                (HeightOneSpectrum.adicCompletion ℚ v) {τ₁})) := by
              rw [hToCT]
          _ = 1 := hTCinv
      obtain ⟨c, hcint, hc⟩ := hdvd u₀ 1
      have h1H : (1 : (ZMod (p ^ 1))ˣ) ∈ Hfin := by
        simp only [hHfindef, Finset.mem_filter]
        exact ⟨Finset.mem_univ _, Subgroup.one_mem _⟩
      have hτfact : τ₁ = q u₀ * (c * ∏ a ∈ Hfin.erase 1, q a) := by
        rw [hτ₁def, ← Finset.mul_prod_erase Hfin q h1H, hc]
        ring
      refine ⟨(c * ∏ a ∈ Hfin.erase 1, q a) * toC ((Tu⁻¹ : _ˣ) :
        IntegralClosure (HeightOneSpectrum.adicCompletionIntegers ℚ v)
          (IntermediateField.adjoin
            (HeightOneSpectrum.adicCompletion ℚ v) {τ₁})), ?_, ?_⟩
      · exact (hcint.mul (Finset.prod_induction q _
          (fun x y hx hy => hx.mul hy) isIntegral_one
          fun a _ => hqint a)).mul (hpushint _)
      · rw [← mul_assoc, ← hτfact]
        exact hTinv
    · -- the period is divisible by `p` at the finite level
      have hTm : T ∈ IsLocalRing.maximalIdeal
          (IntegralClosure (HeightOneSpectrum.adicCompletionIntegers ℚ v)
          (IntermediateField.adjoin (HeightOneSpectrum.adicCompletion ℚ v)
            {τ₁})) := by
        rwa [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff]
      rw [hMR] at hTm
      obtain ⟨Z, hZ⟩ := Ideal.mem_span_singleton'.mp hTm
      have hτ₁p : τ₁ = toC Z * ((p : ℕ) : AlgebraicClosure
          (HeightOneSpectrum.adicCompletion ℚ v)) := by
        rw [← hToCT]
        simp only [htoCdef]
        rw [← hZ, map_mul, map_mul, map_natCast, map_natCast]
      have hsplit : τ₁ * ∏ a ∈ Hfinᶜ, q a = ((p : ℕ) : AlgebraicClosure
          (HeightOneSpectrum.adicCompletion ℚ v)) := by
        rw [hτ₁def, Finset.prod_mul_prod_compl, hprodfull]
      have hcancel : toC Z * ∏ a ∈ Hfinᶜ, q a = 1 := by
        have h2 : ((p : ℕ) : AlgebraicClosure
            (HeightOneSpectrum.adicCompletion ℚ v)) *
            (toC Z * ∏ a ∈ Hfinᶜ, q a) =
            ((p : ℕ) : AlgebraicClosure
              (HeightOneSpectrum.adicCompletion ℚ v)) * 1 := by
          rw [mul_one]
          calc ((p : ℕ) : AlgebraicClosure
                (HeightOneSpectrum.adicCompletion ℚ v)) *
                (toC Z * ∏ a ∈ Hfinᶜ, q a)
              = (toC Z * ((p : ℕ) : AlgebraicClosure
                (HeightOneSpectrum.adicCompletion ℚ v))) *
                ∏ a ∈ Hfinᶜ, q a := by ring
            _ = τ₁ * ∏ a ∈ Hfinᶜ, q a := by rw [← hτ₁p]
            _ = ((p : ℕ) : AlgebraicClosure
                (HeightOneSpectrum.adicCompletion ℚ v)) := hsplit
        exact mul_left_cancel₀ hp0 h2
      have hu₀c : u₀ ∈ Hfinᶜ := by
        simp only [Finset.mem_compl, hHfindef, Finset.mem_filter]
        intro hcon2
        exact hu₀mem hcon2.2
      refine ⟨toC Z * (∏ a ∈ Hfinᶜ.erase u₀, q a), ?_, ?_⟩
      · exact (hpushint _).mul (Finset.prod_induction q _
          (fun x y hx hy => hx.mul hy) isIntegral_one fun a _ => hqint a)
      · rw [← hcancel, ← Finset.mul_prod_erase Hfinᶜ q hu₀c]
        ring
  -- hence every factor is invertible, hence so is `p` itself
  obtain ⟨y₀, hy₀int, hy₀⟩ := hqu₀inv
  have hinvall : ∀ a : (ZMod (p ^ 1))ˣ, ∃ y,
      IsIntegral (HeightOneSpectrum.adicCompletionIntegers ℚ v) y ∧
      q a * y = 1 := by
    intro a
    obtain ⟨c, hcint, hc⟩ := hdvd a u₀
    exact ⟨c * y₀, hcint.mul hy₀int, by rw [← mul_assoc, ← hc, hy₀]⟩
  choose W hWint hW using hinvall
  have hpW : ((p : ℕ) : AlgebraicClosure
      (HeightOneSpectrum.adicCompletion ℚ v)) *
      ∏ a : (ZMod (p ^ 1))ˣ, W a = 1 := by
    rw [← hprodfull, ← Finset.prod_mul_distrib]
    exact Finset.prod_eq_one fun a _ => hW a
  have hWprodint : IsIntegral (HeightOneSpectrum.adicCompletionIntegers ℚ v)
      (∏ a : (ZMod (p ^ 1))ˣ, W a) :=
    Finset.prod_induction W _ (fun x y hx hy => hx.mul hy) isIntegral_one
      fun a _ => hWint a
  -- so `1/p` is integral over `𝒪ᵥ`, hence lies in `𝒪ᵥ`: contradiction
  have hpKv : ((p : ℕ) : HeightOneSpectrum.adicCompletion ℚ v) ≠ 0 :=
    Nat.cast_ne_zero.mpr hp.out.ne_zero
  have hWeq : ∏ a : (ZMod (p ^ 1))ˣ, W a =
      algebraMap (HeightOneSpectrum.adicCompletion ℚ v)
        (AlgebraicClosure (HeightOneSpectrum.adicCompletion ℚ v))
        (((p : ℕ) : HeightOneSpectrum.adicCompletion ℚ v)⁻¹) := by
    have hcast : ((p : ℕ) : AlgebraicClosure
        (HeightOneSpectrum.adicCompletion ℚ v)) =
        algebraMap (HeightOneSpectrum.adicCompletion ℚ v)
          (AlgebraicClosure (HeightOneSpectrum.adicCompletion ℚ v))
          ((p : ℕ) : HeightOneSpectrum.adicCompletion ℚ v) := by
      rw [map_natCast]
    have h2 : algebraMap (HeightOneSpectrum.adicCompletion ℚ v)
        (AlgebraicClosure (HeightOneSpectrum.adicCompletion ℚ v))
        (((p : ℕ) : HeightOneSpectrum.adicCompletion ℚ v)⁻¹) *
        algebraMap (HeightOneSpectrum.adicCompletion ℚ v)
          (AlgebraicClosure (HeightOneSpectrum.adicCompletion ℚ v))
          ((p : ℕ) : HeightOneSpectrum.adicCompletion ℚ v) = 1 := by
      rw [← map_mul, inv_mul_cancel₀ hpKv, map_one]
    calc ∏ a : (ZMod (p ^ 1))ˣ, W a
        = (algebraMap (HeightOneSpectrum.adicCompletion ℚ v)
            (AlgebraicClosure (HeightOneSpectrum.adicCompletion ℚ v))
            (((p : ℕ) : HeightOneSpectrum.adicCompletion ℚ v)⁻¹) *
          algebraMap (HeightOneSpectrum.adicCompletion ℚ v)
            (AlgebraicClosure (HeightOneSpectrum.adicCompletion ℚ v))
            ((p : ℕ) : HeightOneSpectrum.adicCompletion ℚ v)) *
          ∏ a : (ZMod (p ^ 1))ˣ, W a := by rw [h2, one_mul]
      _ = algebraMap (HeightOneSpectrum.adicCompletion ℚ v)
            (AlgebraicClosure (HeightOneSpectrum.adicCompletion ℚ v))
            (((p : ℕ) : HeightOneSpectrum.adicCompletion ℚ v)⁻¹) *
          (((p : ℕ) : AlgebraicClosure
            (HeightOneSpectrum.adicCompletion ℚ v)) *
            ∏ a : (ZMod (p ^ 1))ˣ, W a) := by rw [hcast]; ring
      _ = algebraMap (HeightOneSpectrum.adicCompletion ℚ v)
            (AlgebraicClosure (HeightOneSpectrum.adicCompletion ℚ v))
            (((p : ℕ) : HeightOneSpectrum.adicCompletion ℚ v)⁻¹) := by
            rw [hpW, mul_one]
  have hint : IsIntegral (HeightOneSpectrum.adicCompletionIntegers ℚ v)
      (((p : ℕ) : HeightOneSpectrum.adicCompletion ℚ v)⁻¹) := by
    rw [← isIntegral_algebraMap_iff
      (algebraMap (HeightOneSpectrum.adicCompletion ℚ v)
        (AlgebraicClosure (HeightOneSpectrum.adicCompletion ℚ v))).injective,
      ← hWeq]
    exact hWprodint
  obtain ⟨y, hy⟩ := IsIntegrallyClosed.isIntegral_iff.mp hint
  have hpy : ((p : ℕ) : HeightOneSpectrum.adicCompletionIntegers ℚ v) *
      y = 1 := by
    apply IsFractionRing.injective
      (HeightOneSpectrum.adicCompletionIntegers ℚ v)
      (HeightOneSpectrum.adicCompletion ℚ v)
    rw [map_mul, map_natCast, hy, map_one, mul_inv_cancel₀ hpKv]
  have hpmem : ((p : ℕ) : HeightOneSpectrum.adicCompletionIntegers ℚ v) ∈
      IsLocalRing.maximalIdeal
        (HeightOneSpectrum.adicCompletionIntegers ℚ v) := by
    rw [hspan]
    exact Ideal.mem_span_singleton_self _
  rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff] at hpmem
  exact hpmem (IsUnit.of_mul_eq_one _ hpy)

end GaloisRepresentation.Modularity
