/-
ClassGroupNormSubgroup.lean — own work for the Fermat project.
-/
module

public import Mathlib.RingTheory.Ideal.Norm.RelNorm
public import Mathlib.RingTheory.ClassGroup.Basic
public import Mathlib.NumberTheory.NumberField.ClassNumber
public import Mathlib.NumberTheory.NumberField.InfinitePlace.Ramification
public import Mathlib.RingTheory.Unramified.Locus
public import Mathlib.FieldTheory.Galois.Basic

/-!
# The norm subgroup of the class group, and the second inequality at modulus `1`

This file carries the class-field-theoretic input of
`GaloisRepresentation.Modularity.finrank_le_card_classGroup_of_unramified_abelian_of_isUnramifiedAtInfinitePlaces`
(`Fermat/FLT/Modularity/Interface.lean`), which was a bare `sorry` until
2026-07-28 and is now PROVEN over the single leaf below.

The content is the classical **second inequality at modulus `1`**: for `L/K`
a finite abelian extension of number fields, unramified at every finite prime
AND at every infinite place,

  `[L : K] ≤ [I_K : P_K · N_{L/K} I_L]`,

where the right-hand index is realised here as the index in `Cl(𝓞 K)` of the
subgroup generated by the classes of relative ideal norms
(`normClassSubgroup`). Since that subgroup sits inside the finite group
`Cl(𝓞 K)`, its index divides `h_K`, and the bound `[L : K] ≤ h_K` — i.e.
`L` sits inside the Hilbert class field of `K` — is then pure bookkeeping.

Splitting the file this way is deliberate, and the reason is elaboration cost,
not availability: `Interface.lean` costs ~75 minutes of single-core
elaboration and none of the material here depends on anything in it, so the
open leaf below can be iterated on in seconds instead. It also keeps the
footprint in that heavily-shared file down to one import and one proof term.

**A claim first written here on 2026-07-28 and then REFUTED by its own author,
recorded so nobody re-derives it**: `Ideal.relNorm` is *not* absent from
`Interface.lean`'s import surface. The evidence that suggested it was — the
only `Ideal/Norm/` module `Interface.lean` names is `AbsNorm.lean`, and
`AbsNorm.lean` does not import `RelNorm.lean` — is true and does not settle
the question. Computing the closure under `public import` edges shows
`Mathlib.RingTheory.Ideal.Norm.RelNorm` IS publicly visible there (reached via
`Mathlib.NumberTheory.NumberField.Discriminant.Different`), as is
`Mathlib.NumberTheory.NumberField.ClassNumber` and hence
`NumberField.instFintypeClassGroup`. Direct imports are not the import
surface.
-/

@[expose] public section

open scoped nonZeroDivisors
open NumberField

namespace Ideal

/-- **The relative ideal norm as a monoid homomorphism on NONZERO ideals**
(PROVEN 2026-07-28).

`Ideal.relNorm R : Ideal S →*₀ Ideal R` is a monoid-with-zero hom on all
ideals. For class-group purposes one needs it on `(Ideal S)⁰`, the
nonzerodivisors of the ideal monoid — which for a Dedekind domain are exactly
the nonzero ideals — so that it can be composed with `ClassGroup.mk0`. The
only content is that the norm of a nonzero ideal is nonzero, which is
`Ideal.relNorm_eq_bot_iff`; multiplicativity and unitality are inherited. -/
noncomputable def relNormNonZeroDivisors (R S : Type*) [CommRing R]
    [CommRing S] [IsDedekindDomain R] [IsDedekindDomain S]
    [Algebra R S] [Module.Finite R S] [Module.IsTorsionFree R S] :
    (Ideal S)⁰ →* (Ideal R)⁰ where
  toFun I := ⟨Ideal.relNorm R (I : Ideal S), by
    rw [mem_nonZeroDivisors_iff_ne_zero]
    have hI : (I : Ideal S) ≠ 0 := mem_nonZeroDivisors_iff_ne_zero.mp I.2
    rw [Ideal.zero_eq_bot] at hI ⊢
    exact fun h => hI (Ideal.relNorm_eq_bot_iff.mp h)⟩
  map_one' := Subtype.ext (map_one (Ideal.relNorm R))
  map_mul' I J := Subtype.ext (map_mul (Ideal.relNorm R) _ _)

end Ideal

namespace UnramifiedClassFieldTheory

/-- **The norm subgroup `N_{L/K}` of the class group of `K`** (2026-07-28):
the subgroup of `Cl(𝓞 K)` generated by the classes of the relative norms
`N_{L/K} I` of the nonzero ideals `I` of `𝓞 L`.

This is the class-group avatar of the classical `P_K · N_{L/K} I_L ≤ I_K`:
the quotient `Cl(𝓞 K) ⧸ normClassSubgroup K L` is canonically
`I_K / (P_K · N_{L/K} I_L)`, so `(normClassSubgroup K L).index` IS the
classical norm index `[I_K : P_K · N_{L/K} I_L]`.

Two deliberate choices, both harmless:

* `Subgroup.closure` rather than `MonoidHom.range`. The source `(Ideal (𝓞 L))⁰`
  is a monoid and not a group, so `MonoidHom.range` does not typecheck. The
  closure adds only inverses, and `Cl(𝓞 K)` is finite, so the closure of the
  (already multiplicatively closed, `1`-containing) image is that image.
* Only INTEGRAL ideals are normed. Every fractional-ideal class is the class of
  an integral ideal and `relNorm` is multiplicative, so the subgroup generated
  is the same one the classical statement writes with fractional ideals.

The `letI` supplying `NumberField ↥L` is not a design choice that can leak:
`NumberField` is a `Prop`-valued class, so the instance is unique by proof
irrelevance. It is needed because `NumberField.of_intermediateField` wants the
AMBIENT field to be a number field, and here the ambient field is
`AlgebraicClosure K`, which is not. -/
noncomputable def normClassSubgroup (K : Type) [Field K] [NumberField K]
    (L : IntermediateField K (AlgebraicClosure K)) [FiniteDimensional K L] :
    Subgroup (ClassGroup (𝓞 K)) :=
  letI : NumberField (L : Type _) := NumberField.of_module_finite K (L : Type _)
  Subgroup.closure (Set.range ((ClassGroup.mk0 (R := 𝓞 K)).comp
    (Ideal.relNormNonZeroDivisors (𝓞 K) (𝓞 (L : Type _)))))

/-- **THE SECOND INEQUALITY AT MODULUS `1`: a finite ABELIAN extension of a
number field `K`, unramified at every finite prime AND at every infinite
place, has degree at most the norm index `[I_K : P_K · N_{L/K} I_L]`**
(SORRY LEAF, cut 2026-07-28 out of
`finrank_le_card_classGroup_of_unramified_abelian_of_isUnramifiedAtInfinitePlaces`
in `Fermat/FLT/Modularity/Interface.lean` — **this is where the missing
mathematics is, and it is now ALL of it**).

The consumer's `≤ h_K` follows from this by pure bookkeeping:
`normClassSubgroup K L ≤ Cl(𝓞 K)` and `Cl(𝓞 K)` is finite, so
`Subgroup.index_dvd_card` gives `index ≤ Nat.card (ClassGroup (𝓞 K))`. That
step is PROVEN at the consumer; nothing arithmetic is left there.

**This is SHARP, not merely an inequality.** Artin reciprocity for the
Hilbert class field gives `Cl(𝓞 K) ⧸ N_{L/K} ≃ Gal(L/K)`, so the index here
EQUALS `[L : K]`. Only `≤` is stated because only `≤` is needed and because
the reverse (the "first inequality", `index ≤ [L : K]`) is the analytic half —
a different theorem, proved by Dirichlet density, and not required anywhere
downstream. A prover who ends up with the equality has lost nothing.

**Route, and it is NOT reciprocity.** The classical second inequality is
proven by the cohomological / ambiguous-class-number computation: for `L/K`
cyclic, the Herbrand quotient of the idele class group is `[L : K]`
(Neukirch VI (6.9) and the sections preceding it; Childress ch. 4–5; Lang
*ANT* ch. X; Cassels–Fröhlich ch. VII), and the general abelian case follows
by the class-formation dévissage. Modulus `1` is admissible exactly because of
`IsUnramifiedAtInfinitePlaces` — the same fact the counterexample below turns
on. The alternative route, through surjectivity of the Artin map
`Cl(𝓞 K) ↠ Gal(L/K)`, needs RECIPROCITY (principal ideals in the kernel); the
sibling `exists_artinIdealMap_of_unramifiedAbelianSubgroup` in `Interface.lean`
owns that, and it is a heavily specialised statement over `ℚ` with a
cyclotomic pin — it CANNOT be applied here (checked 2026-07-28 by reading its
signature, not by trusting a note). The norm-index route is the independent
one and is the reason this leaf exists separately.

**⚠ THE ARCHIMEDEAN HYPOTHESIS IS NOT DECORATION — DELETING IT MAKES THE
STATEMENT FALSE.** With the WIDE class group and unramifiedness only at the
FINITE places, the inequality fails over a general number field.
Counterexample, RE-VERIFIED with PARI/GP on 2026-07-28 (`bnfinit(x^2-3,1).no
= 1`, `bnrinit(K,[1,[1,1]]).no = 2`): `K = ℚ(√3)` has `h_K = 1` but narrow
class number `2`, so its narrow Hilbert class field is a QUADRATIC extension,
abelian and unramified at every finite place, of degree `2 > 1 = h_K`. It is
excluded here — and only here — by `IsUnramifiedAtInfinitePlaces`: that
extension is ramified at both real places of `ℚ(√3)`.

Equally, the hypothesis cannot be pushed onto the consumer's `p = 2` branch:
supplying `IsUnramifiedAtInfinitePlaces ℚ L` would already require knowing
`L = ℚ`, which IS the Minkowski statement discharged separately by
`finrank_eq_one_of_unramified_of_finrank_rat_eq_one`.

**Not vacuous.** `h(ℚ(μ_23)) = 3` (PARI/GP, RE-VERIFIED 2026-07-28), and
`ℚ(μ_23)` is totally complex, so the consumer instantiates this leaf at a base
where the bound is a genuine constraint and not `≤ 1`. The index on the right
is likewise not trivially large: it equals `[L : K]` exactly.

**Mathlib survey (re-checked 2026-07-28 against OUR pin, by grep, in all three
places — `Fermat/`, `.lake/packages/mathlib`, `~/cs/FLT`).** Ray class groups,
the Hilbert class field, the Artin map and Artin reciprocity are absent.
Present and used above: `Ideal.relNorm`
(`Mathlib/RingTheory/Ideal/Norm/RelNorm.lean`), `Ideal.relNorm_eq_bot_iff`,
`ClassGroup.mk0`, `NumberField.instFintypeClassGroup`,
`Subgroup.index_dvd_card`, `Algebra.IsUnramifiedAt`,
`IsUnramifiedAtInfinitePlaces`, `NumberField.of_module_finite`. The
Herbrand-quotient machinery is NOT present:
`Mathlib/RepresentationTheory/Homological/TateCohomology/` carries `Basic.lean`
only — definitions, no class formations, no Tate theorem — so the cohomological
route must be built, not cited.

**WHERE TO LOOK FIRST INSIDE THIS PROJECT (2026-07-28).** There is an ACTIVE
parallel class-field-theory development that a prover of this leaf should read
before starting from scratch, even though none of it discharges this statement
as it stands: `Fermat/FLT/GaloisRepresentation/HardlyRamified/ModThree.lean`
carries a DIVISOR-GROUP formulation — `exists_rayClassPackage_ray_class`,
`exists_artinDivisorPackage_ray_class`, `exists_artinNormSubgroups_ray_class`,
and a relative norm `𝔑` on divisors pinned on the basis by
`Ideal.inertiaDeg`, with the Childress ch. 5 consistency property
`φ (𝔑 x) = φ' x`. It is stated for a specific character into `Dickson.K 3`
and with a modulus, so it is not directly applicable here, and `ModThree.lean`
is NOT in `Interface.lean`'s import cone (that edge was cut on 2026-07-27) —
but it is the same mathematics one level down, and the norm-on-divisors
material is the piece this leaf would otherwise have to build. Cross-check
before duplicating it.

**The check that would refute it**: a finite abelian extension of a number
field `K`, unramified at every finite prime and at every infinite place, whose
degree exceeds the index in `Cl(𝓞 K)` of the subgroup generated by the classes
of relative ideal norms from `L`. -/
theorem finrank_le_index_normClassSubgroup (K : Type) [Field K] [NumberField K]
    (L : IntermediateField K (AlgebraicClosure K)) [FiniteDimensional K L]
    [IsGalois K L] [IsUnramifiedAtInfinitePlaces K (L : Type _)]
    (habel : ∀ a b : L ≃ₐ[K] L, a * b = b * a)
    (hunr : ∀ (Q : Ideal (𝓞 L)) (_ : Q.IsPrime), Q ≠ ⊥ →
      Algebra.IsUnramifiedAt (𝓞 K) Q) :
    Module.finrank K L ≤ (normClassSubgroup K L).index :=
  sorry

end UnramifiedClassFieldTheory
