/-
Copyright (c) 2025 Kevin Buzzard. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kevin Buzzard
-/
module

public import Mathlib.RingTheory.MvPowerSeries.Equiv
public import Mathlib.RingTheory.AdicCompletion.RingHom
public import Mathlib.RingTheory.AdicCompletion.Algebra
public import Mathlib.RingTheory.MvPolynomial.Ideal
public import Mathlib.Algebra.MvPolynomial.PDeriv

/-!
# Evaluating a multivariate power series in an adically complete ring

Fontaine's proof that a finite flat group scheme over `𝒪_K` is rigid along the
`𝔪`-adic filtration (*Il n'y a pas de variété abélienne sur ℤ*, Invent. Math. 81
(1985), Prop. 1.7) presents the affine algebra as `𝒪_K[[X₁,…,X_h]]/(P₁,…,P_h)` and
then substitutes tuples from the maximal ideal of a complete discrete valuation
ring into the `P_i`.  This file supplies exactly that substitution, and it does so
**without any topology**: `MvPowerSeries σ R` maps to `MvPolynomial σ R ⧸ (X)^n`
by total truncation (`MvPowerSeries.truncTotalAlgHom`), `MvPolynomial.aeval w`
carries `(X)^n` into `I^n` as soon as every `w i` lies in `I`, and a compatible
family of maps into the `O ⧸ I^n` assembles into a map into `O` itself by
`IsAdicComplete.liftAlgHom`.  So the construction is a composite of three pieces
of mathlib and needs neither `MvPowerSeries.HasEval` nor a uniform structure on
`O` — which matters here, because the ring being substituted into is
`IntegralClosure 𝒪₃ᵥ E`, on which the development carries `IsAdicComplete` but no
topology.

## Main definitions

* `MvPowerSeries.pderiv` — the formal partial derivative of a multivariate power
  series, defined coefficientwise.  (The pin has derivatives for `Polynomial`,
  `MvPolynomial` and `PowerSeries`, but nothing for `MvPowerSeries`.)
* `MvPowerSeries.adicEval` — evaluation `MvPowerSeries σ R →ₐ[R] O` at a tuple
  `w : σ → O` all of whose entries lie in an ideal `I` for which `O` is
  `I`-adically complete.

## Main results

* `MvPowerSeries.mk_adicEval` — the defining property: modulo `I ^ n` the value of
  `adicEval` is the value of the degree-`< n` truncation.
* `MvPowerSeries.adicEval_X`, `MvPowerSeries.adicEval_coe` — the substitution does
  what it should on variables and on polynomials.
* `MvPowerSeries.adicEval_mem_pow` — a power series whose coefficients vanish below
  total degree `k` evaluates into `I ^ k`.  This is the estimate that makes the
  construction useful: it turns "congruent modulo a power of the variable ideal"
  into "congruent modulo a power of `I`".
* `MvPolynomial.taylor_sub_mem_sq` — crude first-order Taylor expansion: the
  remainder lies in the square of the ideal generated by the perturbation.
* `MvPolynomial.taylor_mem_of_coeff` — the refined version Fontaine's step 4 needs,
  which gains a factor of `3` on the quadratic part from the coefficient hypothesis
  `∂P/∂Xⱼ ∈ 3·R[[X]]`.  See the section header below for why this needs no Hasse
  derivatives.
* `MvPolynomial.pderiv_truncTotal` — truncation and differentiation commute, with a
  degree shift of one.
-/

@[expose] public section

/-- Two elements of an `I`-adically complete ring that agree modulo every power of
`I` are equal. -/
theorem IsAdicComplete.eq_of_sub_mem_pow {O : Type*} [CommRing O] (I : Ideal O)
    [IsAdicComplete I O] {a b : O} (h : ∀ n, a - b ∈ I ^ n) : a = b :=
  sub_eq_zero.mp
    (IsHausdorff.haus (IsAdicComplete.toIsHausdorff : IsHausdorff I O) (a - b)
      fun n => SModEq.sub_mem.mpr (by simpa using h n))

/-- Monotonicity of ideal powers in the ideal. -/
theorem Ideal.pow_le_pow_left' {O : Type*} [CommRing O] {J K : Ideal O} (h : J ≤ K) :
    ∀ n : ℕ, J ^ n ≤ K ^ n
  | 0 => by simp
  | n + 1 => by
    rw [pow_succ, pow_succ]
    exact Ideal.mul_mono (Ideal.pow_le_pow_left' h n) h

namespace MvPowerSeries

open Finset (antidiagonal)

section Pderiv

variable {σ : Type*} {R : Type*} [CommRing R]

/-- The formal partial derivative of a multivariate power series with respect to the
variable `j`, defined coefficientwise by `∂(X^n)/∂X_j = n_j · X^(n - e_j)`.

This is a definition only; it is here because Fontaine's argument needs to *state*
that the Jacobian matrix of a power-series presentation is `3` times an invertible
matrix, and this mathlib pin has `Polynomial.derivative`, `MvPolynomial.pderiv` and
`PowerSeries.derivative` but nothing for `MvPowerSeries`. -/
noncomputable def pderiv (j : σ) (f : MvPowerSeries σ R) : MvPowerSeries σ R :=
  fun n => (n j + 1) • coeff (n + Finsupp.single j 1) f

@[simp]
theorem coeff_pderiv (j : σ) (f : MvPowerSeries σ R) (n : σ →₀ ℕ) :
    coeff n (pderiv j f) = (n j + 1) • coeff (n + Finsupp.single j 1) f := by
  simp [pderiv, coeff_apply]

theorem pderiv_add (j : σ) (f g : MvPowerSeries σ R) :
    pderiv j (f + g) = pderiv j f + pderiv j g := by
  ext n
  simp [coeff_pderiv, smul_add]

/-- The reindexing that drives the Leibniz rule: a sum over the antidiagonal of `n`
weighted by `p.1 j + 1` is a sum over the antidiagonal of `n + eⱼ` weighted by
`q.1 j`, the terms with `q.1 j = 0` contributing nothing. -/
theorem coeff_pderiv_mul_left [DecidableEq σ] (j : σ) (f g : MvPowerSeries σ R)
    (n : σ →₀ ℕ) :
    coeff n (pderiv j f * g) =
      ∑ q ∈ (antidiagonal (n + Finsupp.single j 1) : Finset ((σ →₀ ℕ) × (σ →₀ ℕ))),
        (q.1 j) • (coeff q.1 f * coeff q.2 g) := by
  rw [coeff_mul]
  rw [← Finset.sum_filter_add_sum_filter_not
    (antidiagonal (n + Finsupp.single j 1) : Finset ((σ →₀ ℕ) × (σ →₀ ℕ)))
    (fun q => q.1 j ≠ 0)]
  have hzero : ∑ q ∈ (antidiagonal (n + Finsupp.single j 1) :
        Finset ((σ →₀ ℕ) × (σ →₀ ℕ))).filter (fun q => ¬ (q.1 j ≠ 0)),
      (q.1 j) • (coeff q.1 f * coeff q.2 g) = 0 := by
    refine Finset.sum_eq_zero fun q hq => ?_
    simp only [Finset.mem_filter, not_ne_iff] at hq
    rw [hq.2]
    simp
  rw [hzero, add_zero]
  refine Finset.sum_nbij' (fun p => (p.1 + Finsupp.single j 1, p.2))
    (fun q => (q.1 - Finsupp.single j 1, q.2)) ?_ ?_ ?_ ?_ ?_
  · rintro ⟨a, b⟩ hab
    simp only [Finset.mem_antidiagonal] at hab
    simp only [Finset.mem_filter, Finset.mem_antidiagonal]
    refine ⟨by rw [add_right_comm, hab], ?_⟩
    simp
  · rintro ⟨a, b⟩ hab
    simp only [Finset.mem_filter, Finset.mem_antidiagonal, ne_eq] at hab
    simp only [Finset.mem_antidiagonal]
    have h1 : Finsupp.single j 1 ≤ a := by
      rw [Finsupp.single_le_iff]
      omega
    have : a - Finsupp.single j 1 + Finsupp.single j 1 = a := tsub_add_cancel_of_le h1
    have h2 := hab.1
    ext k
    have := congrArg (fun (t : σ →₀ ℕ) => t k) h2
    simp only [Finsupp.add_apply, Finsupp.coe_tsub, Pi.sub_apply] at this ⊢
    have hle : (Finsupp.single j 1 : σ →₀ ℕ) k ≤ a k := h1 k
    omega
  · rintro ⟨a, b⟩ hab
    simp
  · rintro ⟨a, b⟩ hab
    simp only [Finset.mem_filter, Finset.mem_antidiagonal, ne_eq] at hab
    have h1 : Finsupp.single j 1 ≤ a := by
      rw [Finsupp.single_le_iff]
      omega
    simp only [Prod.mk.injEq, and_true]
    exact tsub_add_cancel_of_le h1
  · rintro ⟨a, b⟩ hab
    simp only [coeff_pderiv, Finsupp.add_apply, Finsupp.single_eq_same, smul_mul_assoc]


theorem coeff_pderiv_mul_right [DecidableEq σ] (j : σ) (f g : MvPowerSeries σ R)
    (n : σ →₀ ℕ) :
    coeff n (f * pderiv j g) =
      ∑ q ∈ (antidiagonal (n + Finsupp.single j 1) : Finset ((σ →₀ ℕ) × (σ →₀ ℕ))),
        (q.2 j) • (coeff q.1 f * coeff q.2 g) := by
  rw [mul_comm, coeff_pderiv_mul_left]
  refine Finset.sum_nbij' Prod.swap Prod.swap ?_ ?_ ?_ ?_ ?_
  · rintro ⟨a, b⟩ hab
    simp only [Finset.mem_antidiagonal] at hab ⊢
    rw [add_comm]; exact hab
  · rintro ⟨a, b⟩ hab
    simp only [Finset.mem_antidiagonal] at hab ⊢
    rw [add_comm]; exact hab
  · rintro ⟨a, b⟩ hab; rfl
  · rintro ⟨a, b⟩ hab; rfl
  · rintro ⟨a, b⟩ hab
    simp only [Prod.fst_swap, Prod.snd_swap]
    rw [mul_comm]

/-- **THE LEIBNIZ RULE** for the formal partial derivative of a multivariate power
series. -/
theorem pderiv_mul (j : σ) (f g : MvPowerSeries σ R) :
    pderiv j (f * g) = pderiv j f * g + f * pderiv j g := by
  classical
  ext n
  rw [map_add, coeff_pderiv, coeff_pderiv_mul_left, coeff_pderiv_mul_right, coeff_mul,
    Finset.smul_sum, ← Finset.sum_add_distrib]
  refine Finset.sum_congr rfl fun q hq => ?_
  rw [Finset.mem_antidiagonal] at hq
  rw [← add_smul]
  congr 1
  have h := congrArg (fun t : σ →₀ ℕ => t j) hq
  simpa using h.symm

@[simp]
theorem pderiv_zero (j : σ) : pderiv j (0 : MvPowerSeries σ R) = 0 := by
  ext n; simp [coeff_pderiv]

/-- The derivative of a constant vanishes. -/
@[simp]
theorem pderiv_C (j : σ) (a : R) : pderiv j (C a : MvPowerSeries σ R) = 0 := by
  classical
  ext n
  have h : n + Finsupp.single j 1 ≠ 0 := by
    intro hcon
    have := congrArg (fun t : σ →₀ ℕ => t j) hcon
    simp at this
  simp [coeff_pderiv, coeff_C, h]

theorem pderiv_natCast (j : σ) (m : ℕ) :
    pderiv j (m : MvPowerSeries σ R) = 0 := by
  rw [show ((m : MvPowerSeries σ R)) = C (m : R) by simp, pderiv_C]

/-- **A SPAN WHOSE GENERATORS HAVE THEIR DERIVATIVES INSIDE IT IS A DIFFERENTIAL
IDEAL.**  This is what turns the Jacobian estimate of Fontaine's step 3 into
stability of `ker α + (3)` under every `∂/∂Xⱼ`: only the generators have to be
checked, and the Leibniz rule propagates the property across the span. -/
theorem pderiv_mem_span_of_mem_span (s : Set (MvPowerSeries σ R))
    (hs : ∀ g ∈ s, ∀ j, pderiv j g ∈ Ideal.span s)
    (j : σ) {f : MvPowerSeries σ R} (hf : f ∈ Ideal.span s) :
    pderiv j f ∈ Ideal.span s := by
  induction hf using Submodule.span_induction with
  | mem x hx => exact hs x hx j
  | zero => simp
  | add x y hx hy ihx ihy => rw [pderiv_add]; exact Ideal.add_mem _ ihx ihy
  | smul a x hx ih =>
      rw [smul_eq_mul, pderiv_mul]
      exact Ideal.add_mem _ (Ideal.mul_mem_left _ _ hx) (Ideal.mul_mem_left _ _ ih)


end Pderiv

section KeyLemma

variable {p : ℕ}

/-! ### The `p`-adic slice decomposition of a coefficient family

The machinery the KEY LEMMA below runs on.  A multidegree `n` splits as
`n = p • (expDiv p n) + expMod p n` with every digit of `expMod p n` less than `p`;
`part p b f` collects the coefficients of `f` in the multidegrees congruent to `b`,
and `pExpand p` puts them back.  Everything here is over an arbitrary `CommRing`. -/

section Slices

variable {σ : Type*} {R : Type*} [CommRing R]

/-- `(expDiv p n) j = n j / p`. -/
noncomputable def expDiv (p : ℕ) (n : σ →₀ ℕ) : σ →₀ ℕ := n.mapRange (· / p) (Nat.zero_div p)

/-- `(expMod p n) j = n j % p`. -/
noncomputable def expMod (p : ℕ) (n : σ →₀ ℕ) : σ →₀ ℕ := n.mapRange (· % p) (Nat.zero_mod p)

@[simp] theorem expDiv_apply (p : ℕ) (n : σ →₀ ℕ) (j : σ) : expDiv p n j = n j / p :=
  Finsupp.mapRange_apply

@[simp] theorem expMod_apply (p : ℕ) (n : σ →₀ ℕ) (j : σ) : expMod p n j = n j % p :=
  Finsupp.mapRange_apply

theorem smul_expDiv_add_expMod (p : ℕ) (n : σ →₀ ℕ) :
    p • expDiv p n + expMod p n = n := by
  ext j
  simp only [Finsupp.add_apply, Finsupp.smul_apply, expDiv_apply, expMod_apply, smul_eq_mul]
  exact Nat.div_add_mod (n j) p

theorem expMod_lt (hp : 0 < p) (n : σ →₀ ℕ) (j : σ) : expMod p n j < p := by
  simpa using Nat.mod_lt _ hp

theorem expMod_smul_add {a : σ →₀ ℕ} (ha : ∀ j, a j < p) (q : σ →₀ ℕ) :
    expMod p (p • q + a) = a := by
  ext j
  simp only [expMod_apply, Finsupp.add_apply, Finsupp.smul_apply, smul_eq_mul]
  rw [Nat.mul_add_mod, Nat.mod_eq_of_lt (ha j)]

theorem expDiv_smul_add (hp : 0 < p) {a : σ →₀ ℕ} (ha : ∀ j, a j < p) (q : σ →₀ ℕ) :
    expDiv p (p • q + a) = q := by
  ext j
  simp only [expDiv_apply, Finsupp.add_apply, Finsupp.smul_apply, smul_eq_mul]
  rw [Nat.mul_add_div hp, Nat.div_eq_of_lt (ha j), Nat.add_zero]

theorem expDiv_smul (hp : 0 < p) (q : σ →₀ ℕ) : expDiv p (p • q) = q := by
  have h := expDiv_smul_add (a := (0 : σ →₀ ℕ)) hp (fun _ => by simpa using hp) q
  simpa using h

/-- The `b`-th `p`-adic slice of the coefficient family of `f`. -/
noncomputable def part (p : ℕ) (b : σ →₀ ℕ) (f : MvPowerSeries σ R) : MvPowerSeries σ R :=
  fun q => coeff (p • q + b) f

@[simp] theorem coeff_part (p : ℕ) (b : σ →₀ ℕ) (f : MvPowerSeries σ R) (q : σ →₀ ℕ) :
    coeff q (part p b f) = coeff (p • q + b) f := rfl

/-- Divisibility by `p` in `MvPowerSeries` is tested coefficientwise. -/
theorem mem_span_natCast_iff (f : MvPowerSeries σ R) :
    f ∈ Ideal.span {(p : MvPowerSeries σ R)} ↔
      ∀ n, coeff n f ∈ Ideal.span {(p : R)} := by
  have hC : ((p : ℕ) : MvPowerSeries σ R) = C (p : R) := by simp
  constructor
  · rintro h n
    rw [Ideal.mem_span_singleton'] at h
    obtain ⟨g, rfl⟩ := h
    rw [Ideal.mem_span_singleton']
    exact ⟨coeff n g, by rw [hC, coeff_mul_C]⟩
  · intro h
    rw [Ideal.mem_span_singleton']
    choose c hc using fun n => Ideal.mem_span_singleton'.mp (h n)
    refine ⟨(fun n => c n : MvPowerSeries σ R), ?_⟩
    ext n
    rw [hC, coeff_mul_C, coeff_apply]
    exact hc n

theorem nsmul_mem_ideal {I : Ideal (MvPowerSeries σ R)} {x : MvPowerSeries σ R} (m : ℕ)
    (h : x ∈ I) : m • x ∈ I := by
  rw [nsmul_eq_mul]; exact Ideal.mul_mem_left _ _ h

/-- The `a`-th slice of `∂f/∂Xⱼ` is `(aⱼ+1)` times the `(a+eⱼ)`-th slice of `f`, modulo `p`.
No hypothesis on `a j` is needed: the correction term is literally `(p·qⱼ)·x`. -/
theorem part_pderiv_sub_nsmul_mem {a : σ →₀ ℕ} {j : σ} (f : MvPowerSeries σ R) :
    part p a (pderiv j f) - (a j + 1) • part p (a + Finsupp.single j 1) f ∈
      Ideal.span {(p : MvPowerSeries σ R)} := by
  rw [mem_span_natCast_iff]
  intro q
  rw [map_sub, coeff_part, coeff_pderiv, map_nsmul, coeff_part]
  have hidx : p • q + a + Finsupp.single j 1 = p • q + (a + Finsupp.single j 1) := add_assoc _ _ _
  rw [hidx]
  have hcoef : (p • q + a) j = p * q j + a j := by simp
  rw [hcoef]
  set x := coeff (p • q + (a + Finsupp.single j 1)) f with hx
  have hsplit : (p * q j + a j + 1) • x = (p * q j) • x + (a j + 1) • x := by
    rw [add_assoc, add_smul]
  rw [hsplit, add_sub_cancel_right]
  refine Ideal.mem_span_singleton'.mpr ⟨((q j : ℕ) : R) * x, ?_⟩
  rw [nsmul_eq_mul]
  push_cast
  ring

/-- At the top digit `aⱼ + 1 = p` the `a`-th slice of `∂f/∂Xⱼ` dies modulo `p`. -/
theorem part_pderiv_mem_of_succ_eq {a : σ →₀ ℕ} {j : σ} (haj : a j + 1 = p)
    (f : MvPowerSeries σ R) :
    part p a (pderiv j f) ∈ Ideal.span {(p : MvPowerSeries σ R)} := by
  rw [mem_span_natCast_iff]
  intro q
  rw [coeff_part, coeff_pderiv]
  have hcoef : (p • q + a) j + 1 = p * (q j + 1) := by
    have h0 : (p • q + a) j = p * q j + a j := by simp
    rw [h0, add_assoc, haj]; ring
  rw [hcoef]
  refine Ideal.mem_span_singleton'.mpr
    ⟨((q j + 1 : ℕ) : R) * coeff (p • q + a + Finsupp.single j 1) f, ?_⟩
  rw [nsmul_eq_mul]
  push_cast
  ring

theorem sum_id_eq_zero {c : σ →₀ ℕ} (hc : (c.sum fun _ k => k) = 0) : c = 0 := by
  ext j
  by_contra hne
  have hj : j ∈ c.support := Finsupp.mem_support_iff.mpr (by simpa using hne)
  have hle : c j ≤ c.sum fun _ k => k :=
    Finset.single_le_sum (f := fun a => c a) (fun _ _ => Nat.zero_le _) hj
  simp only [Finsupp.coe_zero, Pi.zero_apply] at hne
  omega

section Expand

variable [DecidableEq σ]

/-- `pExpand p g` is `g` with every exponent multiplied by `p`. -/
noncomputable def pExpand (p : ℕ) (g : MvPowerSeries σ R) : MvPowerSeries σ R :=
  fun n => if p • expDiv p n = n then coeff (expDiv p n) g else 0

theorem coeff_pExpand (p : ℕ) (g : MvPowerSeries σ R) (n : σ →₀ ℕ) :
    coeff n (pExpand p g) =
      if p • expDiv p n = n then coeff (expDiv p n) g else 0 := rfl

theorem coeff_pExpand_smul (hp : 0 < p) (g : MvPowerSeries σ R) (q : σ →₀ ℕ) :
    coeff (p • q) (pExpand p g) = coeff q g := by
  rw [coeff_pExpand, expDiv_smul hp, if_pos rfl]

theorem coeff_pExpand_of_ne {n : σ →₀ ℕ} (g : MvPowerSeries σ R)
    (h : ¬ p • expDiv p n = n) : coeff n (pExpand p g) = 0 := by
  rw [coeff_pExpand, if_neg h]

theorem pExpand_sub (g₁ g₂ : MvPowerSeries σ R) :
    pExpand p (g₁ - g₂) = pExpand p g₁ - pExpand p g₂ := by
  ext n
  simp only [coeff_pExpand, map_sub]
  by_cases h : p • expDiv p n = n <;> simp [h]

theorem pExpand_nsmul (m : ℕ) (g : MvPowerSeries σ R) :
    pExpand p (m • g) = m • pExpand p g := by
  ext n
  simp only [coeff_pExpand, map_nsmul]
  by_cases h : p • expDiv p n = n <;> simp [h]

theorem pExpand_mem_of_mem {x : MvPowerSeries σ R}
    (h : x ∈ Ideal.span {(p : MvPowerSeries σ R)}) :
    pExpand p x ∈ Ideal.span {(p : MvPowerSeries σ R)} := by
  rw [mem_span_natCast_iff] at h ⊢
  intro n
  rw [coeff_pExpand]
  by_cases hd : p • expDiv p n = n
  · rw [if_pos hd]; exact h _
  · rw [if_neg hd]; exact Ideal.zero_mem _

/-- **THE SLICE FORMULA.**  `pExpand p (part p b f) * X^b` is the part of `f` supported
on the multidegrees congruent to `b` modulo `p`. -/
theorem coeff_pExpand_part_mul_monomial (hp : 0 < p) {b : σ →₀ ℕ} (hb : ∀ j, b j < p)
    (f : MvPowerSeries σ R) (n : σ →₀ ℕ) :
    coeff n (pExpand p (part p b f) * monomial b (1 : R)) =
      if expMod p n = b then coeff n f else 0 := by
  rw [coeff_mul_monomial]
  by_cases hmb : expMod p n = b
  · have hble : b ≤ n := by
      refine Finsupp.le_def.mpr fun j => ?_
      have hbj : b j = n j % p := by rw [← hmb]; simp
      rw [hbj]; exact Nat.mod_le _ _
    rw [if_pos hble, if_pos hmb, mul_one]
    have hnb : n - b = p • expDiv p n := by
      ext j
      simp only [Finsupp.coe_tsub, Pi.sub_apply, Finsupp.smul_apply, expDiv_apply, smul_eq_mul]
      have hbj : b j = n j % p := by rw [← hmb]; simp
      have hdm := Nat.div_add_mod (n j) p
      omega
    rw [hnb, coeff_pExpand_smul hp, coeff_part, ← hmb, smul_expDiv_add_expMod]
  · rw [if_neg hmb]
    by_cases hble : b ≤ n
    · rw [if_pos hble]
      have hne : ¬ p • expDiv p (n - b) = n - b := by
        intro hcon
        refine hmb (Finsupp.ext fun j => ?_)
        have h1 : (p • expDiv p (n - b)) j = (n - b) j := by rw [hcon]
        simp only [Finsupp.smul_apply, smul_eq_mul, expDiv_apply, Finsupp.coe_tsub,
          Pi.sub_apply] at h1
        have h2 : b j ≤ n j := Finsupp.le_def.mp hble j
        have h4 : n j = p * ((n j - b j) / p) + b j := by omega
        simp only [expMod_apply]
        rw [h4, Nat.mul_add_mod, Nat.mod_eq_of_lt (hb j)]
      rw [coeff_pExpand_of_ne _ hne, zero_mul]
    · rw [if_neg hble]

/-- Every partial derivative of a `p`-expanded series is divisible by `p`. -/
theorem pderiv_pExpand_mem (j : σ) (g : MvPowerSeries σ R) :
    pderiv j (pExpand p g) ∈ Ideal.span {(p : MvPowerSeries σ R)} := by
  rw [mem_span_natCast_iff]
  intro n
  rw [coeff_pderiv]
  by_cases hd : p • expDiv p (n + Finsupp.single j 1) = n + Finsupp.single j 1
  · set d := expDiv p (n + Finsupp.single j 1) with hddef
    have h1 : p * d j = n j + 1 := by
      have h2 : (p • d : σ →₀ ℕ) j = (n + Finsupp.single j 1 : σ →₀ ℕ) j := by rw [hd]
      simpa using h2
    refine Ideal.mem_span_singleton'.mpr
      ⟨((d j : ℕ) : R) * coeff (n + Finsupp.single j 1) (pExpand p g), ?_⟩
    rw [nsmul_eq_mul, ← h1]
    push_cast
    ring
  · rw [coeff_pExpand_of_ne _ hd, smul_zero]
    exact Ideal.zero_mem _

/-- The base case of the extraction: if every slice of `f` other than the `0`-th is
divisible by `p`, the `0`-th slice, expanded, differs from `f` by a multiple of `p`. -/
theorem pExpand_part_zero_mem (hp : 0 < p) {𝔞 : Ideal (MvPowerSeries σ R)}
    (hpmem : (p : MvPowerSeries σ R) ∈ 𝔞) {f : MvPowerSeries σ R} (hf : f ∈ 𝔞)
    (hzero : ∀ a, (∀ j, a j < p) → a ≠ 0 →
      part p a f ∈ Ideal.span {(p : MvPowerSeries σ R)}) :
    pExpand p (part p 0 f) ∈ 𝔞 := by
  have hple : Ideal.span {(p : MvPowerSeries σ R)} ≤ 𝔞 := by
    rw [Ideal.span_le]; rintro x hx; rw [Set.mem_singleton_iff] at hx; rw [hx]; exact hpmem
  have hb0 : ∀ j, (0 : σ →₀ ℕ) j < p := fun _ => by simpa using hp
  have hdiff : f - pExpand p (part p 0 f) * monomial (0 : σ →₀ ℕ) (1 : R) ∈
      Ideal.span {(p : MvPowerSeries σ R)} := by
    rw [mem_span_natCast_iff]
    intro n
    rw [map_sub, coeff_pExpand_part_mul_monomial hp hb0 f n]
    by_cases hm : expMod p n = 0
    · rw [if_pos hm, sub_self]; exact Ideal.zero_mem _
    · rw [if_neg hm, sub_zero]
      have ha := hzero (expMod p n) (expMod_lt hp n) hm
      rw [mem_span_natCast_iff] at ha
      have := ha (expDiv p n)
      rwa [coeff_part, smul_expDiv_add_expMod] at this
  have hs1 : pExpand p (part p 0 f) * monomial (0 : σ →₀ ℕ) (1 : R) =
      pExpand p (part p 0 f) := by simp
  rw [hs1] at hdiff
  have h2 := Ideal.sub_mem 𝔞 hf (hple hdiff)
  simpa using h2

/-- **THE EXTRACTION.**  Induction on the total degree of `b`, peeling one derivative at
a time: no iterated (Hasse) derivative is ever formed. -/
theorem pExpand_part_mem (hp : p.Prime) {𝔞 : Ideal (MvPowerSeries σ R)}
    (hpmem : (p : MvPowerSeries σ R) ∈ 𝔞)
    (hstab : ∀ (j : σ) (f : MvPowerSeries σ R), f ∈ 𝔞 → pderiv j f ∈ 𝔞) :
    ∀ (N : ℕ) (b : σ →₀ ℕ), (b.sum fun _ k => k) ≤ N → (∀ j, b j < p) →
      ∀ f ∈ 𝔞,
        (∀ a, (∀ j, a j < p) → b ≤ a → a ≠ b →
          part p a f ∈ Ideal.span {(p : MvPowerSeries σ R)}) →
        pExpand p (part p b f) ∈ 𝔞 := by
  have hple : Ideal.span {(p : MvPowerSeries σ R)} ≤ 𝔞 := by
    rw [Ideal.span_le]; rintro x hx; rw [Set.mem_singleton_iff] at hx; rw [hx]; exact hpmem
  intro N
  induction N with
  | zero =>
    intro b hdeg hb f hf hmax
    have hb0 : b = 0 := sum_id_eq_zero (Nat.le_zero.mp hdeg)
    subst hb0
    exact pExpand_part_zero_mem hp.pos hpmem hf (fun a ha hne => hmax a ha (Finsupp.le_def.mpr fun _ => Nat.zero_le _) hne)
  | succ N ih =>
    intro b hdeg hb f hf hmax
    by_cases hb0 : b = 0
    · subst hb0
      exact pExpand_part_zero_mem hp.pos hpmem hf (fun a ha hne => hmax a ha (Finsupp.le_def.mpr fun _ => Nat.zero_le _) hne)
    · obtain ⟨j, hj⟩ : ∃ j, b j ≠ 0 := by
        by_contra hcon
        push Not at hcon
        exact hb0 (Finsupp.ext fun j => by simpa using hcon j)
      have hle : Finsupp.single j 1 ≤ b := Finsupp.single_le_iff.mpr (by omega)
      set b' := b - Finsupp.single j 1 with hb'def
      have hbb' : b' + Finsupp.single j 1 = b := tsub_add_cancel_of_le hle
      have hb'j : b' j + 1 = b j := by
        have h := congrArg (fun t : σ →₀ ℕ => t j) hbb'
        simpa using h
      have hb'box : ∀ k, b' k < p := by
        intro k
        have hkk : b' k ≤ b k := by
          rw [← hbb']; simp
        exact lt_of_le_of_lt hkk (hb k)
      have hdeg' : (b'.sum fun _ k => k) ≤ N := by
        have hsum : (b.sum fun _ k => k) = (b'.sum fun _ k => k) + 1 := by
          conv_lhs => rw [← hbb']
          rw [Finsupp.sum_add_index' (fun _ => rfl) (fun _ _ _ => rfl),
            Finsupp.sum_single_index rfl]
        omega
      have hmax' : ∀ a, (∀ k, a k < p) → b' ≤ a → a ≠ b' →
          part p a (pderiv j f) ∈ Ideal.span {(p : MvPowerSeries σ R)} := by
        intro a ha hb'a hab'
        by_cases haj : a j + 1 < p
        · have hbox2 : ∀ k, (a + Finsupp.single j 1 : σ →₀ ℕ) k < p := by
            intro k
            by_cases hk : k = j
            · subst hk; simpa using haj
            · have : (a + Finsupp.single j 1 : σ →₀ ℕ) k = a k := by
                simp [Ne.symm hk]
              rw [this]; exact ha k
          have hmem : part p (a + Finsupp.single j 1) f ∈
              Ideal.span {(p : MvPowerSeries σ R)} := by
            refine hmax (a + Finsupp.single j 1) hbox2 ?_ ?_
            · rw [← hbb']
              refine Finsupp.le_def.mpr fun k => ?_
              simp only [Finsupp.add_apply]
              exact Nat.add_le_add_right (Finsupp.le_def.mp hb'a k) _
            · intro hcon
              refine hab' ?_
              rw [← hbb'] at hcon
              exact add_right_cancel hcon
          have hstep := part_pderiv_sub_nsmul_mem (p := p) (a := a) (j := j) f
          have := Ideal.add_mem _ hstep (nsmul_mem_ideal (a j + 1) hmem)
          simpa using this
        · have haj' : a j + 1 = p := by have := ha j; omega
          exact part_pderiv_mem_of_succ_eq haj' f
      have hIH := ih b' hdeg' hb'box (pderiv j f) (hstab j f hf) hmax'
      -- relate the `b'`-slice of `∂f` to `b j` times the `b`-slice of `f`
      have hkey : pExpand p (part p b' (pderiv j f)) -
          (b j) • pExpand p (part p b f) ∈ Ideal.span {(p : MvPowerSeries σ R)} := by
        have h0 := part_pderiv_sub_nsmul_mem (p := p) (a := b') (j := j) f
        rw [hb'j, hbb'] at h0
        have h1 := pExpand_mem_of_mem h0
        rwa [pExpand_sub, pExpand_nsmul] at h1
      have hbjy : (b j) • pExpand p (part p b f) ∈ 𝔞 := by
        have := Ideal.sub_mem 𝔞 hIH (hple hkey)
        simpa using this
      -- divide by `b j`, which is prime to `p`
      have hcop : Nat.Coprime p (b j) := by
        refine (Nat.Prime.coprime_iff_not_dvd hp).mpr ?_
        intro hdvd
        have := Nat.le_of_dvd (by omega) hdvd
        have := hb j
        omega
      obtain ⟨A, B, hAB⟩ : ∃ A B : ℤ, (1 : ℤ) = (p : ℤ) * A + ((b j : ℕ) : ℤ) * B := by
        refine ⟨Nat.gcdA p (b j), Nat.gcdB p (b j), ?_⟩
        have h := Nat.gcd_eq_gcd_ab p (b j)
        rw [hcop] at h
        exact_mod_cast h
      set y := pExpand p (part p b f) with hydef
      have hone : (1 : MvPowerSeries σ R) =
          (p : MvPowerSeries σ R) * ((A : ℤ) : MvPowerSeries σ R) +
          ((b j : ℕ) : MvPowerSeries σ R) * ((B : ℤ) : MvPowerSeries σ R) := by
        have h := congrArg (fun z : ℤ => (z : MvPowerSeries σ R)) hAB
        push_cast at h
        exact_mod_cast h
      have hyeq : y = (p : MvPowerSeries σ R) * (((A : ℤ) : MvPowerSeries σ R) * y) +
          ((((b j : ℕ) : MvPowerSeries σ R)) * y) * ((B : ℤ) : MvPowerSeries σ R) := by
        calc y = 1 * y := (one_mul y).symm
        _ = ((p : MvPowerSeries σ R) * ((A : ℤ) : MvPowerSeries σ R) +
              ((b j : ℕ) : MvPowerSeries σ R) * ((B : ℤ) : MvPowerSeries σ R)) * y := by
              rw [← hone]
        _ = _ := by ring
      rw [hyeq]
      refine Ideal.add_mem _ (Ideal.mul_mem_right _ _ hpmem) (Ideal.mul_mem_right _ _ ?_)
      rw [← nsmul_eq_mul]
      exact hbjy

end Expand

end Slices

/-- **THE KEY LEMMA OF FONTAINE'S STEP 3** (**PROVEN 2026-07-31**; cut the same day
out of `GaloisRepresentation.IsHardlyRamified.exists_pderiv_eq_of_minimalPresentation`):
*a differential ideal containing `p` is generated by `p` together with the
elements whose derivatives are all divisible by `p`.*

In the classical formulation — `k` a field of characteristic `p`,
`R̄ = k[[X₁,…,X_h]]`, `S = k[[X₁^p,…,X_h^p]]` — this says that an ideal of `R̄`
stable under every `∂/∂Xⱼ` is generated by `𝔞 ∩ S`.  The form below is that
statement transported back across `R ↠ R/pR`, which is why it needs no field and
no quotient: `{f | ∀ j, ∂f/∂Xⱼ ∈ (p)}` is the preimage of `S`, and the classical
`𝔞 = (𝔞 ∩ S)·R̄` becomes `𝔞 = ({p} ∪ (𝔞 ∩ preimage of S))·R`.

PROOF (three steps, no differential equation — an earlier reading of the parent
leaf guessed that one had to solve `∂u/∂Xⱼ = −u·Cⱼ` over `𝔽₃[[X]]`, and that
guess is wrong; see the SECOND FALSITY AUDIT on `exists_fontainePresentation`).

1. *Box decomposition.*  Every `f : MvPowerSeries σ 𝒪` is uniquely
   `f = ∑_{a ∈ box} s_a · X^a`, the sum over the finite `box = {a | ∀ j, a j < p}`
   and each `s_a` supported on exponents divisible by `p` (group the monomials of
   `f` by the residue of their exponent mod `p`).  This is an identity over ANY
   commutative ring; no perfectness and no `p`-th roots are involved.
2. *Maximal-term extraction.*  Write `T^{(b)} := ∏_j (∂/∂Xⱼ)^{b_j}`.  Since each
   `s_a` has all exponents divisible by `p`, `∂ⱼ s_a ∈ (p)`, so by Leibniz
   `T^{(b)}(s_a X^a) ≡ s_a · T^{(b)}(X^a) (mod p)`, and `T^{(b)} X^a = 0` unless
   `a ≥ b` componentwise.  Take `a₀` MAXIMAL for the componentwise order in the
   (finite) set of `a ∈ box` with `s_a ≠ 0`; then every other surviving `a` fails
   `a ≥ a₀`, so `T^{(a₀)} f ≡ (∏_j a₀_j !) · s_{a₀} (mod p)`.  The ideal is
   `∂`-stable, so the left side lies in `𝔞`; `p ∈ 𝔞`; and `∏_j a₀_j !` is a
   product of factorials of naturals `< p`, hence an integer PRIME TO `p`, hence
   invertible mod `p`.  Multiplying by an inverse and correcting by a multiple of
   `p` gives `s_{a₀} ∈ 𝔞`.  This is the only place primality of `p` is used.
3. *Induction.*  `s_{a₀}` has all its exponents divisible by `p`, so all its
   derivatives lie in `(p)`: it belongs to the generating set.  Replace `f` by
   `f − s_{a₀} X^{a₀} ∈ 𝔞`, whose box support is strictly smaller, and induct on
   the cardinality of that support.

The reverse inclusion is immediate: `p ∈ 𝔞` by hypothesis and the second half of
the generating set is contained in `𝔞` by construction.

# THE ROUTE ACTUALLY TAKEN, AND WHY IT IS CHEAPER THAN THE ONE PRESCRIBED ABOVE

The sketch is correct and was followed for steps 1 and 3.  **Step 2 was NOT: no
iterated derivative `T^{(b)}` is ever formed, and no Hasse-derivative API, no
freeness of `R̄` over `S` on the box monomials, and no factorial is needed.**
Three earlier route notes on this leaf and on its parent all priced a multivariate
Hasse-derivative development (the pin has one only for univariate `Polynomial`) as
the thing to build; that estimate was wrong, in the way CLAUDE.md's *ASK WHAT THE
CRUDE BOUND ALREADY GIVES* section describes.

What replaces it is `pExpand_part_mem` below: an induction on the TOTAL DEGREE of
`b`, peeling ONE derivative at a time.  Writing `b = b' + eⱼ`, the `b'`-th slice of
`∂f/∂Xⱼ` is `bⱼ` times the `b`-th slice of `f` **modulo `p`** — that is
`part_pderiv_sub_nsmul_mem`, which holds with NO hypothesis at all because the
error term is literally `(p·qⱼ)·x`.  So one derivative lowers the degree by one and
multiplies the slice by the single factor `bⱼ`, and only `bⱼ` (not `∏ a₀ⱼ!`) has to
be inverted mod `p`.  The digit at the top of the range, `aⱼ + 1 = p`, is the
separate one-line `part_pderiv_mem_of_succ_eq`.  Primality of `p` is still used
exactly once, for `Nat.Coprime p bⱼ` and the resulting Bézout relation.

`S` is likewise never constructed.  `MvPowerSeries.expand`
(`Mathlib/RingTheory/MvPowerSeries/Expand.lean`) would have supplied it, but it is
built on `MvPowerSeries.Substitution` and so would have dragged a topology cone into
this file and into everything below it — against the whole point of stating the lemma
in the `p`-divisibility form.  The ten-line `pExpand` below has the two properties
the proof consumes (`coeff_pExpand_smul`, `coeff_pExpand_of_ne`) and costs no import.

The reusable pieces this leaves behind, all stated over an arbitrary `CommRing`:
`expDiv`/`expMod` (the `p`-adic digits of a multidegree), `part` (the `b`-th slice of
a coefficient family), `pExpand`, the coefficientwise criterion
`mem_span_natCast_iff` for divisibility by `p` in `MvPowerSeries`, the slice formula
`coeff_pExpand_part_mul_monomial`, and `pderiv_pExpand_mem` (a `p`-expanded series
has every partial derivative divisible by `p` — the "a cube has vanishing
derivative" half, over any base). -/
theorem span_insert_setOf_forall_pderiv_mem_eq
    {σ : Type*} [Finite σ] [DecidableEq σ] {𝒪 : Type*} [CommRing 𝒪]
    [hp : Fact p.Prime] (𝔞 : Ideal (MvPowerSeries σ 𝒪))
    (hpmem : (p : MvPowerSeries σ 𝒪) ∈ 𝔞)
    (hstab : ∀ (j : σ) (f : MvPowerSeries σ 𝒪), f ∈ 𝔞 → pderiv j f ∈ 𝔞) :
    𝔞 = Ideal.span ({(p : MvPowerSeries σ 𝒪)} ∪
      {f | f ∈ 𝔞 ∧ ∀ j, pderiv j f ∈ Ideal.span {(p : MvPowerSeries σ 𝒪)}}) := by
  classical
  have hppos : 0 < p := hp.out.pos
  -- the box of multidegrees with all digits `< p` is finite because `σ` is
  have hboxfin : Set.Finite {a : σ →₀ ℕ | ∀ j, a j < p} := by
    haveI : Finite ↥{a : σ →₀ ℕ | ∀ j, a j < p} := by
      refine Finite.of_injective
        (fun (a : ↥{a : σ →₀ ℕ | ∀ j, a j < p}) => (fun j => (⟨a.1 j, a.2 j⟩ : Fin p))) ?_
      rintro ⟨a, ha⟩ ⟨b, hb⟩ hab
      refine Subtype.ext (Finsupp.ext fun j => ?_)
      have h := congrFun hab j
      simpa using h
    exact Set.toFinite _
  set 𝔟 := Ideal.span ({(p : MvPowerSeries σ 𝒪)} ∪
      {f | f ∈ 𝔞 ∧ ∀ j, pderiv j f ∈ Ideal.span {(p : MvPowerSeries σ 𝒪)}}) with h𝔟
  refine le_antisymm ?_ ?_
  · -- the substantial direction
    have hempty : ∀ f : MvPowerSeries σ 𝒪,
        (∀ a, (∀ j, a j < p) → part p a f ∈ Ideal.span {(p : MvPowerSeries σ 𝒪)}) →
        f ∈ Ideal.span {(p : MvPowerSeries σ 𝒪)} := by
      intro f hall
      rw [mem_span_natCast_iff]
      intro n
      have ha := hall (expMod p n) (expMod_lt hppos n)
      rw [mem_span_natCast_iff] at ha
      have h := ha (expDiv p n)
      rwa [coeff_part, smul_expDiv_add_expMod] at h
    have hpb : Ideal.span {(p : MvPowerSeries σ 𝒪)} ≤ 𝔟 :=
      Ideal.span_mono Set.subset_union_left
    have main : ∀ (N : ℕ) (f : MvPowerSeries σ 𝒪), f ∈ 𝔞 →
        (hboxfin.toFinset.filter
          (fun a => part p a f ∉ Ideal.span {(p : MvPowerSeries σ 𝒪)})).card ≤ N → f ∈ 𝔟 := by
      intro N
      induction N with
      | zero =>
        intro f hf hcard
        refine hpb (hempty f fun a ha => ?_)
        by_contra hcon
        have hmem : a ∈ hboxfin.toFinset.filter
            (fun a => part p a f ∉ Ideal.span {(p : MvPowerSeries σ 𝒪)}) := by
          simp only [Finset.mem_filter, Set.Finite.mem_toFinset, Set.mem_setOf_eq]
          exact ⟨ha, hcon⟩
        have := Finset.card_pos.mpr ⟨a, hmem⟩
        omega
      | succ N ih =>
        intro f hf hcard
        by_cases hemp : (hboxfin.toFinset.filter
            (fun a => part p a f ∉ Ideal.span {(p : MvPowerSeries σ 𝒪)})).Nonempty
        · obtain ⟨b, hbmem, hbmax⟩ := Finset.exists_max_image _
            (fun a : σ →₀ ℕ => a.sum fun _ k => k) hemp
          simp only [Finset.mem_filter, Set.Finite.mem_toFinset, Set.mem_setOf_eq] at hbmem
          obtain ⟨hbbox, hbpart⟩ := hbmem
          -- a `deg`-maximal element of the support is maximal for the componentwise order
          have hmaxord : ∀ a, (∀ j, a j < p) → b ≤ a → a ≠ b →
              part p a f ∈ Ideal.span {(p : MvPowerSeries σ 𝒪)} := by
            intro a ha hba hab
            by_contra hcon
            have haB : a ∈ hboxfin.toFinset.filter
                (fun a => part p a f ∉ Ideal.span {(p : MvPowerSeries σ 𝒪)}) := by
              simp only [Finset.mem_filter, Set.Finite.mem_toFinset, Set.mem_setOf_eq]
              exact ⟨ha, hcon⟩
            have h1 := hbmax a haB
            have hsplit : b + (a - b) = a := add_tsub_cancel_of_le hba
            have hne : a - b ≠ 0 := by
              intro h0
              exact hab (by rw [← hsplit, h0, add_zero])
            have hsum : (a.sum fun _ k => k)
                = (b.sum fun _ k => k) + ((a - b).sum fun _ k => k) := by
              conv_lhs => rw [← hsplit]
              exact Finsupp.sum_add_index' (fun _ => rfl) (fun _ _ _ => rfl)
            have hpos : 0 < ((a - b).sum fun _ k => k) := by
              rcases Nat.eq_zero_or_pos ((a - b).sum fun _ k => k) with h | h
              · exact absurd (sum_id_eq_zero h) hne
              · exact h
            omega
          set s := pExpand p (part p b f) with hsdef
          have hs𝔞 : s ∈ 𝔞 :=
            pExpand_part_mem hp.out hpmem hstab _ b le_rfl hbbox f hf hmaxord
          have hsT : s ∈ ({(p : MvPowerSeries σ 𝒪)} ∪
              {f | f ∈ 𝔞 ∧ ∀ j, pderiv j f ∈ Ideal.span {(p : MvPowerSeries σ 𝒪)}}) :=
            Or.inr ⟨hs𝔞, fun j => pderiv_pExpand_mem j _⟩
          set g := s * monomial b (1 : 𝒪) with hgdef
          have hg𝔟 : g ∈ 𝔟 := Ideal.mul_mem_right _ _ (Ideal.subset_span hsT)
          have hg𝔞 : g ∈ 𝔞 := Ideal.mul_mem_right _ _ hs𝔞
          have hcoeff : ∀ n, coeff n (f - g) = if expMod p n = b then 0 else coeff n f := by
            intro n
            rw [map_sub, hgdef, hsdef, coeff_pExpand_part_mul_monomial hppos hbbox f n]
            by_cases hm : expMod p n = b <;> simp [hm]
          have hpart' : ∀ a, (∀ j, a j < p) →
              part p a (f - g) = if a = b then 0 else part p a f := by
            intro a ha
            ext q
            rw [coeff_part, hcoeff, expMod_smul_add ha]
            by_cases hab : a = b <;> simp [hab]
          have hcard' : (hboxfin.toFinset.filter
              (fun a => part p a (f - g) ∉ Ideal.span {(p : MvPowerSeries σ 𝒪)})).card ≤ N := by
            have hbB : b ∈ hboxfin.toFinset.filter
                (fun a => part p a f ∉ Ideal.span {(p : MvPowerSeries σ 𝒪)}) := by
              simp only [Finset.mem_filter, Set.Finite.mem_toFinset, Set.mem_setOf_eq]
              exact ⟨hbbox, hbpart⟩
            have hsub : (hboxfin.toFinset.filter
                (fun a => part p a (f - g) ∉ Ideal.span {(p : MvPowerSeries σ 𝒪)})) ⊆
                (hboxfin.toFinset.filter
                  (fun a => part p a f ∉ Ideal.span {(p : MvPowerSeries σ 𝒪)})).erase b := by
              intro a ha
              simp only [Finset.mem_filter, Set.Finite.mem_toFinset, Set.mem_setOf_eq] at ha
              obtain ⟨habox, hane⟩ := ha
              have hab : a ≠ b := by
                intro h
                subst h
                rw [hpart' a habox, if_pos rfl] at hane
                exact hane (Ideal.zero_mem _)
              refine Finset.mem_erase.mpr ⟨hab, ?_⟩
              simp only [Finset.mem_filter, Set.Finite.mem_toFinset, Set.mem_setOf_eq]
              refine ⟨habox, ?_⟩
              rwa [hpart' a habox, if_neg hab] at hane
            have h2 := Finset.card_le_card hsub
            rw [Finset.card_erase_of_mem hbB] at h2
            have h3 := Finset.card_pos.mpr ⟨b, hbB⟩
            omega
          have hfg : f = (f - g) + g := by ring
          rw [hfg]
          exact Ideal.add_mem _ (ih (f - g) (Ideal.sub_mem _ hf hg𝔞) hcard') hg𝔟
        · rw [Finset.not_nonempty_iff_eq_empty] at hemp
          refine hpb (hempty f fun a ha => ?_)
          by_contra hcon
          have hmem : a ∈ hboxfin.toFinset.filter
              (fun a => part p a f ∉ Ideal.span {(p : MvPowerSeries σ 𝒪)}) := by
            simp only [Finset.mem_filter, Set.Finite.mem_toFinset, Set.mem_setOf_eq]
            exact ⟨ha, hcon⟩
          rw [hemp] at hmem
          simp at hmem
    intro f hf
    exact main _ f hf le_rfl
  · rw [h𝔟, Ideal.span_le]
    rintro x hx
    rcases hx with hx | hx
    · rw [Set.mem_singleton_iff] at hx
      rw [hx]; exact hpmem
    · exact hx.1

end KeyLemma

section AdicEval

variable {σ : Type*} [Finite σ] {R : Type*} [CommRing R]
  {O : Type*} [CommRing O] [Algebra R O]

omit [Finite σ] in
/-- `MvPolynomial.aeval w` carries the `k`-th power of the ideal of variables into
`I ^ k`, as soon as every `w i` lies in `I`. -/
theorem aeval_mem_pow_of_mem_pow_idealOfVars {I : Ideal O} {w : σ → O}
    (hw : ∀ i, w i ∈ I) (k : ℕ) {a : MvPolynomial σ R}
    (ha : a ∈ (MvPolynomial.idealOfVars σ R) ^ k) :
    MvPolynomial.aeval w a ∈ I ^ k := by
  have h0 : Ideal.map ((MvPolynomial.aeval w : MvPolynomial σ R →ₐ[R] O) :
      MvPolynomial σ R →+* O) (MvPolynomial.idealOfVars σ R) ≤ I := by
    rw [MvPolynomial.idealOfVars, Ideal.map_span, Ideal.span_le]
    rintro y ⟨z, hz, rfl⟩
    obtain ⟨i, rfl⟩ := hz
    simpa using hw i
  have h1 : Ideal.map ((MvPolynomial.aeval w : MvPolynomial σ R →ₐ[R] O) :
      MvPolynomial σ R →+* O) ((MvPolynomial.idealOfVars σ R) ^ k) ≤ I ^ k := by
    rw [Ideal.map_pow]
    exact Ideal.pow_le_pow_left' h0 k
  exact h1 (Ideal.mem_map_of_mem _ ha)

variable (I : Ideal O) (w : σ → O) (hw : ∀ i, w i ∈ I)

/-- Evaluation of a multivariate power series at `w` modulo `I ^ n`: only the
degree-`< n` part of the series contributes, so this is an honest finite sum. -/
noncomputable def adicEvalAux (n : ℕ) : MvPowerSeries σ R →ₐ[R] O ⧸ I ^ n :=
  (Ideal.Quotient.liftₐ ((MvPolynomial.idealOfVars σ R) ^ n)
      ((Ideal.Quotient.mkₐ R (I ^ n)).comp (MvPolynomial.aeval w))
      (fun a ha => by
        have h := aeval_mem_pow_of_mem_pow_idealOfVars (R := R) hw n ha
        show Ideal.Quotient.mk (I ^ n) (MvPolynomial.aeval w a) = 0
        rwa [Ideal.Quotient.eq_zero_iff_mem])).comp
    ((truncTotalAlgHom σ R n).restrictScalars R)

theorem adicEvalAux_apply (n : ℕ) (p : MvPowerSeries σ R) :
    adicEvalAux I w hw n p =
      Ideal.Quotient.mk (I ^ n) (MvPolynomial.aeval w (truncTotal n p)) := rfl

theorem adicEvalAux_compat {m n : ℕ} (hle : m ≤ n) :
    (Ideal.Quotient.factorₐ R (Ideal.pow_le_pow_right (I := I) hle)).comp
        (adicEvalAux I w hw n) = adicEvalAux I w hw m := by
  refine AlgHom.ext fun p => ?_
  have hsub : truncTotal n p - truncTotal m p ∈ (MvPolynomial.idealOfVars σ R) ^ m :=
    truncTotal_sub_truncTotal_mem_pow_idealOfVars hle (le_refl m) p
  have hmem : MvPolynomial.aeval w (truncTotal n p) -
      MvPolynomial.aeval w (truncTotal m p) ∈ I ^ m := by
    have := aeval_mem_pow_of_mem_pow_idealOfVars (R := R) hw m hsub
    simpa using this
  simp only [AlgHom.comp_apply, adicEvalAux_apply]
  rw [show (Ideal.Quotient.factorₐ R (Ideal.pow_le_pow_right (I := I) hle))
      (Ideal.Quotient.mk (I ^ n) (MvPolynomial.aeval w (truncTotal n p))) =
      Ideal.Quotient.mk (I ^ m) (MvPolynomial.aeval w (truncTotal n p)) from rfl,
    Ideal.Quotient.mk_eq_mk_iff_sub_mem]
  exact hmem

variable [IsAdicComplete I O]

/-- **Evaluation of a multivariate power series at a tuple drawn from an ideal of an
adically complete ring.**  If `O` is `I`-adically complete and every `w i` lies in
`I`, then `f ↦ f(w)` is a well-defined `R`-algebra map `MvPowerSeries σ R →ₐ[R] O`.

No topology on `O` is used: the map is assembled by `IsAdicComplete.liftAlgHom`
from the truncated evaluations `adicEvalAux`. -/
noncomputable def adicEval : MvPowerSeries σ R →ₐ[R] O :=
  IsAdicComplete.liftAlgHom I (adicEvalAux I w hw) (adicEvalAux_compat I w hw)

@[simp]
theorem mk_adicEval (n : ℕ) (p : MvPowerSeries σ R) :
    Ideal.Quotient.mk (I ^ n) (adicEval I w hw p) =
      Ideal.Quotient.mk (I ^ n) (MvPolynomial.aeval w (truncTotal n p)) := by
  rw [adicEval, IsAdicComplete.mk_liftAlgHom I (adicEvalAux I w hw)
    (adicEvalAux_compat I w hw) n p, adicEvalAux_apply]

theorem adicEval_sub_mem_pow (n : ℕ) (p : MvPowerSeries σ R) :
    adicEval I w hw p - MvPolynomial.aeval w (truncTotal n p) ∈ I ^ n := by
  rw [← Ideal.Quotient.mk_eq_mk_iff_sub_mem]
  exact mk_adicEval I w hw n p

@[simp]
theorem adicEval_coe (p : MvPolynomial σ R) :
    adicEval I w hw (p : MvPowerSeries σ R) = MvPolynomial.aeval w p := by
  refine IsAdicComplete.eq_of_sub_mem_pow I fun n => ?_
  set N := max n (p.totalDegree + 1) with hN
  have hlt : p.totalDegree < N := lt_of_lt_of_le (Nat.lt_succ_self _) (le_max_right _ _)
  have hpos : 0 < N := lt_of_lt_of_le (Nat.succ_pos _) (le_max_right _ _)
  have h1 := adicEval_sub_mem_pow I w hw N (p : MvPowerSeries σ R)
  have h2 : truncTotal N (p : MvPowerSeries σ R) = p :=
    (truncTotal_coe_eq_self_iff (n := N) p hpos.ne').mpr hlt
  rw [h2] at h1
  exact Ideal.pow_le_pow_right (le_max_left _ _) h1

@[simp]
theorem adicEval_X (i : σ) : adicEval I w hw (X i : MvPowerSeries σ R) = w i := by
  have hX : ((MvPolynomial.X i : MvPolynomial σ R) : MvPowerSeries σ R) = X i := by simp
  rw [← hX, adicEval_coe]
  simp

/-- The estimate that makes `adicEval` useful: a power series all of whose
coefficients below total degree `k` vanish evaluates into `I ^ k`. -/
theorem adicEval_mem_pow (k : ℕ) (p : MvPowerSeries σ R)
    (hp : ∀ d : σ →₀ ℕ, d.degree < k → coeff d p = 0) :
    adicEval I w hw p ∈ I ^ k := by
  have htr : truncTotal k p = 0 := by
    ext d
    rw [MvPolynomial.coeff_zero, coeff_truncTotal_eq_ite]
    split
    · rename_i hd
      exact hp d hd
    · rfl
  have h1 := adicEval_sub_mem_pow I w hw k p
  rwa [htr, map_zero, sub_zero] at h1

end AdicEval

section AdicEvalOfMem

variable {σ : Type*} [Finite σ] {R : Type*} [CommRing R]
  {O : Type*} [CommRing O] [Algebra R O] (I : Ideal O) [IsAdicComplete I O]

open Classical in
/-- The **total** form of `adicEval`: evaluation at an arbitrary tuple `w`, which
falls back to evaluation at `0` when some `w i` fails to lie in `I`.

`adicEval` takes the membership hypothesis `hw : ∀ i, w i ∈ I` as an argument, so
it cannot be used to build a function of `w` alone.  Consumers that need such a
function — Fontaine's "equation function" `F` and "normalised Jacobian" `p`, whose
statements quantify over all `w` — use this instead, together with
`adicEvalOfMem_eq` to recover `adicEval` wherever the hypothesis is available. -/
noncomputable def adicEvalOfMem (w : σ → O) : MvPowerSeries σ R →ₐ[R] O :=
  if hw : ∀ i, w i ∈ I then adicEval I w hw else adicEval I 0 (fun _ => I.zero_mem)

theorem adicEvalOfMem_eq {w : σ → O} (hw : ∀ i, w i ∈ I) :
    (adicEvalOfMem I w : MvPowerSeries σ R →ₐ[R] O) = adicEval I w hw := by
  rw [adicEvalOfMem, dif_pos hw]

@[simp]
theorem adicEvalOfMem_X {w : σ → O} (hw : ∀ i, w i ∈ I) (i : σ) :
    adicEvalOfMem I w (X i : MvPowerSeries σ R) = w i := by
  rw [adicEvalOfMem_eq I hw, adicEval_X]

theorem adicEvalOfMem_mem_pow {w : σ → O} (hw : ∀ i, w i ∈ I) (k : ℕ)
    (p : MvPowerSeries σ R) (hp : ∀ d : σ →₀ ℕ, d.degree < k → coeff d p = 0) :
    adicEvalOfMem I w p ∈ I ^ k := by
  rw [adicEvalOfMem_eq I hw]
  exact adicEval_mem_pow I w hw k p hp

end AdicEvalOfMem

section ConstantCoeff

/-! ### The constant term is what survives modulo `I`

Added 2026-07-28 for Fontaine's step 3.  Fontaine's presentation `α` is an
*arbitrary* `𝒪`-algebra map out of the power series ring, subject only to
`α (X i) = x i` with `x i` in the maximal ideal.  Modulo the maximal ideal such a
map is therefore forced: it is the constant term.  That forcing is what identifies
the residue of the normalised Jacobian `Q(w)` — evaluated by `adicEvalOfMem` — with
the residue of `α (Q i j)`, and it is what makes the invertibility of the Jacobian
transportable between the two sides.

The one nontrivial ingredient is `mem_span_range_X_of_constantCoeff_eq_zero`, which
needs FINITELY many variables and is FALSE without that: for `σ` infinite,
`X₀ + X₁ + ⋯` has zero constant term and is not a finite combination of the `X i`. -/

variable {σ : Type*} {R : Type*} [CommRing R]

/-- **For FINITELY many variables, a power series with zero constant term lies in the
ideal generated by the variables.**

The decomposition is by the LEAST variable occurring: `f = ∑ i, f i` where `f i`
collects the monomials whose least-index positive exponent is at `i`, and `X i ∣ f i`
by `X_dvd_iff` because every monomial of `f i` has a positive exponent at `i`.

FINITENESS IS LOAD-BEARING: for infinite `σ` the series `∑ i, X i` has zero constant
term and lies in no finitely generated subideal of `span (range X)`. -/
theorem mem_span_range_X_of_constantCoeff_eq_zero [Fintype σ] [LinearOrder σ]
    {f : MvPowerSeries σ R} (hf : constantCoeff f = 0) :
    f ∈ Ideal.span (Set.range (X : σ → MvPowerSeries σ R)) := by
  classical
  set g : σ → MvPowerSeries σ R := fun i =>
    (fun d => if d i ≠ 0 ∧ ∀ j, j < i → d j = 0 then coeff d f else 0) with hg
  have hcoeff : ∀ i d, coeff d (g i) =
      if d i ≠ 0 ∧ ∀ j, j < i → d j = 0 then coeff d f else 0 := by
    intro i d; rw [coeff_apply]
  have hdvd : ∀ i, (X i : MvPowerSeries σ R) ∣ g i := by
    intro i
    rw [X_dvd_iff]
    intro m hm
    rw [hcoeff, if_neg]
    rintro ⟨h, -⟩
    exact h hm
  have hsum : f = ∑ i : σ, g i := by
    ext d
    rw [map_sum]
    by_cases hd : d = 0
    · subst hd
      have h0 : ∀ i : σ, coeff (0 : σ →₀ ℕ) (g i) = 0 := by
        intro i
        rw [hcoeff, if_neg]
        rintro ⟨h, -⟩
        exact h rfl
      rw [Finset.sum_congr rfl (fun i _ => h0 i), Finset.sum_const_zero,
        coeff_zero_eq_constantCoeff_apply, hf]
    · have hne : d.support.Nonempty := Finsupp.support_nonempty_iff.mpr hd
      set i₀ := d.support.min' hne with hi₀
      have hi₀mem : i₀ ∈ d.support := d.support.min'_mem hne
      have hi₀ne : d i₀ ≠ 0 := Finsupp.mem_support_iff.mp hi₀mem
      have hlt : ∀ j, j < i₀ → d j = 0 := by
        intro j hj
        by_contra hjne
        exact absurd (d.support.min'_le j (Finsupp.mem_support_iff.mpr hjne)) (not_le.mpr hj)
      rw [Finset.sum_eq_single i₀ ?_ ?_]
      · rw [hcoeff, if_pos ⟨hi₀ne, hlt⟩]
      · intro i _ hine
        rw [hcoeff, if_neg]
        rintro ⟨hdi, hall⟩
        have hle : i₀ ≤ i := d.support.min'_le i (Finsupp.mem_support_iff.mpr hdi)
        exact hi₀ne (hall i₀ (lt_of_le_of_ne hle (Ne.symm hine)))
      · intro hcon
        exact absurd (Finset.mem_univ i₀) hcon
  rw [hsum]
  refine Submodule.sum_mem _ fun i _ => ?_
  obtain ⟨c, hc⟩ := hdvd i
  rw [hc]
  exact Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨i, rfl⟩)

/-- **An `R`-algebra map out of a power series ring in FINITELY many variables that
kills every variable IS the constant term.**  No continuity hypothesis is needed or
available: finiteness of `σ` does the whole job through
`mem_span_range_X_of_constantCoeff_eq_zero`. -/
theorem algHom_apply_eq_constantCoeff [Fintype σ] [LinearOrder σ]
    {T : Type*} [CommRing T] [Algebra R T]
    (φ : MvPowerSeries σ R →ₐ[R] T) (hφ : ∀ i, φ (X i) = 0) (f : MvPowerSeries σ R) :
    φ f = algebraMap R T (constantCoeff f) := by
  have h0 : constantCoeff (f - C (constantCoeff f)) = 0 := by simp
  have hmem := mem_span_range_X_of_constantCoeff_eq_zero h0
  have hle : Ideal.span (Set.range (X : σ → MvPowerSeries σ R)) ≤
      RingHom.ker (φ : MvPowerSeries σ R →+* T) := by
    rw [Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    simp only [SetLike.mem_coe, RingHom.mem_ker, RingHom.coe_coe]
    exact hφ i
  have hker := hle hmem
  rw [RingHom.mem_ker] at hker
  have hC : φ (C (constantCoeff f)) = algebraMap R T (constantCoeff f) := by
    rw [show (C (constantCoeff f) : MvPowerSeries σ R) =
      algebraMap R (MvPowerSeries σ R) (constantCoeff f) from rfl]
    exact φ.commutes _
  simp only [RingHom.coe_coe, map_sub, hC] at hker
  exact sub_eq_zero.mp hker

/-- The degree-`< 1` truncation is the constant term.  (Mathlib's `truncTotal_one` is a
different statement — the truncation of the series `1` — hence the longer name.) -/
theorem truncTotal_one_eq_C_constantCoeff [Finite σ] (f : MvPowerSeries σ R) :
    truncTotal 1 f = MvPolynomial.C (constantCoeff f) := by
  classical
  ext d
  rw [coeff_truncTotal_eq_ite, MvPolynomial.coeff_C]
  by_cases hd : d = 0
  · subst hd
    simp [coeff_zero_eq_constantCoeff_apply]
  · rw [if_neg, if_neg (Ne.symm hd)]
    simpa [Finsupp.degree_eq_zero_iff] using hd

/-- **The residue of an adic evaluation is the constant term**, for any tuple `w` drawn
from `I`.  This is the `adicEvalOfMem` half of the identification described at the head
of this section. -/
theorem mk_pow_one_adicEvalOfMem [Finite σ] {O : Type*} [CommRing O] [Algebra R O]
    (I : Ideal O) [IsAdicComplete I O] {w : σ → O} (hw : ∀ i, w i ∈ I)
    (f : MvPowerSeries σ R) :
    Ideal.Quotient.mk (I ^ 1) (adicEvalOfMem I w f) =
      algebraMap R (O ⧸ I ^ 1) (constantCoeff f) := by
  rw [adicEvalOfMem_eq I hw, mk_adicEval I w hw 1 f, truncTotal_one_eq_C_constantCoeff,
    MvPolynomial.aeval_C]
  exact (IsScalarTower.algebraMap_apply R O (O ⧸ I ^ 1) (constantCoeff f)).symm

end ConstantCoeff

end MvPowerSeries

namespace MvPolynomial

/-! ### First- and second-order Taylor expansion of a multivariate polynomial

Added 2026-07-31 for Fontaine's step 4 (`taylor_of_isFontainePresentation` in
`ModThree.lean`), which needs

> `P(w + μ) ≡ P(w) + Σⱼ (∂P/∂Xⱼ)(w)·μⱼ  (mod 3·(μ)² + (μ)³)`

for a power series `P` all of whose partial derivatives are divisible by `3`.

**THIS NEEDS NO HASSE DERIVATIVES AND NO DIVIDED POWERS**, which is what the older
route in that leaf's docstring prescribed and what made it look expensive (the pin has
a Hasse-derivative API only for univariate `Polynomial`).  The observation that removes
them: the crude first-order estimate `taylor_sub_mem_sq` below — error in `(μ)²`, proved
by a three-case induction over `MvPolynomial.induction_on` and nothing else — is already
enough for every monomial `c·Xᵐ` whose COEFFICIENT is divisible by `3`; and a monomial
whose coefficient is NOT is, under the hypothesis in force, one all of whose EXPONENTS
are divisible by `3`, i.e. one in the image of the cube substitution `Xⱼ ↦ Xⱼ³`.  For
those the same crude estimate applied at the CUBED coordinates does the job, because

    (w + μ)³ = w³ + (3w²·μ + 3w·μ² + μ³),

whose linear-in-`μ` part `3w²μ` is exactly what the chain rule
`pderiv_cubeSub` produces, and whose remaining terms are visibly in `3·(μ)² + (μ)³`.

So the whole second-order phenomenon is carried by ONE substitution and the crude
first-order lemma, applied twice.  The error ideal is written `(μ)² * ((3) + (μ))`,
a single product rather than a sum, which makes the ideal bookkeeping at the call
site one `Ideal.mul_le` instead of a distributivity argument. -/

section Taylor

variable {σ : Type*} [Fintype σ] {R : Type*} [CommRing R]
  {O : Type*} [CommRing O] [Algebra R O]

/-- The linear term of a Taylor expansion lies in the ideal generated by the
perturbation. -/
theorem sum_pderiv_mul_mem_span (a b : σ → O) (p : MvPolynomial σ R) :
    ∑ j, aeval a (pderiv j p) * b j ∈ Ideal.span (Set.range b) :=
  Ideal.sum_mem _ fun j _ => Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨j, rfl⟩)

/-- **CRUDE FIRST-ORDER TAYLOR EXPANSION**: for any polynomial and any two tuples in a
commutative algebra, the first-order remainder lies in the SQUARE of the ideal generated
by the perturbation.  No hypothesis whatsoever on `a`, `b` or `p`.

The proof is `MvPolynomial.induction_on`.  Writing `A p = aeval (a+b) p`, `B p = aeval a
p`, `L p = Σⱼ B(∂ⱼp)·bⱼ` and `D = A - B - L`, the only case with content is `p·Xₙ`, where

    D(p·Xₙ) = aₙ·D(p) + D(p)·bₙ + L(p)·bₙ,

and the last term is the one that needs `L p ∈ (b)`: that is
`sum_pderiv_mul_mem_span`. -/
theorem taylor_sub_mem_sq (a b : σ → O) (p : MvPolynomial σ R) :
    aeval (a + b) p - aeval a p - ∑ j, aeval a (pderiv j p) * b j
      ∈ (Ideal.span (Set.range b)) ^ 2 := by
  classical
  induction p using MvPolynomial.induction_on with
  | C r => simp
  | add p q hp hq =>
      have hrw : aeval (a + b) (p + q) - aeval a (p + q)
            - ∑ j, aeval a (pderiv j (p + q)) * b j
          = (aeval (a + b) p - aeval a p - ∑ j, aeval a (pderiv j p) * b j)
            + (aeval (a + b) q - aeval a q - ∑ j, aeval a (pderiv j q) * b j) := by
        simp only [map_add, add_mul, Finset.sum_add_distrib]
        ring
      rw [hrw]
      exact Ideal.add_mem _ hp hq
  | mul_X p n hp =>
      set L := ∑ j, aeval a (pderiv j p) * b j with hL
      set D := aeval (a + b) p - aeval a p - L with hD
      have hpd : ∀ j, aeval a (pderiv j (p * X n))
          = (if n = j then aeval a p else 0) + a n * aeval a (pderiv j p) := by
        intro j
        rw [pderiv_mul]
        by_cases hnj : n = j
        · subst hnj; simp; ring
        · simp [pderiv_X_of_ne hnj, hnj]; ring
      have hsum : ∑ j, aeval a (pderiv j (p * X n)) * b j
          = aeval a p * b n + a n * L := by
        simp only [hpd, add_mul, Finset.sum_add_distrib, hL, Finset.mul_sum, mul_assoc,
          ite_mul, zero_mul]
        rw [Finset.sum_ite_eq Finset.univ n (fun j => aeval a p * b j),
          if_pos (Finset.mem_univ n)]
      have hrw : aeval (a + b) (p * X n) - aeval a (p * X n)
            - ∑ j, aeval a (pderiv j (p * X n)) * b j
          = a n * D + (D * b n + L * b n) := by
        rw [hsum, hD]
        simp only [map_mul, aeval_X, Pi.add_apply]
        ring
      rw [hrw]
      refine Ideal.add_mem _ (Ideal.mul_mem_left _ _ hp) (Ideal.add_mem _ ?_ ?_)
      · exact Ideal.mul_mem_right _ _ hp
      · rw [pow_two]
        exact Ideal.mul_mem_mul (sum_pderiv_mul_mem_span a b p) (Ideal.subset_span ⟨n, rfl⟩)

end Taylor

section Cube

variable {σ : Type*} {R : Type*} [CommRing R]

/-- The substitution `Xⱼ ↦ Xⱼ³`.  Its image is exactly the span of the monomials all of
whose exponents are divisible by `3`, which is the half of a Fontaine relation whose
coefficients need not be divisible by `3`. -/
noncomputable def cubeSub : MvPolynomial σ R →ₐ[R] MvPolynomial σ R :=
  aeval fun k => (X k) ^ 3

@[simp]
theorem cubeSub_X (k : σ) : (cubeSub (X k) : MvPolynomial σ R) = (X k) ^ 3 := by
  simp [cubeSub]

theorem aeval_cubeSub {O : Type*} [CommRing O] [Algebra R O] (w : σ → O)
    (g : MvPolynomial σ R) :
    aeval w (cubeSub g) = aeval (fun k => (w k) ^ 3) g := by
  have hc : (aeval w : MvPolynomial σ R →ₐ[R] O).comp cubeSub
      = aeval (fun k => (w k) ^ 3) := by
    refine MvPolynomial.algHom_ext fun k => ?_
    simp
  exact congrArg (fun f => f g) hc

/-- **Chain rule for the cube substitution**: `∂ⱼ(g(X³)) = 3·Xⱼ²·(∂ⱼg)(X³)`.  This is the
identity that turns the `3` in Fontaine's `∂P/∂Xⱼ = 3·Q` into the `3` sitting in front of
the linear term of a cubed coordinate. -/
theorem pderiv_cubeSub (j : σ) (g : MvPolynomial σ R) :
    pderiv j (cubeSub g) = (3 : MvPolynomial σ R) * (X j) ^ 2 * cubeSub (pderiv j g) := by
  classical
  induction g using MvPolynomial.induction_on with
  | C r => simp [cubeSub]
  | add p q hp hq => simp only [map_add, hp, hq]; ring
  | mul_X p n hp =>
      have h1 : (cubeSub (p * X n) : MvPolynomial σ R) = cubeSub p * (X n) ^ 3 := by
        simp [map_mul]
      by_cases hnj : n = j
      · subst hnj
        rw [h1, pderiv_mul, hp, pderiv_pow, pderiv_X_self, pderiv_mul, pderiv_X_self,
          map_add, map_mul, cubeSub_X]
        push_cast
        ring_nf
      · rw [h1, pderiv_mul, hp, pderiv_pow, pderiv_X_of_ne hnj, pderiv_mul,
          pderiv_X_of_ne hnj, map_add, map_mul, cubeSub_X]
        simp only [map_zero, mul_zero, add_zero]
        ring

end Cube

section TaylorRefined

variable {σ : Type*} [Fintype σ] {R : Type*} [CommRing R]
  {O : Type*} [CommRing O] [Algebra R O]

/-- **THE TAYLOR ESTIMATE FOR A CUBE SUBSTITUTION**, with NO hypothesis on the
coefficients: for `g(X³)` the first-order remainder already lies in `(μ)²·((3) + (μ))`.

This is where the extra factor of `3` on the quadratic term comes from, and it comes
from the SUBSTITUTION rather than from the coefficients: writing `W = w³` and
`V = (w+μ)³ − w³`, one has `V ∈ (μ)·((3) + (μ))` because
`V = μ·(3w²) + μ·(3wμ) + μ·μ²`, so the crude quadratic remainder at `(W, V)` is in
`(μ)²·((3)+(μ))²`; and the linear term at `(W, V)` differs from the linear term at
`(w, μ)` by `Σⱼ (∂ⱼg)(W)·(3wⱼμⱼ² + μⱼ³)`, again in `(μ)²·((3)+(μ))`. -/
theorem taylor_cubeSub_mem (w μ : σ → O) (g : MvPolynomial σ R) :
    aeval (w + μ) (cubeSub g) - aeval w (cubeSub g)
        - ∑ j, aeval w (pderiv j (cubeSub g)) * μ j
      ∈ (Ideal.span (Set.range μ)) ^ 2 *
        (Ideal.span {(3 : O)} + Ideal.span (Set.range μ)) := by
  classical
  set Nμ := Ideal.span (Set.range μ) with hNμ
  set J := Ideal.span {(3 : O)} + Nμ with hJ
  have hμmem : ∀ k, μ k ∈ Nμ := fun k => Ideal.subset_span ⟨k, rfl⟩
  have h3J : ∀ x : O, 3 * x ∈ J := fun x =>
    Submodule.mem_sup_left (Ideal.mul_mem_right _ _ (Ideal.subset_span rfl))
  set W : σ → O := fun k => (w k) ^ 3 with hW
  set V : σ → O := fun k => (w k + μ k) ^ 3 - (w k) ^ 3 with hV
  have hWV : W + V = fun k => ((w + μ) k) ^ 3 := by
    funext k; simp [hW, hV, Pi.add_apply]
  have h1 : aeval (w + μ) (cubeSub g) = aeval (W + V) g := by
    rw [aeval_cubeSub, hWV]
  have h2 : aeval w (cubeSub g) = aeval W g := aeval_cubeSub w g
  have h3 : ∀ j, aeval w (pderiv j (cubeSub g))
      = 3 * (w j) ^ 2 * aeval W (pderiv j g) := by
    intro j
    rw [pderiv_cubeSub, map_mul, map_mul, map_pow, aeval_X, aeval_cubeSub, map_ofNat]
  have hkey : aeval (w + μ) (cubeSub g) - aeval w (cubeSub g)
        - ∑ j, aeval w (pderiv j (cubeSub g)) * μ j
      = (aeval (W + V) g - aeval W g - ∑ j, aeval W (pderiv j g) * V j)
        + ∑ j, aeval W (pderiv j g) * (V j - 3 * (w j) ^ 2 * μ j) := by
    have hs : ∑ j, aeval W (pderiv j g) * (V j - 3 * (w j) ^ 2 * μ j)
        = ∑ j, aeval W (pderiv j g) * V j
          - ∑ j, 3 * (w j) ^ 2 * aeval W (pderiv j g) * μ j := by
      rw [← Finset.sum_sub_distrib]
      exact Finset.sum_congr rfl fun j _ => by ring
    rw [h1, h2, hs]
    simp only [h3]
    ring
  rw [hkey]
  refine Ideal.add_mem _ ?_ ?_
  · -- the crude quadratic remainder, at the cubed coordinates
    have hVeq : ∀ k, V k
        = μ k * (3 * (w k) ^ 2) + μ k * (3 * ((w k) * μ k)) + μ k * ((μ k) ^ 2) := by
      intro k; simp only [hV]; ring
    have hVmem : ∀ k, V k ∈ Nμ * J := by
      intro k
      rw [hVeq k]
      refine Ideal.add_mem _ (Ideal.add_mem _ ?_ ?_) ?_
      · exact Ideal.mul_mem_mul (hμmem k) (h3J _)
      · exact Ideal.mul_mem_mul (hμmem k) (h3J _)
      · exact Ideal.mul_mem_mul (hμmem k)
          (Submodule.mem_sup_right (Ideal.pow_mem_of_mem _ (hμmem k) 2 (by norm_num)))
    have hle : Ideal.span (Set.range V) ≤ Nμ * J :=
      Ideal.span_le.mpr (by rintro _ ⟨k, rfl⟩; exact hVmem k)
    refine (?_ : (Ideal.span (Set.range V)) ^ 2 ≤ Nμ ^ 2 * J) (taylor_sub_mem_sq W V g)
    calc (Ideal.span (Set.range V)) ^ 2 ≤ (Nμ * J) ^ 2 := Ideal.pow_le_pow_left' hle 2
      _ = Nμ ^ 2 * J ^ 2 := by rw [mul_pow]
      _ ≤ Nμ ^ 2 * J := Ideal.mul_mono le_rfl (by rw [pow_two]; exact Ideal.mul_le_left)
  · refine Ideal.sum_mem _ fun j _ => Ideal.mul_mem_left _ _ ?_
    have hd : V j - 3 * (w j) ^ 2 * μ j
        = (μ j * μ j) * (3 * (w j)) + (μ j * μ j) * (μ j) := by
      simp only [hV]; ring
    rw [hd]
    refine Ideal.add_mem _ ?_ ?_
    · exact Ideal.mul_mem_mul (by rw [pow_two]; exact Ideal.mul_mem_mul (hμmem j) (hμmem j))
        (h3J _)
    · exact Ideal.mul_mem_mul (by rw [pow_two]; exact Ideal.mul_mem_mul (hμmem j) (hμmem j))
        (Submodule.mem_sup_right (hμmem j))

/-- One monomial of the refined estimate.  The dichotomy `hc` is the whole point: a
monomial is handled either because its COEFFICIENT carries the `3` (crude estimate,
scaled) or because all its EXPONENTS do (cube substitution). -/
theorem taylor_monomial_mem (w μ : σ → O) (m : σ →₀ ℕ) (c : R)
    (hc : (∃ j, ¬ (3 ∣ m j)) → c ∈ Ideal.span {(3 : R)}) :
    aeval (w + μ) (monomial m c) - aeval w (monomial m c)
        - ∑ j, aeval w (pderiv j (monomial m c)) * μ j
      ∈ (Ideal.span (Set.range μ)) ^ 2 *
        (Ideal.span {(3 : O)} + Ideal.span (Set.range μ)) := by
  classical
  by_cases hdvd : ∀ j, 3 ∣ m j
  · -- every exponent is divisible by `3`: the monomial is a cube substitution
    set m' : σ →₀ ℕ := Finsupp.mapRange (· / 3) (by norm_num) m with hm'
    have hcube : (monomial m c : MvPolynomial σ R) = cubeSub (monomial m' c) := by
      rw [cubeSub, aeval_monomial, monomial_eq, algebraMap_eq]
      congr 1
      rw [hm', Finsupp.prod_mapRange_index (by intro a; simp)]
      refine Finsupp.prod_congr fun i _ => ?_
      rw [← pow_mul, Nat.mul_div_cancel' (hdvd i)]
    rw [hcube]
    exact taylor_cubeSub_mem w μ (monomial m' c)
  · -- some exponent is prime to `3`: the coefficient carries the factor
    push Not at hdvd
    obtain ⟨c', hc'⟩ := Ideal.mem_span_singleton'.mp (hc (by
      obtain ⟨j, hj⟩ := hdvd; exact ⟨j, hj⟩))
    have hCm : (monomial m c : MvPolynomial σ R) = C 3 * monomial m c' := by
      rw [C_mul_monomial, ← hc', mul_comm]
    have ha1 : ∀ v : σ → O, aeval v (monomial m c) = 3 * aeval v (monomial m c') := by
      intro v; rw [hCm, map_mul, aeval_C, map_ofNat]
    have hpd : ∀ j, aeval w (pderiv j (monomial m c))
        = 3 * aeval w (pderiv j (monomial m c')) := by
      intro j; rw [hCm, pderiv_C_mul, map_mul, aeval_C, map_ofNat]
    have hsplit : aeval (w + μ) (monomial m c) - aeval w (monomial m c)
          - ∑ j, aeval w (pderiv j (monomial m c)) * μ j
        = (aeval (w + μ) (monomial m c') - aeval w (monomial m c')
          - ∑ j, aeval w (pderiv j (monomial m c')) * μ j) * 3 := by
      rw [ha1 (w + μ), ha1 w]
      simp only [hpd]
      rw [show ∑ j, (3 * aeval w (pderiv j (monomial m c'))) * μ j
            = (∑ j, aeval w (pderiv j (monomial m c')) * μ j) * 3 from by
        rw [Finset.sum_mul]; exact Finset.sum_congr rfl fun j _ => by ring]
      ring
    rw [hsplit]
    exact Ideal.mul_mem_mul (taylor_sub_mem_sq w μ (monomial m c'))
      (Submodule.mem_sup_left (Ideal.subset_span rfl))

/-- **THE REFINED TAYLOR ESTIMATE.**  If every coefficient of `p` sitting at a multi-index
with SOME exponent prime to `3` is itself divisible by `3`, then the first-order remainder
lies in `(μ)²·((3) + (μ))` — one factor of `3` better, on the quadratic part, than the
crude `taylor_sub_mem_sq`.

The hypothesis is exactly what `∂P/∂Xⱼ ∈ 3·R[[X]]` for every `j` gives, through
`MvPowerSeries.coeff_pderiv`; see `ModThree.lean`'s `coeff_mem_span_of_pderiv_eq`. -/
theorem taylor_mem_of_coeff (w μ : σ → O) (p : MvPolynomial σ R)
    (hp : ∀ m : σ →₀ ℕ, (∃ j, ¬ (3 ∣ m j)) → coeff m p ∈ Ideal.span {(3 : R)}) :
    aeval (w + μ) p - aeval w p - ∑ j, aeval w (pderiv j p) * μ j
      ∈ (Ideal.span (Set.range μ)) ^ 2 *
        (Ideal.span {(3 : O)} + Ideal.span (Set.range μ)) := by
  classical
  have hEsum : ∀ (s : Finset (σ →₀ ℕ)) (f : (σ →₀ ℕ) → MvPolynomial σ R),
      aeval (w + μ) (∑ i ∈ s, f i) - aeval w (∑ i ∈ s, f i)
          - ∑ j, aeval w (pderiv j (∑ i ∈ s, f i)) * μ j
        = ∑ i ∈ s, (aeval (w + μ) (f i) - aeval w (f i)
          - ∑ j, aeval w (pderiv j (f i)) * μ j) := by
    intro s f
    induction s using Finset.induction with
    | empty => simp
    | insert a s ha ih =>
        rw [Finset.sum_insert ha, Finset.sum_insert ha]
        simp only [map_add, add_mul, Finset.sum_add_distrib]
        rw [← ih]
        ring
  have key := hEsum p.support (fun m => monomial m (coeff m p))
  rw [← p.as_sum] at key
  rw [key]
  exact Ideal.sum_mem _ fun m _ => taylor_monomial_mem w μ m (coeff m p) (hp m)

end TaylorRefined

/-- Truncation and partial differentiation commute, with a degree shift of one.  This is
what lets the Taylor estimate above, which is about honest polynomials, be applied to the
degree-`< n+1` truncation of a power series while its linear term is still read off the
truncation of the power-series derivative. -/
theorem pderiv_truncTotal {σ : Type*} [Finite σ] {R : Type*} [CommRing R]
    (N : ℕ) (j : σ) (f : MvPowerSeries σ R) :
    MvPolynomial.pderiv j (MvPowerSeries.truncTotal (N + 1) f)
      = MvPowerSeries.truncTotal N (MvPowerSeries.pderiv j f) := by
  classical
  ext d
  rw [MvPolynomial.coeff_pderiv, MvPowerSeries.coeff_truncTotal_eq_ite,
    MvPowerSeries.coeff_truncTotal_eq_ite, MvPowerSeries.coeff_pderiv]
  have hdeg : (d + Finsupp.single j 1).degree = d.degree + 1 := by
    rw [map_add, Finsupp.degree_single]
  rw [hdeg]
  by_cases hd : d.degree < N
  · rw [if_pos (by omega), if_pos hd, nsmul_eq_mul, Nat.cast_add, Nat.cast_one]
    ring
  · rw [if_neg (by omega), if_neg hd, zero_mul]

end MvPolynomial
