/-
Copyright (c) 2025 Kevin Buzzard. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kevin Buzzard
-/
module

public import Mathlib.RingTheory.MvPowerSeries.Equiv
public import Mathlib.RingTheory.AdicCompletion.RingHom
public import Mathlib.RingTheory.AdicCompletion.Algebra
public import Mathlib.RingTheory.MvPolynomial.Ideal
public import Mathlib.Algebra.MvPolynomial.PDeriv

/-!
# Evaluating a multivariate power series in an adically complete ring

Fontaine's proof that a finite flat group scheme over `𝒪_K` is rigid along the
`𝔪`-adic filtration (*Il n'y a pas de variété abélienne sur ℤ*, Invent. Math. 81
(1985), Prop. 1.7) presents the affine algebra as `𝒪_K[[X₁,…,X_h]]/(P₁,…,P_h)` and
then substitutes tuples from the maximal ideal of a complete discrete valuation
ring into the `P_i`.  This file supplies exactly that substitution, and it does so
**without any topology**: `MvPowerSeries σ R` maps to `MvPolynomial σ R ⧸ (X)^n`
by total truncation (`MvPowerSeries.truncTotalAlgHom`), `MvPolynomial.aeval w`
carries `(X)^n` into `I^n` as soon as every `w i` lies in `I`, and a compatible
family of maps into the `O ⧸ I^n` assembles into a map into `O` itself by
`IsAdicComplete.liftAlgHom`.  So the construction is a composite of three pieces
of mathlib and needs neither `MvPowerSeries.HasEval` nor a uniform structure on
`O` — which matters here, because the ring being substituted into is
`IntegralClosure 𝒪₃ᵥ E`, on which the development carries `IsAdicComplete` but no
topology.

## Main definitions

* `MvPowerSeries.pderiv` — the formal partial derivative of a multivariate power
  series, defined coefficientwise.  (The pin has derivatives for `Polynomial`,
  `MvPolynomial` and `PowerSeries`, but nothing for `MvPowerSeries`.)
* `MvPowerSeries.adicEval` — evaluation `MvPowerSeries σ R →ₐ[R] O` at a tuple
  `w : σ → O` all of whose entries lie in an ideal `I` for which `O` is
  `I`-adically complete.

## Main results

* `MvPowerSeries.mk_adicEval` — the defining property: modulo `I ^ n` the value of
  `adicEval` is the value of the degree-`< n` truncation.
* `MvPowerSeries.adicEval_X`, `MvPowerSeries.adicEval_coe` — the substitution does
  what it should on variables and on polynomials.
* `MvPowerSeries.adicEval_mem_pow` — a power series whose coefficients vanish below
  total degree `k` evaluates into `I ^ k`.  This is the estimate that makes the
  construction useful: it turns "congruent modulo a power of the variable ideal"
  into "congruent modulo a power of `I`".
* `MvPolynomial.taylor_sub_mem_sq` — crude first-order Taylor expansion: the
  remainder lies in the square of the ideal generated by the perturbation.
* `MvPolynomial.taylor_mem_of_coeff` — the refined version Fontaine's step 4 needs,
  which gains a factor of `3` on the quadratic part from the coefficient hypothesis
  `∂P/∂Xⱼ ∈ 3·R[[X]]`.  See the section header below for why this needs no Hasse
  derivatives.
* `MvPolynomial.pderiv_truncTotal` — truncation and differentiation commute, with a
  degree shift of one.
-/

@[expose] public section

/-- Two elements of an `I`-adically complete ring that agree modulo every power of
`I` are equal. -/
theorem IsAdicComplete.eq_of_sub_mem_pow {O : Type*} [CommRing O] (I : Ideal O)
    [IsAdicComplete I O] {a b : O} (h : ∀ n, a - b ∈ I ^ n) : a = b :=
  sub_eq_zero.mp
    (IsHausdorff.haus (IsAdicComplete.toIsHausdorff : IsHausdorff I O) (a - b)
      fun n => SModEq.sub_mem.mpr (by simpa using h n))

/-- Monotonicity of ideal powers in the ideal. -/
theorem Ideal.pow_le_pow_left' {O : Type*} [CommRing O] {J K : Ideal O} (h : J ≤ K) :
    ∀ n : ℕ, J ^ n ≤ K ^ n
  | 0 => by simp
  | n + 1 => by
    rw [pow_succ, pow_succ]
    exact Ideal.mul_mono (Ideal.pow_le_pow_left' h n) h

namespace MvPowerSeries

section Pderiv

variable {σ : Type*} {R : Type*} [CommRing R]

/-- The formal partial derivative of a multivariate power series with respect to the
variable `j`, defined coefficientwise by `∂(X^n)/∂X_j = n_j · X^(n - e_j)`.

This is a definition only; it is here because Fontaine's argument needs to *state*
that the Jacobian matrix of a power-series presentation is `3` times an invertible
matrix, and this mathlib pin has `Polynomial.derivative`, `MvPolynomial.pderiv` and
`PowerSeries.derivative` but nothing for `MvPowerSeries`. -/
noncomputable def pderiv (j : σ) (f : MvPowerSeries σ R) : MvPowerSeries σ R :=
  fun n => (n j + 1) • coeff (n + Finsupp.single j 1) f

@[simp]
theorem coeff_pderiv (j : σ) (f : MvPowerSeries σ R) (n : σ →₀ ℕ) :
    coeff n (pderiv j f) = (n j + 1) • coeff (n + Finsupp.single j 1) f := by
  simp [pderiv, coeff_apply]

end Pderiv

section AdicEval

variable {σ : Type*} [Finite σ] {R : Type*} [CommRing R]
  {O : Type*} [CommRing O] [Algebra R O]

omit [Finite σ] in
/-- `MvPolynomial.aeval w` carries the `k`-th power of the ideal of variables into
`I ^ k`, as soon as every `w i` lies in `I`. -/
theorem aeval_mem_pow_of_mem_pow_idealOfVars {I : Ideal O} {w : σ → O}
    (hw : ∀ i, w i ∈ I) (k : ℕ) {a : MvPolynomial σ R}
    (ha : a ∈ (MvPolynomial.idealOfVars σ R) ^ k) :
    MvPolynomial.aeval w a ∈ I ^ k := by
  have h0 : Ideal.map ((MvPolynomial.aeval w : MvPolynomial σ R →ₐ[R] O) :
      MvPolynomial σ R →+* O) (MvPolynomial.idealOfVars σ R) ≤ I := by
    rw [MvPolynomial.idealOfVars, Ideal.map_span, Ideal.span_le]
    rintro y ⟨z, hz, rfl⟩
    obtain ⟨i, rfl⟩ := hz
    simpa using hw i
  have h1 : Ideal.map ((MvPolynomial.aeval w : MvPolynomial σ R →ₐ[R] O) :
      MvPolynomial σ R →+* O) ((MvPolynomial.idealOfVars σ R) ^ k) ≤ I ^ k := by
    rw [Ideal.map_pow]
    exact Ideal.pow_le_pow_left' h0 k
  exact h1 (Ideal.mem_map_of_mem _ ha)

variable (I : Ideal O) (w : σ → O) (hw : ∀ i, w i ∈ I)

/-- Evaluation of a multivariate power series at `w` modulo `I ^ n`: only the
degree-`< n` part of the series contributes, so this is an honest finite sum. -/
noncomputable def adicEvalAux (n : ℕ) : MvPowerSeries σ R →ₐ[R] O ⧸ I ^ n :=
  (Ideal.Quotient.liftₐ ((MvPolynomial.idealOfVars σ R) ^ n)
      ((Ideal.Quotient.mkₐ R (I ^ n)).comp (MvPolynomial.aeval w))
      (fun a ha => by
        have h := aeval_mem_pow_of_mem_pow_idealOfVars (R := R) hw n ha
        show Ideal.Quotient.mk (I ^ n) (MvPolynomial.aeval w a) = 0
        rwa [Ideal.Quotient.eq_zero_iff_mem])).comp
    ((truncTotalAlgHom σ R n).restrictScalars R)

theorem adicEvalAux_apply (n : ℕ) (p : MvPowerSeries σ R) :
    adicEvalAux I w hw n p =
      Ideal.Quotient.mk (I ^ n) (MvPolynomial.aeval w (truncTotal n p)) := rfl

theorem adicEvalAux_compat {m n : ℕ} (hle : m ≤ n) :
    (Ideal.Quotient.factorₐ R (Ideal.pow_le_pow_right (I := I) hle)).comp
        (adicEvalAux I w hw n) = adicEvalAux I w hw m := by
  refine AlgHom.ext fun p => ?_
  have hsub : truncTotal n p - truncTotal m p ∈ (MvPolynomial.idealOfVars σ R) ^ m :=
    truncTotal_sub_truncTotal_mem_pow_idealOfVars hle (le_refl m) p
  have hmem : MvPolynomial.aeval w (truncTotal n p) -
      MvPolynomial.aeval w (truncTotal m p) ∈ I ^ m := by
    have := aeval_mem_pow_of_mem_pow_idealOfVars (R := R) hw m hsub
    simpa using this
  simp only [AlgHom.comp_apply, adicEvalAux_apply]
  rw [show (Ideal.Quotient.factorₐ R (Ideal.pow_le_pow_right (I := I) hle))
      (Ideal.Quotient.mk (I ^ n) (MvPolynomial.aeval w (truncTotal n p))) =
      Ideal.Quotient.mk (I ^ m) (MvPolynomial.aeval w (truncTotal n p)) from rfl,
    Ideal.Quotient.mk_eq_mk_iff_sub_mem]
  exact hmem

variable [IsAdicComplete I O]

/-- **Evaluation of a multivariate power series at a tuple drawn from an ideal of an
adically complete ring.**  If `O` is `I`-adically complete and every `w i` lies in
`I`, then `f ↦ f(w)` is a well-defined `R`-algebra map `MvPowerSeries σ R →ₐ[R] O`.

No topology on `O` is used: the map is assembled by `IsAdicComplete.liftAlgHom`
from the truncated evaluations `adicEvalAux`. -/
noncomputable def adicEval : MvPowerSeries σ R →ₐ[R] O :=
  IsAdicComplete.liftAlgHom I (adicEvalAux I w hw) (adicEvalAux_compat I w hw)

@[simp]
theorem mk_adicEval (n : ℕ) (p : MvPowerSeries σ R) :
    Ideal.Quotient.mk (I ^ n) (adicEval I w hw p) =
      Ideal.Quotient.mk (I ^ n) (MvPolynomial.aeval w (truncTotal n p)) := by
  rw [adicEval, IsAdicComplete.mk_liftAlgHom I (adicEvalAux I w hw)
    (adicEvalAux_compat I w hw) n p, adicEvalAux_apply]

theorem adicEval_sub_mem_pow (n : ℕ) (p : MvPowerSeries σ R) :
    adicEval I w hw p - MvPolynomial.aeval w (truncTotal n p) ∈ I ^ n := by
  rw [← Ideal.Quotient.mk_eq_mk_iff_sub_mem]
  exact mk_adicEval I w hw n p

@[simp]
theorem adicEval_coe (p : MvPolynomial σ R) :
    adicEval I w hw (p : MvPowerSeries σ R) = MvPolynomial.aeval w p := by
  refine IsAdicComplete.eq_of_sub_mem_pow I fun n => ?_
  set N := max n (p.totalDegree + 1) with hN
  have hlt : p.totalDegree < N := lt_of_lt_of_le (Nat.lt_succ_self _) (le_max_right _ _)
  have hpos : 0 < N := lt_of_lt_of_le (Nat.succ_pos _) (le_max_right _ _)
  have h1 := adicEval_sub_mem_pow I w hw N (p : MvPowerSeries σ R)
  have h2 : truncTotal N (p : MvPowerSeries σ R) = p :=
    (truncTotal_coe_eq_self_iff (n := N) p hpos.ne').mpr hlt
  rw [h2] at h1
  exact Ideal.pow_le_pow_right (le_max_left _ _) h1

@[simp]
theorem adicEval_X (i : σ) : adicEval I w hw (X i : MvPowerSeries σ R) = w i := by
  have hX : ((MvPolynomial.X i : MvPolynomial σ R) : MvPowerSeries σ R) = X i := by simp
  rw [← hX, adicEval_coe]
  simp

/-- The estimate that makes `adicEval` useful: a power series all of whose
coefficients below total degree `k` vanish evaluates into `I ^ k`. -/
theorem adicEval_mem_pow (k : ℕ) (p : MvPowerSeries σ R)
    (hp : ∀ d : σ →₀ ℕ, d.degree < k → coeff d p = 0) :
    adicEval I w hw p ∈ I ^ k := by
  have htr : truncTotal k p = 0 := by
    ext d
    rw [MvPolynomial.coeff_zero, coeff_truncTotal_eq_ite]
    split
    · rename_i hd
      exact hp d hd
    · rfl
  have h1 := adicEval_sub_mem_pow I w hw k p
  rwa [htr, map_zero, sub_zero] at h1

end AdicEval

section AdicEvalOfMem

variable {σ : Type*} [Finite σ] {R : Type*} [CommRing R]
  {O : Type*} [CommRing O] [Algebra R O] (I : Ideal O) [IsAdicComplete I O]

open Classical in
/-- The **total** form of `adicEval`: evaluation at an arbitrary tuple `w`, which
falls back to evaluation at `0` when some `w i` fails to lie in `I`.

`adicEval` takes the membership hypothesis `hw : ∀ i, w i ∈ I` as an argument, so
it cannot be used to build a function of `w` alone.  Consumers that need such a
function — Fontaine's "equation function" `F` and "normalised Jacobian" `p`, whose
statements quantify over all `w` — use this instead, together with
`adicEvalOfMem_eq` to recover `adicEval` wherever the hypothesis is available. -/
noncomputable def adicEvalOfMem (w : σ → O) : MvPowerSeries σ R →ₐ[R] O :=
  if hw : ∀ i, w i ∈ I then adicEval I w hw else adicEval I 0 (fun _ => I.zero_mem)

theorem adicEvalOfMem_eq {w : σ → O} (hw : ∀ i, w i ∈ I) :
    (adicEvalOfMem I w : MvPowerSeries σ R →ₐ[R] O) = adicEval I w hw := by
  rw [adicEvalOfMem, dif_pos hw]

@[simp]
theorem adicEvalOfMem_X {w : σ → O} (hw : ∀ i, w i ∈ I) (i : σ) :
    adicEvalOfMem I w (X i : MvPowerSeries σ R) = w i := by
  rw [adicEvalOfMem_eq I hw, adicEval_X]

theorem adicEvalOfMem_mem_pow {w : σ → O} (hw : ∀ i, w i ∈ I) (k : ℕ)
    (p : MvPowerSeries σ R) (hp : ∀ d : σ →₀ ℕ, d.degree < k → coeff d p = 0) :
    adicEvalOfMem I w p ∈ I ^ k := by
  rw [adicEvalOfMem_eq I hw]
  exact adicEval_mem_pow I w hw k p hp

end AdicEvalOfMem

section ConstantCoeff

/-! ### The constant term is what survives modulo `I`

Added 2026-07-28 for Fontaine's step 3.  Fontaine's presentation `α` is an
*arbitrary* `𝒪`-algebra map out of the power series ring, subject only to
`α (X i) = x i` with `x i` in the maximal ideal.  Modulo the maximal ideal such a
map is therefore forced: it is the constant term.  That forcing is what identifies
the residue of the normalised Jacobian `Q(w)` — evaluated by `adicEvalOfMem` — with
the residue of `α (Q i j)`, and it is what makes the invertibility of the Jacobian
transportable between the two sides.

The one nontrivial ingredient is `mem_span_range_X_of_constantCoeff_eq_zero`, which
needs FINITELY many variables and is FALSE without that: for `σ` infinite,
`X₀ + X₁ + ⋯` has zero constant term and is not a finite combination of the `X i`. -/

variable {σ : Type*} {R : Type*} [CommRing R]

/-- **For FINITELY many variables, a power series with zero constant term lies in the
ideal generated by the variables.**

The decomposition is by the LEAST variable occurring: `f = ∑ i, f i` where `f i`
collects the monomials whose least-index positive exponent is at `i`, and `X i ∣ f i`
by `X_dvd_iff` because every monomial of `f i` has a positive exponent at `i`.

FINITENESS IS LOAD-BEARING: for infinite `σ` the series `∑ i, X i` has zero constant
term and lies in no finitely generated subideal of `span (range X)`. -/
theorem mem_span_range_X_of_constantCoeff_eq_zero [Fintype σ] [LinearOrder σ]
    {f : MvPowerSeries σ R} (hf : constantCoeff f = 0) :
    f ∈ Ideal.span (Set.range (X : σ → MvPowerSeries σ R)) := by
  classical
  set g : σ → MvPowerSeries σ R := fun i =>
    (fun d => if d i ≠ 0 ∧ ∀ j, j < i → d j = 0 then coeff d f else 0) with hg
  have hcoeff : ∀ i d, coeff d (g i) =
      if d i ≠ 0 ∧ ∀ j, j < i → d j = 0 then coeff d f else 0 := by
    intro i d; rw [coeff_apply]
  have hdvd : ∀ i, (X i : MvPowerSeries σ R) ∣ g i := by
    intro i
    rw [X_dvd_iff]
    intro m hm
    rw [hcoeff, if_neg]
    rintro ⟨h, -⟩
    exact h hm
  have hsum : f = ∑ i : σ, g i := by
    ext d
    rw [map_sum]
    by_cases hd : d = 0
    · subst hd
      have h0 : ∀ i : σ, coeff (0 : σ →₀ ℕ) (g i) = 0 := by
        intro i
        rw [hcoeff, if_neg]
        rintro ⟨h, -⟩
        exact h rfl
      rw [Finset.sum_congr rfl (fun i _ => h0 i), Finset.sum_const_zero,
        coeff_zero_eq_constantCoeff_apply, hf]
    · have hne : d.support.Nonempty := Finsupp.support_nonempty_iff.mpr hd
      set i₀ := d.support.min' hne with hi₀
      have hi₀mem : i₀ ∈ d.support := d.support.min'_mem hne
      have hi₀ne : d i₀ ≠ 0 := Finsupp.mem_support_iff.mp hi₀mem
      have hlt : ∀ j, j < i₀ → d j = 0 := by
        intro j hj
        by_contra hjne
        exact absurd (d.support.min'_le j (Finsupp.mem_support_iff.mpr hjne)) (not_le.mpr hj)
      rw [Finset.sum_eq_single i₀ ?_ ?_]
      · rw [hcoeff, if_pos ⟨hi₀ne, hlt⟩]
      · intro i _ hine
        rw [hcoeff, if_neg]
        rintro ⟨hdi, hall⟩
        have hle : i₀ ≤ i := d.support.min'_le i (Finsupp.mem_support_iff.mpr hdi)
        exact hi₀ne (hall i₀ (lt_of_le_of_ne hle (Ne.symm hine)))
      · intro hcon
        exact absurd (Finset.mem_univ i₀) hcon
  rw [hsum]
  refine Submodule.sum_mem _ fun i _ => ?_
  obtain ⟨c, hc⟩ := hdvd i
  rw [hc]
  exact Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨i, rfl⟩)

/-- **An `R`-algebra map out of a power series ring in FINITELY many variables that
kills every variable IS the constant term.**  No continuity hypothesis is needed or
available: finiteness of `σ` does the whole job through
`mem_span_range_X_of_constantCoeff_eq_zero`. -/
theorem algHom_apply_eq_constantCoeff [Fintype σ] [LinearOrder σ]
    {T : Type*} [CommRing T] [Algebra R T]
    (φ : MvPowerSeries σ R →ₐ[R] T) (hφ : ∀ i, φ (X i) = 0) (f : MvPowerSeries σ R) :
    φ f = algebraMap R T (constantCoeff f) := by
  have h0 : constantCoeff (f - C (constantCoeff f)) = 0 := by simp
  have hmem := mem_span_range_X_of_constantCoeff_eq_zero h0
  have hle : Ideal.span (Set.range (X : σ → MvPowerSeries σ R)) ≤
      RingHom.ker (φ : MvPowerSeries σ R →+* T) := by
    rw [Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    simp only [SetLike.mem_coe, RingHom.mem_ker, RingHom.coe_coe]
    exact hφ i
  have hker := hle hmem
  rw [RingHom.mem_ker] at hker
  have hC : φ (C (constantCoeff f)) = algebraMap R T (constantCoeff f) := by
    rw [show (C (constantCoeff f) : MvPowerSeries σ R) =
      algebraMap R (MvPowerSeries σ R) (constantCoeff f) from rfl]
    exact φ.commutes _
  simp only [RingHom.coe_coe, map_sub, hC] at hker
  exact sub_eq_zero.mp hker

/-- The degree-`< 1` truncation is the constant term.  (Mathlib's `truncTotal_one` is a
different statement — the truncation of the series `1` — hence the longer name.) -/
theorem truncTotal_one_eq_C_constantCoeff [Finite σ] (f : MvPowerSeries σ R) :
    truncTotal 1 f = MvPolynomial.C (constantCoeff f) := by
  classical
  ext d
  rw [coeff_truncTotal_eq_ite, MvPolynomial.coeff_C]
  by_cases hd : d = 0
  · subst hd
    simp [coeff_zero_eq_constantCoeff_apply]
  · rw [if_neg, if_neg (Ne.symm hd)]
    simpa [Finsupp.degree_eq_zero_iff] using hd

/-- **The residue of an adic evaluation is the constant term**, for any tuple `w` drawn
from `I`.  This is the `adicEvalOfMem` half of the identification described at the head
of this section. -/
theorem mk_pow_one_adicEvalOfMem [Finite σ] {O : Type*} [CommRing O] [Algebra R O]
    (I : Ideal O) [IsAdicComplete I O] {w : σ → O} (hw : ∀ i, w i ∈ I)
    (f : MvPowerSeries σ R) :
    Ideal.Quotient.mk (I ^ 1) (adicEvalOfMem I w f) =
      algebraMap R (O ⧸ I ^ 1) (constantCoeff f) := by
  rw [adicEvalOfMem_eq I hw, mk_adicEval I w hw 1 f, truncTotal_one_eq_C_constantCoeff,
    MvPolynomial.aeval_C]
  exact (IsScalarTower.algebraMap_apply R O (O ⧸ I ^ 1) (constantCoeff f)).symm

end ConstantCoeff

end MvPowerSeries

namespace MvPolynomial

/-! ### First- and second-order Taylor expansion of a multivariate polynomial

Added 2026-07-31 for Fontaine's step 4 (`taylor_of_isFontainePresentation` in
`ModThree.lean`), which needs

> `P(w + μ) ≡ P(w) + Σⱼ (∂P/∂Xⱼ)(w)·μⱼ  (mod 3·(μ)² + (μ)³)`

for a power series `P` all of whose partial derivatives are divisible by `3`.

**THIS NEEDS NO HASSE DERIVATIVES AND NO DIVIDED POWERS**, which is what the older
route in that leaf's docstring prescribed and what made it look expensive (the pin has
a Hasse-derivative API only for univariate `Polynomial`).  The observation that removes
them: the crude first-order estimate `taylor_sub_mem_sq` below — error in `(μ)²`, proved
by a three-case induction over `MvPolynomial.induction_on` and nothing else — is already
enough for every monomial `c·Xᵐ` whose COEFFICIENT is divisible by `3`; and a monomial
whose coefficient is NOT is, under the hypothesis in force, one all of whose EXPONENTS
are divisible by `3`, i.e. one in the image of the cube substitution `Xⱼ ↦ Xⱼ³`.  For
those the same crude estimate applied at the CUBED coordinates does the job, because

    (w + μ)³ = w³ + (3w²·μ + 3w·μ² + μ³),

whose linear-in-`μ` part `3w²μ` is exactly what the chain rule
`pderiv_cubeSub` produces, and whose remaining terms are visibly in `3·(μ)² + (μ)³`.

So the whole second-order phenomenon is carried by ONE substitution and the crude
first-order lemma, applied twice.  The error ideal is written `(μ)² * ((3) + (μ))`,
a single product rather than a sum, which makes the ideal bookkeeping at the call
site one `Ideal.mul_le` instead of a distributivity argument. -/

section Taylor

variable {σ : Type*} [Fintype σ] {R : Type*} [CommRing R]
  {O : Type*} [CommRing O] [Algebra R O]

/-- The linear term of a Taylor expansion lies in the ideal generated by the
perturbation. -/
theorem sum_pderiv_mul_mem_span (a b : σ → O) (p : MvPolynomial σ R) :
    ∑ j, aeval a (pderiv j p) * b j ∈ Ideal.span (Set.range b) :=
  Ideal.sum_mem _ fun j _ => Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨j, rfl⟩)

/-- **CRUDE FIRST-ORDER TAYLOR EXPANSION**: for any polynomial and any two tuples in a
commutative algebra, the first-order remainder lies in the SQUARE of the ideal generated
by the perturbation.  No hypothesis whatsoever on `a`, `b` or `p`.

The proof is `MvPolynomial.induction_on`.  Writing `A p = aeval (a+b) p`, `B p = aeval a
p`, `L p = Σⱼ B(∂ⱼp)·bⱼ` and `D = A - B - L`, the only case with content is `p·Xₙ`, where

    D(p·Xₙ) = aₙ·D(p) + D(p)·bₙ + L(p)·bₙ,

and the last term is the one that needs `L p ∈ (b)`: that is
`sum_pderiv_mul_mem_span`. -/
theorem taylor_sub_mem_sq (a b : σ → O) (p : MvPolynomial σ R) :
    aeval (a + b) p - aeval a p - ∑ j, aeval a (pderiv j p) * b j
      ∈ (Ideal.span (Set.range b)) ^ 2 := by
  classical
  induction p using MvPolynomial.induction_on with
  | C r => simp
  | add p q hp hq =>
      have hrw : aeval (a + b) (p + q) - aeval a (p + q)
            - ∑ j, aeval a (pderiv j (p + q)) * b j
          = (aeval (a + b) p - aeval a p - ∑ j, aeval a (pderiv j p) * b j)
            + (aeval (a + b) q - aeval a q - ∑ j, aeval a (pderiv j q) * b j) := by
        simp only [map_add, add_mul, Finset.sum_add_distrib]
        ring
      rw [hrw]
      exact Ideal.add_mem _ hp hq
  | mul_X p n hp =>
      set L := ∑ j, aeval a (pderiv j p) * b j with hL
      set D := aeval (a + b) p - aeval a p - L with hD
      have hpd : ∀ j, aeval a (pderiv j (p * X n))
          = (if n = j then aeval a p else 0) + a n * aeval a (pderiv j p) := by
        intro j
        rw [pderiv_mul]
        by_cases hnj : n = j
        · subst hnj; simp; ring
        · simp [pderiv_X_of_ne hnj, hnj]; ring
      have hsum : ∑ j, aeval a (pderiv j (p * X n)) * b j
          = aeval a p * b n + a n * L := by
        simp only [hpd, add_mul, Finset.sum_add_distrib, hL, Finset.mul_sum, mul_assoc,
          ite_mul, zero_mul]
        rw [Finset.sum_ite_eq Finset.univ n (fun j => aeval a p * b j),
          if_pos (Finset.mem_univ n)]
      have hrw : aeval (a + b) (p * X n) - aeval a (p * X n)
            - ∑ j, aeval a (pderiv j (p * X n)) * b j
          = a n * D + (D * b n + L * b n) := by
        rw [hsum, hD]
        simp only [map_mul, aeval_X, Pi.add_apply]
        ring
      rw [hrw]
      refine Ideal.add_mem _ (Ideal.mul_mem_left _ _ hp) (Ideal.add_mem _ ?_ ?_)
      · exact Ideal.mul_mem_right _ _ hp
      · rw [pow_two]
        exact Ideal.mul_mem_mul (sum_pderiv_mul_mem_span a b p) (Ideal.subset_span ⟨n, rfl⟩)

end Taylor

section Cube

variable {σ : Type*} {R : Type*} [CommRing R]

/-- The substitution `Xⱼ ↦ Xⱼ³`.  Its image is exactly the span of the monomials all of
whose exponents are divisible by `3`, which is the half of a Fontaine relation whose
coefficients need not be divisible by `3`. -/
noncomputable def cubeSub : MvPolynomial σ R →ₐ[R] MvPolynomial σ R :=
  aeval fun k => (X k) ^ 3

@[simp]
theorem cubeSub_X (k : σ) : (cubeSub (X k) : MvPolynomial σ R) = (X k) ^ 3 := by
  simp [cubeSub]

theorem aeval_cubeSub {O : Type*} [CommRing O] [Algebra R O] (w : σ → O)
    (g : MvPolynomial σ R) :
    aeval w (cubeSub g) = aeval (fun k => (w k) ^ 3) g := by
  have hc : (aeval w : MvPolynomial σ R →ₐ[R] O).comp cubeSub
      = aeval (fun k => (w k) ^ 3) := by
    refine MvPolynomial.algHom_ext fun k => ?_
    simp
  exact congrArg (fun f => f g) hc

/-- **Chain rule for the cube substitution**: `∂ⱼ(g(X³)) = 3·Xⱼ²·(∂ⱼg)(X³)`.  This is the
identity that turns the `3` in Fontaine's `∂P/∂Xⱼ = 3·Q` into the `3` sitting in front of
the linear term of a cubed coordinate. -/
theorem pderiv_cubeSub (j : σ) (g : MvPolynomial σ R) :
    pderiv j (cubeSub g) = (3 : MvPolynomial σ R) * (X j) ^ 2 * cubeSub (pderiv j g) := by
  classical
  induction g using MvPolynomial.induction_on with
  | C r => simp [cubeSub]
  | add p q hp hq => simp only [map_add, hp, hq]; ring
  | mul_X p n hp =>
      have h1 : (cubeSub (p * X n) : MvPolynomial σ R) = cubeSub p * (X n) ^ 3 := by
        simp [map_mul]
      by_cases hnj : n = j
      · subst hnj
        rw [h1, pderiv_mul, hp, pderiv_pow, pderiv_X_self, pderiv_mul, pderiv_X_self,
          map_add, map_mul, cubeSub_X]
        push_cast
        ring_nf
      · rw [h1, pderiv_mul, hp, pderiv_pow, pderiv_X_of_ne hnj, pderiv_mul,
          pderiv_X_of_ne hnj, map_add, map_mul, cubeSub_X]
        simp only [map_zero, mul_zero, add_zero]
        ring

end Cube

section TaylorRefined

variable {σ : Type*} [Fintype σ] {R : Type*} [CommRing R]
  {O : Type*} [CommRing O] [Algebra R O]

/-- **THE TAYLOR ESTIMATE FOR A CUBE SUBSTITUTION**, with NO hypothesis on the
coefficients: for `g(X³)` the first-order remainder already lies in `(μ)²·((3) + (μ))`.

This is where the extra factor of `3` on the quadratic term comes from, and it comes
from the SUBSTITUTION rather than from the coefficients: writing `W = w³` and
`V = (w+μ)³ − w³`, one has `V ∈ (μ)·((3) + (μ))` because
`V = μ·(3w²) + μ·(3wμ) + μ·μ²`, so the crude quadratic remainder at `(W, V)` is in
`(μ)²·((3)+(μ))²`; and the linear term at `(W, V)` differs from the linear term at
`(w, μ)` by `Σⱼ (∂ⱼg)(W)·(3wⱼμⱼ² + μⱼ³)`, again in `(μ)²·((3)+(μ))`. -/
theorem taylor_cubeSub_mem (w μ : σ → O) (g : MvPolynomial σ R) :
    aeval (w + μ) (cubeSub g) - aeval w (cubeSub g)
        - ∑ j, aeval w (pderiv j (cubeSub g)) * μ j
      ∈ (Ideal.span (Set.range μ)) ^ 2 *
        (Ideal.span {(3 : O)} + Ideal.span (Set.range μ)) := by
  classical
  set Nμ := Ideal.span (Set.range μ) with hNμ
  set J := Ideal.span {(3 : O)} + Nμ with hJ
  have hμmem : ∀ k, μ k ∈ Nμ := fun k => Ideal.subset_span ⟨k, rfl⟩
  have h3J : ∀ x : O, 3 * x ∈ J := fun x =>
    Submodule.mem_sup_left (Ideal.mul_mem_right _ _ (Ideal.subset_span rfl))
  set W : σ → O := fun k => (w k) ^ 3 with hW
  set V : σ → O := fun k => (w k + μ k) ^ 3 - (w k) ^ 3 with hV
  have hWV : W + V = fun k => ((w + μ) k) ^ 3 := by
    funext k; simp [hW, hV, Pi.add_apply]
  have h1 : aeval (w + μ) (cubeSub g) = aeval (W + V) g := by
    rw [aeval_cubeSub, hWV]
  have h2 : aeval w (cubeSub g) = aeval W g := aeval_cubeSub w g
  have h3 : ∀ j, aeval w (pderiv j (cubeSub g))
      = 3 * (w j) ^ 2 * aeval W (pderiv j g) := by
    intro j
    rw [pderiv_cubeSub, map_mul, map_mul, map_pow, aeval_X, aeval_cubeSub, map_ofNat]
  have hkey : aeval (w + μ) (cubeSub g) - aeval w (cubeSub g)
        - ∑ j, aeval w (pderiv j (cubeSub g)) * μ j
      = (aeval (W + V) g - aeval W g - ∑ j, aeval W (pderiv j g) * V j)
        + ∑ j, aeval W (pderiv j g) * (V j - 3 * (w j) ^ 2 * μ j) := by
    have hs : ∑ j, aeval W (pderiv j g) * (V j - 3 * (w j) ^ 2 * μ j)
        = ∑ j, aeval W (pderiv j g) * V j
          - ∑ j, 3 * (w j) ^ 2 * aeval W (pderiv j g) * μ j := by
      rw [← Finset.sum_sub_distrib]
      exact Finset.sum_congr rfl fun j _ => by ring
    rw [h1, h2, hs]
    simp only [h3]
    ring
  rw [hkey]
  refine Ideal.add_mem _ ?_ ?_
  · -- the crude quadratic remainder, at the cubed coordinates
    have hVeq : ∀ k, V k
        = μ k * (3 * (w k) ^ 2) + μ k * (3 * ((w k) * μ k)) + μ k * ((μ k) ^ 2) := by
      intro k; simp only [hV]; ring
    have hVmem : ∀ k, V k ∈ Nμ * J := by
      intro k
      rw [hVeq k]
      refine Ideal.add_mem _ (Ideal.add_mem _ ?_ ?_) ?_
      · exact Ideal.mul_mem_mul (hμmem k) (h3J _)
      · exact Ideal.mul_mem_mul (hμmem k) (h3J _)
      · exact Ideal.mul_mem_mul (hμmem k)
          (Submodule.mem_sup_right (Ideal.pow_mem_of_mem _ (hμmem k) 2 (by norm_num)))
    have hle : Ideal.span (Set.range V) ≤ Nμ * J :=
      Ideal.span_le.mpr (by rintro _ ⟨k, rfl⟩; exact hVmem k)
    refine (?_ : (Ideal.span (Set.range V)) ^ 2 ≤ Nμ ^ 2 * J) (taylor_sub_mem_sq W V g)
    calc (Ideal.span (Set.range V)) ^ 2 ≤ (Nμ * J) ^ 2 := Ideal.pow_le_pow_left' hle 2
      _ = Nμ ^ 2 * J ^ 2 := by rw [mul_pow]
      _ ≤ Nμ ^ 2 * J := Ideal.mul_mono le_rfl (by rw [pow_two]; exact Ideal.mul_le_left)
  · refine Ideal.sum_mem _ fun j _ => Ideal.mul_mem_left _ _ ?_
    have hd : V j - 3 * (w j) ^ 2 * μ j
        = (μ j * μ j) * (3 * (w j)) + (μ j * μ j) * (μ j) := by
      simp only [hV]; ring
    rw [hd]
    refine Ideal.add_mem _ ?_ ?_
    · exact Ideal.mul_mem_mul (by rw [pow_two]; exact Ideal.mul_mem_mul (hμmem j) (hμmem j))
        (h3J _)
    · exact Ideal.mul_mem_mul (by rw [pow_two]; exact Ideal.mul_mem_mul (hμmem j) (hμmem j))
        (Submodule.mem_sup_right (hμmem j))

/-- One monomial of the refined estimate.  The dichotomy `hc` is the whole point: a
monomial is handled either because its COEFFICIENT carries the `3` (crude estimate,
scaled) or because all its EXPONENTS do (cube substitution). -/
theorem taylor_monomial_mem (w μ : σ → O) (m : σ →₀ ℕ) (c : R)
    (hc : (∃ j, ¬ (3 ∣ m j)) → c ∈ Ideal.span {(3 : R)}) :
    aeval (w + μ) (monomial m c) - aeval w (monomial m c)
        - ∑ j, aeval w (pderiv j (monomial m c)) * μ j
      ∈ (Ideal.span (Set.range μ)) ^ 2 *
        (Ideal.span {(3 : O)} + Ideal.span (Set.range μ)) := by
  classical
  by_cases hdvd : ∀ j, 3 ∣ m j
  · -- every exponent is divisible by `3`: the monomial is a cube substitution
    set m' : σ →₀ ℕ := Finsupp.mapRange (· / 3) (by norm_num) m with hm'
    have hcube : (monomial m c : MvPolynomial σ R) = cubeSub (monomial m' c) := by
      rw [cubeSub, aeval_monomial, monomial_eq, algebraMap_eq]
      congr 1
      rw [hm', Finsupp.prod_mapRange_index (by intro a; simp)]
      refine Finsupp.prod_congr fun i _ => ?_
      rw [← pow_mul, Nat.mul_div_cancel' (hdvd i)]
    rw [hcube]
    exact taylor_cubeSub_mem w μ (monomial m' c)
  · -- some exponent is prime to `3`: the coefficient carries the factor
    push Not at hdvd
    obtain ⟨c', hc'⟩ := Ideal.mem_span_singleton'.mp (hc (by
      obtain ⟨j, hj⟩ := hdvd; exact ⟨j, hj⟩))
    have hCm : (monomial m c : MvPolynomial σ R) = C 3 * monomial m c' := by
      rw [C_mul_monomial, ← hc', mul_comm]
    have ha1 : ∀ v : σ → O, aeval v (monomial m c) = 3 * aeval v (monomial m c') := by
      intro v; rw [hCm, map_mul, aeval_C, map_ofNat]
    have hpd : ∀ j, aeval w (pderiv j (monomial m c))
        = 3 * aeval w (pderiv j (monomial m c')) := by
      intro j; rw [hCm, pderiv_C_mul, map_mul, aeval_C, map_ofNat]
    have hsplit : aeval (w + μ) (monomial m c) - aeval w (monomial m c)
          - ∑ j, aeval w (pderiv j (monomial m c)) * μ j
        = (aeval (w + μ) (monomial m c') - aeval w (monomial m c')
          - ∑ j, aeval w (pderiv j (monomial m c')) * μ j) * 3 := by
      rw [ha1 (w + μ), ha1 w]
      simp only [hpd]
      rw [show ∑ j, (3 * aeval w (pderiv j (monomial m c'))) * μ j
            = (∑ j, aeval w (pderiv j (monomial m c')) * μ j) * 3 from by
        rw [Finset.sum_mul]; exact Finset.sum_congr rfl fun j _ => by ring]
      ring
    rw [hsplit]
    exact Ideal.mul_mem_mul (taylor_sub_mem_sq w μ (monomial m c'))
      (Submodule.mem_sup_left (Ideal.subset_span rfl))

/-- **THE REFINED TAYLOR ESTIMATE.**  If every coefficient of `p` sitting at a multi-index
with SOME exponent prime to `3` is itself divisible by `3`, then the first-order remainder
lies in `(μ)²·((3) + (μ))` — one factor of `3` better, on the quadratic part, than the
crude `taylor_sub_mem_sq`.

The hypothesis is exactly what `∂P/∂Xⱼ ∈ 3·R[[X]]` for every `j` gives, through
`MvPowerSeries.coeff_pderiv`; see `ModThree.lean`'s `coeff_mem_span_of_pderiv_eq`. -/
theorem taylor_mem_of_coeff (w μ : σ → O) (p : MvPolynomial σ R)
    (hp : ∀ m : σ →₀ ℕ, (∃ j, ¬ (3 ∣ m j)) → coeff m p ∈ Ideal.span {(3 : R)}) :
    aeval (w + μ) p - aeval w p - ∑ j, aeval w (pderiv j p) * μ j
      ∈ (Ideal.span (Set.range μ)) ^ 2 *
        (Ideal.span {(3 : O)} + Ideal.span (Set.range μ)) := by
  classical
  have hEsum : ∀ (s : Finset (σ →₀ ℕ)) (f : (σ →₀ ℕ) → MvPolynomial σ R),
      aeval (w + μ) (∑ i ∈ s, f i) - aeval w (∑ i ∈ s, f i)
          - ∑ j, aeval w (pderiv j (∑ i ∈ s, f i)) * μ j
        = ∑ i ∈ s, (aeval (w + μ) (f i) - aeval w (f i)
          - ∑ j, aeval w (pderiv j (f i)) * μ j) := by
    intro s f
    induction s using Finset.induction with
    | empty => simp
    | insert a s ha ih =>
        rw [Finset.sum_insert ha, Finset.sum_insert ha]
        simp only [map_add, add_mul, Finset.sum_add_distrib]
        rw [← ih]
        ring
  have key := hEsum p.support (fun m => monomial m (coeff m p))
  rw [← p.as_sum] at key
  rw [key]
  exact Ideal.sum_mem _ fun m _ => taylor_monomial_mem w μ m (coeff m p) (hp m)

end TaylorRefined

/-- Truncation and partial differentiation commute, with a degree shift of one.  This is
what lets the Taylor estimate above, which is about honest polynomials, be applied to the
degree-`< n+1` truncation of a power series while its linear term is still read off the
truncation of the power-series derivative. -/
theorem pderiv_truncTotal {σ : Type*} [Finite σ] {R : Type*} [CommRing R]
    (N : ℕ) (j : σ) (f : MvPowerSeries σ R) :
    MvPolynomial.pderiv j (MvPowerSeries.truncTotal (N + 1) f)
      = MvPowerSeries.truncTotal N (MvPowerSeries.pderiv j f) := by
  classical
  ext d
  rw [MvPolynomial.coeff_pderiv, MvPowerSeries.coeff_truncTotal_eq_ite,
    MvPowerSeries.coeff_truncTotal_eq_ite, MvPowerSeries.coeff_pderiv]
  have hdeg : (d + Finsupp.single j 1).degree = d.degree + 1 := by
    rw [map_add, Finsupp.degree_single]
  rw [hdeg]
  by_cases hd : d.degree < N
  · rw [if_pos (by omega), if_pos hd, nsmul_eq_mul, Nat.cast_add, Nat.cast_one]
    ring
  · rw [if_neg (by omega), if_neg hd, zero_mul]

end MvPolynomial
