/-
Copyright (c) 2025 Kevin Buzzard. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kevin Buzzard
-/
module

public import Mathlib.RingTheory.MvPowerSeries.Equiv
public import Mathlib.RingTheory.AdicCompletion.RingHom
public import Mathlib.RingTheory.AdicCompletion.Algebra
public import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# Evaluating a multivariate power series in an adically complete ring

Fontaine's proof that a finite flat group scheme over `𝒪_K` is rigid along the
`𝔪`-adic filtration (*Il n'y a pas de variété abélienne sur ℤ*, Invent. Math. 81
(1985), Prop. 1.7) presents the affine algebra as `𝒪_K[[X₁,…,X_h]]/(P₁,…,P_h)` and
then substitutes tuples from the maximal ideal of a complete discrete valuation
ring into the `P_i`.  This file supplies exactly that substitution, and it does so
**without any topology**: `MvPowerSeries σ R` maps to `MvPolynomial σ R ⧸ (X)^n`
by total truncation (`MvPowerSeries.truncTotalAlgHom`), `MvPolynomial.aeval w`
carries `(X)^n` into `I^n` as soon as every `w i` lies in `I`, and a compatible
family of maps into the `O ⧸ I^n` assembles into a map into `O` itself by
`IsAdicComplete.liftAlgHom`.  So the construction is a composite of three pieces
of mathlib and needs neither `MvPowerSeries.HasEval` nor a uniform structure on
`O` — which matters here, because the ring being substituted into is
`IntegralClosure 𝒪₃ᵥ E`, on which the development carries `IsAdicComplete` but no
topology.

## Main definitions

* `MvPowerSeries.pderiv` — the formal partial derivative of a multivariate power
  series, defined coefficientwise.  (The pin has derivatives for `Polynomial`,
  `MvPolynomial` and `PowerSeries`, but nothing for `MvPowerSeries`.)  Its
  algebraic API — additivity, the LEIBNIZ RULE `MvPowerSeries.pderiv_mul`, and
  vanishing on constants — is proved here, since the pin supplies none of it
  either.  (Only what is CONSUMED is kept: `pderiv_smul` was written and then
  deleted unused, per the project's no-free-floating-code rule.  It is four
  lines — `ext`, `simp [coeff_pderiv, coeff_smul, nsmul_eq_mul]`, `ring` — if a
  later proof needs it.)
* `MvPowerSeries.adicEval` — evaluation `MvPowerSeries σ R →ₐ[R] O` at a tuple
  `w : σ → O` all of whose entries lie in an ideal `I` for which `O` is
  `I`-adically complete.

## Main results

* `MvPowerSeries.mk_adicEval` — the defining property: modulo `I ^ n` the value of
  `adicEval` is the value of the degree-`< n` truncation.
* `MvPowerSeries.adicEval_X`, `MvPowerSeries.adicEval_coe` — the substitution does
  what it should on variables and on polynomials.
* `MvPowerSeries.adicEval_mem_pow` — a power series whose coefficients vanish below
  total degree `k` evaluates into `I ^ k`.  This is the estimate that makes the
  construction useful: it turns "congruent modulo a power of the variable ideal"
  into "congruent modulo a power of `I`".
* `MvPowerSeries.pderiv_mem_span_of_mem_span` — a span whose GENERATORS have their
  derivatives inside it is a differential ideal.  Only the generators have to be
  checked; Leibniz propagates the property across the span.
* `MvPowerSeries.span_insert_setOf_forall_pderiv_mem_eq` (sorry leaf) — a
  differential ideal containing a prime `p` is generated by `p` together with the
  elements all of whose derivatives are divisible by `p`.  This is the KEY LEMMA
  of Fontaine's step 3; see its docstring for the proof and for why it is stated
  over an arbitrary base ring rather than over a field of characteristic `p`.
-/

@[expose] public section

/-- Two elements of an `I`-adically complete ring that agree modulo every power of
`I` are equal. -/
theorem IsAdicComplete.eq_of_sub_mem_pow {O : Type*} [CommRing O] (I : Ideal O)
    [IsAdicComplete I O] {a b : O} (h : ∀ n, a - b ∈ I ^ n) : a = b :=
  sub_eq_zero.mp
    (IsHausdorff.haus (IsAdicComplete.toIsHausdorff : IsHausdorff I O) (a - b)
      fun n => SModEq.sub_mem.mpr (by simpa using h n))

/-- Monotonicity of ideal powers in the ideal. -/
theorem Ideal.pow_le_pow_left' {O : Type*} [CommRing O] {J K : Ideal O} (h : J ≤ K) :
    ∀ n : ℕ, J ^ n ≤ K ^ n
  | 0 => by simp
  | n + 1 => by
    rw [pow_succ, pow_succ]
    exact Ideal.mul_mono (Ideal.pow_le_pow_left' h n) h

namespace MvPowerSeries

open Finset (antidiagonal)

section Pderiv

variable {σ : Type*} {R : Type*} [CommRing R]

/-- The formal partial derivative of a multivariate power series with respect to the
variable `j`, defined coefficientwise by `∂(X^n)/∂X_j = n_j · X^(n - e_j)`.

This is a definition only; it is here because Fontaine's argument needs to *state*
that the Jacobian matrix of a power-series presentation is `3` times an invertible
matrix, and this mathlib pin has `Polynomial.derivative`, `MvPolynomial.pderiv` and
`PowerSeries.derivative` but nothing for `MvPowerSeries`. -/
noncomputable def pderiv (j : σ) (f : MvPowerSeries σ R) : MvPowerSeries σ R :=
  fun n => (n j + 1) • coeff (n + Finsupp.single j 1) f

@[simp]
theorem coeff_pderiv (j : σ) (f : MvPowerSeries σ R) (n : σ →₀ ℕ) :
    coeff n (pderiv j f) = (n j + 1) • coeff (n + Finsupp.single j 1) f := by
  simp [pderiv, coeff_apply]

theorem pderiv_add (j : σ) (f g : MvPowerSeries σ R) :
    pderiv j (f + g) = pderiv j f + pderiv j g := by
  ext n
  simp [coeff_pderiv, smul_add]

/-- The reindexing that drives the Leibniz rule: a sum over the antidiagonal of `n`
weighted by `p.1 j + 1` is a sum over the antidiagonal of `n + eⱼ` weighted by
`q.1 j`, the terms with `q.1 j = 0` contributing nothing. -/
theorem coeff_pderiv_mul_left [DecidableEq σ] (j : σ) (f g : MvPowerSeries σ R)
    (n : σ →₀ ℕ) :
    coeff n (pderiv j f * g) =
      ∑ q ∈ (antidiagonal (n + Finsupp.single j 1) : Finset ((σ →₀ ℕ) × (σ →₀ ℕ))),
        (q.1 j) • (coeff q.1 f * coeff q.2 g) := by
  rw [coeff_mul]
  rw [← Finset.sum_filter_add_sum_filter_not
    (antidiagonal (n + Finsupp.single j 1) : Finset ((σ →₀ ℕ) × (σ →₀ ℕ)))
    (fun q => q.1 j ≠ 0)]
  have hzero : ∑ q ∈ (antidiagonal (n + Finsupp.single j 1) :
        Finset ((σ →₀ ℕ) × (σ →₀ ℕ))).filter (fun q => ¬ (q.1 j ≠ 0)),
      (q.1 j) • (coeff q.1 f * coeff q.2 g) = 0 := by
    refine Finset.sum_eq_zero fun q hq => ?_
    simp only [Finset.mem_filter, not_ne_iff] at hq
    rw [hq.2]
    simp
  rw [hzero, add_zero]
  refine Finset.sum_nbij' (fun p => (p.1 + Finsupp.single j 1, p.2))
    (fun q => (q.1 - Finsupp.single j 1, q.2)) ?_ ?_ ?_ ?_ ?_
  · rintro ⟨a, b⟩ hab
    simp only [Finset.mem_antidiagonal] at hab
    simp only [Finset.mem_filter, Finset.mem_antidiagonal]
    refine ⟨by rw [add_right_comm, hab], ?_⟩
    simp
  · rintro ⟨a, b⟩ hab
    simp only [Finset.mem_filter, Finset.mem_antidiagonal, ne_eq] at hab
    simp only [Finset.mem_antidiagonal]
    have h1 : Finsupp.single j 1 ≤ a := by
      rw [Finsupp.single_le_iff]
      omega
    have : a - Finsupp.single j 1 + Finsupp.single j 1 = a := tsub_add_cancel_of_le h1
    have h2 := hab.1
    ext k
    have := congrArg (fun (t : σ →₀ ℕ) => t k) h2
    simp only [Finsupp.add_apply, Finsupp.coe_tsub, Pi.sub_apply] at this ⊢
    have hle : (Finsupp.single j 1 : σ →₀ ℕ) k ≤ a k := h1 k
    omega
  · rintro ⟨a, b⟩ hab
    simp
  · rintro ⟨a, b⟩ hab
    simp only [Finset.mem_filter, Finset.mem_antidiagonal, ne_eq] at hab
    have h1 : Finsupp.single j 1 ≤ a := by
      rw [Finsupp.single_le_iff]
      omega
    simp only [Prod.mk.injEq, and_true]
    exact tsub_add_cancel_of_le h1
  · rintro ⟨a, b⟩ hab
    simp only [coeff_pderiv, Finsupp.add_apply, Finsupp.single_eq_same, smul_mul_assoc]


theorem coeff_pderiv_mul_right [DecidableEq σ] (j : σ) (f g : MvPowerSeries σ R)
    (n : σ →₀ ℕ) :
    coeff n (f * pderiv j g) =
      ∑ q ∈ (antidiagonal (n + Finsupp.single j 1) : Finset ((σ →₀ ℕ) × (σ →₀ ℕ))),
        (q.2 j) • (coeff q.1 f * coeff q.2 g) := by
  rw [mul_comm, coeff_pderiv_mul_left]
  refine Finset.sum_nbij' Prod.swap Prod.swap ?_ ?_ ?_ ?_ ?_
  · rintro ⟨a, b⟩ hab
    simp only [Finset.mem_antidiagonal] at hab ⊢
    rw [add_comm]; exact hab
  · rintro ⟨a, b⟩ hab
    simp only [Finset.mem_antidiagonal] at hab ⊢
    rw [add_comm]; exact hab
  · rintro ⟨a, b⟩ hab; rfl
  · rintro ⟨a, b⟩ hab; rfl
  · rintro ⟨a, b⟩ hab
    simp only [Prod.fst_swap, Prod.snd_swap]
    rw [mul_comm]

/-- **THE LEIBNIZ RULE** for the formal partial derivative of a multivariate power
series. -/
theorem pderiv_mul (j : σ) (f g : MvPowerSeries σ R) :
    pderiv j (f * g) = pderiv j f * g + f * pderiv j g := by
  classical
  ext n
  rw [map_add, coeff_pderiv, coeff_pderiv_mul_left, coeff_pderiv_mul_right, coeff_mul,
    Finset.smul_sum, ← Finset.sum_add_distrib]
  refine Finset.sum_congr rfl fun q hq => ?_
  rw [Finset.mem_antidiagonal] at hq
  rw [← add_smul]
  congr 1
  have h := congrArg (fun t : σ →₀ ℕ => t j) hq
  simpa using h.symm

@[simp]
theorem pderiv_zero (j : σ) : pderiv j (0 : MvPowerSeries σ R) = 0 := by
  ext n; simp [coeff_pderiv]

/-- The derivative of a constant vanishes. -/
@[simp]
theorem pderiv_C (j : σ) (a : R) : pderiv j (C a : MvPowerSeries σ R) = 0 := by
  classical
  ext n
  have h : n + Finsupp.single j 1 ≠ 0 := by
    intro hcon
    have := congrArg (fun t : σ →₀ ℕ => t j) hcon
    simp at this
  simp [coeff_pderiv, coeff_C, h]

theorem pderiv_natCast (j : σ) (m : ℕ) :
    pderiv j (m : MvPowerSeries σ R) = 0 := by
  rw [show ((m : MvPowerSeries σ R)) = C (m : R) by simp, pderiv_C]

/-- **A SPAN WHOSE GENERATORS HAVE THEIR DERIVATIVES INSIDE IT IS A DIFFERENTIAL
IDEAL.**  This is what turns the Jacobian estimate of Fontaine's step 3 into
stability of `ker α + (3)` under every `∂/∂Xⱼ`: only the generators have to be
checked, and the Leibniz rule propagates the property across the span. -/
theorem pderiv_mem_span_of_mem_span (s : Set (MvPowerSeries σ R))
    (hs : ∀ g ∈ s, ∀ j, pderiv j g ∈ Ideal.span s)
    (j : σ) {f : MvPowerSeries σ R} (hf : f ∈ Ideal.span s) :
    pderiv j f ∈ Ideal.span s := by
  induction hf using Submodule.span_induction with
  | mem x hx => exact hs x hx j
  | zero => simp
  | add x y hx hy ihx ihy => rw [pderiv_add]; exact Ideal.add_mem _ ihx ihy
  | smul a x hx ih =>
      rw [smul_eq_mul, pderiv_mul]
      exact Ideal.add_mem _ (Ideal.mul_mem_left _ _ hx) (Ideal.mul_mem_left _ _ ih)


end Pderiv

section KeyLemma

variable {p : ℕ}

/-- **THE KEY LEMMA OF FONTAINE'S STEP 3** (sorry leaf, cut 2026-07-31 out of
`GaloisRepresentation.IsHardlyRamified.exists_pderiv_eq_of_minimalPresentation`):
*a differential ideal containing `p` is generated by `p` together with the
elements whose derivatives are all divisible by `p`.*

In the classical formulation — `k` a field of characteristic `p`,
`R̄ = k[[X₁,…,X_h]]`, `S = k[[X₁^p,…,X_h^p]]` — this says that an ideal of `R̄`
stable under every `∂/∂Xⱼ` is generated by `𝔞 ∩ S`.  The form below is that
statement transported back across `R ↠ R/pR`, which is why it needs no field and
no quotient: `{f | ∀ j, ∂f/∂Xⱼ ∈ (p)}` is the preimage of `S`, and the classical
`𝔞 = (𝔞 ∩ S)·R̄` becomes `𝔞 = ({p} ∪ (𝔞 ∩ preimage of S))·R`.

PROOF (three steps, no differential equation — an earlier reading of the parent
leaf guessed that one had to solve `∂u/∂Xⱼ = −u·Cⱼ` over `𝔽₃[[X]]`, and that
guess is wrong; see the SECOND FALSITY AUDIT on `exists_fontainePresentation`).

1. *Box decomposition.*  Every `f : MvPowerSeries σ 𝒪` is uniquely
   `f = ∑_{a ∈ box} s_a · X^a`, the sum over the finite `box = {a | ∀ j, a j < p}`
   and each `s_a` supported on exponents divisible by `p` (group the monomials of
   `f` by the residue of their exponent mod `p`).  This is an identity over ANY
   commutative ring; no perfectness and no `p`-th roots are involved.
2. *Maximal-term extraction.*  Write `T^{(b)} := ∏_j (∂/∂Xⱼ)^{b_j}`.  Since each
   `s_a` has all exponents divisible by `p`, `∂ⱼ s_a ∈ (p)`, so by Leibniz
   `T^{(b)}(s_a X^a) ≡ s_a · T^{(b)}(X^a) (mod p)`, and `T^{(b)} X^a = 0` unless
   `a ≥ b` componentwise.  Take `a₀` MAXIMAL for the componentwise order in the
   (finite) set of `a ∈ box` with `s_a ≠ 0`; then every other surviving `a` fails
   `a ≥ a₀`, so `T^{(a₀)} f ≡ (∏_j a₀_j !) · s_{a₀} (mod p)`.  The ideal is
   `∂`-stable, so the left side lies in `𝔞`; `p ∈ 𝔞`; and `∏_j a₀_j !` is a
   product of factorials of naturals `< p`, hence an integer PRIME TO `p`, hence
   invertible mod `p`.  Multiplying by an inverse and correcting by a multiple of
   `p` gives `s_{a₀} ∈ 𝔞`.  This is the only place primality of `p` is used.
3. *Induction.*  `s_{a₀}` has all its exponents divisible by `p`, so all its
   derivatives lie in `(p)`: it belongs to the generating set.  Replace `f` by
   `f − s_{a₀} X^{a₀} ∈ 𝔞`, whose box support is strictly smaller, and induct on
   the cardinality of that support.

The reverse inclusion is immediate: `p ∈ 𝔞` by hypothesis and the second half of
the generating set is contained in `𝔞` by construction. -/
theorem span_insert_setOf_forall_pderiv_mem_eq
    {σ : Type*} [Finite σ] [DecidableEq σ] {𝒪 : Type*} [CommRing 𝒪]
    [hp : Fact p.Prime] (𝔞 : Ideal (MvPowerSeries σ 𝒪))
    (hpmem : (p : MvPowerSeries σ 𝒪) ∈ 𝔞)
    (hstab : ∀ (j : σ) (f : MvPowerSeries σ 𝒪), f ∈ 𝔞 → pderiv j f ∈ 𝔞) :
    𝔞 = Ideal.span ({(p : MvPowerSeries σ 𝒪)} ∪
      {f | f ∈ 𝔞 ∧ ∀ j, pderiv j f ∈ Ideal.span {(p : MvPowerSeries σ 𝒪)}}) := by
  sorry

end KeyLemma

section AdicEval

variable {σ : Type*} [Finite σ] {R : Type*} [CommRing R]
  {O : Type*} [CommRing O] [Algebra R O]

omit [Finite σ] in
/-- `MvPolynomial.aeval w` carries the `k`-th power of the ideal of variables into
`I ^ k`, as soon as every `w i` lies in `I`. -/
theorem aeval_mem_pow_of_mem_pow_idealOfVars {I : Ideal O} {w : σ → O}
    (hw : ∀ i, w i ∈ I) (k : ℕ) {a : MvPolynomial σ R}
    (ha : a ∈ (MvPolynomial.idealOfVars σ R) ^ k) :
    MvPolynomial.aeval w a ∈ I ^ k := by
  have h0 : Ideal.map ((MvPolynomial.aeval w : MvPolynomial σ R →ₐ[R] O) :
      MvPolynomial σ R →+* O) (MvPolynomial.idealOfVars σ R) ≤ I := by
    rw [MvPolynomial.idealOfVars, Ideal.map_span, Ideal.span_le]
    rintro y ⟨z, hz, rfl⟩
    obtain ⟨i, rfl⟩ := hz
    simpa using hw i
  have h1 : Ideal.map ((MvPolynomial.aeval w : MvPolynomial σ R →ₐ[R] O) :
      MvPolynomial σ R →+* O) ((MvPolynomial.idealOfVars σ R) ^ k) ≤ I ^ k := by
    rw [Ideal.map_pow]
    exact Ideal.pow_le_pow_left' h0 k
  exact h1 (Ideal.mem_map_of_mem _ ha)

variable (I : Ideal O) (w : σ → O) (hw : ∀ i, w i ∈ I)

/-- Evaluation of a multivariate power series at `w` modulo `I ^ n`: only the
degree-`< n` part of the series contributes, so this is an honest finite sum. -/
noncomputable def adicEvalAux (n : ℕ) : MvPowerSeries σ R →ₐ[R] O ⧸ I ^ n :=
  (Ideal.Quotient.liftₐ ((MvPolynomial.idealOfVars σ R) ^ n)
      ((Ideal.Quotient.mkₐ R (I ^ n)).comp (MvPolynomial.aeval w))
      (fun a ha => by
        have h := aeval_mem_pow_of_mem_pow_idealOfVars (R := R) hw n ha
        show Ideal.Quotient.mk (I ^ n) (MvPolynomial.aeval w a) = 0
        rwa [Ideal.Quotient.eq_zero_iff_mem])).comp
    ((truncTotalAlgHom σ R n).restrictScalars R)

theorem adicEvalAux_apply (n : ℕ) (p : MvPowerSeries σ R) :
    adicEvalAux I w hw n p =
      Ideal.Quotient.mk (I ^ n) (MvPolynomial.aeval w (truncTotal n p)) := rfl

theorem adicEvalAux_compat {m n : ℕ} (hle : m ≤ n) :
    (Ideal.Quotient.factorₐ R (Ideal.pow_le_pow_right (I := I) hle)).comp
        (adicEvalAux I w hw n) = adicEvalAux I w hw m := by
  refine AlgHom.ext fun p => ?_
  have hsub : truncTotal n p - truncTotal m p ∈ (MvPolynomial.idealOfVars σ R) ^ m :=
    truncTotal_sub_truncTotal_mem_pow_idealOfVars hle (le_refl m) p
  have hmem : MvPolynomial.aeval w (truncTotal n p) -
      MvPolynomial.aeval w (truncTotal m p) ∈ I ^ m := by
    have := aeval_mem_pow_of_mem_pow_idealOfVars (R := R) hw m hsub
    simpa using this
  simp only [AlgHom.comp_apply, adicEvalAux_apply]
  rw [show (Ideal.Quotient.factorₐ R (Ideal.pow_le_pow_right (I := I) hle))
      (Ideal.Quotient.mk (I ^ n) (MvPolynomial.aeval w (truncTotal n p))) =
      Ideal.Quotient.mk (I ^ m) (MvPolynomial.aeval w (truncTotal n p)) from rfl,
    Ideal.Quotient.mk_eq_mk_iff_sub_mem]
  exact hmem

variable [IsAdicComplete I O]

/-- **Evaluation of a multivariate power series at a tuple drawn from an ideal of an
adically complete ring.**  If `O` is `I`-adically complete and every `w i` lies in
`I`, then `f ↦ f(w)` is a well-defined `R`-algebra map `MvPowerSeries σ R →ₐ[R] O`.

No topology on `O` is used: the map is assembled by `IsAdicComplete.liftAlgHom`
from the truncated evaluations `adicEvalAux`. -/
noncomputable def adicEval : MvPowerSeries σ R →ₐ[R] O :=
  IsAdicComplete.liftAlgHom I (adicEvalAux I w hw) (adicEvalAux_compat I w hw)

@[simp]
theorem mk_adicEval (n : ℕ) (p : MvPowerSeries σ R) :
    Ideal.Quotient.mk (I ^ n) (adicEval I w hw p) =
      Ideal.Quotient.mk (I ^ n) (MvPolynomial.aeval w (truncTotal n p)) := by
  rw [adicEval, IsAdicComplete.mk_liftAlgHom I (adicEvalAux I w hw)
    (adicEvalAux_compat I w hw) n p, adicEvalAux_apply]

theorem adicEval_sub_mem_pow (n : ℕ) (p : MvPowerSeries σ R) :
    adicEval I w hw p - MvPolynomial.aeval w (truncTotal n p) ∈ I ^ n := by
  rw [← Ideal.Quotient.mk_eq_mk_iff_sub_mem]
  exact mk_adicEval I w hw n p

@[simp]
theorem adicEval_coe (p : MvPolynomial σ R) :
    adicEval I w hw (p : MvPowerSeries σ R) = MvPolynomial.aeval w p := by
  refine IsAdicComplete.eq_of_sub_mem_pow I fun n => ?_
  set N := max n (p.totalDegree + 1) with hN
  have hlt : p.totalDegree < N := lt_of_lt_of_le (Nat.lt_succ_self _) (le_max_right _ _)
  have hpos : 0 < N := lt_of_lt_of_le (Nat.succ_pos _) (le_max_right _ _)
  have h1 := adicEval_sub_mem_pow I w hw N (p : MvPowerSeries σ R)
  have h2 : truncTotal N (p : MvPowerSeries σ R) = p :=
    (truncTotal_coe_eq_self_iff (n := N) p hpos.ne').mpr hlt
  rw [h2] at h1
  exact Ideal.pow_le_pow_right (le_max_left _ _) h1

@[simp]
theorem adicEval_X (i : σ) : adicEval I w hw (X i : MvPowerSeries σ R) = w i := by
  have hX : ((MvPolynomial.X i : MvPolynomial σ R) : MvPowerSeries σ R) = X i := by simp
  rw [← hX, adicEval_coe]
  simp

/-- The estimate that makes `adicEval` useful: a power series all of whose
coefficients below total degree `k` vanish evaluates into `I ^ k`. -/
theorem adicEval_mem_pow (k : ℕ) (p : MvPowerSeries σ R)
    (hp : ∀ d : σ →₀ ℕ, d.degree < k → coeff d p = 0) :
    adicEval I w hw p ∈ I ^ k := by
  have htr : truncTotal k p = 0 := by
    ext d
    rw [MvPolynomial.coeff_zero, coeff_truncTotal_eq_ite]
    split
    · rename_i hd
      exact hp d hd
    · rfl
  have h1 := adicEval_sub_mem_pow I w hw k p
  rwa [htr, map_zero, sub_zero] at h1

end AdicEval

section AdicEvalOfMem

variable {σ : Type*} [Finite σ] {R : Type*} [CommRing R]
  {O : Type*} [CommRing O] [Algebra R O] (I : Ideal O) [IsAdicComplete I O]

open Classical in
/-- The **total** form of `adicEval`: evaluation at an arbitrary tuple `w`, which
falls back to evaluation at `0` when some `w i` fails to lie in `I`.

`adicEval` takes the membership hypothesis `hw : ∀ i, w i ∈ I` as an argument, so
it cannot be used to build a function of `w` alone.  Consumers that need such a
function — Fontaine's "equation function" `F` and "normalised Jacobian" `p`, whose
statements quantify over all `w` — use this instead, together with
`adicEvalOfMem_eq` to recover `adicEval` wherever the hypothesis is available. -/
noncomputable def adicEvalOfMem (w : σ → O) : MvPowerSeries σ R →ₐ[R] O :=
  if hw : ∀ i, w i ∈ I then adicEval I w hw else adicEval I 0 (fun _ => I.zero_mem)

theorem adicEvalOfMem_eq {w : σ → O} (hw : ∀ i, w i ∈ I) :
    (adicEvalOfMem I w : MvPowerSeries σ R →ₐ[R] O) = adicEval I w hw := by
  rw [adicEvalOfMem, dif_pos hw]

@[simp]
theorem adicEvalOfMem_X {w : σ → O} (hw : ∀ i, w i ∈ I) (i : σ) :
    adicEvalOfMem I w (X i : MvPowerSeries σ R) = w i := by
  rw [adicEvalOfMem_eq I hw, adicEval_X]

theorem adicEvalOfMem_mem_pow {w : σ → O} (hw : ∀ i, w i ∈ I) (k : ℕ)
    (p : MvPowerSeries σ R) (hp : ∀ d : σ →₀ ℕ, d.degree < k → coeff d p = 0) :
    adicEvalOfMem I w p ∈ I ^ k := by
  rw [adicEvalOfMem_eq I hw]
  exact adicEval_mem_pow I w hw k p hp

end AdicEvalOfMem

section ConstantCoeff

/-! ### The constant term is what survives modulo `I`

Added 2026-07-28 for Fontaine's step 3.  Fontaine's presentation `α` is an
*arbitrary* `𝒪`-algebra map out of the power series ring, subject only to
`α (X i) = x i` with `x i` in the maximal ideal.  Modulo the maximal ideal such a
map is therefore forced: it is the constant term.  That forcing is what identifies
the residue of the normalised Jacobian `Q(w)` — evaluated by `adicEvalOfMem` — with
the residue of `α (Q i j)`, and it is what makes the invertibility of the Jacobian
transportable between the two sides.

The one nontrivial ingredient is `mem_span_range_X_of_constantCoeff_eq_zero`, which
needs FINITELY many variables and is FALSE without that: for `σ` infinite,
`X₀ + X₁ + ⋯` has zero constant term and is not a finite combination of the `X i`. -/

variable {σ : Type*} {R : Type*} [CommRing R]

/-- **For FINITELY many variables, a power series with zero constant term lies in the
ideal generated by the variables.**

The decomposition is by the LEAST variable occurring: `f = ∑ i, f i` where `f i`
collects the monomials whose least-index positive exponent is at `i`, and `X i ∣ f i`
by `X_dvd_iff` because every monomial of `f i` has a positive exponent at `i`.

FINITENESS IS LOAD-BEARING: for infinite `σ` the series `∑ i, X i` has zero constant
term and lies in no finitely generated subideal of `span (range X)`. -/
theorem mem_span_range_X_of_constantCoeff_eq_zero [Fintype σ] [LinearOrder σ]
    {f : MvPowerSeries σ R} (hf : constantCoeff f = 0) :
    f ∈ Ideal.span (Set.range (X : σ → MvPowerSeries σ R)) := by
  classical
  set g : σ → MvPowerSeries σ R := fun i =>
    (fun d => if d i ≠ 0 ∧ ∀ j, j < i → d j = 0 then coeff d f else 0) with hg
  have hcoeff : ∀ i d, coeff d (g i) =
      if d i ≠ 0 ∧ ∀ j, j < i → d j = 0 then coeff d f else 0 := by
    intro i d; rw [coeff_apply]
  have hdvd : ∀ i, (X i : MvPowerSeries σ R) ∣ g i := by
    intro i
    rw [X_dvd_iff]
    intro m hm
    rw [hcoeff, if_neg]
    rintro ⟨h, -⟩
    exact h hm
  have hsum : f = ∑ i : σ, g i := by
    ext d
    rw [map_sum]
    by_cases hd : d = 0
    · subst hd
      have h0 : ∀ i : σ, coeff (0 : σ →₀ ℕ) (g i) = 0 := by
        intro i
        rw [hcoeff, if_neg]
        rintro ⟨h, -⟩
        exact h rfl
      rw [Finset.sum_congr rfl (fun i _ => h0 i), Finset.sum_const_zero,
        coeff_zero_eq_constantCoeff_apply, hf]
    · have hne : d.support.Nonempty := Finsupp.support_nonempty_iff.mpr hd
      set i₀ := d.support.min' hne with hi₀
      have hi₀mem : i₀ ∈ d.support := d.support.min'_mem hne
      have hi₀ne : d i₀ ≠ 0 := Finsupp.mem_support_iff.mp hi₀mem
      have hlt : ∀ j, j < i₀ → d j = 0 := by
        intro j hj
        by_contra hjne
        exact absurd (d.support.min'_le j (Finsupp.mem_support_iff.mpr hjne)) (not_le.mpr hj)
      rw [Finset.sum_eq_single i₀ ?_ ?_]
      · rw [hcoeff, if_pos ⟨hi₀ne, hlt⟩]
      · intro i _ hine
        rw [hcoeff, if_neg]
        rintro ⟨hdi, hall⟩
        have hle : i₀ ≤ i := d.support.min'_le i (Finsupp.mem_support_iff.mpr hdi)
        exact hi₀ne (hall i₀ (lt_of_le_of_ne hle (Ne.symm hine)))
      · intro hcon
        exact absurd (Finset.mem_univ i₀) hcon
  rw [hsum]
  refine Submodule.sum_mem _ fun i _ => ?_
  obtain ⟨c, hc⟩ := hdvd i
  rw [hc]
  exact Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨i, rfl⟩)

/-- **An `R`-algebra map out of a power series ring in FINITELY many variables that
kills every variable IS the constant term.**  No continuity hypothesis is needed or
available: finiteness of `σ` does the whole job through
`mem_span_range_X_of_constantCoeff_eq_zero`. -/
theorem algHom_apply_eq_constantCoeff [Fintype σ] [LinearOrder σ]
    {T : Type*} [CommRing T] [Algebra R T]
    (φ : MvPowerSeries σ R →ₐ[R] T) (hφ : ∀ i, φ (X i) = 0) (f : MvPowerSeries σ R) :
    φ f = algebraMap R T (constantCoeff f) := by
  have h0 : constantCoeff (f - C (constantCoeff f)) = 0 := by simp
  have hmem := mem_span_range_X_of_constantCoeff_eq_zero h0
  have hle : Ideal.span (Set.range (X : σ → MvPowerSeries σ R)) ≤
      RingHom.ker (φ : MvPowerSeries σ R →+* T) := by
    rw [Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    simp only [SetLike.mem_coe, RingHom.mem_ker, RingHom.coe_coe]
    exact hφ i
  have hker := hle hmem
  rw [RingHom.mem_ker] at hker
  have hC : φ (C (constantCoeff f)) = algebraMap R T (constantCoeff f) := by
    rw [show (C (constantCoeff f) : MvPowerSeries σ R) =
      algebraMap R (MvPowerSeries σ R) (constantCoeff f) from rfl]
    exact φ.commutes _
  simp only [RingHom.coe_coe, map_sub, hC] at hker
  exact sub_eq_zero.mp hker

/-- The degree-`< 1` truncation is the constant term.  (Mathlib's `truncTotal_one` is a
different statement — the truncation of the series `1` — hence the longer name.) -/
theorem truncTotal_one_eq_C_constantCoeff [Finite σ] (f : MvPowerSeries σ R) :
    truncTotal 1 f = MvPolynomial.C (constantCoeff f) := by
  classical
  ext d
  rw [coeff_truncTotal_eq_ite, MvPolynomial.coeff_C]
  by_cases hd : d = 0
  · subst hd
    simp [coeff_zero_eq_constantCoeff_apply]
  · rw [if_neg, if_neg (Ne.symm hd)]
    simpa [Finsupp.degree_eq_zero_iff] using hd

/-- **The residue of an adic evaluation is the constant term**, for any tuple `w` drawn
from `I`.  This is the `adicEvalOfMem` half of the identification described at the head
of this section. -/
theorem mk_pow_one_adicEvalOfMem [Finite σ] {O : Type*} [CommRing O] [Algebra R O]
    (I : Ideal O) [IsAdicComplete I O] {w : σ → O} (hw : ∀ i, w i ∈ I)
    (f : MvPowerSeries σ R) :
    Ideal.Quotient.mk (I ^ 1) (adicEvalOfMem I w f) =
      algebraMap R (O ⧸ I ^ 1) (constantCoeff f) := by
  rw [adicEvalOfMem_eq I hw, mk_adicEval I w hw 1 f, truncTotal_one_eq_C_constantCoeff,
    MvPolynomial.aeval_C]
  exact (IsScalarTower.algebraMap_apply R O (O ⧸ I ^ 1) (constantCoeff f)).symm

end ConstantCoeff

end MvPowerSeries
