/-
Copyright (c) 2026 The Fermat project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Fermat.FLT.Mathlib.RingTheory.MvPowerSeries.AdicEval

/-!
# The ideal of variables of a multivariate power series ring, and rigidity of
algebra maps out of it

Fontaine's Prop. 1.7 (*Il n'y a pas de variété abélienne sur ℤ*, Invent. Math. 81
(1985)) presents a finite flat algebra as `𝒪[[X₁,…,X_h]]/(P₁,…,P_h)` and then has
to know that a map out of that presentation into `𝒪_E/𝔪^k` is DETERMINED by the
images of the `X_i`.  That is false for a general algebra map out of a power
series ring — no continuity is assumed anywhere — and it becomes true exactly
when the images of the variables generate a nilpotent ideal, which is what
`𝒪_E/𝔪^k` supplies.

## Main results

* `MvPowerSeries.mem_varsIdeal_pow` — a power series all of whose coefficients
  below total degree `n` vanish lies in the `n`-th power of the ideal generated
  by the variables.  This is the multivariate power-series analogue of
  `MvPolynomial.mem_pow_idealOfVars_iff'` (which the pin has only for
  polynomials), and it is the one genuinely non-formal step: the proof splits
  `f` as `∑ᵢ Xᵢ · gᵢ`, assigning each monomial to its LEAST variable so that the
  decomposition is well defined and each `gᵢ` again has vanishing coefficients
  below degree `n - 1`.
* `MvPowerSeries.algHom_ext_of_pow_eq_bot` — **the rigidity statement**: two
  `R`-algebra maps `MvPowerSeries σ R →ₐ[R] T` that agree on the variables are
  equal, provided the common images lie in an ideal `I` with `I ^ n = ⊥`.  The
  proof splits `f = truncTotal n f + (f - truncTotal n f)`, notes that the two
  maps agree on the polynomial part because `MvPolynomial` IS generated by its
  variables, and kills the tail with `mem_varsIdeal_pow`.

`σ` is assumed finite and linearly ordered; `Fin h`, the only case Fontaine's
argument uses, supplies both.
-/

@[expose] public section

namespace MvPowerSeries

variable {σ : Type*} [Fintype σ] [LinearOrder σ] {R : Type*} [CommRing R]

/-- The ideal of `MvPowerSeries σ R` generated by the variables. -/
noncomputable def varsIdeal (σ R : Type*) [CommRing R] : Ideal (MvPowerSeries σ R) :=
  Ideal.span (Set.range (X : σ → MvPowerSeries σ R))

/-- The part of `f` whose monomials have `i` as their LEAST variable, divided by
`X i`.  Assigning each monomial to its least variable is what makes
`∑ᵢ Xᵢ · splitAux i f = f` (`sum_X_mul_splitAux`) hold on the nose rather than
up to a multiplicity. -/
noncomputable def splitAux (i : σ) (f : MvPowerSeries σ R) : MvPowerSeries σ R :=
  fun d => if ∀ j, d j ≠ 0 → i ≤ j then coeff (d + Finsupp.single i 1) f else 0

theorem coeff_splitAux (i : σ) (f : MvPowerSeries σ R) (d : σ →₀ ℕ) :
    coeff d (splitAux i f) =
      if ∀ j, d j ≠ 0 → i ≤ j then coeff (d + Finsupp.single i 1) f else 0 := by
  simp [splitAux, coeff_apply]

omit [Fintype σ] [LinearOrder σ] in
theorem coeff_X_mul' (i : σ) (f : MvPowerSeries σ R) (d : σ →₀ ℕ) :
    coeff d (X i * f) =
      if Finsupp.single i 1 ≤ d then coeff (d - Finsupp.single i 1) f else 0 := by
  rw [X, coeff_monomial_mul]
  split_ifs <;> simp

theorem sum_X_mul_splitAux (f : MvPowerSeries σ R) (hf : coeff (0 : σ →₀ ℕ) f = 0) :
    ∑ i : σ, X i * splitAux i f = f := by
  ext d
  rw [map_sum]
  simp only [coeff_X_mul', coeff_splitAux]
  by_cases hd : d = 0
  · subst hd
    rw [hf]
    refine Finset.sum_eq_zero fun i _ => ?_
    rw [if_neg]
    intro hle
    have := (Finsupp.single_le_iff).mp hle
    simp at this
  · have hne : d.support.Nonempty := by
      rwa [Finsupp.support_nonempty_iff]
    set m := d.support.min' hne with hm
    have hmem : m ∈ d.support := d.support.min'_mem hne
    have hdm : d m ≠ 0 := Finsupp.mem_support_iff.mp hmem
    have hmin : ∀ j, d j ≠ 0 → m ≤ j := fun j hj =>
      d.support.min'_le j (Finsupp.mem_support_iff.mpr hj)
    rw [Finset.sum_eq_single_of_mem m (Finset.mem_univ m)]
    · rw [if_pos (Finsupp.single_le_iff.mpr (Nat.one_le_iff_ne_zero.mpr hdm)),
        if_pos, tsub_add_cancel_of_le (Finsupp.single_le_iff.mpr
          (Nat.one_le_iff_ne_zero.mpr hdm))]
      intro j hj
      refine hmin j fun hj0 => hj ?_
      have hle2 : (d - Finsupp.single m 1 : σ →₀ ℕ) j ≤ d j := by
        rw [Finsupp.tsub_apply]
        omega
      omega
    · intro i _ hi
      by_cases hle : Finsupp.single i 1 ≤ d
      · rw [if_pos hle, if_neg]
        intro hcon
        have hmi : (d - Finsupp.single i 1 : σ →₀ ℕ) m = d m := by
          rw [Finsupp.tsub_apply, Finsupp.single_apply, if_neg hi]
          omega
        have := hcon m (by rw [hmi]; exact hdm)
        have hmi2 : m ≤ i := hmin i (by
          have := Finsupp.single_le_iff.mp hle
          omega)
        exact hi (le_antisymm this hmi2)
      · rw [if_neg hle]

theorem coeff_splitAux_eq_zero {n : ℕ} {f : MvPowerSeries σ R}
    (hf : ∀ d : σ →₀ ℕ, Finsupp.degree d < n + 1 → coeff d f = 0) (i : σ) (d : σ →₀ ℕ)
    (hd : Finsupp.degree d < n) : coeff d (splitAux i f) = 0 := by
  rw [coeff_splitAux]
  split_ifs with h
  · refine hf _ ?_
    rw [map_add, Finsupp.degree_single]
    omega
  · rfl

theorem mem_varsIdeal_pow (n : ℕ) (f : MvPowerSeries σ R)
    (hf : ∀ d : σ →₀ ℕ, Finsupp.degree d < n → coeff d f = 0) :
    f ∈ (varsIdeal σ R) ^ n := by
  induction n generalizing f with
  | zero => simp
  | succ n ih =>
    have h0 : coeff (0 : σ →₀ ℕ) f = 0 := hf 0 (by simp)
    have hmem : (∑ i : σ, X i * splitAux i f) ∈ (varsIdeal σ R) ^ (n + 1) := by
      rw [pow_succ']
      refine Ideal.sum_mem _ fun i _ => Ideal.mul_mem_mul (Ideal.subset_span ⟨i, rfl⟩)
        (ih _ fun d hd => coeff_splitAux_eq_zero hf i d hd)
    rwa [sum_X_mul_splitAux f h0] at hmem

omit [Fintype σ] [LinearOrder σ] in
theorem map_mem_pow_of_mem_varsIdeal_pow {T : Type*} [CommRing T] [Algebra R T]
    (φ : MvPowerSeries σ R →ₐ[R] T) (I : Ideal T) (hφ : ∀ i, φ (X i) ∈ I)
    (n : ℕ) {f : MvPowerSeries σ R} (hf : f ∈ (varsIdeal σ R) ^ n) : φ f ∈ I ^ n := by
  have h0 : Ideal.map (φ : MvPowerSeries σ R →+* T) (varsIdeal σ R) ≤ I := by
    rw [varsIdeal, Ideal.map_span, Ideal.span_le]
    rintro y ⟨z, hz, rfl⟩
    obtain ⟨i, rfl⟩ := hz
    exact hφ i
  have h1 : Ideal.map (φ : MvPowerSeries σ R →+* T) ((varsIdeal σ R) ^ n) ≤ I ^ n := by
    rw [Ideal.map_pow]
    exact Ideal.pow_le_pow_left' h0 n
  exact h1 (Ideal.mem_map_of_mem _ hf)

omit [Fintype σ] [LinearOrder σ] in
theorem algHom_apply_coe_eq {T : Type*} [CommRing T] [Algebra R T]
    {φ ψ : MvPowerSeries σ R →ₐ[R] T} (h : ∀ i, φ (X i) = ψ (X i))
    (p : MvPolynomial σ R) :
    φ (p : MvPowerSeries σ R) = ψ (p : MvPowerSeries σ R) := by
  induction p using MvPolynomial.induction_on with
  | C a =>
    rw [MvPolynomial.coe_C]
    rw [show (MvPowerSeries.C a : MvPowerSeries σ R) = algebraMap R (MvPowerSeries σ R) a from rfl]
    rw [AlgHom.commutes, AlgHom.commutes]
  | add p q hp hq => rw [MvPolynomial.coe_add, map_add, map_add, hp, hq]
  | mul_X p i hp =>
    rw [MvPolynomial.coe_mul, MvPolynomial.coe_X, map_mul, map_mul, hp, h i]

/-- **AN ALGEBRA MAP OUT OF A POWER SERIES RING IS DETERMINED BY THE VARIABLES,
ONCE THEIR IMAGES GENERATE A NILPOTENT IDEAL.** -/
theorem algHom_ext_of_pow_eq_bot {T : Type*} [CommRing T] [Algebra R T]
    (I : Ideal T) (n : ℕ) (hI : I ^ n = ⊥)
    {φ ψ : MvPowerSeries σ R →ₐ[R] T}
    (hφ : ∀ i, φ (X i) ∈ I) (h : ∀ i, φ (X i) = ψ (X i)) : φ = ψ := by
  have hψ : ∀ i, ψ (X i) ∈ I := fun i => (h i) ▸ hφ i
  refine AlgHom.ext fun f => ?_
  have hg : f - ((truncTotal n f : MvPolynomial σ R) : MvPowerSeries σ R) ∈
      (varsIdeal σ R) ^ n := by
    refine mem_varsIdeal_pow n _ fun d hd => ?_
    rw [map_sub, MvPolynomial.coeff_coe, coeff_truncTotal _ hd, sub_self]
  have hφg : φ (f - ((truncTotal n f : MvPolynomial σ R) : MvPowerSeries σ R)) = 0 := by
    have := map_mem_pow_of_mem_varsIdeal_pow φ I hφ n hg
    rw [hI] at this
    simpa using this
  have hψg : ψ (f - ((truncTotal n f : MvPolynomial σ R) : MvPowerSeries σ R)) = 0 := by
    have := map_mem_pow_of_mem_varsIdeal_pow ψ I hψ n hg
    rw [hI] at this
    simpa using this
  rw [map_sub, sub_eq_zero] at hφg hψg
  rw [hφg, hψg, algHom_apply_coe_eq h]

end MvPowerSeries
