\\ flt-ramification-break.gp --- upper ramification break of the p^n-torsion
\\ field of a Tate curve, and the Fontaine-bound verdict.
\\
\\     gp -q flt-ramification-break.gp
\\
\\ WHAT IT COMPUTES.  For odd p, n >= 1 and q in Q_p^*, the field
\\
\\     L = Q_p(zeta_{p^n}, q^{1/p^n})
\\
\\ is the field generated by the p^n-torsion of the Tate curve E_q.  Fontaine's
\\ ramification bound (Invent. Math. 81 (1985), Thm. 1 / Prop. 1.7) says that if
\\ E_q[p^n] extends to a finite flat group scheme over Z_p then
\\
\\     G^{(u)}(L/Q_p) = 1   for every  u > (n-1) + 1/(p-1) .
\\
\\ So a break ABOVE that value refutes the existence of a finite flat model, and
\\ a break AT OR BELOW it means the bound is silent.  This script computes the
\\ break and prints the verdict.
\\
\\ WHY IT EXISTS.  It is the check demanded by the SCOPE paragraph on
\\ `pow_dvd_log_valuation_of_exists_fixed_rootOfUnity_of_not_forall_commutator_fixed`
\\ in Fermat/FLT/Modularity/Interface.lean.  Run 2026-08-02, it REFUTES the
\\ field route for n >= 2: the bound is violated in all and only the cases with
\\ p nmid v_p(q), so the route proves p | v_p(q) and never p^n | v_p(q).
\\ The decisive row is p=3, n=2, q=27, degree 18, break 3/2 = the bound exactly,
\\ while 9 nmid v_3(27) = 3 -- see the docstring for the full account.
\\
\\ METHOD.  Build the global Galois model Q(zeta_{p^n}, q^{1/p^n}), take the
\\ LOWER filtration at the prime over p with idealramgroups, and convert to the
\\ upper break with the Herbrand function phi(u) = (1/|G_0|) sum_{i=1}^{u} |G_i|.
\\
\\ TWO TRAPS, both of which cost a round when this was written:
\\   * idealramgroups returns the DECOMPOSITION group G_{-1} first, so one entry
\\     must be dropped before phi is applied;
\\   * a subgroup's order is prod(i=1,#s[2], s[2][i]) -- s[2] is a t_VECSMALL and
\\     vecprod refuses it.
\\
\\ Every row is cross-checked for free against the conductor-discriminant formula
\\   v_p(disc) = sum_i (|G_i| - 1),
\\ which must agree with nfdisc; a disagreement means the filtration was misread.
\\
\\ The first three rows are CONTROLS: they reproduce the numbers already
\\ published in the Interface.lean docstring by an earlier owner (11, 7, 39).
\\ Keep them.  A pipeline that cannot reproduce the figures it is about to
\\ contradict is evidence about the pipeline, not about the mathematics.

default(parisize, 8000000000);

ordsub(s) = prod(i = 1, #s[2], s[2][i]);

\\ upper break = phi(last i with G_i nontrivial), from the LOWER orders
\\ o = [|G_0|, |G_1|, ...]
upperbreak(o) = {
  my(g0 = o[1], s = 0);
  for(i = 2, #o, if(o[i] > 1, s += o[i], break));
  s / g0;
}

run(p, n, q, lab) = {
  my(P, nf, gal, pr, g, o, ub, fb, dsum, dval);
  P = polcompositum(polcyclo(p^n, x), x^(p^n) - q)[1];
  nf = nfinit(P);
  gal = galoisinit(nf);
  pr = idealprimedec(nf, p)[1];
  g = idealramgroups(nf, gal, pr);
  o = vector(#g, i, ordsub(g[i]));
  o = vector(#o - 1, i, o[i+1]);          \\ drop G_{-1}
  ub = upperbreak(o);
  fb = (n-1) + 1/(p-1);
  dsum = sum(i = 1, #o, o[i] - 1);
  dval = valuation(nf.disc, p);
  print(lab);
  print("   p=", p, " n=", n, " q=", q, "  v_p(q)=", valuation(q,p),
        "   p^n | v_p(q)? ", valuation(q,p) % (p^n) == 0);
  print("   deg=", poldegree(P), "  e=", pr.e, "  f=", pr.f);
  print("   lower orders G_0,G_1,... = ", o);
  print("   sum(|G_i|-1) = ", dsum, "   v_p(disc) = ", dval,
        "   AGREE? ", dsum == dval);
  print("   UPPER BREAK = ", ub, " = ", 1.0*ub,
        "      FONTAINE = ", fb, " = ", 1.0*fb);
  print("   VIOLATES FONTAINE? ", ub > fb);
  print("");
}

print("=== CONTROLS: must reproduce the docstring's own published numbers ===");
run(3, 1, 3, "tres ramifiee, n=1   (docstring: v_3(disc)=11, break 3/2)");
run(3, 1, 2, "peu ramifiee,  n=1   (docstring: v_3(disc)=7,  break 1/2)");
run(5, 1, 5, "tres ramifiee, p=5   (docstring: v_5(disc)=39, break 5/4)");

print("=== n = 2, p nmid v_p(q): the bound IS violated ===");
run(3, 2, 3,  "q=3    v=1");
run(3, 2, 9,  "q=9    v=2");
run(3, 2, 81, "q=81   v=4");
run(3, 2, 12, "q=12   v=1, nontrivial unit part");

print("=== n = 2, p | v_p(q) but p^n nmid v_p(q): THE COUNTEREXAMPLES ===");
run(3, 2, 27,  "q=27   v=3   <-- the decisive row");
run(3, 2, 216, "q=216  v=3, nontrivial unit part");
run(3, 2, 3^6, "q=3^6  v=6");
run(3, 2, 54,  "q=54   v=3, mixed radical");

print("=== n = 2, degenerate ends ===");
run(3, 2, 2,   "q=2    v=0, unit: peu ramifiee at level 9");
run(3, 2, 3^9, "q=3^9  v=9, p^n | v: no radical left");

quit
