/-
Modularity/ArtinConductor.lean — own work for the Fermat project (not
vendored from the FLT project).
-/
module

public import Fermat.FLT.Deformations.RepresentationTheory.GaloisRep

/-!
# The Artin conductor exponent of a Galois representation

This module builds the local invariant that the three per-place
"level-lowering" citations of `Fermat/FLT/Modularity/Interface.lean` were
all spelling by hand, each in its own local dialect: the **Artin
conductor exponent** `a_v(V)` of a Galois representation at a finite
place `v`, through the classical dictionary (Serre, *Local Fields*,
VI §2)

  `a_v(V) = (dim V − dim V^{I_v}) + Sw_v(V)`,

the *tame* part read off the inertia invariants and the *wild* part the
Swan conductor.

## What is proven here and what is postponed

The **tame** part is built outright: `GaloisRep.inertiaInvariants` is the
honest `I_v`-fixed submodule (`localInertiaGroup v` acting through
`ρ.toLocal v`), and `GaloisRep.tameExponent` is its codimension, with the
two facts the consumers need proven — it vanishes for an unramified
representation (`GaloisRep.tameExponent_eq_zero_of_isUnramifiedAt`) and
it drops by at least one as soon as inertia fixes a nonzero vector
(`GaloisRep.tameExponent_add_one_le_finrank_of_fixed`).

The **wild** part is not a *number* on this pin, but since 2026-07-26 it
is no longer wholly opaque either: its **vanishing criterion** is now
definable and is built in. See "## The wild part" below for what changed;
the two bullets immediately following are the (still accurate) reason the
NUMBER `Sw_v(V)` is unavailable:

* mathlib has the decomposition and inertia subgroups of a valuation
  subring (`ValuationSubring.decompositionSubgroup`,
  `ValuationSubring.inertiaSubgroup`, i.e. `G_{-1}` and `G_0`) and an
  explicit `TODO: Define higher ramification groups in lower numbering`
  in `Mathlib/RingTheory/Valuation/RamificationGroup.lean`. There is no
  `Swan`, no `ramificationGroup`, no Artin conductor anywhere in the
  library (the `conductor`s it does have are the ring-theoretic
  conductor of a ring extension and the conductor of a Dirichlet
  character — unrelated invariants).
* the naive repair is unavailable *in principle*: over `Kᵥᵃˡᵍ` the
  lower numbering collapses. The value group of the integral closure of
  `𝒪ᵥ` in `Kᵥᵃˡᵍ` is divisible, so `𝔪 ^ (i + 1) = 𝔪` and every
  `AddSubgroup.inertia (𝔪 ^ (i+1))` equals `localInertiaGroup v`
  itself. The Swan conductor genuinely needs the *upper* numbering,
  i.e. Herbrand's function `ψ` and the finite-level ramification
  filtration — a development of its own.

## The wild part: an opaque NUMBER with a DEFINED vanishing criterion

Both bullets above are about the *number* `Sw_v(V)`, and both still
stand. What they do **not** obstruct is the *criterion* for that number
to be zero, and that is all this development actually consumes:

  `Sw_v(V) = 0  ⟺  the wild inertia P_v acts trivially on V`

(Serre, *Local Fields* VI §2 — the Swan conductor is a sum over the wild
ramification breaks). The wild inertia `P_v = Gal(Kᵥᵃˡᵍ / Kᵥᵗᵃᵐᵉ)` is
definable WITHOUT the ramification filtration, because the maximal tame
extension is generated by the elements `x` with `xⁿ ∈ 𝒪ᵥ` for `n` prime
to the residue characteristic. That is `wildInertiaGroup` below, and the
criterion is `GaloisRep.IsTamelyRamifiedAt`.

Why this matters, concretely: the branch condition of `swanExponent` used
to be `IsUnramifiedAt`, and with that condition the at-`2` wild leaf
`swanExponent_two_eq_zero_of_inertia_sq_eq_zero`
(`Fermat/FLT/Modularity/Interface.lean`) was **unprovable as stated** —
any proof would have had to establish unramifiedness at `2`, which that
leaf's own soundness audit refutes with a conductor-`14` curve at
`p = 5`. With the tame criterion it becomes provable, and reduces to the
single honest local statement that a square-zero-unipotent inertia
action in residue characteristic `≠ p` is trivial on wild inertia.

So the wild part enters as an **uninterpreted constant**
`GaloisRep.swanExponentAux`, declared with Lean's `opaque` command,
guarded by that criterion, and the conductor exponent is the honest sum

  `GaloisRep.conductorExponent ρ v = ρ.tameExponent v + ρ.swanExponent v`,

with `HasConductorExponentAt ρ v a` the *equation* `a = conductorExponent ρ v`.

`opaque` introduces **no axiom and no `sorry`** (`#print axioms` on
anything using it stays empty) and the kernel will not unfold it, so
nothing about its value is provable — which is exactly the intent: the
symbol *denotes* the Swan conductor without computing it. The one
property of the Swan conductor that this development actually needs,
vanishing on a TAMELY RAMIFIED representation, is built into
`swanExponent` by construction (`swanExponent ρ v =
if ρ.IsTamelyRamifiedAt v then 0 else swanExponentAux ρ v`), so both
`GaloisRep.swanExponent_eq_zero_of_isTamelyRamifiedAt` and its
specialization `GaloisRep.swanExponent_eq_zero_of_isUnramifiedAt` are
*theorems* rather than further leaves.

Soundness of this packaging is model-theoretic and is the standard one
for axiomatising an invariant that cannot yet be defined: interpret
`swanExponentAux ρ v` as the true Swan conductor `Sw_v(V)`. Under that
interpretation `conductorExponent ρ v` **is** `a_v(V)`, so every leaf
stated with `HasConductorExponentAt` is precisely the corresponding
statement of the literature — no weaker and no stronger.

## HISTORY: why the previous, existential packaging was WITHDRAWN

Until 2026-07-25 this file packaged the wild summand *existentially*,

  `HasConductorExponentAt ρ v a  :=  ∃ s, a = tameExponent + s ∧
                                     (ρ.IsUnramifiedAt v → s = 0)`,

on the argument that every such statement is *implied* by the true
identity `a_v(V) = a`, hence can never be false.

**That argument is valid only in CONCLUSION position.** The predicate is
UPWARD CLOSED in `a` for a representation that is ramified at `v` (take
`s := a − tameExponent`; the only clause constraining `s` is conditioned
on unramifiedness and is then vacuous). So in HYPOTHESIS position the
weakening *strengthens* the statement, and a leaf consuming
`HasConductorExponentAt ρ v a` in order to derive an UPPER bound on `a`
is thereby asserting `ρ` is unramified at `v`. Exactly one leaf did
this — `hasConductorExponentAt_two_le_one_of_inertia_sq_eq_zero` in
`Fermat/FLT/Modularity/Interface.lean` — and it was consequently FALSE
AS STATED, refuted by the curve `E/ℚ` of conductor `14` at `p = 5` (see
that leaf's docstring for the counterexample in full).

The generalizable rule: an existentially weakened invariant can carry
LOWER-bound content (`a ≠ 0 → ρ` ramified) but never UPPER-bound
content. Pinning `a` to a single opaque value, as is now done, restores
both directions at the cost of an uninterpreted symbol — which is the
right trade, since the alternative is a definition under which half the
intended consumers are unstatable.

## Consumers

`Fermat/FLT/Modularity/Interface.lean` states ONE shared Carayol leaf
`hasConductorExponentAt_factorization_of_isNewAtPrime` in these terms
and derives from it the per-place citations that previously each carried
their own copy of Carayol's theorem.
-/

@[expose] public section

open NumberField IsDedekindDomain

universe uK

variable {K : Type uK} [Field K] [NumberField K]
variable {A : Type*} [CommRing A] [TopologicalSpace A]
variable {M : Type*} [AddCommGroup M] [Module A M]

/-- **The subgroup of the local absolute Galois group fixing every
TAMELY RAMIFIED element**.

Concretely: `σ` lies here when it fixes every `x` of the integral
closure of `𝒪ᵥ` in `Kᵥᵃˡᵍ` some `n`-th power of which already lies in
`𝒪ᵥ`, for `n` prime to the residue characteristic (spelled
`(n : 𝓞 K) ∉ v.asIdeal`, which also forces `n ≠ 0` since `0 ∈ v.asIdeal`).

**Why this is exactly `Gal(Kᵥᵃˡᵍ / Kᵥᵗᵃᵐᵉ)`.** The maximal tamely
ramified extension of a local field `Kᵥ` with residue characteristic `ℓ`
is `Kᵥᵗᵃᵐᵉ = Kᵥⁿʳ(π^{1/n} : ℓ ∤ n)` and `Kᵥⁿʳ = Kᵥ(ζₙ : ℓ ∤ n)`, so it
is generated over `Kᵥ` by elements `x` with `xⁿ ∈ 𝒪ᵥ` and `ℓ ∤ n`
(the `ζₙ` satisfy `ζₙⁿ = 1`, the `π^{1/n}` satisfy `(π^{1/n})ⁿ = π`, and
both are integral). Conversely each such `x` generates a tame extension:
`Kᵥ(x) ⊆ Kᵥ(ζₙ, a^{1/n})` with `ℓ ∤ n`, which is unramified-then-Kummer
of degree prime to `ℓ`. An automorphism fixing `Kᵥ` pointwise and fixing
every such generator therefore fixes all of `Kᵥᵗᵃᵐᵉ` pointwise, and
conversely. Hence this subgroup **is** the wild inertia group.

The point of phrasing it through the *generators* rather than through
the extension is that no theory of the maximal tame extension is needed
to write it down — and that the action used is the very one
`localInertiaGroup` is already built from, so nothing new has to be
instantiated. -/
def tameFixingSubgroup (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K)) :
    Subgroup (Field.absoluteGaloisGroup (v.adicCompletion K)) where
  carrier := {σ | ∀ n : ℕ, (n : 𝓞 K) ∉ v.asIdeal →
    ∀ x : IntegralClosure
        (IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers K v)
        (AlgebraicClosure (v.adicCompletion K)),
      (∃ a : IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers K v,
        x ^ n = algebraMap _ _ a) → σ • x = x}
  mul_mem' {a b} ha hb := by
    intro n hn x hx
    rw [mul_smul, hb n hn x hx, ha n hn x hx]
  one_mem' := by
    intro n _ x _
    rw [one_smul]
  inv_mem' {a} ha := by
    intro n hn x hx
    calc a⁻¹ • x = a⁻¹ • (a • x) := by rw [ha n hn x hx]
      _ = x := by rw [← mul_smul, inv_mul_cancel, one_smul]

/-- **The WILD INERTIA group at a finite place `v`**: the inertia
elements that act trivially on the maximal tamely ramified extension,
i.e. `P_v = Gal(Kᵥᵃˡᵍ / Kᵥᵗᵃᵐᵉ)`, the (unique) Sylow pro-`ℓ` subgroup of
`I_v` for `ℓ` the residue characteristic of `v`.

It is written as `localInertiaGroup v ⊓ tameFixingSubgroup v`. The
intersection changes nothing mathematically — `tameFixingSubgroup v` is
already contained in the inertia, since `Kᵥⁿʳ ⊆ Kᵥᵗᵃᵐᵉ` — but it makes
`wildInertiaGroup_le_localInertiaGroup` free, which is the only
containment this development consumes, and it removes any risk of the
group being accidentally LARGER than the true `P_v` (which is the
direction that would matter for soundness of `swanExponent` below).

This is what makes the Swan conductor's vanishing criterion statable
here without the higher ramification filtration in the upper numbering:
`Sw_v(V) = 0` **iff** `P_v` acts trivially (Serre, *Local Fields* VI §2 —
the Swan conductor is supported on the wild ramification breaks), and
that criterion is what `GaloisRep.IsTamelyRamifiedAt` below records. -/
noncomputable def wildInertiaGroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K)) :
    Subgroup (Field.absoluteGaloisGroup (v.adicCompletion K)) :=
  localInertiaGroup v ⊓ tameFixingSubgroup v

/-- The wild inertia is contained in the inertia — true by construction
of `wildInertiaGroup` as a meet. -/
lemma wildInertiaGroup_le_localInertiaGroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K)) :
    wildInertiaGroup v ≤ localInertiaGroup v := inf_le_left

/-!
### `n`-th roots in the wild inertia, for `n` prime to the residue characteristic

`P_v` is pro-`ℓ`, so for `n` prime to `ℓ` the `n`-th power map is a
bijection on it. The consumer
(`isTamelyRamifiedAt_two_of_inertia_sq_eq_zero` in
`Fermat/FLT/Modularity/Interface.lean`) iterates this to extract `pᵏ`-th
roots INSIDE `P_v`, which is what turns `N σ = τσ − 1` into an
infinitely `p`-divisible value.

This block was cut out of that consumer's file on 2026-07-27 and hoisted
here, beside `wildInertiaGroup` itself, where it belongs. The
decomposition below splits the statement along exactly the seam its
original docstring predicted — a PURELY PROFINITE half and a PURELY
ARITHMETIC half — and **only the arithmetic half is still open**:

* `exists_pow_eq_of_forall_openNormal` — the profinite half, PROVEN, and
  stated for an abstract compact `T1` topological group so it is
  reusable. Roots that exist modulo every open normal subgroup exist on
  the nose, by Cantor's intersection theorem.
* `exists_pow_mem_of_coprime_card_quotient` — the finite-level step,
  PROVEN, pure group theory: `Nat.Coprime.pow_left_bijective`.
* `exists_openNormal_subset_of_mem_nhds_one`,
  `isClosed_wildInertiaGroup` — the topological inputs the profinite
  half needs at `Γ Kᵥ`, both PROVEN.
* `coprime_card_quotient_wildInertiaGroup` — PROVEN 2026-07-27, from the
  leaf below: the reduction of "coprime to `n` for every open normal `U`"
  to a single prime and a single element, via finiteness of the quotient
  (compactness of `Γ Kᵥ` plus the second isomorphism theorem) and
  Cauchy's theorem.
* `mem_of_pow_prime_mem_of_mem_wildInertiaGroup` — PROVEN 2026-07-27
  along the recorded KUMMER route: `P_v` is pro-`ℓ` in the element-level
  form "`σ ∈ P_v` and `σ ^ q ∈ U` force `σ ∈ U`". Its proof needed no
  Sylow step and no maximal-tame-field object — see its docstring for the
  LAGRANGE-RESOLVENT form of Kummer descent that replaced them.
* `smul_eq_self_of_pow_eq_one_of_mem_tameFixingSubgroup` — PROVEN
  2026-07-27, step 1 of that route (`μ_q ⊆ Kᵥᵗᵃᵐᵉ`), and immediate from
  the definition of `tameFixingSubgroup` at `n := q`, `a := 1`.
* `exists_pow_eq_of_smul_eq_self_of_mem_wildInertiaGroup` — **the one
  open leaf**, and the only piece of this block carrying any arithmetic:
  step 2 of that route, `q`-divisibility of the fixed field of `σ`. No
  group, no subgroup and no topology occurs in its statement; what it
  needs is the valuation theory of `Kᵥᵃˡᵍ` (value group `ℚ`, residue
  field `𝔽̄_ℓ`, Hensel), which the pin does not have.
-/

open scoped Topology in
/-- **Roots that exist modulo every open normal subgroup exist on the
nose** (PROVEN 2026-07-27) — the profinite half of "the `n`-th power map
is surjective on a pro-`ℓ` group", carrying NO arithmetic whatsoever.

Stated for an abstract compact `T1` topological group `G` and a CLOSED
subgroup `P`, so that it is reusable at any profinite group: the only
inputs are that open normal subgroups are a neighbourhood basis of `1`
(`hbasis`) and that `n`-th roots exist in `P` modulo each of them
(`hlevel`).

THE PROOF is Cantor's intersection theorem. The sets
`t U := P ∩ (θ ↦ σ⁻¹θⁿ)⁻¹(U)`, indexed by the open normal subgroups, are
closed (an open subgroup is closed, and `θ ↦ σ⁻¹θⁿ` is continuous),
nonempty by `hlevel`, and DIRECTED downwards because `U ⊓ V` is again
open and normal. In a compact space their intersection is therefore
nonempty; any `θ` in it satisfies `σ⁻¹θⁿ ∈ U` for EVERY open normal `U`,
and `T1` plus `hbasis` forces `σ⁻¹θⁿ = 1` — if it were some `g ≠ 1`
then `{g}ᶜ` is a neighbourhood of `1`, so some open normal `U` avoids
`g`, contradiction.

Note `σ ∈ P` is NOT a hypothesis: it follows from the conclusion, and
`hlevel` already places the approximating roots in `P`. -/
theorem exists_pow_eq_of_forall_openNormal
    {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T1Space G]
    (hbasis : ∀ s ∈ 𝓝 (1 : G), ∃ U : Subgroup G, U.Normal ∧ IsOpen (U : Set G) ∧
      (U : Set G) ⊆ s)
    {P : Subgroup G} (hP : IsClosed (P : Set G)) {n : ℕ} {σ : G}
    (hlevel : ∀ U : Subgroup G, U.Normal → IsOpen (U : Set G) →
      ∃ θ ∈ P, σ⁻¹ * θ ^ n ∈ U) :
    ∃ θ ∈ P, θ ^ n = σ := by
  classical
  have hcont : Continuous fun θ : G => σ⁻¹ * θ ^ n := (continuous_pow n).const_mul _
  set t : {U : Subgroup G // U.Normal ∧ IsOpen (U : Set G)} → Set G :=
    fun U => (P : Set G) ∩ (fun θ : G => σ⁻¹ * θ ^ n) ⁻¹' (U.1 : Set G) with ht
  have hne : Nonempty {U : Subgroup G // U.Normal ∧ IsOpen (U : Set G)} :=
    ⟨⟨⊤, inferInstance, by simp⟩⟩
  have hclosed : ∀ U, IsClosed (t U) := by
    intro U
    exact hP.inter ((Subgroup.isClosed_of_isOpen _ U.2.2).preimage hcont)
  have hdir : Directed (· ⊇ ·) t := by
    rintro ⟨U, hUn, hUo⟩ ⟨V, hVn, hVo⟩
    refine ⟨⟨U ⊓ V, ?_, ?_⟩, ?_, ?_⟩
    · exact ⟨fun a ha g => ⟨hUn.conj_mem a ha.1 g, hVn.conj_mem a ha.2 g⟩⟩
    · simpa [Subgroup.coe_inf] using hUo.inter hVo
    · exact Set.inter_subset_inter_right _
        (Set.preimage_mono (by simp [Subgroup.coe_inf]))
    · exact Set.inter_subset_inter_right _
        (Set.preimage_mono (by simp [Subgroup.coe_inf]))
  have hnonempty : ∀ U, (t U).Nonempty := by
    rintro ⟨U, hUn, hUo⟩
    obtain ⟨θ, hθP, hθU⟩ := hlevel U hUn hUo
    exact ⟨θ, hθP, hθU⟩
  obtain ⟨θ, hθ⟩ := IsCompact.nonempty_iInter_of_directed_nonempty_isCompact_isClosed
    t hdir hnonempty (fun U => (hclosed U).isCompact) hclosed
  simp only [Set.mem_iInter, ht, Set.mem_inter_iff, Set.mem_preimage] at hθ
  refine ⟨θ, (hθ ⟨⊤, inferInstance, by simp⟩).1, ?_⟩
  have hone : σ⁻¹ * θ ^ n = 1 := by
    by_contra hg
    have hmem : ({σ⁻¹ * θ ^ n}ᶜ : Set G) ∈ 𝓝 (1 : G) :=
      (isOpen_compl_singleton).mem_nhds (by simpa [eq_comm] using hg)
    obtain ⟨U, hUn, hUo, hUs⟩ := hbasis _ hmem
    exact hUs (hθ ⟨U, hUn, hUo⟩).2 rfl
  rw [← mul_left_cancel_iff (a := σ⁻¹), hone, inv_mul_cancel]

/-- **The finite level: a quotient of order coprime to `n` has `n`-th
roots** (PROVEN 2026-07-27). Pure group theory —
`Nat.Coprime.pow_left_bijective` says `x ↦ xⁿ` is a bijection of a group
whose `Nat.card` is coprime to `n`, and no finiteness hypothesis is
needed because `pow_card_eq_one'` holds vacuously when `Nat.card = 0`.

This is the step that CONSUMES the pro-`ℓ` input: with
`P ⧸ (U ∩ P)` an `ℓ`-group and `ℓ ∤ n`, the hypothesis `hcop` holds. -/
theorem exists_pow_mem_of_coprime_card_quotient
    {G : Type*} [Group G] {P U : Subgroup G} [hU : U.Normal] {n : ℕ}
    (hcop : Nat.Coprime (Nat.card (P ⧸ U.subgroupOf P)) n)
    {σ : G} (hσ : σ ∈ P) :
    ∃ θ ∈ P, σ⁻¹ * θ ^ n ∈ U := by
  haveI : (U.subgroupOf P).Normal := hU.subgroupOf P
  obtain ⟨q, hq⟩ := hcop.pow_left_bijective.surjective
    (QuotientGroup.mk (⟨σ, hσ⟩ : P))
  obtain ⟨θ', rfl⟩ := QuotientGroup.mk_surjective q
  refine ⟨(θ' : G), θ'.2, ?_⟩
  have hq' : (QuotientGroup.mk (θ' ^ n) : P ⧸ U.subgroupOf P) =
      QuotientGroup.mk (⟨σ, hσ⟩ : P) := by
    simpa [QuotientGroup.mk_pow] using hq
  rw [eq_comm, QuotientGroup.eq, Subgroup.mem_subgroupOf] at hq'
  simpa using hq'

open scoped Topology in
/-- **Open NORMAL subgroups are a neighbourhood basis of `1` in `Γ Kᵥ`**
(PROVEN 2026-07-27). Mathlib's `krullTopology_mem_nhds_one_iff_of_normal`
supplies a finite NORMAL intermediate field `E` with
`E.fixingSubgroup ⊆ s`; `Kᵥ` has characteristic zero, so `E/Kᵥ` is
automatically separable and hence Galois, and
`IsGalois.fixingSubgroup_normal_of_isGalois` then makes that fixing
subgroup normal. Openness is `IntermediateField.fixingSubgroup_isOpen`. -/
theorem exists_openNormal_subset_of_mem_nhds_one
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K))
    (s : Set (Field.absoluteGaloisGroup (v.adicCompletion K)))
    (hs : s ∈ 𝓝 (1 : Field.absoluteGaloisGroup (v.adicCompletion K))) :
    ∃ U : Subgroup (Field.absoluteGaloisGroup (v.adicCompletion K)), U.Normal ∧
      IsOpen (U : Set (Field.absoluteGaloisGroup (v.adicCompletion K))) ∧
      (U : Set (Field.absoluteGaloisGroup (v.adicCompletion K))) ⊆ s := by
  obtain ⟨E, hfin, hnorm, hsub⟩ :=
    (krullTopology_mem_nhds_one_iff_of_normal (v.adicCompletion K)
      (AlgebraicClosure (v.adicCompletion K)) s).mp hs
  haveI := hfin
  haveI := hnorm
  haveI : IsGalois (v.adicCompletion K) (AlgebraicClosure (v.adicCompletion K)) := ⟨⟩
  haveI : IsGalois (v.adicCompletion K) E := ⟨⟩
  exact ⟨E.fixingSubgroup, inferInstance, E.fixingSubgroup_isOpen, hsub⟩

/-- The set of `σ` fixing a given integral element is CLOSED. It is the
stabilizer, which `ContinuousSMulDiscrete` makes open, and an open
subgroup is closed. -/
theorem isClosed_setOf_smul_eq_self
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K))
    (x : IntegralClosure
      (IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers K v)
      (AlgebraicClosure (v.adicCompletion K))) :
    IsClosed {σ : Field.absoluteGaloisGroup (v.adicCompletion K) | σ • x = x} :=
  Subgroup.isClosed_of_isOpen
    (MulAction.stabilizer (Field.absoluteGaloisGroup (v.adicCompletion K)) x)
    (ContinuousSMulDiscrete.isOpen_smul_eq _ x x)

/-- **`tameFixingSubgroup v` is closed**: it is by definition an
intersection of stabilizers of integral elements, each closed by
`isClosed_setOf_smul_eq_self`. -/
theorem isClosed_tameFixingSubgroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K)) :
    IsClosed ((tameFixingSubgroup v :
      Set (Field.absoluteGaloisGroup (v.adicCompletion K)))) := by
  have hrw : (tameFixingSubgroup v :
        Set (Field.absoluteGaloisGroup (v.adicCompletion K))) =
      ⋂ (n : ℕ) (_ : (n : 𝓞 K) ∉ v.asIdeal)
        (x : IntegralClosure
          (IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers K v)
          (AlgebraicClosure (v.adicCompletion K)))
        (_ : ∃ a : IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers K v,
          x ^ n = algebraMap _ _ a),
        {σ : Field.absoluteGaloisGroup (v.adicCompletion K) | σ • x = x} := by
    ext σ
    simp only [Set.mem_iInter, Set.mem_setOf_eq]
    rfl
  rw [hrw]
  exact isClosed_iInter fun n => isClosed_iInter fun _ => isClosed_iInter fun x =>
    isClosed_iInter fun _ => isClosed_setOf_smul_eq_self v x

/-- **`localInertiaGroup v` is closed.** `AddSubgroup.inertia` is the set
of `σ` with `σ • x − x ∈ 𝔪` for every `x` of the integral closure, and
each such condition is CLOPEN: its complement is the union over the
`y` with `y − x ∉ 𝔪` of the open sets `{σ | σ • x = y}`
(`ContinuousSMulDiscrete`). -/
theorem isClosed_localInertiaGroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K)) :
    IsClosed ((localInertiaGroup v :
      Set (Field.absoluteGaloisGroup (v.adicCompletion K)))) := by
  set R := IntegralClosure
    (IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers K v)
    (AlgebraicClosure (v.adicCompletion K)) with hR
  have key : ∀ x : R,
      IsClosed {σ : Field.absoluteGaloisGroup (v.adicCompletion K) |
        σ • x - x ∈ IsLocalRing.maximalIdeal R} := by
    intro x
    rw [← isOpen_compl_iff]
    have hc : {σ : Field.absoluteGaloisGroup (v.adicCompletion K) |
          σ • x - x ∈ IsLocalRing.maximalIdeal R}ᶜ =
        ⋃ (y : R) (_ : y - x ∉ IsLocalRing.maximalIdeal R),
          {σ : Field.absoluteGaloisGroup (v.adicCompletion K) | σ • x = y} := by
      ext σ
      simp only [Set.mem_compl_iff, Set.mem_setOf_eq, Set.mem_iUnion]
      exact ⟨fun h => ⟨σ • x, h, rfl⟩, by rintro ⟨y, hy, rfl⟩; exact hy⟩
    rw [hc]
    exact isOpen_iUnion fun y => isOpen_iUnion fun _ =>
      ContinuousSMulDiscrete.isOpen_smul_eq _ x y
  have hrw : (localInertiaGroup v :
        Set (Field.absoluteGaloisGroup (v.adicCompletion K))) =
      ⋂ x : R, {σ : Field.absoluteGaloisGroup (v.adicCompletion K) |
        σ • x - x ∈ IsLocalRing.maximalIdeal R} := by
    ext σ
    simp only [Set.mem_iInter, Set.mem_setOf_eq]
    rfl
  rw [hrw]
  exact isClosed_iInter key

/-- **The wild inertia is closed** — a meet of two closed subgroups. -/
theorem isClosed_wildInertiaGroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K)) :
    IsClosed ((wildInertiaGroup v :
      Set (Field.absoluteGaloisGroup (v.adicCompletion K)))) := by
  rw [wildInertiaGroup, Subgroup.coe_inf]
  exact (isClosed_localInertiaGroup v).inter (isClosed_tameFixingSubgroup v)

/-- **Bézout in a subgroup**: if two COPRIME powers of `σ` lie in `U`,
then `σ` does. Pure group theory, stated for an arbitrary group — it is
what turns "no `σ ^ m` with `0 < m < q` fixes the fixed field of `U`"
into the distinctness of the `q` restrictions the Lagrange resolvent
below is built from. -/
theorem Subgroup.mem_of_coprime_pow_mem {G : Type*} [Group G] {U : Subgroup G} {σ : G}
    {m n : ℕ} (hmn : Nat.Coprime m n) (hm : σ ^ m ∈ U) (hn : σ ^ n ∈ U) : σ ∈ U := by
  have key : (m : ℤ) * Nat.gcdA m n + (n : ℤ) * Nat.gcdB m n = 1 := by
    have h := Nat.gcd_eq_gcd_ab m n
    rw [hmn] at h
    exact_mod_cast h.symm
  have hmem : σ ^ ((m : ℤ) * Nat.gcdA m n + (n : ℤ) * Nat.gcdB m n) ∈ U := by
    rw [zpow_add, zpow_mul, zpow_mul, zpow_natCast, zpow_natCast]
    exact mul_mem (zpow_mem hm _) (zpow_mem hn _)
  rwa [key, zpow_one] at hmem

/-- **`μ_n ⊆ Kᵥᵗᵃᵐᵉ` FOR `n` PRIME TO THE RESIDUE CHARACTERISTIC**
(PROVEN 2026-07-27) — step 1 of the Kummer route recorded below, and
immediate from the DEFINITION of `tameFixingSubgroup`, with no
arithmetic at all: an `n`-th root of unity `ζ` is integral over `𝒪ᵥ`
(it is a root of the monic `X ^ n - 1`) and satisfies `ζ ^ n = 1`, i.e.
the defining condition of `tameFixingSubgroup` at `a := 1`. So every
element of the wild inertia fixes it.

This is what makes the Lagrange resolvent below transform correctly:
`σ (ζ⁻¹ ^ i · σ ^ i x) = ζ⁻¹ ^ i · σ ^ (i+1) x` needs precisely
`σ ζ = ζ`. -/
theorem smul_eq_self_of_pow_eq_one_of_mem_tameFixingSubgroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K))
    {n : ℕ} (hn : (n : 𝓞 K) ∉ v.asIdeal)
    {σ : Field.absoluteGaloisGroup (v.adicCompletion K)}
    (hσ : σ ∈ tameFixingSubgroup v)
    {ζ : AlgebraicClosure (v.adicCompletion K)} (hζ : ζ ^ n = 1) :
    σ ζ = ζ := by
  have hn0 : n ≠ 0 := by
    rintro rfl
    exact hn (by simp)
  have hint : IsIntegral
      (IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers K v) ζ :=
    ⟨Polynomial.X ^ n - Polynomial.C 1, Polynomial.monic_X_pow_sub_C 1 hn0, by simp [hζ]⟩
  set x : IntegralClosure
      (IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers K v)
      (AlgebraicClosure (v.adicCompletion K)) := ⟨ζ, hint⟩ with hx
  have hxn : x ^ n = algebraMap _ _
      (1 : IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers K v) := by
    rw [map_one]
    apply Subtype.ext
    show ζ ^ n = 1
    exact hζ
  have hfix : σ • x = x := hσ n hn x ⟨1, hxn⟩
  have h2 : (σ • x).1 = x.1 := congrArg Subtype.val hfix
  rw [IntegralClosure.coe_smul] at h2
  exact h2

/-- **`q`-DIVISIBILITY OF THE FIXED FIELD OF AN ELEMENT OF THE WILD
INERTIA** (SORRY LEAF; CUT 2026-07-27 out of
`mem_of_pow_prime_mem_of_mem_wildInertiaGroup` below, which is now
PROVEN from it). This is step 2 — and ONLY step 2 — of the Kummer route
that leaf's previous docstring recorded. Steps 1 and 3 are discharged
(`smul_eq_self_of_pow_eq_one_of_mem_tameFixingSubgroup` above and the
resolvent argument below), and what is left here is a single statement
of local field ARITHMETIC in which no Galois group, no subgroup and no
topology occurs.

STATEMENT IN WORDS: if `σ` lies in the wild inertia `P_v` and fixes an
element `a` of `Kᵥᵃˡᵍ`, then `a` has a `q`-th root that `σ` ALSO fixes,
for every prime `q` other than the residue characteristic `ℓ`.

WHY IT IS TRUE. Write `F` for the fixed field of the closed subgroup
topologically generated by `σ`; then `a ∈ F`, and `F ⊇ Kᵥᵗᵃᵐᵉ =: T`,
because `σ ∈ P_v = Gal(Kᵥᵃˡᵍ/T)`. So it suffices that `Fˣ` is
`q`-divisible for EVERY algebraic extension `F/T` inside `Kᵥᵃˡᵍ`, and
that splits along the valuation exactly as the route records:

* THE VALUE GROUP. `Γ_T = ℤ[1/m : ℓ ∤ m] ⊆ ℚ` by construction (the
  `m`-th roots of a uniformiser are adjoined for every `m` prime to
  `ℓ`), and `Γ_{Kᵥᵃˡᵍ} = ℚ`, so `Γ_F/Γ_T` embeds in
  `ℚ/Γ_T ≅ ℤ[1/ℓ]/ℤ`, the Prüfer `ℓ`-group. That quotient is
  `q`-divisible and `q`-torsion-free for `q ≠ ℓ`, and `Γ_T` is itself
  `q`-divisible, so `Γ_F` is `q`-divisible.
* THE UNITS. `F` is henselian (an algebraic extension of a henselian
  valued field is henselian) and its residue field is `𝔽̄_ℓ` — it
  contains the residue field of `T`, which is already algebraically
  closed. So `X ^ q - ū` has a root there, and `X ^ q - u` is separable
  because `q ≠ ℓ`; Hensel lifts the root.

Given both: write `val a = q · γ` with `γ ∈ Γ_F`, pick `c ∈ F` of value
`γ`, and take a `q`-th root of the unit `a / c ^ q`. (For `a = 0` take
`b = 0`; that case is why no `a ≠ 0` hypothesis is carried.)

### WHY IT IS PHRASED THROUGH `σ` AND NOT THROUGH `Tˣ`

The previous docstring flagged one gap in the sketch: Cauchy produces a
cyclic degree-`q` extension of some INTERMEDIATE field `E/T`, not of `T`
itself, and it proposed either proving step 2 for every finite extension
of `T` or passing to a procyclic subgroup. Stating the leaf through `σ`
removes the gap outright — it never needs `T` as an object, never needs
a Sylow subgroup of a finite quotient, and never needs `q`-divisibility
transported anywhere, because the consumer's Lagrange-resolvent argument
only ever asks for a `q`-th root fixed by the SAME `σ`.

### WHAT IS MISSING FROM THE PIN — checked 2026-07-27

None of this is a group- or Galois-theoretic gap; it is the valuation
theory of `Kᵥᵃˡᵍ`, which mathlib does not have in the form needed:

* nothing in the pin puts a valuation on
  `AlgebraicClosure (v.adicCompletion K)` beyond
  `Mathlib/Analysis/Normed/Unbundled/SpectralNorm.lean` (already in this
  file's import cone), and nothing computes its value group or its
  residue field;
* `grep -rn "DivisibleBy\|divisible" Mathlib/RingTheory/Valuation/` is
  EMPTY — there is no divisible-value-group API at all;
* `Mathlib/RingTheory/Henselian.lean` has henselian LOCAL RINGS but not
  the statement that an algebraic extension of a henselian VALUED FIELD
  is henselian.

THE CHECK THAT WOULD REFUTE THIS: find, in the pin or in `~/cs/FLT`, a
valuation on `AlgebraicClosure (v.adicCompletion K)` together with a
computation of its residue field. If one exists, both bullets are
ordinary applications of Hensel's lemma and this leaf is short.

Every hypothesis is underscore-prefixed because the body is `sorry`;
all three are genuinely needed and must be consumed by a real proof. -/
theorem exists_pow_eq_of_smul_eq_self_of_mem_wildInertiaGroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K))
    {q : ℕ} (_hq : q.Prime) (_hqv : (q : 𝓞 K) ∉ v.asIdeal)
    {σ : Field.absoluteGaloisGroup (v.adicCompletion K)}
    (_hσ : σ ∈ wildInertiaGroup v)
    {a : AlgebraicClosure (v.adicCompletion K)} (_hfix : σ a = a) :
    ∃ b : AlgebraicClosure (v.adicCompletion K), σ b = b ∧ b ^ q = a :=
  sorry

/-- **THE WILD INERTIA IS PRO-`ℓ`, IN ITS ELEMENT-LEVEL FORM** (PROVEN
2026-07-27 from the single arithmetic leaf
`exists_pow_eq_of_smul_eq_self_of_mem_wildInertiaGroup` above; everything
else — the Galois correspondence, the Kummer descent, the group theory —
is discharged here).

STATEMENT IN WORDS: if `σ` lies in the wild inertia `P_v` and its `q`-th
power already lies in the open normal subgroup `U`, then `σ` itself lies
in `U` — i.e. the finite quotient `P_v ⧸ (U ∩ P_v)` has NO ELEMENT OF
ORDER `q`, for `q` any prime other than the residue characteristic `ℓ`
(spelled `(q : 𝓞 K) ∉ v.asIdeal`).

This is EXACTLY the classical assertion that `P_v = Gal(Kᵥᵃˡᵍ / Kᵥᵗᵃᵐᵉ)`
is pro-`ℓ` — "every finite continuous quotient of `P_v` is an `ℓ`-group"
— restated one prime and one element at a time, which is the only form
the consumer needs.

### THE PROOF — Kummer theory as a LAGRANGE RESOLVENT, not via `Kᵥᵗᵃᵐᵉ`

The route the previous docstring recorded is the right one — Kummer
theory, never Ostrowski's defect theorem — but it is carried out here in
a form that needs neither the maximal tame field as an OBJECT, nor a
Sylow subgroup, nor mathlib's `KummerExtension.lean`. That matters: the
gap that sketch flagged (Cauchy gives a cyclic degree-`q` extension of
some intermediate `E/T`, not of `T` itself, so `q`-divisibility has to be
transported) simply does not arise, because the resolvent is built from
`σ` and its `q`-th root is asked of `σ` again.

Suppose `σ ∉ U`, and let `E := IntermediateField.fixedField U`.

1. **`σ ^ q` fixes `E` pointwise**, since `σ ^ q ∈ U`; and for
   `0 < m < q` **no `σ ^ m` does**. Indeed `σ ^ m` fixing `E` pointwise
   means `σ ^ m ∈ E.fixingSubgroup = U` — this is where the infinite
   Galois correspondence enters, through
   `InfiniteGalois.fixingSubgroup_fixedField` at the CLOSED (because
   open) subgroup `U` — and then `Nat.Coprime m q` plus `σ ^ q ∈ U`
   gives `σ ∈ U` by Bézout
   (`Subgroup.mem_of_coprime_pow_mem` above), a contradiction.
2. So the `q` monoid homomorphisms `E →* Kᵥᵃˡᵍ` given by
   `y ↦ σ ^ i y`, `i < q`, are PAIRWISE DISTINCT, hence linearly
   independent over `Kᵥᵃˡᵍ` by **Dedekind's independence of characters**
   (`linearIndependent_monoidHom`). Therefore the LAGRANGE RESOLVENT
   `α := ∑_{i<q} ζ⁻¹ ^ i · σ ^ i y` is nonzero for some `y ∈ E`, where
   `ζ` is a primitive `q`-th root of unity in `Kᵥᵃˡᵍ` (it exists:
   `Kᵥᵃˡᵍ` is algebraically closed of characteristic zero, so
   `cyclotomic q` has a root).
3. `σ α = ζ α`. Reindexing the sum costs exactly the two facts that
   `σ ζ = ζ` (step 1 of the recorded route,
   `smul_eq_self_of_pow_eq_one_of_mem_tameFixingSubgroup` above, which
   is immediate from the DEFINITION of `tameFixingSubgroup`) and
   `σ ^ q y = y` — the latter is what makes the wrapped-around term
   `i = q` equal the `i = 0` term.
4. Hence `σ (α ^ q) = ζ ^ q α ^ q = α ^ q`. The arithmetic leaf supplies
   `b` with `σ b = b` and `b ^ q = α ^ q`; then `(α b⁻¹) ^ q = 1`, so
   `σ` fixes `α b⁻¹` (step 1 again), i.e. `ζ (α b⁻¹) = α b⁻¹` with
   `α b⁻¹ ≠ 0`. So `ζ = 1`, contradicting `q` prime.

Steps 1–4 use `hqv` only through the two lemmas above, which is right:
the residue characteristic is the ONLY arithmetic input, and it has been
pushed entirely into the leaf.

NOTE FOR THE NEXT OWNER: with the leaf above proven, this closes
`coprime_card_quotient_wildInertiaGroup` and
`exists_pow_eq_of_mem_wildInertiaGroup` below, and with them step 3 — the
last open step — of `isTamelyRamifiedAt_two_of_inertia_sq_eq_zero` in
`Fermat/FLT/Modularity/Interface.lean`. Nothing else is in the way. -/
theorem mem_of_pow_prime_mem_of_mem_wildInertiaGroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K))
    {q : ℕ} (hq : q.Prime) (hqv : (q : 𝓞 K) ∉ v.asIdeal)
    (U : Subgroup (Field.absoluteGaloisGroup (v.adicCompletion K))) [U.Normal]
    (hU : IsOpen (U : Set (Field.absoluteGaloisGroup (v.adicCompletion K))))
    {σ : Field.absoluteGaloisGroup (v.adicCompletion K)}
    (hσ : σ ∈ wildInertiaGroup v) (hpow : σ ^ q ∈ U) :
    σ ∈ U := by
  classical
  by_contra hσU
  haveI : IsGalois (v.adicCompletion K) (AlgebraicClosure (v.adicCompletion K)) := ⟨⟩
  have hσt : σ ∈ tameFixingSubgroup v := hσ.2
  set E : IntermediateField (v.adicCompletion K) (AlgebraicClosure (v.adicCompletion K)) :=
    IntermediateField.fixedField U with hEdef
  have hfixsub : E.fixingSubgroup = U :=
    InfiniteGalois.fixingSubgroup_fixedField ⟨U, Subgroup.isClosed_of_isOpen U hU⟩
  -- STEP 1a. `σ ^ q` fixes `E` pointwise.
  have hσqfix : ∀ y : E, (σ ^ q) (y : AlgebraicClosure (v.adicCompletion K)) = (y : _) := by
    intro y
    exact y.2 ⟨σ ^ q, hpow⟩
  -- STEP 1b. No `σ ^ m` with `0 < m < q` fixes `E` pointwise.
  have hkey : ∀ m : ℕ, 0 < m → m < q →
      ∃ y : E, (σ ^ m) (y : AlgebraicClosure (v.adicCompletion K)) ≠ (y : _) := by
    intro m hm0 hmq
    by_contra hcon
    have hcon' : ∀ y : E, (σ ^ m) (y : AlgebraicClosure (v.adicCompletion K)) = (y : _) := by
      intro y
      by_contra hy
      exact hcon ⟨y, hy⟩
    have hmemfix : σ ^ m ∈ E.fixingSubgroup := by
      rw [IntermediateField.mem_fixingSubgroup_iff]
      intro y hy
      exact hcon' ⟨y, hy⟩
    rw [hfixsub] at hmemfix
    exact hσU (Subgroup.mem_of_coprime_pow_mem
      (Nat.Coprime.symm ((Nat.Prime.coprime_iff_not_dvd hq).mpr
        (Nat.not_dvd_of_pos_of_lt hm0 hmq))) hmemfix hpow)
  -- STEP 2. the `q` restrictions `y ↦ σ ^ i y` are pairwise distinct monoid homs.
  set F : Fin q → (E →* AlgebraicClosure (v.adicCompletion K)) := fun i =>
    { toFun := fun y => (σ ^ (i : ℕ)) (y : AlgebraicClosure (v.adicCompletion K))
      map_one' := by simp
      map_mul' := fun a b => by simp } with hFdef
  have hFinj : Function.Injective F := by
    intro i j hij
    by_contra hne
    have hstep : ∀ i j : Fin q, F i = F j → (i : ℕ) < (j : ℕ) → False := by
      intro i j hFij hlt
      obtain ⟨y, hy⟩ := hkey ((j : ℕ) - (i : ℕ)) (by omega) (by omega)
      apply hy
      have h1 : (σ ^ (i : ℕ)) (y : AlgebraicClosure (v.adicCompletion K))
          = (σ ^ (j : ℕ)) (y : AlgebraicClosure (v.adicCompletion K)) :=
        congrFun (congrArg (fun f : E →* AlgebraicClosure (v.adicCompletion K) =>
          (f : E → AlgebraicClosure (v.adicCompletion K))) hFij) y
      have h2 : (σ ^ (j : ℕ)) (y : AlgebraicClosure (v.adicCompletion K))
          = (σ ^ (i : ℕ)) ((σ ^ ((j : ℕ) - (i : ℕ)))
            (y : AlgebraicClosure (v.adicCompletion K))) := by
        rw [← AlgEquiv.mul_apply, ← pow_add]
        congr 2
        omega
      exact ((σ ^ (i : ℕ)).injective (by rw [h1, h2])).symm
    rcases lt_trichotomy (i : ℕ) (j : ℕ) with h | h | h
    · exact hstep i j hij h
    · exact hne (Fin.ext h)
    · exact hstep j i hij.symm h
  -- a primitive `q`-th root of unity in `Kᵥᵃˡᵍ`.
  obtain ⟨ζ, hζ⟩ : ∃ ζ : AlgebraicClosure (v.adicCompletion K), IsPrimitiveRoot ζ q := by
    obtain ⟨z, hz⟩ := IsAlgClosed.exists_root
      (Polynomial.cyclotomic q (AlgebraicClosure (v.adicCompletion K)))
      (Polynomial.degree_cyclotomic_pos q _ hq.pos).ne.symm
    exact ⟨z, (Polynomial.isRoot_cyclotomic_iff_charZero hq.pos).mp hz⟩
  have hζq : ζ ^ q = 1 := hζ.pow_eq_one
  have hζ0 : ζ ≠ 0 := hζ.ne_zero hq.ne_zero
  have hζ1 : ζ ≠ 1 := hζ.ne_one hq.one_lt
  -- STEP 2 (continued). the Lagrange resolvent is not identically zero, by
  -- Dedekind's linear independence of characters.
  have hli : LinearIndependent (AlgebraicClosure (v.adicCompletion K))
      (fun i : Fin q => (F i : E → AlgebraicClosure (v.adicCompletion K))) :=
    (linearIndependent_monoidHom E (AlgebraicClosure (v.adicCompletion K))).comp F hFinj
  obtain ⟨y, hy⟩ : ∃ y : E, ∑ i ∈ Finset.range q,
      (ζ⁻¹) ^ i * (σ ^ i) (y : AlgebraicClosure (v.adicCompletion K)) ≠ 0 := by
    by_contra hcon
    have hcon' : ∀ y : E, ∑ i ∈ Finset.range q,
        (ζ⁻¹) ^ i * (σ ^ i) (y : AlgebraicClosure (v.adicCompletion K)) = 0 := by
      intro y
      by_contra hyy
      exact hcon ⟨y, hyy⟩
    have hall : ∀ i : Fin q, (ζ⁻¹) ^ (i : ℕ) = 0 := by
      refine Fintype.linearIndependent_iff.mp hli (fun i => (ζ⁻¹) ^ (i : ℕ)) ?_
      funext y
      simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul, Pi.zero_apply, hFdef,
        MonoidHom.coe_mk, OneHom.coe_mk]
      rw [Fin.sum_univ_eq_sum_range
        (fun i => (ζ⁻¹) ^ i * (σ ^ i) (y : AlgebraicClosure (v.adicCompletion K))) q]
      exact hcon' y
    have := hall ⟨0, hq.pos⟩
    simp at this
  set g : ℕ → AlgebraicClosure (v.adicCompletion K) := fun j =>
    (ζ⁻¹) ^ j * (σ ^ j) (y : AlgebraicClosure (v.adicCompletion K)) with hgdef
  set α : AlgebraicClosure (v.adicCompletion K) := ∑ i ∈ Finset.range q, g i with hαdef
  have hσζ : σ ζ = ζ :=
    smul_eq_self_of_pow_eq_one_of_mem_tameFixingSubgroup v hqv hσt hζq
  -- STEP 3. `σ α = ζ α`: the `i = q` term wraps around onto the `i = 0` term.
  have hshift : ∑ i ∈ Finset.range q, g (i + 1) = ∑ i ∈ Finset.range q, g i := by
    have e1 := Finset.sum_range_succ' g q
    have e2 := Finset.sum_range_succ g q
    have h1 : (ζ⁻¹) ^ q = 1 := by rw [inv_pow, hζq, inv_one]
    have h2 : (σ ^ q) (y : AlgebraicClosure (v.adicCompletion K)) = (y : _) := hσqfix y
    have e3 : g q = g 0 := by
      simp only [hgdef, h1, h2, one_mul, pow_zero, AlgEquiv.one_apply]
    rw [e3] at e2
    exact add_right_cancel (e1.symm.trans e2)
  have hstep : ∀ i : ℕ, σ (g i) = ζ * g (i + 1) := by
    intro i
    have hs : σ ((σ ^ i) (y : AlgebraicClosure (v.adicCompletion K)))
        = (σ ^ (i + 1)) (y : AlgebraicClosure (v.adicCompletion K)) := by
      rw [← AlgEquiv.mul_apply, ← pow_succ']
    have hc : ζ * ζ⁻¹ ^ (i + 1) = ζ⁻¹ ^ i := by
      rw [pow_succ, ← mul_assoc, mul_comm ζ (ζ⁻¹ ^ i), mul_assoc, mul_inv_cancel₀ hζ0, mul_one]
    simp only [hgdef, map_mul, map_pow, map_inv₀, hσζ, hs]
    rw [← mul_assoc, hc]
  have hσα : σ α = ζ * α := by
    rw [hαdef, map_sum]
    conv_rhs => rw [← hshift]
    rw [Finset.mul_sum]
    exact Finset.sum_congr rfl fun i _ => hstep i
  -- STEP 4. `α ^ q` is `σ`-fixed, so the arithmetic leaf gives it a `σ`-fixed
  -- `q`-th root, and `α` divided by that root is a `q`-th root of unity.
  have hfixα : σ (α ^ q) = α ^ q := by rw [map_pow, hσα, mul_pow, hζq, one_mul]
  obtain ⟨b, hb1, hb2⟩ :=
    exists_pow_eq_of_smul_eq_self_of_mem_wildInertiaGroup v hq hqv hσ hfixα
  have hb0 : b ≠ 0 := by
    intro h
    rw [h, zero_pow hq.ne_zero] at hb2
    exact pow_ne_zero q hy hb2.symm
  have hw0 : α * b⁻¹ ≠ 0 := mul_ne_zero hy (inv_ne_zero hb0)
  have hwq : (α * b⁻¹) ^ q = 1 := by
    rw [mul_pow, inv_pow, hb2, mul_inv_cancel₀ (pow_ne_zero q hy)]
  have hσw : σ (α * b⁻¹) = α * b⁻¹ :=
    smul_eq_self_of_pow_eq_one_of_mem_tameFixingSubgroup v hqv hσt hwq
  rw [map_mul, map_inv₀, hb1, hσα] at hσw
  refine hζ1 (mul_right_cancel₀ hw0 ?_)
  rw [one_mul, ← mul_assoc]
  exact hσw

/-- **Every finite continuous quotient of the wild inertia has order
coprime to `n`, for `n` prime to the residue characteristic** (PROVEN
2026-07-27 through `mem_of_pow_prime_mem_of_mem_wildInertiaGroup` above,
which is itself PROVEN modulo the single arithmetic leaf
`exists_pow_eq_of_smul_eq_self_of_mem_wildInertiaGroup`; everything here
is group theory and topology).

Quantifying over the open normal `U ≤ Γ Kᵥ` and taking `U.subgroupOf P_v`
is exactly "every finite continuous quotient of `P_v`": `U` open makes
`P_v ⧸ (U ∩ P_v)` finite, and open normal subgroups are cofinal
(`exists_openNormal_subset_of_mem_nhds_one` above).

THE PROOF, in five steps, and note that the FINITENESS is not a side
condition one may skip — `Nat.Coprime 0 n` is false for `n ≠ 1`, so the
statement is genuinely wrong without it:

1. `Γ Kᵥ` is COMPACT and `U` is open, so `Γ ⧸ U` is finite
   (`Subgroup.quotient_finite_of_isOpen`).
2. `Nat.card (P_v ⧸ U.subgroupOf P_v)` is by definition the RELATIVE
   index `U.relIndex P_v`, which divides `U.index` because `U` is normal
   (`Subgroup.relIndex_dvd_index_of_normal` — the second isomorphism
   theorem). So it is nonzero, and the quotient is finite.
3. If it were not coprime to `n`, a common PRIME `q` exists
   (`Nat.Prime.not_coprime_iff_dvd`). From `q ∣ n` and `hn` we get
   `(q : 𝓞 K) ∉ v.asIdeal`, i.e. `q ≠ ℓ` — this is the ONLY place `hn` is
   used, and it is used exactly once.
4. CAUCHY (`exists_prime_orderOf_dvd_card'`) produces an element of order
   exactly `q` in that finite quotient; lift it to `σ ∈ P_v` with
   `σ ^ q ∈ U`.
5. The pro-`ℓ` leaf then puts `σ` itself in `U`, so its class is trivial,
   contradicting `orderOf … = q > 1`. -/
theorem coprime_card_quotient_wildInertiaGroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K))
    {n : ℕ} (hn : (n : 𝓞 K) ∉ v.asIdeal)
    (U : Subgroup (Field.absoluteGaloisGroup (v.adicCompletion K))) [U.Normal]
    (hU : IsOpen (U : Set (Field.absoluteGaloisGroup (v.adicCompletion K)))) :
    Nat.Coprime
      (Nat.card (wildInertiaGroup v ⧸ U.subgroupOf (wildInertiaGroup v))) n := by
  classical
  -- STEP 1. `Γ ⧸ U` is FINITE: `U` is open in the compact group `Γ Kᵥ`.
  haveI hfinΓ : Finite (Field.absoluteGaloisGroup (v.adicCompletion K) ⧸ U) :=
    Subgroup.quotient_finite_of_isOpen U hU
  -- STEP 2. hence `P_v ⧸ (U ∩ P_v)` is finite too: its cardinality is the
  -- RELATIVE index `U.relIndex P_v`, which divides `U.index ≠ 0`.
  have hdvd : U.relIndex (wildInertiaGroup v) ∣ U.index :=
    Subgroup.relIndex_dvd_index_of_normal _ _
  have hidx : U.index ≠ 0 := Subgroup.index_ne_zero_of_finite
  have hcard : Nat.card (wildInertiaGroup v ⧸ U.subgroupOf (wildInertiaGroup v))
      = U.relIndex (wildInertiaGroup v) := rfl
  have hne : Nat.card (wildInertiaGroup v ⧸ U.subgroupOf (wildInertiaGroup v)) ≠ 0 := by
    rw [hcard]
    exact fun h => hidx (Nat.eq_zero_of_zero_dvd (h ▸ hdvd))
  haveI : Finite (wildInertiaGroup v ⧸ U.subgroupOf (wildInertiaGroup v)) :=
    Nat.finite_of_card_ne_zero hne
  -- STEP 3. a failure of coprimality produces a COMMON PRIME `q`.
  by_contra hcon
  obtain ⟨q, hq, hqcard, hqn⟩ := Nat.Prime.not_coprime_iff_dvd.mp hcon
  haveI : Fact q.Prime := ⟨hq⟩
  -- `q ∣ n` and `n ∉ v` force `q ∉ v`, i.e. `q ≠ ℓ`: this is where `hn` is used.
  have hqv : (q : 𝓞 K) ∉ v.asIdeal := by
    intro hmem
    refine hn ?_
    obtain ⟨m, rfl⟩ := hqn
    push_cast
    exact Ideal.mul_mem_right _ _ hmem
  -- STEP 4. CAUCHY gives an element of order exactly `q` in the finite quotient.
  obtain ⟨x, hx⟩ := exists_prime_orderOf_dvd_card'
    (G := wildInertiaGroup v ⧸ U.subgroupOf (wildInertiaGroup v)) q hqcard
  obtain ⟨σ, rfl⟩ := QuotientGroup.mk_surjective x
  have hpow : ((σ : Field.absoluteGaloisGroup (v.adicCompletion K))) ^ q ∈ U := by
    have h1 : (QuotientGroup.mk (σ ^ q) :
        wildInertiaGroup v ⧸ U.subgroupOf (wildInertiaGroup v)) = 1 := by
      rw [QuotientGroup.mk_pow, ← hx]
      exact pow_orderOf_eq_one _
    rw [QuotientGroup.eq_one_iff, Subgroup.mem_subgroupOf] at h1
    simpa using h1
  -- STEP 5. the pro-`ℓ` leaf says such an element is already in `U` — so its
  -- class is trivial, contradicting `orderOf … = q > 1`.
  have hmem : (σ : Field.absoluteGaloisGroup (v.adicCompletion K)) ∈ U :=
    mem_of_pow_prime_mem_of_mem_wildInertiaGroup v hq hqv U hU σ.2 hpow
  have htriv : (QuotientGroup.mk σ :
      wildInertiaGroup v ⧸ U.subgroupOf (wildInertiaGroup v)) = 1 := by
    rw [QuotientGroup.eq_one_iff, Subgroup.mem_subgroupOf]
    exact hmem
  rw [htriv, orderOf_one] at hx
  exact hq.one_lt.ne hx

/-- **The wild inertia is pro-`ℓ`: an `n`-th root exists INSIDE `P_v`
whenever `n` is prime to the residue characteristic** (PROVEN 2026-07-27
MODULO the single leaf `coprime_card_quotient_wildInertiaGroup` above;
hoisted here from `Fermat/FLT/Modularity/Interface.lean`, where it was
cut on the same day as one opaque leaf).

In a pro-`ℓ` group the `n`-th power map is a BIJECTION for every `n`
prime to `ℓ`: it is bijective on each finite continuous quotient — there
the order of any element divides an `ℓ`-power, so `n` is invertible
modulo it — and bijectivity passes to the inverse limit by compactness.
The hypothesis is spelled `(n : 𝓞 K) ∉ v.asIdeal`, which is exactly
`ℓ ∤ n` (and forces `n ≠ 0`, since `0 ∈ v.asIdeal`).

Note the conclusion places `θ` back in `P_v`, not merely in `I_v`: the
consumer iterates this lemma to extract a `pᵏ`-th root, and an
`I_v`-valued root would break the induction at the second step.

THE PROOF is the three-line assembly of the block above — the profinite
limit (`exists_pow_eq_of_forall_openNormal`) fed by the finite level
(`exists_pow_mem_of_coprime_card_quotient`), with the topological side
conditions supplied by `exists_openNormal_subset_of_mem_nhds_one` and
`isClosed_wildInertiaGroup`. `hn` is consumed exactly once, inside the
pro-`ℓ` leaf. -/
theorem exists_pow_eq_of_mem_wildInertiaGroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K))
    {n : ℕ} (hn : (n : 𝓞 K) ∉ v.asIdeal)
    {σ : Field.absoluteGaloisGroup (v.adicCompletion K)}
    (hσ : σ ∈ wildInertiaGroup v) :
    ∃ θ ∈ wildInertiaGroup v, θ ^ n = σ := by
  haveI : T2Space (Field.absoluteGaloisGroup (v.adicCompletion K)) := krullTopology_t2
  refine exists_pow_eq_of_forall_openNormal
    (exists_openNormal_subset_of_mem_nhds_one v) (isClosed_wildInertiaGroup v) ?_
  intro U hUn hUo
  haveI := hUn
  exact exists_pow_mem_of_coprime_card_quotient
    (coprime_card_quotient_wildInertiaGroup v hn U hUo) hσ

namespace GaloisRep

/-- **The inertia invariants of a Galois representation at a finite
place** `V^{I_v}`: the submodule of vectors fixed by every element of
`localInertiaGroup v` acting through the localization `ρ.toLocal v`.
This is the carrier of the TAME part of the Artin conductor exponent. -/
def inertiaInvariants (ρ : GaloisRep K A M) (v : HeightOneSpectrum (𝓞 K)) :
    Submodule A M where
  carrier := {x | ∀ σ ∈ localInertiaGroup v, ρ.toLocal v σ x = x}
  add_mem' {x y} hx hy := by
    intro σ hσ
    show ρ.toLocal v σ (x + y) = x + y
    rw [map_add, hx σ hσ, hy σ hσ]
  zero_mem' := by
    intro σ _
    show ρ.toLocal v σ 0 = 0
    rw [map_zero]
  smul_mem' c x hx := by
    intro σ hσ
    show ρ.toLocal v σ (c • x) = c • x
    rw [map_smul, hx σ hσ]

@[simp]
lemma mem_inertiaInvariants {ρ : GaloisRep K A M} {v : HeightOneSpectrum (𝓞 K)}
    {x : M} :
    x ∈ ρ.inertiaInvariants v ↔
      ∀ σ ∈ localInertiaGroup v, ρ.toLocal v σ x = x :=
  Iff.rfl

/-- **The tame part of the Artin conductor exponent** at `v`:
`dim V − dim V^{I_v}`, the codimension of the inertia invariants. For a
2-dimensional representation this is the `2 − dim V^{I_v}` of the
classical dictionary `a_v = (2 − dim V^{I_v}) + Sw_v`. -/
noncomputable def tameExponent (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) : ℕ :=
  Module.finrank A M - Module.finrank A (ρ.inertiaInvariants v)

/-- An unramified representation has all of `V` as inertia invariants. -/
lemma inertiaInvariants_eq_top_of_isUnramifiedAt (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) [ρ.IsUnramifiedAt v] :
    ρ.inertiaInvariants v = ⊤ := by
  refine eq_top_iff.mpr fun x _ => ?_
  intro σ hσ
  have h1 : (ρ.toLocal v) σ = 1 :=
    GaloisRep.IsUnramifiedAt.localInertiaGroup_le (ρ := ρ) hσ
  rw [h1]
  rfl

/-- **The tame part of the conductor exponent vanishes for an unramified
representation** — the tame half of "`a_v = 0` for `ρ` unramified at
`v`". -/
lemma tameExponent_eq_zero_of_isUnramifiedAt (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) [ρ.IsUnramifiedAt v] :
    ρ.tameExponent v = 0 := by
  have h : Module.finrank A (ρ.inertiaInvariants v) = Module.finrank A M := by
    rw [ρ.inertiaInvariants_eq_top_of_isUnramifiedAt v]
    exact Submodule.topEquiv.finrank_eq
  rw [tameExponent, h, Nat.sub_self]

/-- **A nonzero inertia-fixed vector lowers the tame exponent** — the
tame half of the at-`2` exponent bound `a_2 ≤ 1`: over a field, an
inertia-fixed `w₀ ≠ 0` makes `dim V^{I_v} ≥ 1`, hence
`tameExponent + 1 ≤ dim V`. -/
lemma tameExponent_add_one_le_finrank_of_fixed {k : Type*} [Field k]
    [TopologicalSpace k] {W : Type*} [AddCommGroup W]
    [Module k W] [FiniteDimensional k W] (ρ : GaloisRep K k W)
    (v : HeightOneSpectrum (𝓞 K)) {w₀ : W} (hw₀ : w₀ ≠ 0)
    (hfix : ∀ σ ∈ localInertiaGroup v, ρ.toLocal v σ w₀ = w₀) :
    ρ.tameExponent v + 1 ≤ Module.finrank k W := by
  have hmem : w₀ ∈ ρ.inertiaInvariants v := hfix
  have hne : (ρ.inertiaInvariants v) ≠ ⊥ := fun h => hw₀ (by
    rw [h] at hmem; exact hmem)
  have hpos : 1 ≤ Module.finrank k (ρ.inertiaInvariants v) :=
    Submodule.one_le_finrank_iff.mpr hne
  have hle : Module.finrank k (ρ.inertiaInvariants v) ≤ Module.finrank k W :=
    Submodule.finrank_le _
  have hW : 1 ≤ Module.finrank k W := hpos.trans hle
  have hsub : Module.finrank k W - Module.finrank k (ρ.inertiaInvariants v)
      ≤ Module.finrank k W - 1 := Nat.sub_le_sub_left hpos _
  rw [tameExponent]
  calc Module.finrank k W - Module.finrank k (ρ.inertiaInvariants v) + 1
      ≤ (Module.finrank k W - 1) + 1 := Nat.add_le_add_right hsub 1
    _ = Module.finrank k W := Nat.sub_add_cancel hW

/-- **The tame exponent never exceeds the dimension.** It is the
codimension of a submodule, so `dim V − dim V^{I_v} ≤ dim V` holds
unconditionally (indeed by `Nat` truncated subtraction alone).

This trivial bound is the arithmetic that decides how much content a
CITED conductor bound actually carries: since the tame part is all that
`HasConductorExponentAt ρ v a` constrains at a ramified place
(`hasConductorExponentAt_iff_tameExponent_le_of_not_isUnramifiedAt`), a
citation `a_v(V) = a` with `a ≥ dim V` contributes NOTHING beyond
ramifiedness. For the 2-dimensional representations of the
level-lowering assemblies that means: a cited conductor exponent `≥ 2`
is exactly the assertion "`ρ` is ramified at `v`", and only the
`a = 1` case carries tame information. -/
lemma tameExponent_le_finrank (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) :
    ρ.tameExponent v ≤ Module.finrank A M :=
  Nat.sub_le _ _

/-- **`ρ` is TAMELY RAMIFIED at `v`**: the WILD inertia `P_v` acts
trivially, i.e. `ρ` factors through the tame quotient `I_v / P_v` on
inertia.

This is the vanishing criterion for the Swan conductor (Serre, *Local
Fields* VI §2): `Sw_v(V)` is a sum over the wild ramification breaks of
`V`, so it vanishes **exactly** when `P_v` acts trivially. Stating it
needs the wild inertia group and nothing else — in particular it does
NOT need Herbrand's `ψ` or the ramification filtration in the upper
numbering, which is why this criterion is available on this pin while
the number `Sw_v(V)` itself is not.

It is spelled "fixes every vector" rather than "`ρ.toLocal v σ = 1`" to
keep it free of the module topology on `Module.End A M`, exactly as
`inertiaInvariants` is; the two are equivalent by `LinearMap.ext`. -/
def IsTamelyRamifiedAt (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) : Prop :=
  ∀ σ ∈ wildInertiaGroup v, ∀ x : M, ρ.toLocal v σ x = x

/-- **Unramified implies tamely ramified** — the whole inertia acts
trivially, so in particular the wild inertia does. -/
lemma isTamelyRamifiedAt_of_isUnramifiedAt (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) [ρ.IsUnramifiedAt v] :
    ρ.IsTamelyRamifiedAt v := by
  intro σ hσ x
  have h1 : (ρ.toLocal v) σ = 1 :=
    GaloisRep.IsUnramifiedAt.localInertiaGroup_le (ρ := ρ)
      (wildInertiaGroup_le_localInertiaGroup v hσ)
  rw [h1]
  rfl

/-- **The Swan conductor, as an UNINTERPRETED constant.**

`swanExponentAux ρ v` stands for `Sw_v(V)`, the wild part of the Artin
conductor exponent. It is declared `opaque`: the kernel will not unfold
it, so **nothing about its value is provable**, and — unlike an
`axiom` — it contributes nothing to `#print axioms` (the `:= 0` is only
the inhabitation witness Lean's `opaque` command requires; `= 0` is NOT
derivable from it).

This is deliberate, and it is the only honest option at this pin: the
Swan conductor needs the higher ramification filtration in the UPPER
numbering, which mathlib does not have and which the lower numbering
cannot substitute for over `Kᵥᵃˡᵍ` (divisible value group — see the
module docstring). Rather than pretend to define it, or existentially
quantify it away (which cost this development a FALSE leaf — again see
the module docstring), we name it and say nothing about it.

Do not state or prove any equation about `swanExponentAux` itself.
Facts about the Swan conductor belong on `swanExponent` below, and any
such fact that is not a theorem is a citation leaf whose soundness is
checked against the intended interpretation `swanExponentAux ρ v :=
Sw_v(V)`. -/
opaque swanExponentAux {K : Type uK} [Field K] [NumberField K]
    {A : Type*} [CommRing A] [TopologicalSpace A]
    {M : Type*} [AddCommGroup M] [Module A M]
    (ρ : GaloisRep K A M) (v : HeightOneSpectrum (𝓞 K)) : ℕ := 0

open scoped Classical in
/-- **The wild part of the Artin conductor exponent** at `v`, i.e. the
Swan conductor `Sw_v(V)`.

It is `swanExponentAux` — an opaque constant — with the ONE property
this development needs BUILT IN rather than assumed: **the Swan
conductor is supported on the wild inertia, so it vanishes exactly when
the wild inertia acts trivially**, i.e. when `ρ.IsTamelyRamifiedAt v`.

STRENGTHENED 2026-07-26. Until then the branch condition was
`ρ.IsUnramifiedAt v`, which made `swanExponent` opaque at every ramified
place and left `swanExponent_two_eq_zero_of_inertia_sq_eq_zero`
(`Fermat/FLT/Modularity/Interface.lean`) *unprovable as stated* rather
than merely unproven: its own soundness audit exhibits a curve of
conductor `14` at `p = 5` that is genuinely ramified at `2`, so no proof
could ever establish the branch condition. Widening the condition from
"inertia acts trivially" to "WILD inertia acts trivially" is exactly the
classical criterion, and it is what gives that leaf a route.

The move is conservative in the same sense the previous one was, and for
the same reason: the true Swan conductor DOES vanish on a tamely
ramified representation, so under the intended interpretation
`swanExponentAux ρ v := Sw_v(V)` one still has `swanExponent = Sw_v` **on
the nose**. Soundness needs the branch condition to be no WEAKER than
true tameness — i.e. `wildInertiaGroup` must not be smaller than the true
`P_v` — and it is equal to it; see `wildInertiaGroup`. -/
noncomputable def swanExponent (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) : ℕ :=
  if ρ.IsTamelyRamifiedAt v then 0 else ρ.swanExponentAux v

/-- **The Swan conductor vanishes on a tamely ramified representation** —
true by construction of `swanExponent`, see its docstring. This is the
form in which the at-`2` wild half is discharged. -/
lemma swanExponent_eq_zero_of_isTamelyRamifiedAt (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) (h : ρ.IsTamelyRamifiedAt v) :
    ρ.swanExponent v = 0 := by
  classical
  rw [swanExponent, if_pos h]

/-- **The Swan conductor vanishes at a place of unramifiedness** — the
special case of `swanExponent_eq_zero_of_isTamelyRamifiedAt` at which
the whole inertia, not merely the wild inertia, is trivial. -/
lemma swanExponent_eq_zero_of_isUnramifiedAt (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) [ρ.IsUnramifiedAt v] :
    ρ.swanExponent v = 0 :=
  swanExponent_eq_zero_of_isTamelyRamifiedAt ρ v
    (ρ.isTamelyRamifiedAt_of_isUnramifiedAt v)

/-- **The Artin conductor exponent at a finite place**, through the
classical dictionary (Serre, *Local Fields* VI §2)

  `a_v(V) = (dim V − dim V^{I_v}) + Sw_v(V)`:

the TAME part `ρ.tameExponent v`, computed here from the inertia
invariants, plus the WILD part `ρ.swanExponent v`, an opaque constant.

Because the wild summand is a FUNCTION of `(ρ, v)` rather than an
existentially quantified witness, this number is PINNED — which is what
lets consumers read UPPER bounds off it. See the module docstring for
why the previous existential packaging had to be withdrawn. -/
noncomputable def conductorExponent (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) : ℕ :=
  ρ.tameExponent v + ρ.swanExponent v

/-- **The Artin conductor exponent at a finite place**, as a relation
between the representation and a natural number: `a` IS the conductor
exponent `ρ.conductorExponent v`.

This is the shape in which the literature citations of
`Fermat/FLT/Modularity/Interface.lean` are stated — Carayol's
`ord_q(cond ρ) = ord_q M` reads
`ρ.HasConductorExponentAt v_q (M.factorization q)` — and it is an
EQUATION, not a weakening: a leaf stated with it asserts exactly the
cited identity, under the interpretation of `swanExponentAux` as the
Swan conductor. -/
def HasConductorExponentAt (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) (a : ℕ) : Prop :=
  a = ρ.conductorExponent v

/-- The defining equation, in usable form. -/
lemma HasConductorExponentAt.eq {ρ : GaloisRep K A M}
    {v : HeightOneSpectrum (𝓞 K)} {a : ℕ} (h : ρ.HasConductorExponentAt v a) :
    a = ρ.conductorExponent v := h

/-- The tame part is a lower bound for the conductor exponent (the Swan
conductor is nonnegative). -/
lemma HasConductorExponentAt.tameExponent_le {ρ : GaloisRep K A M}
    {v : HeightOneSpectrum (𝓞 K)} {a : ℕ} (h : ρ.HasConductorExponentAt v a) :
    ρ.tameExponent v ≤ a := by
  rw [h.eq, conductorExponent]
  omega

/-- **An upper bound on the conductor exponent transfers to any `a`
carrying it.** This is the direction the at-`2` level-lowering consumer
needs, and the direction the previous existential packaging could not
supply. -/
lemma HasConductorExponentAt.le_of_conductorExponent_le {ρ : GaloisRep K A M}
    {v : HeightOneSpectrum (𝓞 K)} {a n : ℕ} (h : ρ.HasConductorExponentAt v a)
    (hn : ρ.conductorExponent v ≤ n) : a ≤ n := by
  rw [h.eq]; exact hn

/-- **The conductor exponent vanishes at a place of unramifiedness** —
the full `a_v = 0` statement, tame part by
`tameExponent_eq_zero_of_isUnramifiedAt` and wild part by
`swanExponent_eq_zero_of_isUnramifiedAt`. This is the shape in which the
away-from-`p` per-place citation consumes the shared conductor leaf. -/
lemma HasConductorExponentAt.eq_zero_of_isUnramifiedAt {ρ : GaloisRep K A M}
    {v : HeightOneSpectrum (𝓞 K)} {a : ℕ} (h : ρ.HasConductorExponentAt v a)
    [ρ.IsUnramifiedAt v] : a = 0 := by
  rw [h.eq, conductorExponent, ρ.tameExponent_eq_zero_of_isUnramifiedAt v,
    ρ.swanExponent_eq_zero_of_isUnramifiedAt v]

/-- **A positive conductor exponent forces ramification** — the
contrapositive of `HasConductorExponentAt.eq_zero_of_isUnramifiedAt`,
in the form the level-lowering assemblies consume it: if some conductor
exponent of `ρ` at `v` is nonzero then `ρ` is ramified at `v`. -/
lemma HasConductorExponentAt.not_isUnramifiedAt_of_ne_zero
    {ρ : GaloisRep K A M} {v : HeightOneSpectrum (𝓞 K)} {a : ℕ}
    (h : ρ.HasConductorExponentAt v a) (ha : a ≠ 0) :
    ¬ ρ.IsUnramifiedAt v := by
  intro hun
  haveI : ρ.IsUnramifiedAt v := hun
  exact ha h.eq_zero_of_isUnramifiedAt

/-! ### WITHDRAWN 2026-07-26: the four lemmas about the EXISTENTIAL packaging

Until 2026-07-26 `HasConductorExponentAt` was the existential weakening
`∃ s, a = tameExponent + s ∧ (IsUnramifiedAt → s = 0)`, and this file
carried four lemmas exploiting it:
`hasConductorExponentAt_iff_tameExponent_le_of_not_isUnramifiedAt`,
`hasConductorExponentAt_of_finrank_le_of_not_isUnramifiedAt`,
`hasConductorExponentAt_of_fixed_of_not_isUnramifiedAt` and
`HasConductorExponentAt.mono_of_not_isUnramifiedAt`.

All four are FALSE under the pinned definition above, and that is the
point of the pin. The weakening is UPWARD CLOSED in `a` at a ramified
place, so those lemmas let a Carayol-type conductor identity be
"proved" from ramifiedness alone — which is what
`hasConductorExponentAt_two_le_one_of_inertia_sq_eq_zero` was refuted
for (counterexample: `E/ℚ` of conductor `14` at `p = 5`; inertia at `2`
acts through the Tate parametrisation by square-zero unipotents, `τ` is
ramified at `2` since `5 ∤ v₂(q_E) = 6`, so the weak relation holds at
`a = 2` while the asserted `2 ≤ 1` fails).

An existentially weakened invariant carries LOWER-bound content only.
Do not reintroduce these lemmas; upper bounds now transfer through
`HasConductorExponentAt.le_of_conductorExponent_le`. -/

end GaloisRep
