/-
Modularity/ArtinConductor.lean — own work for the Fermat project (not
vendored from the FLT project).
-/
module

public import Fermat.FLT.Deformations.RepresentationTheory.GaloisRep

/-!
# The Artin conductor exponent of a Galois representation

This module builds the local invariant that the three per-place
"level-lowering" citations of `Fermat/FLT/Modularity/Interface.lean` were
all spelling by hand, each in its own local dialect: the **Artin
conductor exponent** `a_v(V)` of a Galois representation at a finite
place `v`, through the classical dictionary (Serre, *Local Fields*,
VI §2)

  `a_v(V) = (dim V − dim V^{I_v}) + Sw_v(V)`,

the *tame* part read off the inertia invariants and the *wild* part the
Swan conductor.

## What is proven here and what is postponed

The **tame** part is built outright: `GaloisRep.inertiaInvariants` is the
honest `I_v`-fixed submodule (`localInertiaGroup v` acting through
`ρ.toLocal v`), and `GaloisRep.tameExponent` is its codimension, with the
two facts the consumers need proven — it vanishes for an unramified
representation (`GaloisRep.tameExponent_eq_zero_of_isUnramifiedAt`) and
it drops by at least one as soon as inertia fixes a nonzero vector
(`GaloisRep.tameExponent_add_one_le_finrank_of_fixed`).

The **wild** part is not a *number* on this pin, but since 2026-07-26 it
is no longer wholly opaque either: its **vanishing criterion** is now
definable and is built in. See "## The wild part" below for what changed;
the two bullets immediately following are the (still accurate) reason the
NUMBER `Sw_v(V)` is unavailable:

* mathlib has the decomposition and inertia subgroups of a valuation
  subring (`ValuationSubring.decompositionSubgroup`,
  `ValuationSubring.inertiaSubgroup`, i.e. `G_{-1}` and `G_0`) and an
  explicit `TODO: Define higher ramification groups in lower numbering`
  in `Mathlib/RingTheory/Valuation/RamificationGroup.lean`. There is no
  `Swan`, no `ramificationGroup`, no Artin conductor anywhere in the
  library (the `conductor`s it does have are the ring-theoretic
  conductor of a ring extension and the conductor of a Dirichlet
  character — unrelated invariants).
* the naive repair is unavailable *in principle*: over `Kᵥᵃˡᵍ` the
  lower numbering collapses. The value group of the integral closure of
  `𝒪ᵥ` in `Kᵥᵃˡᵍ` is divisible, so `𝔪 ^ (i + 1) = 𝔪` and every
  `AddSubgroup.inertia (𝔪 ^ (i+1))` equals `localInertiaGroup v`
  itself. The Swan conductor genuinely needs the *upper* numbering,
  i.e. Herbrand's function `ψ` and the finite-level ramification
  filtration — a development of its own.

## The wild part: an opaque NUMBER with a DEFINED vanishing criterion

Both bullets above are about the *number* `Sw_v(V)`, and both still
stand. What they do **not** obstruct is the *criterion* for that number
to be zero, and that is all this development actually consumes:

  `Sw_v(V) = 0  ⟺  the wild inertia P_v acts trivially on V`

(Serre, *Local Fields* VI §2 — the Swan conductor is a sum over the wild
ramification breaks). The wild inertia `P_v = Gal(Kᵥᵃˡᵍ / Kᵥᵗᵃᵐᵉ)` is
definable WITHOUT the ramification filtration, because the maximal tame
extension is generated by the elements `x` with `xⁿ ∈ 𝒪ᵥ` for `n` prime
to the residue characteristic. That is `wildInertiaGroup` below, and the
criterion is `GaloisRep.IsTamelyRamifiedAt`.

Why this matters, concretely: the branch condition of `swanExponent` used
to be `IsUnramifiedAt`, and with that condition the at-`2` wild leaf
`swanExponent_two_eq_zero_of_inertia_sq_eq_zero`
(`Fermat/FLT/Modularity/Interface.lean`) was **unprovable as stated** —
any proof would have had to establish unramifiedness at `2`, which that
leaf's own soundness audit refutes with a conductor-`14` curve at
`p = 5`. With the tame criterion it becomes provable, and reduces to the
single honest local statement that a square-zero-unipotent inertia
action in residue characteristic `≠ p` is trivial on wild inertia.

So the wild part enters as an **uninterpreted constant**
`GaloisRep.swanExponentAux`, declared with Lean's `opaque` command,
guarded by that criterion, and the conductor exponent is the honest sum

  `GaloisRep.conductorExponent ρ v = ρ.tameExponent v + ρ.swanExponent v`,

with `HasConductorExponentAt ρ v a` the *equation* `a = conductorExponent ρ v`.

`opaque` introduces **no axiom and no `sorry`** (`#print axioms` on
anything using it stays empty) and the kernel will not unfold it, so
nothing about its value is provable — which is exactly the intent: the
symbol *denotes* the Swan conductor without computing it. The one
property of the Swan conductor that this development actually needs,
vanishing on a TAMELY RAMIFIED representation, is built into
`swanExponent` by construction (`swanExponent ρ v =
if ρ.IsTamelyRamifiedAt v then 0 else swanExponentAux ρ v`), so both
`GaloisRep.swanExponent_eq_zero_of_isTamelyRamifiedAt` and its
specialization `GaloisRep.swanExponent_eq_zero_of_isUnramifiedAt` are
*theorems* rather than further leaves.

Soundness of this packaging is model-theoretic and is the standard one
for axiomatising an invariant that cannot yet be defined: interpret
`swanExponentAux ρ v` as the true Swan conductor `Sw_v(V)`. Under that
interpretation `conductorExponent ρ v` **is** `a_v(V)`, so every leaf
stated with `HasConductorExponentAt` is precisely the corresponding
statement of the literature — no weaker and no stronger.

## HISTORY: why the previous, existential packaging was WITHDRAWN

Until 2026-07-25 this file packaged the wild summand *existentially*,

  `HasConductorExponentAt ρ v a  :=  ∃ s, a = tameExponent + s ∧
                                     (ρ.IsUnramifiedAt v → s = 0)`,

on the argument that every such statement is *implied* by the true
identity `a_v(V) = a`, hence can never be false.

**That argument is valid only in CONCLUSION position.** The predicate is
UPWARD CLOSED in `a` for a representation that is ramified at `v` (take
`s := a − tameExponent`; the only clause constraining `s` is conditioned
on unramifiedness and is then vacuous). So in HYPOTHESIS position the
weakening *strengthens* the statement, and a leaf consuming
`HasConductorExponentAt ρ v a` in order to derive an UPPER bound on `a`
is thereby asserting `ρ` is unramified at `v`. Exactly one leaf did
this — `hasConductorExponentAt_two_le_one_of_inertia_sq_eq_zero` in
`Fermat/FLT/Modularity/Interface.lean` — and it was consequently FALSE
AS STATED, refuted by the curve `E/ℚ` of conductor `14` at `p = 5` (see
that leaf's docstring for the counterexample in full).

The generalizable rule: an existentially weakened invariant can carry
LOWER-bound content (`a ≠ 0 → ρ` ramified) but never UPPER-bound
content. Pinning `a` to a single opaque value, as is now done, restores
both directions at the cost of an uninterpreted symbol — which is the
right trade, since the alternative is a definition under which half the
intended consumers are unstatable.

## Consumers

`Fermat/FLT/Modularity/Interface.lean` states ONE shared Carayol leaf
`hasConductorExponentAt_factorization_of_isNewAtPrime` in these terms
and derives from it the per-place citations that previously each carried
their own copy of Carayol's theorem.
-/

@[expose] public section

open NumberField IsDedekindDomain

universe uK

variable {K : Type uK} [Field K] [NumberField K]
variable {A : Type*} [CommRing A] [TopologicalSpace A]
variable {M : Type*} [AddCommGroup M] [Module A M]

/-- **The subgroup of the local absolute Galois group fixing every
TAMELY RAMIFIED element**.

Concretely: `σ` lies here when it fixes every `x` of the integral
closure of `𝒪ᵥ` in `Kᵥᵃˡᵍ` some `n`-th power of which already lies in
`𝒪ᵥ`, for `n` prime to the residue characteristic (spelled
`(n : 𝓞 K) ∉ v.asIdeal`, which also forces `n ≠ 0` since `0 ∈ v.asIdeal`).

**Why this is exactly `Gal(Kᵥᵃˡᵍ / Kᵥᵗᵃᵐᵉ)`.** The maximal tamely
ramified extension of a local field `Kᵥ` with residue characteristic `ℓ`
is `Kᵥᵗᵃᵐᵉ = Kᵥⁿʳ(π^{1/n} : ℓ ∤ n)` and `Kᵥⁿʳ = Kᵥ(ζₙ : ℓ ∤ n)`, so it
is generated over `Kᵥ` by elements `x` with `xⁿ ∈ 𝒪ᵥ` and `ℓ ∤ n`
(the `ζₙ` satisfy `ζₙⁿ = 1`, the `π^{1/n}` satisfy `(π^{1/n})ⁿ = π`, and
both are integral). Conversely each such `x` generates a tame extension:
`Kᵥ(x) ⊆ Kᵥ(ζₙ, a^{1/n})` with `ℓ ∤ n`, which is unramified-then-Kummer
of degree prime to `ℓ`. An automorphism fixing `Kᵥ` pointwise and fixing
every such generator therefore fixes all of `Kᵥᵗᵃᵐᵉ` pointwise, and
conversely. Hence this subgroup **is** the wild inertia group.

The point of phrasing it through the *generators* rather than through
the extension is that no theory of the maximal tame extension is needed
to write it down — and that the action used is the very one
`localInertiaGroup` is already built from, so nothing new has to be
instantiated. -/
def tameFixingSubgroup (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K)) :
    Subgroup (Field.absoluteGaloisGroup (v.adicCompletion K)) where
  carrier := {σ | ∀ n : ℕ, (n : 𝓞 K) ∉ v.asIdeal →
    ∀ x : IntegralClosure
        (IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers K v)
        (AlgebraicClosure (v.adicCompletion K)),
      (∃ a : IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers K v,
        x ^ n = algebraMap _ _ a) → σ • x = x}
  mul_mem' {a b} ha hb := by
    intro n hn x hx
    rw [mul_smul, hb n hn x hx, ha n hn x hx]
  one_mem' := by
    intro n _ x _
    rw [one_smul]
  inv_mem' {a} ha := by
    intro n hn x hx
    calc a⁻¹ • x = a⁻¹ • (a • x) := by rw [ha n hn x hx]
      _ = x := by rw [← mul_smul, inv_mul_cancel, one_smul]

/-- **The WILD INERTIA group at a finite place `v`**: the inertia
elements that act trivially on the maximal tamely ramified extension,
i.e. `P_v = Gal(Kᵥᵃˡᵍ / Kᵥᵗᵃᵐᵉ)`, the (unique) Sylow pro-`ℓ` subgroup of
`I_v` for `ℓ` the residue characteristic of `v`.

It is written as `localInertiaGroup v ⊓ tameFixingSubgroup v`. The
intersection changes nothing mathematically — `tameFixingSubgroup v` is
already contained in the inertia, since `Kᵥⁿʳ ⊆ Kᵥᵗᵃᵐᵉ` — but it makes
`wildInertiaGroup_le_localInertiaGroup` free, which is the only
containment this development consumes, and it removes any risk of the
group being accidentally LARGER than the true `P_v` (which is the
direction that would matter for soundness of `swanExponent` below).

This is what makes the Swan conductor's vanishing criterion statable
here without the higher ramification filtration in the upper numbering:
`Sw_v(V) = 0` **iff** `P_v` acts trivially (Serre, *Local Fields* VI §2 —
the Swan conductor is supported on the wild ramification breaks), and
that criterion is what `GaloisRep.IsTamelyRamifiedAt` below records. -/
noncomputable def wildInertiaGroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K)) :
    Subgroup (Field.absoluteGaloisGroup (v.adicCompletion K)) :=
  localInertiaGroup v ⊓ tameFixingSubgroup v

/-- The wild inertia is contained in the inertia — true by construction
of `wildInertiaGroup` as a meet. -/
lemma wildInertiaGroup_le_localInertiaGroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K)) :
    wildInertiaGroup v ≤ localInertiaGroup v := inf_le_left

/-!
### The tame quotient is PROCYCLIC

Two declarations, cut 2026-07-27 out of
`exists_localInertia_generator_of_wildInertia_trivial` in
`Fermat/FLT/GaloisRepresentation/HardlyRamified/Threeadic.lean` and
hoisted here, beside `wildInertiaGroup` itself, because they are pure
local Galois theory stated generically in `K` and `v`:

* `exists_localInertia_generator_mod_pow_wildInertiaGroup` — **the one
  open leaf**: modulo `n`-th powers and wild inertia, `I_v` is generated
  by a single element (`Q / Qⁿ` is cyclic, `Q := I_v / P_v`);
* `exists_localInertia_pow_eq_of_wildInertiaGroup_le_ker` — PROVEN over
  it: every finite ABSTRACT quotient of `I_v` that kills `P_v` is
  cyclic, generated by the image of one inertia element with
  non-negative exponents.

The second is the form consumers want, and it carries NO continuity
hypothesis; see its docstring for why none is needed.
-/

/-- **THE TAME QUOTIENT IS PROCYCLIC, in the form an abstract finite
quotient needs it: modulo `n`-th powers and wild inertia, local inertia
is generated by ONE element** (SORRY LEAF, cut 2026-07-27 out of
`exists_localInertia_pow_eq_of_wildInertiaGroup_le_ker` just below,
which is PROVEN over it, and through that out of
`exists_localInertia_generator_of_wildInertia_trivial` in
`Fermat/FLT/GaloisRepresentation/HardlyRamified/Threeadic.lean`).

Content: for every `n ≠ 0` there is a SINGLE `σ ∈ I_v` such that every
`τ ∈ I_v` factors as `σ ^ k · ρ ^ n · w` with `ρ ∈ I_v` and `w ∈ P_v`.
Writing `Q := I_v / P_v` for the tame quotient, this says exactly that
`Q / Qⁿ` is CYCLIC, generated by the class of `σ`. It is the whole
arithmetic content of "the tame quotient is procyclic": the corollary
below turns it into "every finite quotient of `I_v` killing `P_v` is
cyclic" by pure group theory.

WHY THIS SHAPE — and in particular why NO continuity hypothesis. `Q`
itself is not cyclic: it is `∏_{ℓ' ≠ ℓ} ℤ_{ℓ'}` (`ℓ` the residue
characteristic), and `1 ∈ ẑ` does not generate `ẑ` as an abstract group.
So procyclicity can only be stated at the finite layers, which is what
the `n` here is. And no continuity is needed anywhere, deliberately:
every ABSTRACT finite quotient `H` of `∏_ℓ ℤ_ℓ` is already cyclic,
because `H` is abelian and killed by `n := |H|`, so the surjection
factors through `(∏_ℓ ℤ_ℓ) / n · (∏_ℓ ℤ_ℓ) = ∏_ℓ (ℤ_ℓ / n ℤ_ℓ) ≅ ℤ/n'`
with `n'` the prime-to-`ℓ` part of `n` — multiplication by `n` on a
product being coordinatewise, and `ℤ_{ℓ'}` uniquely `q`-divisible for
`q ≠ ℓ'`. A consumer therefore never has to produce a CONTINUOUS
homomorphism, which matters because the actions that consume this (on
the geometric points of a finite flat group scheme, say) arrive as bare
families of maps with no topology in sight.

MATHEMATICAL CONTENT AND ROUTE FOR A PROVER.
`Q ≅ lim_{(m, ℓ) = 1} μ_m(k̄_v) ≅ ∏_{ℓ' ≠ ℓ} ℤ_{ℓ'}` (Serre, *Corps
Locaux* IV §2; Neukirch, *Algebraic Number Theory* II.7.11). Modulo `n`:

* it is enough to treat `n` PRIME TO `ℓ`, because `Q` is uniquely
  `ℓ`-divisible — the `ℓ`-part of the ramification is exactly what `P_v`
  absorbs — so `Qⁿ = Q^{n'}` for `n'` the prime-to-`ℓ` part of `n`;
* for `n` prime to `ℓ` the TAME CHARACTER
  `θ_n : I_v → μ_n(Kᵥᵃˡᵍ)`, `θ_n(τ) = τ(π^{1/n}) / π^{1/n}`, is a
  homomorphism (inertia fixes `μ_n` pointwise, `n` being prime to the
  residue characteristic, so the usual cocycle collapses), it is
  surjective, and its kernel is exactly `P_v · I_vⁿ`. Any `σ` with
  `θ_n(σ)` a generator of `μ_n` then works.

The one genuinely missing input is that kernel computation —
equivalently, that a finite tamely ramified extension of `Kᵥⁿʳ` is
`Kᵥⁿʳ(π^{1/e})` (Serre IV §2 Prop. 8; Neukirch II.7.7) — and it has to
be proved against THIS file's `tameFixingSubgroup`, which is spelled
through GENERATORS precisely so that no theory of `Kᵥᵗᵃᵐᵉ` is
presupposed.

VERIFIED ABSENT 2026-07-27, with the check that would refute it:
`grep -rn "tame\|Tame" ~/cs/FLT/FLT` returns only
`localTameAbelianInertiaGroup` in its `AbsoluteGaloisGroup.lean` — a
definition whose own docstring calls it "somewhat cheating" and carries
`TODO: show that this is indeed the right group` — plus unrelated `PGL₂`
material; and mathlib's `RamificationGroup.lean` defines only
`decompositionSubgroup` and `inertiaSubgroup`. So neither has tame/wild
quotient machinery to vendor.

FAITHFULNESS.

* `hn : n ≠ 0` is ESSENTIAL and the `n = 0` case is not merely unproven
  but FALSE: there the conclusion reads `τ = σ ^ k * 1 * w`, i.e. `Q` is
  generated by ONE element using NON-NEGATIVE exponents only, whereas
  `Q ≅ ∏_{ℓ'} ℤ_{ℓ'}` is uncountable and not even finitely generated.
  Do not drop the hypothesis.
* It is not vacuous: `σ = 1` would force `Q` to be `n`-divisible, false
  for `n` prime to `ℓ` since `Q / Qⁿ ≅ ℤ/n ≠ 1`. So no junk witness
  discharges it.
* The quantifiers range over `localInertiaGroup v` only, never over
  `Γ Kᵥ`. Widening them would make the statement FALSE: the
  decomposition group is an extension of the (also procyclic)
  unramified quotient by `Q`, and such an extension need not be
  procyclic. -/
theorem exists_localInertia_generator_mod_pow_wildInertiaGroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K)) {n : ℕ} (hn : n ≠ 0) :
    ∃ σ : localInertiaGroup v, ∀ τ : localInertiaGroup v,
      ∃ (k : ℕ) (ρ w : localInertiaGroup v),
        (w : Field.absoluteGaloisGroup (v.adicCompletion K)) ∈ wildInertiaGroup v ∧
          τ = σ ^ k * ρ ^ n * w :=
  sorry

/-- **EVERY FINITE QUOTIENT OF LOCAL INERTIA THAT KILLS WILD INERTIA IS
CYCLIC** (PROVEN 2026-07-27 over the single leaf
`exists_localInertia_generator_mod_pow_wildInertiaGroup` above).

Given any group homomorphism `f : I_v →* H` onto a FINITE group `H`
which kills `P_v`, there is one `σ ∈ I_v` whose image generates `H`,
and with NON-NEGATIVE exponents: every `h : H` is `f σ ^ k` for some
`k : ℕ`. That last point is what consumers need — an element of a finite
cyclic group is a non-negative power of a generator — and it saves each
of them the `zpowers`-to-`powers` conversion.

NO CONTINUITY IS REQUIRED of `f`, and none can be, since `H` carries no
topology here. See the leaf's docstring: an abstract finite quotient of
`∏_ℓ ℤ_ℓ` is already cyclic, so procyclicity of the tame quotient is a
purely algebraic input.

THE PROOF is three lines of group theory. Take `n := Nat.card H`, which
is nonzero because `H` is finite and nonempty, and let `σ` be the
element the leaf provides for that `n`. For `h = f τ` write
`τ = σ ^ k · ρ ^ n · w`; then `f w = 1` because `w` is wild, and
`f ρ ^ Nat.card H = 1` by `pow_card_eq_one'` (Lagrange), so
`h = f σ ^ k`.

`Finite H` is used exactly twice — for `Nat.card H ≠ 0` and for
Lagrange — and both uses are essential: for an infinite `H` the
statement is false, since it would make `I_v / P_v` a quotient of `ℕ`.

This is the general-purpose form of "the tame quotient is procyclic".
Its first consumer is
`exists_localInertia_generator_of_wildInertia_trivial` in
`Fermat/FLT/GaloisRepresentation/HardlyRamified/Threeadic.lean`, which
applies it to the image of `I_v` in `Equiv.Perm X` for a finite `X`. -/
theorem exists_localInertia_pow_eq_of_wildInertiaGroup_le_ker
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K))
    {H : Type*} [Group H] [Finite H]
    (f : localInertiaGroup v →* H) (hf : Function.Surjective f)
    (hwild : ∀ π : localInertiaGroup v,
      (π : Field.absoluteGaloisGroup (v.adicCompletion K)) ∈ wildInertiaGroup v → f π = 1) :
    ∃ σ : localInertiaGroup v, ∀ h : H, ∃ k : ℕ, f σ ^ k = h := by
  obtain ⟨σ, hσ⟩ := exists_localInertia_generator_mod_pow_wildInertiaGroup v
    (n := Nat.card H) Nat.card_pos.ne'
  refine ⟨σ, fun h ↦ ?_⟩
  obtain ⟨τ, rfl⟩ := hf h
  obtain ⟨k, ρ, w, hw, hτ⟩ := hσ τ
  refine ⟨k, ?_⟩
  rw [hτ, map_mul, map_mul, map_pow, map_pow, hwild w hw, pow_card_eq_one', mul_one, mul_one]

/-!
### `n`-th roots in the wild inertia, for `n` prime to the residue characteristic

`P_v` is pro-`ℓ`, so for `n` prime to `ℓ` the `n`-th power map is a
bijection on it. The consumer
(`isTamelyRamifiedAt_two_of_inertia_sq_eq_zero` in
`Fermat/FLT/Modularity/Interface.lean`) iterates this to extract `pᵏ`-th
roots INSIDE `P_v`, which is what turns `N σ = τσ − 1` into an
infinitely `p`-divisible value.

This block was cut out of that consumer's file on 2026-07-27 and hoisted
here, beside `wildInertiaGroup` itself, where it belongs. The
decomposition below splits the statement along exactly the seam its
original docstring predicted — a PURELY PROFINITE half and a PURELY
ARITHMETIC half — and **only the arithmetic half is still open**:

* `exists_pow_eq_of_forall_openNormal` — the profinite half, PROVEN, and
  stated for an abstract compact `T1` topological group so it is
  reusable. Roots that exist modulo every open normal subgroup exist on
  the nose, by Cantor's intersection theorem.
* `exists_pow_mem_of_coprime_card_quotient` — the finite-level step,
  PROVEN, pure group theory: `Nat.Coprime.pow_left_bijective`.
* `exists_openNormal_subset_of_mem_nhds_one`,
  `isClosed_wildInertiaGroup` — the topological inputs the profinite
  half needs at `Γ Kᵥ`, both PROVEN.
* `coprime_card_quotient_wildInertiaGroup` — PROVEN 2026-07-27, from the
  leaf below: the reduction of "coprime to `n` for every open normal `U`"
  to a single prime and a single element, via finiteness of the quotient
  (compactness of `Γ Kᵥ` plus the second isomorphism theorem) and
  Cauchy's theorem.
* `mem_of_pow_prime_mem_of_mem_wildInertiaGroup` — **the one open leaf**,
  and the only piece of this block carrying any arithmetic: `P_v` is
  pro-`ℓ`, in the element-level form "`σ ∈ P_v` and `σ ^ q ∈ U` force
  `σ ∈ U`, for `q` prime to the residue characteristic". This is genuine
  local field theory; its docstring records the KUMMER-THEORETIC route
  (`Kᵥᵗᵃᵐᵉ` contains `μ_q` and has `q`-divisible multiplicative group, so
  it admits no cyclic degree-`q` extension), which is the route that
  AVOIDS Ostrowski's defect theorem.
-/

open scoped Topology in
/-- **Roots that exist modulo every open normal subgroup exist on the
nose** (PROVEN 2026-07-27) — the profinite half of "the `n`-th power map
is surjective on a pro-`ℓ` group", carrying NO arithmetic whatsoever.

Stated for an abstract compact `T1` topological group `G` and a CLOSED
subgroup `P`, so that it is reusable at any profinite group: the only
inputs are that open normal subgroups are a neighbourhood basis of `1`
(`hbasis`) and that `n`-th roots exist in `P` modulo each of them
(`hlevel`).

THE PROOF is Cantor's intersection theorem. The sets
`t U := P ∩ (θ ↦ σ⁻¹θⁿ)⁻¹(U)`, indexed by the open normal subgroups, are
closed (an open subgroup is closed, and `θ ↦ σ⁻¹θⁿ` is continuous),
nonempty by `hlevel`, and DIRECTED downwards because `U ⊓ V` is again
open and normal. In a compact space their intersection is therefore
nonempty; any `θ` in it satisfies `σ⁻¹θⁿ ∈ U` for EVERY open normal `U`,
and `T1` plus `hbasis` forces `σ⁻¹θⁿ = 1` — if it were some `g ≠ 1`
then `{g}ᶜ` is a neighbourhood of `1`, so some open normal `U` avoids
`g`, contradiction.

Note `σ ∈ P` is NOT a hypothesis: it follows from the conclusion, and
`hlevel` already places the approximating roots in `P`. -/
theorem exists_pow_eq_of_forall_openNormal
    {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T1Space G]
    (hbasis : ∀ s ∈ 𝓝 (1 : G), ∃ U : Subgroup G, U.Normal ∧ IsOpen (U : Set G) ∧
      (U : Set G) ⊆ s)
    {P : Subgroup G} (hP : IsClosed (P : Set G)) {n : ℕ} {σ : G}
    (hlevel : ∀ U : Subgroup G, U.Normal → IsOpen (U : Set G) →
      ∃ θ ∈ P, σ⁻¹ * θ ^ n ∈ U) :
    ∃ θ ∈ P, θ ^ n = σ := by
  classical
  have hcont : Continuous fun θ : G => σ⁻¹ * θ ^ n := (continuous_pow n).const_mul _
  set t : {U : Subgroup G // U.Normal ∧ IsOpen (U : Set G)} → Set G :=
    fun U => (P : Set G) ∩ (fun θ : G => σ⁻¹ * θ ^ n) ⁻¹' (U.1 : Set G) with ht
  have hne : Nonempty {U : Subgroup G // U.Normal ∧ IsOpen (U : Set G)} :=
    ⟨⟨⊤, inferInstance, by simp⟩⟩
  have hclosed : ∀ U, IsClosed (t U) := by
    intro U
    exact hP.inter ((Subgroup.isClosed_of_isOpen _ U.2.2).preimage hcont)
  have hdir : Directed (· ⊇ ·) t := by
    rintro ⟨U, hUn, hUo⟩ ⟨V, hVn, hVo⟩
    refine ⟨⟨U ⊓ V, ?_, ?_⟩, ?_, ?_⟩
    · exact ⟨fun a ha g => ⟨hUn.conj_mem a ha.1 g, hVn.conj_mem a ha.2 g⟩⟩
    · simpa [Subgroup.coe_inf] using hUo.inter hVo
    · exact Set.inter_subset_inter_right _
        (Set.preimage_mono (by simp [Subgroup.coe_inf]))
    · exact Set.inter_subset_inter_right _
        (Set.preimage_mono (by simp [Subgroup.coe_inf]))
  have hnonempty : ∀ U, (t U).Nonempty := by
    rintro ⟨U, hUn, hUo⟩
    obtain ⟨θ, hθP, hθU⟩ := hlevel U hUn hUo
    exact ⟨θ, hθP, hθU⟩
  obtain ⟨θ, hθ⟩ := IsCompact.nonempty_iInter_of_directed_nonempty_isCompact_isClosed
    t hdir hnonempty (fun U => (hclosed U).isCompact) hclosed
  simp only [Set.mem_iInter, ht, Set.mem_inter_iff, Set.mem_preimage] at hθ
  refine ⟨θ, (hθ ⟨⊤, inferInstance, by simp⟩).1, ?_⟩
  have hone : σ⁻¹ * θ ^ n = 1 := by
    by_contra hg
    have hmem : ({σ⁻¹ * θ ^ n}ᶜ : Set G) ∈ 𝓝 (1 : G) :=
      (isOpen_compl_singleton).mem_nhds (by simpa [eq_comm] using hg)
    obtain ⟨U, hUn, hUo, hUs⟩ := hbasis _ hmem
    exact hUs (hθ ⟨U, hUn, hUo⟩).2 rfl
  rw [← mul_left_cancel_iff (a := σ⁻¹), hone, inv_mul_cancel]

/-- **The finite level: a quotient of order coprime to `n` has `n`-th
roots** (PROVEN 2026-07-27). Pure group theory —
`Nat.Coprime.pow_left_bijective` says `x ↦ xⁿ` is a bijection of a group
whose `Nat.card` is coprime to `n`, and no finiteness hypothesis is
needed because `pow_card_eq_one'` holds vacuously when `Nat.card = 0`.

This is the step that CONSUMES the pro-`ℓ` input: with
`P ⧸ (U ∩ P)` an `ℓ`-group and `ℓ ∤ n`, the hypothesis `hcop` holds. -/
theorem exists_pow_mem_of_coprime_card_quotient
    {G : Type*} [Group G] {P U : Subgroup G} [hU : U.Normal] {n : ℕ}
    (hcop : Nat.Coprime (Nat.card (P ⧸ U.subgroupOf P)) n)
    {σ : G} (hσ : σ ∈ P) :
    ∃ θ ∈ P, σ⁻¹ * θ ^ n ∈ U := by
  haveI : (U.subgroupOf P).Normal := hU.subgroupOf P
  obtain ⟨q, hq⟩ := hcop.pow_left_bijective.surjective
    (QuotientGroup.mk (⟨σ, hσ⟩ : P))
  obtain ⟨θ', rfl⟩ := QuotientGroup.mk_surjective q
  refine ⟨(θ' : G), θ'.2, ?_⟩
  have hq' : (QuotientGroup.mk (θ' ^ n) : P ⧸ U.subgroupOf P) =
      QuotientGroup.mk (⟨σ, hσ⟩ : P) := by
    simpa [QuotientGroup.mk_pow] using hq
  rw [eq_comm, QuotientGroup.eq, Subgroup.mem_subgroupOf] at hq'
  simpa using hq'

open scoped Topology in
/-- **Open NORMAL subgroups are a neighbourhood basis of `1` in `Γ Kᵥ`**
(PROVEN 2026-07-27). Mathlib's `krullTopology_mem_nhds_one_iff_of_normal`
supplies a finite NORMAL intermediate field `E` with
`E.fixingSubgroup ⊆ s`; `Kᵥ` has characteristic zero, so `E/Kᵥ` is
automatically separable and hence Galois, and
`IsGalois.fixingSubgroup_normal_of_isGalois` then makes that fixing
subgroup normal. Openness is `IntermediateField.fixingSubgroup_isOpen`. -/
theorem exists_openNormal_subset_of_mem_nhds_one
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K))
    (s : Set (Field.absoluteGaloisGroup (v.adicCompletion K)))
    (hs : s ∈ 𝓝 (1 : Field.absoluteGaloisGroup (v.adicCompletion K))) :
    ∃ U : Subgroup (Field.absoluteGaloisGroup (v.adicCompletion K)), U.Normal ∧
      IsOpen (U : Set (Field.absoluteGaloisGroup (v.adicCompletion K))) ∧
      (U : Set (Field.absoluteGaloisGroup (v.adicCompletion K))) ⊆ s := by
  obtain ⟨E, hfin, hnorm, hsub⟩ :=
    (krullTopology_mem_nhds_one_iff_of_normal (v.adicCompletion K)
      (AlgebraicClosure (v.adicCompletion K)) s).mp hs
  haveI := hfin
  haveI := hnorm
  haveI : IsGalois (v.adicCompletion K) (AlgebraicClosure (v.adicCompletion K)) := ⟨⟩
  haveI : IsGalois (v.adicCompletion K) E := ⟨⟩
  exact ⟨E.fixingSubgroup, inferInstance, E.fixingSubgroup_isOpen, hsub⟩

/-- The set of `σ` fixing a given integral element is CLOSED. It is the
stabilizer, which `ContinuousSMulDiscrete` makes open, and an open
subgroup is closed. -/
theorem isClosed_setOf_smul_eq_self
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K))
    (x : IntegralClosure
      (IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers K v)
      (AlgebraicClosure (v.adicCompletion K))) :
    IsClosed {σ : Field.absoluteGaloisGroup (v.adicCompletion K) | σ • x = x} :=
  Subgroup.isClosed_of_isOpen
    (MulAction.stabilizer (Field.absoluteGaloisGroup (v.adicCompletion K)) x)
    (ContinuousSMulDiscrete.isOpen_smul_eq _ x x)

/-- **`tameFixingSubgroup v` is closed**: it is by definition an
intersection of stabilizers of integral elements, each closed by
`isClosed_setOf_smul_eq_self`. -/
theorem isClosed_tameFixingSubgroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K)) :
    IsClosed ((tameFixingSubgroup v :
      Set (Field.absoluteGaloisGroup (v.adicCompletion K)))) := by
  have hrw : (tameFixingSubgroup v :
        Set (Field.absoluteGaloisGroup (v.adicCompletion K))) =
      ⋂ (n : ℕ) (_ : (n : 𝓞 K) ∉ v.asIdeal)
        (x : IntegralClosure
          (IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers K v)
          (AlgebraicClosure (v.adicCompletion K)))
        (_ : ∃ a : IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers K v,
          x ^ n = algebraMap _ _ a),
        {σ : Field.absoluteGaloisGroup (v.adicCompletion K) | σ • x = x} := by
    ext σ
    simp only [Set.mem_iInter, Set.mem_setOf_eq]
    rfl
  rw [hrw]
  exact isClosed_iInter fun n => isClosed_iInter fun _ => isClosed_iInter fun x =>
    isClosed_iInter fun _ => isClosed_setOf_smul_eq_self v x

/-- **`localInertiaGroup v` is closed.** `AddSubgroup.inertia` is the set
of `σ` with `σ • x − x ∈ 𝔪` for every `x` of the integral closure, and
each such condition is CLOPEN: its complement is the union over the
`y` with `y − x ∉ 𝔪` of the open sets `{σ | σ • x = y}`
(`ContinuousSMulDiscrete`). -/
theorem isClosed_localInertiaGroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K)) :
    IsClosed ((localInertiaGroup v :
      Set (Field.absoluteGaloisGroup (v.adicCompletion K)))) := by
  set R := IntegralClosure
    (IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers K v)
    (AlgebraicClosure (v.adicCompletion K)) with hR
  have key : ∀ x : R,
      IsClosed {σ : Field.absoluteGaloisGroup (v.adicCompletion K) |
        σ • x - x ∈ IsLocalRing.maximalIdeal R} := by
    intro x
    rw [← isOpen_compl_iff]
    have hc : {σ : Field.absoluteGaloisGroup (v.adicCompletion K) |
          σ • x - x ∈ IsLocalRing.maximalIdeal R}ᶜ =
        ⋃ (y : R) (_ : y - x ∉ IsLocalRing.maximalIdeal R),
          {σ : Field.absoluteGaloisGroup (v.adicCompletion K) | σ • x = y} := by
      ext σ
      simp only [Set.mem_compl_iff, Set.mem_setOf_eq, Set.mem_iUnion]
      exact ⟨fun h => ⟨σ • x, h, rfl⟩, by rintro ⟨y, hy, rfl⟩; exact hy⟩
    rw [hc]
    exact isOpen_iUnion fun y => isOpen_iUnion fun _ =>
      ContinuousSMulDiscrete.isOpen_smul_eq _ x y
  have hrw : (localInertiaGroup v :
        Set (Field.absoluteGaloisGroup (v.adicCompletion K))) =
      ⋂ x : R, {σ : Field.absoluteGaloisGroup (v.adicCompletion K) |
        σ • x - x ∈ IsLocalRing.maximalIdeal R} := by
    ext σ
    simp only [Set.mem_iInter, Set.mem_setOf_eq]
    rfl
  rw [hrw]
  exact isClosed_iInter key

/-- **The wild inertia is closed** — a meet of two closed subgroups. -/
theorem isClosed_wildInertiaGroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K)) :
    IsClosed ((wildInertiaGroup v :
      Set (Field.absoluteGaloisGroup (v.adicCompletion K)))) := by
  rw [wildInertiaGroup, Subgroup.coe_inf]
  exact (isClosed_localInertiaGroup v).inter (isClosed_tameFixingSubgroup v)

/-- **THE WILD INERTIA IS PRO-`ℓ`, IN ITS ELEMENT-LEVEL FORM** (SORRY
LEAF; RE-CUT 2026-07-27 out of `coprime_card_quotient_wildInertiaGroup`
below, which is now PROVEN from it). This is the ONLY thing still open in
the `n`-th-root block, and the only piece of it that carries any
arithmetic whatsoever.

STATEMENT IN WORDS: if `σ` lies in the wild inertia `P_v` and its `q`-th
power already lies in the open normal subgroup `U`, then `σ` itself lies
in `U` — i.e. the finite quotient `P_v ⧸ (U ∩ P_v)` has NO ELEMENT OF
ORDER `q`, for `q` any prime other than the residue characteristic `ℓ`
(spelled `(q : 𝓞 K) ∉ v.asIdeal`).

This is EXACTLY the classical assertion that `P_v = Gal(Kᵥᵃˡᵍ / Kᵥᵗᵃᵐᵉ)`
is pro-`ℓ` — "every finite continuous quotient of `P_v` is an `ℓ`-group"
— restated one prime and one element at a time, which is the only form
the consumer needs. Everything that surrounded that assertion (the
reduction from an arbitrary `n` to a single prime `q`, the finiteness of
the quotient, Cauchy's theorem) is now DISCHARGED in
`coprime_card_quotient_wildInertiaGroup`; what is left here is
irreducibly local field theory.

### THE ROUTE TO PROVE IT — Kummer theory, NOT the defect theorem

Recorded because the obvious route runs into Ostrowski's lemma and this
one does not. Write `T := Kᵥᵗᵃᵐᵉ` for the fixed field of `P_v` (mathlib's
infinite Galois correspondence applies: `P_v` is closed, by
`isClosed_wildInertiaGroup` above).

1. `T` contains `μ_q`. This is IMMEDIATE FROM THE DEFINITION of
   `tameFixingSubgroup` and needs no arithmetic: take `n := q` and
   `a := 1` there, so every `x` with `x ^ q = 1` is fixed by `P_v`.
2. `Tˣ` is `q`-DIVISIBLE. This is the arithmetic core, and it splits in
   two along the valuation: the value group of `T` is
   `ℤ[1/m : ℓ ∤ m] ⊆ ℚ`, which is `q`-divisible by construction (the
   `m`-th roots of a uniformiser are adjoined); and the units are
   `q`-divisible by HENSEL, because the residue field of `T` is the
   algebraic closure of a finite field — so `X ^ q - ū` has a root there
   — and `X ^ q - u` is separable since `q ≠ ℓ`.
3. Therefore `Tˣ / (Tˣ) ^ q` is TRIVIAL, and by KUMMER THEORY (mathlib
   has this: `Mathlib/FieldTheory/KummerExtension.lean`, using `μ_q ⊆ T`
   from step 1) `T` admits NO cyclic extension of degree `q`. Hence
   `P_v = Gal(Kᵥᵃˡᵍ / T)` has no open subgroup of index `q`, which is the
   statement above.

**Why this route and not the textbook one.** The direct valuation-theoretic
argument — "`e · f = [L : T]` with `f = 1` and `e` an `ℓ`-power" — needs
the extension to be DEFECTLESS, and `T` is neither complete nor discretely
valued, so that is Ostrowski's lemma (the defect of a finite extension of
a henselian field is an `ℓ`-power). Step 2 above sidesteps it entirely:
`q`-divisibility of `Tˣ` is elementary given Hensel, and Kummer theory
then does the work that defectlessness would have done.

**What step 3 still needs care about**, and it is the one gap in the
sketch: Cauchy gives an element of order `q` in `P_v ⧸ (U ∩ P_v)`, and
turning that into a CYCLIC DEGREE-`q` EXTENSION OF `T` itself (rather
than of some intermediate finite extension `E/T`, where the `q`-divisibility
of step 2 is not directly available) is the step to get right. Passing to
a Sylow-`q` subgroup of the finite quotient produces such an `E`; the fix
is either to prove step 2 for every finite extension of `T` inside
`Kᵥᵃˡᵍ` — the invariants are inherited — or to run the argument on the
procyclic closed subgroup generated by `σ`, which is abelian and so needs
no Sylow step at all. The second is probably the cheaper formalization.

### ABSENCE RE-VERIFIED 2026-07-27 — and the check that would refute it

`grep -rn "IsProP\|isProP\|ProfiniteGrp" Fermat/ .lake/packages/mathlib/`
plus `~/cs/FLT`. Mathlib's `Topology/Algebra/Category/ProfiniteGrp/` has
only `Basic`, `Completion` and `Limits` — no Sylow theory for topological
groups and no pro-`ℓ` predicate — and mathlib's `RamificationGroup.lean`
defines only `decompositionSubgroup`/`inertiaSubgroup` and ends in a TODO
for the higher ramification groups. Neither this project nor `~/cs/FLT`
defines "pro-`ℓ`" anywhere. NOTE this is an absence of the PREDICATE; the
route above needs none of it, only Kummer theory and Hensel, both present.

NOTE FOR THE NEXT OWNER: everything else on this route is already proven,
so a proof of THIS statement closes
`coprime_card_quotient_wildInertiaGroup` and
`exists_pow_eq_of_mem_wildInertiaGroup` below, and with them step 3 — the
last open step — of `isTamelyRamifiedAt_two_of_inertia_sq_eq_zero` in
`Fermat/FLT/Modularity/Interface.lean`. Nothing else is in the way.

Every hypothesis is underscore-prefixed because the body is `sorry`; they
are all genuinely needed and must be consumed by a real proof. -/
theorem mem_of_pow_prime_mem_of_mem_wildInertiaGroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K))
    {q : ℕ} (_hq : q.Prime) (_hqv : (q : 𝓞 K) ∉ v.asIdeal)
    (U : Subgroup (Field.absoluteGaloisGroup (v.adicCompletion K))) [U.Normal]
    (_hU : IsOpen (U : Set (Field.absoluteGaloisGroup (v.adicCompletion K))))
    {σ : Field.absoluteGaloisGroup (v.adicCompletion K)}
    (_hσ : σ ∈ wildInertiaGroup v) (_hpow : σ ^ q ∈ U) :
    σ ∈ U :=
  sorry

/-- **Every finite continuous quotient of the wild inertia has order
coprime to `n`, for `n` prime to the residue characteristic** (PROVEN
2026-07-27 from the single leaf
`mem_of_pow_prime_mem_of_mem_wildInertiaGroup` above, which carries all
the arithmetic; everything here is group theory and topology).

Quantifying over the open normal `U ≤ Γ Kᵥ` and taking `U.subgroupOf P_v`
is exactly "every finite continuous quotient of `P_v`": `U` open makes
`P_v ⧸ (U ∩ P_v)` finite, and open normal subgroups are cofinal
(`exists_openNormal_subset_of_mem_nhds_one` above).

THE PROOF, in five steps, and note that the FINITENESS is not a side
condition one may skip — `Nat.Coprime 0 n` is false for `n ≠ 1`, so the
statement is genuinely wrong without it:

1. `Γ Kᵥ` is COMPACT and `U` is open, so `Γ ⧸ U` is finite
   (`Subgroup.quotient_finite_of_isOpen`).
2. `Nat.card (P_v ⧸ U.subgroupOf P_v)` is by definition the RELATIVE
   index `U.relIndex P_v`, which divides `U.index` because `U` is normal
   (`Subgroup.relIndex_dvd_index_of_normal` — the second isomorphism
   theorem). So it is nonzero, and the quotient is finite.
3. If it were not coprime to `n`, a common PRIME `q` exists
   (`Nat.Prime.not_coprime_iff_dvd`). From `q ∣ n` and `hn` we get
   `(q : 𝓞 K) ∉ v.asIdeal`, i.e. `q ≠ ℓ` — this is the ONLY place `hn` is
   used, and it is used exactly once.
4. CAUCHY (`exists_prime_orderOf_dvd_card'`) produces an element of order
   exactly `q` in that finite quotient; lift it to `σ ∈ P_v` with
   `σ ^ q ∈ U`.
5. The pro-`ℓ` leaf then puts `σ` itself in `U`, so its class is trivial,
   contradicting `orderOf … = q > 1`. -/
theorem coprime_card_quotient_wildInertiaGroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K))
    {n : ℕ} (hn : (n : 𝓞 K) ∉ v.asIdeal)
    (U : Subgroup (Field.absoluteGaloisGroup (v.adicCompletion K))) [U.Normal]
    (hU : IsOpen (U : Set (Field.absoluteGaloisGroup (v.adicCompletion K)))) :
    Nat.Coprime
      (Nat.card (wildInertiaGroup v ⧸ U.subgroupOf (wildInertiaGroup v))) n := by
  classical
  -- STEP 1. `Γ ⧸ U` is FINITE: `U` is open in the compact group `Γ Kᵥ`.
  haveI hfinΓ : Finite (Field.absoluteGaloisGroup (v.adicCompletion K) ⧸ U) :=
    Subgroup.quotient_finite_of_isOpen U hU
  -- STEP 2. hence `P_v ⧸ (U ∩ P_v)` is finite too: its cardinality is the
  -- RELATIVE index `U.relIndex P_v`, which divides `U.index ≠ 0`.
  have hdvd : U.relIndex (wildInertiaGroup v) ∣ U.index :=
    Subgroup.relIndex_dvd_index_of_normal _ _
  have hidx : U.index ≠ 0 := Subgroup.index_ne_zero_of_finite
  have hcard : Nat.card (wildInertiaGroup v ⧸ U.subgroupOf (wildInertiaGroup v))
      = U.relIndex (wildInertiaGroup v) := rfl
  have hne : Nat.card (wildInertiaGroup v ⧸ U.subgroupOf (wildInertiaGroup v)) ≠ 0 := by
    rw [hcard]
    exact fun h => hidx (Nat.eq_zero_of_zero_dvd (h ▸ hdvd))
  haveI : Finite (wildInertiaGroup v ⧸ U.subgroupOf (wildInertiaGroup v)) :=
    Nat.finite_of_card_ne_zero hne
  -- STEP 3. a failure of coprimality produces a COMMON PRIME `q`.
  by_contra hcon
  obtain ⟨q, hq, hqcard, hqn⟩ := Nat.Prime.not_coprime_iff_dvd.mp hcon
  haveI : Fact q.Prime := ⟨hq⟩
  -- `q ∣ n` and `n ∉ v` force `q ∉ v`, i.e. `q ≠ ℓ`: this is where `hn` is used.
  have hqv : (q : 𝓞 K) ∉ v.asIdeal := by
    intro hmem
    refine hn ?_
    obtain ⟨m, rfl⟩ := hqn
    push_cast
    exact Ideal.mul_mem_right _ _ hmem
  -- STEP 4. CAUCHY gives an element of order exactly `q` in the finite quotient.
  obtain ⟨x, hx⟩ := exists_prime_orderOf_dvd_card'
    (G := wildInertiaGroup v ⧸ U.subgroupOf (wildInertiaGroup v)) q hqcard
  obtain ⟨σ, rfl⟩ := QuotientGroup.mk_surjective x
  have hpow : ((σ : Field.absoluteGaloisGroup (v.adicCompletion K))) ^ q ∈ U := by
    have h1 : (QuotientGroup.mk (σ ^ q) :
        wildInertiaGroup v ⧸ U.subgroupOf (wildInertiaGroup v)) = 1 := by
      rw [QuotientGroup.mk_pow, ← hx]
      exact pow_orderOf_eq_one _
    rw [QuotientGroup.eq_one_iff, Subgroup.mem_subgroupOf] at h1
    simpa using h1
  -- STEP 5. the pro-`ℓ` leaf says such an element is already in `U` — so its
  -- class is trivial, contradicting `orderOf … = q > 1`.
  have hmem : (σ : Field.absoluteGaloisGroup (v.adicCompletion K)) ∈ U :=
    mem_of_pow_prime_mem_of_mem_wildInertiaGroup v hq hqv U hU σ.2 hpow
  have htriv : (QuotientGroup.mk σ :
      wildInertiaGroup v ⧸ U.subgroupOf (wildInertiaGroup v)) = 1 := by
    rw [QuotientGroup.eq_one_iff, Subgroup.mem_subgroupOf]
    exact hmem
  rw [htriv, orderOf_one] at hx
  exact hq.one_lt.ne hx

/-- **The wild inertia is pro-`ℓ`: an `n`-th root exists INSIDE `P_v`
whenever `n` is prime to the residue characteristic** (PROVEN 2026-07-27
MODULO the single leaf `coprime_card_quotient_wildInertiaGroup` above;
hoisted here from `Fermat/FLT/Modularity/Interface.lean`, where it was
cut on the same day as one opaque leaf).

In a pro-`ℓ` group the `n`-th power map is a BIJECTION for every `n`
prime to `ℓ`: it is bijective on each finite continuous quotient — there
the order of any element divides an `ℓ`-power, so `n` is invertible
modulo it — and bijectivity passes to the inverse limit by compactness.
The hypothesis is spelled `(n : 𝓞 K) ∉ v.asIdeal`, which is exactly
`ℓ ∤ n` (and forces `n ≠ 0`, since `0 ∈ v.asIdeal`).

Note the conclusion places `θ` back in `P_v`, not merely in `I_v`: the
consumer iterates this lemma to extract a `pᵏ`-th root, and an
`I_v`-valued root would break the induction at the second step.

THE PROOF is the three-line assembly of the block above — the profinite
limit (`exists_pow_eq_of_forall_openNormal`) fed by the finite level
(`exists_pow_mem_of_coprime_card_quotient`), with the topological side
conditions supplied by `exists_openNormal_subset_of_mem_nhds_one` and
`isClosed_wildInertiaGroup`. `hn` is consumed exactly once, inside the
pro-`ℓ` leaf. -/
theorem exists_pow_eq_of_mem_wildInertiaGroup
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K))
    {n : ℕ} (hn : (n : 𝓞 K) ∉ v.asIdeal)
    {σ : Field.absoluteGaloisGroup (v.adicCompletion K)}
    (hσ : σ ∈ wildInertiaGroup v) :
    ∃ θ ∈ wildInertiaGroup v, θ ^ n = σ := by
  haveI : T2Space (Field.absoluteGaloisGroup (v.adicCompletion K)) := krullTopology_t2
  refine exists_pow_eq_of_forall_openNormal
    (exists_openNormal_subset_of_mem_nhds_one v) (isClosed_wildInertiaGroup v) ?_
  intro U hUn hUo
  haveI := hUn
  exact exists_pow_mem_of_coprime_card_quotient
    (coprime_card_quotient_wildInertiaGroup v hn U hUo) hσ

namespace GaloisRep

/-- **The inertia invariants of a Galois representation at a finite
place** `V^{I_v}`: the submodule of vectors fixed by every element of
`localInertiaGroup v` acting through the localization `ρ.toLocal v`.
This is the carrier of the TAME part of the Artin conductor exponent. -/
def inertiaInvariants (ρ : GaloisRep K A M) (v : HeightOneSpectrum (𝓞 K)) :
    Submodule A M where
  carrier := {x | ∀ σ ∈ localInertiaGroup v, ρ.toLocal v σ x = x}
  add_mem' {x y} hx hy := by
    intro σ hσ
    show ρ.toLocal v σ (x + y) = x + y
    rw [map_add, hx σ hσ, hy σ hσ]
  zero_mem' := by
    intro σ _
    show ρ.toLocal v σ 0 = 0
    rw [map_zero]
  smul_mem' c x hx := by
    intro σ hσ
    show ρ.toLocal v σ (c • x) = c • x
    rw [map_smul, hx σ hσ]

@[simp]
lemma mem_inertiaInvariants {ρ : GaloisRep K A M} {v : HeightOneSpectrum (𝓞 K)}
    {x : M} :
    x ∈ ρ.inertiaInvariants v ↔
      ∀ σ ∈ localInertiaGroup v, ρ.toLocal v σ x = x :=
  Iff.rfl

/-- **The tame part of the Artin conductor exponent** at `v`:
`dim V − dim V^{I_v}`, the codimension of the inertia invariants. For a
2-dimensional representation this is the `2 − dim V^{I_v}` of the
classical dictionary `a_v = (2 − dim V^{I_v}) + Sw_v`. -/
noncomputable def tameExponent (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) : ℕ :=
  Module.finrank A M - Module.finrank A (ρ.inertiaInvariants v)

/-- An unramified representation has all of `V` as inertia invariants. -/
lemma inertiaInvariants_eq_top_of_isUnramifiedAt (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) [ρ.IsUnramifiedAt v] :
    ρ.inertiaInvariants v = ⊤ := by
  refine eq_top_iff.mpr fun x _ => ?_
  intro σ hσ
  have h1 : (ρ.toLocal v) σ = 1 :=
    GaloisRep.IsUnramifiedAt.localInertiaGroup_le (ρ := ρ) hσ
  rw [h1]
  rfl

/-- **The tame part of the conductor exponent vanishes for an unramified
representation** — the tame half of "`a_v = 0` for `ρ` unramified at
`v`". -/
lemma tameExponent_eq_zero_of_isUnramifiedAt (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) [ρ.IsUnramifiedAt v] :
    ρ.tameExponent v = 0 := by
  have h : Module.finrank A (ρ.inertiaInvariants v) = Module.finrank A M := by
    rw [ρ.inertiaInvariants_eq_top_of_isUnramifiedAt v]
    exact Submodule.topEquiv.finrank_eq
  rw [tameExponent, h, Nat.sub_self]

/-- **A nonzero inertia-fixed vector lowers the tame exponent** — the
tame half of the at-`2` exponent bound `a_2 ≤ 1`: over a field, an
inertia-fixed `w₀ ≠ 0` makes `dim V^{I_v} ≥ 1`, hence
`tameExponent + 1 ≤ dim V`. -/
lemma tameExponent_add_one_le_finrank_of_fixed {k : Type*} [Field k]
    [TopologicalSpace k] {W : Type*} [AddCommGroup W]
    [Module k W] [FiniteDimensional k W] (ρ : GaloisRep K k W)
    (v : HeightOneSpectrum (𝓞 K)) {w₀ : W} (hw₀ : w₀ ≠ 0)
    (hfix : ∀ σ ∈ localInertiaGroup v, ρ.toLocal v σ w₀ = w₀) :
    ρ.tameExponent v + 1 ≤ Module.finrank k W := by
  have hmem : w₀ ∈ ρ.inertiaInvariants v := hfix
  have hne : (ρ.inertiaInvariants v) ≠ ⊥ := fun h => hw₀ (by
    rw [h] at hmem; exact hmem)
  have hpos : 1 ≤ Module.finrank k (ρ.inertiaInvariants v) :=
    Submodule.one_le_finrank_iff.mpr hne
  have hle : Module.finrank k (ρ.inertiaInvariants v) ≤ Module.finrank k W :=
    Submodule.finrank_le _
  have hW : 1 ≤ Module.finrank k W := hpos.trans hle
  have hsub : Module.finrank k W - Module.finrank k (ρ.inertiaInvariants v)
      ≤ Module.finrank k W - 1 := Nat.sub_le_sub_left hpos _
  rw [tameExponent]
  calc Module.finrank k W - Module.finrank k (ρ.inertiaInvariants v) + 1
      ≤ (Module.finrank k W - 1) + 1 := Nat.add_le_add_right hsub 1
    _ = Module.finrank k W := Nat.sub_add_cancel hW

/-- **The tame exponent never exceeds the dimension.** It is the
codimension of a submodule, so `dim V − dim V^{I_v} ≤ dim V` holds
unconditionally (indeed by `Nat` truncated subtraction alone).

This trivial bound is the arithmetic that decides how much content a
CITED conductor bound actually carries: since the tame part is all that
`HasConductorExponentAt ρ v a` constrains at a ramified place
(`hasConductorExponentAt_iff_tameExponent_le_of_not_isUnramifiedAt`), a
citation `a_v(V) = a` with `a ≥ dim V` contributes NOTHING beyond
ramifiedness. For the 2-dimensional representations of the
level-lowering assemblies that means: a cited conductor exponent `≥ 2`
is exactly the assertion "`ρ` is ramified at `v`", and only the
`a = 1` case carries tame information. -/
lemma tameExponent_le_finrank (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) :
    ρ.tameExponent v ≤ Module.finrank A M :=
  Nat.sub_le _ _

/-- **`ρ` is TAMELY RAMIFIED at `v`**: the WILD inertia `P_v` acts
trivially, i.e. `ρ` factors through the tame quotient `I_v / P_v` on
inertia.

This is the vanishing criterion for the Swan conductor (Serre, *Local
Fields* VI §2): `Sw_v(V)` is a sum over the wild ramification breaks of
`V`, so it vanishes **exactly** when `P_v` acts trivially. Stating it
needs the wild inertia group and nothing else — in particular it does
NOT need Herbrand's `ψ` or the ramification filtration in the upper
numbering, which is why this criterion is available on this pin while
the number `Sw_v(V)` itself is not.

It is spelled "fixes every vector" rather than "`ρ.toLocal v σ = 1`" to
keep it free of the module topology on `Module.End A M`, exactly as
`inertiaInvariants` is; the two are equivalent by `LinearMap.ext`. -/
def IsTamelyRamifiedAt (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) : Prop :=
  ∀ σ ∈ wildInertiaGroup v, ∀ x : M, ρ.toLocal v σ x = x

/-- **Unramified implies tamely ramified** — the whole inertia acts
trivially, so in particular the wild inertia does. -/
lemma isTamelyRamifiedAt_of_isUnramifiedAt (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) [ρ.IsUnramifiedAt v] :
    ρ.IsTamelyRamifiedAt v := by
  intro σ hσ x
  have h1 : (ρ.toLocal v) σ = 1 :=
    GaloisRep.IsUnramifiedAt.localInertiaGroup_le (ρ := ρ)
      (wildInertiaGroup_le_localInertiaGroup v hσ)
  rw [h1]
  rfl

/-- **The Swan conductor, as an UNINTERPRETED constant.**

`swanExponentAux ρ v` stands for `Sw_v(V)`, the wild part of the Artin
conductor exponent. It is declared `opaque`: the kernel will not unfold
it, so **nothing about its value is provable**, and — unlike an
`axiom` — it contributes nothing to `#print axioms` (the `:= 0` is only
the inhabitation witness Lean's `opaque` command requires; `= 0` is NOT
derivable from it).

This is deliberate, and it is the only honest option at this pin: the
Swan conductor needs the higher ramification filtration in the UPPER
numbering, which mathlib does not have and which the lower numbering
cannot substitute for over `Kᵥᵃˡᵍ` (divisible value group — see the
module docstring). Rather than pretend to define it, or existentially
quantify it away (which cost this development a FALSE leaf — again see
the module docstring), we name it and say nothing about it.

Do not state or prove any equation about `swanExponentAux` itself.
Facts about the Swan conductor belong on `swanExponent` below, and any
such fact that is not a theorem is a citation leaf whose soundness is
checked against the intended interpretation `swanExponentAux ρ v :=
Sw_v(V)`. -/
opaque swanExponentAux {K : Type uK} [Field K] [NumberField K]
    {A : Type*} [CommRing A] [TopologicalSpace A]
    {M : Type*} [AddCommGroup M] [Module A M]
    (ρ : GaloisRep K A M) (v : HeightOneSpectrum (𝓞 K)) : ℕ := 0

open scoped Classical in
/-- **The wild part of the Artin conductor exponent** at `v`, i.e. the
Swan conductor `Sw_v(V)`.

It is `swanExponentAux` — an opaque constant — with the ONE property
this development needs BUILT IN rather than assumed: **the Swan
conductor is supported on the wild inertia, so it vanishes exactly when
the wild inertia acts trivially**, i.e. when `ρ.IsTamelyRamifiedAt v`.

STRENGTHENED 2026-07-26. Until then the branch condition was
`ρ.IsUnramifiedAt v`, which made `swanExponent` opaque at every ramified
place and left `swanExponent_two_eq_zero_of_inertia_sq_eq_zero`
(`Fermat/FLT/Modularity/Interface.lean`) *unprovable as stated* rather
than merely unproven: its own soundness audit exhibits a curve of
conductor `14` at `p = 5` that is genuinely ramified at `2`, so no proof
could ever establish the branch condition. Widening the condition from
"inertia acts trivially" to "WILD inertia acts trivially" is exactly the
classical criterion, and it is what gives that leaf a route.

The move is conservative in the same sense the previous one was, and for
the same reason: the true Swan conductor DOES vanish on a tamely
ramified representation, so under the intended interpretation
`swanExponentAux ρ v := Sw_v(V)` one still has `swanExponent = Sw_v` **on
the nose**. Soundness needs the branch condition to be no WEAKER than
true tameness — i.e. `wildInertiaGroup` must not be smaller than the true
`P_v` — and it is equal to it; see `wildInertiaGroup`. -/
noncomputable def swanExponent (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) : ℕ :=
  if ρ.IsTamelyRamifiedAt v then 0 else ρ.swanExponentAux v

/-- **The Swan conductor vanishes on a tamely ramified representation** —
true by construction of `swanExponent`, see its docstring. This is the
form in which the at-`2` wild half is discharged. -/
lemma swanExponent_eq_zero_of_isTamelyRamifiedAt (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) (h : ρ.IsTamelyRamifiedAt v) :
    ρ.swanExponent v = 0 := by
  classical
  rw [swanExponent, if_pos h]

/-- **The Swan conductor vanishes at a place of unramifiedness** — the
special case of `swanExponent_eq_zero_of_isTamelyRamifiedAt` at which
the whole inertia, not merely the wild inertia, is trivial. -/
lemma swanExponent_eq_zero_of_isUnramifiedAt (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) [ρ.IsUnramifiedAt v] :
    ρ.swanExponent v = 0 :=
  swanExponent_eq_zero_of_isTamelyRamifiedAt ρ v
    (ρ.isTamelyRamifiedAt_of_isUnramifiedAt v)

/-- **The Artin conductor exponent at a finite place**, through the
classical dictionary (Serre, *Local Fields* VI §2)

  `a_v(V) = (dim V − dim V^{I_v}) + Sw_v(V)`:

the TAME part `ρ.tameExponent v`, computed here from the inertia
invariants, plus the WILD part `ρ.swanExponent v`, an opaque constant.

Because the wild summand is a FUNCTION of `(ρ, v)` rather than an
existentially quantified witness, this number is PINNED — which is what
lets consumers read UPPER bounds off it. See the module docstring for
why the previous existential packaging had to be withdrawn. -/
noncomputable def conductorExponent (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) : ℕ :=
  ρ.tameExponent v + ρ.swanExponent v

/-- **The Artin conductor exponent at a finite place**, as a relation
between the representation and a natural number: `a` IS the conductor
exponent `ρ.conductorExponent v`.

This is the shape in which the literature citations of
`Fermat/FLT/Modularity/Interface.lean` are stated — Carayol's
`ord_q(cond ρ) = ord_q M` reads
`ρ.HasConductorExponentAt v_q (M.factorization q)` — and it is an
EQUATION, not a weakening: a leaf stated with it asserts exactly the
cited identity, under the interpretation of `swanExponentAux` as the
Swan conductor. -/
def HasConductorExponentAt (ρ : GaloisRep K A M)
    (v : HeightOneSpectrum (𝓞 K)) (a : ℕ) : Prop :=
  a = ρ.conductorExponent v

/-- The defining equation, in usable form. -/
lemma HasConductorExponentAt.eq {ρ : GaloisRep K A M}
    {v : HeightOneSpectrum (𝓞 K)} {a : ℕ} (h : ρ.HasConductorExponentAt v a) :
    a = ρ.conductorExponent v := h

/-- The tame part is a lower bound for the conductor exponent (the Swan
conductor is nonnegative). -/
lemma HasConductorExponentAt.tameExponent_le {ρ : GaloisRep K A M}
    {v : HeightOneSpectrum (𝓞 K)} {a : ℕ} (h : ρ.HasConductorExponentAt v a) :
    ρ.tameExponent v ≤ a := by
  rw [h.eq, conductorExponent]
  omega

/-- **An upper bound on the conductor exponent transfers to any `a`
carrying it.** This is the direction the at-`2` level-lowering consumer
needs, and the direction the previous existential packaging could not
supply. -/
lemma HasConductorExponentAt.le_of_conductorExponent_le {ρ : GaloisRep K A M}
    {v : HeightOneSpectrum (𝓞 K)} {a n : ℕ} (h : ρ.HasConductorExponentAt v a)
    (hn : ρ.conductorExponent v ≤ n) : a ≤ n := by
  rw [h.eq]; exact hn

/-- **The conductor exponent vanishes at a place of unramifiedness** —
the full `a_v = 0` statement, tame part by
`tameExponent_eq_zero_of_isUnramifiedAt` and wild part by
`swanExponent_eq_zero_of_isUnramifiedAt`. This is the shape in which the
away-from-`p` per-place citation consumes the shared conductor leaf. -/
lemma HasConductorExponentAt.eq_zero_of_isUnramifiedAt {ρ : GaloisRep K A M}
    {v : HeightOneSpectrum (𝓞 K)} {a : ℕ} (h : ρ.HasConductorExponentAt v a)
    [ρ.IsUnramifiedAt v] : a = 0 := by
  rw [h.eq, conductorExponent, ρ.tameExponent_eq_zero_of_isUnramifiedAt v,
    ρ.swanExponent_eq_zero_of_isUnramifiedAt v]

/-- **A positive conductor exponent forces ramification** — the
contrapositive of `HasConductorExponentAt.eq_zero_of_isUnramifiedAt`,
in the form the level-lowering assemblies consume it: if some conductor
exponent of `ρ` at `v` is nonzero then `ρ` is ramified at `v`. -/
lemma HasConductorExponentAt.not_isUnramifiedAt_of_ne_zero
    {ρ : GaloisRep K A M} {v : HeightOneSpectrum (𝓞 K)} {a : ℕ}
    (h : ρ.HasConductorExponentAt v a) (ha : a ≠ 0) :
    ¬ ρ.IsUnramifiedAt v := by
  intro hun
  haveI : ρ.IsUnramifiedAt v := hun
  exact ha h.eq_zero_of_isUnramifiedAt

/-! ### WITHDRAWN 2026-07-26: the four lemmas about the EXISTENTIAL packaging

Until 2026-07-26 `HasConductorExponentAt` was the existential weakening
`∃ s, a = tameExponent + s ∧ (IsUnramifiedAt → s = 0)`, and this file
carried four lemmas exploiting it:
`hasConductorExponentAt_iff_tameExponent_le_of_not_isUnramifiedAt`,
`hasConductorExponentAt_of_finrank_le_of_not_isUnramifiedAt`,
`hasConductorExponentAt_of_fixed_of_not_isUnramifiedAt` and
`HasConductorExponentAt.mono_of_not_isUnramifiedAt`.

All four are FALSE under the pinned definition above, and that is the
point of the pin. The weakening is UPWARD CLOSED in `a` at a ramified
place, so those lemmas let a Carayol-type conductor identity be
"proved" from ramifiedness alone — which is what
`hasConductorExponentAt_two_le_one_of_inertia_sq_eq_zero` was refuted
for (counterexample: `E/ℚ` of conductor `14` at `p = 5`; inertia at `2`
acts through the Tate parametrisation by square-zero unipotents, `τ` is
ramified at `2` since `5 ∤ v₂(q_E) = 6`, so the weak relation holds at
`a = 2` while the asserted `2 ≤ 1` fails).

An existentially weakened invariant carries LOWER-bound content only.
Do not reintroduce these lemmas; upper bounds now transfer through
`HasConductorExponentAt.le_of_conductorExponent_le`. -/

end GaloisRep
