/-
GaloisRepresentation/HardlyRamified/CompleteLocalNoetherian.lean — own
work for the Fermat project (not vendored from the FLT project).

# A complete local ring with finitely generated maximal ideal is Noetherian

This module proves the pure commutative-algebra statement isolated on
2026-07-25 as the "then apply Cohen" half of Carayol's Noetherianity
argument (`isNoetherianRing_of_fg_maximalIdeal` in `Deformation.lean`):

> if `A` is local, `𝔪`-adically complete and separated, and `𝔪` is
> finitely generated, then `A` is Noetherian.

This is Stacks 05GH / Matsumura, *Commutative Ring Theory*, Thm 8.4
(also Bourbaki, *Algèbre commutative* III §2 no 9 Cor. 2) specialised to
`I = 𝔪`. Mathlib has the ingredients (`Ideal.Filtration`, the Artin–Rees
machinery, `IsAdicComplete`, the Hilbert basis theorem for
`MvPolynomial`) but not this implication: a search of
`Mathlib/RingTheory/AdicCompletion/`, `Mathlib/RingTheory/Filtration.lean`
and `Mathlib/RingTheory/GradedAlgebra/` (2026-07-25) finds only
statements that *assume* Noetherianity, no associated-graded ring of an
ideal filtration, and no Cohen structure theorem.

## The argument, and why it is organised the way it is

The textbook proof passes through the associated graded ring
`gr_𝔪(A) = ⊕ 𝔪^n/𝔪^{n+1}`: it is generated over the field `k = A/𝔪` by
the images of a finite generating set `f₁, …, f_r` of `𝔪`, hence
Noetherian by the Hilbert basis theorem; the ideal of leading forms of
an ideal `J` is therefore finitely generated, and lifting a homogeneous
generating set and running successive approximation — which converges
because `A` is complete and separated — shows `J` is generated by the
lifts.

Mathlib has no associated graded ring, so rather than build one this
module replaces `gr_𝔪(A)` by the polynomial ring `k[X₁, …, X_r]` that
surjects onto it, and replaces "the ideal of leading forms of `J`" by

`Gen = { (map (residue A)) P | P homogeneous of degree n, aeval f P ∈ J + 𝔪^{n+1} }`

inside `k[X₁, …, X_r]`. `Ideal.span Gen` is finitely generated because
`k[X₁, …, X_r]` is Noetherian (`MvPolynomial.isNoetherianRing`), and
finitely many of its generators may be taken *from `Gen` itself*
(`Submodule.mem_span_finite_of_mem_span`), which is what supplies the
homogeneous lifts `PP u` together with their degrees `dd u`. The two
bridges between `A` and the polynomial ring are:

* `aeval_mem_mul_pow` — a homogeneous polynomial of degree `n` all of
  whose coefficients lie in an ideal `c` evaluates into `c * 𝔪 ^ n`
  (with `c = ⊤` this says a homogeneous polynomial of degree `n`
  evaluates into `𝔪 ^ n`; with `c = 𝔪` it is what makes the error term
  of one approximation step land in `𝔪 ^ (n + 1)`);
* `exists_isHomogeneous_aeval` — conversely every element of `𝔪 ^ n` is
  the value at `f` of some homogeneous polynomial of degree `n`.

Degree bookkeeping across a decomposition `Ψ P = ∑ q u * Ψ (PP u)` is
done by `homogeneousComponent_mul_isHomogeneous`, which says that
multiplication by a homogeneous polynomial shifts homogeneous
components; that is the one place where the grading of the polynomial
ring is genuinely used, and it is what replaces "a homogeneous element
of a homogeneous ideal is a combination with homogeneous coefficients".

No Cohen structure theorem, no coefficient ring and no Witt vectors are
involved, which matters because `exists_coefficientRing_ringHom` and
`surjective_of_mvPowerSeries_ringHom` in `Deformation.lean` both already
*assume* `IsNoetherianRing`; deriving Noetherianity from them would be
circular.
-/
module

public import Mathlib.RingTheory.AdicCompletion.Basic
public import Mathlib.RingTheory.LocalRing.ResidueField.Basic
public import Mathlib.RingTheory.MvPolynomial.Homogeneous
public import Mathlib.RingTheory.Polynomial.Basic
public import Mathlib.RingTheory.Ideal.Operations
public import Mathlib.RingTheory.Noetherian.Basic

@[expose] public section

namespace CompleteLocalNoetherian

open MvPolynomial

variable {A : Type*} [CommRing A] {r : ℕ}

/-- A monomial `∏_{i ∈ s} f i ^ d i` lies in the `(∑_{i ∈ s} d i)`-th power of
the ideal generated by the `f i`. -/
lemma prod_pow_mem_pow (f : Fin r → A) (d : Fin r → ℕ) (s : Finset (Fin r)) :
    (∏ i ∈ s, f i ^ d i) ∈ (Ideal.span (Set.range f)) ^ (∑ i ∈ s, d i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp [Ideal.one_eq_top]
  | @insert a s ha ih =>
      rw [Finset.prod_insert ha, Finset.sum_insert ha, pow_add]
      exact Ideal.mul_mem_mul
        (Ideal.pow_mem_pow (Ideal.subset_span (Set.mem_range_self a)) _) ih

/-- **Evaluation of a homogeneous polynomial with constrained coefficients.**
If `P` is homogeneous of degree `n` and every coefficient of `P` lies in the
ideal `c`, then `P` evaluated at `f` lies in `c * I ^ n`, where `I` is the
ideal generated by the `f i`. -/
lemma aeval_mem_mul_pow (f : Fin r → A) {n : ℕ} {P : MvPolynomial (Fin r) A}
    (hP : P.IsHomogeneous n) (c : Ideal A)
    (hc : ∀ d, MvPolynomial.coeff d P ∈ c) :
    (MvPolynomial.aeval f) P ∈ c * (Ideal.span (Set.range f)) ^ n := by
  classical
  rw [MvPolynomial.aeval_def, MvPolynomial.eval₂_eq]
  refine Ideal.sum_mem _ fun d hd => ?_
  have hdeg : ∑ i ∈ d.support, d i = n := by
    have h := hP (MvPolynomial.mem_support_iff.mp hd)
    simpa [Finsupp.weight_apply, Finsupp.sum] using h
  refine Ideal.mul_mem_mul (by simpa using hc d) ?_
  have h := prod_pow_mem_pow f (fun i => d i) d.support
  rwa [hdeg] at h

/-- Evaluation of a homogeneous polynomial of degree `n` lands in the `n`-th
power of the ideal generated by the variables' images. -/
lemma aeval_mem_pow (f : Fin r → A) {n : ℕ} {P : MvPolynomial (Fin r) A}
    (hP : P.IsHomogeneous n) :
    (MvPolynomial.aeval f) P ∈ (Ideal.span (Set.range f)) ^ n := by
  have h := aeval_mem_mul_pow f hP ⊤ (fun _ => Submodule.mem_top)
  rwa [Ideal.top_mul] at h

/-- Every element of the ideal generated by the `f i` is the value at `f` of a
homogeneous polynomial of degree `1`. -/
lemma exists_isHomogeneous_aeval_one (f : Fin r → A) {b : A}
    (hb : b ∈ Ideal.span (Set.range f)) :
    ∃ Q : MvPolynomial (Fin r) A, Q.IsHomogeneous 1 ∧
      (MvPolynomial.aeval f) Q = b := by
  induction hb using Submodule.span_induction with
  | mem x hx =>
      obtain ⟨i, rfl⟩ := hx
      exact ⟨MvPolynomial.X i, MvPolynomial.isHomogeneous_X _ _, by simp⟩
  | zero => exact ⟨0, MvPolynomial.isHomogeneous_zero _ _ _, by simp⟩
  | add x y _ _ hx hy =>
      obtain ⟨P, hP, rfl⟩ := hx
      obtain ⟨Q, hQ, rfl⟩ := hy
      exact ⟨P + Q, hP.add hQ, by simp⟩
  | smul a x _ hx =>
      obtain ⟨P, hP, rfl⟩ := hx
      refine ⟨MvPolynomial.C a * P, ?_, by simp⟩
      simpa using (MvPolynomial.isHomogeneous_C _ a).mul hP

/-- **Every element of `I ^ n` is the value of a homogeneous polynomial of
degree `n`**, where `I` is the ideal generated by the `f i`. This is the
converse direction to `aeval_mem_pow`, and is what lets an arbitrary element
of `𝔪 ^ n` be fed to the graded machinery. -/
lemma exists_isHomogeneous_aeval (f : Fin r → A) (n : ℕ) {x : A}
    (hx : x ∈ (Ideal.span (Set.range f)) ^ n) :
    ∃ P : MvPolynomial (Fin r) A, P.IsHomogeneous n ∧
      (MvPolynomial.aeval f) P = x := by
  induction n generalizing x with
  | zero =>
      exact ⟨MvPolynomial.C x, MvPolynomial.isHomogeneous_C _ _, by simp⟩
  | succ n ih =>
      rw [pow_succ] at hx
      refine Submodule.mul_induction_on hx ?_ ?_
      · intro a ha b hb
        obtain ⟨P, hP, rfl⟩ := ih ha
        obtain ⟨Q, hQ, rfl⟩ := exists_isHomogeneous_aeval_one f hb
        exact ⟨P * Q, hP.mul hQ, by simp⟩
      · rintro x y ⟨P, hP, rfl⟩ ⟨Q, hQ, rfl⟩
        exact ⟨P + Q, hP.add hQ, by simp⟩

/-- **Multiplication by a homogeneous polynomial shifts homogeneous
components**: if `P` is homogeneous of degree `d` then the degree-`n`
homogeneous component of `Q * P` is the degree-`(n - d)` component of `Q`
times `P`, and vanishes when `n < d`.

This is the one genuinely graded input of the development: it is what lets a
decomposition `P = ∑ q u * PP u` of a homogeneous `P` over homogeneous `PP u`
be replaced by one whose coefficients are homogeneous of the complementary
degrees, which is what makes the successive approximation converge. -/
lemma homogeneousComponent_mul_isHomogeneous {σ : Type*} {R : Type*}
    [CommRing R] {P : MvPolynomial σ R} {d : ℕ} (hP : P.IsHomogeneous d)
    (Q : MvPolynomial σ R) (n : ℕ) :
    MvPolynomial.homogeneousComponent n (Q * P) =
      (if d ≤ n then MvPolynomial.homogeneousComponent (n - d) Q else 0) * P := by
  classical
  conv_lhs => rw [← MvPolynomial.sum_homogeneousComponent Q]
  rw [Finset.sum_mul, map_sum]
  have key : ∀ i ∈ Finset.range (Q.totalDegree + 1),
      MvPolynomial.homogeneousComponent n
          (MvPolynomial.homogeneousComponent i Q * P) =
        if n = i + d then MvPolynomial.homogeneousComponent i Q * P else 0 :=
    fun i _ => MvPolynomial.homogeneousComponent_of_mem
      ((MvPolynomial.homogeneousComponent_isHomogeneous i Q).mul hP)
  rw [Finset.sum_congr rfl key]
  by_cases hdn : d ≤ n
  · rw [if_pos hdn]
    by_cases hmem : n - d ∈ Finset.range (Q.totalDegree + 1)
    · rw [Finset.sum_eq_single (n - d) (fun b _ hb => if_neg (by omega))
        (fun h => absurd hmem h), if_pos (by omega)]
    · simp only [Finset.mem_range, not_lt] at hmem
      have hz : MvPolynomial.homogeneousComponent (n - d) Q = 0 := by
        apply MvPolynomial.homogeneousComponent_eq_zero
        omega
      rw [hz, zero_mul]
      refine Finset.sum_eq_zero fun i hi => ?_
      simp only [Finset.mem_range] at hi
      exact if_neg (by omega)
  · rw [if_neg hdn, zero_mul]
    exact Finset.sum_eq_zero fun i _ => if_neg (by omega)

/-- **A complete local ring with finitely generated maximal ideal is
Noetherian** (Stacks 05GH / Matsumura, *Commutative Ring Theory*, Thm 8.4,
specialised to `I = 𝔪`).

See the module docstring for the shape of the argument: the associated graded
ring is replaced by the polynomial ring `k[X₁, …, X_r]` over the residue field
that surjects onto it, Noetherianity of that polynomial ring produces finitely
many homogeneous "leading form" lifts, and successive approximation — which
converges by completeness and terminates by separatedness — shows every ideal
is generated by the `J`-parts of their values. -/
theorem isNoetherianRing_of_isAdicComplete_of_fg {A : Type*} [CommRing A]
    [IsLocalRing A]
    (hcomp : IsAdicComplete (IsLocalRing.maximalIdeal A) A)
    (hfg : (IsLocalRing.maximalIdeal A).FG) : IsNoetherianRing A := by
  classical
  haveI := hcomp
  obtain ⟨r, f, hf⟩ : ∃ (r : ℕ) (f : Fin r → A),
      Ideal.span (Set.range f) = IsLocalRing.maximalIdeal A :=
    Submodule.fg_iff_exists_fin_generating_family.mp hfg
  set 𝔪 : Ideal A := IsLocalRing.maximalIdeal A with h𝔪def
  rw [isNoetherianRing_iff_ideal_fg]
  intro J
  set Ψ : MvPolynomial (Fin r) A →+*
      MvPolynomial (Fin r) (IsLocalRing.ResidueField A) :=
    MvPolynomial.map (IsLocalRing.residue A) with hΨdef
  have hΨsurj : Function.Surjective Ψ :=
    MvPolynomial.map_surjective _ Ideal.Quotient.mk_surjective
  -- The "leading form" set, pushed into the polynomial ring over the residue
  -- field, where the Hilbert basis theorem applies.
  set Gen : Set (MvPolynomial (Fin r) (IsLocalRing.ResidueField A)) :=
    {u | ∃ (n : ℕ) (P : MvPolynomial (Fin r) A), P.IsHomogeneous n ∧
      (MvPolynomial.aeval f) P ∈ J ⊔ 𝔪 ^ (n + 1) ∧ Ψ P = u} with hGendef
  -- Finitely many generators may be chosen from `Gen` itself.
  obtain ⟨t, htGen, htspan⟩ :
      ∃ t : Finset (MvPolynomial (Fin r) (IsLocalRing.ResidueField A)), ↑t ⊆ Gen ∧
        Ideal.span (t : Set (MvPolynomial (Fin r) (IsLocalRing.ResidueField A))) = Ideal.span Gen := by
    -- a field is Noetherian, hence so is the polynomial ring over it
    haveI : IsNoetherianRing (IsLocalRing.ResidueField A) := by
      rw [isNoetherianRing_iff_ideal_fg]
      intro I
      rcases I.eq_bot_or_top with rfl | rfl
      · exact Submodule.fg_bot
      · exact ⟨{1}, by simp⟩
    obtain ⟨T, hT⟩ :=
      (isNoetherianRing_iff_ideal_fg (MvPolynomial (Fin r) (IsLocalRing.ResidueField A))).mp inferInstance
        (Ideal.span Gen)
    have hchoice : ∀ u : {x // x ∈ T}, ∃ Tu : Finset (MvPolynomial (Fin r) (IsLocalRing.ResidueField A)),
        ↑Tu ⊆ Gen ∧
          (u : MvPolynomial (Fin r) (IsLocalRing.ResidueField A)) ∈ Ideal.span (Tu : Set _) := by
      intro u
      have hu : (u : MvPolynomial (Fin r) (IsLocalRing.ResidueField A)) ∈ Ideal.span Gen := by
        rw [← hT]; exact Ideal.subset_span u.2
      exact Submodule.mem_span_finite_of_mem_span hu
    choose Tu hTu1 hTu2 using hchoice
    refine ⟨T.attach.biUnion Tu, ?_, le_antisymm ?_ ?_⟩
    · intro x hx
      simp only [Finset.coe_biUnion, Set.mem_iUnion, Finset.mem_coe] at hx
      obtain ⟨u, _, hu⟩ := hx
      exact hTu1 u hu
    · refine Ideal.span_le.mpr fun x hx => ?_
      simp only [Finset.coe_biUnion, Set.mem_iUnion, Finset.mem_coe] at hx
      obtain ⟨u, _, hu⟩ := hx
      exact Ideal.subset_span (hTu1 u hu)
    · rw [← hT]
      refine Ideal.span_le.mpr fun x hx => ?_
      refine Ideal.span_mono ?_ (hTu2 ⟨x, hx⟩)
      intro y hy
      simp only [Finset.coe_biUnion, Set.mem_iUnion, Finset.mem_coe]
      exact ⟨⟨x, hx⟩, Finset.mem_attach _ _, hy⟩
  -- The chosen generators, with their degrees and homogeneous lifts.
  have hdata : ∀ u : {x // x ∈ t}, ∃ (n : ℕ) (P : MvPolynomial (Fin r) A),
      P.IsHomogeneous n ∧ (MvPolynomial.aeval f) P ∈ J ⊔ 𝔪 ^ (n + 1) ∧
        Ψ P = (u : MvPolynomial (Fin r) (IsLocalRing.ResidueField A)) := fun u => htGen u.2
  choose dd PP hPPhom hPPmem hPPmap using hdata
  -- Split the value of each lift into its part in `J` and its error term.
  choose cc hccJ ee heeM hcce using fun u => Submodule.mem_sup.mp (hPPmem u)
  -- Each `cc u` lies in `𝔪 ^ (dd u)`.
  have hccM : ∀ u, cc u ∈ 𝔪 ^ (dd u) := by
    intro u
    have h1 : (MvPolynomial.aeval f) (PP u) ∈ 𝔪 ^ (dd u) := by
      have h := aeval_mem_pow f (hPPhom u)
      rwa [hf] at h
    have h2 : ee u ∈ 𝔪 ^ (dd u) :=
      Ideal.pow_le_pow_right (Nat.le_succ _) (heeM u)
    have h3 : cc u = (MvPolynomial.aeval f) (PP u) - ee u := by
      rw [← hcce u]; ring
    rw [h3]
    exact sub_mem h1 h2
  refine ⟨Finset.univ.image cc, le_antisymm ?_ ?_⟩
  · -- the easy inclusion: every `cc u` lies in `J`
    refine Ideal.span_le.mpr ?_
    intro x hx
    simp only [Finset.coe_image, Set.mem_image, Finset.mem_coe,
      Finset.mem_univ, true_and] at hx
    obtain ⟨u, rfl⟩ := hx
    exact hccJ u
  -- ONE APPROXIMATION STEP: peel off one power of `𝔪` from an element of `J`.
  have approx : ∀ (n : ℕ) (x : A), ∃ a : {x // x ∈ t} → A,
      x ∈ J → x ∈ 𝔪 ^ n →
        ((∀ u, a u ∈ 𝔪 ^ (n - dd u)) ∧
          (x - ∑ u, a u * cc u ∈ J) ∧
          (x - ∑ u, a u * cc u ∈ 𝔪 ^ (n + 1))) := by
    intro n x
    by_cases hgo : x ∈ J ∧ x ∈ 𝔪 ^ n
    swap
    · exact ⟨0, fun h1 h2 => absurd ⟨h1, h2⟩ hgo⟩
    obtain ⟨hxJ, hxm⟩ := hgo
    -- `x` is the value of a homogeneous polynomial of degree `n`
    obtain ⟨P, hPhom, hPval⟩ :=
      exists_isHomogeneous_aeval f n (by rw [hf]; exact hxm)
    -- its image lies in the span of the chosen generators
    have hPGen : Ψ P ∈ Ideal.span Gen :=
      Ideal.subset_span ⟨n, P, hPhom, by rw [hPval]; exact Ideal.mem_sup_left hxJ, rfl⟩
    rw [← htspan] at hPGen
    have hrange : (t : Set (MvPolynomial (Fin r) (IsLocalRing.ResidueField A))) =
        Set.range (fun u : {x // x ∈ t} => (u : MvPolynomial (Fin r) (IsLocalRing.ResidueField A))) := by
      ext y; simp
    have hPGen' : Ψ P ∈ Submodule.span (MvPolynomial (Fin r) (IsLocalRing.ResidueField A))
        (Set.range (fun u : {x // x ∈ t} => (u : MvPolynomial (Fin r) (IsLocalRing.ResidueField A)))) := by
      rw [← hrange]; exact hPGen
    rw [Submodule.mem_span_range_iff_exists_fun] at hPGen'
    obtain ⟨q, hq⟩ := hPGen'
    simp only [smul_eq_mul] at hq
    choose Q hQ using fun u => hΨsurj (q u)
    -- the difference has all coefficients in `𝔪`
    set W : MvPolynomial (Fin r) A := P - ∑ u, Q u * PP u with hWdef
    have hWker : Ψ W = 0 := by
      rw [hWdef, map_sub, map_sum]
      simp only [map_mul, hQ, hPPmap]
      rw [hq, sub_self]
    have hWcoeff : ∀ dg, MvPolynomial.coeff dg W ∈ 𝔪 := by
      intro dg
      have h : (IsLocalRing.residue A) (MvPolynomial.coeff dg W) = 0 := by
        rw [← MvPolynomial.coeff_map]
        change MvPolynomial.coeff dg (Ψ W) = 0
        rw [hWker, MvPolynomial.coeff_zero]
      rwa [IsLocalRing.residue_eq_zero_iff] at h
    -- the homogeneous coefficients of the decomposition, and their values
    set qq : {x // x ∈ t} → MvPolynomial (Fin r) A := fun u =>
      if dd u ≤ n then MvPolynomial.homogeneousComponent (n - dd u) (Q u) else 0
      with hqqdef
    have hqqhom : ∀ u, (qq u).IsHomogeneous (n - dd u) := by
      intro u
      rw [hqqdef]
      dsimp only
      split
      · exact MvPolynomial.homogeneousComponent_isHomogeneous _ _
      · exact MvPolynomial.isHomogeneous_zero _ _ _
    set aa : {x // x ∈ t} → A := fun u => (MvPolynomial.aeval f) (qq u) with haadef
    have haaM : ∀ u, aa u ∈ 𝔪 ^ (n - dd u) := by
      intro u
      have h := aeval_mem_pow f (hqqhom u)
      rw [hf] at h
      exact h
    -- extract the degree-`n` homogeneous component of `W`
    have hcompn : MvPolynomial.homogeneousComponent n W = P - ∑ u, qq u * PP u := by
      rw [hWdef, map_sub, map_sum,
        MvPolynomial.homogeneousComponent_eq_self hPhom]
      congr 1
      exact Finset.sum_congr rfl fun u _ =>
        homogeneousComponent_mul_isHomogeneous (hPPhom u) (Q u) n
    have hev : (MvPolynomial.aeval f) (MvPolynomial.homogeneousComponent n W) =
        x - ∑ u, aa u * ((MvPolynomial.aeval f) (PP u)) := by
      rw [hcompn, map_sub, map_sum, hPval]
      simp only [map_mul, haadef]
    have hleft : (MvPolynomial.aeval f)
        (MvPolynomial.homogeneousComponent n W) ∈ 𝔪 ^ (n + 1) := by
      have h := aeval_mem_mul_pow f
        (MvPolynomial.homogeneousComponent_isHomogeneous n W) 𝔪 (fun dg => by
          rw [MvPolynomial.coeff_homogeneousComponent]
          split
          · exact hWcoeff dg
          · exact Submodule.zero_mem _)
      rw [hf] at h
      rwa [← pow_succ'] at h
    refine ⟨aa, fun _ _ => ⟨haaM, ?_, ?_⟩⟩
    · exact sub_mem hxJ (Ideal.sum_mem _ fun u _ => Ideal.mul_mem_left _ _ (hccJ u))
    · have hsplit : x - ∑ u, aa u * cc u =
          (MvPolynomial.aeval f) (MvPolynomial.homogeneousComponent n W) +
            ∑ u, aa u * ee u := by
        rw [hev]
        have hterm : ∀ u : {x // x ∈ t},
            aa u * ((MvPolynomial.aeval f) (PP u)) = aa u * cc u + aa u * ee u := by
          intro u; rw [← hcce u]; ring
        rw [Finset.sum_congr rfl fun u _ => hterm u, Finset.sum_add_distrib]
        ring
      rw [hsplit]
      refine Ideal.add_mem _ hleft (Ideal.sum_mem _ fun u _ => ?_)
      have hle : 𝔪 ^ ((n - dd u) + (dd u + 1)) ≤ 𝔪 ^ (n + 1) :=
        Ideal.pow_le_pow_right (by omega)
      refine hle ?_
      rw [pow_add]
      exact Ideal.mul_mem_mul (haaM u) (heeM u)
  -- SUCCESSIVE APPROXIMATION: iterate the step and sum the coefficients.
  choose aa haa using approx
  intro x hxJ
  obtain ⟨seq, hseq0, hseqs⟩ : ∃ seq : ℕ → A, seq 0 = x ∧
      ∀ n, seq (n + 1) = seq n - ∑ u, aa n (seq n) u * cc u :=
    ⟨fun n => Nat.rec (motive := fun _ => A) x
      (fun m y => y - ∑ u, aa m y u * cc u) n, rfl, fun _ => rfl⟩
  have hinv : ∀ n, seq n ∈ J ∧ seq n ∈ 𝔪 ^ n := by
    intro n
    induction n with
    | zero =>
        refine ⟨by rw [hseq0]; exact hxJ, ?_⟩
        rw [pow_zero, Ideal.one_eq_top]
        exact Submodule.mem_top
    | succ n ih =>
        have h := haa n (seq n) ih.1 ih.2
        exact ⟨by rw [hseqs]; exact h.2.1, by rw [hseqs]; exact h.2.2⟩
  have hstep : ∀ n u, aa n (seq n) u ∈ 𝔪 ^ (n - dd u) :=
    fun n u => (haa n (seq n) (hinv n).1 (hinv n).2).1 u
  set SS : {x // x ∈ t} → ℕ → A :=
    fun u T => ∑ n ∈ Finset.range T, aa n (seq n) u with hSSdef
  have hSseq : ∀ T, x - ∑ u, SS u T * cc u = seq T := by
    intro T
    induction T with
    | zero => simp [hSSdef, hseq0]
    | succ T ih =>
        have hterm : ∀ u : {x // x ∈ t},
            SS u (T + 1) * cc u = SS u T * cc u + aa T (seq T) u * cc u := by
          intro u
          rw [hSSdef]
          simp only [Finset.sum_range_succ]
          ring
        rw [Finset.sum_congr rfl fun u _ => hterm u, Finset.sum_add_distrib,
          hseqs, ← ih]
        ring
  have hcauchy : ∀ (u : {x // x ∈ t}) {m n : ℕ}, m ≤ n →
      SS u (n + dd u) - SS u (m + dd u) ∈ 𝔪 ^ m := by
    intro u m n hmn
    have hrw : SS u (n + dd u) - SS u (m + dd u)
        = ∑ i ∈ Finset.Ico (m + dd u) (n + dd u), aa i (seq i) u := by
      rw [hSSdef]
      rw [Finset.sum_Ico_eq_sub _ (by omega : m + dd u ≤ n + dd u)]
    rw [hrw]
    refine Ideal.sum_mem _ fun i hi => ?_
    simp only [Finset.mem_Ico] at hi
    exact Ideal.pow_le_pow_right (by omega) (hstep i u)
  have hlim : ∀ u : {x // x ∈ t}, ∃ L : A, ∀ n, SS u (n + dd u) - L ∈ 𝔪 ^ n := by
    intro u
    obtain ⟨L, hL⟩ := IsPrecomplete.prec (inferInstance : IsPrecomplete 𝔪 A)
      (f := fun n => SS u (n + dd u))
      (fun {m n} hmn => by
        simp only [SModEq.sub_mem, smul_eq_mul, Ideal.mul_top]
        have h := hcauchy u hmn
        simpa using neg_mem h)
    refine ⟨L, fun n => ?_⟩
    have h := hL n
    simpa [SModEq.sub_mem, smul_eq_mul, Ideal.mul_top] using h
  choose L hL using hlim
  set D : ℕ := Finset.univ.sup dd with hDdef
  have hzero : x - ∑ u, L u * cc u = 0 := by
    refine IsHausdorff.haus (inferInstance : IsHausdorff 𝔪 A) _ fun N => ?_
    simp only [SModEq.zero, smul_eq_mul, Ideal.mul_top]
    have hsp : x - ∑ u, L u * cc u
        = (x - ∑ u, SS u (N + D) * cc u) + ∑ u, (SS u (N + D) - L u) * cc u := by
      have hterm : ∀ u : {x // x ∈ t}, (SS u (N + D) - L u) * cc u
          = SS u (N + D) * cc u - L u * cc u := fun u => by ring
      rw [Finset.sum_congr rfl fun u _ => hterm u, Finset.sum_sub_distrib]
      ring
    rw [hsp, hSseq (N + D)]
    refine Ideal.add_mem _ (Ideal.pow_le_pow_right (by omega) (hinv (N + D)).2)
      (Ideal.sum_mem _ fun u _ => ?_)
    have h1 : SS u (N + D) - L u ∈ 𝔪 ^ (N + D - dd u) := by
      have h := hL u (N + D - dd u)
      rwa [Nat.sub_add_cancel
        (le_trans (Finset.le_sup (Finset.mem_univ u)) (Nat.le_add_left D N))] at h
    have h2 := Ideal.mul_mem_mul h1 (hccM u)
    rw [← pow_add] at h2
    exact Ideal.pow_le_pow_right (by omega) h2
  rw [sub_eq_zero] at hzero
  rw [hzero]
  refine Ideal.sum_mem _ fun u _ => Ideal.mul_mem_left _ _ (Ideal.subset_span ?_)
  exact Finset.mem_coe.mpr (Finset.mem_image_of_mem cc (Finset.mem_univ u))

end CompleteLocalNoetherian
