/-
GaloisRepresentation/HardlyRamified/ProfiniteLocal.lean — own work for
the Fermat project (not vendored from the FLT project).

# Adic rings with finite adic quotients are COMPACT, and what that buys

This module supplies the topological keystone that Carayol's Théorème 1
turned out to need in `Deformation.lean`, and that mathlib does not have:

> a topological ring whose topology is the `I`-adic one, which is
> `I`-adically precomplete, and all of whose quotients `A ⧸ Iⁿ` are
> finite, is a COMPACT space.

Applied to `I = 𝔪` in a complete Noetherian local ring with FINITE
residue field — which is exactly the coefficient ring of an object of
Mazur's deformation category over a finite residue field `k` — it says
that such a ring is profinite. That is the property that makes the
Carayol ring theory work, because it converts *closed* into *compact*.

Mathlib already has the consequences of compactness for ideals
(`Mathlib/Topology/Algebra/Ring/Compact.lean`: `Ideal.isCompact_of_fg`,
`IsNoetherianRing.isClosed_ideal`, `IsLocalRing.isOpen_maximalIdeal_pow`)
but nothing that PRODUCES a compact ring from adic completeness; a search
of `Mathlib/RingTheory/AdicCompletion/`,
`Mathlib/Topology/Algebra/Nonarchimedean/` and
`Mathlib/Topology/Algebra/Ring/` (2026-07-26) finds no occurrence of
`CompactSpace` together with `IsAdicComplete`.

The compactness proof is by ultrafilters, which avoids all uniform-space
plumbing: an ultrafilter `F` on `A` pushes forward to an ultrafilter on
each FINITE quotient `A ⧸ Iⁿ`, hence is principal there, which pins a
compatible sequence of residues `bₙ`; adic precompleteness assembles the
`bₙ` into a single `L`, and the cosets `L + Iⁿ` — a neighbourhood basis of
`L` by `IsAdic` — all belong to `F`, i.e. `F → L`.

Two consequences are proven here, both of them of the same shape ("a
decreasing family of compact sets with empty intersection is eventually
empty") and both consumed by the Carayol cluster of `Deformation.lean`:

* `exists_le_of_antitone_of_isOpen` is **Chevalley's theorem** (Matsumura,
  *Commutative Ring Theory*, Thm 8.9): a decreasing sequence of CLOSED
  ideals with zero intersection is eventually inside any given OPEN ideal.
  In `Deformation.lean` it turns finite generation of Carayol's `𝔪'` into
  his Lemme 1 — the comparison of the subspace filtration `𝔪ᵐ ∩ R'` with
  the `𝔪'`-adic one.
* `fg_comap_of_uniform_span` is the finite-generation transfer: if the
  induced ideal `I ∩ C` of a closed subring `C` can be generated by `r`
  elements modulo `Iⁿ` for every `n`, with `r` NOT depending on `n`, then
  it is generated by `r` elements outright. The compactness of the space
  of `r`-tuples is what lets the level-wise generating sets — which have
  no reason to be compatible with each other — be replaced by a single
  one. This is the step that would fail for a merely complete `C`, and it
  is what makes the Carayol arithmetic input a purely *uniform* statement
  with no coherence clause.
-/
module

public import Mathlib.RingTheory.AdicCompletion.Basic
public import Mathlib.Topology.Algebra.Nonarchimedean.AdicTopology
public import Mathlib.Topology.Algebra.Ring.Compact
public import Mathlib.Topology.Algebra.Module.Compact
public import Mathlib.RingTheory.Ideal.Quotient.Index
public import Mathlib.Order.Filter.Ultrafilter.Basic

@[expose] public section

namespace ProfiniteLocal

open Topology Filter

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

/-- **The cosets of the powers of `I` are a neighbourhood basis** in the
`I`-adic topology (PROVEN, elementary): translate
`IsAdic.hasBasis_nhds_zero` by `x`. -/
lemma hasBasis_nhds_adic {I : Ideal A} (hadic : IsAdic I) (x : A) :
    (𝓝 x).HasBasis (fun _ : ℕ => True) (fun n => {y : A | y - x ∈ I ^ n}) := by
  have heq : ∀ n : ℕ, (fun y => x + y) '' ((I ^ n : Ideal A) : Set A) =
      {y : A | y - x ∈ I ^ n} := by
    intro n
    ext y
    simp only [Set.mem_image, Set.mem_setOf_eq, SetLike.mem_coe]
    constructor
    · rintro ⟨w, hw, rfl⟩
      simpa using hw
    · intro hy
      exact ⟨y - x, hy, by ring⟩
  have hmap := hadic.hasBasis_nhds_zero.map (fun y => x + y)
  rw [show Filter.map (fun y => x + y) (𝓝 (0 : A)) = 𝓝 x from by
    rw [map_add_left_nhds, add_zero]] at hmap
  simpa only [heq] using hmap

/-- **Approximation by a set gives membership in its closure** (PROVEN,
elementary): if `x` is congruent to some element of `s` modulo `Iⁿ` for
every `n`, then `x` lies in the closure of `s`. -/
lemma mem_closure_of_forall_sub_mem {I : Ideal A} (hadic : IsAdic I)
    {s : Set A} {x : A} (hx : ∀ n : ℕ, ∃ y ∈ s, x - y ∈ I ^ n) :
    x ∈ closure s := by
  rw [mem_closure_iff_nhds_basis (hasBasis_nhds_adic hadic x)]
  intro n _
  obtain ⟨y, hy, hxy⟩ := hx n
  refine ⟨y, hy, ?_⟩
  show y - x ∈ I ^ n
  rw [show y - x = -(x - y) from by ring]
  exact neg_mem hxy

omit [TopologicalSpace A] [IsTopologicalRing A] in
/-- **The level-`n` residue of an ultrafilter** (PROVEN, elementary): if
`A ⧸ Iⁿ` is finite then some coset `b + Iⁿ` belongs to any ultrafilter
`F` on `A` — push `F` forward to the finite quotient, where every
ultrafilter is principal, and lift the resulting point. -/
lemma exists_coset_mem_of_finite_quotient {I : Ideal A} (F : Ultrafilter A)
    (n : ℕ) (hfin : Finite (A ⧸ I ^ n)) :
    ∃ b : A, {x : A | x - b ∈ I ^ n} ∈ F := by
  haveI := hfin
  obtain ⟨y, hy⟩ := (F.map (Ideal.Quotient.mk (I ^ n))).eq_pure_of_finite
  obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective y
  refine ⟨b, ?_⟩
  have hmem : (Ideal.Quotient.mk (I ^ n)) ⁻¹'
      {Ideal.Quotient.mk (I ^ n) b} ∈ F := by
    have : ({Ideal.Quotient.mk (I ^ n) b} : Set (A ⧸ I ^ n)) ∈
        F.map (Ideal.Quotient.mk (I ^ n)) := by
      rw [hy]
      exact rfl
    exact this
  refine mem_of_superset hmem fun x hx => ?_
  have : Ideal.Quotient.mk (I ^ n) x = Ideal.Quotient.mk (I ^ n) b := hx
  exact (Ideal.Quotient.eq).mp this

/-- **An adically topologized, adically precomplete ring with finite adic
quotients is compact** (the keystone of this module; see the module
docstring). -/
theorem compactSpace_of_isAdic_of_finite_quotient {I : Ideal A}
    (hadic : IsAdic I) [IsPrecomplete I A]
    (hfin : ∀ n : ℕ, Finite (A ⧸ I ^ n)) : CompactSpace A := by
  constructor
  rw [isCompact_iff_ultrafilter_le_nhds]
  intro F _
  -- the level-`n` residues of `F`
  choose b hb using fun n : ℕ => exists_coset_mem_of_finite_quotient F n (hfin n)
  -- they are compatible: two members of an ultrafilter meet
  have hcompat : ∀ {m n : ℕ}, m ≤ n → b m - b n ∈ I ^ m := by
    intro m n hmn
    obtain ⟨x, hxn, hxm⟩ := Filter.nonempty_of_mem
      (Filter.inter_mem (hb n) (hb m))
    have hxn' : x - b n ∈ I ^ m := Ideal.pow_le_pow_right hmn hxn
    rw [show b m - b n = (x - b n) - (x - b m) from by ring]
    exact Ideal.sub_mem _ hxn' hxm
  -- precompleteness assembles them into a single limit point
  obtain ⟨L, hL⟩ := IsPrecomplete.prec' (I := I) (M := A) b (fun {m n} hmn => by
    rw [SModEq.sub_mem, smul_eq_mul, Ideal.mul_top]
    exact hcompat hmn)
  have hL' : ∀ n : ℕ, b n - L ∈ I ^ n := by
    intro n
    have h := hL n
    rw [SModEq.sub_mem, smul_eq_mul, Ideal.mul_top] at h
    exact h
  refine ⟨L, Set.mem_univ L, ?_⟩
  -- the cosets `L + Iⁿ` are a neighbourhood basis of `L`, and all lie in `F`
  rw [(hasBasis_nhds_adic hadic L).ge_iff]
  intro n _
  refine mem_of_superset (hb n) fun x hx => ?_
  show x - L ∈ I ^ n
  rw [show x - L = (x - b n) + (b n - L) from by ring]
  exact Ideal.add_mem _ hx (hL' n)

omit [IsTopologicalRing A] in
/-- **Chevalley's theorem, via compactness**: in a compact Hausdorff
topological ring, a decreasing sequence of CLOSED ideals whose
intersection is trivial is eventually contained in every open ideal.

The sets `J n \ I` are a decreasing sequence of compact sets; if none
were empty their intersection would be nonempty, and any point of it
would be a nonzero element of every `J n`.

(In a Noetherian ring the closedness hypothesis is automatic —
`IsNoetherianRing.isClosed_ideal` — but the application in
`Deformation.lean` is to the filtration induced on a subring by an ideal
of the ambient ring, whose members are closed for the much cheaper
reason that they are preimages of closed sets.) -/
theorem exists_le_of_antitone_of_isOpen [CompactSpace A] [T2Space A]
    {J : ℕ → Ideal A} (hanti : Antitone J)
    (hJcl : ∀ n, IsClosed ((J n : Ideal A) : Set A))
    (hbot : ∀ x : A, (∀ n, x ∈ J n) → x = 0)
    {I : Ideal A} (hI : IsOpen (I : Set A)) : ∃ m, J m ≤ I := by
  by_contra hcon
  push Not at hcon
  set K : ℕ → Set A := fun n => (J n : Set A) \ (I : Set A) with hK
  have hne : ∀ n, (K n).Nonempty := by
    intro n
    obtain ⟨x, hx1, hx2⟩ := Set.not_subset.mp (hcon n)
    exact ⟨x, hx1, hx2⟩
  have hcl : ∀ n, IsClosed (K n) := fun n => (hJcl n).sdiff hI
  have hsub : ∀ n, K (n + 1) ⊆ K n :=
    fun n => Set.sdiff_subset_sdiff_left (hanti (Nat.le_succ n))
  obtain ⟨x, hx⟩ :=
    IsCompact.nonempty_iInter_of_sequence_nonempty_isCompact_isClosed
      K hsub hne ((hcl 0).isCompact) hcl
  rw [Set.mem_iInter] at hx
  have hx0 : x = 0 := hbot x fun n => (hx n).1
  exact (hx 0).2 (hx0 ▸ I.zero_mem)

/-- **Uniform level-wise generation gives finite generation** (see the
module docstring): let `C` be a CLOSED subring of a compact Hausdorff
`I`-adic ring `A`, and suppose that for every `n` the induced ideal
`I ∩ C` of `C` is generated, modulo `Iⁿ ∩ C`, by `r` elements of `I ∩ C`
— with the SAME `r` for every `n`, but with no compatibility required
between the level-`n` generating sets. Then `I ∩ C` is generated by `r`
elements.

The point is that no coherence has to be assumed. The set `Sₙ` of
`r`-tuples that generate modulo `Iⁿ ∩ C` is determined by the residues of
the tuple modulo `Iⁿ ∩ C` alone, hence is a union of cosets of the OPEN
subgroup `(Iⁿ ∩ C)ʳ` and so is clopen; the `Sₙ` decrease and are
nonempty, so compactness of `Cʳ` gives a tuple lying in all of them at
once. Its span is a finitely generated, hence compact, hence closed ideal
that is dense in `I ∩ C`, so it IS `I ∩ C`. -/
theorem fg_comap_of_uniform_span [CompactSpace A] [T2Space A] {I : Ideal A}
    (hadic : IsAdic I) (C : Subring A) (hC : IsClosed (C : Set A)) {r : ℕ}
    (hspan : ∀ n : ℕ, ∃ z : Fin r → C,
      Ideal.span (Set.range z) ≤ Ideal.comap C.subtype I ∧
      Ideal.comap C.subtype I ≤
        Ideal.span (Set.range z) ⊔ Ideal.comap C.subtype (I ^ n)) :
    (Ideal.comap C.subtype I).FG := by
  classical
  haveI : CompactSpace C := isCompact_iff_compactSpace.mp hC.isCompact
  set J : Ideal C := Ideal.comap C.subtype I with hJdef
  set F : ℕ → Ideal C := fun n => Ideal.comap C.subtype (I ^ n) with hFdef
  have hFanti : Antitone F := fun p q hpq =>
    Ideal.comap_mono (Ideal.pow_le_pow_right hpq)
  have hFle : ∀ n : ℕ, F (n + 1) ≤ J :=
    fun n => Ideal.comap_mono (Ideal.pow_le_self (Nat.succ_ne_zero n))
  have hFopen : ∀ n : ℕ, IsOpen ((F n : Ideal C) : Set C) := fun n =>
    ((isAdic_iff.mp hadic).1 n).preimage continuous_subtype_val
  -- the `r`-tuples generating `J` modulo `F (n+1)`
  set S : ℕ → Set (Fin r → C) := fun n =>
    {z | Ideal.span (Set.range z) ≤ J ∧
      J ≤ Ideal.span (Set.range z) ⊔ F (n + 1)} with hSdef
  have hSne : ∀ n, (S n).Nonempty := fun n => hspan (n + 1)
  have hSanti : ∀ n, S (n + 1) ⊆ S n := by
    intro n z hz
    exact ⟨hz.1, hz.2.trans (sup_le_sup_left
      (hFanti (Nat.succ_le_succ (Nat.le_succ n))) _)⟩
  -- membership of `S n` only depends on the tuple modulo `F (n+1)`
  have hSdet : ∀ (n : ℕ) (z w : Fin r → C), z ∈ S n →
      (∀ i, w i - z i ∈ F (n + 1)) → w ∈ S n := by
    intro n z w hz hzw
    have hsw : ∀ i, w i ∈ Ideal.span (Set.range z) ⊔ F (n + 1) := by
      intro i
      rw [show w i = z i + (w i - z i) from by ring]
      exact Ideal.add_mem _
        (Submodule.mem_sup_left (Ideal.subset_span ⟨i, rfl⟩))
        (Submodule.mem_sup_right (hzw i))
    have hkey : Ideal.span (Set.range w) ⊔ F (n + 1) =
        Ideal.span (Set.range z) ⊔ F (n + 1) := by
      refine le_antisymm (sup_le ?_ le_sup_right) (sup_le ?_ le_sup_right)
      · rw [Ideal.span_le]
        rintro _ ⟨i, rfl⟩
        exact hsw i
      · rw [Ideal.span_le]
        rintro _ ⟨i, rfl⟩
        rw [show z i = w i + -(w i - z i) from by ring]
        exact Ideal.add_mem _
          (Submodule.mem_sup_left (Ideal.subset_span ⟨i, rfl⟩))
          (Submodule.mem_sup_right (neg_mem (hzw i)))
    refine ⟨?_, ?_⟩
    · rw [Ideal.span_le]
      rintro _ ⟨i, rfl⟩
      rw [show w i = z i + (w i - z i) from by ring]
      exact Ideal.add_mem _ (hz.1 (Ideal.subset_span ⟨i, rfl⟩)) (hFle n (hzw i))
    · rw [hkey]
      exact hz.2
  -- a set saturated under congruence modulo `F (n+1)` is open
  have hsat : ∀ (n : ℕ) (T : Set (Fin r → C)),
      (∀ z w, z ∈ T → (∀ i, w i - z i ∈ F (n + 1)) → w ∈ T) → IsOpen T := by
    intro n T hT
    rw [isOpen_iff_mem_nhds]
    intro z hz
    have hopen : IsOpen {w : Fin r → C | ∀ i, w i - z i ∈ F (n + 1)} := by
      rw [show {w : Fin r → C | ∀ i, w i - z i ∈ F (n + 1)} =
          ⋂ i : Fin r, (fun w : Fin r → C => w i - z i) ⁻¹'
            ((F (n + 1) : Ideal C) : Set C) from by
        ext w
        simp only [Set.mem_setOf_eq, Set.mem_iInter, Set.mem_preimage,
          SetLike.mem_coe]]
      exact isOpen_iInter_of_finite fun i =>
        (hFopen (n + 1)).preimage ((continuous_apply i).sub continuous_const)
    refine Filter.mem_of_superset (hopen.mem_nhds ?_) fun w hw => hT z w hz hw
    intro i
    simp
  have hSclosed : ∀ n, IsClosed (S n) := by
    intro n
    rw [← isOpen_compl_iff]
    refine hsat n _ fun z w hz hzw hw => hz ?_
    refine hSdet n w z hw fun i => ?_
    rw [show z i - w i = -(w i - z i) from by ring]
    exact neg_mem (hzw i)
  -- one tuple generating at every level at once
  obtain ⟨z, hz⟩ :=
    IsCompact.nonempty_iInter_of_sequence_nonempty_isCompact_isClosed
      S hSanti hSne ((hSclosed 0).isCompact) hSclosed
  rw [Set.mem_iInter] at hz
  -- its span is closed, and dense in `J`
  have hspanfg : (Ideal.span (Set.range z)).FG :=
    Submodule.fg_span (Set.finite_range z)
  have himgclosed : IsClosed (Subtype.val ''
      ((Ideal.span (Set.range z) : Ideal C) : Set C)) :=
    ((Ideal.isCompact_of_fg hspanfg).image continuous_subtype_val).isClosed
  have hge : J ≤ Ideal.span (Set.range z) := by
    intro x hx
    have hcl : (x : A) ∈ closure (Subtype.val ''
        ((Ideal.span (Set.range z) : Ideal C) : Set C)) := by
      refine mem_closure_of_forall_sub_mem hadic fun n => ?_
      obtain ⟨s, hs, t, ht, hst⟩ := Submodule.mem_sup.mp ((hz n).2 hx)
      refine ⟨(s : A), ⟨s, hs, rfl⟩, ?_⟩
      rw [show (x : A) - (s : A) = (t : A) from by rw [← hst]; push_cast; ring]
      exact Ideal.pow_le_pow_right (Nat.le_succ n) ht
    rw [himgclosed.closure_eq] at hcl
    obtain ⟨y, hy, hyx⟩ := hcl
    exact (Subtype.ext hyx : y = x) ▸ hy
  refine ⟨(Finset.univ : Finset (Fin r)).image z, ?_⟩
  rw [Finset.coe_image, Finset.coe_univ, Set.image_univ]
  exact le_antisymm (hz 0).1 hge

end ProfiniteLocal
