/-
TateSepClosure.lean — own work for the Fermat project.

# Tate's uniformisation over a separable closure

The Ω-level (separable-closure) part of the Tate uniformisation,
moved out of `TateCurve.lean` (2026-07-18) so that it can consume the
finite-level uniformisation machinery of `TateUniformization.lean`
(which sits above `TateCurve.lean` in the import graph): the
pre-quotient uniformising homomorphism `Ωˣ →+ E_q(Ω)` (derived below
from the finite-level equivalence `TateCurve.tateCurveEquiv` through
the sorried gluing implication), the quotient form `Ωˣ/q^ℤ ≃+ E_q(Ω)`,
the transport to a general curve `E` with split multiplicative
reduction, the torsion analysis, and the inertia-unipotence theorems.
-/
module

public import Fermat.FLT.KnownIn1980s.EllipticCurves.TateCurve
public import Fermat.FLT.KnownIn1980s.EllipticCurves.TateUniformization
public import Mathlib.RingTheory.Valuation.RamificationGroup
-- `ValuationSubring.inertia_fixes_of_pow_eq_one` (step (b)) and the good-reduction
-- framework, used in the local unipotence assembly
import Fermat.FLT.KnownIn1980s.EllipticCurves.GoodReduction
import Mathlib.AlgebraicGeometry.EllipticCurve.NormalForms
import Mathlib.RingTheory.Henselian
import Fermat.FLT.Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
import Fermat.FLT.Mathlib.AlgebraicGeometry.EllipticCurve.VariableChange

@[expose] public section

open scoped WeierstrassCurve.Affine -- `(E⁄k).Point` notation for the group of `k`-points
open ValuativeRel -- `𝒪[k]` notation for the ring of integers of `k`, and `valuation`

-- Can be deleted when mathlib#41391 lands
set_option linter.overlappingInstances false

-- let k be a nonarchimedean local field
variable {k : Type*} [Field k] [ValuativeRel k] [TopologicalSpace k]
  [IsNonarchimedeanLocalField k]

-- let E/k be elliptic with split multiplicative reduction, minimal
variable (E : WeierstrassCurve k) [E.IsElliptic] [E.HasSplitMultiplicativeReduction 𝒪[k]]
  [E.IsMinimal 𝒪[k]]

/-! ### Tate's uniformisation over a separable closure

Passing to the limit over the finite subextensions of a separable closure `Ω` of `k`, the
finite-level uniformisations `E(l) ≅ lˣ/qᶻ` glue to a Galois-equivariant uniformisation
`E(Ω) ≅ Ωˣ/qᶻ`. The `N`-torsion of `Ωˣ/qᶻ` is generated by the `N`-th roots of unity and
(the classes of) the `N`-th roots of `q`, so the uniformisation identifies the `N`-torsion
of `E` explicitly: this is how one computes the Galois representations attached to `E`.

The statement below is an existential Prop (see the vendoring note in the module
docstring): the isomorphism is pinned down mathematically only up to a sign (the choice
of one of the two isomorphisms `E_{q(E)} ≅ E`), and no consumer needs a canonical
choice — only existence of an equivariant one.
-/

-- Now let `Ω` be a separable closure of `k`. It is not itself a nonarchimedean local field
-- (it is not complete), so it does not fit the framework above; but `E(Ω)` is the union of
-- the `E(l)` over the finite subextensions `l/k` of `Ω`, and Tate's theory applies to each.
-- (`Ω` is placed in a NAMED universe so that the finite-level hypothesis of the gluing
-- implication below can quantify over fields in the same universe — the intermediate
-- fields of `Ω/k` — keeping the universe inferable at the application site.)
universe uΩ
variable (Ω : Type uΩ) [Field Ω] [Algebra k Ω] [IsSepClosed Ω] [Algebra.IsSeparable k Ω]

-- the base change of E to Ω is elliptic (same remark as for `l` above)
instance : (E.baseChange Ω).IsElliptic :=
  inferInstanceAs (E.map (algebraMap k Ω)).IsElliptic

/-- The image of the Tate parameter in a separable closure `Ω` of `k`, as a unit. (`Ω` is
not a nonarchimedean local field, so this is not literally `(E.baseChange Ω).qUnit`.) -/
noncomputable def WeierstrassCurve.qUnitSepClosure : Ωˣ :=
  Units.map (algebraMap k Ω).toMonoidHom E.qUnit

-- `DecidableEq Ω` is needed for the group law on `(E⁄Ω).Point`
variable [DecidableEq Ω]

set_option warn.sorry false in
/-- **The gluing implication for Tate's uniformisation** (sorry node —
Ω-level from finite level): GIVEN the finite-level canonical
uniformisation — for every nonarchimedean local field `l` an additive
equivalence `lˣ/q^ℤ ≃+ E_q(l)` whose underlying function is the
canonical (choice-free) `TateCurve.pointMapQuot` — the uniformising
homomorphism over the separable closure `Ω` exists: `Ωˣ →+ E_q(Ω)`,
surjective, with kernel exactly `q^ℤ`, commuting with every
`k`-automorphism of `Ω`. Content of the (sorried) gluing: every
`u ∈ Ωˣ` and every point of `E_q(Ω)` lives in a finite subextension
`l/k` of `Ω/k`; a finite extension of a nonarchimedean local field is a
nonarchimedean local field with a unique valuative extension structure,
so the hypothesis applies at each level; the resulting maps are
compatible with the inclusions `l ⊆ l'` and with the `σ`-twists because
the underlying function `pointMapQuot` is defined by universal series
independent of the field (naturality of the annulus-representative
point map under valuative embeddings), so they glue to `Ωˣ` and the
kernel/surjectivity/equivariance properties pass to the colimit. -/
theorem WeierstrassCurve.exists_tateCurveHomSepClosure_of_finiteLevel
    [CharZero k] (q : kˣ) (hq : valuation k (q : k) < 1)
    (hfin : ∀ (l : Type uΩ) [Field l] [ValuativeRel l] [TopologicalSpace l]
      [IsNonarchimedeanLocalField l] [CharZero l] [DecidableEq l] (ql : lˣ)
      (hql : valuation l (ql : l) < 1),
      ∃ e : Additive (lˣ ⧸ Subgroup.zpowers ql) ≃+
          (WeierstrassCurve.tateCurve ((ql : l) : l)).toAffine.Point,
        ∀ x, e x = TateCurve.pointMapQuot ql hql x.toMul) :
    ∃ φ : Additive Ωˣ →+ (((tateCurve ((q : k) : k))⁄Ω)).Point,
      Function.Surjective φ ∧
      (∀ u : Ωˣ, φ (Additive.ofMul u) = 0 ↔
        u ∈ Subgroup.zpowers (Units.map (algebraMap k Ω).toMonoidHom q)) ∧
      (∀ (σ : Ω ≃ₐ[k] Ω) (u : Ωˣ),
        WeierstrassCurve.Affine.Point.map (W' := tateCurve ((q : k) : k))
            σ.toAlgHom (φ (Additive.ofMul u)) =
          φ (Additive.ofMul (Units.map σ.toAlgHom.toRingHom.toMonoidHom u))) :=
  sorry

/-- **The Tate-curve uniformising homomorphism over a separable closure**
(derived 2026-07-18 by feeding the finite-level uniformisation
`TateCurve.tateCurveEquiv` — canonical, with underlying function
`pointMapQuot`, from `TateUniformization.lean` — into the gluing
implication above): for a unit `q` of `k` with `|q| < 1` there is a
surjective group homomorphism `Ωˣ → E_q(Ω)` with kernel exactly `q^ℤ`,
commuting with every `k`-algebra automorphism of `Ω` ON THE NOSE. -/
theorem WeierstrassCurve.exists_tateCurveHomSepClosure [CharZero k] (q : kˣ)
    (hq : valuation k (q : k) < 1) :
    ∃ φ : Additive Ωˣ →+ (((tateCurve ((q : k) : k))⁄Ω)).Point,
      Function.Surjective φ ∧
      (∀ u : Ωˣ, φ (Additive.ofMul u) = 0 ↔
        u ∈ Subgroup.zpowers (Units.map (algebraMap k Ω).toMonoidHom q)) ∧
      (∀ (σ : Ω ≃ₐ[k] Ω) (u : Ωˣ),
        WeierstrassCurve.Affine.Point.map (W' := tateCurve ((q : k) : k))
            σ.toAlgHom (φ (Additive.ofMul u)) =
          φ (Additive.ofMul (Units.map σ.toAlgHom.toRingHom.toMonoidHom u))) :=
  WeierstrassCurve.exists_tateCurveHomSepClosure_of_finiteLevel Ω q hq
    (fun _l _ _ _ _ _ _ ql hql =>
      ⟨TateCurve.tateCurveEquiv ql hql,
        fun x => TateCurve.tateCurveEquiv_apply ql hql x⟩)

/-- **Tate's uniformisation of the TATE CURVE over a separable closure**
(derived 2026-07-18 from the pre-quotient homomorphism
`exists_tateCurveHomSepClosure` by the first isomorphism theorem): for a
unit `q` of `k` with `|q| < 1`, the points of the Tate curve `E_q` over
a separable closure `Ω` are `Ωˣ/q^ℤ`, Galois-equivariantly ON THE NOSE.
The uniformising homomorphism `Ωˣ → E_q(Ω)` is surjective with kernel
`q^ℤ`, so it descends to an isomorphism on the quotient; equivariance
descends along the quotient map. -/
theorem WeierstrassCurve.exists_tateCurveEquivSepClosure [CharZero k] (q : kˣ)
    (hq : valuation k (q : k) < 1) :
    ∃ e : Additive (Ωˣ ⧸ Subgroup.zpowers
        (Units.map (algebraMap k Ω).toMonoidHom q)) ≃+
      (((tateCurve ((q : k) : k))⁄Ω)).Point,
      ∀ (σ : Ω ≃ₐ[k] Ω) (u : Ωˣ),
        WeierstrassCurve.Affine.Point.map (W' := tateCurve ((q : k) : k))
            σ.toAlgHom (e (Additive.ofMul ↑u)) =
          e (Additive.ofMul ↑(Units.map σ.toAlgHom.toRingHom.toMonoidHom u)) := by
  obtain ⟨φ, hφsurj, hφker, hφequiv⟩ :=
    WeierstrassCurve.exists_tateCurveHomSepClosure (k := k) Ω q hq
  -- the multiplicative form of `φ`, as a `MonoidHom` out of `Ωˣ`
  let ψ : Ωˣ →* Multiplicative ((((tateCurve ((q : k) : k))⁄Ω)).Point) :=
    { toFun := fun u => Multiplicative.ofAdd (φ (Additive.ofMul u))
      map_one' := by simp
      map_mul' := fun u v => by simp }
  -- `q^ℤ` is contained in the kernel, so `ψ` descends to the quotient
  have hZle : Subgroup.zpowers (Units.map (algebraMap k Ω).toMonoidHom q) ≤
      ψ.ker := by
    intro z hz
    exact (hφker z).mpr hz
  let ψbar : (Ωˣ ⧸ Subgroup.zpowers
      (Units.map (algebraMap k Ω).toMonoidHom q)) →*
      Multiplicative ((((tateCurve ((q : k) : k))⁄Ω)).Point) :=
    QuotientGroup.lift _ ψ hZle
  -- the descended map is injective (kernel of `φ` is exactly `q^ℤ`) …
  have hinj : Function.Injective ψbar := by
    rw [injective_iff_map_eq_one]
    intro x hx
    induction x using QuotientGroup.induction_on with
    | H u =>
      rw [QuotientGroup.eq_one_iff]
      exact (hφker u).mp hx
  -- … and surjective (because `φ` is)
  have hsurj : Function.Surjective ψbar := by
    intro p
    obtain ⟨a, ha⟩ := hφsurj (Multiplicative.toAdd p)
    refine ⟨((Additive.toMul a : Ωˣ) : Ωˣ ⧸ Subgroup.zpowers
      (Units.map (algebraMap k Ω).toMonoidHom q)), ?_⟩
    show Multiplicative.ofAdd (φ (Additive.ofMul (Additive.toMul a))) = p
    simp [ha]
  -- assemble the additive equivalence out of the multiplicative bijection
  refine ⟨MulEquiv.toAdditiveLeft
    (MulEquiv.ofBijective ψbar ⟨hinj, hsurj⟩), fun σ u => ?_⟩
  -- on the class of `u` the equivalence evaluates to `φ (ofMul u)`,
  -- so equivariance is exactly the equivariance of `φ`
  exact hφequiv σ u

omit [E.IsMinimal 𝒪[k]] in
set_option backward.isDefEq.respectTransparency false in
set_option synthInstance.maxHeartbeats 400000 in
set_option maxHeartbeats 1000000 in
/-- **Tate's uniformisation theorem over a separable closure** (derived
2026-07-17 from the choice-free Tate-curve uniformisation above and
Tate's theorem `exists_variableChange_tateCurve`): for `E/k`
an elliptic curve, in minimal Weierstrass form, with split multiplicative reduction
over a nonarchimedean local field `k`, and `Ω` a separable closure of `k`, there is a
group isomorphism `Ωˣ/q(E)ᶻ ≅ E(Ω)` that is equivariant for the natural actions of
`Gal(Ω/k)` on both sides (Silverman, ATAEC V.3.1 + V.5.3: glue the finite-level
uniformisations `E(l) ≅ lˣ/qᶻ` over the finite subextensions `l/k` of `Ω`; the
`k`-linearity of every `σ ∈ Gal(Ω/k)` makes the sign choice `σ`-stable, cf.
`tateEquiv_galois` in the upstream FLT file). Stated as an existential Prop because
the isomorphism is canonical only up to negation. -/
theorem WeierstrassCurve.exists_tateEquivSepClosure [CharZero k] :
    ∃ e : Additive (Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω)) ≃+ ((E⁄Ω)).Point,
      ∀ (σ : Ω ≃ₐ[k] Ω) (u : Ωˣ),
        WeierstrassCurve.Affine.Point.map (W' := E) σ.toAlgHom (e (Additive.ofMul ↑u)) =
          e (Additive.ofMul ↑(Units.map σ.toAlgHom.toRingHom.toMonoidHom u)) := by
  classical
  obtain ⟨C, hC⟩ := E.exists_variableChange_tateCurve
  obtain ⟨e₀, he₀⟩ := WeierstrassCurve.exists_tateCurveEquivSepClosure (k := k) Ω
    E.qUnit E.valuation_q_lt_one
  -- the `Ω`-stage curve equality behind the variable change
  have hEq : (E⁄Ω) = (C.baseChange Ω) •
      ((tateCurve ((E.qUnit : k) : k))⁄Ω) := by
    conv_lhs => rw [← hC]
    exact (baseChange_smul_baseChange _ _ _).symm
  haveI hTell : (((tateCurve ((E.qUnit : k) : k))⁄Ω)).IsElliptic := by
    haveI h1 : ((C.baseChange Ω) •
        ((tateCurve ((E.qUnit : k) : k))⁄Ω)).IsElliptic := by
      rw [← hEq]
      infer_instance
    have h2 : ((C.baseChange Ω)⁻¹ • ((C.baseChange Ω) •
        ((tateCurve ((E.qUnit : k) : k))⁄Ω))).IsElliptic := inferInstance
    rw [inv_smul_smul] at h2
    exact h2
  let Ψ : ((E⁄Ω)).Point ≃+ (((tateCurve ((E.qUnit : k) : k))⁄Ω)).Point :=
    (Affine.Point.equivOfEq hEq).trans
      (Affine.Point.equivVariableChange
        ((tateCurve ((E.qUnit : k) : k))⁄Ω) (C.baseChange Ω))
  have hΨapp : ∀ R : ((E⁄Ω)).Point, Ψ R =
      (Affine.Point.equivVariableChange
        ((tateCurve ((E.qUnit : k) : k))⁄Ω) (C.baseChange Ω))
      ((Affine.Point.equivOfEq hEq) R) := fun R => rfl
  refine ⟨e₀.trans Ψ.symm, ?_⟩
  intro σ u
  -- σ fixes the base-changed variable-change data (it is `k`-rational)
  have hσu : σ.toAlgHom (((C.baseChange Ω).u : Ω)) = ((C.baseChange Ω).u : Ω) := by
    simp only [VariableChange.baseChange, VariableChange.map, Units.coe_map,
      MonoidHom.coe_coe]
    exact σ.toAlgHom.commutes _
  have hσr : σ.toAlgHom (C.baseChange Ω).r = (C.baseChange Ω).r := by
    simp only [VariableChange.baseChange, VariableChange.map]
    exact σ.toAlgHom.commutes _
  have hσs : σ.toAlgHom (C.baseChange Ω).s = (C.baseChange Ω).s := by
    simp only [VariableChange.baseChange, VariableChange.map]
    exact σ.toAlgHom.commutes _
  have hσt : σ.toAlgHom (C.baseChange Ω).t = (C.baseChange Ω).t := by
    simp only [VariableChange.baseChange, VariableChange.map]
    exact σ.toAlgHom.commutes _
  -- equivariance of `Ψ` under `σ`
  have h12 : ∀ Q : ((E⁄Ω)).Point,
      Ψ (WeierstrassCurve.Affine.Point.map (W' := E) σ.toAlgHom Q) =
      WeierstrassCurve.Affine.Point.map (W' := tateCurve ((E.qUnit : k) : k))
        σ.toAlgHom (Ψ Q) := by
    intro Q
    rw [hΨapp, hΨapp]
    cases Q with
    | zero => simp [← WeierstrassCurve.Affine.Point.zero_def]
    | some x y hxy =>
      rw [WeierstrassCurve.Affine.Point.map_some,
        WeierstrassCurve.Affine.Point.equivOfEq_some,
        WeierstrassCurve.Affine.Point.equivOfEq_some,
        WeierstrassCurve.Affine.Point.equivVariableChange_some,
        WeierstrassCurve.Affine.Point.equivVariableChange_some,
        WeierstrassCurve.Affine.Point.map_some]
      refine WeierstrassCurve.Affine.Point.some_eq_some _ ?_ ?_
      · simp only [map_add, map_mul, map_pow, hσu, hσr]
      · simp only [map_add, map_mul, map_pow, hσu, hσs, hσt]
  have h12' : ∀ R : (((tateCurve ((E.qUnit : k) : k))⁄Ω)).Point,
      Ψ.symm (WeierstrassCurve.Affine.Point.map
        (W' := tateCurve ((E.qUnit : k) : k)) σ.toAlgHom R) =
      WeierstrassCurve.Affine.Point.map (W' := E) σ.toAlgHom (Ψ.symm R) := by
    intro R
    apply Ψ.injective
    rw [Ψ.apply_symm_apply, h12, Ψ.apply_symm_apply]
  show WeierstrassCurve.Affine.Point.map (W' := E) σ.toAlgHom
      (Ψ.symm (e₀ (Additive.ofMul ↑u))) =
      Ψ.symm (e₀ (Additive.ofMul
        ↑(Units.map σ.toAlgHom.toRingHom.toMonoidHom u)))
  rw [← h12', he₀]

/-- **Representatives of torsion in the Tate quotient** (PROVEN — pure
group theory): every `N`-torsion class of `Gˣ/q^ℤ` is represented by an
element whose `N`-th power is an integer power of `q`. This is step (a)
of the derivation of the multiplicative-reduction inertia statements
from `exists_tateEquivSepClosure`. -/
theorem exists_rep_pow_eq_zpow_of_torsion {G : Type*} [CommGroup G]
    (q : G) {N : ℕ} (t : Additive (G ⧸ Subgroup.zpowers q))
    (ht : ((N : ℤ)) • t = 0) :
    ∃ (u : G) (a : ℤ),
      Additive.ofMul ((u : G ⧸ Subgroup.zpowers q)) = t ∧ u ^ N = q ^ a := by
  obtain ⟨u, hu⟩ := QuotientGroup.mk_surjective (Additive.toMul t)
  have h1 : ((u : G ⧸ Subgroup.zpowers q)) ^ N = 1 := by
    have h2 := congrArg Additive.toMul ht
    rw [toMul_zsmul, toMul_zero, zpow_natCast] at h2
    rw [hu]
    exact h2
  have h3 : (u ^ N : G) ∈ Subgroup.zpowers q := by
    rw [← QuotientGroup.eq_one_iff, QuotientGroup.mk_pow]
    exact h1
  obtain ⟨a, ha⟩ := Subgroup.mem_zpowers_iff.mp h3
  exact ⟨u, a, by rw [hu, ofMul_toMul], ha.symm⟩

/-- **The inertia-difference of a Tate-parameter root is a root of
unity** (PROVEN): if `σ` fixes `u^N`, then `σ(u)·u⁻¹` is an `N`-th root
of unity. Step (c) of the multiplicative-reduction derivation: for a
torsion representative `u` with `u^N = q_E^a`, every `σ ∈ Gal(Ω/k)`
fixes `u^N` (the Tate parameter comes from the base field), so `σ`
moves `u` by at most an `N`-th root of unity. -/
theorem map_mul_inv_mem_rootsOfUnity_of_pow_fixed
    {k Ω : Type*} [Field k] [Field Ω] [Algebra k Ω]
    (σ : Ω ≃ₐ[k] Ω) (u : Ωˣ) {N : ℕ}
    (hfix : Units.map σ.toAlgHom.toRingHom.toMonoidHom (u ^ N) = u ^ N) :
    Units.map σ.toAlgHom.toRingHom.toMonoidHom u * u⁻¹ ∈
      rootsOfUnity N Ω := by
  rw [mem_rootsOfUnity]
  calc (Units.map σ.toAlgHom.toRingHom.toMonoidHom u * u⁻¹) ^ N
      = Units.map σ.toAlgHom.toRingHom.toMonoidHom (u ^ N) * (u ^ N)⁻¹ := by
        rw [mul_pow, map_pow, inv_pow]
    _ = 1 := by rw [hfix, mul_inv_cancel]

omit [E.IsMinimal 𝒪[k]] [IsSepClosed Ω] [Algebra.IsSeparable k Ω]
  [DecidableEq Ω] in
/-- Every `k`-automorphism of `Ω` fixes the Tate parameter (PROVEN): it
comes from the base field. -/
theorem WeierstrassCurve.map_qUnitSepClosure_eq (σ : Ω ≃ₐ[k] Ω) :
    Units.map σ.toAlgHom.toRingHom.toMonoidHom (E.qUnitSepClosure Ω) =
      E.qUnitSepClosure Ω := by
  apply Units.ext
  show σ ((algebraMap k Ω) E.q) = (algebraMap k Ω) E.q
  exact σ.commutes E.q

omit [E.IsMinimal 𝒪[k]] [IsSepClosed Ω] [Algebra.IsSeparable k Ω]
  [DecidableEq Ω] in
/-- Every `k`-automorphism of `Ω` fixes all integer powers of the Tate
parameter (PROVEN). -/
theorem WeierstrassCurve.map_zpow_qUnitSepClosure_eq (σ : Ω ≃ₐ[k] Ω)
    (a : ℤ) :
    Units.map σ.toAlgHom.toRingHom.toMonoidHom (E.qUnitSepClosure Ω ^ a) =
      E.qUnitSepClosure Ω ^ a := by
  rw [map_zpow, E.map_qUnitSepClosure_eq]

omit [E.IsMinimal 𝒪[k]] [IsSepClosed Ω] [Algebra.IsSeparable k Ω]
  [DecidableEq Ω] in
/-- **Integer powers of the Tate parameter are distinct** (PROVEN): the
Tate parameter has valuation strictly less than `1` in the base field,
so `a ↦ q^a` is injective — the class group `Ωˣ/q^ℤ` is a genuine
`ℤ`-quotient. -/
theorem WeierstrassCurve.qUnitSepClosure_zpow_injective :
    Function.Injective (fun a : ℤ => E.qUnitSepClosure Ω ^ a) := by
  intro a b hab
  -- descend to `k` along the injective algebra map
  have h1 : E.qUnit ^ a = E.qUnit ^ b := by
    have h2 : Units.map (algebraMap k Ω).toMonoidHom (E.qUnit ^ a) =
        Units.map (algebraMap k Ω).toMonoidHom (E.qUnit ^ b) := by
      rw [map_zpow, map_zpow]
      exact hab
    apply Units.ext
    have h3 := congrArg Units.val h2
    exact (algebraMap k Ω).injective h3
  -- valuation freeness in `k`
  have h4 := congrArg (fun w : kˣ => valuation k ((w : k))) h1
  rw [Units.val_zpow_eq_zpow_val, Units.val_zpow_eq_zpow_val,
    map_zpow₀, map_zpow₀] at h4
  exact zpow_right_injective₀
    (zero_lt_iff.mpr ((valuation k).ne_zero_iff.mpr E.q_ne_zero))
    (ne_of_lt E.valuation_q_lt_one) h4

set_option backward.isDefEq.respectTransparency false in
set_option maxHeartbeats 1000000 in
omit [E.IsMinimal 𝒪[k]] [Algebra.IsSeparable k Ω] in
/-- **The Tate valuation-exponent quotient on `p`-torsion** (PROVEN
over any uniformization witness): the `p`-torsion of a Tate-uniformized
curve surjects `Galois-invariantly` onto `ℤ/p` by the exponent of the
Tate parameter in the `p`-th power of any representative — the
quotient of the filtration `0 → μ_p → E[p] → ℤ/p → 0`. Since every
`k`-automorphism fixes the Tate parameter, the quotient carries the
TRIVIAL `Gal(Ω/k)`-action; this is the split-case content of the
tame-quotient condition at `2`. Surjectivity requires a `p`-th root of
the Tate parameter, which exists in the separably closed `Ω` when
`p ≠ 0` there. -/
theorem WeierstrassCurve.exists_tateTorsionQuotient
    (e : Additive (Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω)) ≃+ ((E⁄Ω)).Point)
    (he : ∀ (σ : Ω ≃ₐ[k] Ω) (u : Ωˣ),
      WeierstrassCurve.Affine.Point.map (W' := E) σ.toAlgHom (e (Additive.ofMul ↑u)) =
        e (Additive.ofMul ↑(Units.map σ.toAlgHom.toRingHom.toMonoidHom u)))
    {p : ℕ} (hp : p ≠ 0) (hpΩ : ((p : ℕ) : Ω) ≠ 0) :
    ∃ π : AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ) →+ ZMod p,
      Function.Surjective π ∧
      ∀ (σ : Ω ≃ₐ[k] Ω)
        (P Q : AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ)),
        (Q : ((E⁄Ω)).Point) =
          WeierstrassCurve.Affine.Point.map (W' := E) σ.toAlgHom
            (P : ((E⁄Ω)).Point) →
        π Q = π P := by
  classical
  -- torsion transfers to the quotient side
  have htors : ∀ P : AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ),
      ((p : ℕ) : ℤ) • (e.symm (P : ((E⁄Ω)).Point)) = 0 := fun P => by
    rw [← map_zsmul e.symm,
      (show ((p : ℕ) : ℤ) • (P : ((E⁄Ω)).Point) = 0 from P.2), map_zero]
  -- choose a representative and exponent for each torsion point
  choose u a hu ha using fun P : AddSubgroup.torsionBy ((E⁄Ω)).Point
      ((p : ℕ) : ℤ) =>
    exists_rep_pow_eq_zpow_of_torsion (E.qUnitSepClosure Ω)
      (e.symm (P : ((E⁄Ω)).Point)) (htors P)
  -- the exponent is independent of the representative, mod `p`
  have hindep : ∀ (P : AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ))
      (v : Ωˣ) (b : ℤ),
      Additive.ofMul ((v : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) =
        e.symm (P : ((E⁄Ω)).Point) →
      v ^ p = E.qUnitSepClosure Ω ^ b →
      ((b : ZMod p)) = ((a P : ZMod p)) := by
    intro P v b hv hvb
    have h1 : ((u P : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) =
        ((v : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) :=
      Additive.ofMul.injective ((hu P).trans hv.symm)
    obtain ⟨m, hm⟩ := Subgroup.mem_zpowers_iff.mp (QuotientGroup.eq.mp h1)
    -- `v = u P * q^m`
    have h2 : v = u P * E.qUnitSepClosure Ω ^ m := by
      rw [hm]
      group
    have h3 : E.qUnitSepClosure Ω ^ b =
        E.qUnitSepClosure Ω ^ (a P + m * (p : ℤ)) := by
      rw [← hvb, h2, mul_pow, ha P, ← zpow_natCast
        (E.qUnitSepClosure Ω ^ m) p, ← zpow_mul, ← zpow_add]
    have h4 : b = a P + m * (p : ℤ) :=
      E.qUnitSepClosure_zpow_injective Ω h3
    rw [h4]
    push_cast
    simp
  -- the exponent function and its additivity
  have hadd : ∀ P Q : AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ),
      ((a (P + Q) : ZMod p)) = ((a P : ZMod p)) + ((a Q : ZMod p)) := by
    intro P Q
    have hclass : Additive.ofMul (((u P * u Q : Ωˣ) :
        Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) =
        e.symm ((P + Q : AddSubgroup.torsionBy ((E⁄Ω)).Point
          ((p : ℕ) : ℤ)) : ((E⁄Ω)).Point) := by
      rw [show ((P + Q : AddSubgroup.torsionBy ((E⁄Ω)).Point
          ((p : ℕ) : ℤ)) : ((E⁄Ω)).Point) =
          (P : ((E⁄Ω)).Point) + (Q : ((E⁄Ω)).Point) from rfl,
        map_add e.symm, ← hu P, ← hu Q, QuotientGroup.mk_mul, ofMul_mul]
    have hpow : (u P * u Q) ^ p =
        E.qUnitSepClosure Ω ^ (a P + a Q) := by
      rw [mul_pow, ha P, ha Q, ← zpow_add]
    have := hindep (P + Q) (u P * u Q) (a P + a Q) hclass hpow
    rw [← this]
    push_cast
    ring
  let π : AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ) →+ ZMod p :=
    AddMonoidHom.mk' (fun P => ((a P : ZMod p))) hadd
  refine ⟨π, ?_, ?_⟩
  · -- surjectivity: a `p`-th root of the Tate parameter has exponent `1`
    have hq0 : (algebraMap k Ω) E.q ≠ 0 := by
      simp only [map_ne_zero]
      exact E.q_ne_zero
    obtain ⟨x, hx⟩ := IsSepClosed.exists_root
      (Polynomial.X ^ p - Polynomial.C ((algebraMap k Ω) E.q))
      (by
        rw [Polynomial.degree_X_pow_sub_C (Nat.pos_of_ne_zero hp)]
        exact_mod_cast Nat.pos_of_ne_zero hp |>.ne')
      (Polynomial.separable_X_pow_sub_C _ hpΩ hq0)
    have hxpow : x ^ p = (algebraMap k Ω) E.q := by
      have h1 := hx
      rw [Polynomial.IsRoot, Polynomial.eval_sub, Polynomial.eval_pow,
        Polynomial.eval_X, Polynomial.eval_C, sub_eq_zero] at h1
      exact h1
    have hx0 : x ≠ 0 := by
      intro h0
      rw [h0, zero_pow hp] at hxpow
      exact hq0 hxpow.symm
    set xu : Ωˣ := Units.mk0 x hx0 with hxu
    have hxupow : xu ^ p = E.qUnitSepClosure Ω ^ (1 : ℤ) := by
      apply Units.ext
      rw [Units.val_pow_eq_pow_val, Units.val_zpow_eq_zpow_val, zpow_one]
      exact hxpow
    -- the corresponding torsion point
    have htor : ((p : ℕ) : ℤ) • (e (Additive.ofMul ((xu :
        Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))))) = 0 := by
      rw [← map_zsmul e, ← ofMul_zpow, ← QuotientGroup.mk_zpow,
        zpow_natCast, hxupow]
      rw [show ((E.qUnitSepClosure Ω ^ (1 : ℤ) :
          Ωˣ) : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω)) = 1 from
        (QuotientGroup.eq_one_iff _).mpr (Subgroup.zpow_mem _
          (Subgroup.mem_zpowers _) _), ofMul_one, map_zero]
    set P₁ : AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ) :=
      ⟨e (Additive.ofMul ((xu : Ωˣ ⧸ Subgroup.zpowers
        (E.qUnitSepClosure Ω)))), htor⟩ with hP₁
    have hπ1 : π P₁ = 1 := by
      have hclass : Additive.ofMul ((xu : Ωˣ ⧸ Subgroup.zpowers
          (E.qUnitSepClosure Ω))) = e.symm ((P₁ :
          ((E⁄Ω)).Point)) := by
        rw [hP₁]
        exact (e.symm_apply_apply _).symm
      have := hindep P₁ xu 1 hclass hxupow
      rw [show π P₁ = ((a P₁ : ZMod p)) from rfl, ← this]
      norm_num
    -- `1` generates `ZMod p`
    haveI : NeZero p := ⟨hp⟩
    intro c
    refine ⟨c.val • P₁, ?_⟩
    rw [map_nsmul, hπ1, nsmul_eq_mul, mul_one, ZMod.natCast_val,
      ZMod.cast_id]
  · -- Galois invariance: `σ`-images have the same exponent
    intro σ P Q hQ
    have hclass : Additive.ofMul
        ((Units.map σ.toAlgHom.toRingHom.toMonoidHom (u P) :
          Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) =
        e.symm ((Q : ((E⁄Ω)).Point)) := by
      apply e.injective
      rw [e.apply_symm_apply, ← he, hQ]
      congr 1
      rw [hu P, e.apply_symm_apply]
    have hpow : (Units.map σ.toAlgHom.toRingHom.toMonoidHom (u P)) ^ p =
        E.qUnitSepClosure Ω ^ (a P) := by
      rw [← map_pow, ha P, map_zpow_qUnitSepClosure_eq]
    exact (hindep Q _ _ hclass hpow).symm

set_option backward.isDefEq.respectTransparency false in
set_option maxHeartbeats 1000000 in
omit [E.IsMinimal 𝒪[k]] [IsSepClosed Ω] [Algebra.IsSeparable k Ω] in
/-- **Local unipotence of inertia on Tate torsion** (PROVEN 2026-07-17,
assembling steps (a), (b), (c) over ANY witness of the uniformization):
given a Galois-equivariant Tate uniformization `e` of `E` over `Ω` and
a valuation subring `A` of `Ω` whose residue characteristic does not
divide `p`, every element of the inertia subgroup of `A` acts
unipotently on the `p`-torsion: `σ(σP) − σP − σP + P = 0`. The torsion
class is represented by `u` with `u^p = q_E^a` (step (a)); every
`k`-automorphism fixes `q_E^a`, so `σ(u)/u =: ζ` is a `p`-th root of
unity (step (c)) and `σP − P = e[ζ]`; inertia fixes `ζ` (step (b)), so
a second application of `σ − 1` kills `e[ζ]`. -/
theorem WeierstrassCurve.tate_inertia_unipotent
    (e : Additive (Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω)) ≃+ ((E⁄Ω)).Point)
    (he : ∀ (σ : Ω ≃ₐ[k] Ω) (u : Ωˣ),
      WeierstrassCurve.Affine.Point.map (W' := E) σ.toAlgHom (e (Additive.ofMul ↑u)) =
        e (Additive.ofMul ↑(Units.map σ.toAlgHom.toRingHom.toMonoidHom u)))
    (A : ValuationSubring Ω) {p : ℕ} (hp : p ≠ 0)
    (hchar : ((p : ℕ) : IsLocalRing.ResidueField A) ≠ 0)
    (σ : A.decompositionSubgroup k) (hσ : σ ∈ A.inertiaSubgroup k)
    (P : ((E⁄Ω)).Point)
    (hP : P ∈ AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ)) :
    WeierstrassCurve.Affine.Point.map (W' := E)
        ((σ : Ω ≃ₐ[k] Ω)).toAlgHom
        (WeierstrassCurve.Affine.Point.map (W' := E)
          ((σ : Ω ≃ₐ[k] Ω)).toAlgHom P) -
      WeierstrassCurve.Affine.Point.map (W' := E)
        ((σ : Ω ≃ₐ[k] Ω)).toAlgHom P -
      WeierstrassCurve.Affine.Point.map (W' := E)
        ((σ : Ω ≃ₐ[k] Ω)).toAlgHom P + P = 0 := by
  classical
  -- pull the torsion class back through `e`
  set t : Additive (Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω)) :=
    e.symm P with ht
  have hPt : e t = P := e.apply_symm_apply P
  have httor : ((p : ℕ) : ℤ) • t = 0 := by
    have h1 : ((p : ℕ) : ℤ) • P = 0 := hP
    rw [ht, ← map_zsmul e.symm, h1, map_zero]
  obtain ⟨u, a, hut, hupow⟩ :=
    exists_rep_pow_eq_zpow_of_torsion (E.qUnitSepClosure Ω) t httor
  -- `σ` moves `u` by the root of unity `ζ`
  have hfixpow : Units.map ((σ : Ω ≃ₐ[k] Ω)).toAlgHom.toRingHom.toMonoidHom
      (u ^ p) = u ^ p := by
    rw [hupow]
    exact E.map_zpow_qUnitSepClosure_eq Ω (σ : Ω ≃ₐ[k] Ω) a
  have hζmem : Units.map ((σ : Ω ≃ₐ[k] Ω)).toAlgHom.toRingHom.toMonoidHom u
      * u⁻¹ ∈ rootsOfUnity p Ω :=
    map_mul_inv_mem_rootsOfUnity_of_pow_fixed (σ : Ω ≃ₐ[k] Ω) u hfixpow
  set ζ : Ωˣ := Units.map ((σ : Ω ≃ₐ[k] Ω)).toAlgHom.toRingHom.toMonoidHom u
    * u⁻¹ with hζ
  -- inertia fixes `ζ`
  have hζpow : (ζ : Ω) ^ p = 1 := by
    have h1 : ζ ^ p = 1 := hζmem
    have h2 := congrArg Units.val h1
    rwa [Units.val_pow_eq_pow_val, Units.val_one] at h2
  have hσζ : Units.map ((σ : Ω ≃ₐ[k] Ω)).toAlgHom.toRingHom.toMonoidHom ζ =
      ζ := by
    apply Units.ext
    show (σ : Ω ≃ₐ[k] Ω) (ζ : Ω) = (ζ : Ω)
    exact A.inertia_fixes_of_pow_eq_one hp hchar σ hσ hζpow
  -- `σP = P + e[ζ]`
  have hσu : Units.map ((σ : Ω ≃ₐ[k] Ω)).toAlgHom.toRingHom.toMonoidHom u =
      ζ * u := by
    rw [hζ, inv_mul_cancel_right]
  have hstep : ∀ Q : ((E⁄Ω)).Point,
      Q = e (Additive.ofMul (↑u : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) →
      WeierstrassCurve.Affine.Point.map (W' := E)
        ((σ : Ω ≃ₐ[k] Ω)).toAlgHom Q =
      e (Additive.ofMul (↑(ζ * u) : Ωˣ ⧸ Subgroup.zpowers
        (E.qUnitSepClosure Ω))) := by
    intro Q hQ
    rw [hQ, he (σ : Ω ≃ₐ[k] Ω) u, hσu]
  have hPu : P = e (Additive.ofMul (↑u : Ωˣ ⧸ Subgroup.zpowers
      (E.qUnitSepClosure Ω))) := by
    rw [hut, hPt]
  have hσP : WeierstrassCurve.Affine.Point.map (W' := E)
      ((σ : Ω ≃ₐ[k] Ω)).toAlgHom P =
      e (Additive.ofMul (↑(ζ * u) : Ωˣ ⧸ Subgroup.zpowers
        (E.qUnitSepClosure Ω))) := hstep P hPu
  -- `σ(σP) = σP + e[σζ] − ... = e[ζ·ζ·u]`? — apply equivariance again
  have hσσP : WeierstrassCurve.Affine.Point.map (W' := E)
      ((σ : Ω ≃ₐ[k] Ω)).toAlgHom
      (WeierstrassCurve.Affine.Point.map (W' := E)
        ((σ : Ω ≃ₐ[k] Ω)).toAlgHom P) =
      e (Additive.ofMul (↑(ζ * (ζ * u)) : Ωˣ ⧸ Subgroup.zpowers
        (E.qUnitSepClosure Ω))) := by
    rw [hσP, he (σ : Ω ≃ₐ[k] Ω) (ζ * u)]
    congr 2
    rw [map_mul, hσζ, hσu]
  -- assemble in the additive quotient
  have h₂ : (Additive.ofMul (↑(ζ * u) : Ωˣ ⧸ Subgroup.zpowers
      (E.qUnitSepClosure Ω))) =
      Additive.ofMul ((ζ : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) +
      Additive.ofMul ((u : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) := by
    rw [QuotientGroup.mk_mul, ofMul_mul]
  have h₁ : (Additive.ofMul (↑(ζ * (ζ * u)) : Ωˣ ⧸ Subgroup.zpowers
      (E.qUnitSepClosure Ω))) =
      Additive.ofMul ((ζ : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) +
      (Additive.ofMul ((ζ : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) +
       Additive.ofMul ((u : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω)))) := by
    rw [QuotientGroup.mk_mul, ofMul_mul, h₂]
  rw [hσσP, hσP, hPu, h₁, h₂, map_add, map_add]
  abel

set_option backward.isDefEq.respectTransparency false in
set_option maxHeartbeats 1000000 in
omit [E.IsMinimal 𝒪[k]] [IsSepClosed Ω] [Algebra.IsSeparable k Ω] in
/-- **Local triviality of inertia on Tate torsion when the parameter is
a `p`-th power up to units** (steps (a)+(b′)+(d) over any witness of
the uniformization): if `q_E · w⁻ᵖ` is a unit of the valuation subring
`A` (with nonzero residue) for some `w ∈ kˣ`, then every inertia
element FIXES the `p`-torsion pointwise. The torsion class is
represented by `u` with `uᵖ = q_Eᵃ`; then `x := u·w⁻ᵃ` satisfies
`xᵖ = (q_E·w⁻ᵖ)ᵃ`, a `σ`-fixed unit constant of `A`, so inertia fixes
`x` (`inertia_fixes_of_pow_eq`), hence `u`, hence the point. -/
theorem WeierstrassCurve.tate_inertia_trivial
    (e : Additive (Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω)) ≃+ ((E⁄Ω)).Point)
    (he : ∀ (σ : Ω ≃ₐ[k] Ω) (u : Ωˣ),
      WeierstrassCurve.Affine.Point.map (W' := E) σ.toAlgHom (e (Additive.ofMul ↑u)) =
        e (Additive.ofMul ↑(Units.map σ.toAlgHom.toRingHom.toMonoidHom u)))
    (A : ValuationSubring Ω) {p : ℕ} (hp : p ≠ 0)
    (hchar : ((p : ℕ) : IsLocalRing.ResidueField A) ≠ 0)
    (σ : A.decompositionSubgroup k) (hσ : σ ∈ A.inertiaSubgroup k)
    (w : kˣ)
    (hcA : algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k)) ∈ A)
    (hcres : IsLocalRing.residue A
      (⟨algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k)), hcA⟩ : A) ≠ 0)
    (P : ((E⁄Ω)).Point)
    (hP : P ∈ AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ)) :
    WeierstrassCurve.Affine.Point.map (W' := E)
      ((σ : Ω ≃ₐ[k] Ω)).toAlgHom P = P := by
  classical
  set t : Additive (Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω)) :=
    e.symm P with ht
  have hPt : e t = P := e.apply_symm_apply P
  have httor : ((p : ℕ) : ℤ) • t = 0 := by
    have h1 : ((p : ℕ) : ℤ) • P = 0 := hP
    rw [ht, ← map_zsmul e.symm, h1, map_zero]
  obtain ⟨u, a, hut, hupow⟩ :=
    exists_rep_pow_eq_zpow_of_torsion (E.qUnitSepClosure Ω) t httor
  -- the recentred representative `x := u · wΩ⁻ᵃ` and its constant power
  set wΩ : Ωˣ := Units.map (algebraMap k Ω).toMonoidHom w with hwΩ
  have h1 : (u * wΩ⁻¹ ^ a) ^ (p : ℤ) =
      (Units.map (algebraMap k Ω).toMonoidHom (E.qUnit * w⁻¹ ^ p)) ^ a := by
    calc (u * wΩ⁻¹ ^ a) ^ (p : ℤ)
        = u ^ (p : ℤ) * (wΩ⁻¹ ^ a) ^ (p : ℤ) := mul_zpow _ _ _
      _ = u ^ p * (wΩ⁻¹ ^ a) ^ (p : ℤ) := by rw [zpow_natCast]
      _ = E.qUnitSepClosure Ω ^ a * (wΩ⁻¹ ^ a) ^ (p : ℤ) := by rw [hupow]
      _ = E.qUnitSepClosure Ω ^ a * (wΩ⁻¹ ^ (p : ℤ)) ^ a := by
          rw [← zpow_mul, ← zpow_mul, mul_comm a ((p : ℤ))]
      _ = E.qUnitSepClosure Ω ^ a * (wΩ⁻¹ ^ p) ^ a := by rw [zpow_natCast]
      _ = (E.qUnitSepClosure Ω * wΩ⁻¹ ^ p) ^ a := (mul_zpow _ _ _).symm
      _ = (Units.map (algebraMap k Ω).toMonoidHom (E.qUnit * w⁻¹ ^ p)) ^ a := by
          congr 1
          rw [map_mul, map_pow, map_inv, ← hwΩ]
          rfl
  have hxpow : ((u * wΩ⁻¹ ^ a : Ωˣ) : Ω) ^ p =
      (algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a := by
    calc ((u * wΩ⁻¹ ^ a : Ωˣ) : Ω) ^ p
        = (((u * wΩ⁻¹ ^ a) ^ p : Ωˣ) : Ω) :=
          (Units.val_pow_eq_pow_val _ _).symm
      _ = (((u * wΩ⁻¹ ^ a) ^ (p : ℤ) : Ωˣ) : Ω) := by rw [zpow_natCast]
      _ = (((Units.map (algebraMap k Ω).toMonoidHom
            (E.qUnit * w⁻¹ ^ p)) ^ a : Ωˣ) : Ω) := by rw [h1]
      _ = ((Units.map (algebraMap k Ω).toMonoidHom
            (E.qUnit * w⁻¹ ^ p) : Ωˣ) : Ω) ^ a :=
          Units.val_zpow_eq_zpow_val _ _
      _ = (algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a := rfl
  -- the constant power is `σ`-fixed (it comes from the base field)
  have hσc : (σ : Ω ≃ₐ[k] Ω)
      ((algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a) =
      (algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a := by
    rw [map_zpow₀]
    congr 1
    exact (σ : Ω ≃ₐ[k] Ω).commutes _
  -- the constant is a unit of `A`, so its integer powers stay in `A`
  have hcunit : IsUnit (⟨algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k)),
      hcA⟩ : A) := by
    by_contra hnu
    exact hcres (Ideal.Quotient.eq_zero_iff_mem.mpr
      ((IsLocalRing.mem_maximalIdeal _).mpr hnu))
  have hcoe : (((hcunit.unit ^ a : Aˣ) : A) : Ω) =
      (algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a := by
    calc (((hcunit.unit ^ a : Aˣ) : A) : Ω)
        = ((Units.map A.subtype.toMonoidHom (hcunit.unit ^ a) : Ωˣ) : Ω) := rfl
      _ = (((Units.map A.subtype.toMonoidHom hcunit.unit) ^ a : Ωˣ) : Ω) := by
          rw [map_zpow]
      _ = ((Units.map A.subtype.toMonoidHom hcunit.unit : Ωˣ) : Ω) ^ a :=
          Units.val_zpow_eq_zpow_val _ _
      _ = (((hcunit.unit : A) : Ω)) ^ a := rfl
      _ = (algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a := by
          rw [hcunit.unit_spec]
  have hcApow : (algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a ∈ A :=
    hcoe ▸ SetLike.coe_mem _
  have hcrespow : IsLocalRing.residue A
      (⟨(algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a, hcApow⟩ : A) ≠
      0 := by
    rw [show (⟨(algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a,
        hcApow⟩ : A) = ((hcunit.unit ^ a : Aˣ) : A) from Subtype.ext hcoe.symm]
    exact ((hcunit.unit ^ a).isUnit.map (IsLocalRing.residue A)).ne_zero
  -- inertia fixes the recentred representative (step (b′))
  have hfix : (σ : Ω ≃ₐ[k] Ω) ((u * wΩ⁻¹ ^ a : Ωˣ) : Ω) =
      ((u * wΩ⁻¹ ^ a : Ωˣ) : Ω) :=
    A.inertia_fixes_of_pow_eq hp hchar σ hσ hcApow hcrespow hσc hxpow
  -- `σ` fixes `wΩ` (it comes from the base field), hence fixes `u`
  have hσw : Units.map ((σ : Ω ≃ₐ[k] Ω)).toAlgHom.toRingHom.toMonoidHom wΩ =
      wΩ := by
    apply Units.ext
    show (σ : Ω ≃ₐ[k] Ω) ((wΩ : Ωˣ) : Ω) = ((wΩ : Ωˣ) : Ω)
    exact (σ : Ω ≃ₐ[k] Ω).commutes w
  have h5 : (u * wΩ⁻¹ ^ a) * wΩ ^ a = u := by
    rw [inv_zpow, inv_mul_cancel_right]
  have hσu : Units.map ((σ : Ω ≃ₐ[k] Ω)).toAlgHom.toRingHom.toMonoidHom u =
      u := by
    rw [← h5, map_mul, map_zpow, hσw]
    congr 1
    apply Units.ext
    exact hfix
  -- conclude: the point itself is fixed
  rw [← hPt, ← hut, he (σ : Ω ≃ₐ[k] Ω) u, hσu]
