/-
TateSepClosure.lean — own work for the Fermat project.

# Tate's uniformisation over a separable closure

The Ω-level (separable-closure) part of the Tate uniformisation,
moved out of `TateCurve.lean` (2026-07-18) so that it can consume the
finite-level uniformisation machinery of `TateUniformization.lean`
(which sits above `TateCurve.lean` in the import graph): the
pre-quotient uniformising homomorphism `Ωˣ →+ E_q(Ω)` (derived below
from the finite-level equivalence `TateCurve.tateCurveEquiv` through
the sorried gluing implication), the quotient form `Ωˣ/q^ℤ ≃+ E_q(Ω)`,
the transport to a general curve `E` with split multiplicative
reduction, the torsion analysis, and the inertia-unipotence theorems.
-/
module

public import Fermat.FLT.KnownIn1980s.EllipticCurves.TateCurve
public import Fermat.FLT.KnownIn1980s.EllipticCurves.TateUniformization
public import Mathlib.RingTheory.Valuation.RamificationGroup
-- `ValuationSubring.inertia_fixes_of_pow_eq_one` (step (b)) and the good-reduction
-- framework, used in the local unipotence assembly
import Fermat.FLT.KnownIn1980s.EllipticCurves.GoodReduction
import Mathlib.AlgebraicGeometry.EllipticCurve.NormalForms
import Mathlib.RingTheory.Henselian
import Fermat.FLT.Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
import Fermat.FLT.Mathlib.AlgebraicGeometry.EllipticCurve.VariableChange
import Fermat.FLT.Deformations.RepresentationTheory.AbsoluteGaloisGroup

@[expose] public section

open scoped WeierstrassCurve.Affine -- `(E⁄k).Point` notation for the group of `k`-points
open ValuativeRel -- `𝒪[k]` notation for the ring of integers of `k`, and `valuation`

-- Can be deleted when mathlib#41391 lands
set_option linter.overlappingInstances false

-- let k be a nonarchimedean local field
variable {k : Type*} [Field k] [ValuativeRel k] [TopologicalSpace k]
  [IsNonarchimedeanLocalField k]

-- let E/k be elliptic with split multiplicative reduction, minimal
variable (E : WeierstrassCurve k) [E.IsElliptic] [E.HasSplitMultiplicativeReduction 𝒪[k]]
  [E.IsMinimal 𝒪[k]]

/-! ### Tate's uniformisation over a separable closure

Passing to the limit over the finite subextensions of a separable closure `Ω` of `k`, the
finite-level uniformisations `E(l) ≅ lˣ/qᶻ` glue to a Galois-equivariant uniformisation
`E(Ω) ≅ Ωˣ/qᶻ`. The `N`-torsion of `Ωˣ/qᶻ` is generated by the `N`-th roots of unity and
(the classes of) the `N`-th roots of `q`, so the uniformisation identifies the `N`-torsion
of `E` explicitly: this is how one computes the Galois representations attached to `E`.

The statement below is an existential Prop (see the vendoring note in the module
docstring): the isomorphism is pinned down mathematically only up to a sign (the choice
of one of the two isomorphisms `E_{q(E)} ≅ E`), and no consumer needs a canonical
choice — only existence of an equivariant one.
-/

-- Now let `Ω` be a separable closure of `k`. It is not itself a nonarchimedean local field
-- (it is not complete), so it does not fit the framework above; but `E(Ω)` is the union of
-- the `E(l)` over the finite subextensions `l/k` of `Ω`, and Tate's theory applies to each.
-- (`Ω` is placed in a NAMED universe so that the finite-level hypothesis of the gluing
-- implication below can quantify over fields in the same universe — the intermediate
-- fields of `Ω/k` — keeping the universe inferable at the application site.)
universe uΩ
variable (Ω : Type uΩ) [Field Ω] [Algebra k Ω] [IsSepClosed Ω] [Algebra.IsSeparable k Ω]

-- the base change of E to Ω is elliptic (same remark as for `l` above)
instance : (E.baseChange Ω).IsElliptic :=
  inferInstanceAs (E.map (algebraMap k Ω)).IsElliptic

/-- The image of the Tate parameter in a separable closure `Ω` of `k`, as a unit. (`Ω` is
not a nonarchimedean local field, so this is not literally `(E.baseChange Ω).qUnit`.) -/
noncomputable def WeierstrassCurve.qUnitSepClosure : Ωˣ :=
  Units.map (algebraMap k Ω).toMonoidHom E.qUnit

-- `DecidableEq Ω` is needed for the group law on `(E⁄Ω).Point`
variable [DecidableEq Ω]

/-- Pullback of a valuative relation along a ring homomorphism:
`x ≤ᵥ y` iff `f x ≤ᵥ f y`. Used to restrict the (unique) valuative
structure of a separable closure to its finite subextensions, making the
restricted structures coherent by construction. -/
@[reducible] def ValuativeRel.comap {S R : Type*} [Semiring S] [Semiring R]
    [ValuativeRel R] (f : S →+* R) : ValuativeRel S where
  vle x y := f x ≤ᵥ f y
  vle_total x y := ValuativeRel.vle_total (f x) (f y)
  vle_trans := ValuativeRel.vle_trans
  vle_add h1 h2 := by
    rw [map_add]
    exact ValuativeRel.vle_add h1 h2
  mul_vle_mul_left h z := by
    rw [map_mul, map_mul]
    exact ValuativeRel.mul_vle_mul_left h _
  vle_mul_cancel h1 h2 := by
    rw [map_mul, map_mul] at h2
    refine ValuativeRel.vle_mul_cancel ?_ h2
    rwa [map_zero] at h1
  not_vle_one_zero := by
    rw [map_one, map_zero]
    exact ValuativeRel.not_vle_one_zero
  vle_mul_comm {x y} := by
    rw [map_mul, map_mul]
    exact ValuativeRel.vle_mul_comm

omit [IsSepClosed Ω] [DecidableEq Ω] in
/-- **The valuative structure of a separable closure** (PROVEN
2026-07-20): the valuation of a nonarchimedean local field extends to
any separable algebraic extension, in particular to `Ω` — the integral
closure of `𝒪[k]` in `Ω` is a valuation subring by the spectral-norm
dichotomy (vendored `isIntegral_of_spectralNorm_le_one` over the
rank-one `Valued` structure of `k`), and its valuation restricts to
that of `k` by integral closedness of the DVR `𝒪[k]`. -/
theorem exists_valuativeRel_sepClosure :
    ∃ v : ValuativeRel Ω, @ValuativeExtension k Ω _ _ _ v _ ∧
      ∀ (σ : Ω ≃ₐ[k] Ω) (a b : Ω),
        (@ValuativeRel.vle Ω _ v (σ a) (σ b) ↔ @ValuativeRel.vle Ω _ v a b) := by
  classical
  -- analytic structure on `k`: uniformity, rank-one valued, complete, normed
  letI : UniformSpace k := IsTopologicalAddGroup.rightUniformSpace k
  haveI : IsUniformAddGroup k := isUniformAddGroup_of_addCommGroup
  letI : (Valued.v (R := k)).RankOne :=
    { hom' := IsRankLeOne.nonempty.some.emb (R := k).comp
        MonoidWithZeroHom.ValueGroup₀.embedding
      strictMono' := IsRankLeOne.nonempty.some.strictMono.comp
        MonoidWithZeroHom.ValueGroup₀.embedding_strictMono }
  letI : NontriviallyNormedField k := Valued.toNontriviallyNormedField _ _
  haveI : Algebra.IsAlgebraic k Ω := Algebra.IsSeparable.isAlgebraic k Ω
  -- the integral closure of `𝒪[k]` in `Ω` is a valuation subring, by the
  -- spectral-norm dichotomy (vendored `isIntegral_of_spectralNorm_le_one`)
  have hdicho : ∀ x : Ω, x ∈ (integralClosure 𝒪[k] Ω).toSubring ∨
      x⁻¹ ∈ (integralClosure 𝒪[k] Ω).toSubring := fun x => by
    obtain hx | hx := le_total (spectralNorm k Ω x) 1
    · exact Or.inl (isIntegral_of_spectralNorm_le_one hx)
    · have h1 : spectralNorm k Ω x⁻¹ ≤ 1 := by
        rw [spectralNorm_inv]
        exact inv_le_one_of_one_le₀ hx
      exact Or.inr (isIntegral_of_spectralNorm_le_one h1)
  set B : ValuationSubring Ω :=
    ⟨(integralClosure 𝒪[k] Ω).toSubring, hdicho⟩ with hBdef
  letI vΩ : ValuativeRel Ω := ValuativeRel.ofValuation B.valuation
  -- membership bridge: a base-field element lands in `B` iff it is a
  -- `k`-integer (integral closedness of the DVR `𝒪[k]`)
  have hmem : ∀ c : k, algebraMap k Ω c ∈ B ↔ valuation k c ≤ 1 := by
    intro c
    constructor
    · intro hc
      have h1 : IsIntegral 𝒪[k] (algebraMap k Ω c) := hc
      have h2 : IsIntegral 𝒪[k] c :=
        (isIntegral_algebraMap_iff (algebraMap k Ω).injective).mp h1
      obtain ⟨y, hy⟩ := IsIntegrallyClosed.isIntegral_iff.mp h2
      rw [← hy]
      exact y.2
    · intro hc
      have h1 : IsIntegral 𝒪[k] ((⟨c, hc⟩ : 𝒪[k]) : k) :=
        isIntegral_algebraMap (R := 𝒪[k]) (A := k) (x := (⟨c, hc⟩ : 𝒪[k]))
      show IsIntegral 𝒪[k] (algebraMap k Ω c)
      exact (isIntegral_algebraMap_iff (algebraMap k Ω).injective).mpr h1
  -- Galois stability of the integral closure: comparisons are preserved
  have hBstab : ∀ (σ : Ω ≃ₐ[k] Ω) (x : Ω), x ∈ B → σ x ∈ B := by
    intro σ x hx
    have h1 : IsIntegral 𝒪[k] x := hx
    exact h1.map (σ.toAlgHom.restrictScalars 𝒪[k])
  have hBiff : ∀ (σ : Ω ≃ₐ[k] Ω) (x : Ω), σ x ∈ B ↔ x ∈ B := by
    intro σ x
    refine ⟨fun h => ?_, hBstab σ x⟩
    have h2 := hBstab σ.symm _ h
    rwa [AlgEquiv.symm_apply_apply] at h2
  have hσ : ∀ (σ : Ω ≃ₐ[k] Ω) (a b : Ω),
      (B.valuation (σ a) ≤ B.valuation (σ b) ↔
        B.valuation a ≤ B.valuation b) := by
    intro σ a b
    by_cases hb : b = 0
    · subst hb
      rw [map_zero, map_zero, le_zero_iff, le_zero_iff,
        Valuation.zero_iff, Valuation.zero_iff]
      exact ⟨fun h => by simpa using (map_eq_zero σ.toAlgHom.toRingHom).mp h,
        fun h => by rw [h, map_zero]⟩
    · have hσb : σ b ≠ 0 := fun h => hb (by
        simpa using (map_eq_zero σ.toAlgHom.toRingHom).mp h)
      have hbpos : (0 : _) < B.valuation b :=
        zero_lt_iff.mpr ((Valuation.ne_zero_iff _).mpr hb)
      have hσbpos : (0 : _) < B.valuation (σ b) :=
        zero_lt_iff.mpr ((Valuation.ne_zero_iff _).mpr hσb)
      rw [← div_le_one₀ hbpos, ← div_le_one₀ hσbpos,
        ← map_div₀ B.valuation, ← map_div₀ B.valuation,
        ValuationSubring.valuation_le_one_iff,
        ValuationSubring.valuation_le_one_iff,
        show σ a / σ b = σ (a / b) from (map_div₀ σ.toAlgHom.toRingHom a b).symm]
      exact hBiff σ (a / b)
  refine ⟨vΩ, ⟨fun a b => ?_⟩, fun σ a b => hσ σ a b⟩
  show B.valuation (algebraMap k Ω a) ≤ B.valuation (algebraMap k Ω b)
    ↔ a ≤ᵥ b
  rw [show (a ≤ᵥ b) ↔ valuation k a ≤ valuation k b from
    Valuation.Compatible.vle_iff_le a b]
  by_cases hb : b = 0
  · subst hb
    rw [map_zero, map_zero, map_zero, le_zero_iff, le_zero_iff,
      Valuation.zero_iff, Valuation.zero_iff]
    exact ⟨fun h => (map_eq_zero _).mp h, fun h => by rw [h, map_zero]⟩
  · have hbΩ : algebraMap k Ω b ≠ 0 := (map_ne_zero _).mpr hb
    have hbBpos : (0 : _) < B.valuation (algebraMap k Ω b) :=
      zero_lt_iff.mpr ((Valuation.ne_zero_iff _).mpr hbΩ)
    have hbkpos : (0 : _) < valuation k b :=
      zero_lt_iff.mpr ((Valuation.ne_zero_iff _).mpr hb)
    rw [← div_le_one₀ hbBpos, ← map_div₀ B.valuation, ← map_div₀,
      ValuationSubring.valuation_le_one_iff, hmem, map_div₀,
      div_le_one₀ hbkpos]

omit [TopologicalSpace k] [IsNonarchimedeanLocalField k] [IsSepClosed Ω] [Algebra.IsSeparable k Ω] [DecidableEq Ω] in
/-- The restriction of a valuative structure of `Ω` to an intermediate
field is a valuative extension of `k` (definitional unwinding through
the tower `k ⊆ L ⊆ Ω`). -/
theorem valuativeExtension_comap (v : ValuativeRel Ω)
    (hv : @ValuativeExtension k Ω _ _ _ v _) (L : IntermediateField k Ω) :
    @ValuativeExtension k L _ _ _
      (@ValuativeRel.comap L Ω _ _ v L.val.toRingHom) _ := by
  letI : ValuativeRel Ω := v
  letI : ValuativeRel L := @ValuativeRel.comap L Ω _ _ v L.val.toRingHom
  constructor
  intro a b
  show L.val.toRingHom (algebraMap k L a) ≤ᵥ
    L.val.toRingHom (algebraMap k L b) ↔ a ≤ᵥ b
  have hcomp : ∀ c : k, L.val.toRingHom (algebraMap k L c)
      = algebraMap k Ω c := fun c => by
    rw [IsScalarTower.algebraMap_apply k L Ω c]
    rfl
  rw [hcomp, hcomp]
  exact hv.vle_iff_vle a b

omit [ValuativeRel k] [TopologicalSpace k] [IsNonarchimedeanLocalField k] [IsSepClosed Ω] [Algebra.IsSeparable k Ω] [DecidableEq Ω] in
/-- The restriction is definitionally a valuative extension of `Ω`
along the inclusion. -/
theorem valuativeExtension_comap_val (v : ValuativeRel Ω)
    (L : IntermediateField k Ω) :
    @ValuativeExtension L Ω _ _
      (@ValuativeRel.comap L Ω _ _ v L.val.toRingHom) v _ := by
  letI : ValuativeRel Ω := v
  letI : ValuativeRel L := @ValuativeRel.comap L Ω _ _ v L.val.toRingHom
  exact ⟨fun a b => Iff.rfl⟩

omit [IsSepClosed Ω] [DecidableEq Ω] in
/-- **Local compactness of finite subextensions**: in its valuative
topology, a finite intermediate field `L` of `Ω/k` is locally compact.
Proof route: `hsmall` (below any nonzero value of `L` lies a nonzero
base value, by clearing denominators over `𝒪[k]` and one strict shrink)
gives Hausdorffness and continuity of the structure map, hence
`ContinuousSMul k L`; then any `k`-linear equivalence with
`k ^ finrank` is a homeomorphism (`LinearMap.continuous_of_finiteDimensional`
over the complete field `k`) and local compactness transports. -/
theorem locallyCompactSpace_intermediate
    (v : ValuativeRel Ω) (hv : @ValuativeExtension k Ω _ _ _ v _)
    (L : IntermediateField k Ω) [FiniteDimensional k L] :
    letI : ValuativeRel L := @ValuativeRel.comap L Ω _ _ v L.val.toRingHom
    @LocallyCompactSpace L (ValuativeRel.topologicalSpace L) := by
  letI vL : ValuativeRel L :=
    @ValuativeRel.comap L Ω _ _ v L.val.toRingHom
  letI tL : TopologicalSpace L := ValuativeRel.topologicalSpace L
  -- analytic structure on `k` (the LocalField.Basic recipe)
  letI : UniformSpace k := IsTopologicalAddGroup.rightUniformSpace k
  haveI : IsUniformAddGroup k := isUniformAddGroup_of_addCommGroup
  letI : (Valued.v (R := k)).RankOne :=
    { hom' := IsRankLeOne.nonempty.some.emb (R := k).comp
        MonoidWithZeroHom.ValueGroup₀.embedding
      strictMono' := IsRankLeOne.nonempty.some.strictMono.comp
        MonoidWithZeroHom.ValueGroup₀.embedding_strictMono }
  letI : NontriviallyNormedField k := Valued.toNontriviallyNormedField _ _
  haveI : Algebra.IsAlgebraic k Ω := Algebra.IsSeparable.isAlgebraic k Ω
  -- the two-sided bridge: membership in the integral closure is the
  -- closed unit ball of the spectral norm
  have hBmem : ∀ x : Ω, x ∈ integralClosure 𝒪[k] Ω ↔
      spectralNorm k Ω x ≤ 1 := by
    intro x
    constructor
    · intro hx
      have hint : IsIntegral 𝒪[k] x := hx
      rw [spectralNorm,
        spectralValue_le_one_iff
          (minpoly.monic (Algebra.IsIntegral.isIntegral x))]
      intro n
      rw [minpoly.isIntegrallyClosed_eq_field_fractions' k hint,
        Polynomial.coeff_map]
      exact Valued.toNormedField.norm_le_one_iff.mpr
        ((minpoly 𝒪[k] x).coeff n).2
    · exact isIntegral_of_spectralNorm_le_one
  -- the strict version, via multiplicativity of the inverse
  have hBmem_lt : ∀ x : Ω, x ≠ 0 →
      (x ∈ integralClosure 𝒪[k] Ω ∧ x⁻¹ ∉ integralClosure 𝒪[k] Ω ↔
        spectralNorm k Ω x < 1) := by
    intro x hx0
    rw [hBmem, hBmem, spectralNorm_inv]
    constructor
    · rintro ⟨h1, h2⟩
      rcases lt_or_eq_of_le h1 with h | h
      · exact h
      · exact absurd (by rw [h, inv_one]) h2
    · intro h
      refine ⟨le_of_lt h, ?_⟩
      intro hinv
      have hpos : 0 < spectralNorm k Ω x :=
        spectralNorm_zero_lt hx0 (Algebra.IsAlgebraic.isAlgebraic x)
      exact absurd h (not_lt.mpr ((inv_le_one₀ hpos).mp hinv))
  -- a strictly-small base element
  obtain ⟨γπ, hγπ0, hγπ1⟩ := ValuativeRel.IsNontrivial.exists_lt_one (R := k)
  obtain ⟨p, hp⟩ := ValuativeRel.valuation_surjective (K := k) γπ
  have hp0 : p ≠ 0 := by
    intro h
    rw [h, map_zero] at hp
    exact (zero_lt_iff.mp hγπ0) hp.symm
  have hpimg : valuation L (algebraMap k L p) < 1 := by
    have h1 : ¬ ((1 : k) ≤ᵥ p) := by
      rw [Valuation.Compatible.vle_iff_le (v := valuation k), map_one, hp]
      exact not_le.mpr hγπ1
    have h2 : ¬ (algebraMap k L 1 ≤ᵥ algebraMap k L p) := by
      rw [(valuativeExtension_comap (k := k) Ω v hv L).vle_iff_vle]
      exact h1
    rw [Valuation.Compatible.vle_iff_le (v := valuation L), map_one] at h2
    exact not_le.mp h2
  -- every `𝒪[k]`-integral element of `Ω` has value at most one (the
  -- classical power-comparison argument, coefficient bound through the
  -- valuative extension)
  have hkle : ∀ a : k, valuation k a ≤ 1 →
      valuation Ω (algebraMap k Ω a) ≤ 1 := by
    intro a ha
    have h1 : a ≤ᵥ (1 : k) := by
      rw [Valuation.Compatible.vle_iff_le (v := valuation k), map_one]
      exact ha
    have h2 : algebraMap k Ω a ≤ᵥ algebraMap k Ω 1 := hv.vle_iff_vle a 1 |>.mpr h1
    rw [Valuation.Compatible.vle_iff_le (v := valuation Ω), map_one] at h2
    exact h2
  have hint_le : ∀ x : Ω, IsIntegral 𝒪[k] x → valuation Ω x ≤ 1 := by
    intro x hx
    obtain ⟨f, hm, hf⟩ := hx
    by_cases hn : f.natDegree = 0
    · exfalso
      rw [Polynomial.natDegree_eq_zero] at hn
      obtain ⟨c, rfl⟩ := hn
      have hc1 : c = 1 := by
        simpa [Polynomial.Monic, Polynomial.leadingCoeff] using hm
      rw [hc1, map_one, Polynomial.eval₂_one] at hf
      exact one_ne_zero hf
    by_contra hgt
    rw [not_le] at hgt
    have hxne : valuation Ω x ^ f.natDegree ≠ 0 :=
      pow_ne_zero _ (lt_trans zero_lt_one hgt).ne'
    have h0 := hf
    rw [Polynomial.eval₂_eq_sum_range, Finset.sum_range_succ,
      hm.coeff_natDegree, map_one, one_mul] at h0
    have h1 : x ^ f.natDegree
        = -∑ i ∈ Finset.range f.natDegree,
            algebraMap 𝒪[k] Ω (f.coeff i) * x ^ i :=
      eq_neg_of_add_eq_zero_right h0
    have h2 := congrArg (valuation Ω) h1
    rw [map_pow, (valuation Ω).map_neg] at h2
    refine absurd h2.symm (ne_of_lt ((valuation Ω).map_sum_lt ?_ ?_))
    · exact hxne
    · intro i hi
      rw [Finset.mem_range] at hi
      rw [map_mul, map_pow]
      have hcoeff : valuation Ω (algebraMap 𝒪[k] Ω (f.coeff i)) ≤ 1 := by
        rw [IsScalarTower.algebraMap_apply 𝒪[k] k Ω]
        exact hkle _ (f.coeff i).2
      exact mul_lt_of_le_one_of_lt hcoeff (pow_lt_pow_right₀ hgt hi)
  -- every element of `k` is algebraic over `𝒪[k]` (valuation-ring
  -- dichotomy), hence so is every element of `Ω`
  haveI hOk : Algebra.IsAlgebraic 𝒪[k] k := by
    constructor
    intro c
    by_cases hc : valuation k c ≤ 1
    · exact isAlgebraic_algebraMap (⟨c, hc⟩ : 𝒪[k])
    · have hc0 : c ≠ 0 := by
        intro h
        rw [h, map_zero] at hc
        exact hc zero_le
      have hcinv : valuation k c⁻¹ ≤ 1 := by
        rw [map_inv₀]
        exact inv_le_one_of_one_le₀ (le_of_lt (not_le.mp hc))
      refine ⟨Polynomial.C (⟨c⁻¹, hcinv⟩ : 𝒪[k]) * Polynomial.X - 1,
        ?_, ?_⟩
      · intro h0
        have h1 := congrArg (fun q => Polynomial.coeff q 1) h0
        simp only [Polynomial.coeff_sub, Polynomial.coeff_C_mul,
          Polynomial.coeff_X_one, mul_one, Polynomial.coeff_one,
          Polynomial.coeff_zero] at h1
        have h2 : (⟨c⁻¹, hcinv⟩ : 𝒪[k]) = 0 := by
          simpa using h1
        exact inv_ne_zero hc0 (by simpa using congrArg Subtype.val h2)
      · simp only [map_sub, map_mul, Polynomial.aeval_C,
          Polynomial.aeval_X, map_one]
        show (c⁻¹ : k) * c - 1 = 0
        rw [inv_mul_cancel₀ hc0, sub_self]
  haveI : Algebra.IsAlgebraic 𝒪[k] Ω :=
    ⟨fun x => (Algebra.IsAlgebraic.isAlgebraic (R := k) x).restrictScalars
      (R := 𝒪[k])⟩
  -- below any nonzero value of `L` there is a nonzero base value: clear
  -- denominators of the inverse and shrink once by `p`
  have hsmall : ∀ w : L, w ≠ 0 → ∃ c : k, c ≠ 0 ∧
      valuation L (algebraMap k L c) < valuation L w := by
    intro w hw0
    obtain ⟨y, hy0, hyint⟩ :=
      (Algebra.IsAlgebraic.isAlgebraic (R := 𝒪[k])
        ((L.val (w⁻¹) : Ω))).exists_integral_multiple
    have h1 : valuation Ω (algebraMap 𝒪[k] Ω y * L.val w⁻¹) ≤ 1 := by
      have h2 := hint_le _ hyint
      rwa [Algebra.smul_def] at h2
    -- comparisons in `L` are comparisons of images in `Ω`
    have hLcomp : ∀ a b : L, valuation L a ≤ valuation L b ↔
        valuation Ω (algebraMap L Ω a) ≤ valuation Ω (algebraMap L Ω b) := by
      intro a b
      rw [← Valuation.Compatible.vle_iff_le (v := valuation L),
        ← Valuation.Compatible.vle_iff_le (v := valuation Ω)]
      exact (valuativeExtension_comap_val (k := k) Ω v L).vle_iff_vle a b
    have hw0' : valuation Ω (L.val w) ≠ 0 := by
      rw [Valuation.ne_zero_iff]
      exact fun h => hw0 ((map_eq_zero L.val).mp h)
    have hyW : valuation Ω (algebraMap 𝒪[k] Ω y) ≤ valuation Ω (L.val w) := by
      rw [map_inv₀ L.val, map_mul, map_inv₀, ← div_eq_mul_inv,
        div_le_one₀ (zero_lt_iff.mpr hw0')] at h1
      exact h1
    refine ⟨p * (y : k), mul_ne_zero hp0 (by exact_mod_cast hy0), ?_⟩
    have hyL : valuation L (algebraMap k L (y : k)) ≤ valuation L w := by
      rw [hLcomp]
      have e1 : algebraMap L Ω (algebraMap k L (y : k))
          = algebraMap 𝒪[k] Ω y := by
        rw [← IsScalarTower.algebraMap_apply k L Ω,
          IsScalarTower.algebraMap_apply 𝒪[k] k Ω]
        rfl
      have e2 : algebraMap L Ω w = L.val w := rfl
      rw [e1, e2]
      exact hyW
    have hyLpos : 0 < valuation L (algebraMap k L (y : k)) := by
      rw [zero_lt_iff, Valuation.ne_zero_iff]
      intro h
      exact (by exact_mod_cast hy0 : (y : k) ≠ 0)
        ((map_eq_zero (algebraMap k L)).mp h)
    calc valuation L (algebraMap k L (p * (y : k)))
        = valuation L (algebraMap k L p) *
            valuation L (algebraMap k L (y : k)) := by
          rw [map_mul, map_mul]
      _ < 1 * valuation L (algebraMap k L (y : k)) :=
          mul_lt_mul_of_pos_right hpimg hyLpos
      _ = valuation L (algebraMap k L (y : k)) := one_mul _
      _ ≤ valuation L w := hyL
  -- `L` is a Hausdorff topological ring in its valuative topology
  haveI hvtL : IsValuativeTopology L := ValuativeRel.isValuativeTopology L
  haveI : T2Space L := by
    apply IsTopologicalAddGroup.t2Space_of_zero_sep
    intro w hw0
    refine ⟨{x | valuation L x < valuation L w}, ?_,
      fun h => lt_irrefl _ (show valuation L w < valuation L w from h)⟩
    rw [IsValuativeTopology.mem_nhds_zero_iff]
    exact ⟨Units.mk0 (valuation L w) ((valuation L).ne_zero_iff.mpr hw0),
      fun y hy => hy⟩
  -- strict comparisons transfer from `k` to `L`
  have hlt : ∀ x z : k, valuation k x < valuation k z →
      valuation L (algebraMap k L x) < valuation L (algebraMap k L z) := by
    intro x z hxz
    rw [lt_iff_not_ge] at hxz ⊢
    intro hge
    apply hxz
    rw [← Valuation.Compatible.vle_iff_le (v := valuation L)] at hge
    rw [← Valuation.Compatible.vle_iff_le (v := valuation k)]
    exact ((valuativeExtension_comap (k := k) Ω v hv L).vle_iff_vle z x).mp hge
  -- the structure map is continuous: the preimage of every basic ball
  -- around zero contains a basic ball, by `hsmall`
  have hcont : Continuous (algebraMap k L) := by
    apply continuous_of_continuousAt_zero (algebraMap k L)
    rw [ContinuousAt, map_zero]
    rw [(IsValuativeTopology.hasBasis_nhds_zero k).tendsto_iff
      (IsValuativeTopology.hasBasis_nhds_zero L)]
    rintro γL -
    obtain ⟨z, hz⟩ := ValuativeRel.valuation_surjective (K := L)
      ((γL : ValueGroupWithZero L))
    have hz0 : z ≠ 0 := by
      intro h
      rw [h, map_zero] at hz
      exact γL.ne_zero hz.symm
    obtain ⟨c, hc0, hc⟩ := hsmall z hz0
    refine ⟨Units.mk0 (valuation k c) ((valuation k).ne_zero_iff.mpr hc0),
      trivial, ?_⟩
    intro a ha
    calc valuation L (algebraMap k L a)
        < valuation L (algebraMap k L c) := hlt a c ha
      _ < valuation L z := hc
      _ = (γL : ValueGroupWithZero L) := hz
  -- hence scalar multiplication is continuous
  haveI : ContinuousSMul k L := by
    constructor
    have h : (fun q : k × L => q.1 • q.2)
        = fun q : k × L => algebraMap k L q.1 * q.2 := by
      funext q
      exact Algebra.smul_def _ _
    rw [h]
    exact ((hcont.comp continuous_fst).mul continuous_snd)
  -- transport local compactness from `k ^ finrank`
  let e : (Fin (Module.finrank k L) → k) ≃ₗ[k] L :=
    (Module.finBasis k L).equivFun.symm
  have he : Continuous e.toLinearMap := e.toLinearMap.continuous_of_finiteDimensional
  have he' : Continuous e.symm.toLinearMap :=
    e.symm.toLinearMap.continuous_of_finiteDimensional
  let h : (Fin (Module.finrank k L) → k) ≃ₜ L :=
    { toEquiv := e.toEquiv
      continuous_toFun := he
      continuous_invFun := he' }
  exact h.locallyCompactSpace_iff.mp inferInstance

omit [IsSepClosed Ω] [DecidableEq Ω] in
/-- **Finite subextensions of `Ω` are nonarchimedean local fields**
(DERIVED 2026-07-20 from the local-compactness leaf): with the
restricted valuative relation and its valuative topology, `L` is a
nonarchimedean local field — the topology is valuative by construction
(`ValuativeRel.isValuativeTopology`), and nontriviality transports from
`k` through the proven valuative extension. -/
theorem isNonarchimedeanLocalField_intermediate
    (v : ValuativeRel Ω) (hv : @ValuativeExtension k Ω _ _ _ v _)
    (L : IntermediateField k Ω) [FiniteDimensional k L] :
    letI : ValuativeRel L := @ValuativeRel.comap L Ω _ _ v L.val.toRingHom
    @IsNonarchimedeanLocalField L _ _ (ValuativeRel.topologicalSpace L) := by
  letI vL : ValuativeRel L := @ValuativeRel.comap L Ω _ _ v L.val.toRingHom
  letI tL : TopologicalSpace L := ValuativeRel.topologicalSpace L
  haveI hvt : IsValuativeTopology L := ValuativeRel.isValuativeTopology L
  haveI hlc : LocallyCompactSpace L :=
    locallyCompactSpace_intermediate (k := k) Ω v hv L
  haveI hext : ValuativeExtension k L := valuativeExtension_comap (k := k) Ω v hv L
  haveI hnt : ValuativeRel.IsNontrivial L := by
    obtain ⟨γ, hγ0, hγ1⟩ := ValuativeRel.IsNontrivial.exists_lt_one (R := k)
    obtain ⟨c, hc⟩ := ValuativeRel.valuation_surjective (K := k) γ
    have hc0 : c ≠ 0 := by
      intro h
      rw [h, map_zero] at hc
      exact (zero_lt_iff.mp hγ0) hc.symm
    refine ⟨valuation L (algebraMap k L c), ?_, ?_⟩
    · simp [(Valuation.ne_zero_iff _).mpr
        ((map_ne_zero (algebraMap k L)).mpr hc0)]
    · intro h1
      -- `val_L (image c) = 1` forces `val_k c = 1`, contradicting `γ < 1`
      have hge : algebraMap k L 1 ≤ᵥ algebraMap k L c := by
        rw [Valuation.Compatible.vle_iff_le (v := valuation L)]
        rw [map_one, h1, map_one]
      rw [hext.vle_iff_vle] at hge
      rw [Valuation.Compatible.vle_iff_le (v := valuation k), map_one,
        hc] at hge
      exact absurd hγ1 (not_lt.mpr hge)
  exact { }

/-- **The level-`L` point of the glued Tate uniformisation**: for a
finite intermediate field `L` of `Ω/k` (a nonarchimedean local field by
`isNonarchimedeanLocalField_intermediate`), the canonical point map of
`L` (`TateCurve.pointMapQuot` at the image of `q`) applied to a unit of
`L`, transported across the curve identification
`(E_q)_L = E_{q_L}` (`TateCurve.tateCurve_map`) and pushed forward to
`Ω` along the inclusion `L.val`. -/
noncomputable def WeierstrassCurve.tateGluePointAt [CharZero k] (q : kˣ)
    (hq : valuation k (q : k) < 1) (v : ValuativeRel Ω)
    (hv : @ValuativeExtension k Ω _ _ _ v _)
    (L : IntermediateField k Ω) [FiniteDimensional k L] (u : Lˣ) :
    (((tateCurve ((q : k) : k))⁄Ω)).Point :=
  letI : ValuativeRel L := @ValuativeRel.comap L Ω _ _ v L.val.toRingHom
  letI : TopologicalSpace L := ValuativeRel.topologicalSpace L
  haveI : IsNonarchimedeanLocalField L :=
    isNonarchimedeanLocalField_intermediate (k := k) Ω v hv L
  haveI : CharZero L :=
    charZero_of_injective_algebraMap (algebraMap k L).injective
  haveI : ValuativeExtension k L :=
    valuativeExtension_comap (k := k) Ω v hv L
  WeierstrassCurve.Affine.Point.map (W' := tateCurve ((q : k) : k)) (S := k)
    L.val
    (cast (congrArg (fun W : WeierstrassCurve L => W.toAffine.Point)
        (TateCurve.tateCurve_map (l := L) ((q : k) : k) hq)).symm
      (TateCurve.pointMapQuot (Units.map (algebraMap k L).toMonoidHom q)
        (TateCurve.valuation_algebraMap_lt_one hq)
        (QuotientGroup.mk u)))

set_option warn.sorry false in
/-- **Naturality of the level maps in the subextension** (sorry node —
the gluing well-definedness): for `L ≤ L'`, computing the level point
in `L'` of (the image of) a unit of `L` gives the level point computed
in `L`. Reduces to the naturality of the canonical annulus-point map
under the valuative extension `L → L'` (the annulus representative is
preserved because values transfer strictly, and the coordinates are
values of the universal bilateral series — `bilateralX_map`-style
naturality applied to the local-field extension `L ⊆ L'` rather than to
`k ⊆ l`). -/
theorem WeierstrassCurve.tateGluePointAt_inclusion [CharZero k] (q : kˣ)
    (hq : valuation k (q : k) < 1) (v : ValuativeRel Ω)
    (hv : @ValuativeExtension k Ω _ _ _ v _)
    {L L' : IntermediateField k Ω} (h : L ≤ L')
    [FiniteDimensional k L] [FiniteDimensional k L'] (u : Lˣ) :
    tateGluePointAt Ω q hq v hv L'
        (Units.map (IntermediateField.inclusion h).toRingHom.toMonoidHom u) =
      tateGluePointAt Ω q hq v hv L u := by
  sorry

set_option warn.sorry false in
/-- **Galois-naturality of the level maps** (sorry node — the
equivariance leg of the gluing): a `k`-automorphism `σ` of `Ω` carries
the level point of `u` at `L` to the level point of `σ u` at `σ(L)`,
provided the valuative relation of `Ω` is `σ`-invariant (which the
constructed valuation is, by the strengthened
`exists_valuativeRel_sepClosure`). Reduces to the naturality of the
canonical point map under the value-preserving isomorphism
`σ : L ≃ σ(L)` of nonarchimedean local fields. -/
theorem WeierstrassCurve.tateGluePointAt_conj [CharZero k] (q : kˣ)
    (hq : valuation k (q : k) < 1) (v : ValuativeRel Ω)
    (hv : @ValuativeExtension k Ω _ _ _ v _)
    (hσinv : ∀ (σ : Ω ≃ₐ[k] Ω) (a b : Ω),
      (@ValuativeRel.vle Ω _ v (σ a) (σ b) ↔ @ValuativeRel.vle Ω _ v a b))
    (σ : Ω ≃ₐ[k] Ω) (L : IntermediateField k Ω) [FiniteDimensional k L]
    [FiniteDimensional k (L.map σ.toAlgHom)] (u : Lˣ) :
    WeierstrassCurve.Affine.Point.map (W' := tateCurve ((q : k) : k))
        σ.toAlgHom (tateGluePointAt Ω q hq v hv L u) =
      tateGluePointAt Ω q hq v hv (L.map σ.toAlgHom)
        (Units.map (IntermediateField.intermediateFieldMap σ L).toAlgHom.toRingHom.toMonoidHom u) := by
  sorry

set_option warn.sorry false in
/-- **Additivity of the level map in the unit** (sorry node — expected
mechanical): the level map turns unit multiplication into point
addition, by `TateCurve.pointMapQuot_add` at the local field `L`
transported across the curve identification and pushed forward along
the additive `Point.map`. -/
theorem WeierstrassCurve.tateGluePointAt_mul [CharZero k] (q : kˣ)
    (hq : valuation k (q : k) < 1) (v : ValuativeRel Ω)
    (hv : @ValuativeExtension k Ω _ _ _ v _)
    (L : IntermediateField k Ω) [FiniteDimensional k L] (u w : Lˣ) :
    tateGluePointAt Ω q hq v hv L (u * w) =
      tateGluePointAt Ω q hq v hv L u + tateGluePointAt Ω q hq v hv L w := by
  sorry

set_option warn.sorry false in
/-- **The kernel of the level map** (sorry node — expected mechanical):
the level point of `u` vanishes iff `u` is a power of the image of `q`
in `L`, by `TateCurve.pointMapQuot_eq_zero_iff` at `L`, injectivity of
the point pushforward, and injectivity of the inclusion on `q`-power
subgroups. -/
theorem WeierstrassCurve.tateGluePointAt_eq_zero_iff [CharZero k] (q : kˣ)
    (hq : valuation k (q : k) < 1) (v : ValuativeRel Ω)
    (hv : @ValuativeExtension k Ω _ _ _ v _)
    (L : IntermediateField k Ω) [FiniteDimensional k L] (u : Lˣ) :
    tateGluePointAt Ω q hq v hv L u = 0 ↔
      u ∈ Subgroup.zpowers (Units.map (algebraMap k L).toMonoidHom q) := by
  sorry

set_option warn.sorry false in
/-- **The gluing implication for Tate's uniformisation** (sorry node —
Ω-level from finite level): GIVEN the finite-level canonical
uniformisation — for every nonarchimedean local field `l` an additive
equivalence `lˣ/q^ℤ ≃+ E_q(l)` whose underlying function is the
canonical (choice-free) `TateCurve.pointMapQuot` — the uniformising
homomorphism over the separable closure `Ω` exists: `Ωˣ →+ E_q(Ω)`,
surjective, with kernel exactly `q^ℤ`, commuting with every
`k`-automorphism of `Ω`. Content of the (sorried) gluing: every
`u ∈ Ωˣ` and every point of `E_q(Ω)` lives in a finite subextension
`l/k` of `Ω/k`; a finite extension of a nonarchimedean local field is a
nonarchimedean local field with a unique valuative extension structure,
so the hypothesis applies at each level; the resulting maps are
compatible with the inclusions `l ⊆ l'` and with the `σ`-twists because
the underlying function `pointMapQuot` is defined by universal series
independent of the field (naturality of the annulus-representative
point map under valuative embeddings), so they glue to `Ωˣ` and the
kernel/surjectivity/equivariance properties pass to the colimit. -/
theorem WeierstrassCurve.exists_tateCurveHomSepClosure_of_finiteLevel
    [CharZero k] (q : kˣ) (hq : valuation k (q : k) < 1)
    (hfin : ∀ (l : Type uΩ) [Field l] [ValuativeRel l] [TopologicalSpace l]
      [IsNonarchimedeanLocalField l] [CharZero l] [DecidableEq l] (ql : lˣ)
      (hql : valuation l (ql : l) < 1),
      ∃ e : Additive (lˣ ⧸ Subgroup.zpowers ql) ≃+
          (WeierstrassCurve.tateCurve ((ql : l) : l)).toAffine.Point,
        ∀ x, e x = TateCurve.pointMapQuot ql hql x.toMul) :
    ∃ φ : Additive Ωˣ →+ (((tateCurve ((q : k) : k))⁄Ω)).Point,
      Function.Surjective φ ∧
      (∀ u : Ωˣ, φ (Additive.ofMul u) = 0 ↔
        u ∈ Subgroup.zpowers (Units.map (algebraMap k Ω).toMonoidHom q)) ∧
      (∀ (σ : Ω ≃ₐ[k] Ω) (u : Ωˣ),
        WeierstrassCurve.Affine.Point.map (W' := tateCurve ((q : k) : k))
            σ.toAlgHom (φ (Additive.ofMul u)) =
          φ (Additive.ofMul (Units.map σ.toAlgHom.toRingHom.toMonoidHom u))) := by
  -- The naturality of the fundamental-annulus bilateral coordinates under a
  -- valuative extension of nonarchimedean local fields (PROVEN in
  -- `TateUniformization.lean`: `coeffRingEval_map`, `evalA_XA_map`,
  -- `evalA_YA_map`, `bilateralX_map`, `bilateralY_map`), packaged as the
  -- coordinate-pair fact the gluing needs to check well-definedness of the
  -- glued point map independently of the chosen finite subextension.
  have hnat : ∀ {l : Type uΩ} [Field l] [ValuativeRel l] [TopologicalSpace l]
      [IsNonarchimedeanLocalField l] [CharZero l] [Algebra k l]
      [ValuativeExtension k l] (u₀ q₀ : k) (h0 : u₀ ≠ 0) (h1 : u₀ ≠ 1)
      (hu : valuation k u₀ ≤ 1) (hq1 : valuation k q₀ < 1)
      (hqu : valuation k q₀ < valuation k u₀)
      (h0' : algebraMap k l u₀ ≠ 0) (h1' : algebraMap k l u₀ ≠ 1)
      (hu' : valuation l (algebraMap k l u₀) ≤ 1)
      (hq1' : valuation l (algebraMap k l q₀) < 1)
      (hqu' : valuation l (algebraMap k l q₀) < valuation l (algebraMap k l u₀)),
      algebraMap k l (TateCurve.bilateralX u₀ q₀) =
        TateCurve.bilateralX (algebraMap k l u₀) (algebraMap k l q₀) ∧
      algebraMap k l (TateCurve.bilateralY u₀ q₀) =
        TateCurve.bilateralY (algebraMap k l u₀) (algebraMap k l q₀) :=
    fun {l} _ _ _ _ _ _ _ u₀ q₀ h0 h1 hu hq1 hqu h0' h1' hu' hq1' hqu' =>
      ⟨TateCurve.bilateralX_map u₀ q₀ h0 h1 hu hq1 hqu h0' h1' hu' hq1' hqu',
       TateCurve.bilateralY_map u₀ q₀ h0 h1 hu hq1 hqu h0' h1' hu' hq1' hqu'⟩
  -- The Tate curve itself is functorial in a valuative extension (PROVEN,
  -- `TateCurve.tateCurve_map`), so the base-changed curve
  -- `(tateCurve q₀).map (algebraMap k l)` used to type the eventual
  -- `WeierstrassCurve.Affine.Point.map` in the gluing construction is
  -- identified with `tateCurve (algebraMap k l q₀)` directly.
  have hcurve : ∀ {l : Type uΩ} [Field l] [ValuativeRel l] [TopologicalSpace l]
      [IsNonarchimedeanLocalField l] [CharZero l] [Algebra k l]
      [ValuativeExtension k l] (q₀ : k) (hq0 : valuation k q₀ < 1),
      (WeierstrassCurve.tateCurve q₀).map (algebraMap k l) =
        WeierstrassCurve.tateCurve (algebraMap k l q₀) :=
    fun {l} _ _ _ _ _ _ _ q₀ hq0 => TateCurve.tateCurve_map q₀ hq0
  -- The valuative structure of `Ω` and the local-field structure of each
  -- finite subextension (the two prerequisite leaves above): every element
  -- of `Ωˣ` and every point of `E_q(Ω)` lives in some finite intermediate
  -- field `L`, which these leaves make a nonarchimedean local field
  -- valuatively over `k`, so the finite-level hypothesis `hfin` applies.
  obtain ⟨vΩ, hvΩ, hσinv⟩ := exists_valuativeRel_sepClosure (k := k) Ω
  have hL : ∀ (L : IntermediateField k Ω) (_ : FiniteDimensional k L),
      letI : ValuativeRel L := @ValuativeRel.comap L Ω _ _ vΩ L.val.toRingHom
      @IsNonarchimedeanLocalField L _ _ (ValuativeRel.topologicalSpace L) :=
    fun L _ =>
      isNonarchimedeanLocalField_intermediate (k := k) Ω vΩ hvΩ L
  have hLk : ∀ L : IntermediateField k Ω,
      @ValuativeExtension k L _ _ _
        (@ValuativeRel.comap L Ω _ _ vΩ L.val.toRingHom) _ :=
    fun L => valuativeExtension_comap (k := k) Ω vΩ hvΩ L
  have hLΩ : ∀ L : IntermediateField k Ω,
      @ValuativeExtension L Ω _ _
        (@ValuativeRel.comap L Ω _ _ vΩ L.val.toRingHom) vΩ _ :=
    fun L => valuativeExtension_comap_val (k := k) Ω vΩ L
  classical
  haveI : CharZero Ω :=
    charZero_of_injective_algebraMap (algebraMap k Ω).injective
  haveI halgΩ : Algebra.IsAlgebraic k Ω := Algebra.IsSeparable.isAlgebraic k Ω
  have hfdAdj : ∀ x : Ω,
      FiniteDimensional k (IntermediateField.adjoin k {x}) := fun x =>
    IntermediateField.adjoin.finiteDimensional
      (Algebra.IsAlgebraic.isAlgebraic (R := k) x).isIntegral
  -- units of a finite subextension from global units lying in it
  let toUnit : ∀ (L : IntermediateField k Ω) (u : Ωˣ), ((u : Ω) ∈ L) → Lˣ :=
    fun L u hu =>
      ⟨⟨(u : Ω), hu⟩,
        ⟨((u⁻¹ : Ωˣ) : Ω), by
          rw [Units.val_inv_eq_inv_val]
          exact L.inv_mem hu⟩,
        by
          apply Subtype.ext
          simp,
        by
          apply Subtype.ext
          simp⟩
  -- the glued underlying function: compute at the field generated by `u`
  let Φ : Ωˣ → (((tateCurve ((q : k) : k))⁄Ω)).Point := fun u =>
    haveI := hfdAdj (u : Ω)
    tateGluePointAt Ω q hq vΩ hvΩ (IntermediateField.adjoin k {(u : Ω)})
      (toUnit _ u (IntermediateField.mem_adjoin_simple_self k (u : Ω)))
  -- `Φ` can be computed at any finite level containing the unit
  have hΦat : ∀ (L : IntermediateField k Ω) (_ : FiniteDimensional k L)
      (u : Ωˣ) (hu : (u : Ω) ∈ L),
      Φ u = tateGluePointAt Ω q hq vΩ hvΩ L (toUnit L u hu) := by
    intro L hfd u hu
    haveI := hfdAdj (u : Ω)
    have hle : IntermediateField.adjoin k {(u : Ω)} ≤ L := by
      rw [IntermediateField.adjoin_le_iff]
      simpa using hu
    have hmap : Units.map (IntermediateField.inclusion hle).toRingHom.toMonoidHom
        (toUnit _ u (IntermediateField.mem_adjoin_simple_self k (u : Ω))) =
        toUnit L u hu := by
      apply Units.ext
      rfl
    calc Φ u
        = tateGluePointAt Ω q hq vΩ hvΩ L
            (Units.map (IntermediateField.inclusion hle).toRingHom.toMonoidHom
              (toUnit _ u (IntermediateField.mem_adjoin_simple_self k (u : Ω)))) :=
          (tateGluePointAt_inclusion Ω q hq vΩ hvΩ hle _).symm
      _ = tateGluePointAt Ω q hq vΩ hvΩ L (toUnit L u hu) := by rw [hmap]
  -- additivity
  have hΦadd : ∀ u w : Ωˣ, Φ (u * w) = Φ u + Φ w := by
    intro u w
    haveI := hfdAdj (u : Ω)
    haveI := hfdAdj (w : Ω)
    set L := IntermediateField.adjoin k {(u : Ω)} ⊔
      IntermediateField.adjoin k {(w : Ω)} with hLdef
    haveI : FiniteDimensional k L := IntermediateField.finiteDimensional_sup _ _
    have humem : (u : Ω) ∈ L :=
      le_sup_left (α := IntermediateField k Ω)
        (IntermediateField.mem_adjoin_simple_self k (u : Ω))
    have hwmem : (w : Ω) ∈ L :=
      le_sup_right (α := IntermediateField k Ω)
        (IntermediateField.mem_adjoin_simple_self k (w : Ω))
    have huw : ((u * w : Ωˣ) : Ω) ∈ L := by
      rw [Units.val_mul]
      exact mul_mem humem hwmem
    rw [hΦat L inferInstance (u * w) huw, hΦat L inferInstance u humem,
      hΦat L inferInstance w hwmem]
    have hsplit : toUnit L (u * w) huw = toUnit L u humem * toUnit L w hwmem := by
      apply Units.ext
      apply Subtype.ext
      rfl
    rw [hsplit, tateGluePointAt_mul]
  -- kernel
  have hΦker : ∀ u : Ωˣ, Φ u = 0 ↔
      u ∈ Subgroup.zpowers (Units.map (algebraMap k Ω).toMonoidHom q) := by
    intro u
    haveI := hfdAdj (u : Ω)
    set L := IntermediateField.adjoin k {(u : Ω)} with hLdef
    rw [hΦat L inferInstance u (IntermediateField.mem_adjoin_simple_self k _),
      tateGluePointAt_eq_zero_iff]
    -- transfer `q`-power membership along the injective inclusion
    have hqcomp : Units.map L.val.toRingHom.toMonoidHom
        (Units.map (algebraMap k L).toMonoidHom q) =
        Units.map (algebraMap k Ω).toMonoidHom q := by
      apply Units.ext
      show L.val (algebraMap k L (q : k)) = algebraMap k Ω (q : k)
      rw [IsScalarTower.algebraMap_apply k L Ω]
      rfl
    have hucomp : Units.map L.val.toRingHom.toMonoidHom
        (toUnit L u (IntermediateField.mem_adjoin_simple_self k _)) = u := by
      apply Units.ext
      rfl
    rw [Subgroup.mem_zpowers_iff, Subgroup.mem_zpowers_iff]
    constructor
    · rintro ⟨n, hn⟩
      refine ⟨n, ?_⟩
      rw [← hqcomp, ← map_zpow, hn, hucomp]
    · rintro ⟨n, hn⟩
      refine ⟨n, ?_⟩
      have hinj : Function.Injective
          (Units.map L.val.toRingHom.toMonoidHom : Lˣ →* Ωˣ) := by
        intro a b hab
        apply Units.ext
        exact L.val.injective (congrArg Units.val hab)
      apply hinj
      rw [map_zpow, hqcomp, hn, hucomp]
  -- equivariance
  have hΦequiv : ∀ (σ : Ω ≃ₐ[k] Ω) (u : Ωˣ),
      WeierstrassCurve.Affine.Point.map (W' := tateCurve ((q : k) : k))
          σ.toAlgHom (Φ u) =
        Φ (Units.map σ.toAlgHom.toRingHom.toMonoidHom u) := by
    intro σ u
    haveI := hfdAdj (u : Ω)
    set L := IntermediateField.adjoin k {(u : Ω)} with hLdef
    haveI : FiniteDimensional k (L.map σ.toAlgHom) :=
      LinearEquiv.finiteDimensional
        (IntermediateField.intermediateFieldMap σ L).toLinearEquiv
    rw [hΦat L inferInstance u (IntermediateField.mem_adjoin_simple_self k _),
      tateGluePointAt_conj Ω q hq vΩ hvΩ hσinv σ L]
    have hmem : ((Units.map σ.toAlgHom.toRingHom.toMonoidHom u : Ωˣ) : Ω) ∈
        L.map σ.toAlgHom :=
      ⟨(u : Ω), IntermediateField.mem_adjoin_simple_self k _, rfl⟩
    rw [hΦat (L.map σ.toAlgHom) inferInstance _ hmem]
    congr 1
  -- surjectivity (the only leg that uses the finite-level hypothesis)
  have hΦsurj : ∀ P : (((tateCurve ((q : k) : k))⁄Ω)).Point,
      ∃ u : Ωˣ, Φ u = P := by
    sorry
  -- package
  refine ⟨AddMonoidHom.mk' (fun x => Φ x.toMul) ?_, ?_, ?_, ?_⟩
  · intro x y
    exact hΦadd x.toMul y.toMul
  · intro P
    obtain ⟨u, hu⟩ := hΦsurj P
    exact ⟨Additive.ofMul u, hu⟩
  · intro u
    exact hΦker u
  · intro σ u
    exact hΦequiv σ u

/-- **The Tate-curve uniformising homomorphism over a separable closure**
(derived 2026-07-18 by feeding the finite-level uniformisation
`TateCurve.tateCurveEquiv` — canonical, with underlying function
`pointMapQuot`, from `TateUniformization.lean` — into the gluing
implication above): for a unit `q` of `k` with `|q| < 1` there is a
surjective group homomorphism `Ωˣ → E_q(Ω)` with kernel exactly `q^ℤ`,
commuting with every `k`-algebra automorphism of `Ω` ON THE NOSE. -/
theorem WeierstrassCurve.exists_tateCurveHomSepClosure [CharZero k] (q : kˣ)
    (hq : valuation k (q : k) < 1) :
    ∃ φ : Additive Ωˣ →+ (((tateCurve ((q : k) : k))⁄Ω)).Point,
      Function.Surjective φ ∧
      (∀ u : Ωˣ, φ (Additive.ofMul u) = 0 ↔
        u ∈ Subgroup.zpowers (Units.map (algebraMap k Ω).toMonoidHom q)) ∧
      (∀ (σ : Ω ≃ₐ[k] Ω) (u : Ωˣ),
        WeierstrassCurve.Affine.Point.map (W' := tateCurve ((q : k) : k))
            σ.toAlgHom (φ (Additive.ofMul u)) =
          φ (Additive.ofMul (Units.map σ.toAlgHom.toRingHom.toMonoidHom u))) :=
  WeierstrassCurve.exists_tateCurveHomSepClosure_of_finiteLevel Ω q hq
    (fun _l _ _ _ _ _ _ ql hql =>
      ⟨TateCurve.tateCurveEquiv ql hql,
        fun x => TateCurve.tateCurveEquiv_apply ql hql x⟩)

/-- **Tate's uniformisation of the TATE CURVE over a separable closure**
(derived 2026-07-18 from the pre-quotient homomorphism
`exists_tateCurveHomSepClosure` by the first isomorphism theorem): for a
unit `q` of `k` with `|q| < 1`, the points of the Tate curve `E_q` over
a separable closure `Ω` are `Ωˣ/q^ℤ`, Galois-equivariantly ON THE NOSE.
The uniformising homomorphism `Ωˣ → E_q(Ω)` is surjective with kernel
`q^ℤ`, so it descends to an isomorphism on the quotient; equivariance
descends along the quotient map. -/
theorem WeierstrassCurve.exists_tateCurveEquivSepClosure [CharZero k] (q : kˣ)
    (hq : valuation k (q : k) < 1) :
    ∃ e : Additive (Ωˣ ⧸ Subgroup.zpowers
        (Units.map (algebraMap k Ω).toMonoidHom q)) ≃+
      (((tateCurve ((q : k) : k))⁄Ω)).Point,
      ∀ (σ : Ω ≃ₐ[k] Ω) (u : Ωˣ),
        WeierstrassCurve.Affine.Point.map (W' := tateCurve ((q : k) : k))
            σ.toAlgHom (e (Additive.ofMul ↑u)) =
          e (Additive.ofMul ↑(Units.map σ.toAlgHom.toRingHom.toMonoidHom u)) := by
  obtain ⟨φ, hφsurj, hφker, hφequiv⟩ :=
    WeierstrassCurve.exists_tateCurveHomSepClosure (k := k) Ω q hq
  -- the multiplicative form of `φ`, as a `MonoidHom` out of `Ωˣ`
  let ψ : Ωˣ →* Multiplicative ((((tateCurve ((q : k) : k))⁄Ω)).Point) :=
    { toFun := fun u => Multiplicative.ofAdd (φ (Additive.ofMul u))
      map_one' := by simp
      map_mul' := fun u v => by simp }
  -- `q^ℤ` is contained in the kernel, so `ψ` descends to the quotient
  have hZle : Subgroup.zpowers (Units.map (algebraMap k Ω).toMonoidHom q) ≤
      ψ.ker := by
    intro z hz
    exact (hφker z).mpr hz
  let ψbar : (Ωˣ ⧸ Subgroup.zpowers
      (Units.map (algebraMap k Ω).toMonoidHom q)) →*
      Multiplicative ((((tateCurve ((q : k) : k))⁄Ω)).Point) :=
    QuotientGroup.lift _ ψ hZle
  -- the descended map is injective (kernel of `φ` is exactly `q^ℤ`) …
  have hinj : Function.Injective ψbar := by
    rw [injective_iff_map_eq_one]
    intro x hx
    induction x using QuotientGroup.induction_on with
    | H u =>
      rw [QuotientGroup.eq_one_iff]
      exact (hφker u).mp hx
  -- … and surjective (because `φ` is)
  have hsurj : Function.Surjective ψbar := by
    intro p
    obtain ⟨a, ha⟩ := hφsurj (Multiplicative.toAdd p)
    refine ⟨((Additive.toMul a : Ωˣ) : Ωˣ ⧸ Subgroup.zpowers
      (Units.map (algebraMap k Ω).toMonoidHom q)), ?_⟩
    show Multiplicative.ofAdd (φ (Additive.ofMul (Additive.toMul a))) = p
    simp [ha]
  -- assemble the additive equivalence out of the multiplicative bijection
  refine ⟨MulEquiv.toAdditiveLeft
    (MulEquiv.ofBijective ψbar ⟨hinj, hsurj⟩), fun σ u => ?_⟩
  -- on the class of `u` the equivalence evaluates to `φ (ofMul u)`,
  -- so equivariance is exactly the equivariance of `φ`
  exact hφequiv σ u

omit [E.IsMinimal 𝒪[k]] in
set_option backward.isDefEq.respectTransparency false in
set_option synthInstance.maxHeartbeats 400000 in
set_option maxHeartbeats 1000000 in
/-- **Tate's uniformisation theorem over a separable closure** (derived
2026-07-17 from the choice-free Tate-curve uniformisation above and
Tate's theorem `exists_variableChange_tateCurve`): for `E/k`
an elliptic curve, in minimal Weierstrass form, with split multiplicative reduction
over a nonarchimedean local field `k`, and `Ω` a separable closure of `k`, there is a
group isomorphism `Ωˣ/q(E)ᶻ ≅ E(Ω)` that is equivariant for the natural actions of
`Gal(Ω/k)` on both sides (Silverman, ATAEC V.3.1 + V.5.3: glue the finite-level
uniformisations `E(l) ≅ lˣ/qᶻ` over the finite subextensions `l/k` of `Ω`; the
`k`-linearity of every `σ ∈ Gal(Ω/k)` makes the sign choice `σ`-stable, cf.
`tateEquiv_galois` in the upstream FLT file). Stated as an existential Prop because
the isomorphism is canonical only up to negation. -/
theorem WeierstrassCurve.exists_tateEquivSepClosure [CharZero k] :
    ∃ e : Additive (Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω)) ≃+ ((E⁄Ω)).Point,
      ∀ (σ : Ω ≃ₐ[k] Ω) (u : Ωˣ),
        WeierstrassCurve.Affine.Point.map (W' := E) σ.toAlgHom (e (Additive.ofMul ↑u)) =
          e (Additive.ofMul ↑(Units.map σ.toAlgHom.toRingHom.toMonoidHom u)) := by
  classical
  obtain ⟨C, hC⟩ := E.exists_variableChange_tateCurve
  obtain ⟨e₀, he₀⟩ := WeierstrassCurve.exists_tateCurveEquivSepClosure (k := k) Ω
    E.qUnit E.valuation_q_lt_one
  -- the `Ω`-stage curve equality behind the variable change
  have hEq : (E⁄Ω) = (C.baseChange Ω) •
      ((tateCurve ((E.qUnit : k) : k))⁄Ω) := by
    conv_lhs => rw [← hC]
    exact (baseChange_smul_baseChange _ _ _).symm
  haveI hTell : (((tateCurve ((E.qUnit : k) : k))⁄Ω)).IsElliptic := by
    haveI h1 : ((C.baseChange Ω) •
        ((tateCurve ((E.qUnit : k) : k))⁄Ω)).IsElliptic := by
      rw [← hEq]
      infer_instance
    have h2 : ((C.baseChange Ω)⁻¹ • ((C.baseChange Ω) •
        ((tateCurve ((E.qUnit : k) : k))⁄Ω))).IsElliptic := inferInstance
    rw [inv_smul_smul] at h2
    exact h2
  let Ψ : ((E⁄Ω)).Point ≃+ (((tateCurve ((E.qUnit : k) : k))⁄Ω)).Point :=
    (Affine.Point.equivOfEq hEq).trans
      (Affine.Point.equivVariableChange
        ((tateCurve ((E.qUnit : k) : k))⁄Ω) (C.baseChange Ω))
  have hΨapp : ∀ R : ((E⁄Ω)).Point, Ψ R =
      (Affine.Point.equivVariableChange
        ((tateCurve ((E.qUnit : k) : k))⁄Ω) (C.baseChange Ω))
      ((Affine.Point.equivOfEq hEq) R) := fun R => rfl
  refine ⟨e₀.trans Ψ.symm, ?_⟩
  intro σ u
  -- σ fixes the base-changed variable-change data (it is `k`-rational)
  have hσu : σ.toAlgHom (((C.baseChange Ω).u : Ω)) = ((C.baseChange Ω).u : Ω) := by
    simp only [VariableChange.baseChange, VariableChange.map, Units.coe_map,
      MonoidHom.coe_coe]
    exact σ.toAlgHom.commutes _
  have hσr : σ.toAlgHom (C.baseChange Ω).r = (C.baseChange Ω).r := by
    simp only [VariableChange.baseChange, VariableChange.map]
    exact σ.toAlgHom.commutes _
  have hσs : σ.toAlgHom (C.baseChange Ω).s = (C.baseChange Ω).s := by
    simp only [VariableChange.baseChange, VariableChange.map]
    exact σ.toAlgHom.commutes _
  have hσt : σ.toAlgHom (C.baseChange Ω).t = (C.baseChange Ω).t := by
    simp only [VariableChange.baseChange, VariableChange.map]
    exact σ.toAlgHom.commutes _
  -- equivariance of `Ψ` under `σ`
  have h12 : ∀ Q : ((E⁄Ω)).Point,
      Ψ (WeierstrassCurve.Affine.Point.map (W' := E) σ.toAlgHom Q) =
      WeierstrassCurve.Affine.Point.map (W' := tateCurve ((E.qUnit : k) : k))
        σ.toAlgHom (Ψ Q) := by
    intro Q
    rw [hΨapp, hΨapp]
    cases Q with
    | zero => simp [← WeierstrassCurve.Affine.Point.zero_def]
    | some x y hxy =>
      rw [WeierstrassCurve.Affine.Point.map_some,
        WeierstrassCurve.Affine.Point.equivOfEq_some,
        WeierstrassCurve.Affine.Point.equivOfEq_some,
        WeierstrassCurve.Affine.Point.equivVariableChange_some,
        WeierstrassCurve.Affine.Point.equivVariableChange_some,
        WeierstrassCurve.Affine.Point.map_some]
      refine WeierstrassCurve.Affine.Point.some_eq_some _ ?_ ?_
      · simp only [map_add, map_mul, map_pow, hσu, hσr]
      · simp only [map_add, map_mul, map_pow, hσu, hσs, hσt]
  have h12' : ∀ R : (((tateCurve ((E.qUnit : k) : k))⁄Ω)).Point,
      Ψ.symm (WeierstrassCurve.Affine.Point.map
        (W' := tateCurve ((E.qUnit : k) : k)) σ.toAlgHom R) =
      WeierstrassCurve.Affine.Point.map (W' := E) σ.toAlgHom (Ψ.symm R) := by
    intro R
    apply Ψ.injective
    rw [Ψ.apply_symm_apply, h12, Ψ.apply_symm_apply]
  show WeierstrassCurve.Affine.Point.map (W' := E) σ.toAlgHom
      (Ψ.symm (e₀ (Additive.ofMul ↑u))) =
      Ψ.symm (e₀ (Additive.ofMul
        ↑(Units.map σ.toAlgHom.toRingHom.toMonoidHom u)))
  rw [← h12', he₀]

/-- **Representatives of torsion in the Tate quotient** (PROVEN — pure
group theory): every `N`-torsion class of `Gˣ/q^ℤ` is represented by an
element whose `N`-th power is an integer power of `q`. This is step (a)
of the derivation of the multiplicative-reduction inertia statements
from `exists_tateEquivSepClosure`. -/
theorem exists_rep_pow_eq_zpow_of_torsion {G : Type*} [CommGroup G]
    (q : G) {N : ℕ} (t : Additive (G ⧸ Subgroup.zpowers q))
    (ht : ((N : ℤ)) • t = 0) :
    ∃ (u : G) (a : ℤ),
      Additive.ofMul ((u : G ⧸ Subgroup.zpowers q)) = t ∧ u ^ N = q ^ a := by
  obtain ⟨u, hu⟩ := QuotientGroup.mk_surjective (Additive.toMul t)
  have h1 : ((u : G ⧸ Subgroup.zpowers q)) ^ N = 1 := by
    have h2 := congrArg Additive.toMul ht
    rw [toMul_zsmul, toMul_zero, zpow_natCast] at h2
    rw [hu]
    exact h2
  have h3 : (u ^ N : G) ∈ Subgroup.zpowers q := by
    rw [← QuotientGroup.eq_one_iff, QuotientGroup.mk_pow]
    exact h1
  obtain ⟨a, ha⟩ := Subgroup.mem_zpowers_iff.mp h3
  exact ⟨u, a, by rw [hu, ofMul_toMul], ha.symm⟩

/-- **The inertia-difference of a Tate-parameter root is a root of
unity** (PROVEN): if `σ` fixes `u^N`, then `σ(u)·u⁻¹` is an `N`-th root
of unity. Step (c) of the multiplicative-reduction derivation: for a
torsion representative `u` with `u^N = q_E^a`, every `σ ∈ Gal(Ω/k)`
fixes `u^N` (the Tate parameter comes from the base field), so `σ`
moves `u` by at most an `N`-th root of unity. -/
theorem map_mul_inv_mem_rootsOfUnity_of_pow_fixed
    {k Ω : Type*} [Field k] [Field Ω] [Algebra k Ω]
    (σ : Ω ≃ₐ[k] Ω) (u : Ωˣ) {N : ℕ}
    (hfix : Units.map σ.toAlgHom.toRingHom.toMonoidHom (u ^ N) = u ^ N) :
    Units.map σ.toAlgHom.toRingHom.toMonoidHom u * u⁻¹ ∈
      rootsOfUnity N Ω := by
  rw [mem_rootsOfUnity]
  calc (Units.map σ.toAlgHom.toRingHom.toMonoidHom u * u⁻¹) ^ N
      = Units.map σ.toAlgHom.toRingHom.toMonoidHom (u ^ N) * (u ^ N)⁻¹ := by
        rw [mul_pow, map_pow, inv_pow]
    _ = 1 := by rw [hfix, mul_inv_cancel]

omit [E.IsMinimal 𝒪[k]] [IsSepClosed Ω] [Algebra.IsSeparable k Ω]
  [DecidableEq Ω] in
/-- Every `k`-automorphism of `Ω` fixes the Tate parameter (PROVEN): it
comes from the base field. -/
theorem WeierstrassCurve.map_qUnitSepClosure_eq (σ : Ω ≃ₐ[k] Ω) :
    Units.map σ.toAlgHom.toRingHom.toMonoidHom (E.qUnitSepClosure Ω) =
      E.qUnitSepClosure Ω := by
  apply Units.ext
  show σ ((algebraMap k Ω) E.q) = (algebraMap k Ω) E.q
  exact σ.commutes E.q

omit [E.IsMinimal 𝒪[k]] [IsSepClosed Ω] [Algebra.IsSeparable k Ω]
  [DecidableEq Ω] in
/-- Every `k`-automorphism of `Ω` fixes all integer powers of the Tate
parameter (PROVEN). -/
theorem WeierstrassCurve.map_zpow_qUnitSepClosure_eq (σ : Ω ≃ₐ[k] Ω)
    (a : ℤ) :
    Units.map σ.toAlgHom.toRingHom.toMonoidHom (E.qUnitSepClosure Ω ^ a) =
      E.qUnitSepClosure Ω ^ a := by
  rw [map_zpow, E.map_qUnitSepClosure_eq]

omit [E.IsMinimal 𝒪[k]] [IsSepClosed Ω] [Algebra.IsSeparable k Ω]
  [DecidableEq Ω] in
/-- **Integer powers of the Tate parameter are distinct** (PROVEN): the
Tate parameter has valuation strictly less than `1` in the base field,
so `a ↦ q^a` is injective — the class group `Ωˣ/q^ℤ` is a genuine
`ℤ`-quotient. -/
theorem WeierstrassCurve.qUnitSepClosure_zpow_injective :
    Function.Injective (fun a : ℤ => E.qUnitSepClosure Ω ^ a) := by
  intro a b hab
  -- descend to `k` along the injective algebra map
  have h1 : E.qUnit ^ a = E.qUnit ^ b := by
    have h2 : Units.map (algebraMap k Ω).toMonoidHom (E.qUnit ^ a) =
        Units.map (algebraMap k Ω).toMonoidHom (E.qUnit ^ b) := by
      rw [map_zpow, map_zpow]
      exact hab
    apply Units.ext
    have h3 := congrArg Units.val h2
    exact (algebraMap k Ω).injective h3
  -- valuation freeness in `k`
  have h4 := congrArg (fun w : kˣ => valuation k ((w : k))) h1
  rw [Units.val_zpow_eq_zpow_val, Units.val_zpow_eq_zpow_val,
    map_zpow₀, map_zpow₀] at h4
  exact zpow_right_injective₀
    (zero_lt_iff.mpr ((valuation k).ne_zero_iff.mpr E.q_ne_zero))
    (ne_of_lt E.valuation_q_lt_one) h4

set_option backward.isDefEq.respectTransparency false in
set_option maxHeartbeats 1000000 in
omit [E.IsMinimal 𝒪[k]] [Algebra.IsSeparable k Ω] in
/-- **The Tate valuation-exponent quotient on `p`-torsion** (PROVEN
over any uniformization witness): the `p`-torsion of a Tate-uniformized
curve surjects `Galois-invariantly` onto `ℤ/p` by the exponent of the
Tate parameter in the `p`-th power of any representative — the
quotient of the filtration `0 → μ_p → E[p] → ℤ/p → 0`. Since every
`k`-automorphism fixes the Tate parameter, the quotient carries the
TRIVIAL `Gal(Ω/k)`-action; this is the split-case content of the
tame-quotient condition at `2`. Surjectivity requires a `p`-th root of
the Tate parameter, which exists in the separably closed `Ω` when
`p ≠ 0` there. -/
theorem WeierstrassCurve.exists_tateTorsionQuotient
    (e : Additive (Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω)) ≃+ ((E⁄Ω)).Point)
    (he : ∀ (σ : Ω ≃ₐ[k] Ω) (u : Ωˣ),
      WeierstrassCurve.Affine.Point.map (W' := E) σ.toAlgHom (e (Additive.ofMul ↑u)) =
        e (Additive.ofMul ↑(Units.map σ.toAlgHom.toRingHom.toMonoidHom u)))
    {p : ℕ} (hp : p ≠ 0) (hpΩ : ((p : ℕ) : Ω) ≠ 0) :
    ∃ π : AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ) →+ ZMod p,
      Function.Surjective π ∧
      ∀ (σ : Ω ≃ₐ[k] Ω)
        (P Q : AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ)),
        (Q : ((E⁄Ω)).Point) =
          WeierstrassCurve.Affine.Point.map (W' := E) σ.toAlgHom
            (P : ((E⁄Ω)).Point) →
        π Q = π P := by
  classical
  -- torsion transfers to the quotient side
  have htors : ∀ P : AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ),
      ((p : ℕ) : ℤ) • (e.symm (P : ((E⁄Ω)).Point)) = 0 := fun P => by
    rw [← map_zsmul e.symm,
      (show ((p : ℕ) : ℤ) • (P : ((E⁄Ω)).Point) = 0 from P.2), map_zero]
  -- choose a representative and exponent for each torsion point
  choose u a hu ha using fun P : AddSubgroup.torsionBy ((E⁄Ω)).Point
      ((p : ℕ) : ℤ) =>
    exists_rep_pow_eq_zpow_of_torsion (E.qUnitSepClosure Ω)
      (e.symm (P : ((E⁄Ω)).Point)) (htors P)
  -- the exponent is independent of the representative, mod `p`
  have hindep : ∀ (P : AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ))
      (v : Ωˣ) (b : ℤ),
      Additive.ofMul ((v : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) =
        e.symm (P : ((E⁄Ω)).Point) →
      v ^ p = E.qUnitSepClosure Ω ^ b →
      ((b : ZMod p)) = ((a P : ZMod p)) := by
    intro P v b hv hvb
    have h1 : ((u P : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) =
        ((v : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) :=
      Additive.ofMul.injective ((hu P).trans hv.symm)
    obtain ⟨m, hm⟩ := Subgroup.mem_zpowers_iff.mp (QuotientGroup.eq.mp h1)
    -- `v = u P * q^m`
    have h2 : v = u P * E.qUnitSepClosure Ω ^ m := by
      rw [hm]
      group
    have h3 : E.qUnitSepClosure Ω ^ b =
        E.qUnitSepClosure Ω ^ (a P + m * (p : ℤ)) := by
      rw [← hvb, h2, mul_pow, ha P, ← zpow_natCast
        (E.qUnitSepClosure Ω ^ m) p, ← zpow_mul, ← zpow_add]
    have h4 : b = a P + m * (p : ℤ) :=
      E.qUnitSepClosure_zpow_injective Ω h3
    rw [h4]
    push_cast
    simp
  -- the exponent function and its additivity
  have hadd : ∀ P Q : AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ),
      ((a (P + Q) : ZMod p)) = ((a P : ZMod p)) + ((a Q : ZMod p)) := by
    intro P Q
    have hclass : Additive.ofMul (((u P * u Q : Ωˣ) :
        Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) =
        e.symm ((P + Q : AddSubgroup.torsionBy ((E⁄Ω)).Point
          ((p : ℕ) : ℤ)) : ((E⁄Ω)).Point) := by
      rw [show ((P + Q : AddSubgroup.torsionBy ((E⁄Ω)).Point
          ((p : ℕ) : ℤ)) : ((E⁄Ω)).Point) =
          (P : ((E⁄Ω)).Point) + (Q : ((E⁄Ω)).Point) from rfl,
        map_add e.symm, ← hu P, ← hu Q, QuotientGroup.mk_mul, ofMul_mul]
    have hpow : (u P * u Q) ^ p =
        E.qUnitSepClosure Ω ^ (a P + a Q) := by
      rw [mul_pow, ha P, ha Q, ← zpow_add]
    have := hindep (P + Q) (u P * u Q) (a P + a Q) hclass hpow
    rw [← this]
    push_cast
    ring
  let π : AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ) →+ ZMod p :=
    AddMonoidHom.mk' (fun P => ((a P : ZMod p))) hadd
  refine ⟨π, ?_, ?_⟩
  · -- surjectivity: a `p`-th root of the Tate parameter has exponent `1`
    have hq0 : (algebraMap k Ω) E.q ≠ 0 := by
      simp only [map_ne_zero]
      exact E.q_ne_zero
    obtain ⟨x, hx⟩ := IsSepClosed.exists_root
      (Polynomial.X ^ p - Polynomial.C ((algebraMap k Ω) E.q))
      (by
        rw [Polynomial.degree_X_pow_sub_C (Nat.pos_of_ne_zero hp)]
        exact_mod_cast Nat.pos_of_ne_zero hp |>.ne')
      (Polynomial.separable_X_pow_sub_C _ hpΩ hq0)
    have hxpow : x ^ p = (algebraMap k Ω) E.q := by
      have h1 := hx
      rw [Polynomial.IsRoot, Polynomial.eval_sub, Polynomial.eval_pow,
        Polynomial.eval_X, Polynomial.eval_C, sub_eq_zero] at h1
      exact h1
    have hx0 : x ≠ 0 := by
      intro h0
      rw [h0, zero_pow hp] at hxpow
      exact hq0 hxpow.symm
    set xu : Ωˣ := Units.mk0 x hx0 with hxu
    have hxupow : xu ^ p = E.qUnitSepClosure Ω ^ (1 : ℤ) := by
      apply Units.ext
      rw [Units.val_pow_eq_pow_val, Units.val_zpow_eq_zpow_val, zpow_one]
      exact hxpow
    -- the corresponding torsion point
    have htor : ((p : ℕ) : ℤ) • (e (Additive.ofMul ((xu :
        Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))))) = 0 := by
      rw [← map_zsmul e, ← ofMul_zpow, ← QuotientGroup.mk_zpow,
        zpow_natCast, hxupow]
      rw [show ((E.qUnitSepClosure Ω ^ (1 : ℤ) :
          Ωˣ) : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω)) = 1 from
        (QuotientGroup.eq_one_iff _).mpr (Subgroup.zpow_mem _
          (Subgroup.mem_zpowers _) _), ofMul_one, map_zero]
    set P₁ : AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ) :=
      ⟨e (Additive.ofMul ((xu : Ωˣ ⧸ Subgroup.zpowers
        (E.qUnitSepClosure Ω)))), htor⟩ with hP₁
    have hπ1 : π P₁ = 1 := by
      have hclass : Additive.ofMul ((xu : Ωˣ ⧸ Subgroup.zpowers
          (E.qUnitSepClosure Ω))) = e.symm ((P₁ :
          ((E⁄Ω)).Point)) := by
        rw [hP₁]
        exact (e.symm_apply_apply _).symm
      have := hindep P₁ xu 1 hclass hxupow
      rw [show π P₁ = ((a P₁ : ZMod p)) from rfl, ← this]
      norm_num
    -- `1` generates `ZMod p`
    haveI : NeZero p := ⟨hp⟩
    intro c
    refine ⟨c.val • P₁, ?_⟩
    rw [map_nsmul, hπ1, nsmul_eq_mul, mul_one, ZMod.natCast_val,
      ZMod.cast_id]
  · -- Galois invariance: `σ`-images have the same exponent
    intro σ P Q hQ
    have hclass : Additive.ofMul
        ((Units.map σ.toAlgHom.toRingHom.toMonoidHom (u P) :
          Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) =
        e.symm ((Q : ((E⁄Ω)).Point)) := by
      apply e.injective
      rw [e.apply_symm_apply, ← he, hQ]
      congr 1
      rw [hu P, e.apply_symm_apply]
    have hpow : (Units.map σ.toAlgHom.toRingHom.toMonoidHom (u P)) ^ p =
        E.qUnitSepClosure Ω ^ (a P) := by
      rw [← map_pow, ha P, map_zpow_qUnitSepClosure_eq]
    exact (hindep Q _ _ hclass hpow).symm

set_option backward.isDefEq.respectTransparency false in
set_option maxHeartbeats 1000000 in
omit [E.IsMinimal 𝒪[k]] [IsSepClosed Ω] [Algebra.IsSeparable k Ω] in
/-- **Local unipotence of inertia on Tate torsion** (PROVEN 2026-07-17,
assembling steps (a), (b), (c) over ANY witness of the uniformization):
given a Galois-equivariant Tate uniformization `e` of `E` over `Ω` and
a valuation subring `A` of `Ω` whose residue characteristic does not
divide `p`, every element of the inertia subgroup of `A` acts
unipotently on the `p`-torsion: `σ(σP) − σP − σP + P = 0`. The torsion
class is represented by `u` with `u^p = q_E^a` (step (a)); every
`k`-automorphism fixes `q_E^a`, so `σ(u)/u =: ζ` is a `p`-th root of
unity (step (c)) and `σP − P = e[ζ]`; inertia fixes `ζ` (step (b)), so
a second application of `σ − 1` kills `e[ζ]`. -/
theorem WeierstrassCurve.tate_inertia_unipotent
    (e : Additive (Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω)) ≃+ ((E⁄Ω)).Point)
    (he : ∀ (σ : Ω ≃ₐ[k] Ω) (u : Ωˣ),
      WeierstrassCurve.Affine.Point.map (W' := E) σ.toAlgHom (e (Additive.ofMul ↑u)) =
        e (Additive.ofMul ↑(Units.map σ.toAlgHom.toRingHom.toMonoidHom u)))
    (A : ValuationSubring Ω) {p : ℕ} (hp : p ≠ 0)
    (hchar : ((p : ℕ) : IsLocalRing.ResidueField A) ≠ 0)
    (σ : A.decompositionSubgroup k) (hσ : σ ∈ A.inertiaSubgroup k)
    (P : ((E⁄Ω)).Point)
    (hP : P ∈ AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ)) :
    WeierstrassCurve.Affine.Point.map (W' := E)
        ((σ : Ω ≃ₐ[k] Ω)).toAlgHom
        (WeierstrassCurve.Affine.Point.map (W' := E)
          ((σ : Ω ≃ₐ[k] Ω)).toAlgHom P) -
      WeierstrassCurve.Affine.Point.map (W' := E)
        ((σ : Ω ≃ₐ[k] Ω)).toAlgHom P -
      WeierstrassCurve.Affine.Point.map (W' := E)
        ((σ : Ω ≃ₐ[k] Ω)).toAlgHom P + P = 0 := by
  classical
  -- pull the torsion class back through `e`
  set t : Additive (Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω)) :=
    e.symm P with ht
  have hPt : e t = P := e.apply_symm_apply P
  have httor : ((p : ℕ) : ℤ) • t = 0 := by
    have h1 : ((p : ℕ) : ℤ) • P = 0 := hP
    rw [ht, ← map_zsmul e.symm, h1, map_zero]
  obtain ⟨u, a, hut, hupow⟩ :=
    exists_rep_pow_eq_zpow_of_torsion (E.qUnitSepClosure Ω) t httor
  -- `σ` moves `u` by the root of unity `ζ`
  have hfixpow : Units.map ((σ : Ω ≃ₐ[k] Ω)).toAlgHom.toRingHom.toMonoidHom
      (u ^ p) = u ^ p := by
    rw [hupow]
    exact E.map_zpow_qUnitSepClosure_eq Ω (σ : Ω ≃ₐ[k] Ω) a
  have hζmem : Units.map ((σ : Ω ≃ₐ[k] Ω)).toAlgHom.toRingHom.toMonoidHom u
      * u⁻¹ ∈ rootsOfUnity p Ω :=
    map_mul_inv_mem_rootsOfUnity_of_pow_fixed (σ : Ω ≃ₐ[k] Ω) u hfixpow
  set ζ : Ωˣ := Units.map ((σ : Ω ≃ₐ[k] Ω)).toAlgHom.toRingHom.toMonoidHom u
    * u⁻¹ with hζ
  -- inertia fixes `ζ`
  have hζpow : (ζ : Ω) ^ p = 1 := by
    have h1 : ζ ^ p = 1 := hζmem
    have h2 := congrArg Units.val h1
    rwa [Units.val_pow_eq_pow_val, Units.val_one] at h2
  have hσζ : Units.map ((σ : Ω ≃ₐ[k] Ω)).toAlgHom.toRingHom.toMonoidHom ζ =
      ζ := by
    apply Units.ext
    show (σ : Ω ≃ₐ[k] Ω) (ζ : Ω) = (ζ : Ω)
    exact A.inertia_fixes_of_pow_eq_one hp hchar σ hσ hζpow
  -- `σP = P + e[ζ]`
  have hσu : Units.map ((σ : Ω ≃ₐ[k] Ω)).toAlgHom.toRingHom.toMonoidHom u =
      ζ * u := by
    rw [hζ, inv_mul_cancel_right]
  have hstep : ∀ Q : ((E⁄Ω)).Point,
      Q = e (Additive.ofMul (↑u : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) →
      WeierstrassCurve.Affine.Point.map (W' := E)
        ((σ : Ω ≃ₐ[k] Ω)).toAlgHom Q =
      e (Additive.ofMul (↑(ζ * u) : Ωˣ ⧸ Subgroup.zpowers
        (E.qUnitSepClosure Ω))) := by
    intro Q hQ
    rw [hQ, he (σ : Ω ≃ₐ[k] Ω) u, hσu]
  have hPu : P = e (Additive.ofMul (↑u : Ωˣ ⧸ Subgroup.zpowers
      (E.qUnitSepClosure Ω))) := by
    rw [hut, hPt]
  have hσP : WeierstrassCurve.Affine.Point.map (W' := E)
      ((σ : Ω ≃ₐ[k] Ω)).toAlgHom P =
      e (Additive.ofMul (↑(ζ * u) : Ωˣ ⧸ Subgroup.zpowers
        (E.qUnitSepClosure Ω))) := hstep P hPu
  -- `σ(σP) = σP + e[σζ] − ... = e[ζ·ζ·u]`? — apply equivariance again
  have hσσP : WeierstrassCurve.Affine.Point.map (W' := E)
      ((σ : Ω ≃ₐ[k] Ω)).toAlgHom
      (WeierstrassCurve.Affine.Point.map (W' := E)
        ((σ : Ω ≃ₐ[k] Ω)).toAlgHom P) =
      e (Additive.ofMul (↑(ζ * (ζ * u)) : Ωˣ ⧸ Subgroup.zpowers
        (E.qUnitSepClosure Ω))) := by
    rw [hσP, he (σ : Ω ≃ₐ[k] Ω) (ζ * u)]
    congr 2
    rw [map_mul, hσζ, hσu]
  -- assemble in the additive quotient
  have h₂ : (Additive.ofMul (↑(ζ * u) : Ωˣ ⧸ Subgroup.zpowers
      (E.qUnitSepClosure Ω))) =
      Additive.ofMul ((ζ : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) +
      Additive.ofMul ((u : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) := by
    rw [QuotientGroup.mk_mul, ofMul_mul]
  have h₁ : (Additive.ofMul (↑(ζ * (ζ * u)) : Ωˣ ⧸ Subgroup.zpowers
      (E.qUnitSepClosure Ω))) =
      Additive.ofMul ((ζ : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) +
      (Additive.ofMul ((ζ : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω))) +
       Additive.ofMul ((u : Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω)))) := by
    rw [QuotientGroup.mk_mul, ofMul_mul, h₂]
  rw [hσσP, hσP, hPu, h₁, h₂, map_add, map_add]
  abel

set_option backward.isDefEq.respectTransparency false in
set_option maxHeartbeats 1000000 in
omit [E.IsMinimal 𝒪[k]] [IsSepClosed Ω] [Algebra.IsSeparable k Ω] in
/-- **Local triviality of inertia on Tate torsion when the parameter is
a `p`-th power up to units** (steps (a)+(b′)+(d) over any witness of
the uniformization): if `q_E · w⁻ᵖ` is a unit of the valuation subring
`A` (with nonzero residue) for some `w ∈ kˣ`, then every inertia
element FIXES the `p`-torsion pointwise. The torsion class is
represented by `u` with `uᵖ = q_Eᵃ`; then `x := u·w⁻ᵃ` satisfies
`xᵖ = (q_E·w⁻ᵖ)ᵃ`, a `σ`-fixed unit constant of `A`, so inertia fixes
`x` (`inertia_fixes_of_pow_eq`), hence `u`, hence the point. -/
theorem WeierstrassCurve.tate_inertia_trivial
    (e : Additive (Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω)) ≃+ ((E⁄Ω)).Point)
    (he : ∀ (σ : Ω ≃ₐ[k] Ω) (u : Ωˣ),
      WeierstrassCurve.Affine.Point.map (W' := E) σ.toAlgHom (e (Additive.ofMul ↑u)) =
        e (Additive.ofMul ↑(Units.map σ.toAlgHom.toRingHom.toMonoidHom u)))
    (A : ValuationSubring Ω) {p : ℕ} (hp : p ≠ 0)
    (hchar : ((p : ℕ) : IsLocalRing.ResidueField A) ≠ 0)
    (σ : A.decompositionSubgroup k) (hσ : σ ∈ A.inertiaSubgroup k)
    (w : kˣ)
    (hcA : algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k)) ∈ A)
    (hcres : IsLocalRing.residue A
      (⟨algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k)), hcA⟩ : A) ≠ 0)
    (P : ((E⁄Ω)).Point)
    (hP : P ∈ AddSubgroup.torsionBy ((E⁄Ω)).Point ((p : ℕ) : ℤ)) :
    WeierstrassCurve.Affine.Point.map (W' := E)
      ((σ : Ω ≃ₐ[k] Ω)).toAlgHom P = P := by
  classical
  set t : Additive (Ωˣ ⧸ Subgroup.zpowers (E.qUnitSepClosure Ω)) :=
    e.symm P with ht
  have hPt : e t = P := e.apply_symm_apply P
  have httor : ((p : ℕ) : ℤ) • t = 0 := by
    have h1 : ((p : ℕ) : ℤ) • P = 0 := hP
    rw [ht, ← map_zsmul e.symm, h1, map_zero]
  obtain ⟨u, a, hut, hupow⟩ :=
    exists_rep_pow_eq_zpow_of_torsion (E.qUnitSepClosure Ω) t httor
  -- the recentred representative `x := u · wΩ⁻ᵃ` and its constant power
  set wΩ : Ωˣ := Units.map (algebraMap k Ω).toMonoidHom w with hwΩ
  have h1 : (u * wΩ⁻¹ ^ a) ^ (p : ℤ) =
      (Units.map (algebraMap k Ω).toMonoidHom (E.qUnit * w⁻¹ ^ p)) ^ a := by
    calc (u * wΩ⁻¹ ^ a) ^ (p : ℤ)
        = u ^ (p : ℤ) * (wΩ⁻¹ ^ a) ^ (p : ℤ) := mul_zpow _ _ _
      _ = u ^ p * (wΩ⁻¹ ^ a) ^ (p : ℤ) := by rw [zpow_natCast]
      _ = E.qUnitSepClosure Ω ^ a * (wΩ⁻¹ ^ a) ^ (p : ℤ) := by rw [hupow]
      _ = E.qUnitSepClosure Ω ^ a * (wΩ⁻¹ ^ (p : ℤ)) ^ a := by
          rw [← zpow_mul, ← zpow_mul, mul_comm a ((p : ℤ))]
      _ = E.qUnitSepClosure Ω ^ a * (wΩ⁻¹ ^ p) ^ a := by rw [zpow_natCast]
      _ = (E.qUnitSepClosure Ω * wΩ⁻¹ ^ p) ^ a := (mul_zpow _ _ _).symm
      _ = (Units.map (algebraMap k Ω).toMonoidHom (E.qUnit * w⁻¹ ^ p)) ^ a := by
          congr 1
          rw [map_mul, map_pow, map_inv, ← hwΩ]
          rfl
  have hxpow : ((u * wΩ⁻¹ ^ a : Ωˣ) : Ω) ^ p =
      (algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a := by
    calc ((u * wΩ⁻¹ ^ a : Ωˣ) : Ω) ^ p
        = (((u * wΩ⁻¹ ^ a) ^ p : Ωˣ) : Ω) :=
          (Units.val_pow_eq_pow_val _ _).symm
      _ = (((u * wΩ⁻¹ ^ a) ^ (p : ℤ) : Ωˣ) : Ω) := by rw [zpow_natCast]
      _ = (((Units.map (algebraMap k Ω).toMonoidHom
            (E.qUnit * w⁻¹ ^ p)) ^ a : Ωˣ) : Ω) := by rw [h1]
      _ = ((Units.map (algebraMap k Ω).toMonoidHom
            (E.qUnit * w⁻¹ ^ p) : Ωˣ) : Ω) ^ a :=
          Units.val_zpow_eq_zpow_val _ _
      _ = (algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a := rfl
  -- the constant power is `σ`-fixed (it comes from the base field)
  have hσc : (σ : Ω ≃ₐ[k] Ω)
      ((algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a) =
      (algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a := by
    rw [map_zpow₀]
    congr 1
    exact (σ : Ω ≃ₐ[k] Ω).commutes _
  -- the constant is a unit of `A`, so its integer powers stay in `A`
  have hcunit : IsUnit (⟨algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k)),
      hcA⟩ : A) := by
    by_contra hnu
    exact hcres (Ideal.Quotient.eq_zero_iff_mem.mpr
      ((IsLocalRing.mem_maximalIdeal _).mpr hnu))
  have hcoe : (((hcunit.unit ^ a : Aˣ) : A) : Ω) =
      (algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a := by
    calc (((hcunit.unit ^ a : Aˣ) : A) : Ω)
        = ((Units.map A.subtype.toMonoidHom (hcunit.unit ^ a) : Ωˣ) : Ω) := rfl
      _ = (((Units.map A.subtype.toMonoidHom hcunit.unit) ^ a : Ωˣ) : Ω) := by
          rw [map_zpow]
      _ = ((Units.map A.subtype.toMonoidHom hcunit.unit : Ωˣ) : Ω) ^ a :=
          Units.val_zpow_eq_zpow_val _ _
      _ = (((hcunit.unit : A) : Ω)) ^ a := rfl
      _ = (algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a := by
          rw [hcunit.unit_spec]
  have hcApow : (algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a ∈ A :=
    hcoe ▸ SetLike.coe_mem _
  have hcrespow : IsLocalRing.residue A
      (⟨(algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a, hcApow⟩ : A) ≠
      0 := by
    rw [show (⟨(algebraMap k Ω (((E.qUnit * w⁻¹ ^ p : kˣ) : k))) ^ a,
        hcApow⟩ : A) = ((hcunit.unit ^ a : Aˣ) : A) from Subtype.ext hcoe.symm]
    exact ((hcunit.unit ^ a).isUnit.map (IsLocalRing.residue A)).ne_zero
  -- inertia fixes the recentred representative (step (b′))
  have hfix : (σ : Ω ≃ₐ[k] Ω) ((u * wΩ⁻¹ ^ a : Ωˣ) : Ω) =
      ((u * wΩ⁻¹ ^ a : Ωˣ) : Ω) :=
    A.inertia_fixes_of_pow_eq hp hchar σ hσ hcApow hcrespow hσc hxpow
  -- `σ` fixes `wΩ` (it comes from the base field), hence fixes `u`
  have hσw : Units.map ((σ : Ω ≃ₐ[k] Ω)).toAlgHom.toRingHom.toMonoidHom wΩ =
      wΩ := by
    apply Units.ext
    show (σ : Ω ≃ₐ[k] Ω) ((wΩ : Ωˣ) : Ω) = ((wΩ : Ωˣ) : Ω)
    exact (σ : Ω ≃ₐ[k] Ω).commutes w
  have h5 : (u * wΩ⁻¹ ^ a) * wΩ ^ a = u := by
    rw [inv_zpow, inv_mul_cancel_right]
  have hσu : Units.map ((σ : Ω ≃ₐ[k] Ω)).toAlgHom.toRingHom.toMonoidHom u =
      u := by
    rw [← h5, map_mul, map_zpow, hσw]
    congr 1
    apply Units.ext
    exact hfix
  -- conclude: the point itself is fixed
  rw [← hPt, ← hut, he (σ : Ω ≃ₐ[k] Ω) u, hσu]
