/-
AlgebraicIntegerConjugacy.lean — own work for the Fermat project.

**`Γ ℚ` acts transitively on the valuation subrings of `ℚ̄` lying over a
prime number `q`.**

This is the classical conjugacy of the extensions of `v_q` to an algebraic
closure of `ℚ`, proven here in the form the Frey-curve local frame needs
(`GaloisRepresentation.exists_smul_eq_globalValuationSubring` in
`FreyCurve/MazurTorsion.lean`).

THE ARGUMENT, in four steps.

1. *The centre.* Every valuation subring `B ⊆ ℚ̄` contains the ring
   `𝒪 = integralClosure ℤ ℚ̄` of ALL algebraic integers, because a valuation
   subring is integrally closed in its fraction field. So `B` has a centre
   `center B = 𝔪_B ∩ 𝒪`, a prime of `𝒪`; and `(q : ℚ̄)⁻¹ ∉ B` says exactly
   that this centre lies over `(q) ⊆ ℤ`.

2. *Transitivity on primes.* `Γ ℚ` is profinite, acts continuously on the
   discrete ring `𝒪`, and `Algebra.IsInvariant ℤ 𝒪 (Γ ℚ)` holds (a fixed
   algebraic integer is rational by infinite Galois theory, hence a rational
   integer because `ℤ` is integrally closed). Mathlib's
   `Algebra.IsInvariant.exists_smul_of_under_eq_of_profinite` then gives
   transitivity on the primes of `𝒪` over `(q)`.

3. *Injectivity.* A valuation subring lying over `q` is DETERMINED by its
   centre. This is where the Prüfer property of `𝒪` enters, and it is proven
   here by descending to the number field `ℚ(x)` generated by a single
   element: mathlib's
   `IsDedekindDomain.HeightOneSpectrum.exists_primeCompl_mul_eq_or_mul_eq`
   writes `x` as `n/d` or `d/n` with `d` outside the prime, which is exactly
   the statement that the localisation of `𝒪` at the centre is a valuation
   ring. Two valuation subrings with the same centre then contain each other.

4. *The pinned subring is over `q`.* `1/q` is not integral over `𝒪ᵥ = ℤ_q`,
   because `ℤ_q` is integrally closed in `ℚ_q` and `q` lies in its maximal
   ideal (`maximalIdeal_adicCompletionIntegers_eq_span`).

FAITHFULNESS. The hypothesis `(q : ℚ̄)⁻¹ ∉ B` cannot be dropped and cannot be
weakened to `B ≠ ⊤`: `B ∩ ℚ` is a valuation subring of `ℚ` containing `ℤ`,
hence `ℤ_(ℓ)` for a prime `ℓ`, or `ℚ`; the hypothesis excludes `ℚ` and every
`ℓ ≠ q` at once, and without it the conclusion is false — a subring above a
different prime `ℓ` has centre over `(ℓ) ≠ (q)`, and `Γ ℚ` preserves the
centre's contraction to `ℤ`, so no `γ` can carry it to the pinned subring.
-/
module

public import Mathlib.RingTheory.Invariant.Profinite
public import Mathlib.FieldTheory.Galois.Infinite
public import Mathlib.FieldTheory.Galois.Profinite
public import Mathlib.RingTheory.Valuation.LocalSubring
public import Mathlib.RingTheory.DedekindDomain.AdicValuation
public import Mathlib.NumberTheory.NumberField.Basic
public import Fermat.FLT.Deformations.RepresentationTheory.AbsoluteGaloisGroup
public import Fermat.FLT.Mathlib.RingTheory.DedekindDomain.Ideal.Lemmas

@[expose] public section

open scoped Pointwise NumberField
open IsDedekindDomain

namespace AlgebraicIntegersRat

/-- **`ℚ̄/ℚ` is Galois**, proven by hand: `inferInstance` fails because typeclass
search finds `DivisionRing.toRatAlgebra` for `Algebra ℚ (AlgebraicClosure ℚ)`
while mathlib's instances are stated for `AlgebraicClosure.instAlgebra`; the two
are propositionally but not syntactically equal. (Same trick as
`isGalois_rat_algebraicClosure` in `Modularity/Interface.lean`; repeated here so
that this module does not have to import that 80k-line file.) -/
theorem isGalois_rat : IsGalois ℚ (AlgebraicClosure ℚ) :=
  cast (congrArg (fun (i : Algebra ℚ (AlgebraicClosure ℚ)) =>
      @IsGalois ℚ _ (AlgebraicClosure ℚ) _ i)
    (Subsingleton.elim (AlgebraicClosure.instAlgebra ℚ (R := ℚ)) inferInstance))
    (inferInstance :
      @IsGalois ℚ _ (AlgebraicClosure ℚ) _ (AlgebraicClosure.instAlgebra ℚ (R := ℚ)))

attribute [local instance] isGalois_rat

/-- The ring of ALL algebraic integers: the integral closure of `ℤ` in `ℚ̄`. -/
noncomputable abbrev AlgInt := integralClosure ℤ (AlgebraicClosure ℚ)

/-- **`Algebra.IsInvariant ℤ 𝒪 (Γ ℚ)`**: an algebraic integer fixed by the whole
absolute Galois group lies in `ℚ` (infinite Galois theory) and is integral over
`ℤ`, hence lies in `ℤ` because `ℤ` is integrally closed. -/
instance instIsInvariant :
    Algebra.IsInvariant ℤ AlgInt (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) := by
  refine ⟨fun b hb => ?_⟩
  have hfix : ∀ g : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ, g (b : AlgebraicClosure ℚ)
      = (b : AlgebraicClosure ℚ) := fun g => congrArg Subtype.val (hb g)
  have hbot : (b : AlgebraicClosure ℚ) ∈ (⊥ : IntermediateField ℚ (AlgebraicClosure ℚ)) :=
    (InfiniteGalois.mem_bot_iff_fixed _).mpr hfix
  obtain ⟨r, hr⟩ := IntermediateField.mem_bot.mp hbot
  have hint : IsIntegral ℤ r :=
    (isIntegral_algebraMap_iff (R := ℤ) (A := ℚ) (B := AlgebraicClosure ℚ)
      (algebraMap ℚ (AlgebraicClosure ℚ)).injective).mp (by rw [hr]; exact b.2)
  obtain ⟨a, ha⟩ := IsIntegrallyClosed.algebraMap_eq_of_integral hint
  refine ⟨a, Subtype.ext ?_⟩
  have hcast : (algebraMap ℤ (AlgebraicClosure ℚ)) a = (b : AlgebraicClosure ℚ) := by
    rw [IsScalarTower.algebraMap_apply ℤ ℚ (AlgebraicClosure ℚ), ha, hr]
  simpa using hcast

/-- **`Γ ℚ` acts transitively on the primes of `𝒪` over a given prime of `ℤ`.**
`Γ ℚ` is profinite and acts continuously on the discrete ring `𝒪` (each
stabiliser is open by `stabilizer_isOpen_of_isIntegral`), so mathlib's profinite
form of the invariant-extension theorem applies. -/
theorem exists_smul_eq_of_under_eq
    (P Q : Ideal AlgInt) [P.IsPrime] [Q.IsPrime] (h : P.under ℤ = Q.under ℤ) :
    ∃ g : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ, Q = g • P := by
  letI : TopologicalSpace AlgInt := ⊥
  haveI : DiscreteTopology AlgInt := ⟨rfl⟩
  haveI : ContinuousSMul (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) AlgInt := by
    rw [continuousSMul_iff_stabilizer_isOpen]
    intro x
    have hop := stabilizer_isOpen_of_isIntegral (K := ℚ) (L := AlgebraicClosure ℚ)
      (x : AlgebraicClosure ℚ)
    convert hop using 2
    ext g
    simp only [MulAction.mem_stabilizer_iff]
    exact ⟨fun hg => congrArg Subtype.val hg, fun hg => Subtype.ext hg⟩
  exact Algebra.IsInvariant.exists_smul_of_under_eq_of_profinite P Q h

/-! ### Valuation subrings of `ℚ̄` and their centres on the algebraic integers -/

/-- Every algebraic integer lies in every valuation subring of `ℚ̄`: a valuation
subring is integrally closed in its fraction field. -/
theorem mem_of_isIntegral (B : ValuationSubring (AlgebraicClosure ℚ))
    {x : AlgebraicClosure ℚ} (hx : IsIntegral ℤ x) : x ∈ B := by
  have hxB : IsIntegral B x := hx.tower_top
  obtain ⟨y, hy⟩ := IsIntegrallyClosed.isIntegral_iff.mp hxB
  exact hy ▸ y.2

/-- The structural map from the algebraic integers into any valuation subring of `ℚ̄`. -/
noncomputable def toValuationSubring (B : ValuationSubring (AlgebraicClosure ℚ)) :
    AlgInt →+* B where
  toFun a := ⟨(a : AlgebraicClosure ℚ), mem_of_isIntegral B a.2⟩
  map_one' := rfl
  map_mul' _ _ := rfl
  map_zero' := rfl
  map_add' _ _ := rfl

@[simp] theorem coe_toValuationSubring (B : ValuationSubring (AlgebraicClosure ℚ)) (a : AlgInt) :
    ((toValuationSubring B a : B) : AlgebraicClosure ℚ) = (a : AlgebraicClosure ℚ) := rfl

/-- **The centre** of a valuation subring of `ℚ̄` on the ring of all algebraic integers. -/
noncomputable def center (B : ValuationSubring (AlgebraicClosure ℚ)) : Ideal AlgInt :=
  (IsLocalRing.maximalIdeal B).comap (toValuationSubring B)

theorem mem_center_iff (B : ValuationSubring (AlgebraicClosure ℚ)) (a : AlgInt) :
    a ∈ center B ↔ (a : AlgebraicClosure ℚ) ∈ B.nonunits := by
  rw [center, Ideal.mem_comap, ← ValuationSubring.coe_mem_nonunits_iff]
  rfl

instance (B : ValuationSubring (AlgebraicClosure ℚ)) : (center B).IsPrime :=
  Ideal.comap_isPrime _ _

/-- An algebraic integer outside the centre of `B` is nonzero and invertible in `B`. -/
theorem inv_mem_of_notMem_center (B : ValuationSubring (AlgebraicClosure ℚ))
    {s : AlgInt} (hs : s ∉ center B) :
    (s : AlgebraicClosure ℚ) ≠ 0 ∧ ((s : AlgebraicClosure ℚ))⁻¹ ∈ B := by
  refine ⟨?_, ?_⟩
  · rintro h0
    exact hs ((mem_center_iff B s).2 (by rw [h0]; exact (B.nonunits).zero_mem))
  · by_contra hc
    exact hs ((mem_center_iff B s).2 ((ValuationSubring.mem_nonunits_iff_or B).2 (Or.inr hc)))

/-- A fraction whose denominator is an algebraic integer outside the centre lies in `B`. -/
theorem div_mem_of_notMem_center (B : ValuationSubring (AlgebraicClosure ℚ))
    {s a : AlgInt} (hs : s ∉ center B) (x : AlgebraicClosure ℚ)
    (hx : (s : AlgebraicClosure ℚ) * x = (a : AlgebraicClosure ℚ)) : x ∈ B := by
  obtain ⟨hs0, hsinv⟩ := inv_mem_of_notMem_center B hs
  have hxeq : x = ((s : AlgebraicClosure ℚ))⁻¹ * (a : AlgebraicClosure ℚ) := by
    rw [← hx, inv_mul_cancel_left₀ hs0]
  rw [hxeq]
  exact B.mul_mem _ _ hsinv (mem_of_isIntegral B a.2)

/-- The centre transforms equivariantly under the Galois action. -/
theorem center_smul (g : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ)
    (B : ValuationSubring (AlgebraicClosure ℚ)) : center (g • B) = g • center B := by
  ext a
  rw [Ideal.mem_pointwise_smul_iff_inv_smul_mem, mem_center_iff, mem_center_iff]
  have hcoe : ((g⁻¹ • a : AlgInt) : AlgebraicClosure ℚ) = g⁻¹ (a : AlgebraicClosure ℚ) := rfl
  rw [hcoe, ValuationSubring.mem_nonunits_iff_or, ValuationSubring.mem_nonunits_iff_or]
  have h0 : ((a : AlgebraicClosure ℚ) = 0) ↔ (g⁻¹ (a : AlgebraicClosure ℚ) = 0) := by simp
  have h1 : ((a : AlgebraicClosure ℚ))⁻¹ ∈ g • B ↔ (g⁻¹ (a : AlgebraicClosure ℚ))⁻¹ ∈ B := by
    rw [ValuationSubring.mem_pointwise_smul_iff_inv_smul_mem]
    show (g⁻¹ ((a : AlgebraicClosure ℚ))⁻¹ ∈ B) ↔ _
    rw [map_inv₀]
  rw [h0, h1]

/-- **A valuation subring of `ℚ̄` not containing `1/q` has centre lying over `(q)`.** -/
theorem under_center_eq {q : ℕ} (hq : q.Prime) (B : ValuationSubring (AlgebraicClosure ℚ))
    (hB : (algebraMap ℚ (AlgebraicClosure ℚ) (q : ℚ))⁻¹ ∉ B) :
    (center B).under ℤ = Ideal.span {(q : ℤ)} := by
  haveI : (Ideal.under ℤ (center B)).IsPrime := Ideal.IsPrime.under ℤ _
  have hqmem : (q : ℤ) ∈ (center B).under ℤ := by
    rw [Ideal.mem_comap, mem_center_iff]
    refine (ValuationSubring.mem_nonunits_iff_or B).2 (Or.inr ?_)
    have hcast : ((algebraMap ℤ AlgInt (q : ℤ) : AlgInt) : AlgebraicClosure ℚ)
        = algebraMap ℚ (AlgebraicClosure ℚ) (q : ℚ) := by
      have h1 : ((algebraMap ℤ AlgInt (q : ℤ) : AlgInt) : AlgebraicClosure ℚ)
          = ((q : ℤ) : AlgebraicClosure ℚ) := by push_cast; rfl
      rw [h1]
      push_cast
      rfl
    rw [hcast]
    exact hB
  have hne : (center B).under ℤ ≠ ⊤ := by
    intro htop
    have h1 : (1 : ℤ) ∈ (center B).under ℤ := htop ▸ Submodule.mem_top
    rw [Ideal.mem_comap, mem_center_iff] at h1
    have h2 : ((algebraMap ℤ AlgInt (1 : ℤ) : AlgInt) : AlgebraicClosure ℚ) = 1 := by
      push_cast; rfl
    rw [h2] at h1
    simp [ValuationSubring.mem_nonunits_iff_or] at h1
  have hmax : (Ideal.span {(q : ℤ)}).IsMaximal :=
    PrincipalIdealRing.isMaximal_of_irreducible
      (Int.prime_iff_natAbs_prime.mpr (by simpa using hq)).irreducible
  exact ((hmax.eq_of_le hne (Ideal.span_le.2 (by simpa using hqmem)))).symm

/-! ### The Prüfer step: the localisation of `𝒪` at a prime over `q` is a valuation ring -/

/-- The ring of integers of a number subfield of `ℚ̄` maps into the algebraic integers. -/
noncomputable def ringOfIntegersToAlgInt (F : IntermediateField ℚ (AlgebraicClosure ℚ))
    [NumberField F] : 𝓞 F →+* AlgInt where
  toFun z := ⟨F.val (z : F), map_isIntegral_int F.val z.2⟩
  map_one' := Subtype.ext (map_one _)
  map_mul' _ _ := Subtype.ext (map_mul _ _ _)
  map_zero' := Subtype.ext (map_zero _)
  map_add' _ _ := Subtype.ext (map_add _ _ _)

@[simp] theorem coe_ringOfIntegersToAlgInt (F : IntermediateField ℚ (AlgebraicClosure ℚ))
    [NumberField F] (z : 𝓞 F) :
    ((ringOfIntegersToAlgInt F z : AlgInt) : AlgebraicClosure ℚ) = F.val (z : F) := rfl

/-- **The localisation of `𝒪` at a prime lying over a nonzero prime of `ℤ` is a
valuation ring**: every `x : ℚ̄` is `a/s` or `s/a` with `s` an algebraic integer
outside `P`. Proven by descending to the number field `ℚ(x)`, where the statement
is mathlib's `exists_primeCompl_mul_eq_or_mul_eq` for a Dedekind domain. -/
theorem exists_den_notMem (P : Ideal AlgInt) [P.IsPrime] (hP : P.under ℤ ≠ ⊥)
    (x : AlgebraicClosure ℚ) :
    (∃ s a : AlgInt, s ∉ P ∧ (s : AlgebraicClosure ℚ) * x = (a : AlgebraicClosure ℚ)) ∨
      (∃ s a : AlgInt, s ∉ P ∧ (s : AlgebraicClosure ℚ) * x⁻¹ = (a : AlgebraicClosure ℚ)) := by
  classical
  have hone : (1 : AlgInt) ∉ P := fun h => ‹P.IsPrime›.ne_top ((Ideal.eq_top_iff_one P).2 h)
  rcases eq_or_ne x 0 with rfl | hx0
  · exact Or.inl ⟨1, 0, hone, by simp⟩
  set F := IntermediateField.adjoin ℚ ({x} : Set (AlgebraicClosure ℚ)) with hFdef
  haveI : FiniteDimensional ℚ F :=
    IntermediateField.adjoin.finiteDimensional (Algebra.IsIntegral.isIntegral x)
  haveI : NumberField F := ⟨⟩
  set ι := ringOfIntegersToAlgInt F with hι
  set PF : Ideal (𝓞 F) := P.comap ι with hPF
  haveI : PF.IsPrime := Ideal.comap_isPrime _ _
  have hPFne : PF ≠ ⊥ := by
    obtain ⟨m, hm, hm0⟩ : ∃ m : ℤ, m ∈ P.under ℤ ∧ m ≠ 0 := by
      by_contra hc
      simp only [not_exists, not_and, ne_eq, not_not] at hc
      exact hP (by
        ext m
        simp only [Ideal.mem_bot]
        exact ⟨fun h => hc m h, fun h => h ▸ Submodule.zero_mem _⟩)
    intro hbot
    have hmem : (m : 𝓞 F) ∈ PF := by
      rw [hPF, Ideal.mem_comap]
      have hmap : ι (m : 𝓞 F) = algebraMap ℤ AlgInt m := by simp [map_intCast ι m]
      rw [hmap]
      exact hm
    rw [hbot, Ideal.mem_bot] at hmem
    exact hm0 (by exact_mod_cast hmem)
  let v : HeightOneSpectrum (𝓞 F) := ⟨PF, inferInstance, hPFne⟩
  have hxF : x ∈ F := IntermediateField.subset_adjoin ℚ _ rfl
  obtain ⟨n, d, hnd⟩ :=
    HeightOneSpectrum.exists_primeCompl_mul_eq_or_mul_eq (R := 𝓞 F) (K := F) v (⟨x, hxF⟩ : F)
  have hdP : ι (d : 𝓞 F) ∉ P := fun hc => d.2 hc
  have hval : ∀ z : 𝓞 F, F.val (algebraMap (𝓞 F) F z) = ((ι z : AlgInt) : AlgebraicClosure ℚ) :=
    fun _ => rfl
  rcases hnd with h | h
  · refine Or.inl ⟨ι (d : 𝓞 F), ι n, hdP, ?_⟩
    have hc := congrArg F.val h
    rw [map_mul, hval, hval] at hc
    simpa [mul_comm] using hc
  · refine Or.inr ⟨ι (d : 𝓞 F), ι n, hdP, ?_⟩
    have hc := congrArg F.val h
    rw [map_mul, hval, hval] at hc
    have hx : (F.val (⟨x, hxF⟩ : F)) = x := rfl
    rw [hx] at hc
    rw [← hc, mul_comm x _, mul_assoc, mul_inv_cancel₀ hx0, mul_one]

/-- **A valuation subring of `ℚ̄` whose centre lies over a nonzero prime of `ℤ` is
determined by its centre.** -/
theorem eq_of_center_eq {B₁ B₂ : ValuationSubring (AlgebraicClosure ℚ)}
    (hne : (center B₁).under ℤ ≠ ⊥) (h : center B₁ = center B₂) : B₁ = B₂ := by
  have key : ∀ C₁ C₂ : ValuationSubring (AlgebraicClosure ℚ), (center C₁).under ℤ ≠ ⊥ →
      center C₁ = center C₂ → C₁ ≤ C₂ := by
    intro C₁ C₂ hne' h' x hx
    rcases eq_or_ne x 0 with rfl | hx0
    · exact C₂.zero_mem
    rcases exists_den_notMem (center C₁) hne' x with ⟨s, a, hs, hsa⟩ | ⟨s, a, hs, hsa⟩
    · exact div_mem_of_notMem_center C₂ (h' ▸ hs) x hsa
    · -- `x⁻¹ = a/s` lies in `C₁` and `x ∈ C₁`, so `a` is a unit of `C₁`
      obtain ⟨hs0, hsinv⟩ := inv_mem_of_notMem_center C₁ hs
      have hxinv : x⁻¹ ∈ C₁ := div_mem_of_notMem_center C₁ hs x⁻¹ hsa
      have ha : a ∉ center C₁ := by
        intro hac
        rcases (ValuationSubring.mem_nonunits_iff_or C₁).1 ((mem_center_iff C₁ a).1 hac) with
          h0 | hinv
        · rw [← hsa] at h0
          exact hx0 (inv_eq_zero.1 (by
            rcases mul_eq_zero.1 h0 with hz | hz
            · exact absurd hz hs0
            · exact hz))
        · refine hinv ?_
          have haeq : ((a : AlgebraicClosure ℚ))⁻¹ = ((s : AlgebraicClosure ℚ))⁻¹ * x := by
            rw [← hsa]
            field_simp
          rw [haeq]
          exact C₁.mul_mem _ _ hsinv hx
      refine div_mem_of_notMem_center (s := a) (a := s) C₂ (h' ▸ ha) x ?_
      rw [← hsa]
      field_simp
  exact le_antisymm (key B₁ B₂ hne h) (key B₂ B₁ (h ▸ hne) h.symm)

/-- **`Γ ℚ` ACTS TRANSITIVELY ON THE VALUATION SUBRINGS OF `ℚ̄` ABOVE `q`.**

The hypothesis `(q : ℚ̄)⁻¹ ∉ Bᵢ` is exactly `Bᵢ ∩ ℚ = ℤ_(q)`; see the module
docstring for why it is load-bearing. -/
theorem exists_smul_eq_of_valuationSubring {q : ℕ} (hq : q.Prime)
    (B₁ B₂ : ValuationSubring (AlgebraicClosure ℚ))
    (h₁ : (algebraMap ℚ (AlgebraicClosure ℚ) (q : ℚ))⁻¹ ∉ B₁)
    (h₂ : (algebraMap ℚ (AlgebraicClosure ℚ) (q : ℚ))⁻¹ ∉ B₂) :
    ∃ γ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ, γ • B₁ = B₂ := by
  have hu : (center B₁).under ℤ = (center B₂).under ℤ := by
    rw [under_center_eq hq B₁ h₁, under_center_eq hq B₂ h₂]
  obtain ⟨g, hg⟩ := exists_smul_eq_of_under_eq (center B₁) (center B₂) hu
  refine ⟨g, ?_⟩
  have hqg : (algebraMap ℚ (AlgebraicClosure ℚ) (q : ℚ))⁻¹ ∉ g • B₁ := by
    rw [ValuationSubring.mem_pointwise_smul_iff_inv_smul_mem]
    have hfix : (g⁻¹ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) •
        (algebraMap ℚ (AlgebraicClosure ℚ) (q : ℚ))⁻¹
        = (algebraMap ℚ (AlgebraicClosure ℚ) (q : ℚ))⁻¹ := by
      show g⁻¹ ((algebraMap ℚ (AlgebraicClosure ℚ) (q : ℚ))⁻¹) = _
      rw [map_inv₀, AlgEquiv.commutes]
    rw [hfix]
    exact h₁
  have hne : (center (g • B₁)).under ℤ ≠ ⊥ := by
    rw [under_center_eq hq _ hqg]
    intro hbot
    have hz : (q : ℤ) ∈ (⊥ : Ideal ℤ) := hbot ▸ Ideal.mem_span_singleton_self _
    rw [Ideal.mem_bot] at hz
    exact hq.ne_zero (by exact_mod_cast hz)
  exact eq_of_center_eq hne (by rw [center_smul, ← hg])

/-! ### The pinned subring of `ℚ̄` above `q` lies over `q` -/

/-- **`1/q` is not in the pinned valuation subring of `ℚ̄` above `q`** — i.e. the
comap along the fixed embedding `ℚ̄ ↪ ℚ̄_q` of the integral closure of `𝒪ᵥ`.
`1/q` would have to be integral over `𝒪ᵥ`, hence (as `𝒪ᵥ` is integrally closed in
`ℚ_q`) lie in `𝒪ᵥ`, making `q` a unit there against
`maximalIdeal_adicCompletionIntegers_eq_span`.

This is `GaloisRepresentation.globalValuationSubring hq.toHeightOneSpectrumRingOfIntegersRat`
spelled out; that definition lives in `FreyCurve/MazurTorsion.lean`, downstream of
this module. -/
theorem inv_natCast_notMem_comap_localValuationSubring {q : ℕ} (hq : q.Prime) :
    (algebraMap ℚ (AlgebraicClosure ℚ) (q : ℚ))⁻¹ ∉
      (localValuationSubring hq.toHeightOneSpectrumRingOfIntegersRat).comap
        (AlgebraicClosure.map (algebraMap ℚ
          (HeightOneSpectrum.adicCompletion ℚ hq.toHeightOneSpectrumRingOfIntegersRat))) := by
  set v := hq.toHeightOneSpectrumRingOfIntegersRat with hv
  set Kv := HeightOneSpectrum.adicCompletion ℚ v with hKv
  set Ov := HeightOneSpectrum.adicCompletionIntegers ℚ v with hOv
  intro hmem
  have hint : IsIntegral Ov
      (AlgebraicClosure.map (algebraMap ℚ Kv) ((algebraMap ℚ (AlgebraicClosure ℚ) (q : ℚ))⁻¹)) :=
    hmem
  have himg : AlgebraicClosure.map (algebraMap ℚ Kv)
      ((algebraMap ℚ (AlgebraicClosure ℚ) (q : ℚ))⁻¹)
      = algebraMap Kv (AlgebraicClosure Kv) ((q : Kv)⁻¹) := by
    rw [map_inv₀, map_inv₀]
    congr 1
    rw [show (algebraMap ℚ (AlgebraicClosure ℚ)) (q : ℚ) = ((q : ℕ) : AlgebraicClosure ℚ) by
      push_cast; rfl, map_natCast, map_natCast]
  rw [himg] at hint
  have hint' : IsIntegral Ov ((q : Kv)⁻¹) :=
    (isIntegral_algebraMap_iff (R := Ov) (A := Kv) (B := AlgebraicClosure Kv)
      (algebraMap Kv (AlgebraicClosure Kv)).injective).mp hint
  obtain ⟨y, hy⟩ := IsIntegrallyClosed.isIntegral_iff.mp hint'
  have hqmem : ((q : ℕ) : Ov) ∈ IsLocalRing.maximalIdeal Ov := by
    rw [maximalIdeal_adicCompletionIntegers_eq_span hq]
    exact Ideal.mem_span_singleton_self _
  have hmul : ((q : ℕ) : Ov) * y = 1 := by
    apply (IsFractionRing.injective Ov Kv)
    rw [map_mul, hy, map_one, map_natCast]
    refine mul_inv_cancel₀ ?_
    have hc : ((q : ℕ) : Kv) = algebraMap ℚ Kv (q : ℚ) := by push_cast; rfl
    rw [hc]
    exact (map_ne_zero_iff _ (algebraMap ℚ Kv).injective).2 (Nat.cast_ne_zero.2 hq.pos.ne')
  exact (IsLocalRing.mem_maximalIdeal _).mp hqmem
    ⟨⟨_, y, hmul, by rw [mul_comm]; exact hmul⟩, rfl⟩

end AlgebraicIntegersRat
