/-
Copyright (c) 2026 Kevin Buzzard. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Michael Stoll, Claude
-/
module

public import Fermat.FLT.EllipticCurve.MazurNonCMCertificate
public import Fermat.FLT.EllipticCurve.MazurNonCMFrobenius.ThirtySevenB

/-!
# Row `p = 37`, `j = −162677523113838677`: the mod-`1259` certificate

Generated by `gen_thirtyseven.py`.  The EDS chain `Ψ₂Sq, Ψ₃, preΨ₄, preΨ' 5 … 12, 17 … 20`
re-derives `preΨ' 37 mod 1259` from mathlib's recursion and factors it as
`C 37 * (D * H)`; `not_monic_dvd_of_smallDegreePart'` then turns the two computational leaves
proven in `MazurNonCMFrobenius/ThirtySevenB.lean` (`H ∣ X ^ (1259 ^ 37) - X` at `m = 37` PRIME, and
`IsCoprime H (X ^ 1259 - X)` at the single small divisor `d = 1`) into the row's obstruction.

Every polynomial here is carried as `npoly 1259 <coefficient list>`; each recursion step is
one `decide` on a list identity.  See `MazurNonCMReflect.lean` for why this shape.
-/

@[expose] public section

open Polynomial

set_option maxRecDepth 20000
set_option maxHeartbeats 4000000

-- Generated code: which cast/map lemmas fire varies with the coefficient values of each
-- instance, so the per-instance simp sets are deliberately uniform.
set_option linter.unusedSimpArgs false

namespace Fermat.MazurNonCMCertificate

/-- The minimal model `[1, 1, 1, -208083, -36621194]` of the `p = 37`, `j = −162677523113838677`
row, read over `ZMod 1259`.  Definitionally `Fermat.nonCMModelThirtySevenBmod`. -/
def thirtySevenBMod : WeierstrassCurve (ZMod 1259) := ⟨1, 1, 1, -208083, -36621194⟩

/-- The product of the eighteen linear factors of `Ψ₃₇ mod 1259` on this row. -/
noncomputable def dPolyThirtySevenB : (ZMod 1259)[X] :=
  X^18 + 763*X^17 + 162*X^16 + 1020*X^15 + 1114*X^14 + 294*X^13 + 591*X^12 + 72*X^11 +
    826*X^10 + 414*X^9 + 974*X^8 + 847*X^7 + 1155*X^6 + 1252*X^5 + 758*X^4 + 313*X^3 + 178*X^2 +
    340*X + 863

theorem Ψ₂Sq_thirtySevenBMod : thirtySevenBMod.Ψ₂Sq =
    4*X^3 + 5*X^2 + 1128*X + 1134 := by
  rw [WeierstrassCurve.Ψ₂Sq]
  simp only [thirtySevenBMod, WeierstrassCurve.b₂, WeierstrassCurve.b₄, WeierstrassCurve.b₆,
    map_ofNat, C_neg, C_add, C_sub, C_mul, C_pow, C_1, C_0]
  reduce_mod_char

theorem Ψ₃_thirtySevenBMod : thirtySevenBMod.Ψ₃ =
    3*X^4 + 5*X^3 + 433*X^2 + 884*X + 581 := by
  rw [WeierstrassCurve.Ψ₃]
  simp only [thirtySevenBMod, WeierstrassCurve.b₂, WeierstrassCurve.b₄, WeierstrassCurve.b₆, WeierstrassCurve.b₈,
    map_ofNat, C_neg, C_add, C_sub, C_mul, C_pow, C_1, C_0]
  reduce_mod_char

theorem preΨ₄_thirtySevenBMod : thirtySevenBMod.preΨ₄ =
    2*X^6 + 5*X^5 + 302*X^4 + 9*X^3 + 774*X^2 + 383*X + 1086 := by
  rw [WeierstrassCurve.preΨ₄]
  simp only [thirtySevenBMod, WeierstrassCurve.b₂, WeierstrassCurve.b₄, WeierstrassCurve.b₆, WeierstrassCurve.b₈,
    map_ofNat, C_neg, C_add, C_sub, C_mul, C_pow, C_1, C_0]
  reduce_mod_char

theorem Ψ₂Sq_npoly_ThirtySevenB : thirtySevenBMod.Ψ₂Sq = npoly 1259
    ([1134, 1128, 5, 4]) := by
  rw [Ψ₂Sq_thirtySevenBMod]
  simp only [npoly, Nat.cast_ofNat, Nat.cast_one, Nat.cast_zero, map_ofNat, map_one, map_zero]
  ring

theorem Ψ₃_npoly_ThirtySevenB : thirtySevenBMod.Ψ₃ = npoly 1259
    ([581, 884, 433, 5, 3]) := by
  rw [Ψ₃_thirtySevenBMod]
  simp only [npoly, Nat.cast_ofNat, Nat.cast_one, Nat.cast_zero, map_ofNat, map_one, map_zero]
  ring

theorem preΨ₄_npoly_ThirtySevenB : thirtySevenBMod.preΨ₄ = npoly 1259
    ([1086, 383, 774, 9, 302, 5, 2]) := by
  rw [preΨ₄_thirtySevenBMod]
  simp only [npoly, Nat.cast_ofNat, Nat.cast_one, Nat.cast_zero, map_ofNat, map_one, map_zero]
  ring

theorem dPoly_npoly_ThirtySevenB : dPolyThirtySevenB = npoly 1259
    ([863, 340, 178, 313, 758, 1252, 1155, 847, 974, 414, 826, 72, 591, 294, 1114, 1020, 162,
      763, 1]) := by
  simp only [dPolyThirtySevenB, npoly, Nat.cast_ofNat, Nat.cast_one, Nat.cast_zero, map_ofNat, map_one,
    map_zero]
  ring

theorem C37_npoly_ThirtySevenB : (C 37 : (ZMod 1259)[X]) = npoly 1259 [37] := by
  simp [npoly, Nat.cast_ofNat]

theorem preΨ'_five_ThirtySevenB : thirtySevenBMod.preΨ' 5 = npoly 1259
    ([250, 276, 1093, 879, 723, 758, 807, 957, 146, 1217, 1142, 25, 5]) := by
  have h := thirtySevenBMod.preΨ'_odd 0
  norm_num [WeierstrassCurve.preΨ'_one, WeierstrassCurve.preΨ'_two, WeierstrassCurve.preΨ'_three, WeierstrassCurve.preΨ'_four] at h
  rw [h, preΨ₄_npoly_ThirtySevenB, Ψ₃_npoly_ThirtySevenB, Ψ₂Sq_npoly_ThirtySevenB]
  simp only [← npoly_npow, ← npoly_nmul, sub_eq_add_neg, ← npoly_nneg, ← npoly_nadd]
  exact congrArg (npoly 1259) (by decide)

theorem preΨ'_six_ThirtySevenB : thirtySevenBMod.preΨ' 6 = npoly 1259
    ([1024, 600, 626, 1208, 231, 173, 237, 643, 546, 558, 861, 1119, 1011, 854, 185, 20, 3]) := by
  have h := thirtySevenBMod.preΨ'_even 0
  norm_num [WeierstrassCurve.preΨ'_one, WeierstrassCurve.preΨ'_two, WeierstrassCurve.preΨ'_three, WeierstrassCurve.preΨ'_four] at h
  rw [h, Ψ₃_npoly_ThirtySevenB, preΨ'_five_ThirtySevenB, preΨ₄_npoly_ThirtySevenB]
  simp only [← npoly_npow, ← npoly_nmul, sub_eq_add_neg, ← npoly_nneg, ← npoly_nadd]
  exact congrArg (npoly 1259) (by decide)

theorem preΨ'_seven_ThirtySevenB : thirtySevenBMod.preΨ' 7 = npoly 1259
    ([224, 565, 393, 697, 551, 89, 595, 302, 529, 156, 109, 291, 77, 1183, 145, 659, 621, 212,
      231, 261, 527, 641, 160, 70, 7]) := by
  have h := thirtySevenBMod.preΨ'_odd 1
  norm_num [WeierstrassCurve.preΨ'_one, WeierstrassCurve.preΨ'_two, WeierstrassCurve.preΨ'_three, WeierstrassCurve.preΨ'_four] at h
  rw [h, preΨ'_five_ThirtySevenB, Ψ₃_npoly_ThirtySevenB, preΨ₄_npoly_ThirtySevenB, Ψ₂Sq_npoly_ThirtySevenB]
  simp only [← npoly_npow, ← npoly_nmul, sub_eq_add_neg, ← npoly_nneg, ← npoly_nadd]
  exact congrArg (npoly 1259) (by decide)

theorem preΨ'_eight_ThirtySevenB : thirtySevenBMod.preΨ' 8 = npoly 1259
    ([754, 636, 619, 819, 341, 980, 474, 631, 766, 176, 479, 1055, 1097, 752, 713, 951, 644,
      692, 1119, 176, 652, 120, 1106, 1050, 905, 876, 233, 576, 659, 50, 4]) := by
  have h := thirtySevenBMod.preΨ'_even 1
  norm_num [WeierstrassCurve.preΨ'_one, WeierstrassCurve.preΨ'_two, WeierstrassCurve.preΨ'_three, WeierstrassCurve.preΨ'_four] at h
  rw [h, Ψ₃_npoly_ThirtySevenB, preΨ₄_npoly_ThirtySevenB, preΨ'_six_ThirtySevenB, preΨ'_five_ThirtySevenB]
  simp only [← npoly_npow, ← npoly_nmul, sub_eq_add_neg, ← npoly_nneg, ← npoly_nadd]
  exact congrArg (npoly 1259) (by decide)

theorem preΨ'_nine_ThirtySevenB : thirtySevenBMod.preΨ' 9 = npoly 1259
    ([690, 1074, 799, 172, 152, 244, 1160, 645, 765, 415, 1020, 67, 854, 798, 1062, 1039, 1065,
      363, 1072, 562, 768, 675, 849, 254, 46, 607, 1119, 345, 587, 93, 1176, 1017, 540, 213,
      1258, 41, 255, 961, 477, 150, 9]) := by
  have h := thirtySevenBMod.preΨ'_odd 2
  norm_num [WeierstrassCurve.preΨ'_three, WeierstrassCurve.preΨ'_four, Nat.even_iff] at h
  rw [h, preΨ'_six_ThirtySevenB, preΨ₄_npoly_ThirtySevenB, Ψ₃_npoly_ThirtySevenB, preΨ'_five_ThirtySevenB, Ψ₂Sq_npoly_ThirtySevenB]
  simp only [← npoly_npow, ← npoly_nmul, sub_eq_add_neg, ← npoly_nneg, ← npoly_nadd]
  exact congrArg (npoly 1259) (by decide)

theorem preΨ'_ten_ThirtySevenB : thirtySevenBMod.preΨ' 10 = npoly 1259
    ([592, 269, 1175, 837, 689, 693, 190, 1177, 999, 918, 912, 910, 716, 661, 257, 331, 883,
      1023, 929, 65, 677, 729, 732, 506, 1145, 241, 1256, 840, 382, 393, 137, 1176, 1004, 410,
      831, 567, 68, 868, 1148, 252, 285, 1242, 300, 823, 194, 867, 924, 100, 5]) := by
  have h := thirtySevenBMod.preΨ'_even 2
  norm_num [WeierstrassCurve.preΨ'_three, WeierstrassCurve.preΨ'_four] at h
  rw [h, preΨ₄_npoly_ThirtySevenB, preΨ'_five_ThirtySevenB, preΨ'_seven_ThirtySevenB, Ψ₃_npoly_ThirtySevenB, preΨ'_six_ThirtySevenB]
  simp only [← npoly_npow, ← npoly_nmul, sub_eq_add_neg, ← npoly_nneg, ← npoly_nadd]
  exact congrArg (npoly 1259) (by decide)

theorem preΨ'_eleven_ThirtySevenB : thirtySevenBMod.preΨ' 11 = npoly 1259
    ([1083, 1209, 59, 1078, 517, 1000, 449, 583, 789, 157, 849, 169, 380, 69, 260, 456, 1182,
      849, 345, 958, 746, 184, 988, 703, 379, 385, 8, 302, 474, 997, 1, 1033, 607, 28, 6, 333,
      1113, 915, 911, 253, 588, 56, 1210, 234, 133, 367, 751, 1233, 840, 224, 659, 483, 59, 514,
      528, 276, 66, 229, 440, 275, 11]) := by
  have h := thirtySevenBMod.preΨ'_odd 3
  norm_num [WeierstrassCurve.preΨ'_three, WeierstrassCurve.preΨ'_four, Nat.even_iff] at h
  rw [h, preΨ'_seven_ThirtySevenB, preΨ'_five_ThirtySevenB, preΨ₄_npoly_ThirtySevenB, preΨ'_six_ThirtySevenB, Ψ₂Sq_npoly_ThirtySevenB]
  simp only [← npoly_npow, ← npoly_nmul, sub_eq_add_neg, ← npoly_nneg, ← npoly_nadd]
  exact congrArg (npoly 1259) (by decide)

theorem preΨ'_twelve_ThirtySevenB : thirtySevenBMod.preΨ' 12 = npoly 1259
    ([54, 274, 876, 943, 643, 731, 740, 307, 584, 248, 570, 236, 533, 395, 144, 691, 1196, 422,
      134, 10, 692, 608, 288, 301, 242, 51, 348, 1025, 756, 767, 987, 227, 330, 958, 225, 658,
      651, 857, 494, 756, 184, 835, 189, 239, 1143, 128, 256, 966, 451, 209, 165, 253, 881, 875,
      990, 1110, 90, 926, 548, 1104, 109, 597, 1081, 26, 1222, 425, 368, 241, 1124, 175, 6]) := by
  have h := thirtySevenBMod.preΨ'_even 3
  norm_num [WeierstrassCurve.preΨ'_three, WeierstrassCurve.preΨ'_four] at h
  rw [h, preΨ'_five_ThirtySevenB, preΨ'_six_ThirtySevenB, preΨ'_eight_ThirtySevenB, preΨ₄_npoly_ThirtySevenB, preΨ'_seven_ThirtySevenB]
  simp only [← npoly_npow, ← npoly_nmul, sub_eq_add_neg, ← npoly_nneg, ← npoly_nadd]
  exact congrArg (npoly 1259) (by decide)

theorem preΨ'_seventeen_ThirtySevenB : thirtySevenBMod.preΨ' 17 = npoly 1259
    ([332, 1102, 12, 630, 185, 7, 718, 679, 341, 42, 639, 1198, 99, 64, 375, 201, 1210, 597,
      1162, 1107, 490, 100, 901, 561, 405, 441, 38, 710, 635, 579, 86, 866, 951, 281, 267, 1072,
      969, 1069, 441, 963, 1019, 973, 218, 37, 107, 852, 83, 1013, 410, 993, 47, 789, 273, 952,
      716, 959, 772, 445, 824, 1011, 846, 94, 215, 448, 30, 549, 261, 456, 1234, 1226, 537,
      1012, 291, 1096, 952, 847, 62, 724, 371, 593, 1056, 210, 1115, 191, 12, 34, 831, 792,
      1129, 1086, 1128, 36, 999, 175, 335, 1025, 659, 862, 104, 1001, 627, 1057, 187, 114, 174,
      336, 452, 882, 381, 1053, 1203, 416, 559, 1167, 240, 835, 771, 188, 1191, 988, 1148, 879,
      937, 150, 505, 25, 326, 113, 236, 727, 265, 123, 918, 7, 1232, 202, 166, 294, 856, 331,
      737, 1195, 0, 1020, 17]) := by
  have h := thirtySevenBMod.preΨ'_odd 6
  norm_num [Nat.even_iff] at h
  rw [h, preΨ'_ten_ThirtySevenB, preΨ'_eight_ThirtySevenB, preΨ'_seven_ThirtySevenB, preΨ'_nine_ThirtySevenB, Ψ₂Sq_npoly_ThirtySevenB]
  simp only [← npoly_npow, ← npoly_nmul, sub_eq_add_neg, ← npoly_nneg, ← npoly_nadd]
  exact congrArg (npoly 1259) (by decide)

theorem preΨ'_eighteen_ThirtySevenB : thirtySevenBMod.preΨ' 18 = npoly 1259
    ([667, 1247, 719, 1035, 232, 1198, 1249, 1237, 625, 621, 654, 447, 169, 718, 712, 349, 910,
      964, 665, 460, 1235, 1202, 843, 742, 589, 18, 79, 955, 744, 1075, 515, 219, 1100, 631,
      1113, 966, 953, 1110, 178, 821, 1084, 890, 969, 896, 848, 679, 647, 83, 559, 485, 858,
      1213, 55, 217, 575, 364, 548, 1169, 820, 4, 61, 611, 927, 843, 1078, 627, 92, 750, 102,
      1038, 366, 760, 1207, 595, 1065, 360, 755, 629, 434, 869, 612, 690, 636, 328, 950, 1237,
      816, 708, 1097, 410, 354, 33, 660, 417, 1140, 393, 27, 245, 73, 316, 584, 225, 8, 562,
      514, 429, 110, 213, 1113, 978, 113, 1199, 1123, 1065, 748, 951, 288, 1163, 533, 979, 609,
      1202, 235, 388, 227, 624, 424, 1132, 272, 339, 894, 921, 651, 349, 307, 290, 1170, 980,
      1159, 1029, 1107, 694, 158, 604, 242, 81, 163, 624, 258, 995, 1252, 839, 252, 0, 1164,
      339, 921, 351, 487, 600, 9]) := by
  have h := thirtySevenBMod.preΨ'_even 6
  norm_num at h
  rw [h, preΨ'_eight_ThirtySevenB, preΨ'_nine_ThirtySevenB, preΨ'_eleven_ThirtySevenB, preΨ'_seven_ThirtySevenB, preΨ'_ten_ThirtySevenB]
  simp only [← npoly_npow, ← npoly_nmul, sub_eq_add_neg, ← npoly_nneg, ← npoly_nadd]
  exact congrArg (npoly 1259) (by decide)

theorem preΨ'_nineteen_ThirtySevenB : thirtySevenBMod.preΨ' 19 = npoly 1259
    ([326, 927, 147, 521, 844, 747, 242, 223, 828, 1055, 656, 1127, 586, 273, 916, 545, 328,
      690, 244, 460, 318, 430, 1179, 67, 742, 66, 292, 680, 459, 946, 1107, 601, 1018, 1188,
      372, 555, 628, 1095, 1130, 1, 277, 698, 33, 482, 324, 238, 547, 59, 60, 1028, 573, 427,
      640, 488, 785, 294, 537, 929, 633, 863, 1067, 31, 1130, 653, 1111, 1227, 639, 1065, 997,
      1028, 1167, 456, 1117, 10, 533, 1194, 804, 858, 636, 239, 1019, 1174, 171, 1115, 908, 674,
      465, 914, 42, 555, 55, 647, 831, 1012, 341, 1043, 346, 410, 849, 914, 247, 822, 798, 816,
      743, 180, 882, 562, 88, 255, 1001, 869, 390, 1016, 400, 149, 16, 61, 626, 407, 336, 1143,
      499, 976, 859, 428, 735, 30, 161, 1105, 623, 610, 301, 1223, 296, 571, 844, 798, 58, 650,
      580, 150, 948, 800, 807, 529, 227, 852, 153, 761, 385, 1014, 18, 481, 106, 854, 667, 757,
      147, 41, 1077, 596, 295, 156, 65, 828, 303, 935, 1047, 600, 140, 364, 953, 1120, 400, 994,
      1052, 1202, 102, 166, 19]) := by
  have h := thirtySevenBMod.preΨ'_odd 7
  norm_num [Nat.even_iff] at h
  rw [h, preΨ'_eleven_ThirtySevenB, preΨ'_nine_ThirtySevenB, preΨ'_eight_ThirtySevenB, preΨ'_ten_ThirtySevenB, Ψ₂Sq_npoly_ThirtySevenB]
  simp only [← npoly_npow, ← npoly_nmul, sub_eq_add_neg, ← npoly_nneg, ← npoly_nadd]
  exact congrArg (npoly 1259) (by decide)

theorem preΨ'_twenty_ThirtySevenB : thirtySevenBMod.preΨ' 20 = npoly 1259
    ([1059, 722, 519, 657, 993, 570, 7, 1257, 0, 334, 276, 730, 871, 801, 212, 367, 17, 205,
      1132, 341, 1172, 73, 27, 410, 590, 227, 36, 781, 1060, 419, 133, 681, 1135, 717, 301, 680,
      564, 932, 175, 202, 810, 156, 191, 799, 844, 21, 933, 87, 733, 451, 481, 780, 176, 1171,
      152, 362, 572, 62, 1064, 395, 382, 804, 1032, 478, 593, 503, 984, 24, 1196, 676, 46, 698,
      965, 988, 659, 119, 392, 482, 346, 627, 1196, 637, 253, 886, 614, 287, 243, 83, 178, 210,
      23, 682, 831, 475, 622, 1097, 791, 519, 654, 42, 1226, 723, 907, 679, 240, 526, 922, 913,
      159, 1038, 711, 1102, 246, 233, 986, 1197, 248, 249, 1191, 555, 1089, 1227, 981, 62, 158,
      733, 1230, 401, 759, 585, 31, 1129, 718, 123, 1112, 932, 454, 882, 605, 226, 15, 320, 156,
      227, 1237, 656, 32, 1189, 491, 292, 768, 295, 1082, 840, 904, 287, 1155, 508, 819, 520,
      865, 562, 731, 750, 804, 1179, 982, 952, 1032, 835, 520, 707, 219, 1184, 528, 634, 820,
      811, 1000, 1003, 55, 740, 387, 364, 423, 1247, 649, 1228, 374, 705, 1128, 213, 399, 836,
      450, 797, 50, 825, 10]) := by
  have h := thirtySevenBMod.preΨ'_even 7
  norm_num at h
  rw [h, preΨ'_nine_ThirtySevenB, preΨ'_ten_ThirtySevenB, preΨ'_twelve_ThirtySevenB, preΨ'_eight_ThirtySevenB, preΨ'_eleven_ThirtySevenB]
  simp only [← npoly_npow, ← npoly_nmul, sub_eq_add_neg, ← npoly_nneg, ← npoly_nadd]
  exact congrArg (npoly 1259) (by decide)

/-- **`Ψ₃₇ mod 1259 = 37 · D · H`** on this row, the certificate in the form
`not_monic_dvd_of_smallDegreePart'` consumes. -/
theorem preΨ'_thirtySeven_ThirtySevenB :
    thirtySevenBMod.preΨ' 37 = C 37 * (dPolyThirtySevenB * hPolyThirtySevenB) := by
  have h := thirtySevenBMod.preΨ'_odd 16
  norm_num [Nat.even_iff] at h
  rw [h, preΨ'_twenty_ThirtySevenB, preΨ'_eighteen_ThirtySevenB, preΨ'_seventeen_ThirtySevenB, preΨ'_nineteen_ThirtySevenB, Ψ₂Sq_npoly_ThirtySevenB, C37_npoly_ThirtySevenB, dPoly_npoly_ThirtySevenB, hPolyThirtySevenB_eq]
  simp only [← npoly_npow, ← npoly_nmul, sub_eq_add_neg, ← npoly_nneg, ← npoly_nadd]
  exact congrArg (npoly 1259) (by decide)

/-- **Row `p = 37`, `j = −162677523113838677`: `Ψ₃₇ mod 1259` has no monic divisor of degree `36`.**

This is what `Fermat.not_monic_dvd_preΨ_mod_nonCMModelThirtySevenB` in `X0.lean` consumes. -/
theorem not_monic_dvd_preΨ_thirtySevenB_mod (G : (ZMod 1259)[X]) (hG : G.Monic)
    (hdeg : G.natDegree = 36) : ¬ G ∣ thirtySevenBMod.preΨ' 37 := by
  have hc : (37 : ZMod 1259) ≠ 0 := by decide
  have hmk : ∀ d : ℕ, d ∣ 37 → d ≤ 36 → d ∣ 1 := by
    intro d hd hle
    interval_cases d <;> revert hd <;> decide
  have hDdeg : dPolyThirtySevenB.natDegree = 18 := by rw [dPolyThirtySevenB]; compute_degree!
  have hD0 : dPolyThirtySevenB ≠ 0 := fun h => by rw [h, natDegree_zero] at hDdeg; omega
  have hDlt : dPolyThirtySevenB.natDegree < 36 := by omega
  -- the `Fact` must come AFTER the `decide`s above; see the `p = 17` row.
  haveI : Fact (Nat.Prime 1259) := ⟨by norm_num⟩
  exact not_monic_dvd_of_smallDegreePart' hc preΨ'_thirtySeven_ThirtySevenB hmk
    dvd_X_pow_card_pow_sub_X_hPolyThirtySevenB isCoprime_hPolyThirtySevenB hD0 hDlt G hG hdeg

end Fermat.MazurNonCMCertificate
