/-
Copyright (c) 2026 Deyao Chen. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Deyao Chen
-/
module

public import Mathlib.GroupTheory.Complement
public import Mathlib.GroupTheory.Index
public import Mathlib.GroupTheory.OrderOfElement

/-!
# Complementing the kernel of a map onto a cyclic group

This file is the GROUP-THEORETIC CORE of the "unramified descent" step that
`WeierstrassCurve.nonempty_fullTranslationDatum_wild`
(`Fermat/FLT/FreyCurve/IsogenySignature.lean`) is blocked on, isolated from
every Galois-theoretic and arithmetic input.

## The statement the arithmetic wants

Write `G = Gal(ℚ̄_q / ℚ_q)`, `I ≤ G` for the inertia subgroup, and let `N ⊴ G`
be an open subgroup of `I` which is normal in `G` (in the application
`N = ker (I ⟶ Aut (T_ℓ E))`, so that `Φ := I/N` is the *semistability defect*,
a finite group). What is wanted is a closed subgroup `H ≤ G` with

    H ∩ I = N        and        H · I = G,

equivalently: the fixed field of `H` is a TOTALLY RAMIFIED extension of `ℚ_q`
of degree `|Φ|` over which `E` acquires good reduction. Since `H · I = G` and
`H ∩ I = N` force `[G : H] = [I : N] = |Φ| < ∞`, such an `H` is automatically
OPEN, so its fixed field really is a finite extension.

The classical proof passes to `Γ := G/N`, in which `Φ = I/N` is finite normal
with `Γ/Φ ≅ G/I ≅ Ẑ`, and observes that `Ẑ` is projective in the category of
profinite groups, so the extension splits and `Φ` has a complement.

## What is proved here, and why it is the whole content

`Ẑ` does not exist in the mathlib pin, and its projectivity would need the
structure theory of procyclic profinite groups. It is not needed: the splitting
can be produced at FINITE LEVEL, and the following two facts are all of it.

* `Fermat.isComplement'_ker_zpowers` — **the criterion.** If `q : A →* U` has
  cyclic image generated by `u`, and some `σ ∈ A` with `q σ = u` has the SAME
  ORDER as `u`, then `Subgroup.zpowers σ` is a complement to `ker q`. In the
  arithmetic, `A = Gal(M/K)` for a finite Galois `M/K`, `q` is restriction to
  the maximal unramified subextension, `ker q` is the inertia subgroup, and `σ`
  is a Frobenius lift; so the criterion reads *inertia is complemented as soon
  as some Frobenius lift has the order of Frobenius*.

* `Fermat.isComplement'_fiberProduct` — **the construction.** A lift of the
  right order can always be MANUFACTURED by enlarging the unramified layer.
  Given `π : G →* Q` and `ρ : U →* Q` and a compatible pair `(φ, u)`, the
  element `(φ, u)` of the fibre product `G ×_Q U` has order the lcm of those of
  `φ` and `u`, so it has the order of `u` as soon as `orderOf φ ∣ orderOf u`;
  and then it complements the kernel of the second projection. In the
  arithmetic, `G = Gal(M/K)`, `Q = Gal(M₀/K)` with `M₀ = M ∩ K^{nr}`, and
  `U = Gal(K_d/K)` is the unramified extension of degree `d = orderOf φ` (a
  multiple of `[M₀ : K]`, since `φ` is a lift of a generator of `Gal(M₀/K)`):
  the fibre product is `Gal(M K_d / K)`, whose inertia subgroup is
  `Gal(M K_d / K_d) = ker (second projection)`.

The reason the finite-level argument does not contradict the necessity of `Ẑ`
is that the complement is NOT found inside `Gal(M/K)` — it need not exist there
(`Gal(M/K) = ℤ/4` with inertia `ℤ/2` is realisable over `ℚ_p`, and `ℤ/2` is not
complemented in `ℤ/4`). One first goes UP, by an unramified extension, which is
exactly the room that `Ẑ = Gal(K^{nr}/K)` provides.

## What this file deliberately does not do

Nothing here mentions fields, valuations or elliptic curves, and nothing here is
consumed yet: `nonempty_fullTranslationDatum_wild` is still an OPEN LEAF, and an
open leaf's body creates no dependency edge. What remains, in the shape of a task
for a successor, is the GALOIS half:

* `Gal(M · K_d / K) ≅ Gal(M/K) ×_{Gal(M₀/K)} Gal(K_d/K)` — the fibre-product
  description of the Galois group of a compositum with a linearly disjoint
  factor (`M ∩ K_d = M₀`, which holds because `K_d/K` is unramified and
  `M ∩ K^{nr} = M₀`);
* existence of the unramified extension `K_d/K` of every degree `d`, cyclic
  with Frobenius as a canonical generator;
* the fixed field `M'` of the complement is totally ramified of degree `|Φ|`,
  `M' · K_d = M K_d`, and `M K_d / M'` is unramified;
* good reduction descends along an unramified extension
  (Néron–Ogg–Shafarevich: `I_{M'} = I_{M K_d}` when `M K_d / M'` is
  unramified).

None of those four is group theory, and none of them is affected by anything in
this file.

## Main results

* `Fermat.isComplement'_ker_zpowers` — the criterion, for a map to a cyclic group
* `Fermat.isComplement'_zpowers_of_quotient_cyclic` — the same at `A ⧸ I`, which
  is the shape a Galois consumer meets
* `Fermat.isComplement'_fiberProduct` — the construction, after enlarging the
  cyclic layer
* `Fermat.bijective_restrict_of_isComplement'_ker` and `Fermat.isComplement'_facts`
  — what a complement gives back
-/

@[expose] public section

namespace Fermat

open Subgroup

variable {A G U Q : Type*} [Group A] [Group G] [Group U] [Group Q]

/-! ### An order criterion for `zpow` equations -/

/-- If the order of `σ` divides the order of `u`, then every `zpow` relation
satisfied by `u` is satisfied by `σ`.

Both degenerate cases are covered: `orderOf u = 0` (i.e. `u` of infinite order)
makes the hypothesis vacuous *and* the conclusion vacuous, since then `u ^ k = 1`
only for `k = 0`. -/
theorem zpow_eq_one_of_orderOf_dvd {σ : A} {u : U} (h : orderOf σ ∣ orderOf u)
    {k : ℤ} (hk : u ^ k = 1) : σ ^ k = 1 := by
  rw [← orderOf_dvd_iff_zpow_eq_one] at hk ⊢
  exact dvd_trans (Int.natCast_dvd_natCast.mpr h) hk

/-! ### The criterion: a lift of the right order complements the kernel -/

/-- **A Frobenius lift of the right order complements inertia.**

If `q : A →* U` lands in the cyclic subgroup generated by `u` (`hgen` says every
element of `U` is a `zpow` of `u`, i.e. `U = ⟨u⟩`), and `σ : A` is a lift of `u`
satisfying every `zpow` relation that `u` satisfies, then `⟨σ⟩` is a complement
to `ker q`.

`hord` is exactly "`orderOf σ` divides `orderOf u`"; since `q σ = u` forces
`orderOf u ∣ orderOf σ`, the two orders are then equal. Use
`Fermat.zpow_eq_one_of_orderOf_dvd` to supply it from a divisibility of orders.

Note that no finiteness is assumed anywhere. -/
theorem isComplement'_ker_zpowers {q : A →* U} {u : U} {σ : A}
    (hgen : ∀ x : U, x ∈ Subgroup.zpowers u) (hσ : q σ = u)
    (hord : ∀ k : ℤ, u ^ k = 1 → σ ^ k = 1) :
    Subgroup.IsComplement' q.ker (Subgroup.zpowers σ) := by
  refine Subgroup.isComplement'_of_disjoint_and_mul_eq_univ ?_ ?_
  · rw [Subgroup.disjoint_def]
    intro x hx hx'
    obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.mp hx'
    refine hord k ?_
    have hker : q (σ ^ k) = 1 := hx
    rwa [map_zpow, hσ] at hker
  · refine Set.eq_univ_of_forall fun a => ?_
    obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp (hgen (q a))
    refine Set.mem_mul.mpr
      ⟨a * (σ ^ k)⁻¹, ?_, σ ^ k, ?_, inv_mul_cancel_right a (σ ^ k)⟩
    · show a * (σ ^ k)⁻¹ ∈ q.ker
      rw [MonoidHom.mem_ker, map_mul, map_inv, map_zpow, hσ, hk, mul_inv_cancel]
    · exact SetLike.mem_coe.mpr (Subgroup.zpow_mem _ (Subgroup.mem_zpowers σ) k)

/-- **The criterion in the shape a Galois consumer meets it.** `I` is the inertia
subgroup of a finite Galois group `A`, `A ⧸ I` is cyclic generated by Frobenius,
and `σ` is a Frobenius lift. The hypothesis `hord` says that `σ` meets `I` only
in the identity along its own powers — equivalently `orderOf σ = orderOf (σ : A ⧸ I)`
— and the conclusion is that `⟨σ⟩` is a complement to inertia, so its fixed field
is totally ramified of degree `|I|`.

This is `Fermat.isComplement'_ker_zpowers` at `q = QuotientGroup.mk' I`. -/
theorem isComplement'_zpowers_of_quotient_cyclic (I : Subgroup A) [I.Normal] {σ : A}
    (hgen : ∀ x : A ⧸ I, x ∈ Subgroup.zpowers (QuotientGroup.mk' I σ))
    (hord : ∀ k : ℤ, σ ^ k ∈ I → σ ^ k = 1) :
    Subgroup.IsComplement' I (Subgroup.zpowers σ) := by
  have key : ∀ k : ℤ, (QuotientGroup.mk' I σ) ^ k = 1 → σ ^ k = 1 := by
    intro k hk
    refine hord k ?_
    have hq : QuotientGroup.mk' I (σ ^ k) = 1 := by rw [map_zpow, hk]
    rw [QuotientGroup.mk'_apply] at hq
    exact (QuotientGroup.eq_one_iff _).mp hq
  have h := isComplement'_ker_zpowers (q := QuotientGroup.mk' I) hgen rfl key
  rwa [QuotientGroup.ker_mk'] at h

/-- The three facts an arithmetic consumer reads off a complement to inertia:
the two subgroups intersect trivially, they generate, and the complement has
index the order of inertia — i.e. its fixed field is totally ramified of degree
`|I|`. -/
theorem isComplement'_facts {I H : Subgroup A} (h : Subgroup.IsComplement' I H) :
    I ⊓ H = ⊥ ∧ I ⊔ H = ⊤ ∧ H.index = Nat.card I :=
  ⟨h.isCompl.inf_eq_bot, h.sup_eq_top, h.index_eq_card⟩

/-- The complement produced by `Fermat.isComplement'_ker_zpowers` maps
isomorphically onto `U` — this is what says that the fixed field of the
complement is "the totally ramified part", of degree the order of `ker q`. -/
theorem bijective_restrict_of_isComplement'_ker {q : A →* U} {H : Subgroup A}
    (h : Subgroup.IsComplement' q.ker H) (hq : Function.Surjective q) :
    Function.Bijective (fun x : H => q x) := by
  constructor
  · intro x y hxy
    have hxy' : q (x : A) = q (y : A) := hxy
    have hmem : (x : A) * (y : A)⁻¹ ∈ q.ker := by
      rw [MonoidHom.mem_ker, map_mul, map_inv, hxy', mul_inv_cancel]
    have hmem' : (x : A) * (y : A)⁻¹ ∈ H := H.mul_mem x.2 (H.inv_mem y.2)
    have hone := Subgroup.disjoint_def.mp h.disjoint hmem hmem'
    exact Subtype.ext (by rwa [mul_inv_eq_one] at hone)
  · intro t
    obtain ⟨a, rfl⟩ := hq t
    obtain ⟨⟨k, hh⟩, hk⟩ := h.2 a
    refine ⟨hh, ?_⟩
    show q (hh : A) = q a
    rw [← hk, map_mul, MonoidHom.mem_ker.mp k.2, one_mul]

/-! ### The construction: enlarging the cyclic layer -/

/-- The fibre product `G ×_Q U` of `π : G →* Q` and `ρ : U →* Q`, as a subgroup
of `G × U`.

In the arithmetic application `G = Gal(M/K)`, `Q = Gal(M₀/K)` for the maximal
unramified subextension `M₀ ⊆ M`, `U = Gal(K_d/K)` for an unramified `K_d/K`
containing `M₀`, and this is `Gal(M · K_d / K)`. -/
def fiberProduct (π : G →* Q) (ρ : U →* Q) : Subgroup (G × U) where
  carrier := {p : G × U | π p.1 = ρ p.2}
  one_mem' := by simp
  mul_mem' := by
    intro a b ha hb
    simp only [Set.mem_setOf_eq, Prod.fst_mul, Prod.snd_mul, map_mul] at *
    rw [ha, hb]
  inv_mem' := by
    intro a ha
    simp only [Set.mem_setOf_eq, Prod.fst_inv, Prod.snd_inv, map_inv] at *
    rw [ha]

@[simp] theorem mem_fiberProduct {π : G →* Q} {ρ : U →* Q} {p : G × U} :
    p ∈ fiberProduct π ρ ↔ π p.1 = ρ p.2 := Iff.rfl

/-- Projection of the fibre product `G ×_Q U` onto its second factor. Its kernel
is the copy of `ker π`, i.e. the inertia subgroup in the arithmetic reading. -/
def fiberProductSnd (π : G →* Q) (ρ : U →* Q) : ↥(fiberProduct π ρ) →* U :=
  (MonoidHom.snd G U).comp (fiberProduct π ρ).subtype

@[simp] theorem fiberProductSnd_apply {π : G →* Q} {ρ : U →* Q}
    (p : ↥(fiberProduct π ρ)) : fiberProductSnd π ρ p = (p : G × U).2 := rfl

theorem mem_ker_fiberProductSnd {π : G →* Q} {ρ : U →* Q}
    {p : ↥(fiberProduct π ρ)} :
    p ∈ (fiberProductSnd π ρ).ker ↔ (p : G × U).2 = 1 := Iff.rfl

/-- The second projection of the fibre product is surjective as soon as `π` is —
the unramified layer of `M · K_d` really is all of `Gal(K_d/K)`. -/
theorem fiberProductSnd_surjective {π : G →* Q} {ρ : U →* Q}
    (hπ : Function.Surjective π) : Function.Surjective (fiberProductSnd π ρ) := by
  intro x
  obtain ⟨g, hg⟩ := hπ (ρ x)
  exact ⟨⟨(g, x), hg⟩, rfl⟩

/-- The first projection of the fibre product is surjective as soon as `ρ` is —
`M · K_d` really does contain `M`. -/
theorem fiberProductFst_surjective {π : G →* Q} {ρ : U →* Q}
    (hρ : Function.Surjective ρ) :
    Function.Surjective (fun p : ↥(fiberProduct π ρ) => (p : G × U).1) := by
  intro g
  obtain ⟨x, hx⟩ := hρ (π g)
  exact ⟨⟨(g, x), hx.symm⟩, rfl⟩

/-- **The complement exists after enlarging the cyclic layer.**

Given `π : G →* Q`, `ρ : U →* Q` with `U = ⟨u⟩` cyclic, a compatible pair
`(φ, u)`, and the hypothesis that `φ` satisfies every `zpow` relation that `u`
does (i.e. `orderOf φ ∣ orderOf u`, via `Fermat.zpow_eq_one_of_orderOf_dvd`),
the cyclic subgroup generated by `(φ, u)` is a complement to the kernel of the
second projection in the fibre product `G ×_Q U`.

Read arithmetically: over the compositum `M · K_d` with `d = orderOf φ`, the
inertia subgroup `Gal(M · K_d / K_d)` is complemented, and the fixed field of a
complement is a totally ramified extension of `K` of degree `|inertia|`. -/
theorem isComplement'_fiberProduct (π : G →* Q) (ρ : U →* Q) {φ : G} {u : U}
    (hφu : π φ = ρ u) (hgen : ∀ x : U, x ∈ Subgroup.zpowers u)
    (hord : ∀ k : ℤ, u ^ k = 1 → φ ^ k = 1) :
    Subgroup.IsComplement' (fiberProductSnd π ρ).ker
      (Subgroup.zpowers (⟨(φ, u), hφu⟩ : ↥(fiberProduct π ρ))) := by
  refine isComplement'_ker_zpowers hgen rfl ?_
  intro k hk
  refine Subtype.ext ?_
  have hcoe : (((⟨(φ, u), hφu⟩ : ↥(fiberProduct π ρ)) ^ k : ↥(fiberProduct π ρ)) :
      G × U) = ((φ, u) : G × U) ^ k := by
    simp
  rw [hcoe]
  have h1 : (((φ, u) : G × U) ^ k).1 = φ ^ k := by simp
  have h2 : (((φ, u) : G × U) ^ k).2 = u ^ k := by simp
  refine Prod.ext ?_ ?_
  · rw [h1, hord k hk]; rfl
  · rw [h2, hk]; rfl

/-- The packaged form: in the enlarged group there is a subgroup complementing
the "inertia" `ker (second projection)` and mapping bijectively onto the cyclic
layer `U`. -/
theorem exists_isComplement'_fiberProductSnd (π : G →* Q) (ρ : U →* Q) {φ : G}
    {u : U} (hφu : π φ = ρ u) (hgen : ∀ x : U, x ∈ Subgroup.zpowers u)
    (hord : ∀ k : ℤ, u ^ k = 1 → φ ^ k = 1) (hπ : Function.Surjective π) :
    ∃ H : Subgroup ↥(fiberProduct π ρ),
      Subgroup.IsComplement' (fiberProductSnd π ρ).ker H ∧
        Function.Bijective (fun x : H => fiberProductSnd π ρ x) := by
  refine ⟨_, isComplement'_fiberProduct π ρ hφu hgen hord, ?_⟩
  exact bijective_restrict_of_isComplement'_ker
    (isComplement'_fiberProduct π ρ hφu hgen hord)
    (fiberProductSnd_surjective hπ)

end Fermat

end
