module

/-
Descent.lean — own work for the Fermat project (not vendored: neither
`Mathlib` nor `~/cs/FLT` contains a descent theorem, a height function or
any form of the Mordell–Weil theorem).

# The descent theorem

This module contains the **group-theoretic half of the Mordell–Weil
theorem**, and it is PROVEN here in full.

Silverman, *The Arithmetic of Elliptic Curves* (2nd ed.), Theorem
VIII.3.1 (the *Descent Theorem*), reads:

> Let `A` be an abelian group.  Suppose there is a function
> `h : A → ℝ` with
>
> (i) for each `Q ∈ A` there is a constant `C₁` with
>     `h (P + Q) ≤ 2 * h P + C₁` for all `P ∈ A`;
> (ii) there are an integer `m ≥ 2` and a constant `C₂` with
>     `h (m • P) ≥ m ^ 2 * h P − C₂` for all `P ∈ A`;
> (iii) for every `C₃` the set `{P ∈ A | h P ≤ C₃}` is finite.
>
> Suppose further that `A / mA` is finite.  Then `A` is finitely
> generated.

`DescentHeight A` bundles (i), (ii) and (iii) — with (iii) supplied by
`Mathlib`'s own `Northcott` class, which is literally this condition —
and `fg_of_descentHeight` is the theorem.

## Why this module exists, and what it is FOR

The Mordell–Weil theorem for an abelian variety over `ℚ` is the
conjunction of three genuinely different things:

* **weak Mordell–Weil** — `A(ℚ) / n A(ℚ)` is finite, via the Kummer
  sequence, finiteness of the class group and Dirichlet's unit theorem;
* **the theory of heights** — a Weil height attached to a symmetric ample
  line bundle, with the quasi-parallelogram law, the quadraticity
  `h (m • P) = m² h P + O(1)` and Northcott's finiteness theorem;
* **the descent argument** itself, which combines the two.

The first two are analytic/arithmetic and are open leaves elsewhere in
this development.  The third is pure group theory over an ordered field
and needs none of that machinery, so it is proven here once, for an
arbitrary `AddCommGroup`, and reused.

## The proof

`Mathlib`'s statement of the descent step is by an infinite descending
sequence; the formalisation below uses the equivalent **minimal
counterexample** form, which is what `Northcott.exists_min_image` makes
available directly and which avoids constructing the sequence at all.

Let `Q₁, …, Q_r` represent the cosets of `A / mA`, let `C₁` dominate all
the translation constants of `−Q₁, …, −Q_r`, let `C₂` be the constant of
(ii), and put `C := max 0 ((C₁ + C₂) / 2)`.  Let

`S := {Q₁, …, Q_r} ∪ {P | h P ≤ C}`,

a finite set by (iii), and `H := closure S`.  If `H ≠ ⊤` then
`{P | P ∉ H}` is nonempty, so by (iii) it contains an element `P` of
minimal height.  Then `h P > C`, since every point of height `≤ C` lies
in `S ⊆ H`.  Write `P = m • P' + Q` with `Q ∈ S`; then `P' ∉ H`, for
otherwise `P ∈ H`.  Now (ii) and (i) give

`m² · h P' ≤ h (m • P') + C₂ = h (P + (−Q)) + C₂ ≤ 2 · h P + C₁ + C₂`,

while minimality gives `h P ≤ h P'`, and `h P > C ≥ 0` makes `h P' > 0`,
so `4 · h P ≤ 4 · h P' ≤ m² · h P' ≤ 2 · h P + C₁ + C₂`.  Hence
`h P ≤ (C₁ + C₂) / 2 ≤ C`, contradicting `h P > C`.  So `H = ⊤` and `A`
is generated by the finite set `S`.

Everything in this module is PROVEN; it contains no `sorry`.
-/

public import Mathlib.GroupTheory.Finiteness
public import Mathlib.GroupTheory.QuotientGroup.Defs
public import Mathlib.Order.Northcott
public import Mathlib.Algebra.Order.BigOperators.Group.Finset
public import Mathlib.Algebra.Group.Hom.Basic
public import Mathlib.Data.Real.Basic
public import Mathlib.Tactic.Linarith
public import Mathlib.Tactic.Ring
public import Mathlib.Tactic.Abel

@[expose] public section

namespace Fermat

/-- **A height function for descent on an additive abelian group.**

The three hypotheses of Silverman's descent theorem (AEC VIII.3.1),
bundled with the integer `m` of hypothesis (ii):

* `translate` is (i), the quasi-parallelogram bound — for each `Q` the
  translate `P ↦ height (P + Q)` is bounded by `2 * height P` up to a
  constant depending on `Q`;
* `double` is (ii), quadraticity of the height in the direction that
  descent needs — multiplication by `m` multiplies the height by `m²`,
  up to a constant, and only the inequality `≥` is used;
* `northcott` is (iii), Northcott's finiteness property, taken from
  `Mathlib`'s `Northcott` class, whose `finite_le` field is exactly
  "`{P | height P ≤ C}` is finite for every `C`".

For an abelian variety over a number field, `height` is the Weil height
attached to a symmetric ample line bundle. -/
structure DescentHeight (A : Type*) [AddCommGroup A] where
  /-- the height function -/
  height : A → ℝ
  /-- the integer of the quadraticity hypothesis; descent needs `2 ≤ m` -/
  m : ℕ
  /-- descent needs `m` at least `2` -/
  two_le : 2 ≤ m
  /-- **(i)** for each `Q` there is a constant `C` with
  `height (P + Q) ≤ 2 * height P + C` for all `P` -/
  translate : ∀ Q : A, ∃ C : ℝ, ∀ P : A, height (P + Q) ≤ 2 * height P + C
  /-- **(ii)** there is a constant `C` with
  `m ^ 2 * height P ≤ height (m • P) + C` for all `P` -/
  double : ∃ C : ℝ, ∀ P : A, (m : ℝ) ^ 2 * height P ≤ height (m • P) + C
  /-- **(iii)** every set `{P | height P ≤ C}` is finite -/
  northcott : Northcott height

/-- **Finiteness of `A / nA` produces a finite set of coset
representatives** (PROVEN).

This is the only use made of the hypothesis "`A / mA` is finite" in the
descent theorem, and it is separated out because it is pure quotient
bookkeeping: choose one preimage of each of the finitely many classes.

The subgroup `nA` is written as the range of the multiplication-by-`n`
endomorphism `nsmulAddMonoidHom n`. -/
theorem exists_finset_nsmul_repr {A : Type*} [AddCommGroup A] (n : ℕ)
    (hq : Finite (A ⧸ (nsmulAddMonoidHom n : A →+ A).range)) :
    ∃ R : Finset A, ∀ P : A, ∃ q ∈ R, ∃ P' : A, P = n • P' + q := by
  classical
  haveI := hq
  set H : AddSubgroup A := (nsmulAddMonoidHom n : A →+ A).range with hH
  have hsurj : Function.Surjective (fun a : A => (a : A ⧸ H)) := fun c =>
    ⟨Quotient.out c, Quotient.out_eq c⟩
  set f : A ⧸ H → A := Function.surjInv hsurj with hf
  have hfeq : ∀ c : A ⧸ H, ((f c : A) : A ⧸ H) = c := Function.surjInv_eq hsurj
  have hfin : (Set.range f).Finite := Set.finite_range f
  refine ⟨hfin.toFinset, fun P => ?_⟩
  refine ⟨f ((P : A ⧸ H)), hfin.mem_toFinset.mpr ⟨(P : A ⧸ H), rfl⟩, ?_⟩
  have h1 : ((f ((P : A ⧸ H)) : A) : A ⧸ H) = (P : A ⧸ H) := hfeq _
  have h2 : -(f ((P : A ⧸ H))) + P ∈ H := QuotientAddGroup.eq.mp h1
  obtain ⟨P', hP'⟩ := h2
  refine ⟨P', ?_⟩
  have hP'' : n • P' = -(f ((P : A ⧸ H))) + P := hP'
  rw [hP'']
  abel

/-- **The descent theorem** (PROVEN) — Silverman, *AEC* Theorem VIII.3.1.

An abelian group carrying a height function in the sense of
`DescentHeight`, and whose quotient by `m A` is finite for the `m` of
that height, is finitely generated.

This is the group-theoretic half of the Mordell–Weil theorem: given weak
Mordell–Weil (the `hq` hypothesis) and a theory of heights (the `dh`
hypothesis), finite generation follows with no further arithmetic.

The generating set produced is `R ∪ {P | height P ≤ C}` for coset
representatives `R` and an explicit constant `C` built from the
constants of the two height inequalities. -/
theorem fg_of_descentHeight {A : Type*} [AddCommGroup A] (dh : DescentHeight A)
    (hq : Finite (A ⧸ (nsmulAddMonoidHom dh.m : A →+ A).range)) :
    AddGroup.FG A := by
  classical
  haveI := dh.northcott
  obtain ⟨R, hR⟩ := exists_finset_nsmul_repr dh.m hq
  obtain ⟨C₂, hC₂⟩ := dh.double
  choose Cf hCf using fun q : A => dh.translate (-q)
  set C₁ : ℝ := ∑ q ∈ R, |Cf q| with hC₁def
  have hC₁le : ∀ q ∈ R, Cf q ≤ C₁ := fun q hqR =>
    (le_abs_self _).trans
      (Finset.single_le_sum (f := fun q : A => |Cf q|) (fun i _ => abs_nonneg _) hqR)
  set C : ℝ := max 0 ((C₁ + C₂) / 2) with hCdef
  have hCnn : (0 : ℝ) ≤ C := le_max_left _ _
  have hCge : (C₁ + C₂) / 2 ≤ C := le_max_right _ _
  set S : Set A := (R : Set A) ∪ {P : A | dh.height P ≤ C} with hSdef
  have hSfin : S.Finite := R.finite_toSet.union (Northcott.finite_le (h := dh.height) C)
  refine AddGroup.fg_iff.mpr ⟨S, ?_, hSfin⟩
  set H : AddSubgroup A := AddSubgroup.closure S with hHdef
  by_contra hne
  have hex : Set.Nonempty {P : A | P ∉ H} := by
    by_contra hcon
    refine hne (eq_top_iff.mpr fun x _ => ?_)
    by_contra hx
    exact hcon ⟨x, hx⟩
  obtain ⟨P, hPmem, hPmin⟩ := Northcott.exists_min_image dh.height {P : A | P ∉ H} hex
  have hP : P ∉ H := hPmem
  -- `P` has height above the threshold, since everything below it is a generator
  have hgt : C < dh.height P := by
    by_contra hle
    exact hP (AddSubgroup.subset_closure (Set.mem_union_right _ (not_lt.mp hle)))
  -- descend one step
  obtain ⟨q, hqR, P', hPeq⟩ := hR P
  have hqH : q ∈ H := AddSubgroup.subset_closure (Set.mem_union_left _ hqR)
  have hP'notH : P' ∉ H := by
    intro hmem
    exact hP (hPeq ▸ H.add_mem (nsmul_mem hmem dh.m) hqH)
  have hmP' : dh.m • P' = P + -q := by rw [hPeq]; abel
  have h1 : dh.height (dh.m • P') ≤ 2 * dh.height P + C₁ := by
    rw [hmP']
    exact (hCf q P).trans (by linarith [hC₁le q hqR])
  have h2 : (dh.m : ℝ) ^ 2 * dh.height P' ≤ 2 * dh.height P + C₁ + C₂ := by
    linarith [hC₂ P']
  have hminP' : dh.height P ≤ dh.height P' := hPmin P' hP'notH
  have hm2 : (4 : ℝ) ≤ (dh.m : ℝ) ^ 2 := by
    have h2m : (2 : ℝ) ≤ (dh.m : ℝ) := by exact_mod_cast dh.two_le
    nlinarith
  have hpos : (0 : ℝ) < dh.height P' := lt_of_lt_of_le (lt_of_le_of_lt hCnn hgt) hminP'
  have h3 : 4 * dh.height P' ≤ (dh.m : ℝ) ^ 2 * dh.height P' :=
    mul_le_mul_of_nonneg_right hm2 hpos.le
  linarith

end Fermat
