module

/-
Descent.lean — own work for the Fermat project.

**THE PARENTHETICAL THAT USED TO STAND HERE IS FALSE — see the
CORRECTION section at the end of this docstring before using or
extending this module.**  It read: "not vendored: neither `Mathlib` nor
`~/cs/FLT` contains a descent theorem, a height function or any form of
the Mordell–Weil theorem".  Two of those three clauses are wrong at pin
`a3364fa`: mathlib has `Mathlib/GroupTheory/Descent.lean` (the descent
theorem, in three strengths) and `Mathlib/NumberTheory/Height/` (six
modules of height theory, Northcott included).  Only the clause about
`~/cs/FLT`, and the clause about the Mordell–Weil theorem itself, survive.

# The descent theorem

This module contains the **group-theoretic half of the Mordell–Weil
theorem**, and it is PROVEN here in full.

Silverman, *The Arithmetic of Elliptic Curves* (2nd ed.), Theorem
VIII.3.1 (the *Descent Theorem*), reads:

> Let `A` be an abelian group.  Suppose there is a function
> `h : A → ℝ` with
>
> (i) for each `Q ∈ A` there is a constant `C₁` with
>     `h (P + Q) ≤ 2 * h P + C₁` for all `P ∈ A`;
> (ii) there are an integer `m ≥ 2` and a constant `C₂` with
>     `h (m • P) ≥ m ^ 2 * h P − C₂` for all `P ∈ A`;
> (iii) for every `C₃` the set `{P ∈ A | h P ≤ C₃}` is finite.
>
> Suppose further that `A / mA` is finite.  Then `A` is finitely
> generated.

`DescentHeight A` bundles (i), (ii) and (iii) — with (iii) supplied by
`Mathlib`'s own `Northcott` class, which is literally this condition —
and `fg_of_descentHeight` is the theorem.

## Why this module exists, and what it is FOR

The Mordell–Weil theorem for an abelian variety over `ℚ` is the
conjunction of three genuinely different things:

* **weak Mordell–Weil** — `A(ℚ) / n A(ℚ)` is finite, via the Kummer
  sequence, finiteness of the class group and Dirichlet's unit theorem;
* **the theory of heights** — a Weil height attached to a symmetric ample
  line bundle, with the quasi-parallelogram law, the quadraticity
  `h (m • P) = m² h P + O(1)` and Northcott's finiteness theorem;
* **the descent argument** itself, which combines the two.

The first two are analytic/arithmetic and are open leaves elsewhere in
this development.  The third is pure group theory over an ordered field
and needs none of that machinery, so it is proven here once, for an
arbitrary `AddCommGroup`, and reused.

**Both halves of that paragraph need the CORRECTION below.**  The height
theory is NOT an open leaf — mathlib has it, and the only genuinely
missing pieces on that axis are ampleness of line bundles and the theorem
of the cube.  And the descent argument is not exclusive to this module
either: mathlib proves it too.

## The proof

`Mathlib`'s statement of the descent step is by an infinite descending
sequence; the formalisation below uses the equivalent **minimal
counterexample** form, which is what `Northcott.exists_min_image` makes
available directly and which avoids constructing the sequence at all.

Let `Q₁, …, Q_r` represent the cosets of `A / mA`, let `C₁` dominate all
the translation constants of `−Q₁, …, −Q_r`, let `C₂` be the constant of
(ii), and put `C := max 0 ((C₁ + C₂) / 2)`.  Let

`S := {Q₁, …, Q_r} ∪ {P | h P ≤ C}`,

a finite set by (iii), and `H := closure S`.  If `H ≠ ⊤` then
`{P | P ∉ H}` is nonempty, so by (iii) it contains an element `P` of
minimal height.  Then `h P > C`, since every point of height `≤ C` lies
in `S ⊆ H`.  Write `P = m • P' + Q` with `Q ∈ S`; then `P' ∉ H`, for
otherwise `P ∈ H`.  Now (ii) and (i) give

`m² · h P' ≤ h (m • P') + C₂ = h (P + (−Q)) + C₂ ≤ 2 · h P + C₁ + C₂`,

while minimality gives `h P ≤ h P'`, and `h P > C ≥ 0` makes `h P' > 0`,
so `4 · h P ≤ 4 · h P' ≤ m² · h P' ≤ 2 · h P + C₁ + C₂`.  Hence
`h P ≤ (C₁ + C₂) / 2 ≤ C`, contradicting `h P > C`.  So `H = ⊤` and `A`
is generated by the finite set `S`.

## Two further reductions, added 2026-07-27

Both are pure group theory, and both exist to shrink what the two
*arithmetic* leaves of Mordell–Weil have to supply.

* **`ParallelogramHeight` and `ParallelogramHeight.toDescentHeight`.**
  The three fields of `DescentHeight` are an awkward thing to ask a
  geometer for: they mix a one-sided translation bound, a one-sided
  quadraticity bound, and a choice of `m`.  What the theory of heights
  actually produces is a single symmetric statement — the **approximate
  parallelogram law** `|h (P + Q) + h (P − Q) − 2 h P − 2 h Q| ≤ C`, one
  constant, uniform in both variables — together with Northcott.
  `ParallelogramHeight` bundles exactly those two, and
  `toDescentHeight` derives a `DescentHeight` with `m = 2` from them.
  The only non-formal step is that a Northcott height is automatically
  **bounded below** (`ParallelogramHeight.exists_lowerBound`), which is
  what turns the two-sided parallelogram bound into the one-sided
  translation bound.

  (A second, byte-for-byte equivalent copy of this — `WeilHeight`,
  `WeilHeight.toDescentHeight`, `exists_lowerBound_of_northcott` — was
  developed independently for the integral-coordinate route and was
  DELETED with it on 2026-07-28.)

* **`finite_quotient_nsmul_of_prime`.**  Weak Mordell–Weil is needed for
  every `n ≥ 2`, but `A / nA` is finite as soon as `A / pA` is finite for
  every prime `p`: `A / (m k) A` sits in an extension of `A / mA` by a
  quotient of `A / kA` (`finite_quotient_nsmul_mul`), and an induction on
  the prime factorisation does the rest.  This matters because the
  arithmetic input — the Kummer sequence and the `n`-Selmer group — is
  much better behaved at a prime, where `A[p]` is an `𝔽_p`-vector space
  and so is every cohomology group built from it.

Everything in this module is PROVEN; it contains no `sorry`.

## CORRECTION (2026-07-28): mathlib HAS the descent theorem AND the heights

This module was written against a survey that said neither existed.  Both
claims are false at pin `a3364fa`, and both were refuted by grepping for
the right names rather than for `MordellWeil` / `NeronTateHeight` /
`WeilHeight` — none of which occurs anywhere in mathlib, which is exactly
why the absence reads as real.

**`Mathlib/GroupTheory/Descent.lean` (Michael Stoll) is the descent
theorem**, in three strengths, all PROVEN upstream:

* `AddGroup.fg_of_descent` — for an endomorphism `f` carrying subgroups
  into themselves, a finite `s` surjecting onto `G ⧸ f(G)`, a height with
  `h x ≤ a * h (g + x) + c`, `b * h x - c ≤ h (f x)`, `[Northcott h]` and
  `0 ≤ a < b`;
* `AddCommGroup.fg_of_descent` — the `n`-th power endomorphism version,
  with a per-element constant `c : G → ℝ`;
* `AddCommGroup.fg_of_descent'` — the **approximate parallelogram law**
  version: `G ⧸ 2G` of finite index, `0 ≤ h`,
  `|h (x + y) + h (x - y) - 2 * (h x + h y)| ≤ C`, `[Northcott h]` ⟹
  `AddGroup.FG G`.  Its own docstring calls itself "one of the main
  ingredients of the standard proof of the **Mordell-Weil Theorem**".

Read across the dictionary, that file subsumes this one almost exactly:

| here | upstream |
|---|---|
| `DescentHeight` + `fg_of_descentHeight` | `AddCommGroup.fg_of_descent` (`a = 2`, `b = m²`, `n = m`) |
| `ParallelogramHeight` + `toDescentHeight` + `fg_of_descentHeight` | `AddCommGroup.fg_of_descent'` |

**Two things here are NOT upstream, and they are the reason this module
is not simply deleted:**

1. `ParallelogramHeight.exists_lowerBound`, and with it the fact that
   `ParallelogramHeight` needs **no nonnegativity hypothesis**.
   Mathlib's `fg_of_descent'` assumes `H₂ : ∀ x, 0 ≤ h x`;
   `ParallelogramHeight` does not, because Northcott already forces a
   lower bound.  So it is strictly the weaker ask of a producer, which
   matters: a producer would otherwise have to prove `0 ≤ h` separately
   for whatever height it supplies.
2. `finite_quotient_nsmul_of_prime` / `finite_quotient_nsmul_mul` — the
   reduction of weak Mordell–Weil from a general `n` to the primes.
   Nothing upstream does this.

Upstream also has `AddCommGroup.finite_torsion_of_descent'` (the torsion
subgroup is finite under the parallelogram law alone, with **no** `G/2G`
hypothesis), which has no analogue here and is worth knowing about.

**`Mathlib/NumberTheory/Height/` is the theory of heights** — six
modules: `Basic`, `Northcott`, `NumberField`, `Projectivization`,
`MvPolynomial`, `EllipticCurve`.  `Height.mulHeight` / `logHeight` on
tuples over any field with `Height.AdmissibleAbsValues`; that instance
holds for **every number field**, hence for `ℚ`; Northcott as a genuine
instance (`instance : Northcott (mulHeight₁ (K := K))`,
`Height/NumberField.lean:393`, and `Northcott (logHeight₁ (K := K))`
derived from it); `Rat.logHeight_eq_max_abs_of_gcd_eq_one`;
`Projectivization.mulHeight` / `logHeight`, well defined on projective
space; and the height machine for a family of homogeneous forms in BOTH
directions, `Height.logHeight_eval_le'` and `Height.logHeight_eval_ge'`.

`Height/EllipticCurve.lean` runs the elliptic-curve case in four lines
(`abs_logHeight_addSubMap_sub_two_mul_logHeight_le`), and is the model to
copy for anyone assembling a `ParallelogramHeight` on `E(ℚ)`.

**What IS still genuinely absent, so this correction is not read too
widely:**

* the **canonical (Néron–Tate) height** — mathlib has only the naive
  height; `canonicalHeight` and `neronTate` return nothing;
* the **naive height on an elliptic curve as a function on points**, and
  the approximate parallelogram law for it: `Height/EllipticCurve.lean`
  lists all three as `TODO`, and supplies only the morphism bound above;
* **Northcott on `Projectivization`** — `Height/Northcott.lean` lists it
  as `TODO`;
* **ampleness of line bundles and the theorem of the cube**
  (`grep -rn "TheoremOfTheCube\|VeryAmple\|IsAmple"` finds nothing in
  mathlib), which is what
  `exists_cubeModel_of_abelianScheme` in `ModularCurve/X0.lean`
  still carries;
* **weak Mordell–Weil** in any form, and the Mordell–Weil theorem itself;
* everything in `~/cs/FLT`: it really does have no height material at
  all (`grep -rlniE 'mulHeight|logHeight|northcott|weil height'` over the
  whole tree returns nothing), so that clause of the original note was
  right.

Nothing in this module is wrong or wasted — it is what the rest of the
development consumes, and it is proven — but a reader must not conclude
from the text above that these theories are missing upstream.  The
companion correction is in
`Fermat/FLT/Mathlib/NumberTheory/ProjectiveHeight.lean`.  (Two further
copies of it lived in `IntegralHeight.lean` and `SegreHeight.lean`,
deleted with the integral-coordinate route on 2026-07-28.)
-/

public import Mathlib.GroupTheory.Finiteness
public import Mathlib.GroupTheory.QuotientGroup.Defs
public import Mathlib.GroupTheory.QuotientGroup.Basic
public import Mathlib.GroupTheory.QuotientGroup.Finite
public import Mathlib.Data.Nat.Factorization.Induction
public import Mathlib.Order.Northcott
public import Mathlib.Algebra.Order.BigOperators.Group.Finset
public import Mathlib.Algebra.Group.Hom.Basic
public import Mathlib.Data.Real.Basic
public import Mathlib.Tactic.Linarith
public import Mathlib.Tactic.Ring
public import Mathlib.Tactic.Abel

@[expose] public section

namespace Fermat

/-- **A height function for descent on an additive abelian group.**

The three hypotheses of Silverman's descent theorem (AEC VIII.3.1),
bundled with the integer `m` of hypothesis (ii):

* `translate` is (i), the quasi-parallelogram bound — for each `Q` the
  translate `P ↦ height (P + Q)` is bounded by `2 * height P` up to a
  constant depending on `Q`;
* `double` is (ii), quadraticity of the height in the direction that
  descent needs — multiplication by `m` multiplies the height by `m²`,
  up to a constant, and only the inequality `≥` is used;
* `northcott` is (iii), Northcott's finiteness property, taken from
  `Mathlib`'s `Northcott` class, whose `finite_le` field is exactly
  "`{P | height P ≤ C}` is finite for every `C`".

For an abelian variety over a number field, `height` is the Weil height
attached to a symmetric ample line bundle. -/
structure DescentHeight (A : Type*) [AddCommGroup A] where
  /-- the height function -/
  height : A → ℝ
  /-- the integer of the quadraticity hypothesis; descent needs `2 ≤ m` -/
  m : ℕ
  /-- descent needs `m` at least `2` -/
  two_le : 2 ≤ m
  /-- **(i)** for each `Q` there is a constant `C` with
  `height (P + Q) ≤ 2 * height P + C` for all `P` -/
  translate : ∀ Q : A, ∃ C : ℝ, ∀ P : A, height (P + Q) ≤ 2 * height P + C
  /-- **(ii)** there is a constant `C` with
  `m ^ 2 * height P ≤ height (m • P) + C` for all `P` -/
  double : ∃ C : ℝ, ∀ P : A, (m : ℝ) ^ 2 * height P ≤ height (m • P) + C
  /-- **(iii)** every set `{P | height P ≤ C}` is finite -/
  northcott : Northcott height

/-- **A quasi-parallelogram height — what the classical "height machine"
actually produces.**

`DescentHeight` is the hypothesis of Silverman's descent theorem, and it
is stated in the asymmetric form that the *proof* consumes: a translation
bound, a one-sided quadraticity bound, and a choice of the integer `m`.
No theory of heights produces those three directly.  What it produces is
a **single** two-sided estimate, the *approximate parallelogram law*

`|h(P + Q) + h(P − Q) − 2 h(P) − 2 h(Q)| ≤ C`,

for one constant `C` independent of `P` and `Q` — Silverman, *AEC*
Theorem VIII.6.2 (via the theorem of the cube), Hindry–Silverman
*Diophantine Geometry* Theorem B.5.1 — together with Northcott's
theorem.  So this structure is the honest interface between the two
halves, and `toParallelogramHeight`-style constructions should target it
rather than `DescentHeight`.

Note what is **not** a field, because it does not have to be:

* there is no `m`; the parallelogram law gives quadraticity at `m = 2`
  outright, and `2` is the `m` that `toDescentHeight` supplies;
* there is no lower bound on `height`, and requiring one would be
  redundant: `northcott` alone forces it, since `{P | height P ≤ 0}` is
  finite and hence has a minimum.  That is `exists_lowerBound` below.

The `translate` field of `DescentHeight` is exactly where that lower
bound is needed — the parallelogram law bounds `h(P + Q) + h(P − Q)`,
and discarding the second summand requires it to be bounded below. -/
structure ParallelogramHeight (A : Type*) [AddCommGroup A] where
  /-- the height function -/
  height : A → ℝ
  /-- the **approximate parallelogram law**, with one constant for all
  `P` and `Q` -/
  parallelogram : ∃ C : ℝ, ∀ P Q : A,
    |height (P + Q) + height (P - Q) - 2 * height P - 2 * height Q| ≤ C
  /-- every set `{P | height P ≤ C}` is finite -/
  northcott : Northcott height

/-- **A Northcott function is bounded below** (PROVEN).

`{P | height P ≤ 0}` is finite, so the height takes only finitely many
values `≤ 0`; the minimum of those (or `0`, if there are none) is a lower
bound. -/
theorem ParallelogramHeight.exists_lowerBound {A : Type*} [AddCommGroup A]
    (ph : ParallelogramHeight A) : ∃ B : ℝ, ∀ P : A, B ≤ ph.height P := by
  haveI := ph.northcott
  have hfin : {P : A | ph.height P ≤ 0}.Finite := Northcott.finite_le 0
  obtain ⟨B, hB⟩ := (hfin.image ph.height).bddBelow
  refine ⟨min B 0, fun P => ?_⟩
  rcases le_or_gt (ph.height P) 0 with h | h
  · exact (min_le_left _ _).trans (hB ⟨P, h, rfl⟩)
  · exact (min_le_right _ _).trans h.le

/-- **The parallelogram law supplies the descent hypotheses, with
`m = 2`** (PROVEN) — pure group theory over `ℝ`, no arithmetic.

* `translate`: the law gives
  `h(P + Q) ≤ 2 h(P) + 2 h(Q) + C − h(P − Q)`, and `h(P − Q) ≥ B` by
  `exists_lowerBound`, so `2 * h(Q) + C − B` works as the constant
  attached to `Q`.
* `double`: taking `Q = P` makes `P − Q = 0`, so the law reads
  `|h(2P) + h(0) − 4 h(P)| ≤ C`, whose lower half is exactly
  `2² · h(P) ≤ h(2 • P) + (h(0) + C)`.
* `northcott` is carried across unchanged. -/
def ParallelogramHeight.toDescentHeight {A : Type*} [AddCommGroup A]
    (ph : ParallelogramHeight A) : DescentHeight A where
  height := ph.height
  m := 2
  two_le := le_rfl
  translate := by
    obtain ⟨C, hC⟩ := ph.parallelogram
    obtain ⟨B, hB⟩ := ph.exists_lowerBound
    refine fun Q => ⟨2 * ph.height Q + C - B, fun P => ?_⟩
    have h := (abs_le.mp (hC P Q)).2
    have hBQ := hB (P - Q)
    linarith
  double := by
    obtain ⟨C, hC⟩ := ph.parallelogram
    refine ⟨ph.height 0 + C, fun P => ?_⟩
    have h := (abs_le.mp (hC P P)).1
    rw [sub_self] at h
    rw [two_nsmul]
    push_cast
    linarith
  northcott := ph.northcott

/-- **Finiteness of `A / nA` produces a finite set of coset
representatives** (PROVEN).

This is the only use made of the hypothesis "`A / mA` is finite" in the
descent theorem, and it is separated out because it is pure quotient
bookkeeping: choose one preimage of each of the finitely many classes.

The subgroup `nA` is written as the range of the multiplication-by-`n`
endomorphism `nsmulAddMonoidHom n`. -/
theorem exists_finset_nsmul_repr {A : Type*} [AddCommGroup A] (n : ℕ)
    (hq : Finite (A ⧸ (nsmulAddMonoidHom n : A →+ A).range)) :
    ∃ R : Finset A, ∀ P : A, ∃ q ∈ R, ∃ P' : A, P = n • P' + q := by
  classical
  haveI := hq
  set H : AddSubgroup A := (nsmulAddMonoidHom n : A →+ A).range with hH
  have hsurj : Function.Surjective (fun a : A => (a : A ⧸ H)) := fun c =>
    ⟨Quotient.out c, Quotient.out_eq c⟩
  set f : A ⧸ H → A := Function.surjInv hsurj with hf
  have hfeq : ∀ c : A ⧸ H, ((f c : A) : A ⧸ H) = c := Function.surjInv_eq hsurj
  have hfin : (Set.range f).Finite := Set.finite_range f
  refine ⟨hfin.toFinset, fun P => ?_⟩
  refine ⟨f ((P : A ⧸ H)), hfin.mem_toFinset.mpr ⟨(P : A ⧸ H), rfl⟩, ?_⟩
  have h1 : ((f ((P : A ⧸ H)) : A) : A ⧸ H) = (P : A ⧸ H) := hfeq _
  have h2 : -(f ((P : A ⧸ H))) + P ∈ H := QuotientAddGroup.eq.mp h1
  obtain ⟨P', hP'⟩ := h2
  refine ⟨P', ?_⟩
  have hP'' : n • P' = -(f ((P : A ⧸ H))) + P := hP'
  rw [hP'']
  abel

/-- **The descent theorem** (PROVEN) — Silverman, *AEC* Theorem VIII.3.1.

An abelian group carrying a height function in the sense of
`DescentHeight`, and whose quotient by `m A` is finite for the `m` of
that height, is finitely generated.

This is the group-theoretic half of the Mordell–Weil theorem: given weak
Mordell–Weil (the `hq` hypothesis) and a theory of heights (the `dh`
hypothesis), finite generation follows with no further arithmetic.

The generating set produced is `R ∪ {P | height P ≤ C}` for coset
representatives `R` and an explicit constant `C` built from the
constants of the two height inequalities. -/
theorem fg_of_descentHeight {A : Type*} [AddCommGroup A] (dh : DescentHeight A)
    (hq : Finite (A ⧸ (nsmulAddMonoidHom dh.m : A →+ A).range)) :
    AddGroup.FG A := by
  classical
  haveI := dh.northcott
  obtain ⟨R, hR⟩ := exists_finset_nsmul_repr dh.m hq
  obtain ⟨C₂, hC₂⟩ := dh.double
  choose Cf hCf using fun q : A => dh.translate (-q)
  set C₁ : ℝ := ∑ q ∈ R, |Cf q| with hC₁def
  have hC₁le : ∀ q ∈ R, Cf q ≤ C₁ := fun q hqR =>
    (le_abs_self _).trans
      (Finset.single_le_sum (f := fun q : A => |Cf q|) (fun i _ => abs_nonneg _) hqR)
  set C : ℝ := max 0 ((C₁ + C₂) / 2) with hCdef
  have hCnn : (0 : ℝ) ≤ C := le_max_left _ _
  have hCge : (C₁ + C₂) / 2 ≤ C := le_max_right _ _
  set S : Set A := (R : Set A) ∪ {P : A | dh.height P ≤ C} with hSdef
  have hSfin : S.Finite := R.finite_toSet.union (Northcott.finite_le (h := dh.height) C)
  refine AddGroup.fg_iff.mpr ⟨S, ?_, hSfin⟩
  set H : AddSubgroup A := AddSubgroup.closure S with hHdef
  by_contra hne
  have hex : Set.Nonempty {P : A | P ∉ H} := by
    by_contra hcon
    refine hne (eq_top_iff.mpr fun x _ => ?_)
    by_contra hx
    exact hcon ⟨x, hx⟩
  obtain ⟨P, hPmem, hPmin⟩ := Northcott.exists_min_image dh.height {P : A | P ∉ H} hex
  have hP : P ∉ H := hPmem
  -- `P` has height above the threshold, since everything below it is a generator
  have hgt : C < dh.height P := by
    by_contra hle
    exact hP (AddSubgroup.subset_closure (Set.mem_union_right _ (not_lt.mp hle)))
  -- descend one step
  obtain ⟨q, hqR, P', hPeq⟩ := hR P
  have hqH : q ∈ H := AddSubgroup.subset_closure (Set.mem_union_left _ hqR)
  have hP'notH : P' ∉ H := by
    intro hmem
    exact hP (hPeq ▸ H.add_mem (nsmul_mem hmem dh.m) hqH)
  have hmP' : dh.m • P' = P + -q := by rw [hPeq]; abel
  have h1 : dh.height (dh.m • P') ≤ 2 * dh.height P + C₁ := by
    rw [hmP']
    exact (hCf q P).trans (by linarith [hC₁le q hqR])
  have h2 : (dh.m : ℝ) ^ 2 * dh.height P' ≤ 2 * dh.height P + C₁ + C₂ := by
    linarith [hC₂ P']
  have hminP' : dh.height P ≤ dh.height P' := hPmin P' hP'notH
  have hm2 : (4 : ℝ) ≤ (dh.m : ℝ) ^ 2 := by
    have h2m : (2 : ℝ) ≤ (dh.m : ℝ) := by exact_mod_cast dh.two_le
    nlinarith
  have hpos : (0 : ℝ) < dh.height P' := lt_of_lt_of_le (lt_of_le_of_lt hCnn hgt) hminP'
  have h3 : 4 * dh.height P' ≤ (dh.m : ℝ) ^ 2 * dh.height P' :=
    mul_le_mul_of_nonneg_right hm2 hpos.le
  linarith

-- RETIRED 2026-07-28.  `Fermat.exists_lowerBound_of_northcott`,
-- `Fermat.WeilHeight` and `Fermat.WeilHeight.toDescentHeight` stood here.
-- They were an exact duplicate of `ParallelogramHeight`,
-- `ParallelogramHeight.exists_lowerBound` and
-- `ParallelogramHeight.toDescentHeight` above, differing only in the
-- association of the right-hand side of the parallelogram law, and their sole
-- consumer was `IntegralCoordinates.toWeilHeight` in the retired
-- `Fermat/FLT/Mathlib/NumberTheory/IntegralHeight.lean`.  The whole
-- integral-coordinate route was deleted; the live route is
-- `ProjectiveHeightSource.toParallelogramHeight →
-- ParallelogramHeight.toDescentHeight → fg_of_descentHeight`.  Recover from
-- git history if wanted.

/-! ## Reducing `A / nA` to the prime case -/

/-- **`A / 1·A` is trivial, hence finite** (PROVEN) — the base case of the
induction in `finite_quotient_nsmul_of_prime`. -/
theorem finite_quotient_nsmul_one {A : Type*} [AddCommGroup A] :
    Finite (A ⧸ (nsmulAddMonoidHom 1 : A →+ A).range) := by
  have htop : (nsmulAddMonoidHom 1 : A →+ A).range = ⊤ :=
    eq_top_iff.mpr fun x _ => ⟨x, by simp⟩
  rw [htop]
  haveI := QuotientAddGroup.subsingleton_quotient_top (G := A)
  exact Finite.of_subsingleton

/-- **`A / nA` is multiplicative in `n`** (PROVEN).

Write `N = (m k) A ≤ M = m A`.  Noether's third isomorphism theorem
identifies `(A / N) / (M / N)` with `A / M`, which is finite by
hypothesis; and `M / N` — the image of `M` in `A / N` — is the range of
`P ↦ m • P mod N`, a homomorphism killing `k A`, hence a quotient of
`A / kA` and finite too.  A group with a finite subgroup and a finite
quotient by it is finite. -/
theorem finite_quotient_nsmul_mul {A : Type*} [AddCommGroup A] {m k : ℕ}
    (hm : Finite (A ⧸ (nsmulAddMonoidHom m : A →+ A).range))
    (hk : Finite (A ⧸ (nsmulAddMonoidHom k : A →+ A).range)) :
    Finite (A ⧸ (nsmulAddMonoidHom (m * k) : A →+ A).range) := by
  classical
  haveI := hm
  haveI := hk
  have hle : (nsmulAddMonoidHom (m * k) : A →+ A).range
      ≤ (nsmulAddMonoidHom m : A →+ A).range := by
    rintro _ ⟨P, rfl⟩
    exact ⟨k • P, by simp [smul_smul]⟩
  set N : AddSubgroup A := (nsmulAddMonoidHom (m * k) : A →+ A).range with hNdef
  set M : AddSubgroup A := (nsmulAddMonoidHom m : A →+ A).range with hMdef
  set K : AddSubgroup A := (nsmulAddMonoidHom k : A →+ A).range with hKdef
  set φ : A →+ (A ⧸ N) := (QuotientAddGroup.mk' N).comp (nsmulAddMonoidHom m) with hφdef
  have hker : K ≤ φ.ker := by
    rintro _ ⟨P, rfl⟩
    have hmem : ((m * k) • P : A) ∈ N := ⟨P, rfl⟩
    have h0 : ((((m * k) • P : A) : A ⧸ N)) = 0 := (QuotientAddGroup.eq_zero_iff _).mpr hmem
    simpa [hφdef, smul_smul] using h0
  have hsub : ((M.map (QuotientAddGroup.mk' N) : AddSubgroup (A ⧸ N)) : Set (A ⧸ N))
      ⊆ Set.range (QuotientAddGroup.lift K φ hker) := by
    rintro y ⟨x, ⟨P, rfl⟩, rfl⟩
    exact ⟨QuotientAddGroup.mk P, rfl⟩
  haveI : Finite (M.map (QuotientAddGroup.mk' N)) :=
    Set.Finite.to_subtype ((Set.finite_range _).subset hsub)
  haveI : Finite ((A ⧸ N) ⧸ M.map (QuotientAddGroup.mk' N)) :=
    Finite.of_equiv _ (QuotientAddGroup.quotientQuotientEquivQuotient N M hle).symm.toEquiv
  exact Finite.of_addSubgroup_quotient (M.map (QuotientAddGroup.mk' N))

/-- **Weak Mordell–Weil at every `n ≠ 0` follows from weak Mordell–Weil at
every prime** (PROVEN).

Induct on the prime factorisation of `n` using
`finite_quotient_nsmul_mul`, with `finite_quotient_nsmul_one` as the base
case.  `n ≠ 0` is load-bearing and cannot be dropped: `A / 0·A = A`, which
is infinite for every abelian variety of positive rank. -/
theorem finite_quotient_nsmul_of_prime {A : Type*} [AddCommGroup A]
    (hp : ∀ p : ℕ, p.Prime → Finite (A ⧸ (nsmulAddMonoidHom p : A →+ A).range))
    (n : ℕ) (hn : n ≠ 0) :
    Finite (A ⧸ (nsmulAddMonoidHom n : A →+ A).range) := by
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    rcases eq_or_lt_of_le (Nat.one_le_iff_ne_zero.mpr hn) with h1 | h1
    · rw [← h1]; exact finite_quotient_nsmul_one
    · obtain ⟨p, hpp, hpd⟩ := Nat.exists_prime_and_dvd (by omega : n ≠ 1)
      obtain ⟨q, rfl⟩ := hpd
      have hq0 : q ≠ 0 := by rintro rfl; simp at hn
      have hp2 : 2 ≤ p := hpp.two_le
      have hqlt : q < p * q :=
        calc q = 1 * q := (one_mul q).symm
        _ < p * q := Nat.mul_lt_mul_of_lt_of_le (by omega) (le_refl q) (Nat.pos_of_ne_zero hq0)
      exact finite_quotient_nsmul_mul (hp p hpp) (ih q hqlt hq0)

/-! ## The Kummer reduction of weak Mordell–Weil

Weak Mordell–Weil is `A(K) / nA(K)` finite.  Its classical proof
(Silverman, *AEC* VIII.1) never argues about that quotient directly: it
builds the **Kummer map**, which turns an element of the quotient into a
cochain on the Galois group, and then proves that only finitely many
such cochains occur.  The theorem below is the *reduction* — the step
that converts "finitely many cochains" into "finite quotient" — and it
is pure algebra: no fields, no schemes, no topology, no cohomology
theory.

The arithmetic of weak Mordell–Weil is entirely in the hypothesis
`hfin`, and this theorem carries none of it. -/

/-- **The Kummer reduction: `A / nA` is finite as soon as only finitely
many Kummer cochains occur** (PROVEN) — Silverman, *AEC* VIII.1, in the
form the abelian-scheme development consumes.

The setting is the algebraic skeleton of the classical argument.  `M`
plays the role of `A(K̄)`, `Γ` of the Galois group, `act` of the Galois
action, and `ι` of the inclusion `A(K) ↪ A(K̄)`:

* `hact` — `act σ` is subtractive.  It is all that is used of the action:
  no group law on `Γ`, no action axioms, no continuity.  (`Γ` is not even
  assumed to be a group, precisely to make that visible.)
* `hzero`, `hadd` — `ι` is additive.  Bundling `ι` as an `A →+ M` in the
  statement would force every caller to build the bundled map first; the
  two field equations are what a functor-of-points producer actually has
  in hand.
* `hinj` — `ι` is injective, i.e. `A(K) → A(K̄)` loses nothing.
* `hfix` — **Galois descent**: an `act`-invariant element of `M` comes
  from `A`.  Together with `hinj` this says `ι` identifies `A` with
  `M^Γ`; only the stated inclusion is used.
* `hdiv` — **divisibility**: every element of `ι '' A` is `n` times
  something in `M`.  Over an algebraically closed field this is
  surjectivity of the isogeny `[n]`.
* `hfin` — **the arithmetic**: only finitely many *Kummer cochains*
  `σ ↦ act σ Q - Q` (over all `P : A` and all `Q : M` with `n • Q = ι P`)
  occur.

**The argument.**  Choose, for each `P`, some `Q P` with `n • Q P = ι P`,
and let `c P` be its Kummer cochain.  If `c P = c P'` then
`act σ (Q P - Q P') = Q P - Q P'` for every `σ`, so by `hfix` the
difference is `ι a` for some `a : A`; applying `n •` and `hinj` gives
`P - P' = n • a`.  Hence `P ↦ c P` separates the cosets of `nA`, and
`A ⧸ nA` embeds into the finite set of cochains by sending a coset to the
cochain of a chosen representative.

**What this theorem is NOT.**  It is not weak Mordell–Weil: `hfin` is the
whole arithmetic input, and over a number field it is what the finiteness
of the class group and Dirichlet's unit theorem are for.  What is proven
here is that *nothing else* is needed — in particular no cohomology
theory, since a Kummer cochain is written down as a plain function and
the coboundary relation never has to be formed. -/
theorem finite_quotient_nsmul_of_kummerCochains
    {A : Type*} [AddCommGroup A] {M : Type*} [AddCommGroup M] {Γ : Type*}
    (n : ℕ) (act : Γ → M → M)
    (hact : ∀ (σ : Γ) (y z : M), act σ (y - z) = act σ y - act σ z)
    (ι : A → M) (hzero : ι 0 = 0) (hadd : ∀ a b : A, ι (a + b) = ι a + ι b)
    (hinj : Function.Injective ι)
    (hfix : ∀ y : M, (∀ σ : Γ, act σ y = y) → ∃ a : A, ι a = y)
    (hdiv : ∀ P : A, ∃ Q : M, n • Q = ι P)
    (hfin : {c : Γ → M | ∃ (P : A) (Q : M), n • Q = ι P ∧
      c = fun σ => act σ Q - Q}.Finite) :
    Finite (A ⧸ (nsmulAddMonoidHom n : A →+ A).range) := by
  classical
  set ιh : A →+ M := { toFun := ι, map_zero' := hzero, map_add' := hadd } with hιh
  set C : Set (Γ → M) := {c : Γ → M | ∃ (P : A) (Q : M), n • Q = ι P ∧
    c = fun σ => act σ Q - Q} with hC
  haveI : Finite C := hfin.to_subtype
  choose Q hQ using hdiv
  set c : A → (Γ → M) := fun P => fun σ => act σ (Q P) - Q P with hc
  have hcC : ∀ P : A, c P ∈ C := fun P => ⟨P, Q P, hQ P, rfl⟩
  have key : ∀ P P' : A, c P = c P' → P - P' ∈ (nsmulAddMonoidHom n : A →+ A).range := by
    intro P P' h
    have hfixed : ∀ σ : Γ, act σ (Q P - Q P') = Q P - Q P' := by
      intro σ
      have h1 : act σ (Q P) - Q P = act σ (Q P') - Q P' := congrFun h σ
      rw [hact]
      exact sub_eq_sub_iff_sub_eq_sub.mp h1
    obtain ⟨a, ha⟩ := hfix _ hfixed
    refine ⟨a, hinj ?_⟩
    show ι (n • a) = ι (P - P')
    have h2 : ι (n • a) = n • ι a := map_nsmul ιh n a
    have h3 : ι (P - P') = ι P - ι P' := map_sub ιh P P'
    rw [h2, ha, h3, ← hQ P, ← hQ P', nsmul_sub]
  set F : A ⧸ (nsmulAddMonoidHom n : A →+ A).range → C :=
    fun x => ⟨c (Quotient.out x), hcC _⟩ with hF
  have hFinj : Function.Injective F := by
    intro x y hxy
    have h : c (Quotient.out x) = c (Quotient.out y) := congrArg Subtype.val hxy
    have hmem : Quotient.out x - Quotient.out y ∈
        (nsmulAddMonoidHom n : A →+ A).range := key _ _ h
    have hmem' : -(Quotient.out x) + Quotient.out y ∈
        (nsmulAddMonoidHom n : A →+ A).range := by
      have := neg_mem hmem
      simpa [neg_sub, sub_eq_neg_add] using this
    have h2 : ((Quotient.out x : A) : A ⧸ (nsmulAddMonoidHom n : A →+ A).range)
        = ((Quotient.out y : A) : A ⧸ (nsmulAddMonoidHom n : A →+ A).range) :=
      QuotientAddGroup.eq.mpr hmem'
    calc x = ((Quotient.out x : A) : A ⧸ (nsmulAddMonoidHom n : A →+ A).range) :=
          (Quotient.out_eq x).symm
      _ = ((Quotient.out y : A) : A ⧸ (nsmulAddMonoidHom n : A →+ A).range) := h2
      _ = y := Quotient.out_eq y
  exact Finite.of_injective F hFinj

end Fermat
